### ISSUE TITLE
Iteration issue with option -keep_browser_open - invalid option / usage issue, see soln

### ISSUE THREAD

**Issue by Xuquansheng** [kelaberetiv/TagUI#1000]
Hello, Tagui team
  I'm trying to use tagui to create many user ids on my nextcloud. Browser closed after first iteration was successfully done, next iteration stopped. below are tag file, add_users.csv

c:\tagui_windows\tagui\src\tagui add_users_on_nextcloud1.tag add_users.csv -keep_browser_open

content of add_users_on_nextcloud1.tag 

if `[iteration]` equals to 1
      http://nextcloud.17tongx.com:8888/login
      type user as admin
      type password as ******
      click submit-form
      click add_users_1.png
      click add_users_2.png
      click New user

type newusername as `newusername`
type newdisplayname as `newdisplayname`
type newuserpassword as `newuserpassword`
click add_users_3.png
click `group`
click newsubmit

content of add_users.csv

#,newusername,newdisplayname,newuserpassword,group
1,user1,test_user1,12345678,group1
2,user2,test_user2,12345678,group2
3,user3,test_user3,12345678,group3

I tried -s option,  but need to add url addr and click New user before line type newusername as `newusername`, which slow dow process.

**Comment by PPJ-SolarTerms** [comment]
```
if [iteration] equals to 1
     http://nextcloud.17tongx.com:8888/login
     type user as admin
     type password as ******
     click submit-form
     click add_users_1.png
     click add_users_2.png
     click New user

type newusername as newusername
type newdisplayname as newdisplayname
type newuserpassword as newuserpassword
click add_users_3.png
click group
click newsubmit
```

**Comment by kensoh** [comment]
Hi @Xuquansheng can you try the following?

1. Use -s or -speed option
2. For the block of steps under the if iteration line, you have to indent (tab or spaces) to make all the lines belong to the condition and run only 1 time.

**Comment by Xuquansheng** [comment]
Hi, Kensoh
Before I raised the issue, I had tried both -s, -speed and -keep_browser_open option separately. For -s option, it can keep browser open, but leave website as blank, I need to add url http://nextcloud.17tongx.com:8888/settings/user and click New user in the iteration block, which slow down the process. For -keep_browser_open, it worked only for the first iteration, browser was closed before the second iteration. What I need this feature is : during iteration, keep browser open and keey url. By the way, no issue with the if iteration line, i indented. this is copy and paste issue here.

**Comment by kensoh** [comment]
Hi Quan Sheng, there is no `-keep_browser_open` option at all, it is an idea in discussion for now. I understand your scenario now, what you can do is see what is the latest URL before doing the 'repeated steps'. Then go to that URL before each repeated sequence. For example, https://github.com/aimakerspace/TagUI-Bricks/tree/master/IMDA-ICMS-CITREP#tagui-workflow

**content of add_users_on_nextcloud1.tag**
```
if [iteration] equals to 1
    http://nextcloud.17tongx.com:8888/login
    type user as admin
    type password as ******
    click submit-form
    click add_users_1.png
    click add_users_2.png
    click New user

// specify main page to go for subsequent iterations
// fill up with url that browser is at just before adding users
https://some_url

type newusername as newusername
type newdisplayname as newdisplayname
type newuserpassword as newuserpassword
click add_users_3.png
click group
click newsubmit
```
**content of add_users.csv**
```
#,newusername,newdisplayname,newuserpassword,group
1,user1,test_user1,12345678,group1
2,user2,test_user2,12345678,group2
3,user3,test_user3,12345678,group3
```

**Comment by kensoh** [comment]
By the way, we want to congratulate you on raising the 1000th issue for TagUI project! Issue #1 is more than 4 years ago.

Can I check with you how big is your team? I would like to personally buy coffee or tea (maybe Starbucks or whatever local coffee house you have at your city) for your team. I can transfer through PayPal. No limit on drink size or type 🎉

**Comment by Xuquansheng** [comment]
Thanks, Kensoh. We're an open source erp company, 5 people right now. Thanks for your kindness, no need to transfer through Paypal. We're happy to use Tagui for us and our clients. Thanks again.

**Comment by kensoh** [comment]
Sure Quan Sheng! Let us know more next time when you run into issues!

For GitHub issues here, we will try to reply within 24h, 365 days a year. There is also a Telegram group chat for the community which usually in a few hours some experienced users or us will reply (https://t.me/rpa_chat). Lastly, there is also a [weekly Zoom meeting](https://github.com/kelaberetiv/TagUI/issues/914) Thursday 4pm (UTC+8) for us to troubleshoot issues together with users.

We are now rapidly iterating on doing RPA directly from Microsoft Word and Excel, so this can be an option for your clients if they are not programmers and find it easier to use - https://github.com/kelaberetiv/TagUI/tree/master/src/office

Also, I have a personal project which is a popular Python wrapper for TagUI, so Python users can do RPA easily -
https://github.com/tebelorg/RPA-Python
