### ISSUE TITLE
Enhance select step to choose not only by option value, but also option text - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1001]
TagUI's select step helps users select options. The default design assuming best web design practices is to select using the `value` attribute. This is because `value` is the 'source-of-truth' that gets submitted when someone submits a form.

See this page from W3Schools on option value - https://www.w3schools.com/tags/att_option_value.asp

![Screenshot 2021-04-08 at 1 29 17 PM](https://user-images.githubusercontent.com/10379601/113973180-74e63300-986e-11eb-9e1b-7b24e057664a.png)

However, using value is non-intuitive for a non-developer user because 'value' is not something that is visible on the screen. Only text is visible. Furthermore, sometimes 'value' is some unique number that has nothing to do with the text of the option being selected. A TagUI workflow would be hard to understand in such situation what is being selected.

After thinking through, the best approach should be matching by value but should that fail, then match by text. It is not advisable to match by text first because 'value' is still the unique source-of-truth when submitting a form. But having this fallback should open up new use cases without causing problems for existing users use cases.

**Comment by kensoh** [comment]
Code enhancement implemented will let the following flow run correctly whether you give value or text.

```
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_option_value
frame iframeResult
    wait 1
    select cars as Volvo XC90
    wait 1
    select cars as Saab 95
    wait 1
    select cars as Mercedes SLK
    wait 1
    select cars as Audi TT
    wait 3
    select cars as volvo
    wait 1
    select cars as saab
    wait 1
    select cars as mercedes
    wait 1
    select cars as audi
    wait 3
```

**Comment by kensoh** [comment]
Above commit implements this enhancement. You can download the latest copy of TagUI with this fix and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this fix will become part of the packaged zip files. Thanks Novianto for suggesting this!

**Comment by noviantonugroho4** [comment]
> Above commit implements this enhancement. You can download the latest copy of TagUI with this fix and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip
> 
> In the next release, this fix will become part of the packaged zip files. Thanks Novianto for suggesting this!



Thank you so much for adding new feature select by text 🔥🔥🎉🎉🎉

**Comment by kensoh** [comment]
Thanks Novianto for raising this!! :D

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0
