### ISSUE TITLE
User workflows and demos, to place on GitHub homepage etc for sharing - WIP

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1003]
*source - telegram chat*

**Comment by kensoh** [comment]
https://github.com/lookang/TagUI

**Comment by kensoh** [comment]
https://github.com/nived00015/Tagui-Chatbot

**Comment by kensoh** [comment]
[Rahul Gupta](https://www.linkedin.com/in/rahul-gupta-robotics/), based in Pune India, has took a big step forward to create demos of TagUI / RPA for Python leveraging on ML models (through API services or locally hosted models). Putting a note here to recognise his initiative and to share his demos here + LinkedIn, until a proper place to share demos is created.

**Comment by kensoh** [comment]
Adding on to this train of thought,

I would imagine if TagUI has some form of 'packages' system like Python's pypi.org or JavaScript's NPM, that would be an efficient way for the community to create, share, install and leverage on the earlier work of others. 

For eg instead of pip install some_package it can be tagui install xero to get access to some Xero package someone creates for TagUI with a few commonly used workflows already created and users just need to provide the parameters (which month report to download, what type of report etc).

**Comment by marcelocecin** [comment]
https://pipedream.com/docs

**Comment by kensoh** [comment]
Added @nived00015's amazing Voice assisted RPA - https://www.linkedin.com/posts/nived-n-776470139_rpa-tagui-automation-ugcPost-6805844345904857088-tC8Y

**Comment by kensoh** [comment]
AI Singapore website is launching a community forum page soon, maybe that could be the home for easy sharing.

That website would be for all AI Singapore's projects and topics, but each project will have its own section.

To assess after the page is launched.

**Comment by kensoh** [comment]
The community page on AI Singapore website is planned to be launched by end of July.

We'll see if some other platform is needed in the interim, then consider setting up.

**Comment by kensoh** [comment]
https://github.com/lookang/TagUI/tree/main/SLS_assessment_automation

**Comment by kensoh** [comment]
Closing issue because the community website has been launched. The thread for user workflows showcase is -

https://community.aisingapore.org/groups/tagui-rpa/forum/discussion/workflows-showcase-from-users/

**Comment by kensoh** [comment]
Attaching TagUI Interview Report by NIPA - [2021 GIP_글로벌인터뷰_싱가포르_인공지능(AI)_TagUI.pdf](https://github.com/kelaberetiv/TagUI/files/6868537/2021.GIP_._._.AI._TagUI.pdf)

**Comment by kensoh** [comment]
Attaching TagUI Interview Report by Korea's National IT Industry Promotion Agency - [NIPA - TagUI Interview.pdf](https://github.com/kelaberetiv/TagUI/files/6868543/NIPA.-.TagUI.Interview.pdf)

**Comment by kensoh** [comment]
Attaching TagUI Interview Report by Korea's National IT Industry Promotion Agency - [NIPA_TagUI.pdf](https://github.com/kelaberetiv/TagUI/files/6868556/NIPA_TagUI.pdf)
