### ISSUE TITLE
Alt+D keyboard short for current date is not working - pending reply on suggestion

### ISSUE THREAD

**Issue by Srijit686** [kelaberetiv/TagUI#1005]
Hi 

I want to enter the current date in the below fields by using the keyboard shortcut Alt+D.
But this command is not working at all.
Could you please suggest to me how to specify the current date in these fields.
![image](https://user-images.githubusercontent.com/81609262/114259473-36bc5100-99df-11eb-9ccc-bd2d1734978e.png)

Thank
Srijit

**Comment by ruthtxh** [comment]
Hi @Srijit686 

You can write javascript code in TagUI and leverage on the javascript date function.
