### ISSUE TITLE
Create a VS code extension for TagUI - Subhas Malik has created beta release

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1007]
Subhas has created beta release. Extension on Visual Studio Marketplace -
https://marketplace.visualstudio.com/items?itemName=TagUisupport.tagui-support

**Comment by kensoh** [comment]
Closing for now, Subhas has been quiet, I hope things are ok for him.

Now he's in India and there is a widespread wave of covid.

**Comment by kensoh** [comment]
Subhas has created beta release -
https://www.linkedin.com/posts/kensoh_hi-vs-code-folks-who-love-rpa-now-you-can-activity-6805445134034042880--PWT

**Comment by kensoh** [comment]
CC Subhas @subhasmalik on this issue for users to feedback, for time being until project is public

**Comment by subhasmalik** [comment]
Thanks Ken, I am following here.

**Comment by Anujpalu24** [comment]
I have added the VS extension and added the all related .tagui script in new project and having below concerns :

Concern 1  :
I have added the VS extension and tired to run the .tag script but it is showing below prompt :

![Debugging Tagui](https://user-images.githubusercontent.com/89205899/137090180-31b584de-4368-4868-a6e4-097b5a0265d4.png)

I have then added a configuration and select environment as chrome but still not able to run my .tag script.

Concern 2 :  So after above i tried to run the script using terminal available in VS code but it showing me below error :

![Terminal](https://user-images.githubusercontent.com/89205899/137090286-ca4b6731-6fce-4668-9bd5-150af968bb37.PNG)


Concern 3 : I have some scripts which are working with skiuli and added all images in VS project but not sure how to call tehm in my script.

Please help me with the above concerns.

**Comment by kensoh** [comment]
For 1, let's see what @subhasmalik says.

For 2, this looks like a powershell terminal. Can you try running tagui command from command prompt terminal? I'm assuming in your normal command prompt you have already added the tagui\src folder into your PATH env variable.

For 3, can you attach one of your SikuliX scripts here? Doing visual automation is as easy as click image1.png

**Comment by kensoh** [comment]
Hi @Anujpalu24, 

2. Can you check that you are using normal command prompt instead of powershell? After that you can take screenshot of error message to share here

3. You can put images in the same folder as the .tag file. And automate this way - click image.png

**Comment by Anujpalu24** [comment]
@kensoh :  

For issue 2 : With normal command prompt things are working but when trying same from VS code terminal it is not working.

For issue 3 : I have kept the file and images in same folder and things are working with normal command prompt  but not sure how to run the same using VS code.

So i think subhas Malik can help us out here.

**Comment by kensoh** [comment]
Have you tried opening command prompt instead in VS Code instead of PowerShell?

https://stackoverflow.com/questions/46107955/open-cmd-in-the-visual-studio-code-terminal

**Comment by kensoh** [comment]
Above screenshot looks like PowerShell, it is different from normal command prompt.

**Comment by Anujpalu24** [comment]
@kensoh : Yes now things seems to be working for issue 2. Thank you for providing help.

Please help me with issue 1 and issue 3. Like wanted to give a demo to my team. 
Tried many things but not able to run the .tag file using VS code run feature.

**Comment by Anujpalu24** [comment]
@subhasmalik @kensoh  : Please help me with running the .tagui script using VS code, i am still not able to run the same.

Please provide any document for the same.

**Comment by Anujpalu24** [comment]
@ruthtxh : will try the same again and let you know

**Comment by Anujpalu24** [comment]
@ruthtxh  : I have already added the path to environment variable but still not able to run the same. Is it possible to record an video how you are doing the setup and running the cases from VS code.
![image](https://user-images.githubusercontent.com/89205899/145199244-2a98b9da-3b38-472f-9427-311ffcd3e8c1.png)

Please help me out

**Comment by Anujpalu24** [comment]
@ruthtxh  : Any update on the same

**Comment by ruthtxh** [comment]
Hi @Anujpalu24, sorry for the delayed reply.

Then perhaps this could be due to powershell not being able to invoke the tagui command, see https://stackoverflow.com/questions/20938389/powershell-snapin-cmdlet-commandnotfoundexception for some ideas to troubleshoot. I suggest you can run it from command prompt instead in the meantime?

**Comment by kensoh** [comment]
Hi @subhasmalik, writing down some notes from our meeting. On possible VS Code command palette -

```
Run workflow normally
tagui filename.tag

Run workflow in turbo mode
tagui filename.tag -turbo

Run workflow without browser
tagui filename.tag -nobrowser

Deploy workflow as a shortcut
tagui filename.tag -deploy
```

**Comment by kensoh** [comment]
Copy @ruthtxh fyi on some ideas to add to VS Code command palette.

Let us know if you have some thoughts to add or iterate.

**Comment by Anujpalu24** [comment]
@kensoh  @ruthtxh  : Any update over why test script is not working from VS code, From cmd prompt option of VS code things seems to working but not from Run option of VS code :  

![image](https://user-images.githubusercontent.com/89205899/149338441-86970d42-47be-4343-95bd-3f3c34a6a98c.png)

**Comment by kensoh** [comment]
Copying both @ruthtxh and @subhasmalik

**Comment by Anujpalu24** [comment]
@kensoh @subhasmalik @ruthtxh  : Any update on the same?

**Comment by kensoh** [comment]
Closing issue since no further updates / inputs, and the VS Code extension and credit are already linked from readme.
