### ISSUE TITLE
How to simplify checking if an element is present before acting on it?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#101]
Raising this from an user email for sharing, as other users might benefit from this question.

---

1. If there a way to simplify checking of whether an element is present before acting on it?

```
if present('(//*[text()="Awards: "]/../../div)[2]')
{
read (//*[text()="Awards: "]/../../div)[2] to awards
}
```

2. If not, in the future version, would be great if you can add one more command read_if_present. With this new command, for the last one "awards", instead of that 4 lines, we can simply write:
```
read_if_present (//*[text()="Awards: "]/../../div)[2] to awards
```

This would be very helpful if there are many optional elements.

**Comment by kensoh** [comment]
For 1, yes -

instead of writing this -
```
if present('(//*[text()="Awards: "]/../../div)[2]')
{
read (//*[text()="Awards: "]/../../div)[2] to awards
}
```

try this - 
```
if present('(//*[text()="Awards: "]/../../div)[2]')
read (//*[text()="Awards: "]/../../div)[2] to awards
```

or if repository is used -
```
if present('`identifier`')
read `identifier` to awards
```

For 2, I'll skip that, otherwise once I add that for each tagui step, there will be a corresponding step_name_if_present and step_name_if_visible and it will be pretty hard to maintain the core code base. Ie sacrifice resources for future improvements into maintaining hard to maintain redundancies. Above 3 example should be very simplified already for normal use cases.

**Comment by adegard** [comment]
HI, I don't know why this is not working...

https://www.kijiji.it/offerte-di-lavoro/cerco-lavoro-servizi/badante/?entryPoint=sb
wait 5
element_identifier = '#search-result > li:nth-child(INDEX) > div > h4'
for i from 3 to 19
{
	URLSelector = element_identifier.replace("INDEX", i);
	
	if present('+URLSelector+')
	fetch '+URLSelector+' to link
	print  '+link+'
}

=> error: "Can't find variable link"

Any idea?

**Comment by kensoh** [comment]
Hi @adegard, try below code. The reason is present() is already a function, so if you are calling a variable you can directly use present(URLSelector).

```
https://www.kijiji.it/offerte-di-lavoro/cerco-lavoro-servizi/badante/?entryPoint=sb
wait 5
element_identifier = '#search-result > li:nth-child(INDEX) > div > h4'
for i from 3 to 19
{
        URLSelector = element_identifier.replace("INDEX", i);

        if present(URLSelector)
        fetch '+URLSelector+' to link
        print  '+link+'
}
```

**Comment by adegard** [comment]
ok, thank you!
