### ISSUE TITLE
Unable to run "tagui\flows\samples\1_google.tag" - maybe miss out tagui command?

### ISSUE THREAD

**Issue by merubinsan** [kelaberetiv/TagUI#1015]
encounter error message:
this file does not have an app associated with it for performing this action. Please install an app, or if one is already installed, create an association in the Default Apps Settings page.

**Comment by kensoh** [comment]
Hi @merubinsan you may have miss out the tagui command in the installation steps.

tagui c:\tagui\flows\samples\1_google.tag

https://tagui.readthedocs.io/en/latest/setup.html

**Comment by merubinsan** [comment]
Thanks Ken.
Before running the tagui command, need to use the Terminal.
This may be silly.
but I do not know how to "Hold Command and press spacebar" in the following step:
"Hold Command and press spacebar, then type Terminal and press Enter."
Appreciate your advice.
Many thanks!

**Comment by kensoh** [comment]
Hi @merubinsan I assume you are using macOS, there is a 'command' key on your keyboard just left of your space bar. If you press and hold on the command key, and press space you can get a popup to search. Then you are open Terminal. Let me know if you run into other blockers!

**Comment by merubinsan** [comment]
Thanks Ken.
My bad.
am using Windows.
Let me start over, on the installation steps.
Many thanks for your prompt advice.

**Comment by kensoh** [comment]
@merubinsan I see, no probs!

Here's the link for Windows (for other users to read too)
https://tagui.readthedocs.io/en/latest/setup.html#windows

There is a weekly Zoom at Thursday 4pm Singapore time, if you run into any questions
[Link to Zoom meeting URL](https://github.com/kelaberetiv/TagUI/issues/914)

There is a Telegram group where you can post questions too
https://t.me/rpa_chat

**Comment by merubinsan** [comment]
Thanks!
After re-installing, it worked :)
