### ISSUE TITLE
Access to id/item in iframe/frame - you can do this with frame step, see examples

### ISSUE THREAD

**Issue by Flipsand** [kelaberetiv/TagUI#1016]
Hello. First of all thanks for that nice tool. I am new and willing to learn and had first success using it. Now i can't get any further because i want to access some part in an iframe. I get the XPath but when i want to read it i get the info cannot find.

The full XPath is:
/html/body/div/div/div/div/div/div/margin-container/full-container/div[2]/margin-container/full-container/div/div[1]/div/div[1]/svg/g[2]/svg/text
The Xpath is:
//*[@id="ember44"]/svg/g[2]/svg/text
If i do a 
read //*[@id="ember44"]/svg/g[2]/svg/text to test
i get a  ERROR - cannot find //*[@id="ember44"]/svg/g[2]/svg/text message.

All id's in iframe are not accessible this way. I tried alot but can't get any further.

**Comment by kensoh** [comment]
Hi @Flipsand thanks for trying out TagUI and learning how to use it!

Oh frames are generally headaches. To access elements within a frame, you can use the `frame` step. You can also access elements within a subframe within a frame. More details in below documentation URL. Try and let me know how it goes!

```
frame name or id
    click element1
    type element2 as some text
```

https://tagui.readthedocs.io/en/latest/reference.html#frame

**Comment by Flipsand** [comment]
Hi kensoh. I looked for me at some example using the frame element. It worked for my example and so i can go doing more stuff trying out and learning.  What is most important for me in the beginning is to look after making an indentation if needed, doing the ->`variable`<- with ` (ASCII CODE 96), splitting some strings and so on. So thanks for your fast response and help....i'll try more out with this nice tool :)
