### ISSUE TITLE
type identifier as xxx@moe.gov.sg [enter], [enter] not working? - resolved using keyboard

### ISSUE THREAD

**Issue by lookang** [kelaberetiv/TagUI#1018]
Dear ken,
I think the [enter] doesn't work properly as [enter] on the keyboard.
Is there a fix?

I read this https://github.com/kelaberetiv/TagUI/issues/370
but the [enter] doesn't trigger a keyboard [return] on the Mac? When I press on the real physical keyboard, it is triggered correctly. So maybe I need some help.
Thanks!

My new flow is here
https://github.com/lookang/TagUI/blob/main/share/share.tag

**Comment by kensoh** [comment]
Hi Lawrence, normally for webpages the [enter] will still work, for example below.

```
https://google.com
type q as singapore[enter]
```

But in some cases, the webpage design does not take a virtual 'enter' keypress as valid and ignore that input. For the workflow, do you have a minimal replication script that can reproduce that issue and I can take a look with no user account?

Most likely it is that webpage can't take that input. Or it could be the target to receive that key is a child or parent. If cant take input then will have to consider simulating a real key press with keyboard step or any other ways to proceed to next step?

**Comment by lookang** [comment]
Dear Ken,
What is the command for
"simulating a real key press with keyboard step "?

**Comment by kensoh** [comment]
Dear Lawrence, a likely reason is because your Chrome browser is not in focus or your textbox is not in 'real' focus.

For below step,
```
type /html/body/div[3]/div[2]/div/div[2]/div[1]/div[3]/div[1]/div/div[1] as xxx@moe.gov.sg[enter] 
```

Try changing it to
```
click chrome_icon.png
type email_textbox.png as xxx@moe.gov.sg
keyboard [enter]
```
or
```
click chrome_icon.png
type email_textbox.png as xxx@moe.gov.sg[enter]
```
And see if that works. Above first clicks on the Chrome icon on your macOS dock bar, typing into the textbox using computer vision and then entering it. Using web automation, although a click seems to make the textbox in focus, it may not really be in focus as far as the OS layer is concerned.

Yes Zoom would be great, if above doesn't work, will you be available on Thursday btw 4-5pm? We have a weekly Zoom call to work with users 1-to-1 on these things. This is the link to the [Zoom meeting URL](https://github.com/kelaberetiv/TagUI/issues/914). Hopefully above suggestions will work!

**Comment by lookang** [comment]
i followed your instruction
i created a chrome_icon.png
<img width="28" alt="chrome_icon" src="https://user-images.githubusercontent.com/20143558/115580289-882ae100-a2f9-11eb-8d37-48d0712029ac.png">
i saved the in /Users/lookang/Desktop/tagui/flows/lookang/20210318/
which is the same to the flow file.
But the error message in cmd is 
click chrome_icon.png
ERROR - cannot find /Users/lookang/Desktop/tagui/flows/lookang/20210318/chrome_icon.png on screen

**Comment by kensoh** [comment]
Hi Lawrence, is it that you have a high-res Retina mac display? There is a known issue. On Mac laptops with Retina display, the Mac snapshot tool will create an image that is double the size of what is shown on the screen. This causes image to be incorrect and unable to find a match. For such laptops, need to either resize it down or use another snapshot tool.

[More details on this and the solution](https://github.com/tebelorg/RPA-Python/issues/170#issuecomment-823063368)

**Comment by kensoh** [comment]
Later at 4pm today, if you happen to be available, you can join us at the [weekly Zoom call](https://github.com/kelaberetiv/TagUI/issues/914 ) to troubleshoot together.

Zoom meeting URL - https://nus-sg.zoom.us/j/85847222905?pwd=bm9yb3R2NEZEVnRPZ0ZKdjJ0d1VhZz09

**Comment by lookang** [comment]
Thanks, Ken, for your guidance. It is working now.
https://github.com/lookang/TagUI/tree/main/share
The updated and working files are kept here.

**Comment by kensoh** [comment]
Thanks Lawrence! For time being, I track your sharings here - https://github.com/kelaberetiv/TagUI/issues/1003

Will figure out a way to make community sharings more accessible!
