### ISSUE TITLE
Log files are not generating - create empty tagui_logging file in tagui\src folder

### ISSUE THREAD

**Issue by dhruthi-t** [kelaberetiv/TagUI#1021]
Hi Ken,

Could you please point me to any document/issue related to Logging.

I have created the tagui_logging.txt file in my src folder but none of the files for debugging are generated after execution.

Thanks in advance

**Comment by kensoh** [comment]
Hi @dhruthi-t the file to be created is tagui_logging, not tagui_logging.txt

https://tagui.readthedocs.io/en/latest/advanced.html?highlight=tagui_logging#create-log-files-for-debugging

Other than above log files, some log files for TagUI integrations such as Chrome, SikuliX, Python etc, are automatically captured for the latest run.
