### ISSUE TITLE
Chrome session timeout when downloading large files - pending more details

### ISSUE THREAD

**Issue by prachi71** [kelaberetiv/TagUI#1022]
Hi

Thank you for this wonderful tool. Is there a way to specify a chrome session timeout. We are automating the download of large files and are running into session timeouts.

Thank You

**Comment by kensoh** [comment]
Hi @prachi71 can you tell me more what you mean by Chrome session timeout? The usual way to handle this will be trying to replicate how you manually change this timeout, then ask RPA tool to do the same steps to change this timeout.

**Comment by pkumar-rt** [comment]
Hi Ken,

Thank you for your prompt response. We were getting a prompt from Chrome , saying that the session would timeout unless we cancelled the timeout. However since we added the -speed and -h option and it seems to finish through the file download. I will recreate the session timeout dialog and post back here for future reference. 

Thank You

**Comment by prachi71** [comment]
Hi Ken,

Thank you for your prompt response. We were getting a prompt from Chrome , saying that the session would timeout unless we cancelled the timeout. However since we added the -speed and -h option and it seems to finish through the file download. I will recreate the session timeout dialog and post back here for future reference.

Thank You

**Comment by kensoh** [comment]
Oh great! I'm happy to hear that you have found a possible workaround. Sure, if you can take a screenshot that will be useful.

First we need to figure out whether the timeout message is from Chrome or from the website. Then can decide next steps.

If from Chrome, need to check any Chrome settings to disable or use computer vision to click away.

If from website, need to check any settings on that website to disable timeout, or use web automation or computer vision.
