### ISSUE TITLE
Run RPA on Internet Explorer in the background - seems not doable with TagUI

### ISSUE THREAD

**Issue by AaronMarki** [kelaberetiv/TagUI#1023]
Hello,
I installed this tool for the first time today.
I have no knowledge of this language and I have some difficulties.

If possible, get help, I'll explain what I need to do:

1 - Launch a web link that includes in the link, user and pass. (ok, this i saw how to do it, but in chrome, i need to open it with IE)

2: After login, Open a new link, which directly launches the extraction of an excel file.
(this link, after a few seconds of waiting, presents the save popup)

3: Save the .csv file with a specific name.

Know if there is an option to do all the steps in the background, without iterating on the monitor.

End..  
I don't know if I wrote in the right place.

Can someone help me?

**Comment by kensoh** [comment]
Hi Aaron, the short answer to above seems to be no. TagUI can't automate on IE without running on foreground on the screen.

You can join our Telegram group chat to share more on your use case and I can also comment more any other ways.

https://t.me/rpa_chat

You can also join our weekly [Zoom 1-to-1 call](https://github.com/kelaberetiv/TagUI/issues/914) to discuss more any other ways to get to the outcome you want.

**Comment by kensoh** [comment]
Closing issue for now, though TagUI can run on Microsoft Edge in the background without monitor (headless mode) -

https://github.com/kelaberetiv/TagUI/issues/946
