### ISSUE TITLE
Unable to locate and launch file in local drive - pending replication details from user

### ISSUE THREAD

**Issue by merubinsan** [kelaberetiv/TagUI#1024]
Hi Ken,
am trying to launch pdf file from c:\drive or d:\drive.
but failed.

Objective: take snapshot of pdf, post in WhatsApp and send via Chatgroup.

Appreciate if you can advise.

Many thanks!
Mel

**Comment by marcelocecin** [comment]
try to place the pdf in the same folder as the script tag file

**Comment by kensoh** [comment]
Thanks Marcelo!

Hi Mel, can you share your workflow code here?

Your scenario sounds doable. There are many ways to open PDF file using TagUI. For eg using the run step to use Windows start command to open a file, use dclick step to double-click on a file icon on desktop to open etc..

**Comment by merubinsan** [comment]
Thanks!
after re-installing, it worked :)

**Comment by merubinsan** [comment]
Pai seh.
Closed wrong issue.
This one still open.
As requested, Ppls see below the code:

_// This flow logins to WhatsApp Web, send snapshots of tables to chatgroups

// Launch pdf file
dclick D:/1VCs.pdf

// move mouse cursor away to prevent blocking of PDF report,
// else there is a popup tooltip on macOS blocking browser
hover (0,0)

// resize table
keyboard [cmd]-

// capture screenshot of VC statistics table,
// subjected to change if report format changes,
// and depends on the window position on the PC.
snap (163,340)-(1307,815) to VC.png

// First, visit https://web.whatsapp.com/
https://web.whatsapp.com/

// open WhatsApp to send statistics table to chatgroup
// Look on the web page for an element with 'type a message' in its text, id or name
// paste table
js clipboard('https://web.whatsapp.com/')
keyboard [cmd]v
keyboard [enter]

// paste email subject to Add a caption: field
js clipboard('Apr: vaccinated at VCs')
keyboard [cmd]v
keyboard [tab]

// Wait 3 seconds so the page can load
wait 3_

**Comment by kensoh** [comment]
I assume that you mean the error happens at

```
dclick D:/1VCs.pdf
```

This looks wrong. dblick can double-click on an image of an icon on the desktop. But it doesn't double click on the PDF file with this name, even if it is visible on the screen. Can you try if something like below works?

```
run cmd /c start d:/1VCs.pdf
```

**Comment by merubinsan** [comment]
Thanks Ken!
yes, the error happened at dclick D:/1VCs.pdf
your proposed code worked beautifully :)
