### ISSUE TITLE
Chrome cannot read or write to its data directory: chrome\tagui_user_profile - to check

### ISSUE THREAD

**Issue by kalyangadgil** [kelaberetiv/TagUI#1029]
Dont know whether fault in my code or some other issue.

**Comment by ruthtxh** [comment]
Hello @kalyangadgil 

Can you share more on your workflow/code and how the issue occurs? Thanks!

**Comment by kalyangadgil** [comment]
Hello @ruthtxh 

Issue is solved now.
Go to the chrome folder .
Give full access to user of chrome folder.
I added user named Everyone and gave full access.

![img](https://user-images.githubusercontent.com/40426939/117271071-77d94100-ae77-11eb-99da-78e0da9b0c6b.png)

**Comment by kensoh** [comment]
Thanks @kalyangadgil and @ruthtxh !

Hi @kalyangadgil can you do a search for tagui_user_profile folder inside that Chrome folder? If TagUI is working properly the folder created should be inside the directory where you unzip tagui, under tagui\src\chrome folder. Your feedback will help to identify if there is some bug which is missed, then we can work on a permanent fix for you and future users.

**Comment by kalyangadgil** [comment]
Hii @kensoh 

Yes. I searched for the folder under tagui\src\chrome and It is there.
And I am using tagui VERSION 6

Thank you!!

![img_tagui](https://user-images.githubusercontent.com/40426939/117407875-cd235a00-af2c-11eb-83e9-9ba2d318b475.png)

**Comment by kensoh** [comment]
Thanks @kalyangadgil! How about inside C:\Program Files (x86)\Google\Chrome folder? Is there a tagui_user_profile folder somewhere within that folder? Because the solution that worked for you is changing folder permissions for this folder, and that somehow fixes the problem. But TagUI shouldn't be saving the tagui_user_profile folder there.

**Comment by kalyangadgil** [comment]
@kensoh 
Yes. I have found tagui_user_profile in this folder C:\Program Files (x86)\Google\Chrome\Application\chrome.

![taguiimg](https://user-images.githubusercontent.com/40426939/117532258-2a3e0f00-b004-11eb-8492-066da98166a6.png)

**Comment by kensoh** [comment]
Thanks @kalyangadgil for your inputs! We'll check more on our end. From above screenshot it looks like for some reason TagUI is creating folder there instead of in c:\tagui (when I compare the last modified dates above).

**Comment by kensoh** [comment]
For mine, the Chrome folder in Program Files does not have the tagui_user_profile. Most probably is the limited permission at where tagui folder is placed. In any case, adding a commit above that adds a Chrome fallback if the user can't install Chrome system-wide for all users but only for a particular user.
