### ISSUE TITLE
Does not work in certain folders - pending replication details, likely permissions issue

### ISSUE THREAD

**Issue by owenttttt01** [kelaberetiv/TagUI#1032]
I am trying to make a vulnerability scanner website with RPA demonstrations. I am able to run the scripts in another folder without any problems. As this is a group project, we moved all the codes to a shared VM folder that links to Github so that all of us have access. However, some TagUI codes started returning error messages such as "TagUI stopped unexpectedly". Does any one have an idea why this is happening? Thanks.

**Comment by kensoh** [comment]
Hi @owenttttt01 thanks for raising this! I've not come across other users who have raised a similar issue. Can you share more on your VM folder setup? For example, can you tell me exactly how you run the TagUI flow files? And what is the minimum replication script that can consistently reproduce the error?

Also, create an empty tagui_logging file in tagui/src folder. It will help to retain the execution logs which you can share here for more details. Depending on how the error happens, I may ask you for more logs (eg tagui_chrome.log, or Python or SikuliX logs) to explore further the cause.

**Comment by kensoh** [comment]
Adding on to above, with the limited info provided, the best guess now is some permissions issue for certain folder which the running user is unable to let the TagUI process read / write to those folders.

**Comment by kensoh** [comment]
Closing for now until further inputs!
