### ISSUE TITLE
How to change Chrome download directory, added new download to step - done

### ISSUE THREAD

**Issue by beefstew151** [kelaberetiv/TagUI#1035]
hi, anyone know how to change the directory of the downloaded file from the scripts?
I want to save my file into shared folder.

**Comment by kensoh** [comment]
Hi @beefstew151, you can use this 1-line inside TagUI workflow to change the location - https://github.com/kelaberetiv/TagUI/issues/567#issuecomment-531472830

**Comment by kensoh** [comment]
```
maybe a good solution is have a helper function

download_folder('some directory') to set location
location = download_folder() to get the location

this way, users can also know what's the current download folder

which defaults to the workflow folder
```

**Comment by kensoh** [comment]
>helper function if want to enabled 20+ languages also need some effort to add, because will need to run Google engine to generate and then update the dictionaries. but it is less effort than normal TagUI steps.
>
>i'll also review if it make sense to add this to replace current download step

**Comment by beefstew151** [comment]
> ```
> maybe a good solution is have a helper function
> 
> download_folder('some directory') to set location
> location = download_folder() to get the location
> 
> this way, users can also know what's the current download folder
> 
> which defaults to the workflow folder
> ```

thanks.. this will work

**Comment by kensoh** [comment]
Thanks @beefstew151, I'll also review if replacing the current download step is possible. For eg

```
download to c:\downloads
```
vs
```
download_folder('c:\\downloads')
```

But if it is a function it has additional benefit of returning current folder to download.

**Comment by kensoh** [comment]
Above commit adds this. Users can download the latest copy of TagUI with this and unzip to overwrite existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files.

**Windows**
```
download to c:\temp
```

**macOS/Linux**
```
download to /tmp
```

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0

**Comment by kensoh** [comment]
Improved `download to` step to handle such scenarios where \u is used. See more info at #1110.

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update.

For list of changes since TagUI v.6.46 release in mid-June, see this (link also found at TagUI installation page) -
https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+
