### ISSUE TITLE
Is element is visible in webpage (not just existing) until timeout, add appeared() - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1036]
*source - Telegram*

**Comment by kensoh** [comment]
Checking for visible() instead of present() in a webpage is rarely used. Thus there is no function to wait for timeout like exist() for present(). Below is an appeared() function which runs the visible() check until timeout of default 10 seconds.



[appeared.zip](https://github.com/kelaberetiv/TagUI/files/6525546/appeared.zip)

**Comment by kensoh** [comment]
Users can put the tagui_global.js to tagui/src directory so all flows can access the appeared function, or put tagui_local.js to some directory so all flows in that directory can access the appeared function. Users can also add on their custom functions.

**Comment by kensoh** [comment]
With the appeared() function, following works -

```
https://google.com
if appeared('//*[@name="q"]')
    echo works
else
    echo oops
```

**Comment by kensoh** [comment]
Thought just add to TagUI standard helper functions. Since the cost is minimal, additional 2 lines of code for function definition.

Above commit implements this. You can download the latest copy of TagUI with this fix and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files.

**Comment by marcelocecin** [comment]
it works
thanks @kensoh

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0
