### ISSUE TITLE
How to login once and repeat automation process many times? - use iteration to check

### ISSUE THREAD

**Issue by EslamGitHub** [kelaberetiv/TagUI#1037]
First I would like to thank you so much for your effort creating TagUI tool. I would like to be able to access a system with my credential and then repeat getting an image for each recorder. I wasn't able to do so since I can only repeat the records only, but still I need to access the website for once and not on every record. Can you help me with this?? 

Regards,

**Comment by kensoh** [comment]
Hi Eslam,

Thank you for sharing your appreciation. We are happy to know that the tool can be helpful.

If you are referring to using [datatable csv file](https://tagui.readthedocs.io/en/latest/advanced.html#datatables) to do batch automation, you can use a condition to detect whether it is the first record, so that login is done 1 time only.

```
if `[iteration]` equals to 1
    // do login steps

// do the real work here
```

See this for the complete example -
https://github.com/aimakerspace/TagUI-Bricks/tree/master/IMDA-ICMS-CITREP#tagui-workflow

PS - You can use -speed option to avoid restarting web browser for each record and no 3 sec delay between records.

---

Let me know if above helps or if you are doing batch automation in another way without datatable csv.

Lastly, feel free to join the TagUI group chat to ask any questions, there are other expert users there who will often share their experiences if a question asked is something they have come across - https://t.me/rpa_chat

**Comment by kensoh** [comment]
(in the next release, it will be `if iteration equals to 1` - https://github.com/kelaberetiv/TagUI/issues/953#issuecomment-846855456)

**Comment by EslamGitHub** [comment]
Thank you for the prompt reply Kensoh, the solution somehow worked but there is an issue with the reload the page that I need to put the page link for every load and revisit and adjust it to be able to extract the data that I'm looking for

```
if [iteration] equals to 1
    // do login steps
   // do the first record
else
visit the same page again
// do the other records
```

What I found is that, I can use array but I'm not that expert in Javascript coding but here is the code that worked and exactly do the thing that I'm looking for
```
array_items = ["KIA", "Volvo", "BMW", "Skoda", "Corolla", "TATA", "Mitso"]
csv_file = 'cif_list.csv'
load `csv_file` to lines
array_lines = lines.split('\n')
http://www.google.com
for (n=0; n<array_lines.length; n++)
	{
		itm = array_items[n]
		type Search as [clear]`itm`[enter]
		//echo `itm`
	}
for (n=0; n<array_lines.length; n++) 
	{
		echo `array_lines`
	}
```
Even after I finish doing my job then I can easily sign out.

My only issue is that how to load my CSV file into an array and work with it?

I found this [link](https://rpa-sg.org/TagUI-Tips-Techniques/how-to-read-a-csv-file-part-1-single-column.php) but, it's not working.

Thank you so much for your help.

**Comment by kensoh** [comment]
Oh I see, for the first way of checking iteration count, you can do something like this. By using -speed option the browser will not restart. However, this works if the URL for starting the actual work (after login) is the same for each run. It should be.

```
if `[iteration]` equals to 1
    // go to website URL
    // do login steps
    // do the first record

// put URL here that is the starting URL for this part
// do the other records
```

**Comment by kensoh** [comment]
For accessing array from CSV, you can do something like below. The idea is to split the line again using , as the separator. But ideally use the first method so that you don't have to do a lot of JavaScript just to read and use the data from array.

demo.tag
```
load data.csv to data_csv
  
array_lines = data_csv.split('\n')

for (n=0; n<array_lines.length; n++)
    array_elements = array_lines[n].split(",")
    for (m=0; m<array_elements.length; m++)
        echo `array_elements[m]`
```

data.csv
```
#,name,town
1,Rick,Budapest
2,Tammy,London
3,Pui,Bangkok
```

output
```
START - automation started - Tue May 25 2021 09:48:44 GMT+0800 (+08)

load data.csv to data_csv
#
name
town
1
Rick
Budapest
2
Tammy
London
3
Pui
Bangkok

FINISH - automation finished - 1.3s
```

**Comment by EslamGitHub** [comment]
I've tried the later solution I felt it will do the job, but I got one issue is that there's an [enter] character because of it I can't snap a screenshot and save it with .png

**Comment by EslamGitHub** [comment]
The ONLY issue is that I got those strange error that I can't save the file to PNG file. Otherwise the process is working find if I changed the value somehow. Please help me with it.

![issue_1](https://user-images.githubusercontent.com/25060415/119509393-e6bc0280-bd70-11eb-894c-b586d517525e.PNG)
![issue_2](https://user-images.githubusercontent.com/25060415/119509397-e885c600-bd70-11eb-9e02-b931edb9769d.PNG)

**Comment by EslamGitHub** [comment]
I found a work around for this issue (new line character) but just reading the data from the record and use as a file name.
![issue_3](https://user-images.githubusercontent.com/25060415/119642971-8e8e0a80-be1b-11eb-8589-c737c7b65c05.PNG)

**Comment by kensoh** [comment]
Hi Eslam, oh great! Can you share the part of your workflow script that has the issue, and the script after your fix?

Then I can comment on whether there are other ways around the issue which you can consider for use next time.

**Comment by EslamGitHub** [comment]
Sorry for the late reply.
Here is the syntax that I used to login once and repeat many without reset/refresh the link

```
echo --------------[STEPS USED FOR ONCE]--------------
//Load the CSV file here
csv_file = 'csv_list.csv'

//Extract the data
load `csv_file` to data_csv
echo CSV data is (`data_csv`)

//Split the lines to use them as steps
array_lines = data_csv.split('\n')
echo array is (`array_lines`)

//Show the length of the steps
len = array_lines.length
echo the length is (`len`) steps

//Access the page
https://www.google.com

echo --------------[START THE REPEATED STEPS FROM HERE]--------------
//Repeat the steps for each record
for (n=1; n<array_lines.length; n++)
	{
		car = array_lines[n].split(",")
		type Search as [clear]`car`[enter]
		echo The caption is (`car`)
	}
```

**Comment by kensoh** [comment]
Hi Eslam, no probs. I see.. For your code using JavaScript array, I don't have anything to suggest to make it easier. The only thing is from v6 onwards, users can also do code blocks by indenting using tab or a few spaces, instead of using {}.

```
for n from 1 to array_lines.length-1
    itm= array_lines[n].split(",")
    type Search as [clear]`itm`[enter]
    echo The caption is (`itm`)
```

From your now working code, I can't infer the original code that could have led to the strange issue on saving file to .png, but let us know again if you run into any issues! Feel free to post on Telegram if that's easier.
