### ISSUE TITLE
TagUI hangs, AVG Internet Security false-positive for tagui_chrome.php - whitelisted now

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1044]
I was alerted by my colleague that AVG Anti-virus / Internet Security started detecting tagui_chrome.php as a threat and deleting it to move to Quarantine. This will hang TagUI on startup because the file is needed to establish a websocket connection to Chrome to automate it. Have registered and pending a whitelisting account from AVG to file a report.

In the meantime, AVG users experiencing TagUI hangs on start-up can follow the steps below to add whitelist exception. If you are using both TagUI in human language and Python package version, note that there are 2 tagui_chrome.php files to be added to exception because the Python version runs a forked version of TagUI and is installed to a separate folder.

![image](https://user-images.githubusercontent.com/10379601/120292190-aae7e680-c2f6-11eb-9c38-49903c976d24.png)

![image-2](https://user-images.githubusercontent.com/10379601/120292201-ade2d700-c2f6-11eb-82b9-f43992b2f9fd.png)

![image-3](https://user-images.githubusercontent.com/10379601/120292208-b0453100-c2f6-11eb-8c48-ae9c51fbb1c8.png)

**Comment by kensoh** [comment]
Completed whitelisting submission, advised to check back a few days later by scanning file again -
https://support.avast.com/en-us/article/160?option=ftpwhitelisting

**Comment by marcelocecin** [comment]
https://www.youtube.com/watch?v=LtiBhAOO2r8&t=334s
