### ISSUE TITLE
Elements not found issue, while using click actions - see this working example

### ISSUE THREAD

**Issue by fazlur10** [kelaberetiv/TagUI#1047]
When i tried a flow with https://www.gumtree.com.au/, actions for clicking certain elements worked sometimes, while sometimes element not found error occured. How can i tackle this.? I have used Xpath of elements as identifiers for all actions.

**Comment by kensoh** [comment]
Hi @fazlur10 can you share your example workflow here?

The most common cause for this is if the website has randomly generated webpage structure and attributes like id / name / class etc. So when you click on a working XPath, the next time it run may not be there. If that's the case, finding a stable anchor that doesn't change and then point to the children of that will work.

By default, TagUI will auto-wait for 10 seconds for the element to appear before throwing error not found.

**Comment by fazlur10** [comment]
this is the workflow, it would be great help if you could help me to find
out a way to extract the product links in this particular page aswell

**Comment by kensoh** [comment]
Hi @fazlur10 your reply has no attachment or additional info on the workflow.

**Comment by fazlur10** [comment]
https://github.com/fazlur10/TagUIFlow.git

**Comment by kensoh** [comment]
Here's a working example, base on how the website is rendered to Singapore users -

```
https://www.gumtree.com.au/s-teapot/k0?categoryRedirected=true
product = count('//*[@class="user-ad-collection-new-design__wrapper--row"]//a')
for item from 1 to product
    show (//*[@class="user-ad-collection-new-design__wrapper--row"]//a)[`item`]
    show (//*[@class="user-ad-collection-new-design__wrapper--row"]//a/@href)[`item`]
```

**Comment by kensoh** [comment]
The class you used not suitable, too many fake and wrong results. Above use something that is fixed, then specify the child and grandchildren `a` nodes with //a

**Comment by fazlur10** [comment]
Thank you, I will do that.

**Comment by fazlur10** [comment]
actually i want to run this automation every 1hour, and check if any new
products are uploaded in particular url:
https://www.gumtree.com.au/s-car-seats/wyndham/c20097l3001743?price=__30.00,
and if new products are uploaded, an email should be sent on the list
products. Can you help me with this?

**Comment by kensoh** [comment]
Hi @fazlur10 this is possible but not easy to do. So it's outside of support scope, [read more on TagUI usage here](https://tagui.readthedocs.io).

You will have to think through how to do it by collecting list of existing products. Then schedule a job to run and compare with existing list. Then you send email by using computer vision to control your desktop or web email program.

**Comment by kensoh** [comment]
You can also try posting to the Telegram group chat here https://t.me/rpa_chat to see if someone from the community can do it for you. You can share the requirements and budget to see who is able to take up the development.

**Comment by fazlur10** [comment]
Thanks, I'll check it out.

**Comment by fazlur10** [comment]
Finally i have done it my self. Thanks for helping me throughout
