### ISSUE TITLE
Retrieving array - use case sounds like working with array using JS, best is google

### ISSUE THREAD

**Issue by fazlur10** [kelaberetiv/TagUI#1051]
how can i add an retrieve an array by extracting data from a website and pushing it into an array
Code is as follows
https://www.gumtree.com.au/s-car-seats/wyndham/c20097l3001743?price=__30.00
product = count('//*[@class="user-ad-collection-new-design__wrapper--row"]//a')
array_web_links = []
for item from 1 to product
 read (//*[@class="user-ad-collection-new-design__wrapper--row"]//a/@href)[`item`] to link
 productrow = ['https://www.gumtree.com.au/'+link]
 write `productrow` to array_web_links
read array_web_links to web_links
write web_links

Pls help me out with this to add productrow into an array and write it back

**Comment by kensoh** [comment]
Hi @fazlur10 is it that you want to create an array? What do you want to do with array?

If you want to write to CSV then there is no need to use array, see example below -

https://tagui.readthedocs.io/en/latest/reference.html#csv-row

**Comment by fazlur10** [comment]
i dont need to add to csv, i just want to know how to add to an array and
echo it back

**Comment by kensoh** [comment]
Oh I see, for this you can google to find out how to do.

This is JavaScript usage, there are better resources on teaching JavaScript.

TagUI can write human language steps but can use JavaScript in its workflow files. Working with array is JavaScript code.

**Comment by fazlur10** [comment]
👍

**Comment by fazlur10** [comment]
array.push(input) is not working, following error occurs
cannot understand step array_web_links.push('+productrow+')

**Comment by kensoh** [comment]
You can try using the following
```
// with js in front to tell TagUI this is JavaScript code
js array_web_links.push(productrow)
```
```
// with ; behind to let TagUI know this is JavaScript code
array_web_links.push(productrow);
```
