### ISSUE TITLE
Adding array to email - see example earlier and this JavaScript example of using array

### ISSUE THREAD

**Issue by fazlur10** [kelaberetiv/TagUI#1054]
how can we add an array of values to email body.
I have an array of links extracted from web. How can i send them as an email?
Sample code
https://www.gumtree.com.au/s-car-seats/wyndham/c20097l3001743?price=__30.00
product = count('//*[@class="user-ad-collection-new-design__wrapper--row"]//a')
array_web_links = []
for item from 1 to product
 read (//*[@class="user-ad-collection-new-design__wrapper--row"]//a/@href)[`item`] to link
 productrow = ['https://www.gumtree.com.au/'+link]
 js array_web_links.push(productrow)
https://mail.google.com/mail/u/0/
click Compose
type To as sfazlurrahmanrs@gmail.com
type Subject as New Products List
type //*[@id=":ss"] as array_web_links[]
click Send

**Comment by kensoh** [comment]
Following is an example of how to send email, it is using visual automation - https://github.com/kelaberetiv/TagUI/issues/1052#issuecomment-855872330

In JavaScript, you need to use array_web_links.toString() to convert array to text before using it in TagUI step -

```
a = ['1','2']
echo `a.toString()`
```

**Comment by fazlur10** [comment]
thank you, by the way how can we overwrite a csv file?
I should delete existing content and write the new one

**Comment by fazlur10** [comment]
But how can i add that array to message body
Following step don't work out
js var email_links = `arrayUnique.toString()`
type ***@***.***=":ss"] as email_links

**Comment by kensoh** [comment]
Oh to overwrite you can do `dump `''` to abc.csv` to erase it or for the first line use dump to overwrite that file.
```
type ***@***.***=":ss"] as `arrayUnique.toString()`
```

**Comment by fazlur10** [comment]
Thank you

**Comment by fazlur10** [comment]
other than 'wait', is there any way to perform actions when only an element
is found?

**Comment by fazlur10** [comment]
i want add elements of an array in each row when inputting into a text
field. How can i make it to the following code, if i add js and declared
var ts =  arrayUnique.join("<br>"), them while entering into a text field,
variable ts not found error occurs
ts = arrayUnique.join("<br>")
enter ***@***.***=":sv"]//div as `ts`

**Comment by kensoh** [comment]
You can try below see which one works -
```
ts = arrayUnique.join("[enter]")
ts = arrayUnique.join("\n")
```

**Comment by fazlur10** [comment]
Thanks, it worked.
