### ISSUE TITLE
dont html tags work in js codes of tagui?

### ISSUE THREAD

**Issue by fazlur10** [kelaberetiv/TagUI#1055]
I want to enter array elements in each rows in an element, How can i do it other than below. In below br is not recognized. So output come along with br
sample:
arrayUnique = ["12","14"]
js begin
var ts = arrayUnique.join("<br>")
function generateVar() {
val = ts
}
js finish
generateVar();
enter //*[@id=":sv"]//div as `val`

**Comment by kensoh** [comment]
I think you ask in the previous issue and I answered - https://github.com/kelaberetiv/TagUI/issues/1054#issuecomment-856897654

Closing this issue.
