### ISSUE TITLE
Comparing two arrays and getting the uniques elements of first array - resolved

### ISSUE THREAD

**Issue by fazlur10** [kelaberetiv/TagUI#1057]
I have two arrays made of extracting some links from a web page and extracting from an csv file. I have to make a unique array with elements that are unique in first array(array_web_links) that are not available in second(array_csv). 
Following method give me correct output
array1 = ['https://www.gumtree.com.au//s-ad/point-cook/car-seats/mothers-choice-car-seats/1275605213','https://www.gumtree.com.au//s-ad/point-cook/car-seats/mother-choice-booster/1275583974','https://www.gumtree.com.au//s-ad/point-cook/car-seats/booster-seat-hipod/1275528143']
array2 = ['https://www.gumtree.com.au//s-ad/point-cook/car-seats/mothers-choice-car-seats/1275605213','https://www.gumtree.com.au//s-ad/point-cook/car-seats/mother-choice-booster/1275583974','https://www.gumtree.com.au//s-ad/point-cook/car-seats/booster-seat-hipod/1275528143']
array3 = []
js array3 = array1.filter(function(obj) { return array2.indexOf(obj) == -1; });
for (n=0; n<array3.length; n++)
 echo `array3[n]`

But for the following example above method do not work, where all the elements of first array (array_web_links) are added into unique array
https://www.gumtree.com.au/s-car-seats/wyndham/c20097l3001743?price=__30.00
product = count('//*[@class="user-ad-collection-new-design__wrapper--row"]//a')
array_web_links = []
array_csv = []
for item from 1 to product
 read (//*[@class="user-ad-collection-new-design__wrapper--row"]//a/@href)[`item`] to link
 productrow = ['https://www.gumtree.com.au/'+link]
 js array_web_links.push(productrow)
load product.csv to lines_csv
array_lines_csv = lines_csv.split('\n')
for (n=0; n<array_lines_csv.length; n++)
 array_items_csv = array_lines_csv[n].split(',')
 for (m=0; m<array_items_csv.length; m++)
  js array_csv.push(array_items_csv[m])
arrayUnique = []
js arrayUnique = array_web_links.filter(function(obj) { return array_csv.indexOf(obj) == -1; });
for (n=0; n<arrayUnique.length; n++)
 echo `arrayUnique[n]`

Please help me to solve this

**Comment by kensoh** [comment]
Hi @fazlur10 are you saying you tried above method which works but in your automation it does not work?

What is the error you have and what is not working?

**Comment by fazlur10** [comment]
if i run the above method as a single automation it works, but incase with
my scenario, when i run it actually no error comes, but the unique values
of first array not added to third array as element, instead all the
elements of first array are added to third array(unique array)

**Comment by kensoh** [comment]
Your JavaScript code looks correct. Can you try to print out the values of the array_web_links and array_csv and see if you get more clues? The only reason I can think of is the array_csv, the values maybe have some special characters or quotation marks that make the comparison not working correctly and treat every item as unique.

**Comment by fazlur10** [comment]
while using echo to display both arrays, output of both arrays are as shown
in attachment echo output.png.
Output of array_csv elements is row by row, while output of
array_web_elements are together. How can I make the output of array_csv
look similar to array_web_links or vice versa?

Still if i print the arrays an error not found occurs as shown in
attachment print.png

array_web_links = []
array_csv = []
for item from 1 to product
 read
***@***.******@***.***)[`item`]
to link
 productrow = ['https://www.gumtree.com.au/'+link]
 js array_web_links.push(productrow)
load product.csv to lines_csv
array_lines_csv = lines_csv.split('\n')
for (n=0; n<array_lines_csv.length; n++)
 array_items_csv = array_lines_csv[n].split(',')
 for (m=0; m<array_items_csv.length; m++)
  js array_csv.push(array_items_csv[m])
arrayUnique = []
js arrayUnique = array_web_links.filter(function(obj) { return
array_csv.indexOf(obj) == -1; });
print `array_web_links`
print `array_csv`

**Comment by fazlur10** [comment]
this is the product.csv file

**Comment by kensoh** [comment]
none of the attachments can be seen on the github issue

**Comment by fazlur10** [comment]
please check now

**Comment by fazlur10** [comment]
hello,
Have found the issue and sorted it, anyways thanks for the help.
The reason was that the array formed from csv data was storing it elements
as objects in the array while the other was not.

**Comment by kensoh** [comment]
Hi @fazlur10 oh great, and congratulations on creating this pretty complex automation!!
