### ISSUE TITLE
How to schedule TagUI flow? - use -deploy option and Windows Task Scheduler

### ISSUE THREAD

**Issue by fazlur10** [kelaberetiv/TagUI#1059]
How can we schedule a tagui flow with task scheduler of windows? Which program should be chosen to reccur the flow?

**Comment by kensoh** [comment]
Hi @fazlur10 you can run TagUI with -deploy option, this will generate the file that you can point to in Task Scheduler -

https://tagui.readthedocs.io/en/latest/reference.html#deploy-or-d

**Comment by fazlur10** [comment]
thank you

**Comment by kensoh** [comment]
Btw feel free to post questions at Telegram group, if it is easier. Users can post any questions there and me and other experienced users will answer. https://t.me/rpa_chat

**Comment by fazlur10** [comment]
okay
