### ISSUE TITLE
TagUI does not recognize variables when expecting for string - outdated syntax used

### ISSUE THREAD

**Issue by malbicomp** [kelaberetiv/TagUI#1063]
No matter the quoting I try TagUI just see variables like string literals instead of variables when it is expecting for a string parameter (shoud accept variables).

I'm trying to do this:
1-Running TagUI for a csv file this way from shell:
  tagui my_autom.tag data/data_file.csv -h

2- here, the csv file content (header plus 3 lines of data):
projeto,bolsa,nome
proj1,voluntario,marcelo
proj2,caps,joao
proj3,fapeam,guilherme

3- So it runs the following code:
if bolsa equals to 'fapeam'
	echo fapeam
else
	echo nao fapeam
	echo 'bolsa'
	echo '+bolsa+'

4- the 3 outputs respectively I get for each iteration:
(Iteration 1):
 nao fapeam
 'bolsa'
 '+bolsa+'

(Iteration 2):
nao fapeam
'bolsa'
'+bolsa+'

(Iteration 3):
fapeam

TagUI is not using the variable as a variable consistently, so.. I realy tryed to solve it but I'm stuck..
What could be?
I'm using a updated Ubuntu last LTE version.. everything installed following https://tagui.readthedocs.io steps.

Please help this newby..

**Comment by kensoh** [comment]
Hi @malbicomp sorry for the trouble! The syntax for quoting variables is the backtick symbol ` for eg

```
a = 'abc'
echo `a`
```

So the syntax for your example would be -
```
if bolsa equals to 'fapeam'
	echo fapeam
else
	echo nao fapeam
	echo `bolsa`
```

Can you share more how you ended up trying out '++' or ''? All existing documentation has been updated over a year ago to use backticks for variables, including object repository and datatable. It might be some external tutorial or reference. For example, below echo step in documentation is using backtick.

https://tagui.readthedocs.io/en/latest/reference.html#echo

**Comment by malbicomp** [comment]
Hello again Mr. Soh (Mr. @kensoh). Sorry for my disappearance. My fault in answer so many days after.
I read your answer as soon as you reply. And... I remembered when, surrendered after hours trying to track some code files, looking for some clue about any kind of setup I could be missing in my environment.. well again.. :face_with_head_bandage: 
I realized I was just confusing backticks (\`variable\`) with single quotes ( 'just literals' ) :facepalm:... I read the right reference too.. but.. with... tired eyes...
So, I apology to have '+blamed+' TagUI... :face_with_thermometer:  what if issue's title changes to 'tired eyes mistakes'(kidding) becouse.. TagUI \`ROCKS!!!!\` :v: 

Everything runs fine right now... :+1: :+1: :+1:

**Comment by kensoh** [comment]
Hi @malbicomp no probs at all, take your time! Great to hear your feedback that it runs ok now 😄

Hope you have fun using the tool, there is a recent release of MS Word plug-in v3 which can make it even easier to use - https://github.com/kelaberetiv/TagUI#do-rpa-with-microsoft-word

And if you are someone familiar with Python programming, you can check out the Python version of TagUI - https://github.com/tebelorg/RPA-Python
