### ISSUE TITLE
Permission denied in macOS setup instructions - updated instructions to include sudo

### ISSUE THREAD

**Issue by jpdemas** [kelaberetiv/TagUI#1064]
Hello I'm in the process of installing.  After I type into Terminal:  'ln -sf /your_tagui_path/tagui/src/tagui /usr/local/bin/tagui' I get the message Permission denied.

I enabled Java and terminal in Accessibility.  What else could it be?

**Comment by kensoh** [comment]
Hi @jpdemas thanks for your feedback! Can you try if the following works?

```
sudo ln -sf /your_tagui_path/tagui/src/tagui /usr/local/bin/tagui
```

In the meantime, I have update documentation to include the `sudo` command in front. Sudo command is used to run a command as root user. I believe for most users this would be required, so I've added this now as standard installation steps.

**Comment by jpdemas** [comment]
The command worked.  I then tried the next line in the install instructions: "tagui /your_tagui_path/tagui/flows/samples/1_google.tag"

The response was "command not found: tagui"

**Comment by kensoh** [comment]
Oh the part on `/your_tagui_path` you have to replace with where you install TagUI

In step 6 - https://tagui.readthedocs.io/en/latest/setup.html#macos-linux

For eg, maybe you unzip to your desktop, it will be following (change to your user id)

```
sudo ln -sf /Users/your_user_id/Desktop/tagui/src/tagui /usr/local/bin/tagui

tagui /Users/your_user_id/Desktop/tagui/flows/samples/1_google.tag
```

**Comment by chengwhynot** [comment]
Hi. I got same error "permission denied". The ln command finished smoothly, but tagui ... reports permission denied.

attached terminal cmds.

``` cmd

(base) admin@bogon tagui % pwd
/Users/admin/Downloads/apps/tagui
(base) admin@bogon tagui % 
(base) admin@bogon tagui % sudo ln -sf /Users/admin/Downloads/apps/tagui /usr/local/bin/tagui
Password:
(base) admin@bogon tagui % tagui /Users/admin/Downloads/apps/tagui/flows/samples/1_google.tag 
zsh: permission denied: tagui
(base) admin@bogon tagui % sudo tagui /Users/admin/Downloads/apps/tagui/flows/samples/1_google.tag
sudo: tagui: command not found
(base) admin@bogon tagui % tagui
zsh: permission denied: tagui
```

**Comment by ruthtxh** [comment]
Hi @chengwhynot, can you try the following?
```
sudo ln -sf /Users/admin/Downloads/apps/tagui/src/tagui /usr/local/bin/tagui
```

**Comment by chengwhynot** [comment]
> Hi @chengwhynot, can you try the following?
> 
> ```
> sudo ln -sf /Users/admin/Downloads/apps/tagui/src/tagui /usr/local/bin/tagui
> ```

thank you for your suggest, 
I've ln to tagui/src/tagui, but still not working...

<img width="896" alt="ln-tagui" src="https://user-images.githubusercontent.com/1076902/157584152-7eecaa73-2053-4ca8-b481-669de729820e.png">

**Comment by chengwhynot** [comment]
Solved.
I've removed old tagui link in /usr/local/bin/, then relink it from /Users/admin/Downloads/apps/tagui/src/tagui
now it works.

Thank you @ruthtxh
