### ISSUE TITLE
Cannot click on image using computer vision - pending checks on requirements & setup

### ISSUE THREAD

**Issue by qassimnasir** [kelaberetiv/TagUI#1067]
It could not find the picture at all in below example ( also tried different ones), any help or should I need to install any

// visit IRAS website (for managing taxes in Singapore) 
https://www.iras.gov.sg/irashome/default.aspx

// bring Chrome web browser to foreground to be in focus,
// for subsequent steps to click visually on UI elements
click chrome_icon.png

// increase timeout from default 10 seconds to 300 seconds
// to let user sign in, including using 2FA authentication
timeout 300

// log in to personal income tax using visual automation,
// instead of specifying XPath or other web identifiers
// that natively interact with web browser's backend
click login_menu.png
click mytax_option.png
click personal_button.png

**Comment by lookang** [comment]
Try to run Tagui on primary monitor. Computer vision works only on primary monitor, I think.
Good luck

**Comment by kensoh** [comment]
Adding on to @lookang's reply, @qassimnasir here are a few things to check -

1. Have you install OpenJDK here (required for computer vision) - https://tagui.readthedocs.io/en/latest/setup.html
2. If you are using secondary monitor, try dragging your Windows taskbar to the screen you want to automate on
3. You'll need to take image snapshots on your laptop for above images, what I take on my mac laptop may be different
4. For macOS Retina display, run this at the start to fix snapshot resolutions `vision Settings.AlwaysResize = 0.5`
