### ISSUE TITLE
Click is not working for images - closing issue duplicated with #1067

### ISSUE THREAD

**Issue by qassimnasir** [kelaberetiv/TagUI#1068]
Click is not working for images , I use example below

// This automation flow downloads a document from IRAS
// and uses OCR to extract information from the document.
// Accounting firms can do this at scale to download and
// automate part of their business processes for clients.

// visit IRAS website (for managing taxes in Singapore) 
https://www.iras.gov.sg/irashome/default.aspx

// bring Chrome web browser to foreground to be in focus,
// for subsequent steps to click visually on UI elements
//click chrome_icon.png

// increase timeout from default 10 seconds to 300 seconds
// to let user sign in, including using 2FA authentication
//timeout 15

// log in to personal income tax using visual automation,
// instead of specifying XPath or other web identifiers
// that natively interact with web browser's backend
click login_menu.png
click mytax_option.png
click personal_button.pn

**Comment by kensoh** [comment]
closing issue duplicated with #1067
