### ISSUE TITLE
Numeric keypad emulation for the keyboard function - use vision step type() command

### ISSUE THREAD

**Issue by tuncK** [kelaberetiv/TagUI#1072]
Thank you very much for your hard work, I really appreciate your RPA library.

Is it possible to add a feature to emulate keystrokes to the numeric keypad portion of the keyboard? To clarify, I realise that certain applications distinguish between hitting the "-" key located above the letters vs. the "-" key on the numeric keypad. My understanding is TagUI currently only supports the former case.

**Comment by kensoh** [comment]
Thanks @tuncK you're welcome! We hope to make RPA and digital automation accessible to more people.

TagUI has a keyboard step to do keyboard special keys, combination keys, or low-level key presses -
https://tagui.readthedocs.io/en/latest/reference.html#keyboard

However for the numpad area there is no special mapping now. You can either of below to send such keys. Using single quotes or double quotes for text strings, while using Key.SPECIAL_CHARACTER to access and use your numpad keys. vision step lets user sends custom commands to SikuliX engine, which is doing the backend work for keyboard step and visual automation.

```
vision type("testing " + Key.NUM0 + " testing " + Key.MINUS + " some more keys ")

OR

vision type('testing ' + Key.NUM0 + ' testing ' + Key.MINUS + ' some more keys ')
```

The full list of numpad keys are -
```
NUM0, NUM1, NUM2, NUM3, NUM4, NUM5, NUM6, NUM7, NUM8, NUM9, SEPARATOR, ADD, MINUS, MULTIPLY, DIVIDE
```

For all the other keys you can refer to the documentation link above which already covers the other keys.

**Comment by kensoh** [comment]
In the future, if this becomes a bigger usage pattern by more users, we can add native support to keyboard step.

Otherwise it will add clutter and maybe confusion to most users if the documentation has a distinction of why there are special keys needed for numpad when there are the same keys in the main keyboard.
