### ISSUE TITLE
telegram step to send notifications, hosting reference implementation on my VPS - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1073]
To setup, look up [@taguibot](https://t.me/taguibot) on Telegram and click START button.

The bot will reply with your Telegram ID. Send notifications with -

```
telegram id message
```

I'm hosting this on my idle [VPS server](https://tebel.org) with https encryption, but [the source code](https://github.com/kelaberetiv/TagUI/tree/master/src/telegram) is on GitHub if you wish to host this feature on your own cloud or server. The implementation is in pure PHP without any dependencies. The only info logged is chat_id, length of the message, datetime stamp (to prevent abuse). If you wish to host on your own, first read through this link to learn more about Telegram Bot API, creating your bot API token and setting up the webhook - https://core.telegram.org/bots

**Comment by kensoh** [comment]
If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update.

Alternatively, you can manually unzip [this zip file](https://github.com/kelaberetiv/TagUI/archive/refs/heads/master.zip) to overwrite your existing TagUI installation. After unzipping, drag all the folders and files under TagUI-master\src to your existing tagui\src folder. This will apply this update to your TagUI.

**Comment by kensoh** [comment]
Done, usage guide here - https://tagui.readthedocs.io/en/latest/reference.html#telegram

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update.

Alternatively, you can manually unzip [this zip file](https://github.com/kelaberetiv/TagUI/archive/refs/heads/master.zip) to overwrite your existing TagUI installation. After unzipping, drag all the folders and files under TagUI-master\src to your existing tagui\src folder. This will apply this update to your TagUI.

**Comment by chooimail** [comment]
Hi,

Chooi here, and totally new to TagUI.
But have been using a Telegram bot with Node-red

Thus unfamiliar with webhooks and have no idea about hosting servers.
Can we edit something in the PHP file to use our own TG bot instead?

Target: At least using TagUI to send messages via the TG bot to myself

**Comment by kensoh** [comment]
Hi @chooimail, yes users can set to use their own Telegram bots and servers instead with the following line -
```
telegram_endpoint = 'your_server_endpoint'
```

The default server set by TagUI is
```
telegram_endpoint = 'https://tebel.org/taguibot'
```

Which is my own VPS server which my vendor claims to guarantee 99.9% uptime.

However, to run your own robots, you need to host a server in order to run your own Telegram bot. You can read more from this link here (which has link to Telegram docs on creating and hosting your own bots).

The essential steps will be hosting your own server, creating and setting up your Telegram bot, and modifying the the sample server source code to work for your Telegram bot.

https://tagui.readthedocs.io/en/latest/reference.html#telegram

Copying @ruthtxh

**Comment by kensoh** [comment]
Running your own Telegram bots will require you to know about webservers and webhooks and hosting / configuring them yourselves. This is a requirement from Telegram, as they do not provide free or paid cloud service to host robots for users. They are merely the registry of robots which you will have to tell them for your robot talk to which webserver you own.

**Comment by kensoh** [comment]
Closing since this change has made its way into the latest packaged release.
