### ISSUE TITLE
How to create my own "Recorder" for my Desktop Application? - check out OpenRPA

### ISSUE THREAD

**Issue by ace-rivera** [kelaberetiv/TagUI#1074]
Hello,

I know that there is a Chrome extension to record web applications using TagUI.
But I want to create my own to record desktop application actions as well as Web from an application I'm creating.

Is there a way for me to achieve this? Thank you!

**Comment by kensoh** [comment]
Hi @ace-rivera, your best bet will be checking out the source code of OpenRPA to see how that is done.

The open-source RPA tool can work with desktop apps on Windows and has a recorder to replay recorded actions.

https://github.com/open-rpa/openrpa

For TagUI, at the moment no desktop recorder but we will creating one in a couple of months time to capture image snapshots of desktop UI elements to automate processes on them.

**Comment by ace-rivera** [comment]
@kensoh, thank you so much. I'll check it out
