### ISSUE TITLE
run command not working (macOS) - pending checks and printing run_result

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#1075]
hi Ken
I installed pngquant on MacOS using the `brew install pngquant command`
now i'm trying to run the command inside the tag file
`run pngquant --quality=60-90 pag.png --ext e.png`
but nothing happens
I tested it on the terminal and it works normally
what can be happening?
thanks

**Comment by kensoh** [comment]
Hi Marcelo,

Can you try below to see what is the error message? Is the pngquant command available anywhere in the terminal?

By default the run process will happen in tagui/src folder as the working directory. Thanks for reporting this issue!

```
echo `run_result`
```

**Comment by marcelocecin** [comment]
hi Ken
including the full path of the image worked
`run pngquant --quality=60-90 /Users/rpa/tagui/flows/samples/pag.png --ext e.png`
thanks
