### ISSUE TITLE
Explore whether OCR-related steps can return a confidence score - pending

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1077]
https://sikulix-2014.readthedocs.io/en/latest/textandocr.html?highlight=confidence#accuracy-of-text-recognition-confidence

**Comment by kensoh** [comment]
Raising query to Raimund to confirm my initial findings - https://github.com/RaiMan/SikuliX1/issues/466

---

Hi Raimund,

A very good day to you. From below link it looks like `match.getScore()` will return the confidence level of a search.

https://sikulix-2014.readthedocs.io/en/latest/textandocr.html#accuracy-of-text-recognition-confidence

Following that line, there is `match.getText()` performed using SikuliX's implementation of Tesseract OCR.

May I check with you if my understanding is correct that there isn't a confidence output that can be returned as part of `match.getText()`? For example, given an image and this function returns 'Hello World', is there existing functionality to know the confidence level of this OCR parsing result 'Hello World'?

```py
# for example, let's say I want to get the OCR text from a region
ocr_text = Region(region_origin_x,region_origin_y,region_width,region_height).text()

# is there a way to know the 'confidence level' of ocr_text returned?
```

Thanks in advance for your time! No urgency on this and the other recent issue I raised.

**Comment by kensoh** [comment]
Raimund replied that he'll look into this in the next release.

TagUI is using older version of SikuliX though. The new version requires manual setup of Tesseract for Mac users. A possible solution may be for users who really need this feature to consider using a fork of TagUI that works with the new version, if there are codebase changes required for TagUI to work with the new version of SikuliX.

---

Sorry, but currently this is not a feature.

I will check this with version 2.0.6.
Thanks for the pointer.

**Comment by marcelocecin** [comment]
hi Ken
soon tesseract will be in version 5
https://github.com/tesseract-ocr/tesseract/releases

**Comment by kensoh** [comment]
Thanks Marcelo for the heads-up! Adding on below you other useful and related comment at issue https://github.com/kelaberetiv/TagUI/issues/916#issuecomment-889024370

---

hello Ken
just some instructions to install tesseract-3.05.02 on Ubuntu 18.04.5
```
wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/3.05.02.tar.gz
tar xzf 3.05.02.tar.gz
cd tesseract-3.05.02
./autogen.sh
./configure
make
sudo make install
sudo ldconfig
```
then download the tessdata from https://github.com/tesseract-ocr/tessdata and put at `/usr/local/share/tessdata` and check it running the command `tesseract --list-langs`

**Comment by kensoh** [comment]
Closing issue for now since this is pending on SikuliX roadmap
