### ISSUE TITLE
How to send a CLI parameter to flow - use p1 to p8 for parameters 1 to 8, see examples

### ISSUE THREAD

**Issue by evandeng2009** [kelaberetiv/TagUI#1078]
A flow wants to open an url but it needs to be sent by command line parameter, coz of it depends on which url I want to open.

Tried "p1" but not recoginzed. Also "url = p1 url" not work.

**Comment by kensoh** [comment]
Hi @evandeng2009 it might be because without http or https at start of line TagUI didn't detect that line as URL step.

Can you try if the following works for you? It works for me -

**demo.tag**
```
echo https://`p1`
```

**then run with**
```
tagui demo.tag google.com
```

**demo2.tag**
```
echo `p1` `p2` `p3` `p4` `p5` `p6` `p7` `p8`
```

**following should work too**
```
tagui demo.tag 1 2 3 4 5 6 7 8
```

**Comment by evandeng2009** [comment]
Thank you Kensoh. I've found 2 ways below:
1. Like you said, url as a parameter and flow reads it by `p1` to `p8`. The most important part is that explicitly tell flow the url starts with http or https, like this https://`url_variable`, while `url_variable` only not work even if url_variable's value does starts with https or http. This method has a defect that the url in CLI can not contain special char as shell terminal think. So
2. Save the url without http or https in a file and "load xx.file to url_variable", then http://`url_variable` or https://`url_variable`.

**Comment by kensoh** [comment]
Adding on, if you are open to using files, you can make use of object repository or datatable to do so.

In this way, you can even make the step as follows, because during code compilation the value is already inserted.

```
`url`
```

More info and examples - 

https://tagui.readthedocs.io/en/latest/advanced.html#object-repositories

https://tagui.readthedocs.io/en/latest/advanced.html#datatables

**Comment by evandeng2009** [comment]
Thank you, Ken.

**Comment by kensoh** [comment]
Above works by returning the website portion without the https:// and then use the https:// prefix to let TagUI know to handle this instruction as a URL instead of something else.
