### ISSUE TITLE
Errors tagui update and always opening headless - may be running from wrong folder

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#1079]
hi Ken
we are having two errors with TagUI
<img width="596" alt="" src="https://user-images.githubusercontent.com/2955762/125987268-5942a85a-77e9-4a05-9d54-92c3ac152b84.png">
the tagui update command is not being recognized
and when running a script, the browser is always being opened in headless mode
and when we open with python
it opens normally
<img width="810" alt="" src="https://user-images.githubusercontent.com/2955762/125987947-4059178e-2d5d-45cc-a9b7-8eea60199127.png">
we use the installation from here
https://tagui.readthedocs.io/en/latest/setup.html
thanks

**Comment by kensoh** [comment]
Hi Marcelo, double check that you have followed the steps in https://tagui.readthedocs.io/en/latest/setup.html and running the command at the right tagui folder where you installed. For RPA for Python, it will install to ~/.tagui folder.

The behaviour you describe is running the RPA for Python version. I maintain a fork of TagUI optimised for the RPA package. That one does not have tagui update command and will always run headless using PhantomJS by default. That one not meant to be run directly from command prompt.

To confirm you can type ./tagui command without parameters. TagUI now is at > v6.46 while the Python's TagUI is at v5.27.

**Comment by marcelocecin** [comment]
hi Ken, I deleted the contents of the folder created by Python and downloaded the latest version of TagUI and put it in the folder

**Comment by marcelocecin** [comment]
hi Ken, can't Python use the latest version of TagUI ?

**Comment by kensoh** [comment]
Oh nope, they went on separate development paths already, there are changes in TagUI human language that doesn't make sense and is bad for Python context.

However, for features relevant, I'll sync and add to Python version. But there will be some delay because I maintain the Python version in my personal time when I get some time.

**Comment by marcelocecin** [comment]
thanks for the explanation Ken, I'll try to put the two together then, use Python as the API server and pool with a single worker, and call TagUI to run the automations.  thanks.

**Comment by kensoh** [comment]
I see, sure Marcelo! Let me know if you run into any problems.
