### ISSUE TITLE
Unexpected token '/' - old syntax and outdated TagUI version, try new TagUI and this

### ISSUE THREAD

**Issue by amit018-hub** [kelaberetiv/TagUI#1080]
I wanted to automate by doing a program but this happened, But This errors give me headache..
-----------------------------------------------------
-----------------------------------------------------
SyntaxError: Unexpected token '/'

  phantomjs://code/updateresults.tag.js:1582 in injectJs
  phantomjs://code/bootstrap.js:456

------------------------------------------------------
------------------------------------------------------

The Code is as follows:

-------------------------------------------------------
-------------------------------------------------------

// Upadate results on icmr website

// login to icmr cvstatus page
tagui login.tag

// Goto  cvstatus website
https://cvstatus.icmr.gov.in/

// type user name
type username as `uname`

// type password
type passwd as `pwd`

//click on login button
click login_btn

// load csv file

file_rows= []
csv_file= 'result.csv'
load '+csv_file+' to lines
file_rows = lines.split('\n')

for i from 1 to file_rows.length-1
{

// check data from file

row=[]
row=file_rows[i].split(',')

if row[13] equal to 1
	record = row[1] + "\n Positive results recorded."
	write `record` to failed.txt
	echo `record`
	continue

// click on Add Record from SRF Portal

	click Add Record from SRF Portal

// type SRF ID  
	type srf_id as `row[1]`

// click Search button

	click btn

// passing row data of csv to dom_json

dom_json={ recno:i,name:row[2], pid:row[3], sid:row[4], rdate:row[5], stype:row[6], sdate:row[7], kit:row[8], tdate:row[9], egene:row[10], orf:row[11], rdrp:row[12], fresult:row[13] }

// opens the next page to edit wait for 3 seconds to load the page .... wait for another 5 sec if delayed in loading the next page
wait 3

if url() not equal to "https://cvstatus.icmr.gov.in/add_record.php"
{
	echo "page not yet loaded"
	wait 5
	record = row[1] +"\n SRF ID could not open. Already fetched probably." 
	write `record` to failed.txt
	echo `record`
	continue
}
dom begin
	var flg=0
	var tmp
	if(document.getElementById("patient_name").value != dom_json.name)
	{
		flg=1
	}
	if(flg==0)
	{
		document.getElementById("patient_id").value= dom_json.pid
		document.getElementById("sample_id").value = dom_json.sid
		document.getElementById("sample_rdate").value = dom_json.rdate
		document.getElementById("sample_tdate").value = dom_json.tdate
		document.getElementById("sample_type").selectedIndex = dom_json.stype
		document.getElementById("date_of_onset_of_symptoms").value = dom_json.sdate
		document.getElementById("testing_kit_used").selectedIndex = dom_json.kit
		document.getElementById("covid19_result_egene").selectedIndex= dom_json.egene
		document.getElementById("orf1b_confirmatory").selectedIndex= dom_json.orf
		document.getElementById("rdrp_confirmatory").selectedIndex= dom_json.rdrp
		document.getElementById("final_result_of_sample").selectedIndex= dom_json.fresult
		if(dom_json.recno==1)
		{
			var disp="\nPatient_id : "+ document.getElementById("patient_id").value
			disp+= "\nSample_id : "+ document.getElementById("sample_id").value
			disp+= "\nSample recieved Date : "+  document.getElementById("sample_rdate").value
			disp+= "\nSample tested Date : "+  document.getElementById("sample_tdate").value
			disp+= "\nSample Type : " + document.getElementById("sample_type").selectedOptions[0].innerText
			disp+= "\nSymptom Date : " + document.getElementById("date_of_onset_of_symptoms").value
			disp+= "\nTesting kit : " + document.getElementById("testing_kit_used").selectedOptions[0].innerText
			disp+= "\nResult Egene : "+ document.getElementById("covid19_result_egene").selectedOptions[0].innerText
			disp+= "\norf1b_confirmatory : "+ document.getElementById("orf1b_confirmatory").selectedOptions[0].innerText
			disp+= "\nrdrp_confirmatory : "+ document.getElementById("rdrp_confirmatory").selectedOptions[0].innerText
			disp+= "\nFinal Result : "+ document.getElementById("final_result_of_sample").selectedOptions[0].innerText
			disp+= "\nPlease press Cancel to stop further submissions" 
			var tmp= confirm("verify data submitted"+disp)	
			if(!tmp)
				flg=2	
		}
			
	}
	return flg
dom finish

if dom_result equal to 2
	echo HALTED
	break

if dom_result equals to 1
	record = row[1] + "\n Patient Name"
	write `record` to failed.txt
	echo `record`
else
	frecord = row[1] 
	write `frecord` to success.txt
	echo "page updated for "+`frecord`
		
// click submit button to save changes
	click btn

// wait for 3 sec to submit the data and reload the page for next iteration
	wait 3
}
-------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------

**Comment by ruthtxh** [comment]
Hi @amit018-hub, you may try wrapping the variable csv_file in backticks instead of '+ +' for the load step as per v6 syntax. For example:
```
load `csv_file` to lines
```

**Comment by amit018-hub** [comment]
Thank You @ruthtxh, But I got another error

SyntaxError: Expected token ')'

  phantomjs://code/updateresults.tag.js:1582 in injectJs
  phantomjs://code/bootstrap.js:456

**Comment by amit018-hub** [comment]
@kensoh Please help me to fix this issue. I would be very grateful.

**Comment by ruthtxh** [comment]
Hi @amit018-hub

The following flow file works for the latest version of TagUI (change the extension from .txt to .tag before running):
[example.txt](https://github.com/kelaberetiv/TagUI/files/6860933/example.txt)
These are the only 2 changes we did for this example to run:
- replacing '+ +' with backticks
- comment out the subflow - tagui login.tag (because we don't have your subflow to replicate)

There might be a few reasons why you are getting this error. Our main suspicion is that you're using an older version of TagUI which may flag out some inconsistencies in your indentation, for example your //code comments should follow the same indentation of the preceding line of code. Another reason could be your subflow login.tag could be causing the issue.

Can you check the version of TagUI that you're using? You can do so by running the command tagui in your command prompt like this:
![image](https://user-images.githubusercontent.com/40910744/126610295-b7f94f9d-a943-4b74-9a51-418bcd1d066d.png)

We recommend you use the latest version of TagUI. Please note that some changes in v6 that might cause backward compatibility issues if you built your flows on the older version syntax. Some of main features of v6 can be found here: https://github.com/kelaberetiv/TagUI/tree/v6.46.0#migrating-to-v6

You can download the latest copy of TagUI from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation):
https://github.com/kelaberetiv/TagUI/archive/master.zip

**Comment by amit018-hub** [comment]
These are the sub flows to replicate that program


login.tag
----------------------------------------------------------
----------------------------------------------------------

// Loginto icmr website for data entry or dataupdate

// First, visit  cvstatus website
https://cvstatus.icmr.gov.in/

// type user name

type username as INDNAB

// type password
type passwd as terminatecovid19

//click on login button

click login_btn

------------------------------------------------------------
------------------------------------------------------------
 
[result.xlsx](https://github.com/kelaberetiv/TagUI/files/6866308/result.xlsx)

**Comment by kensoh** [comment]
Hi @amit018-hub, attached zip file contains example.tag and login.tag - [Archive.zip](https://github.com/kelaberetiv/TagUI/files/6866334/Archive.zip)

It is able to run ok. Ruth's post above shared the changes made. Basically changing syntax for variables to the new v6 syntax for steps like load step. Can you try downloading the latest version of TagUI and see if the files in Archive.zip work for you?

**Comment by amit018-hub** [comment]
ThankYou So much @kensoh & @ruthtxh Im really appreciated to you guys, It works. But i need a small query.

How i put this value, which is exist in csv file as patient id : IND/GOV/COV/ED485

In this step:
-----------------------------------------

document.getElementById("patient_id").value= dom_json.pid
document.getElementById("sample_id").value = dom_json.sid

_______________________________________

I think by default it take integer value.

**Comment by amit018-hub** [comment]
why it didn't follow the csv file

![Screenshot (2)](https://user-images.githubusercontent.com/87682204/126819464-cc84915f-b3e4-4182-84a9-13371ad5f462.png)

**Comment by kensoh** [comment]
For the question on dom you can do some checks before assigning dom to see why the value is not assigned or wrong.

```
echo `row[3]`,`row[4]`
dom_json={ recno:i,name:row[2], pid:row[3], sid:row[4], rdate:row[5], stype:row[6], sdate:row[7], kit:row[8], tdate:row[9], egene:row[10], orf:row[11], rdrp:row[12], fresult:row[13] }
```

Also, why are you using dom to do the assignment? TagUI has the type step to do the assignment -

```
type patient_id as `row[3]`
```

**Comment by kensoh** [comment]
For your question why it does not follow CSV file, can you point out which line you mean does not follow?

Can you also share your CSV file here for us to see and tell us which is the value you are expecting it to use?

**Comment by amit018-hub** [comment]
Yeah Im shared my csv file as excel shhet before let me send again.

[docs.zip](https://github.com/kelaberetiv/TagUI/files/6871826/docs.zip)


I think this part doesn't working because it directly comes to end.
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
dom begin
	var flg=0
	var tmp
	if(document.getElementById("patient_name").value != dom_json.name)
	{
		flg=1
	}
	if(flg==0)
	{
		document.getElementById("patient_id").value= dom_json.pid
		document.getElementById("sample_id").value = dom_json.sid
		document.getElementById("sample_rdate").value = dom_json.rdate
		document.getElementById("sample_tdate").value = dom_json.tdate
		document.getElementById("sample_type").selectedIndex = dom_json.stype
		document.getElementById("date_of_onset_of_symptoms").value = dom_json.sdate
		document.getElementById("testing_kit_used").selectedIndex = dom_json.kit
		document.getElementById("covid19_result_egene").selectedIndex= dom_json.egene
		document.getElementById("orf1b_confirmatory").selectedIndex= dom_json.orf
		document.getElementById("rdrp_confirmatory").selectedIndex= dom_json.rdrp
		document.getElementById("final_result_of_sample").selectedIndex= dom_json.fresult
		if(dom_json.recno==1)
		{
			var disp="\nPatient_id : "+ document.getElementById("patient_id").value
			disp+= "\nSample_id : "+ document.getElementById("sample_id").value
			disp+= "\nSample recieved Date : "+  document.getElementById("sample_rdate").value
			disp+= "\nSample tested Date : "+  document.getElementById("sample_tdate").value
			disp+= "\nSample Type : " + document.getElementById("sample_type").selectedOptions[0].innerText
			disp+= "\nSymptom Date : " + document.getElementById("date_of_onset_of_symptoms").value
			disp+= "\nTesting kit : " + document.getElementById("testing_kit_used").selectedOptions[0].innerText
			disp+= "\nResult Egene : "+ document.getElementById("covid19_result_egene").selectedOptions[0].innerText
			disp+= "\norf1b_confirmatory : "+ document.getElementById("orf1b_confirmatory").selectedOptions[0].innerText
			disp+= "\nrdrp_confirmatory : "+ document.getElementById("rdrp_confirmatory").selectedOptions[0].innerText
			disp+= "\nFinal Result : "+ document.getElementById("final_result_of_sample").selectedOptions[0].innerText
			disp+= "\nPlease press Cancel to stop further submissions" 
			var tmp= confirm("verify data submitted"+disp)	
			if(!tmp)
				flg=2	
		}
			
	}
	return flg
dom finish
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------

**Comment by kensoh** [comment]
The echo output looks correct -
```
IND/GOV/COV/ED485,IND/GOV/COV/ED485
```

Please see attached file. Below runs for me. I think the problem is because within dom begin and finish, you should not do indentation. I added an if block. You can try this or you remove the 1 level of indentation for all the lines in dom begin/finish.
[updateresults.tag.zip](https://github.com/kelaberetiv/TagUI/files/6871911/updateresults.tag.zip)

**Comment by amit018-hub** [comment]
Thank You So much @kensoh @ruthtxh for you co-operation. Im very thankful to you.

**Comment by amit018-hub** [comment]
I have last query for you, if the third row of that csv file already filled in that portal, and that was not editable how can we start from 4th row and also not comparing with name.

**Comment by ruthtxh** [comment]
Hi @amit018-hub, before you fill in any row of record, you may search up the patient to see if there's already a record in the system. Perhaps you can use the if present('') or if exist('') functions to check if an element exist when patient has existing records.

```
for i from 1 to file_rows.length-1
{
    if present('xpath_to_some_element')
        // whole block of code to add new patient to system
}
```

**Comment by ruthtxh** [comment]
@amit018-hub Would also like to add on that, I noticed you included the login credentials to the portal when uploading your flow file here at Github. I hope it is some test account / test site that does not return any actual patient info. If you have overlooked and this is your actual account to the database, it is best if you remove the login credentials here and reset your password to that website ASAP.

Cheers,
Ruth

**Comment by amit018-hub** [comment]
That's a good point actually. I don't even remeber it, Thank You @ruthtxh

**Comment by kensoh** [comment]
(adding on, I deleted one of your reply above with screenshot, as it contains your user id and password)
