### ISSUE TITLE
Sikulix crashes when typing accented characters - use clipboard() and paste instead

### ISSUE THREAD

**Issue by loweaxerium** [kelaberetiv/TagUI#1082]
When asking to type something that has an accented character sikulix crashes

**Comment by ruthtxh** [comment]
Hi @loweaxerium, can you share an example of accented characters that causes SikuliX to crash on type step? Thanks!

I tried the following and TagUI was able to type into the google search bar:
```
https://google.com
type q as éŒœÐðÇç
wait 5
```

**Comment by loweaxerium** [comment]
Thanks for the response, just tested on macOS using a png and it fails.

**Comment by ruthtxh** [comment]
Hi @loweaxerium, if you are using keyboard step to type into a field, you may try setting the accented characters to a variable, and paste the variable to the text field. 

```
message = 'some international characters'
clipboard(message)
click field.png
keyboard [ctrl]v
```

SikuliX has limitation a for keyboard step which only accepts US-English keyboard layout.
Do let us know if this helps!

**Comment by loweaxerium** [comment]
Thanks for sharing more tips!!!
