### ISSUE TITLE
Select specific row in html table - try out these ideas to do (checking text or attribute)

### ISSUE THREAD

**Issue by andrei152515** [kelaberetiv/TagUI#1086]
Hi, i'm new to tagui and i'm trying to select a specific row in an html table. 
I have a table on a website and i want to delete a specific row where a specific class (text-danger) is present.
example below.
![image](https://user-images.githubusercontent.com/87833471/126710051-1710f24f-3e41-45e4-ab7e-67f2775d731c.png)

I want to delete the specific products which are out of stock.
for the example shown the html code is: 
![image](https://user-images.githubusercontent.com/87833471/126710366-27414147-08e3-4a49-8322-38c29e611a33.png)

Can someone help me please ?
Thank you :)

**Comment by kensoh** [comment]
Hi @andrei152515 an easy way would be using read step to get the text into a variable, then check before deleting.

```
read xpath_of_item_description to description
if description contains '***'
    click xpath_of_button_to_delete
```

Above can then be wrapped in a for loop to process all the records, using this XPath syntax `(xpath)[n]`. Other ways that can be explored will be reading attributes using `xpath/@class` or check if `xpath//[@class="text-danger"]` exists using exist().

**Comment by kensoh** [comment]
Other than visually inspecting the HTML code, Chrome extension like SelectorsHub can be very helpful to find XPath.

**Comment by andrei152515** [comment]
Hi @kensoh
Thank you for your quick response, your suggestions helped me a lot, but now I face another issue. 
I get the number of products from that list (products from the cart) into a variable using count and after that I used 'for' to loop from 1 to the number of products then  delete the product from the cart, where exist '***' 
The issue is that every time I delete a product, the list is updated and for example if I have 3 products that are out of stock (having the *** mark) from a list of 4 total products: 
#1 out of stock product***
#2 out of stock product***
#3 product in stock 
#4 out of stock product***

If  I delete the first product, tagui will not delete the second one, because #2 will become #1 and the for loop at that time is passed from the step #1 which delete the first out of stock product and in this way I will get only 2 products deleted instead of 3. 
Is there any way to deal with this kind of issue?

Thank you so much.

**Comment by kensoh** [comment]
Hi @andrei152515 I'm bringing in my team-mate @ruthtxh to look at this. This is an interesting scenario, I thought if more people can look into this a better solution can be found.

**Comment by ruthtxh** [comment]
Hi @andrei152515 
You may create your own counter variable to track and decrement the total count once you delete something. Usually for list of products the xpath will be in an array, so create a loop with variable n to access that array. For example:
```
counter = count('xpath_of_products')
for (n=1; n<counter; n++)
    read xpath_of_item_description[`n`] to description
    if description contains '***'
        click xpath_of_button_to_delete[`n`]
        js n--
        js counter--
```

**Comment by kensoh** [comment]
This is a great idea - I'm not sure if the for loops in TagUI can accept direct decrements of the variables, but is worth trying!

**Comment by andrei152515** [comment]
hi @ruthtxh, thank you for your suggestion, but is not working.  The reason, I think, is because  'for' is using the first count and do not take into account the decrementing. Below I will attach the code that I'm using, and the results, to have a better idea of what I'm trying to do:

number_items=count('//*[@class="table table-bordered"]//*[@class="text-center"]') - 1 
echo `number_items`

for (item=1; item<number_items; item++)
  if exist ('//*[@id="content"]/form/div/table/tbody/tr[`item`]/td[2]//*[@class="text-danger"]')
    click (//*[@id="content"]/form/div/table/tbody/tr[`item`]/td[4]/div/span/button[2]) 
  echo the number of items before decrement is: `number_items`
    js item--
    js number_items--
  echo the number of items after decrement is: `number_items`


The total number of items in the list is 5, and 3 of them are out of stock. 
![image](https://user-images.githubusercontent.com/87833471/127180693-b448bdaa-5954-4e9e-a64f-2036c0ad77a5.png)

**Comment by marcelocecin** [comment]
@andrei152515 hello, can you share the website url?

**Comment by andrei152515** [comment]
hi @marcelocecin, unfortunately is on localhost

**Comment by marcelocecin** [comment]
and the html code?

**Comment by andrei152515** [comment]
The website is based on Opencart. This is the cart page:
[website.txt](https://github.com/kelaberetiv/TagUI/files/6887238/website.txt)

**Comment by marcelocecin** [comment]
try to use this XPath `//span[text()='***']/../..//td//div//span//button[@title='Remove']`

**Comment by kensoh** [comment]
Hi Marcelo, this looks like a brilliant solution!

If the removal has some processing time, @andrei152515 can add a wait after deleting for page to refresh before loop again.

**Comment by andrei152515** [comment]
hi @marcelocecin, very good idea, helped me a lot, with just a small rectification: 

total_items = count('//span[text()="***"]')
for n from 1 to total_items
  click //span[text()="***"]/../..//td//div//span//button[@title="Remove"]<style="color:red;">[1]

If there is `n` then I receive this error: ERROR - cannot find //span[text()="***"]/../..//td//div//span//button[@title="Remove"][2]
and I think this is because after the first product with "***" is deleted n becomes 2 and the second product from the deletion list become 1.

Thank you.

**Comment by andrei152515** [comment]
hi @marcelocecin, very good idea, helped me a lot, with just a small rectification: 

total_items = count('//span[text()="***"]')
for n from 1 to total_items
  click //span[text()="***"]/../..//td//div//span//button[@title="Remove"]   [1]

For, 'click', instead of n is working with 1. If there is `n` then I receive this error: ERROR - cannot find //span[text()="***"]/../..//td//div//span//button[@title="Remove"][2]
and I think this is because after the first product with "***" is deleted n becomes 2 and the second product from the deletion list become 1 and so on. The  product to delete from the list is always 1. 

Thank you.
