### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by munishmarya** [kelaberetiv/TagUI#1090]
I am trying for some time below script but system is giving me syntax error, any help will be appreciated. 

SyntaxError: Expected token ')'
  phantomjs://code/drivenscrap.tag.js:1577 in injectJs
  phantomjs://code/bootstrap.js:456

_______________________________________________
keyboard [alt][tab]
click images/drivenproperties.PNG
click images/locationsearchbox.PNG
// iterate through table on the page and collect data
dump date, community, propertyname, type, bedroom, price, sqft, pricesqft to drivenproperties.csv
rows = count('//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"]')
for rows from 1 to rows
    read((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[2] to date
    read(((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[3])/strong to community
    read((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[4] to propertyname
    read((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[5] to type
    read((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[6] to bedroom
    read((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[7] to price
    read((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[8] to sqft
    read((//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"])[`row`]/td)[9] to pricesqft
    new_row = [date, community, propertyname, type, bedroom, price, sqft, pricesqft]
    write `csv_row(new_row)` to drivenproperties.csv
______________________________________________________________________

**Comment by munishmarya** [comment]
i tried removing all brackets in read rows and it worked. thanks for great project

keyboard [alt][tab]
click images/drivenproperties.PNG
click images/locationsearchbox.PNG
// iterate through table on the page and collect data
dump date, community, propertyname, type, bedroom, price, sqft, pricesqft to drivenproperties.csv
rows = count('//tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"]')
for rows from 1 to rows
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[2] to date
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[3]/strong to community
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[4] to propertyname
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[5] to type
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[6] to bedroom
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[7] to price
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[8] to sqft
    read //tbody/tr[@class="dpx-sold-grid-row dpx-sold-grid-df"][`row`]/td[9] to pricesqft
    new_row = [date, community, propertyname, type, bedroom, price, sqft, pricesqft]
    write `csv_row(new_row)` to drivenproperties.csv

**Comment by kensoh** [comment]
Welcome @munishmarya! Interesting, yes in this case the brackets should be removed.

In addition, I would like to introduce to you the table step. With it, you may be able to collect this data in 1 line. Example -

```
table [table number] to [filename.csv]
table [XPath] to [filename.csv]
```

```
table 1 to regional_exchange_rates.csv
table (//table)[2] to global_exchange_rates.csv
table //table[@name='report'] to report.csv
```

https://tagui.readthedocs.io/en/latest/reference.html#table

**Comment by kensoh** [comment]
CC @ruthtxh fyi
