### ISSUE TITLE
Error - TAGUI is reading xpath incorrectly

### ISSUE THREAD

**Issue by munishmarya** [kelaberetiv/TagUI#1091]
Hi,

I have used tagui in past and its great, but this is my first time dealing with xpath. I am using below flow but tagui is reading count of rows as zero while in the webpage there are 51 instances of the xpath (I checked xpath using chrome console result was 51)

results from tagui:
____________
START - automation started - Tue Aug 03 2021 10:08:37 GMT+0530 (India Standard Time)
keyboard [win]r
keyboard chrome[enter]
wait 2
keyboard [ctrl][v][enter]
wait 2
dump date, community, propertyname, type, bedroom, price, sqft, pricesqft to drivenproperties.csv
'row counted' 0
_______________________

flow used:
__________________________
keyboard [win]r
keyboard chrome[enter]
clipboard('https://www.drivenproperties.com/dubai-real-estate-market-guide/rental-transactions')
wait 2
keyboard [ctrl][v][enter]
wait 2
dump date drivenproperties.csv
rows = count('//*[@id="dpx-sold-grid-tbody"]/tr')
echo 'row counted' `rows`
for row from 1 to rows
    echo 'for started ' `row`
    read //*[@id="dpx-sold-grid-tbody"]/tr[`row`]/td[2] to date
_____________________

**Comment by ruthtxh** [comment]
Hi @munishmarya 

Instead of using keyboard and clipboard to access the webpage you can directly access it with the url as a step
```
https://www.drivenproperties.com/dubai-real-estate-market-guide/rental-transactions
rows = count('//*[@id="dpx-sold-grid-tbody"]/tr')
echo `rows`
```
doing this in live mode gives the result of 51 for me:
![image](https://user-images.githubusercontent.com/40910744/127998340-1d4e859a-cded-4430-b205-682f0e5eed3c.png)

**Comment by munishmarya** [comment]
thanks for reply Ruth. I tried again following your approach but same results for me 0 rows, i am saving the flow and using cmd to run. I have used the latest package from [https://tagui.readthedocs.io/en/latest/setup.html](url)

flow results
_______________
https://www.drivenproperties.com/dubai-real-estate-market-guide/rental-transactions
rows = count('//*[@id="dpx-sold-grid-tbody"]/tr')
echo `rows`

flow used:
`_________________
https://www.drivenproperties.com/dubai-real-estate-market-guide/rental-transactions
rows = count('//*[@id="dpx-sold-grid-tbody"]/tr')
echo `rows`
`
![image](https://user-images.githubusercontent.com/11234851/128012795-d18c1622-0e3d-494c-b482-f56cbb1fcc6f.png)

**Comment by ruthtxh** [comment]
Hi @munishmarya, seems like the webpage takes a while to load. You may add a wait step in between like this for a 3 second delay:
```
https://www.drivenproperties.com/dubai-real-estate-market-guide/rental-transactions
wait 3
rows = count('//*[@id="dpx-sold-grid-tbody"]/tr')
echo `rows`
```

see diff after adding the wait step:
![image](https://user-images.githubusercontent.com/40910744/128016057-765d4e56-6a03-41f9-b2d0-ccea4bdd243e.png)
![image](https://user-images.githubusercontent.com/40910744/128016124-a33c9b23-504d-4d20-abae-a629c83fa76a.png)

**Comment by munishmarya** [comment]
@ruthtxh thanks, you are a star. It worked after wait time, have patience let it load :)

**Comment by ruthtxh** [comment]
@munishmarya no problem, feel free to ask anything!

**Comment by kensoh** [comment]
Adding on, if you prefer a dynamic wait time instead of a fixed time, you can use hover step on some element that only shows up when the page is fully loaded. That way, once the page is done loading, automation proceeds.
