### ISSUE TITLE
Does TagUI support desktop application? - yes, some ways to copy, paste and click

### ISSUE THREAD

**Issue by evandeng2009** [kelaberetiv/TagUI#1094]
So far I noticed TagUI supports web page operations, how about desktop applications, we may copy, paste and click.

**Comment by ruthtxh** [comment]
Hi @evandeng2009 we can automate desktop applications with visual automation.

To copy and paste on windows, we can use:
```
keyboard [ctrl]c
keyboard [ctrl]v
```
you can also use the clipboard function to copy:
```
clipboard('some text')
keyboard [ctrl]v
```
on mac:
```
keyboard [cmd]c
keyboard [cmd]v
```
to click destop applications, you can save a snapshot of the button for example,
![image](https://user-images.githubusercontent.com/40910744/128444664-907178a9-91cc-40cb-881a-5beb1b86ea05.png)
name this snapshot as windows_button.png, then do something like:
```
click windows_button.png
```

**Comment by kensoh** [comment]
closing for time being until further inputs
