### ISSUE TITLE
How to use Key Up and Key Down Functionality | [ctrl]c

### ISSUE THREAD

**Issue by bcpeinhardt** [kelaberetiv/TagUI#1103]
I noticed the following examples in https://tagui.readthedocs.io/en/latest/reference.html#keyboard
```
keyboard [win]run[enter]
keyboard [ctrl]c
```
The typical usage of [ctrl]c is to 
1) Key down [ctrl]
2) Key down c
3) Key up c
4) Key up [ctrl]

whereas the typical usage of [win]run[enter] is
1) Key down [win]
2) Key up [win]
3) Key down r
4) Key up r
5) Key down u
6) Key up u
7) Key down n
8) Key up n
9) Key down [enter]
10) Key up [enter]

How does tagui know to swap the order for [ctrl]c / can a tagui user specify Key down and Key up?

**Comment by bcpeinhardt** [comment]
Thanks! Even if it doesn't work for the select it's good information for me to know! I do a lot of web automation with selenium and I had a process that required interacting with the local machine part way through so I thought I'd give TagUI a try and man it's awesome!

**Comment by kensoh** [comment]
Linking to a dom step solution that @bcpeinhardt tested - https://github.com/kelaberetiv/TagUI/issues/283#issuecomment-911952607
