### ISSUE TITLE
How to use timeout properly - usage is correct pending details and logs

### ISSUE THREAD

**Issue by bcpeinhardt** [kelaberetiv/TagUI#1104]
I am experiencing issues with the timeout command which are almost certainly due to user error.
I am trying to automate interactions with a website that has several VERY slow load times. I would like to set a global timeout of 500s (yes it's that slow). When I do
```
https://theurl.com
type usernameBox as theusername@example.com
```
it works fine, but
```
https://theurl.com
timeout 500
type usernameBox as theusername@example.com
```
causes the script not to proceed. Is this waiting 500 seconds no matter what? I'm trying to achieve a 500 second timeout but have the script proceed immediately once the element is located. usernameBox is the id. I have also used a unique xpath and the same issue is occuring.

**Comment by bcpeinhardt** [comment]
Currently, I am using the for loop solution from https://github.com/kelaberetiv/TagUI/issues/499 to achieve explicit waits on the problem elements.

**Comment by kensoh** [comment]
Hi @bcpeinhardt yes your usage is correct. See below sample flow, it runs ok for me immediately once webpage loads.

```
www.google.com
timeout 500
type //*[@name = 'q'] as testing 123
wait
```

Can you share more on what is the error? Is it hangs at the type step perpetually?

There is a tagui_chrome.log file under tagui/src folder. Can you attached the file here for running 1) without timeout 500 and 2) running with timeout 500. To see if there are clues why that is happening. Base on the info above, I can't think of a reason why it hangs, and have not hear a similar issue reported by users so far.

**Comment by bcpeinhardt** [comment]
Just put the timeout back and it didn't block this time. There must have been some other error in my code or maybe the page wasn't registering as completely loaded for some reason. Sorry for the time wasted! Closing this issue.
