### ISSUE TITLE
Why read  (x1,y1)-(x2,y2) function didn't work? - try this, issue with OpenCV

### ISSUE THREAD

**Issue by HuangJingping** [kelaberetiv/TagUI#1106]
when i used the function 'read (x1,y1)-(x2,y2) to some-variable', the flow  didn't run forward and output nothing. please tell me why this happened

**Comment by kensoh** [comment]
Hi @HuangJingping, thanks for raising this, some next steps -

1. check that you have OpenJDK / Java 64-bit installed for this feature to work - [link here at installation steps](https://tagui.readthedocs.io/en/latest/setup.html)
2. can you share more what is your OS? Win/Mac/Linux etc
3. can you check your tagui folder, there is a src/tagui.sikuli folder. can you attach the tagui.log here?

**Comment by kensoh** [comment]
copying my team-mate @ruthtxh

**Comment by HuangJingping** [comment]
thanks @kensoh 
my os is win7 an i am sure the OpenJDK / Java is already on my system.
i can't find the tagui.log in the src/tagui.sikuli folder

**Comment by kensoh** [comment]
I see.. In your command prompt where you run tagui command, can you run java -v and share the output here?

The SikuliX engine only works with 64-bit OpenJDK / Java. Empty log sounds like for some reason it did not run.

**Comment by HuangJingping** [comment]
the fllowing is the error information when i run java -v
error:registry key 'software\javasoft\java runtime environment'\currentversion'
has value '1.8.0_302', but '1.8' is required.
error:could not find java.dll
error:could not find java se runtime environment

**Comment by kensoh** [comment]
Looks like your computer java is not working. Install from step 1 below - 

> Hi @HuangJingping, thanks for raising this, some next steps -
> 
> 1. check that you have OpenJDK / Java 64-bit installed for this feature to work - [link here at installation steps](https://tagui.readthedocs.io/en/latest/setup.html)
> 2. can you share more what is your OS? Win/Mac/Linux etc
> 3. can you check your tagui folder, there is a src/tagui.sikuli folder. can you attach the tagui.log here?

**Comment by HuangJingping** [comment]
ok, i'll try. thanks for your help



---Original---
From: "Ken ***@***.***&gt;
Date: Tue, Sep 7, 2021 00:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kelaberetiv/TagUI] Why read  (x1,y1)-(x2,y2) function didn't work? - pending details and replication (#1106)




 
Looks like your computer java is not working. Install from step 1 below -
  
Hi @HuangJingping, thanks for raising this, some next steps -
  
check that you have OpenJDK / Java 64-bit installed for this feature to work - link here at installation steps 

can you share more what is your OS? Win/Mac/Linux etc 

can you check your tagui folder, there is a src/tagui.sikuli folder. can you attach the tagui.log here? 
  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HuangJingping** [comment]
Java - v is no problem now and It also can find the log file  in the SRC/tagui tagui. 
But when I run the read (x1,y1)-(x2,y2) to variable, sikuliX engine occur error and the cmd don,t run forward.

**Comment by kensoh** [comment]
Oh great! Can you check the step 3 above and share the log file from SikuliX Engine?

**Comment by kensoh** [comment]
Alternatively, for Windows, there should be a SikuliX Engine command window which you can take a screenshot.

**Comment by HuangJingping** [comment]
yes, there were a sikulix engine command window. but when i typed 'read …' and enter, it disappeared



---Original---
From: "Ken ***@***.***&gt;
Date: Wed, Sep 8, 2021 00:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kelaberetiv/TagUI] Why read  (x1,y1)-(x2,y2) function didn't work? - pending details and replication (#1106)




 
Alternatively, for Windows, there should be a SikuliX Engine command window which you can take a screenshot.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kensoh** [comment]
I see.. Can you check the step 3 above and share the log file from SikuliX Engine?

**Comment by HuangJingping** [comment]
the content of the log file is in the attachment.



---Original---
From: "Ken ***@***.***&gt;
Date: Wed, Sep 8, 2021 08:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kelaberetiv/TagUI] Why read  (x1,y1)-(x2,y2) function didn't work? - pending details and replication (#1106)




 
If the log is blank and has no clues, see if you can join the weekly Zoom Q&amp;A tomorrow.
 
It is Thursday at 4-5pm Singapore time / China time / Taiwan time / Hongkong time.
 
Meeting link here - #914
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kensoh** [comment]
Can you try attaching in the issue directly? It looks like from email there is no attachment here.

**Comment by HuangJingping** [comment]
[tagui] START  - listening for inputs

[tagui] INPUT  - [1] vision xy_mouseLocation = Env.getMouseLocation(); xy_x = xy_mouseLocation.getX(); xy_y = xy_mouseLocation.getY(); output_sikuli_text('(' + str(xy_x) + ',' + str(xy_y) + ')');
[tagui] ACTION - xy_mouseLocation = Env.getMouseLocation(); xy_x = xy_mouseLocation.getX(); xy_y = xy_mouseLocation.getY(); output_sikuli_text('(' + str(xy_x) + ',' + str(xy_y) + ')');
[tagui] OUTPUT - [1] SUCCESS

[tagui] INPUT  - [2] vision xy_mouseLocation = Env.getMouseLocation(); xy_x = xy_mouseLocation.getX(); xy_y = xy_mouseLocation.getY(); output_sikuli_text('(' + str(xy_x) + ',' + str(xy_y) + ')');
[tagui] ACTION - xy_mouseLocation = Env.getMouseLocation(); xy_x = xy_mouseLocation.getX(); xy_y = xy_mouseLocation.getY(); output_sikuli_text('(' + str(xy_x) + ',' + str(xy_y) + ')');
[tagui] OUTPUT - [2] SUCCESS

[tagui] INPUT  - [3] read (565,472)-(1109,539) to ddd
[tagui] ACTION - read (565,472)-(1109,539) to ddd
[error] RunTimeAPI: Problematic lib: C:\Users\Administrator\AppData\Roaming\Sikulix\SikulixLibs\opencv_java342.dll (...TEMP...)
[error] RunTimeAPI: opencv_java342.dll loaded, but it might be a problem with needed dependent libraries
ERROR: ...TEMP...: Can't find dependent libraries
[error] script [ tagui ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 584, in <module>
    intent_result_value = parse_intent(tagui_intent)
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 522, in parse_intent
    return read_intent(script_line)
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 323, in read_intent
    return text_read(raw_intent)
  File "C:\tagui\src\tagui.sikuli\tagui.py", line 354, in text_read
    temp_text = region_layer.text()
  File "C:\Users\Administrator\AppData\Roaming\Sikulix\Lib\sikuli\Region.py", line 53, in text
    return JRegion.text(self).encode("utf8")
	at org.sikuli.script.TextRecognizer.<init>(TextRecognizer.java:31)
	at org.sikuli.script.TextRecognizer.start(TextRecognizer.java:54)
	at org.sikuli.script.TextRecognizer.doOCR(TextRecognizer.java:243)
	at org.sikuli.script.TextRecognizer.doOCR(TextRecognizer.java:238)
	at org.sikuli.script.Region.text(Region.java:4976)
	at org.python.proxies.sikuli.Region$Region$3.super__text(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError

IDE terminated: returned: 1

**Comment by kensoh** [comment]
The error above is

```
[error] RunTimeAPI: Problematic lib: C:\Users\Administrator\AppData\Roaming\Sikulix\SikulixLibs\opencv_java342.dll (...TEMP...)
[error] RunTimeAPI: opencv_java342.dll loaded, but it might be a problem with needed dependent libraries
ERROR: ...TEMP...: Can't find dependent libraries
```

From googling, this seems to be a possible solution - https://bugs.launchpad.net/sikuli/+bug/1797505

Install this https://www.microsoft.com/en-us/software-download/mediafeaturepack and restart PC.

**Comment by kensoh** [comment]
Check the link for other options. Try one by one until solved. If no solution, then cannot use. The maintainer of SikuliX also no other way to help.

For example this one for Windows 7,
https://www.microsoft.com/en-nz/download/details.aspx?id=36805

**Comment by HuangJingping** [comment]
ok, thanks for your help



---Original---
From: "Ken ***@***.***&gt;
Date: Thu, Sep 9, 2021 07:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kelaberetiv/TagUI] Why read  (x1,y1)-(x2,y2) function didn't work? - try this, issue with OpenCV (#1106)




 
Check the link for other options. Try one by one until solved. If no solution, then cannot use. The maintainer of SikuliX also no other way to help.
 
For example this one for Windows 7,
 https://www.microsoft.com/en-nz/download/details.aspx?id=36805
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kensoh** [comment]
No probs! Hope the Windows 7 solution or one of the solutions in the link works for you. Thanks for raising this issue Jingping.

**Comment by gauravgandhi1315** [comment]
@kensoh Thanks, works for me.

**Comment by kensoh** [comment]
Closing this. Due to rare occurrence, not adding to documentation. Fyi @ruthtxh on a rare issue where user needs to install Microsoft Media Feature pack in order to use SikuliX features. By right these requirements come with Windows by default.
