### ISSUE TITLE
MS Edge not working with TagUI - use -edge or -e option to use MS Edge browser

### ISSUE THREAD

**Issue by gshields** [kelaberetiv/TagUI#1111]
tagui v6.76
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe ver. 93.0961.44
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043

running tagui live gives:
ERROR - cannot find Chrome browser executable file at a few commonly located folders
Chrome is at a non-standard location on your Windows, raise an issue on t.me/rpa_chat

**Comment by kensoh** [comment]
Hi @gshields, the default browser used by TagUI is Chrome. To use MS Edge, you have to use `-edge` / `-e` option -

```
tagui live -edge
```

https://tagui.readthedocs.io/en/latest/reference.html#edge-or-e

**Comment by gshields** [comment]
Ken,
Thanks for your help, that worked!

**Comment by gshields** [comment]
Found the docs
