### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by hermandr** [kelaberetiv/TagUI#1112]
Hi,
I have installed tagui version v6.48

When I run it on tag file below
```
echo Test

echo Test for loop
for n from 1 to 5
    echo loop `n`

echo Test while loop	
n = 0
while n less than 5
    n = n+1
    echo loop `n`

n = 3
echo N `n`

```

I get
```
START - automation started - Mon Sep 13 2021 12:16:19 GMT+0800 (Malay Peninsula Standard Time)

Test
Test for loop
loop 1
loop 2
loop 3
loop 4
loop 5
Test while loop
loop 1
loop 2
loop 3
loop 4
loop 5
N 3
```

When I run the tag file below
```
echo Test

echo Test for loop
for n from 1 to 5
    echo loop `n`

echo Test while loop	
n = 0
while n less than 5
    n = n+1
    echo loop `n`

n = 3
echo N `n`

if n equals 3
    echo N equals 3

```

I get error
```
SyntaxError: Expected token ')'

  phantomjs://code/test.tag.js:1549 in injectJs
  phantomjs://code/bootstrap.js:456

```

**Comment by hermandr** [comment]
For those like me - new to tagui...

```
if n equals to 3
    echo N equals 3
```
Use EQUALS TO

Or 
```
if (n == 3)
    echo N equals 3
```

Both the above works

**Comment by kensoh** [comment]
Thanks @hermandr for raising this! There was a typo in the documentation with the `to`. This is now fixed.

https://tagui.readthedocs.io/en/latest/main_concepts.html#if-conditions

The sample for conditions is ok - https://github.com/kelaberetiv/TagUI/blob/master/flows/samples/3_conditions.tag

You can also use `equal to` (without s) in the same was as `equals to` (with s)

**Comment by kensoh** [comment]
CC my team-mate @ruthtxh for info
