### ISSUE TITLE
'tar' is not recognized as an internal or external command - see this solution

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1114]
*source - telegram*

A user has this message when doing `tagui update`
```
'tar' is not recognized as an internal or external command, operable program or batch file.
```

For Windows, TagUI uses the tar command to unzip the downloaded and updated version of TagUI. From Microsoft website (https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows), it seems to say that all versions of Windows have it now.

>Tar and curl are staples in a developer’s toolbox;
>beginning today, you’ll find these tools are available from the command-line for all SKUs of Windows.

However for the user, his Windows 7 does not have this command. It might be because Microsoft didn't push this update to Windows 7 users or it might be company policy not updating to latest Windows 7 patches. Will lookout for more users giving this feedback to see if it is one-off situation, before adding below solution to usage guide.

Creating an issue here and sharing the solution below that works for him.

1. download this zip (link is from Microsoft website earlier) - http://libarchive.org/downloads/libarchive-v3.5.2-win64.zip

2. move the files under bin folder to tagui\src\unx folder

3. rename bsdtar.exe to tar.exe

4. try tagui update again to see if it works

**Comment by muhammadqasim6308** [comment]
hello sir,
"I have an error on Jupiter notebook tar is not recognized so what should I do for it?"

**Comment by kensoh** [comment]
Can you tell me more about how are you producing this error?

If you are using Python rpa package in Jupyter notebook, there should not be any code that calls `tar` command.

If you are using TagUI in human language version, then why would you be using it in Jupyter notebook?

Copying @ruthtxh fyi

**Comment by kensoh** [comment]
Closing this. Due to rare occurrence, not adding to documentation. Fyi @ruthtxh on a rare issue where user needs to install tar command manually in order to use `tagui update`. By right this command comes with Windows by default.

**Comment by racashik** [comment]
> hello sir, "I have an error on Jupiter notebook tar is not recognized so what should I do for it?"

I'm having same problem, could you help me to solve it please?
