### ISSUE TITLE
Fixed sporadic Aw, Snap! error on Chrome, looks like Chrome bug, see here - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1116]
Heard from Ruth and students who she's working with of above sporadic error. Raising issue to track further reports and replication details to find permanent fix. Issue seems likely to be a recent Chrome update which spawns 2 processes instead of 1. And when the process TagUI kills happens to be the child instead of parent, there will be a dead session left open.

****
Adding on, looks like this might be a Chrome bug. When updated to latest Chrome `Version 94.0.4606.54 (Official Build) (64-bit)`, only a single process is returned on Windows when checking with wmic command. Will KIV for more data before rolling back. In the meantime, this updated fix should let TagUI work with both the older Chrome version and newer one.

**Comment by kensoh** [comment]
adding a note that we verified that the generated JS file and tagui_chrome.php files are the same for computer with the error and computer which does not have the error. Thus eliminating turbo mode file corruption as a potential cause of issue.

**Comment by kensoh** [comment]
Multiple processes issue seems to be happening only on Windows Chrome, but not Windows Edge, or macOS Chrome / Edge.

For the child processes, there are additional attributes in the commandline property of the process. One is `--type=renderer`

**Comment by kensoh** [comment]
Trying out a potential solution by excluding those with `--type=renderer` string in the commandline property of the process.

**Comment by kensoh** [comment]
If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update.

For list of changes since TagUI v.6.46 release in mid-June, see this (link also found at TagUI installation page) -
https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+

**Comment by kensoh** [comment]
Adding on, looks like this might be a Chrome bug. When updated to latest Chrome `Version 94.0.4606.54 (Official Build) (64-bit)`, only a single process is returned on Windows when checking with wmic command. Will KIV for more data before rolling back.

**Comment by gauravgandhi1315** [comment]
@kensoh Above solution works.

**Comment by kensoh** [comment]
Thanks @gauravgandhi1315 ! I assume you mean that updating Chrome works.

Thinking whether to roll back this update since updating Chrome works (root cause).

But some people cannot close Chrome to update it because they have a lot of tabs open.

**Comment by gauravgandhi1315** [comment]
Yes, updating chrome works.

**Comment by kensoh** [comment]
Closing since this change has made its way into the latest packaged release.
