### ISSUE TITLE
Added PDF integration to read .pdf, added MS Word integration to read .docx - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1118]

**Comment by kensoh** [comment]
Doesn't seem valuable for other types of documents. Excel is meaningful because the data is structured and there is a way to move data in and out of TagUI while retaining that structure, since in TagUI an array would represents Excel perfectly.

For PDF and Word, it is either copy all of the text into a linear string variable or array of sentences. This can already be done in 5 lines of TagUI instructions (1 line to open, 1 line to wait, 1 to select all, 1 to copy to clipboard, 1 to copy from clipboard to variable). Value of doing this for PDF is the reading can be done in 1 line vs 5 lines.

Value for doing this for MS Word is possibility of replacing specific text. Eg Word template with special text markers, that RPA can use to replace accordingly with real data during automation. In addition to reducing reading all text from 5 to 1 line. Furthermore, with helper functions like get_text() and del_chars(), useful fields can be extracted from Word text content.

**Comment by kensoh** [comment]
word / pdf —> explore on windows / mac

**Comment by marcelocecin** [comment]
please consider including linux too

**Comment by kensoh** [comment]
oh Marcelo, I'm afraid Linux doesn't have such an API to automate desktop apps. For Windows it is through VB Script and for Mac it is through AppleScript. If you know something similar for Linux, I can check it out.

**Comment by marcelocecin** [comment]
https://www.makeuseof.com/tag/linux-automation-apps/

**Comment by kensoh** [comment]
Thanks @marcelocecin ! I've looked through the items in the article.

The 3rd and 4th items at the link are for expanding text and doing scheduling. The first two items are https://github.com/Jmgr/actiona and https://github.com/autokey/autokey which are for automating Linux apps through the GUI. However they are different from how TagUI automates Excel.

On Windows it is uses VB Script, on Mac it is using AppleScript. Both are API methods that let TagUI control programmatically the automation of apps, but Actiona and AutoKey are actual apps which have to be used to do the automation.

**Comment by marcelocecin** [comment]
hi Ken, on Linux would you necessarily have to use UI or could you use Python?
I found some examples using Python:

https://linuxhint.com/manipulating_excel_python/

https://www.cdata.com/kb/tech/excel-odbc-python-linux.rst

**Comment by kensoh** [comment]
Oh for automating Excel it is necessary to use the Excel app, even if it is done programatically to control.

The reason is without the actual Excel app, various ways to modify Excel file using Python make use of creating a temporary data representation of the Excel file, which is not 100% accurate and after the file is saved, data may be created or modified, or removed.

**Comment by kensoh** [comment]
But if you are running Linux, then definitely you can write some Python code to easily manipulate the Excel files, at some risk of losing data or formatting accurately. TagUI you can use the `py begin` and `py finish` to do what is needed.

**Comment by kensoh** [comment]
For the TagUI-Excel integration (which requires Excel app), it is now out and available for Windows and Mac - https://tagui.readthedocs.io/en/latest/reference.html#excel

**Comment by kensoh** [comment]
Added PDF integration in TagUI v6.99. With this change, users can read the text contents of a PDF in 1 line, by providing the filename and assigning directly to a variable, for example below (relative and absolute paths supported) -
```
text_data = [Research Paper 2019.pdf]
```
- Windows pre-requisite - need the free Adobe Acrobat Reader installed as default PDF viewer
- Mac no pre-requite - its Preview app can copy text from PDF files without installing other apps

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update. For list of changes since TagUI v6.46 release in mid-June 2021, [visit this link](https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+) (also found at TagUI installation page).

**Comment by kensoh** [comment]
Added Word .docx integration in TagUI v6.100. With this change, users can read the text contents of a Word document in 1 line, by providing the filename and assigning directly to a variable, for eg below (relative and absolute paths supported) -

```
text_data = [Research Paper 2019.docx]
```

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update. For list of changes since TagUI v6.46 release in mid-June 2021, [visit this link](https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+) (also found at TagUI installation page).

**Comment by kensoh** [comment]
Thanks @marcelocecin for sharing!

Looks like in this case, you can call the PDF extraction with `run` step to chain a series of steps together. `evince` and `xdotool` do not come default in Linux, thus not a good idea to add as part of PDF integration. CC @ruthtxh

**Comment by kensoh** [comment]
Closing since this change has made its way into the latest packaged release.
