### ISSUE TITLE
Automating Firefox - yes visual automation v60 onwards, -firefox option for v59

### ISSUE THREAD

**Issue by aaditkamat** [kelaberetiv/TagUI#1119]
I've currently switched from Google Chrome to Firefox Developer Edition. Based on what I can see, there used to be a [command-line option to run the automation on Firefox](https://tagui.readthedocs.io/en/latest/dep_options.html?highlight=firefox#deprecated-command-line-options) which is now deprecated. May I know if it is still possible to automate using Firefox?

**Comment by kensoh** [comment]
Hi @aaditkamat, if you are using visual automation, you can still automate Firefox with computer vision, keyboard and mouse automation. But if you want to automate Firefox from backend, you can download Firefox v59, and then run TagUI with -firefox option.

The reason for no longer supporting new Firefox version is TagUI automates Firefox through SlimerJS. However, Firefox overhauled its architecture from v60 onwards, that is a huge change in architecture that SlimerJS no longer works with.

**Comment by kensoh** [comment]
I saw your message in the group chat, we can follow-up more there - https://t.me/rpa_chat/7806
