### ISSUE TITLE
How can we read and write to database from TagUI?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#112]
Raising this from an user email for sharing, as other users might benefit from this question.

---

Do you think you can provide very simple script samples on how TagUI can make the connection directly to DB?

**Comment by kensoh** [comment]
Yes this should be possible using the run step to run specific DB command for your database.

It depends on your variant of database for different types of CLI, for eg mysql, sqlcmd. Let me put together a sample for mysql for a database on my server, to read some data and write some data.

**Comment by kensoh** [comment]
**TagUI automation file**
```
// form sql query to read from database and save to os script
// on mac/linux be sure that read_db file has execute permission
sql_query = 'mysql DATABASE_NAME -e "SELECT NAME,EMAIL FROM TABLE_NAME"'
dump sql_query to read_db

// use run step to run the script and retrieve results
run /full_path_to_flow/read_db
db_result = run_result.split('\n')
for row from 1 to db_result.length
{
        db_row = db_result[row-1].split('\t')
        echo db_row[0] ',' db_row[1]
}

// form sql query to write to database and save to os script
// on mac/linux be sure that read_db file has execute permission
sql_query = 'mysql DATABASE_NAME -e "UPDATE TABLE_NAME SET NAME=\'KS\' WHERE EMAIL=\'kensoh@gmail.com\'"'
dump sql_query to write_db

// use run step to run the script to write
run /full_path_to_flow/write_db

// repeat the reading of database showing new data
run /full_path_to_flow/read_db
db_result = run_result.split('\n')
for row from 1 to db_result.length
{
        db_row = db_result[row-1].split('\t')
        echo db_row[0] ',' db_row[1]
}
```

**Execution result**
```
START - automation started - Sat Mar 31 2018 22:02:20 GMT+0800 (SGT)

dump sql_query to read_db
run /full_path_to_flow/read_db
NAME,EMAIL
Ken Soh,kensoh@gmail.com
Starbucks PS,paultan@starbucks.com
dump sql_query to write_db
run /full_path_to_flow/write_db
run /full_path_to_flow/read_db
NAME,EMAIL
KS,kensoh@gmail.com
Starbucks PS,paultan@starbucks.com

FINISH - automation finished - 0.7s
```

**Comment by kensoh** [comment]
Above shows an example of forming SQL query in TagUI automation flow. It first reads from the database and then write something to it, before reading and displaying back the new result.

Notice that NAME value has been changed from 'Ken Soh' to 'KS' after the database write operation. Closing this issue for now unless there is new queries on this.

For now, it might not make sense to create a sql step to do DB operations like these because it is very specific to what type of DB and what type of operations to be general enough for a new helper step.

**Comment by adegard** [comment]
Hi @kensoh ,
I 'd like to consider Mysql Connection to database to automatize processes on own website. But in your above axample, I didn't anderstand how to configure connection with MySQL like: Host: .... Username=... ; passwords: ..., Database: .... Could you please indicate me the correct command line to insert in read_db file?
Thanks

**Comment by kensoh** [comment]
Hi @adegard that's a good question, thanks! I've updated example above - https://github.com/kelaberetiv/TagUI/issues/112#issuecomment-377695716

The example assumes using root user from server. If database credentials are needed, something like below should be used. (reference - [mysql command line options](https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html))

```
sql_query = 'mysql DATABASE_NAME --user=username --password=\'password\' -e "SELECT NAME,EMAIL FROM TABLE_NAME"'
```

**Comment by balwant-sd** [comment]
I have some issues with fetching data from mysql database.
i make another folder 'sql_test' in samples.

Above Mention Code I write in a file and when i run this, it does not show any output.

My Path of script file is ->/home/pericent/tagui/src/samples/sql_test
path of read_db file is ->/home/pericent/tagui/src/samples/sql_test

```
sql_query = 'mysql temp_info --user=root --password=\'\' -e "SELECT NAME, ADDRESS FROM EMP"'
dump sql_query to read_db
run /read_db
db_result = run_result.split('\n')
for row from 1 to db_result.length
{
       db_row = db_result[row-1].split('\t')
       echo db_row[0] ',' db_row[1]
}
``` 

I recheck the existence of database and table. both are exist. 

Username='root' and password =''

**Comment by balwant-sd** [comment]
Hi, I am using this line but it only show myql options. it does not fetch data.
What should I do ???

`sql_query = 'mysql temp_info --user=root password=\'\' --execute = "select name from emp"'`

**Comment by brahmanath** [comment]
@kensoh I am trying to run the script for fetching data from mysql database.
but getting below error on command prompt.

START - automation started - Fri Oct 04 2019 17:45:25 GMT+0530 (India Standard Time)

dump sql_query to read_db
run /C:/app/read_db
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

**Below query written in my automation file (read_db)**

// form sql query to read from database and save to os script
// on mac/linux be sure that read_db file has execute permission
sql_query = 'mysql taguidemo --user=****--password=\'********\' -e "SELECT MobileNo FROM tbluser"'
dump sql_query to read_db

// use run step to run the script and retrieve results
run /C:/app/read_db
db_result = run_result.split('\n')
for row from 1 to db_result.length
{
        db_row = db_result[row-1].split('\t')
        echo db_row[0] ',' db_row[1]
}

![read_db](https://user-images.githubusercontent.com/55791043/66206984-38f96d00-e6cf-11e9-8996-9a9d5fa8e1b8.jpg)
[read_db.log](https://github.com/kelaberetiv/TagUI/files/3690471/read_db.log)

I am attaching log file and command prompt output. Please suggest and help

**Comment by kensoh** [comment]
Hi @brahmanath this error is because the filename you specified is invalid -

`/C:/app/read_db`

In Windows, there is no `/` before the drive letter. Also, I think you have to name the read_db as read_db.bat so that it can be run by Windows. Something like below -

```
sql_query = 'mysql taguidemo --user=****--password='********' -e "SELECT MobileNo FROM tbluser"'
dump sql_query to read_db.bat

// use run step to run the script and retrieve results
run C:/app/read_db.bat
```

**Comment by brahmanath** [comment]
Hi Ken,

Thanks for response, I have change the thing that you have suggested, but still getting issue for the same. Kindly look command prompt screen shot and attached file for the same and it will be great appreciation if you suggest on the same.

**Below query written in my automation file (read_db)**

sql_query = 'mysql taguidemo --user=root --password=\'mysql@123\' -e "SELECT MobileNo FROM tbluser"'
dump sql_query to read_db.bat

// use run step to run the script and retrieve results
run C:/app/read_db.bat
db_result = run_result.split('\n')
for row from 1 to db_result.length
{
db_row = db_result[row-1].split('\t')
echo db_row[0] ',' db_row[1]
}

[read_db.log](https://github.com/kelaberetiv/TagUI/files/3710732/read_db.log)

![read_db](https://user-images.githubusercontent.com/55791043/66543645-9a985c00-eb53-11e9-9261-2b869ee39342.jpg)

**Comment by brahmanath** [comment]
Hi Ken,

Thanks for response. I have tested both scenario. When I running the query from command prompt, it is working fine and provide result but when I am running read_db.bat file then its generate error "ERROR 1045 (28000): Access denied for user '=root'@'localhost' (using password: YES)" while I have given full right to read_db.bat file. Please see the screen shot and suggest.

![read_db](https://user-images.githubusercontent.com/55791043/66639613-cc352400-ec34-11e9-89d0-3741eefde44a.jpg)
[read_db.log](https://github.com/kelaberetiv/TagUI/files/3716601/read_db.log)

**Comment by kensoh** [comment]
Hi Brahma, this is useful information, but I'm afraid it is related to the way Windows batch file works and I could not advise on how to troubleshoot this problem (running the command from prompt works but from batch file does not work).

You can try providing password as part of the command or google to see if other people have problem running mysql command from batch file. For my example in this issue, it is coded and tested to run on macOS and Linux using their shell scripts.
