### ISSUE TITLE
Multiple Chrome Profiles and Proxy features - ideas to explore, Ghostbrowser etc

### ISSUE THREAD

**Issue by 0xGitGuy** [kelaberetiv/TagUI#1124]
I like to use TagUI to automate web actions in multiple accounts. Each web account maintains a unique IP through the use of proxy. Ideally, I like each account to maintain their session to avoid having to login again daily. What's the best way to do this? Will you support Ghostbrowser since its based on chromium?

**Comment by kensoh** [comment]
Oh great, thanks @0xGitGuy for sharing back! I'll close the issue for now but please feel free to ping back here.

PS - sorry for my slow reply, was away past few weeks to organise my mum's funeral and coming back to work again
