### ISSUE TITLE
How to run a script headless, which contain some steps via skuli and some via normal element identifier.

### ISSUE THREAD

**Issue by Anujpalu24** [kelaberetiv/TagUI#1128]
How to run a script headless, which contain some steps via skuli and some via normal element identifier.

Try to create a new script for skuli  steps and call the same in another tag
tagui skuil.tag -n

and run the same script using -h but it is not allowing

**Comment by ruthtxh** [comment]
Hi @Anujpalu24 

For calling subflows, you are unable to add run options. However, you can chain the different tag files like this in a .cmd file. One with headless mode and one with no browser mode, like this:

```
@echo off
call tagui a.tag -h
call tagui b.tag -n
```
