### ISSUE TITLE
ask_result stores no value - access variable w backticks, not quotes

### ISSUE THREAD

**Issue by RidaShahidMalik** [kelaberetiv/TagUI#1131]
Even when I run the simplest code: 

ask Package ID:
echo 'ask_result'

In the cmd menu 'ask_result' gets returned. No matter what I type in the google prompt box.

**Comment by ruthtxh** [comment]
Hi @RidaShahidMalik, variables are accessed using backticks, not quotes. Please try the following
```
echo `ask_result`
```
