### ISSUE TITLE
headless vs nobrowser mode return single vs array of elements - phantomjs inherent feature

### ISSUE THREAD

**Issue by chooimail** [kelaberetiv/TagUI#1132]
Hi there,

Still very new to TagUI and exploring how to use it.

I've upload a file that has some tagui steps.
Basically trying to find out, save, list out the available links on a webpage.

**Q: Why is there a difference when I run "headless" and "nobrowser"?**
For example:
tagui filename.tag -h  .... this results in 1 link only
tagui filename.tag -n  .... this results in all links

Rgds,
Chooi
[pagelinks.tag.txt](https://github.com/kelaberetiv/TagUI/files/7559554/pagelinks.tag.txt)

**Comment by ruthtxh** [comment]
Hi @chooimail,
-n runs on phantomjs invisible browser whereas
-h runs on Chrome in invisible mode
seems like you just discovered a "feature" of phantomjs browser where it returns all instances of the element when searched.

A more reliable way to loop through the results is using the for loop, like this:
```
for n from 1 to link_num
  read (//*[@id="main-content"]//*/h2/a)[`n`] to text
```

**Comment by chooimail** [comment]
> Hi @chooimail, -n runs on phantomjs invisible browser whereas -h runs on Chrome in invisible mode seems like you just discovered a "feature" of phantomjs browser where it returns all instances of the element when searched.
> 
> A more reliable way to loop through the results is using the for loop, like this:
> 
> ```
> for n from 1 to link_num
>   read (//*[@id="main-content"]//*/h2/a)[`n`] to text
>   // you can use write step to append `text` to csv file next
> ```
> 
> Here's an example of looping in action, https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail

Hi Ruth,
TQVM for your guidance and link to an example.
I will look further into the example and learn more as I use more of TagUI, as well as more of [phantomjs invisible browser].

On that note, I would just like to ask further in relation to that sample tagui flow/set of codes
_**What do you call the *.tag files anyway? Codes? Lines of codes? Steps file?_

### Question 1
From the excerpt set of lines below.
**Actually line 44 is not needed....correct?**

```
// To use image snapshots here, set browser to 125% zoom while at Gmail.
// (Chrome was set at 125% zoom for this workflow to show actions clearly)
**https://mail.google.com/mail/u/0/**     // Line 44 here

// set focus to Chrome browser and compose a new message
click chrome_icon.png
click gmail_compose.png
```

### Question 2
```
for n from 1 to link_num
read (//*[@id="main-content"]//*/h2/a)[`n`] to text
// you can use write step to append `text` to csv file next
```
**What coding language is the above lines using?**
Because I'm more familiar with JavaScript, where a FOR loop is usually
```
for(i=0;i<link_num;i++){
   // execute more code here
}
```

**Comment by kensoh** [comment]
Hi @chooimail, .tag files we usually call them workflow or flow files. Because they store the sequence of steps to be done to automate a workflow.

On your question 1, the workflow in that example does some steps on a banking website, after that it tries to send email through Gmail. Thus the line 44 to go to Gmail URL is needed to get the browser from the banking website to gmail, before continuing the rest of the automation steps.

On your question 2, the language Ruth gave is the TagUI language of for loops - https://tagui.readthedocs.io/en/latest/main_concepts.html#for-loops

However, underlying engine in TagUI is Javascript, so you should be able write using JavaScript for loops. If you run into any problem let us know. As the language move towards the Python style of code blocks, it might introduce edge cases that we are not aware of.

**Comment by kensoh** [comment]
Also copying @ruthtxh

**Comment by chooimail** [comment]
@kensoh @ruthtxh 
_On your question 1, the workflow in that example does some steps on a banking website, after that it tries to send email through Gmail. Thus the line 44 to go to Gmail URL is needed to get the browser from the banking website to gmail, before continuing the rest of the automation steps._

But, going from banking website to Gmail...
  - The web browser that is being used/opened up by TagUI does not have any Google account signed in.

I just want to know if what I'm seeing and trying is the correct understanding.
Or I seem to be missing something in between.

**Comment by kensoh** [comment]
Oh, the user is first required to log in to Gmail on the browser. The logged-in state will be saved so that subsequent access to the page no longer requires logging in. You can do this by putting a fake `ask` step to wait, or some long wait time like `wait 120` while you login for the first time.

**Comment by chooimail** [comment]
I see.
Alright, thank you very much.

**Comment by kensoh** [comment]
Welcome @chooimail, let us know if you run into any doubts or issues again.

If you use Telegram, you can join the group chat at https://t.me/rpa_chat

Besides us, other experienced users will also share their tips :)
