### ISSUE TITLE
Command line arguments - how to pass special characters such as exclamation mark

### ISSUE THREAD

**Issue by adwilson99** [kelaberetiv/TagUI#1135]
I'm trying to make my TagUI script so that I can pass in the user name and password as parameters.  however my password has an exclamation mark (!) that does not get passed across
e.g.
`tagui ./test.tag user pass123!`

This results in: 
`D:\tagui>tagui test.tag user pass123!

START - automation started - Fri Nov 19 2021 17:30:34 GMT+0800 (Malay Peninsula Standard Time)
"Username is:" user
"Password is:" pass123`

As can be seen above the exclamation (!) mark is missing.   Appreciate any help or suggestion on how to pass this special character across. My script is really simple and included below.
```
// test TagUI CL Arguments
echo "Username is:" `p1`
echo "Password is:" `p2`

```

**Comment by ruthtxh** [comment]
Hi @adwilson99, in the meanwhile you can use the ask step to prompt user for the password using chrome's prompt. It passes in the exclamation mark character.

```
ask Enter password:
echo `ask_result`
```

**Comment by adwilson99** [comment]
> Hi @adwilson99, in the meanwhile you can use the ask step to prompt user for the password using chrome's prompt. It passes in the exclamation mark character.
> 
> ```
> ask Enter password:
> echo `ask_result`
> ```

Thank you Ruthtxh, that works.   Is there any way to get the ask command to star out the text as it's typed (i.e. show **** instead of plain text, since this is a password input field.

Thanks.

**Comment by ruthtxh** [comment]
Hi @adwilson99, unfortunately this step makes use of the browser's prompt feature, which does not have the option of masking input. Thanks.

**Comment by marcelocecin** [comment]
you might consider including base64 password in `tagui_local.csv`
```
OBJECT,DEFINITION
username,user
password,cGFzczEyMyE=
```
and read the password inside the `test.tag`
```
js pass = atob(password)
echo Username is: `username`
echo Password is: `pass`
```

**Comment by kensoh** [comment]
Thanks @ruthtxh and @marcelocecin for sharing your tips!

Adding on, another option is 'escaping' characters like `!` with backlash `\!`, for example the following will send the value `pass123!` to be available for use in TagUI as `p1` variable. This is because ! is a special purpose character in the bash prompt, and backslash can be used to override that to take it as a normal ! character.

```
tagui ./test.tag user pass123\!
```
