### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count()

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#1136]
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /Users/tagui/src/tagui_parse.php:35
Stack trace:
#0 {main}
  thrown in /Users/tagui/src/tagui_parse.php on line 35
ERROR - automation aborted due to above

**Comment by ruthtxh** [comment]
Hi @marcelocecin, can you share your flow so we can take a look at the syntax used thanks!

**Comment by marcelocecin** [comment]
Hello @ruthtxh 
this error occurs after updating mac OS to version 12.0.1 (21A559)
I had to reinstall php
I used the commands
`tagui update`
`xcode-select --install`
`brew install php`
PHP 8.0.13 (cli) (built: Nov 19 2021 09:05:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
     with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies
I'm trying to run the flow `tagui /Users/tagui/flows/samples/1_google.tag`

**Comment by ticonsulting-dlara** [comment]
Hi!

I had the same issue, I resolved it uninstalling php 8 and then installing 7.4:
brew install php@7.4
brew link --force --overwrite php@7.4
brew services start php@7.4
export PATH="/usr/local/opt/php@7.4/bin:$PATH"
export PATH="/usr/local/opt/php@7.4/sbin:$PATH"

I hope it works for you too!

Kind regards,
David

**Comment by marcelocecin** [comment]
thanks @ticonsulting-dlara it works !

**Comment by kensoh** [comment]
Thanks Guys for raising this and discussing this!

I've created an issue to track and review if there is a OS-level problem introduced with MacOS v12 - https://github.com/kelaberetiv/TagUI/issues/1137

**Comment by yixian3500** [comment]
hello guys , I got same issue, but when I use 

> brew install php@7.4

it shows 👍 


Warning: No available formula with the name "php@7.4". Did you mean php@8.2, php@8.1 or php@8.0?
==> Searching for similarly named formulae and casks...
==> Formulae
php@8.2                    php@8.1                    php@8.0


does that means 7.4 is not available from brew?

**Comment by yixian3500** [comment]
> hello guys , I got same issue, but when I use
> 
> > brew install php@7.4
> 
> it shows 👍
> 
> Warning: No available formula with the name "php@7.4". Did you mean php@8.2, php@8.1 or php@8.0? ==> Searching for similarly named formulae and casks... ==> Formulae php@8.2 php@8.1 php@8.0
> 
> does that means 7.4 is not available from brew?

please ignore my question, I solved this problem when I updated to the last version of tagui (v6.114) by " tagui update
"
