### ISSUE TITLE
Type variable that is read from another web element - see usage guide and example here

### ISSUE THREAD

**Issue by filip86pa** [kelaberetiv/TagUI#1139]
Hello

Please, how to type variable which read [XPath] to [variable]

I want copy text from one [XPath] and paste to another [XPath]

Thank you

**Comment by marcelocecin** [comment]
to read: https://tagui.readthedocs.io/en/latest/reference.html#id2
to type: https://tagui.readthedocs.io/en/latest/reference.html#type

**Comment by kensoh** [comment]
Thanks @marcelocecin!

Here's an example using the links Marcelo shared. It reads the value of this GitHub issue page, and types it into the comment field. (You will need to login to GitHub first, just put a wait 60 to do the login on the first time).

```
https://github.com/kelaberetiv/TagUI/issues/1139
read markdown-title to title
type new_comment_field as `title`
```

**Comment by filip86pa** [comment]
Thank you everyone!
but it does not work, command "type new_comment_field as `title`" paste exactly `title` not variable. I want to clarify that copy "variable" and paste position are not in same web page.
Please for help

**Comment by filip86pa** [comment]
Xpath is problem

**Comment by kensoh** [comment]
Hi @filip86pa can you copy and paste the above sample code again? The title variable is backticks and not the single quote.

Above sample code works for me and type the title variable into the textbox.

I'm using TagUI v6.95. Which version are you? (type tagui from command prompt)

**Comment by kensoh** [comment]
(closing for time being till further inputs)
