### ISSUE TITLE
No package 'libimobiledevice-glue-1.0' found when brew install - pending clarification

### ISSUE THREAD

**Issue by ramaraj2601** [kelaberetiv/TagUI#1141]
configure: error: Package requirements (libimobiledevice-glue-1.0 >= 1.0.0) were not met:

No package 'libimobiledevice-glue-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables limd_glue_CFLAGS
and limd_glue_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by kensoh** [comment]
Hi @ramaraj2601 can you tell me more why you need to use Homebrew?

Are you trying to install some requirements for Mac that is needed by TagUI?

**Comment by ramaraj2601** [comment]
@kensoh 
I am doing appium setup in mac machine.
While i am running this command in terminal- brew install --HEAD libimobiledevice, I am getting this error.

**Comment by kensoh** [comment]
Oh this GitHub repo is for TagUI RPA open-source software, nothing to do with Appium.

Looks like you may have raised the issue in the wrong GitHub repo. Appium is here -

https://github.com/appium/appium/issues

I'll close the issue here for now.

**Comment by kensoh** [comment]
copying @ruthtxh
