### ISSUE TITLE
if condition not validating text? - variables in if condition don't need backticks

### ISSUE THREAD

**Issue by Anujpalu24** [kelaberetiv/TagUI#1145]
so actually i wanted to verify that that particular text in variable "CreateLoadText" contain some values "has been created. If you have any questions please contact your rep" but it is not going into IF condition.

read //p[text()='Load '] to CreateLoadText
echo `CreateLoadText`

if `CreateLoadText` contains "has been created. If you have any questions please contact your rep."
{
hover Emulating...
click Stop Emulating & Sign out     
}
else
{
echo test case failed
}

**Comment by ruthtxh** [comment]
Hi @Anujpalu24, for if condition, you do not have to wrap variables in between backticks.

```
if CreateLoadText contains "has been created. If you have any questions please contact your rep."
```

**Comment by 20013505-Low-TianYee** [comment]
> so actually i wanted to verify that that particular text in variable "CreateLoadText" contain some values "has been created. If you have any questions please contact your rep" but it is not going into IF condition.
> 
> read //p[text()='Load '] to CreateLoadText echo `CreateLoadText`
> 
> if `CreateLoadText` contains "has been created. If you have any questions please contact your rep." { hover Emulating... click Stop Emulating & Sign out } else { echo test case failed }

I tried to do it too. I found out that if condition only works on numbers and not string.

**Comment by kensoh** [comment]
Oh the if condition can work on both numbers and text.

For comparing numbers, don't need use quotation marks
```
if price greater than 20
    echo expensive
```

For comparing text, need to use quotation marks
```
if brand equals to "Cartier"
   echo expensive
```
