### ISSUE TITLE
get_text() to read by number of characters from left marker? - use this JS function

### ISSUE THREAD

**Issue by filip86pa** [kelaberetiv/TagUI#1147]
Hello everyone

Is it possible to right marker of get_text command be defined as "numbers of characters" from left marker. 
Left marker is same, the right marker varies from case to case, because I can not define right marker

Thank you

**Comment by kensoh** [comment]
Hi @filip86pa, I'm afraid the get_text() function the parameter aren't designed to be used this way. However, you can write your own using standard JavaScript functions. See below example of finding a left marker and reading 7 characters from the start of the left marker -
```
text = 'abc def ghi'
echo `text.substr(text.indexOf('def'), 7)`
```

The output will be def ghi

CC @ruthtxh fyi
