### ISSUE TITLE
Dumping array into csv works, but i keep receiving error - try this example

### ISSUE THREAD

**Issue by 20013505-Low-TianYee** [kelaberetiv/TagUI#1148]
For eg
dump Name,Mobile\r to cand.csv
for c from 0 to 2
    write `csv_row(phoneArr[c])` to cand.csv

it does dumps into csv file however i keep getting 
ERROR - undefined is not an object (evaluating 'original_row_data.slice')

**Comment by ruthtxh** [comment]
Hi @20013505-Low-TianYee, you may try something like this.

```
phoneArr = [000,111,2222]
for c from 0 to 2
	phone = phoneArr[c]
	write `csv_row([phone])` to cand.csv
```
https://tagui.readthedocs.io/en/latest/reference.html?#csv-row
