### ISSUE TITLE
How to generate a random number or character with specific size - see this

### ISSUE THREAD

**Issue by Anujpalu24** [kelaberetiv/TagUI#1149]
How to generate a random number or character with specific size

**Comment by ruthtxh** [comment]
Hi @Anujpalu24 I believe this is a generic question that is not related to TagUI.

Within TagUI you can use a variety of other programming languages to do this generation. 
To run javascript code: https://tagui.readthedocs.io/en/latest/reference.html?#js
To run python code: https://tagui.readthedocs.io/en/latest/reference.html?#py
To run r code: https://tagui.readthedocs.io/en/latest/reference.html?#r
