### ISSUE TITLE
TagUIWordAddIn error

### ISSUE THREAD

**Issue by better319** [kelaberetiv/TagUI#1150]
win10 64bit 19042.1237
TagUIWordAddInSetupV3.15.zip
word 2016 
i install TagUI_Windows.exe  TagUIWordAddInSetupV3.15.zip  

this can be run,it's ok
tagui c:\tagui\flows\samples\1_google.tag

but i can't get the word ui ,
my word show like  this ,help needed,THANKS

**Comment by better319** [comment]
![22](https://user-images.githubusercontent.com/13842581/146322010-1003758e-26a7-4ba0-ae88-bfd27f87cad7.png)

**Comment by better319** [comment]
install the setup.exe  and just for me ,not for everyone.

sloved

**Comment by kensoh** [comment]
Thanks @better319 for updating back! Also copying @ruthtxh
