### ISSUE TITLE
Improve input parameters p1-p8 by defaulting to blank '' instead of undefined - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1153]
If user does not provide the input parameter, it will `undefined` when used in TagUI.

Making an enhancement to default the values as blank string '' when inputs are not given.

After the change, below line will show a blank output instead of the word `undefined`, the value for an undefined JS variable.
```
echo `p1`
```

**Comment by kensoh** [comment]
Fixed in TagUI v6.103. If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. If not, you can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html) before performing the update. For list of changes since TagUI v6.46 release in mid-June 2021, [visit this link](https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+) (also found at TagUI installation page).

**Comment by kensoh** [comment]
Closing since this change has made its way into the latest packaged release.

**Comment by lookang** [comment]
Interesting idea @kensoh .
This will help users not edit the tag file and just use command prompt with changing inputs.

Thanks 🙏

**Comment by kensoh** [comment]
Thanks @lookang for your support always! Yes this is important, and is a natural feature of command-line tools, to easily run differently base on user different parameters during running.
