### ISSUE TITLE
Scrap "Selling Cash" & "Currency" rows - example using JavaScript Number() function

### ISSUE THREAD

**Issue by devanimesh1** [kelaberetiv/TagUI#1154]
I want to scrap table data only for selling cash value 60 or above in the following code,

//Step 1: Create CSV file with Date stamp in filename and headers Name , Price
dump Name,Price to newTable.csv

//Step 2: Website link from where to extract
https://www.dbs.com/in/treasures/rates-online/foreign-currency-foreign-exchange.page
wait 30

//Step 3: Count rows
rows = count('(//table[contains(@Class,"sc-dxgOiQ dzHkKC tbl-primary mBot-16")])[1]//tbody/tr')
echo rows

//Step 4: Run loop for all the rows to extract currency-foreign-exchange
for row from 1 to rows
{
read (//table[contains(@Class,"sc-dxgOiQ dzHkKC tbl-primary mBot-16")])[1]//tbody/tr[`row`]/td[1] to name
echo `name`
write `name` to name
read (//table[contains(@Class,"sc-dxgOiQ dzHkKC tbl-primary mBot-16")])[1]//tbody/tr[`row`]/td[3] to price
echo `price`
forex_rate= [name, price]

//Make entry on current currency Name and it's Price to the CSV File created at step 1
//echo `csv_row(forex_rate)`
write `csv_row(forex_rate)` to newTable.csv
}

As I am a beginner to RPA, this will be a great help

**Comment by kensoh** [comment]
Hi @devanimesh1 you can do something like this. Note that in below example, I use spaces indentation instead of {} to enclose the code block. From TagUI v6 onwards, it supports such indentation style for code blocks.

```
price = "70"
if Number(price) more than or equals to 60
    //Make entry on current currency Name and it's Price to the CSV File created at step 1
    //echo `csv_row(forex_rate)`
    write `csv_row(forex_rate)` to newTable.csv
```

**Comment by kensoh** [comment]
Adding on, TagUI's backend language is JavaScript, so you can google and search for standard JavaScript functions to do various operations as needed.
