### ISSUE TITLE
Uncaught WebSocket\ConnectionException: Could only write 0 out of .. - some thoughts

### ISSUE THREAD

**Issue by pp082** [kelaberetiv/TagUI#1156]
Hello, I am learning to use Tagui and it is an incredible tool, although I am still trying to take advantage of its full potential.

I have been trying to access a frame in different ways from live tag.

When identifying the frame I want to print its content from the Chrome Log and verify that I have access

<img width="650" alt="image" src="https://user-images.githubusercontent.com/38953492/146983890-2c4e7162-13f5-4ffb-b022-8f937bd06615.png">

In the first instance I want to know if I can get the src attribute

When I run in tagui live **dom return document.querySelector('#mainContent').name = "new_name"**

```
[tagui] INPUT  - 
[5] {"id":5,"method":"Runtime.evaluate","params":{"expression":"(function (dom_json) {document.querySelector('#mainContent').name = \"new_name\";})({})"}}

Fatal error: Uncaught WebSocket\ConnectionException: Could only write 0 out of 158 bytes. in /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php:249
Stack trace:
#0 /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php(126): WebSocket\Base->write('\x81\xFE\x00\x96*\x12<\x9BQ0U\xFF\x08(\t...')
#1 /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php(70): WebSocket\Base->send_fragment(true, '{"id":5,"method...', 'text', true)
#2 /Users/mac/Desktop/TAGUI_000/tagui/src/tagui_chrome.php(47): WebSocket\Base->send('{"id":5,"method...')
#3 {main}
  thrown in /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php on line 249
```
When I run in tagui live **document.querySelector('#mainContent').textContent**

```
[210] {"id":210,"method":"Runtime.evaluate","params":{"expression":"(function (dom_json) {return document.querySelector('#mainContent').textContent;})({})"}}
Fatal error: Uncaught WebSocket\ConnectionException: Could only write 0 out of 159 bytes. in /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php:249
Stack trace:
#0 /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php(126): WebSocket\Base->write('\x81\xFE\x00\x97u\xC3[i\x0E\xE12\rW\xF9i...')
#1 /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php(70): WebSocket\Base->send_fragment(true, '{"id":210,"meth...', 'text', true)
#2 /Users/mac/Desktop/TAGUI_000/tagui/src/tagui_chrome.php(47): WebSocket\Base->send('{"id":210,"meth...')
#3 {main}
  thrown in /Users/mac/Desktop/TAGUI_000/tagui/src/ws/Base.php on line 249
```

**Comment by pp082** [comment]
when resetting the connection `ctrl + C `and put `tagui live`, changing the command to

dom return document.querySelector('#mainContent').getAttribute("src")

```
[tagui] INPUT  - 
[13] {"id":13,"method":"Runtime.evaluate","params":{"expression":"(function (dom_json) {return document.querySelector('#mainContent').getAttribute(\"src\");})({})"}}
[tagui] OUTPUT - 
[13] {"id":13,"result":{"result":{"type":"string","value":"/wwwCuprum/wwwProductos/Ultimos_Movimientos/UltimosMovimientosCuenta2.aspx?id=2"}}}

```
it worked

To check
# How to read attribute value of a web element? #427
# https://github.com/kelaberetiv/TagUI/issues/427

**Comment by kensoh** [comment]
Hi @pp082 yes what you have found out works. By using dom step and standard JavaScript functions you can do this.

```
dom return document.querySelector('#mainContent').getAttribute("src")
```

Alternatively, you can try out using XPath and @src to read the attribute value for src.
```
read //*[@id = "mainContent"]//@src to link
```

For live mode, the frame step is not usable and web content within the frame is not accessible. 

For your initial attempt, `dom return document.querySelector('#mainContent').name = "new_name"` I'm not sure why the error happens. For your 2nd attempt, I think to return the HTML of a frame it is `contentDocument` not `textContent`, but I'm not sure if that can be immediately accessible that way. Usually it is retrieved and further decomposed to access the children.
