### ISSUE TITLE
Scheduling a flow to run periodically, but only if it is not running halfway - see this

### ISSUE THREAD

**Issue by delegate-it** [kelaberetiv/TagUI#1159]
Hi Ken

I am running a tagui flow tax.tag using a crontab scheduled every 4 hours. In the tagui flow, I am checking if the first flow is still running (doing this by checking the status in a postgres database via an api). If the status is still running, then the second flow will exit. if the status has failed, then I will continue with the flow. The second flow will pick where the first one stopped.

I realized that if the first flow is still running, and the second call to tax.tag will crash the first flow. Is there a way that I can run the same flow more than once on the same machine?

BTW, the flow of the first call and second call is the same.
`// get the compliance run from the database
//////////////
py begin

import requests
import json

query = {'today': 1}
response = requests.get(base_url + "taxes/api/runs/", params=query)

f=response.json()[0]
json_f = json.dumps(f)
print(json_f)
py finish
///////////////

echo py_result = `py_result`
py_result = JSON.parse(py_result)

status = py_result.status
last_iteration = py_result.last_iteration
last_row = py_result.last_row

echo status = `status`
echo last_iteration = `last_iteration`
echo last_row = `last_row`
// if failed or just started (status == 0)
if status == 0`

**Comment by kensoh** [comment]
Hi @delegate-it, TagUI wasn't designed and tested to run in parallel, and some intermediate working files are hosted within the tagui/src folders. Thus running a new process might interrupt or disrupt totally an existing one.

One easy way I can think of is this, set up your crontab to run runner.sh script this way -

runner.sh
```
#!/usr/bin/env bash
if ! [ -f "running_lock" ]; then tagui flow.tag; fi
```

And in your TagUI flow file, you set it up such that a dummy file helps to mark the status of the job -

flow.tag
```
dump [RUNNING] to running_lock
...
your TagUI steps and code
...
run rm /full_path/running_lock
```

The dummy file will be deleted after the job completes.

CC @ruthtxh on this interesting scenario

**Comment by delegate-it** [comment]
Thank you Ken. I managed to do it as you suggested. Below is the runner.sh file that I used.

`#!/usr/bin/env bash
FILE=/home/elhagen/compliance/rpas/running_lock

if ! [ -f "FILE" ]; then 
	/home/elhagen/tagui/src/tagui /home/elhagen/compliance/rpas/tax.tag -h > tax.log ; 
	rm /home/elhagen/compliance/rpas/running_lock
fi
`

**Comment by marcelocecin** [comment]
hi Nicolas
I have an example of how to run the script using [Celery with Redis](https://github.com/marcelocecin/TagUI-Podio)
it might make sense to you

**Comment by kensoh** [comment]
Thanks Marcelo for adding in! Oh nice Nicholas! This will you guarantee execution even if earlier runs fail.

**Comment by kensoh** [comment]
There's a small typo in your comment, I assume you meant `$FILE` in the if statement. I've updated your comment.

**Comment by kensoh** [comment]
Another idea is running with report option (-report or -r), this way you get all the historical logs, as well as a summary CSV file under tagui/src folder (tagui_report.csv) of all runs, time taken, and outcomes -https://tagui.readthedocs.io/en/latest/advanced.html#saving-run-results-of-flow
