### ISSUE TITLE
What are some of the main limitations of TagUI?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#116]
Raising this from an user email for sharing, as other users might benefit from this question.

---

What are some of the main limitations of the tool?

**Comment by kensoh** [comment]
There are many limitations of TagUI, below are some that I can think of now but there are many more.

- automation of desktop applications is done through visual recognition right now. planning to integrate with another open-source project (Roro or AHK) to control Windows applications on a native backend level to be able to cover more use cases ([more details at this issue](https://github.com/kelaberetiv/TagUI/issues/113))

- reading and writing directly to databases is possible now ([an example at this issue](https://github.com/kelaberetiv/TagUI/issues/112)), but I think there can be an easier way to do so. pending more datapoints from users, because different databases and different types of operations have different ways to invoke, not sure if there are stuffs general enough to be made into a new sql step

- extensibility is possible but limited now. developers can overwrite the code in TagUI's core engine. but with each upgrade their custom code will be missing and they have to add again. probably gotta make it easier for people to have a copy of their customizations which will continue to work with new TagUI upgrades. ([more details on this roadmap issue of TagUI](https://github.com/kelaberetiv/TagUI/issues/83))

- possibly repackaging TagUI so that it can be a Python library or R library for example. So that users from Python or R can directly make UI interactions by creating a tagui object and uses its methods (the current TagUI steps) to interact with websites or desktop applications. this is challenging as it might suddenly invite a lot of new users, and along with that many new support issues. but i think this is something i want to explore. ([more details on this roadmap issue of TagUI](https://github.com/kelaberetiv/TagUI/issues/83))

- unlike commercial RPA tools designed for enterprise, there is no nice visual dashboard or reporting features. for example initiating and controlling robots from a central web-app or electron desktop app for parallel runs, or having nice reports of all the robots' activities in your office for the month. ([more details on this roadmap issue of TagUI](https://github.com/kelaberetiv/TagUI/issues/83))

- there is already native integration with Python and R, so that users can call their machine learning models and frameworks for decision making. but current state of AI is very specific and can only solve narrowly defined problems. combining rule-based logic + machine learning models will probably expand the range of what can be automated. but we are still very far from general artificial intelligence ([check out this insightful article](https://www.edge.org/conversation/kai_fu_lee-we-are-here-to-create))

- there is no integration with hardware robotics actuators and sensors. in theory it can be easily done with API calls to Arduino or Raspberry Pi webservices. to read inputs from camera and send outputs to actuators like robotic arms. I've just bought below robotic arm on my own and also OpenMV Cam. When i get some time, i'll like to build physical integrations so that RPA workflows can extend beyond what's happening inside a computer to the external physical environment.

![robotic_arm](https://user-images.githubusercontent.com/10379601/38401929-3c365534-398b-11e8-9882-dcb051863c89.jpg)

**Comment by athbharat** [comment]
Is there a plan to add Mesos in TagUI?

**Comment by kensoh** [comment]
If you are referring to Apache Mesos - http://mesos.apache.org then no there is no plan to add native integration with it. However, as Mesos is used through various ways, you should be able to use existing TagUI features to integrate and automate it -

For Mesos command line - use run step
For Mesos HTTP APIs - use api step
For Mesos web interface - use usual TagUI web automation steps or visual automation

See more under pro steps in - https://github.com/kelaberetiv/TagUI#steps-description
More on api step and examples in - https://github.com/kelaberetiv/TagUI#api

CC fyi @siowyisheng. Oh I realise a few sections from Developer Reference not in readthedocs. API, Files and Security details will be useful for developers building stuffs using TagUI. Is there a way to store this info (and other removed parts) after they are removed from readme so that users who can benefit from the info can still have access to them?
