### ISSUE TITLE
How to write into a particular cell of a csv file? - consider using Excel integration?

### ISSUE THREAD

**Issue by TejasShete1196** [kelaberetiv/TagUI#1160]
As in my business case scenario, I want to add loop on csv file and add data into last column of same csv file so that at the time of running same bot again it will start from new row which is not processed. how it can be done?

**Comment by kensoh** [comment]
Are you familiar with JavaScript? There is Excel integration which you can read rows and range of data, and make modifications. However, some JavaScript is needed to loop through the data and process. See examples - https://tagui.readthedocs.io/en/latest/reference.html#excel
