### ISSUE TITLE
Bug on headless mode with report and pdf saving - can't replicate, usage pattern

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#1162]
Hi
I'm using the latest version of TagUI (v6.105) on MacOS
when I run the command `-r` with the `-headless` option the report is not saved
and if I use the `snap page to file.pdf` command the file is also saved in a corrupted way
please validate this bug
thanks

**Comment by kensoh** [comment]
Hi Marcelo, thanks for raising this!

For issue 1, can you go to the tagui/flows/samples folder and enter the following?

```
tagui 1_google.tag -headless -report
```

After I run above, there is a new report entered into the report tagui/src/tagui_report.csv

For issue 2, can you edit the 1_google.tag, and change the last line to below, then run again with -headless

```
snap page to top_result.pdf
```

After I run using the updated 1_google.tag, it captures PDF file correctly below -
[top_result.pdf](https://github.com/kelaberetiv/TagUI/files/7843739/top_result.pdf)

PS - I'm running MacOS Catalina

**Comment by marcelocecin** [comment]
sorry Ken I forget to mention that it happens when the option -quiet is also used

**Comment by kensoh** [comment]
Oh when -quiet option is used, there is no logging to the screen or log file. Because of this, the -report option would be invalid (no data to capture since there isn't any logging to log file or to the screen).

**Comment by kensoh** [comment]
Is there another way for you to achieve your use case without using -quiet option?

If the goal is to hide sensitive data from being in the log, what you can do is in your script, set the variable quiet_mode accordingly at sections which you have sensitive info.

```
// normal tagui steps

quiet_mode = true

// sensitive steps like keying in password

quiet_mode = false

```

**Comment by kensoh** [comment]
In above way, sensitive info will not be shown on the screen nor logged to the generated log.

**Comment by marcelocecin** [comment]
I understand, it makes sense Ken
however, the bug of saving the page in PDF occurs when these options are put together

**Comment by kensoh** [comment]
Hi Marcelo, can you send me your script to try replicating? Let me know more about your OS too, and the full command line you use to run TagUI. From above https://github.com/kelaberetiv/TagUI/issues/1162#issuecomment-1009593142 the PDF file seems to be saved correctly.

**Comment by marcelocecin** [comment]
`trady.tag`
```
https://www.trady.com.br/index.php/agenda/
snap page to trady.pdf
```
`tagui trady.tag -h -r`
[trady.pdf](https://github.com/kelaberetiv/TagUI/files/7871822/trady.pdf)

**Comment by kensoh** [comment]
Hi Marcelo, oh this is usage issue. The snap step will immediately send instruction to Chrome to save a PDF file, it does not wait until webpage is fully loaded or if there are items still loading in progress. In above case, you can add a `wait` before the snap step and it should work. If the load speed is slow, you can try `wait 10`.

For my 1_google.tag example above, there are interactions with the webpage with auto-wait in place. And there is a `wait 3` as well in order to give some time for webpage results to be fully loaded.

**Comment by marcelocecin** [comment]
perfect Ken
it worked out
thanks
