### ISSUE TITLE
TagUI new chrome session does not keep user logged in - pending checks, some ideas

### ISSUE THREAD

**Issue by avv2202** [kelaberetiv/TagUI#1165]
Website XXX uses 2FA which cannot be handled by tagui. So I authenticate outside tagui and reach to the website's landing page. Now if I copy paste the landing page's URL into another chrome instance (new window/instance not a new tab), I am able to navigate through the webpages in the new window as the server interprets me as "logged in". Now I intend to do exactly the same using tagui, i.e. once I log in manually with 2FA, I will run a tag script with the landing page URL as the starting point and work with my logic thereafter. However, this does not work and the browsers throws me back to the sign up page when run through tagui. Is there any way I can achieve this?

**Comment by marcelocecin** [comment]
try to find some chrome extension that solves the 2FA process

**Comment by ruthtxh** [comment]
Hi @avv2202 

TagUI uses a separate Chrome user profile for web automations, so if you have noticed, whenever you launch an automation, a new session of Chrome opens, and not on your existing Chrome.

You can try to add a live step during the login portion, for you to manually key in your 2FA details, then type done (in the command prompt) to quit the live step and proceed with the other automation steps.

```
live
// your other steps like click echo etc...
```

https://tagui.readthedocs.io/en/latest/reference.html?#live

**Comment by avv2202** [comment]
I am trying as you said. But 1 thing I forgot to mention earlier, is that when I open the website from a tagui session, the 2FA authentication code (like a capcha) does not get displayed on the webpage. That area just keeps spinning "Loading...." but if I open it outside tagui from a regular browser session all works fine. So unless this is sorted I cannot proceed with the solution suggested above.

**Comment by kensoh** [comment]
Oh this is interesting. One thing you can check is if popups are allowed on the TagUI browser. If not, you can click the top-right part of the browser, there should be some icon to choose allow popup. My best guess is for TagUI browser, you have not allowed popups, that's why the 2FA window cannot show up.

Also, as an alternative, see if you can join our weekly Zoom Q&A to troubleshoot together. It's every Thursday 4-5pm SGT (UTC+8), so it is convenient time zone for Asia, India and early morning for Europe. Here's the link - https://github.com/kelaberetiv/TagUI/issues/914

**Comment by avv2202** [comment]
@kensoh ,
The 2FA code opens in the same window and all the webpage opens except the code. There is no popup/separate window. I have attached a screenshot. What you see in the screenshot is the area that does not load at all. Rest of the page loads 100%. 
Btw, thank you for your invite to the call, but I checked with my team and I wont be able to demonstrate this on the LIVE site due to security issues. I will check if I can replicate this locally
![Selection_127](https://user-images.githubusercontent.com/97892040/149889928-33ec6216-e250-41b0-bc6e-d3b0168e19db.png)
.

**Comment by kensoh** [comment]
Oh this is very puzzling. Unless... This website has some security checks to prevent users from accessing the website using an automated browser. For TagUI to be able to control Chrome from its backend, there is a backdoor open for that browser session. This might be the reason.

Alternatively, if you can't replicate, you can try automating the whole workflow using visual automation? You can use a combination of image snapshots and keyboard and mouse automation. See if that works for you. This method does not require using TagUI browser and you can automate directly on your normal browser.

**Comment by avv2202** [comment]
@kensoh 
The captcha code failing to load was not a TagUi issue. I figured that the code loads if the user takes a certain path to that page. Like - from page x, then y and then z etc. Sorry for the trouble. Will check my primary issue now.

**Comment by kensoh** [comment]
Oh I see.. Thanks for updating back!

Adding on, you can try using x y coordinates to move the mouse around to see if that helps.

```
echo `mouse_xy()`
hover (100,400)
echo `mouse_xy()`
hover (800,200)
echo `mouse_xy()`
```
