### ISSUE TITLE
echo variable,the output is the variable name - incorrect syntax, check this example

### ISSUE THREAD

**Issue by duxiaoyan22** [kelaberetiv/TagUI#1168]
I write a test.tag file,the content is bellow:
a='123'
echo a

 when I use the command tagui **test.tag**,the output is **a**,not **123**.

**Comment by kensoh** [comment]
Hi the syntax is, you might have miss that in the usage guide.

```
echo `a`
```

Without the backticks, TagUI will treat the text as plain text and not variables.

**Comment by duxiaoyan22** [comment]
> the syntax is, you might have miss that in the usage guide.

Thanks very much

**Comment by kensoh** [comment]
Welcome Xiaoyan!
