### ISSUE TITLE
Tried calling a JavaScript custom function but it not seems to be working - use js begin / finish

### ISSUE THREAD

**Issue by Anujpalu24** [kelaberetiv/TagUI#1169]
function Check() {
        var chkPermission = document.getElementById("permission-218");
        if (chkPermission .checked) {
            echo "CheckBox checked"
        } else {
            echo "CheckBox not checked"
            Dom document.getElementById("permission-218").click();
        }
    }
getting below error for the same : ERROR - use a consistent number of spaces for indentation

UseCase : Here we want that if checkbox is checked dont do anything but if unchecked, check the same checkbox.

**Comment by Anujpalu24** [comment]
Any update on the same

**Comment by ruthtxh** [comment]
Hi @Anujpalu24 you can use javascript code in between the js begin and js finish blocks. Here's an example if you want to echo the results outside the block.

```
output = ""
js begin
function Check() {
if (1==1) {
output = "true";
} else {
output = "false";
}
}
Check();
js finish
echo `output`
```

**Comment by kensoh** [comment]
Closing issue for now, but please let us know if you still run into issues!
