### ISSUE TITLE
PHP Warning:  Undefined variable $scan_period - do tagui update for the bug fix

### ISSUE THREAD

**Issue by loweaxerium** [kelaberetiv/TagUI#1175]
Hello friends! Have been getting this error lately while running tagui on macOS, can you please help!

**Comment by kensoh** [comment]
Hi @loweaxerium, can you try doing `tagui update` from your terminal?

There is recent fix which handles this warning message from newer versions of PHP, which could be the case here for example when you upgrade macOS or somehow updated your PHP version. After doing `tagui update`, the warning message should go away. Let us know if it doesn't.

**Comment by loweaxerium** [comment]
Thanks a lot Ken, worked perfectly!
