### ISSUE TITLE
Import TagUI File, more specifically it is running sub-flows - see examples and docs

### ISSUE THREAD

**Issue by imkrishnendu92** [kelaberetiv/TagUI#1176]
Hi Kensoh,

Hope you are doing great!!!

I want to know how to call multiple tag file in TagUI?

**Comment by lookang** [comment]
https://github.com/lookang/TagUI/blob/main/login/runall.sh

I use a shell command file to run different files like tag and py on a MacBook.

There should be a way to do the same thing on Windows.

**Comment by imkrishnendu92** [comment]
Hello Lookang,

Particularly I want to know how to import one tag file to another tag file in tagui?

**Comment by lookang** [comment]
I think it is the same as in command prompt. It is to run one tag file with another tag file inside it right?


tagui filename.tag

I don't have an existing example. Most of the time, I run one tag by one tag in shell.
In command prompt type
sh runall.sh

**Comment by imkrishnendu92** [comment]
how to reuse one tag file code in another one tag file (like I want store for loop code in one tag file and then I want to call for loop in multiple in tag file)

**Comment by marcelocecin** [comment]
you can call one script inside another using tagui command
example `001.tag`: 
```
echo One
```
example `002.tag`: 
```
tagui 001.tag
echo Two
```
then run `tagui 002.tag -q -h`
<img width="783" src="https://user-images.githubusercontent.com/2955762/152185847-c53c3498-6b32-455d-9459-4817121035d5.png">

**Comment by imkrishnendu92** [comment]
when you call another tag file is it necessary to run in quiet and headless mode?

**Comment by marcelocecin** [comment]
nope

**Comment by marcelocecin** [comment]
here is the documentation about [running-flows-within-a-flow](https://tagui.readthedocs.io/en/latest/advanced.html?#running-flows-within-a-flow)

**Comment by ruthtxh** [comment]
Hi @imkrishnendu92 

Yes, you can check out the documentation on subflows as per the comment above.

If you need to call the other flow file name as a variable you can check out some examples here: https://github.com/kelaberetiv/TagUI/issues/1008#issuecomment-849561356
