### ISSUE TITLE
Notepad++ TagUI Language Dictionary and Code Snippets - Md Ardyansyah created

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1178]
Ardy from Indonesia has created a Notepad++ dictionary and snippets.

Attached is the initial version, to follow-up on linking to his GitHub repo.

**Comment by kensoh** [comment]
[Notepad++.zip](https://github.com/kelaberetiv/TagUI/files/7999564/Notepad%2B%2B.zip)

**Comment by kensoh** [comment]
Video and report here - https://github.com/tilyanPristka/TagUI-Snippets-for-NotepadPP

**Comment by kensoh** [comment]
Updated to GitHub readme and credits

**Comment by kensoh** [comment]
https://github.com/kelaberetiv/TagUI#do-rpa-any-way-you-want

https://github.com/kelaberetiv/TagUI#credits

**Comment by ruthtxh** [comment]
Tried out the code snippets here are some of my comments:

1. Installation:

- To import TagUI user define language go to Notepad++ ribbon `Language > User Define language > Define your language...` then click Import and select your TagUI-UserDefine.xml file.
![image](https://user-images.githubusercontent.com/40910744/152932711-5a274cbc-399a-49b7-a7fe-a0c47962c53d.png)
![image](https://user-images.githubusercontent.com/40910744/152933389-bd1ccea2-b778-4d27-88b9-0fb4d1d18943.png)

- TagUI Snippets in Notepad++
After installing Snippets plugin, to import the TagUI library, `right-click top of Snippets taskpane > Import library...` then select your TagUI-Snippets.sqlite file.
![image](https://user-images.githubusercontent.com/40910744/152932761-b39e6fac-9d65-4da2-8ba2-82ba99d1b5ac.png)

- For TagUI library to appear in Snippets taskpane, you have to be using the TagUI user define language first
![image](https://user-images.githubusercontent.com/40910744/152934044-5df574a1-7f0e-437b-a78a-f64561efed7d.png)

2. For running the code from Notepad++:

- Run TagUI command as per documentation turns on turbo mode (-t)
```
<Command name="Run TagUI" Ctrl="no" Alt="yes" Shift="yes" Key="84">cmd /K cd /D $(CURRENT_DIRECTORY) &amp;tagui $(FILE_NAME) -t &amp;pause &amp;exit</Command>
```

3. Other comments:
- Web Visit (URL) step can take in https:// http:// or www. prefixes
