### ISSUE TITLE
Can't access variable outside js code block - try this

### ISSUE THREAD

**Issue by tidet** [kelaberetiv/TagUI#1180]
Hey,
open an issue is my last chance, now "googling" since two hours - even read the docs more than ten times if i miss something out.

I have a JS block and an input field where I have to type in something out of the js block.

**JS:**
js begin
var tmpDate = new Date()
tmpDate .setDate(tmpDate.getDate() - 1)
var date = {}
date.year = tmpDate.getYear()+1900
date.month = (tmpDate.getMonth()) + 1
date.day = tmpDate.getDate()
date.raw = tmpDate
var month =date.month < 10 ? '0' +date.month :date.month
var day =date.day < 10 ? '0' +date.day:date.day
var year =date.year
date.formatted = day + "." + month + "." + year
var yesterday = date.formatted
js finish

I've tested both and checked the xPath (shortened here!) three times. If I use ; in JS or not did not change anything. Function is working in live editor if i do console.log(yesterday); then everything is correct.

**Type:**
wait 10
type _xPath_ as [clear] \`yesterday\`
wait 10
type _xPath as [clear] ‘+yesterday+’

I've tested around, but everytime i get the same error if it comes to "type":
`» ERROR - can't find variable: yesterday`

How can i use the var `yesterday` from within `js begin` and `js finish` outside the js block for a `type` interaction?

**Comment by marcelocecin** [comment]
```
https://www.google.com/
js begin
var tmpDate = new Date();
tmpDate.setDate(tmpDate.getDate() - 1);
var date = {};
date.year = tmpDate.getYear()+1900;
date.month = (tmpDate.getMonth()) + 1;
date.day = tmpDate.getDate();
date.raw = tmpDate;
var month = date.month < 10 ? '0' +date.month:date.month;
var day = date.day < 10 ? '0' +date.day:date.day;
var year = date.year;
date.formatted = day + "." + month + "." + year;
var yesterday = date.formatted;
js finish
yday = yesterday
wait
type //*[@name="q"] as `yday`
wait
```

**Comment by ruthtxh** [comment]
Hi @tidet, yes above example by Marcelo is correct, you have to first initialise a variable outside the js code block then you can use that initialised variable.

For example you can do  `yesterday = ""` or `yesterday = new Date()`. For Marcelo example, he initialised another variable yday to be used in the type step.

```
yesterday = new Date()

js begin
var tmpDate = new Date()
tmpDate .setDate(tmpDate.getDate() - 1)
var date = {}
date.year = tmpDate.getYear()+1900
date.month = (tmpDate.getMonth()) + 1
date.day = tmpDate.getDate()
date.raw = tmpDate
var month =date.month < 10 ? '0' +date.month :date.month
var day =date.day < 10 ? '0' +date.day:date.day
var year =date.year
date.formatted = day + "." + month + "." + year
yesterday = date.formatted
js finish

type xPath as `yesterday`
```

**Comment by ruthtxh** [comment]
Thanks @tidet, I've added an example to the docs.
