### ISSUE TITLE
How to find XPath in Gmail? - some tips

### ISSUE THREAD

**Issue by jamesnyika** [kelaberetiv/TagUI#1181]
Ken
 What a fantastic tool you created for the world here. I love it and am using it to do a password reset through Google mail. 
 Do you have an example showing how to do it ? Gmail is hard since you cannot easily inspect the row with the email. 

Any help appreciated !

**Comment by ruthtxh** [comment]
Hi @jamesnyika 

There is actually a way to get the xpath of the rows of email on gmail. While you cannot right click and directly inspect the rows of email, you can right click the top portion of gmail where you can inspect, then slowly expand the elements in the pane and find the element you are looking for by checking against what is highlighted on the UI when you expand and hover it in the pane.

Here's an example of the absolute xpath I got of the first email
```
/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[1]/div[8]/div/div[1]/div[3]/div/table/tbody/tr[1]
```

**Comment by jamesnyika** [comment]
Hi @ruthtxh ...I actually was able to use an XPath extension to get a similar path. But notice that it simply points to a TR element. I am guessing that Google is probably using javascript to submit any click events on this element rather than an anchor tag. So my question is: if you run a click on this : does it actually go to the email ? have you had success with this ? because I think I tried and could not get it to work (particularly after a search for emails matching a specific piece of text)

**Comment by ruthtxh** [comment]
Hi @jamesnyika yes, clicking that XPath in TagUI works for me. What error message do you get?

**Comment by jamesnyika** [comment]
Hi @ruthtxh - I need to try it out again : I feel I have had more experience in the last few days.. let me see if I can get it working and report back.

**Comment by ruthtxh** [comment]
Closing this issue for now due to inactivity, feel free to reopen.
