### ISSUE TITLE
I got an issue (SyntaxError in my TagUI script) - some tips

### ISSUE THREAD

**Issue by imkrishnendu92** [kelaberetiv/TagUI#1183]
Hi @kensoh @lookang @marcelocecin @ruthtxh, I'm having trouble with if/else statements in general and I think something is wrong with my syntax. can pleae help me to solve this problem

Here is my code:
for (loop_wait=1; loop_wait<=wait_loop; loop_wait++)
	{
		wait 5
		if present(path_to_check)
		{
			click `path_to_check`
			break
		}
		wait 3
		else if present (new_path_to_check)
		{
			click `new_path_to_check`
			break
		}
	}

Output: SyntaxError: Unexpected token 'else'

  phantomjs://code/test_ifelse.tag.js:2008 in injectJs
  phantomjs://code/bootstrap.js:456

**Comment by ruthtxh** [comment]
Hi @imkrishnendu92 

After some debugging I think the wait 3 is causing the error. The following works for me:

```
wait_loop = 3
path_to_check = "windows.png"
new_path_to_check = "mail.png"

for (loop_wait=1; loop_wait<=wait_loop; loop_wait++)
{
wait 5
if present(path_to_check)
{
click windows.png
wait 3
break
}
else if present(new_path_to_check)
{
click mail.png
break
}
}
```

while you can pass the variables `path_to_check` and `new_path_to_check` to the present function, it is best to use the click full path on the click step instead of a variable.

**Comment by imkrishnendu92** [comment]
Thanks @ruthtxh now it's working fine.
