### ISSUE TITLE
How to change filename? - use OS level commands

### ISSUE THREAD

**Issue by imkrishnendu92** [kelaberetiv/TagUI#1184]
I'm having trouble changing with downloaded file name, and I know the syntax for download directory 
Syntax : download to [folder location]
but somehow I want to change the downloaded file name so is it possible in TagUI?

@kensoh @lookang @marcelocecin @ruthtxh, Please help me

**Comment by ruthtxh** [comment]
Hi @imkrishnendu92 you can use your OS level commands, if you are on windows you can do the following with the run command:
```
run cmd /c cd folder_location && ren old_file_name new_file_name
```
this changes directory to where the file is located and renames it from the old file name to new file name.

**Comment by fjchavez** [comment]
Hello,

I have the script already assembled and running in cmd.
The question is how do I add it to tagui.
Would it be something like this?

`run cmd /c echo "Termina Proceso de Extracción"`
`run cmd /c echo "Inicial Proceso de Traslado de archivos extraidos"`
`run cmd /c cd C:\Users\FranCiscO\Downloads`
`run cmd /c mkdir %date:~6,4%%date:~3,2%%date:~0,2%`
`run cmd /c move *.xls %date:~6,4%%date:~3,2%%date:~0,2%`
`run cmd /c D:`
`run cmd /c cd "D:\Google Drive\Mc Laren\Forecast"`
`run cmd /c mkdir %date:~6,4%%date:~3,2%%date:~0,2%`
`run cmd /c xcopy C:\Users\FranCiscO\Downloads\%date:~6,4%%date:~3,2%%date:~0,2% %date:~6,4%%date:~3,2%%date:~0,2% /E /H /C /I`
`run cmd /c rd /s /q C:\Users\FranCiscO\Downloads\%date:~6,4%%date:~3,2%%date:~0,2%`
`run cmd /c echo "Termina Proceso de Traslado de archivos extraidos"`

The syntax is correct?

**Comment by ruthtxh** [comment]
Hi @fjchavez 

Yes you can use the run step to launch the command prompt and run commands. Something to note, if you want to echo back into the command prompt used to run TagUI, you can use echo step instead of run step: `echo something`

**Comment by kensoh** [comment]
Closing the issue, but feel free to ping back or reopen if anything!

**Comment by pp082** [comment]
Hi!!

Context: in before steps download a file. The file name contains spaces and cant move with the command 
run mv `[pathFile_ini]` `[pathFile_fin]`
where pathFile_ini and pathFile_fin are variables containing the full path.

for this reasons i need change name the filename.

I need run the next command but the execution is stuck
```
run for f in * ; do mv "$f" "${f// /_}" ; done
echo 2 `[run_result]`
```

thats is worked on terminal, but I when put in the tagui command dosen't worked and got stuck
`for f in * ; do mv "$f" "${f// /-}" ; done` 

Tagui is a exceptional tools.
Thanks in advance

**Comment by ruthtxh** [comment]
Hi @pp082 I believe you have asked the same question here https://github.com/kelaberetiv/TagUI/issues/1262, will follow up there.

**Comment by OwensLopez211** [comment]
Hi @everyone im trying to automate downloads of pdf´s from a web but im doing it with a `keyboard [ctrl]s` step. the thing is that the pdf download with the default name, I have a variable named `fondo_name`  and i want to download the file with the variable name.

Some have any idea?

pd: sorry for my english :(

```
load C:\tagui\ReglamentoInterno\datos_tabla.csv to csv_content
rows = csv_content.split('\n')

index = 1
// procesar cada fila del CSV
for row from 2 to rows.length()
{
// dividir la fila en columnas
columns = rows[row-1].split(',')
// obtener el nombre del fondo
nombre_fondo = columns[1].trim()
vigencia = columns[3].trim()
if vigencia == "Vigente"
{
https://www.cmfchile.cl/portal/principal/613/w3-	search.php?keywords=larrainvial#fiscalizados
keyboard [ctrl]f
keyboard `nombre_fondo`
if present(nombre_fondo)
{
click `nombre_fondo`
wait 5
keyboard [ctrl]f
keyboard Reglamento Interno
dclick Reglamento Interno
wait 2
keyboard [ctrl]f
wait 5
keyboard Descarga
click Descarga
wait 5
download to C:\tagui\ReglamentoInterno\reglamentos
wait 2
keyboard [ctrl]1
keyboard [ctrl]2
keyboard [ctrl]w
}
}
}

```
