### ISSUE TITLE
Need list of scripts to run command - some tips

### ISSUE THREAD

**Issue by Diyazsdirr94** [kelaberetiv/TagUI#1185]
Hi

Im currently new to TagUI and the RPA system. Im doing a project to automate our HR processes.

Do you have list of scripts for command prompt to run a few steps?

1. I would like the system to select certain range of field to highlight text file and copy it to a spreadsheet cell.
2. I would like the system to match a certain range of text that I want.
3. I would like the system to repeat the steps previous steps automatically.

**Comment by ruthtxh** [comment]
Hi @Diyazsdirr94 

1. This depends on whether you are automating the HR process on a webpage in the browser or on the desktop:
If it is a web automation you can use the read step to read xpath and then the excel step to populate it to excel.
```
https://en.wikipedia.org/wiki/Main_Page
read //*[@id="mp-tfa"]/p to text
[sample.xlsx]Sheet1!A1 = text
```
See documentation here:
https://tagui.readthedocs.io/en/latest/main_concepts.html#read
https://tagui.readthedocs.io/en/latest/main_concepts.html#excel

If you are on desktop you can use keyboard step to copy some text, then access it using the clipboard helper function. See example here:
https://tagui.readthedocs.io/en/latest/main_concepts.html#clipboard

https://tagui.readthedocs.io/en/latest/main_concepts.html#clipboard

2. You can make use of javascript functions to do the matching
```
text = "abc"
if (text.indexOf("abc")>-1)
  echo yes
```

3. You can write nest the steps in side a loop to repeat them:
See https://tagui.readthedocs.io/en/latest/main_concepts.html#for-loops
You can try out the example that came with your installation here: tagui/flows/samples/4_loops.tag
