### ISSUE TITLE
Running TagUI as a Lambda Function - see if running Chrome alone works

### ISSUE THREAD

**Issue by rikthomas** [kelaberetiv/TagUI#1189]
I am trying to see if I can run a simple flow as a Lambda function using container images. I have made a Dockerfile which runs fine locally:

```
FROM amazonlinux:2

RUN yum install -y wget nano php java-1.8.0-openjdk unzip procps

RUN curl https://intoli.com/install-google-chrome.sh | bash

RUN wget https://github.com/kelaberetiv/TagUI/releases/download/v6.46.0/TagUI_Linux.zip \
    && unzip TagUI_Linux.zip \
    && rm TagUI_Linux.zip \
    && ln -sf /tagui/src/tagui /usr/local/bin/tagui \
    && tagui update

RUN sed -i 's/no_sandbox_switch=""/no_sandbox_switch="--no-sandbox"/' /tagui/src/tagui

ADD tr.tag /tr.tag

ENTRYPOINT cp -r tagui tmp; cp tr.tag tmp; ./tmp/tagui/src/tagui /tmp/tr.tag -h
```

Notes: 
- the ```sed``` line is required to get it running in docker images. I think this is a bug as I see the bash script should detect Docker or running as root. I worked that out from #780 but have not had time to look into it and do a PR (sorry).
- tr.tag is just a simple flow to do a password reset on a webapp so I can confirm the container has run.
- everything has to be run in /tmp as that is the only folder Lambda can write to in the container.

When I run as a Lambda I get the error:

```./tmp/tagui/src/tagui: line 398: 56 Trace/breakpoint trap (core dumped) $chrome_command --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size $headless_switch $no_sandbox_switch > /dev/null 2>&1``` 

Locally it runs instantly. I've got the memory and timeout cranked right up on the Lambda.

Does anyone have any ideas? The end goal here is to use an API Gateway to receive some data and trigger a flow.

**Comment by ruthtxh** [comment]
Hi @rikthomas I am not too sure about running on lamdba, my guess is there might be a problem with the google chrome installation. Are you able to check if chrome is installed and running properly?

**Comment by rikthomas** [comment]
Google Chrome is definitely installed and working correctly from the point of view of the container. When I run the container locally everything works as expected. Based on other posts and  [this tutorial](https://aripalo.com/blog/2020/aws-lambda-container-image-support/) I have worked on my container so it now looks like this:

```
FROM amazon/aws-lambda-provided:al2

RUN yum install -y wget nano php java-1.8.0-openjdk unzip procps

RUN curl https://intoli.com/install-google-chrome.sh | bash

RUN wget https://github.com/kelaberetiv/TagUI/releases/download/v6.46.0/TagUI_Linux.zip \
    && unzip TagUI_Linux.zip \
    && rm TagUI_Linux.zip \
    && ln -sf /var/task/tagui/src/tagui /usr/local/bin/tagui \
    && tagui update 

RUN sed -i 's/no_sandbox_switch=""/no_sandbox_switch="--no-sandbox"/' /var/task/tagui/src/tagui

ADD tr.tag /var/task/tagui/src/tr.tag

WORKDIR /var/runtime/
COPY bootstrap bootstrap
RUN chmod 755 bootstrap

WORKDIR /var/task/
COPY function.sh function.sh
RUN chmod 755 function.sh

CMD [ "function.sh.handler" ]
```
My function.sh:

```
function handler () {
   cp -r /var/task/tagui/src/* /tmp;
   chmod 755 /tmp/tagui;
   OUTPUT=$(/tmp/tagui /tmp/tr.tag -h);
   echo "${OUTPUT}";
}
```

But I still get the same error

```./tmp/tagui/src/tagui: line 398: 56 Trace/breakpoint trap (core dumped) $chrome_command --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size $headless_switch $no_sandbox_switch > /dev/null 2>&1```

**Comment by ruthtxh** [comment]
Hi @rikthomas sorry I don't have the means to test on the same environment as you. However you can check out how @ardyan69 got TagUI running on Ubuntu, perhaps the dependencies he downloaded is something you would like to consider.
[install TagUI on Ubuntu.txt](https://github.com/kelaberetiv/TagUI/files/8258443/install.TagUI.on.Ubuntu.txt)

**Comment by kensoh** [comment]
An angle to try debugging this is to confirm if the problem is due to Chrome.

You can try changing below line in your function -
```
OUTPUT=$(/tmp/tagui /tmp/tr.tag -h);
```

To the line below, and see if there is any error launching Chrome -
```
OUTPUT=$(google-chrome --window-size=1366,768 --headless --disable-gpu --no-sandbox);
```

Many years ago, I heard that Lambda memory space isn't sufficient to run Chrome browser, not sure if that has changed.

**Comment by kensoh** [comment]
Maybe fine to close until further inputs from users
