### ISSUE TITLE
Close google chrome after flow ends - try updating tagui

### ISSUE THREAD

**Issue by fjchavez** [kelaberetiv/TagUI#1191]
Hello!

I have this question.
How can I close google chrome after flow ends?

**Comment by ruthtxh** [comment]
Hi @fjchavez by default google chrome will close after the flow ends. Does your google chrome not close? Can you check with version of TagUI you are running on, by running the `tagui` command in command prompt or terminal.

**Comment by fjchavez** [comment]
Hi @ruthtxh ,

The version is tagui v6.74. My OS is Windows 11.
I made these changes in tagui

// Changed tagui.cmd to open google chrome in incognito: chrome_switches=--user-data-dir=chrometagui_user_profile --incognito --remote-debugging-port=9222 about:blank
// Changed tagui_parse.php in setDownloadBehavior from allow to default

Maybe it is because of these changes? If so, how do I make it close keeping these changes?

**Comment by ruthtxh** [comment]
Hi @fjchavez 

Can you try updating tagui and see if the error persists? You can update by running `tagui update` from the command prompt.

**Comment by ruthtxh** [comment]
Closing issue due to lack of updates, feel free to reopen.
