### ISSUE TITLE
How to pass proxy credentials in tagui? - some tips

### ISSUE THREAD

**Issue by riya-coddle** [kelaberetiv/TagUI#1193]
Hi, 

I'm trying to use proxy for headless chrome. I managed to set the proxy by adding proxy server string in chrome_switches (in tagui file in src folder) like this: --proxy-server=http://proxyurl:port_no

But the problem is that the proxy server requires authentication and I couldn't find how to set it in tagui. 
Tried to pass the credentials like this but didnt work:  --proxy-server=http://username:password@proxyurl:port_no

Also tried to set username and password in tagui_config file's casper.options.pageSettings like this but that didnt work either: 
casper.options.pageSettings = {
  loadImages: true,
  loadPlugins: true,
  webSecurityEnabled: false,
  ignoreSslErrors: false,
  localToRemoteUrlAccessEnabled: true,
  userName: username,
  password: password
}

Any help or suggestions on this would be greatly appreciated!

**Comment by ruthtxh** [comment]
Hi @riya-coddle you can try the solution [here](https://github.com/kelaberetiv/TagUI/issues/162#issuecomment-516743499)

**Comment by ruthtxh** [comment]
Closing issue due to lack of updates, feel free to reopen.
