### ISSUE TITLE
flow stops after datatable first iteration - pending details

### ISSUE THREAD

**Issue by TejasShete1196** [kelaberetiv/TagUI#1194]
In my business case scenario the complete tagui code flow files are on the xyz server and input and deployed windows command file both are on the same server . While running the deployed main flow file with using input CSV file as datatable after very first iteration the command file stops execution and sometimes it continues to work any particular reason behind this case???

**Comment by ruthtxh** [comment]
Hi @TejasShete1196, what version of TagUI are you running on? You can run `tagui` in the command prompt/terminal to check.

**Comment by TejasShete1196** [comment]
Hello @ruthtxh 
I am using tagui  version 6.48
Does that needs to be changed?

**Comment by ruthtxh** [comment]
Hi @TejasShete1196 yes you would need to update to a later version to get that to work!

Please go to command prompt and run `tagui update` to pull the latest version. Let us know if error still persists.

**Comment by TejasShete1196** [comment]
Sure I will try this and let you know.

**Comment by TejasShete1196** [comment]
Hello @ruthtxh 
Also does the location of deployed file matters while running the bot ?  Is it necessary that deployed file must be in the same folder where the code is present.

**Comment by ruthtxh** [comment]
Hi @TejasShete1196, you may deploy it to a different location, and the executable file will be created there. However, the flow/code files should remain in their original location so the executable file can reference to their file paths correctly.

**Comment by ruthtxh** [comment]
Hi @TejasShete1196 you can download a copy of the latest version [here](https://github.com/kelaberetiv/TagUI/archive/master.zip) and paste over your tagui/src folder.
