### ISSUE TITLE
How to break script? - some tips

### ISSUE THREAD

**Issue by PepijnVogelzangGO-Sharing** [kelaberetiv/TagUI#1196]
read //tr[`row`]/td[@class="ant-table-cell ant-table-column-sort"] to Balance
if `Balance` > -500
(tab) break

we want to break powershell if the amount is above -499,99 how does this work?

**Comment by marcelocecin** [comment]
https://github.com/kelaberetiv/TagUI/blob/master/flows/samples/3_conditions.tag

**Comment by PepijnVogelzangGO-Sharing** [comment]
Tagui sees `balance` as  a string, not an integer. we want that tagui reeds a string as an integer

**Comment by marcelocecin** [comment]
you can run javascript inside tagui
https://tagui.readthedocs.io/en/latest/reference.html?highlight=javascript#js

**Comment by ruthtxh** [comment]
Hi @PepijnVogelzangGO-Sharing 

You don't require the backticks in the conditional statement
```
if Balance > -500
```

**Comment by kensoh** [comment]
Adding on, following is another way to exit -

```
this.exit();
```

or

```
js this.exit()
```
\
However this way will not work if you are doing datatable iteration, because it will exit the current iteration but continues the next iteration. @ruthtxh's method will exit TagUI completely, even if there are more iterations left.
