### ISSUE TITLE
Reading Excel problems with traditional Chinese content - change pc language settings

### ISSUE THREAD

**Issue by petertsneg** [kelaberetiv/TagUI#1199]
Reading Excel problems with traditional Chinese content.

code:
```
varString = [list.xlsx]Sheet1!A1
echo `varString`
varString = "中文"
echo `varString`
```
result:
```
Active code page: 65001
PS D:\rpa> tagui line.tag -n

START - automation started - Fri Mar 25 2022 20:27:21 GMT+0800 (台北標準時間)
varString = [list.xlsx]Sheet1!A1
����
中文

FINISH - automation finished - 3.4s

```
how do I fix that?
Thanks.

**Comment by jinjiaoyi** [comment]
Maybe the text is read correctly, but shown with wrong encoding in CLI? 
Try `chcp 936` to CHange Command Prompt temporary for Chinese Traditional, or `chcp 65001` for UTF-8.
FYI [read file has a Chinese field reporting an error - save CSV using Notepad or other text editor · Issue #687 · kelaberetiv/TagUI](https://github.com/kelaberetiv/TagUI/issues/687)

**Comment by ruthtxh** [comment]
Hi @petertsneg 

You can change your language settings on your pc. The following steps allow me to read the Chinese characters from excel correctly.

Click your windows icon then go to Language Settings
![image](https://user-images.githubusercontent.com/40910744/160365828-bd56b83a-49ef-4b59-8066-93f60ce38563.png)
![image](https://user-images.githubusercontent.com/40910744/160365907-7005bde8-0a11-4953-aa6b-1657bd538ecf.png)
![image](https://user-images.githubusercontent.com/40910744/160366074-dd8a7989-04ee-4c03-9c8b-aebb8bc6ca4a.png)

Output:
![image](https://user-images.githubusercontent.com/40910744/160366685-98fc7a05-f6b4-4b31-b2e9-44caadb00776.png)

**Comment by petertsneg** [comment]
Hi @ruthtxh ,

According to your method,
Problem solved, very thanks .

Thanks also for the reply from @jinjiaoyi .

**Comment by kangyiwen** [comment]
留个中文截图，看着更方便

![image](https://user-images.githubusercontent.com/76672577/168740133-2d54f90c-1ee2-4b8c-b8fc-9ecd3fe14a94.png)
