### ISSUE TITLE
Newbie How Read Value To Variable - try read step

### ISSUE THREAD

**Issue by arliec** [kelaberetiv/TagUI#1200]
Newbie here, I just want read and store the values ₱ 0.1907104 & +14.64% to a variables, pls help
![css-01](https://user-images.githubusercontent.com/32003068/160310794-0e81d583-ca40-4d88-9c2d-d5d6fb37c1a8.PNG)
.

**Comment by ruthtxh** [comment]
Hi @arliec I believe I've answered your query on telegram too!

You can try read step, like this
```
read xpath to text
a = text.substring(2)
b = a*1.1464
```
To get the xpath you can right click the highlighted element in your image and copy xpath
https://tagui.readthedocs.io/en/latest/main_concepts.html?#read
