### ISSUE TITLE
subflows can turn on/off -headless flag dynamically? - no, try chaining flows in .cmd file instead

### ISSUE THREAD

**Issue by pohhian** [kelaberetiv/TagUI#1201]
For tagui flow calling another flow, anyone know if there is 'headless_mode = false' etc ??
In another perspective, when calling another tagui flow, does it just reuse the instance of browser (hidden or not)? 
The original design is to have a simpler flow to 'detect' and check something, then if really has error, then only trigger another tagui flow (which contains vision) to execute something which is more complicated.  By having such design, the automation task can then run more 'quietly' and hidden, unless until really has issue.
Thanks in advanced for any information

**Comment by ruthtxh** [comment]
Hi @pohhian for subflows, you cannot specify parameters. It will inherit the parameters like headless mode etc from the main flow file you run. However from your scenario, it seems like the events happen in sequence and you can chain the flows together in a batch file by doing the following:

Create a .cmd file with the contents
```
call tagui flow1.tag -h && tagui flow2.tag
```
and you can run the file by double clicking it. This will run flow1 in headless and flow2 in normal mode.

**Comment by pohhian** [comment]
Thank you for the reply. The idea actually is to run flow1.tag first, then depending on certain "result/status", then it shall, or shall not, trigger flow2.tag (flow2.tag use visio so cannot be headless). 
I shall maybe have a cmd/batch file, to run flow1.tag, and then check its output, then decide whether to trigger flow2.tag.

**Comment by marcelocecin** [comment]
maybe the best way is to have another intermediate flow, in flow1 you could save the return in a text file, in the intermediate flow you can read and interpret the txt to decide whether to run flow2 or not

**Comment by kensoh** [comment]
Not sure if this is Ryan? 😄

Adding on, following could be experimented. I don't have a Windows laptop to validate below solution.

**flow1.tag**
```
dump run_flow2 to result.txt
```

**batch file**
```
call tagui flow1.tag -headless
set /p result=<result.txt
echo %result%
if %result%==run_flow2 call tagui flow2.tag
```

**Comment by pohhian** [comment]
Thanks to Ken for update. Yes, the solution in the batch file is exactly what i need. Thanks a lot.
