### ISSUE TITLE
Issues in Passing a FilePath to Python

### ISSUE THREAD

**Issue by DushyantK14** [kelaberetiv/TagUI#1202]
Hi,

I am having issues passing a filepath to python code in tagui. The path gets corrupted.

This is my code:
filepath = "C:\\TagUi\\tagui\\flows\\SnowRequestCreation\\Inputs.txt"
py_step('filepath = "' + filepath + '"')
py begin
print(filepath)
py finish
echo `py_result`

Output :
py print(filepath)
C:\TagUi        agui♀lows\SnowRequestCreation\Inputs.txt

You see this path got corrupted.

But when I use same path inside python code, it works:

py begin
filepath = "C:\\TagUi\\tagui\\flows\\SnowRequestCreation\\Inputs.txt"
print(filepath)
py finish
echo `py_result`

Output:
print(filepath)
C:\TagUi\tagui\flows\SnowRequestCreation\Inputs.txt

I have tried multiple ways but nothing seems to work in passing correct path as input argument to py. Please advise.

**Comment by ruthtxh** [comment]
Hi @DushyantK14 this is not an issue with the py step.

In programming or javascript for the matter, certain characters when placed behind a backslash, are escaped characters. In this case, \t is a tab and \f is a form feed. Another common ones is \n newline.

I suggest you can caps those characters behind the backslash like this:
```
filepath = "C:\\TagUi\\Tagui\\Flows\\SnowRequestCreation\\Inputs.txt"
```

Also note that for file paths in TagUI you should do double backslashs because the single one is also an escape character.

**Comment by DushyantK14** [comment]
Hi Ruth,

I know about escape characters, when I pasted code here it removed second '\' from each path and shows only one slash in path.

Attaching screenshot  so you can see the path was provided in the exact way as you are suggesting. Output shows corrupted path:
<img width="508" alt="Code" src="https://user-images.githubusercontent.com/102656593/161014283-b65390aa-ccb9-4f0a-ad2d-75aa6c81744e.PNG">
<img width="475" alt="Output" src="https://user-images.githubusercontent.com/102656593/161014287-a4c4341a-7797-4111-962d-0492b5e9e795.PNG">

**Comment by ruthtxh** [comment]
Hi @DushyantK14 

As mentioned in above comment, \t and \f are escaped characters too so you will have to capitalise it as \T \F as in the filepath I provided.

**Comment by DushyantK14** [comment]
that worked.
Thank you.
