### ISSUE TITLE
Possible to run vision steps in headless mode? - display needed for visual automation image matching

### ISSUE THREAD

**Issue by mrinmoysd** [kelaberetiv/TagUI#1203]
Recently I have been working on a Web automation using TagUi and am stuck at a place where I have to handle a browser alert. Is there any solutions we have to handle the alert using vision steps in headless mode.

**Comment by ruthtxh** [comment]
Hi @mrinmoysd unfortunately if you want to use visual automation to match an image and click, you would need the image to be shown on the screen.

P.S. you can do visual automation without vision step too... you can take a screenshot of the button and name it button.png and place it in the same folder as your flow. Then something as simple as your usual click step like this will do:
```
click button.png
```
