### ISSUE TITLE
"Word cannot save this file because it is already open elsewhere" - pending check if restart pc helps

### ISSUE THREAD

**Issue by edmundchan1976** [kelaberetiv/TagUI#1204]
<img width="959" alt="error tagui" src="https://user-images.githubusercontent.com/4532478/162399513-df0c813b-1834-455e-b020-1c28d2408821.png">

The automation seemed to hang with this pop-up. What do i need to do for the automation to not be disrupted? attached is the screenprint

**Comment by ruthtxh** [comment]
Hi @edmundchan1976 can you try to restart your pc and see if error persists?

**Comment by edmundchan1976** [comment]
Hi Ruth

Thank you for the advice. It works after I restart it. Why does this
happen? i am hoping for tagui use to be as stable as possible. Also, i
notice  (attached, circled in green) that there is document1, document2,
document3, etc..., that seems to be created previously. Is that the
cause of the error?

[image: restart.jpg]

**Comment by ruthtxh** [comment]
Hi @edmundchan1976 that should not be the cause of the error. But perhaps sometimes MS Word does not close files properly and requires a restart to terminate unwanted sessions.
