### ISSUE TITLE
Turn a negative number into a positive - use Math.abs()

### ISSUE THREAD

**Issue by Vitodenere** [kelaberetiv/TagUI#1205]
When i read the balance its reads it as a negative number as it should. But i want to turn it into a positive number. Is this possible with tagui? so when i let it read the Balance it reads it as 885, instead of -885?
![image](https://user-images.githubusercontent.com/98885634/162420113-ebebe9b0-2f55-40b7-9ff8-4ccf2faa2801.png)

**Comment by ruthtxh** [comment]
Hi @Vitodenere you can get the absolute value like this:
```
num = -885
posNum = Math.abs(num)
echo `posNum`
```

**Comment by Vitodenere** [comment]
This worked great thank you very much!

**Comment by ruthtxh** [comment]
Closing this for now, feel free to reopen.
