### ISSUE TITLE
Concatenating string - try this

### ISSUE THREAD

**Issue by Vitodenere** [kelaberetiv/TagUI#1206]
![image](https://user-images.githubusercontent.com/98885634/162427781-822338c2-bdb7-4f35-8d41-7d3c958c7f61.png)
![image](https://user-images.githubusercontent.com/98885634/162427824-04547932-aaa4-4bdf-b996-113e7ed5d45e.png)
I made this and i want the variabele "addedmoney" to be EUR 5, but when I echo the variable it echos +currency+ +balance+ instead of EUR 5. How can i fix this?

**Comment by ruthtxh** [comment]
Hi @Vitodenere you can try something like this:
```
balance = 5
currency = "EUR"
addedmoney = currency + " " + balance
echo `addedmoney`
```

**Comment by Vitodenere** [comment]
Great thank you!

**Comment by Vitodenere** [comment]
I added this to the script and both of the values are the same but it still echo's "Payment not succesfull"
![image](https://user-images.githubusercontent.com/98885634/162688965-cd0c0476-f9de-4a00-a558-e8e194baed28.png)
![image](https://user-images.githubusercontent.com/98885634/162689007-7ee5ab0f-14ec-4cd9-bc7c-b413903cb9ee.png)

**Comment by Vitodenere** [comment]
You are right, rookie mistake haha!
