### ISSUE TITLE
Error accessing variable - use backticks instead of quotes

### ISSUE THREAD

**Issue by zjy090** [kelaberetiv/TagUI#1207]
![2](https://user-images.githubusercontent.com/26294782/163122897-4a981f93-3551-44bf-9a61-d1cdb28a5de7.png)
![3](https://user-images.githubusercontent.com/26294782/163122918-1490e636-208d-44bd-afc1-49d973e65fd6.png)
![1](https://user-images.githubusercontent.com/26294782/163122923-8446b4c6-fae4-4628-aa6b-264935799698.png)

read //*[@id="import_overview_f:hl168"]/tbody/tr/td[2]/span to text
When I run the code in picture 1, I don't get the value in the span. But I see that the log of picture 3 has obtained the value.

pls help

**Comment by ruthtxh** [comment]
Hi @zjy090 
To access the variable you need to call it in between backticks, not quotes like this:
```
echo `text`
```
