### ISSUE TITLE
Don't re-download file(s)? - try load step and search from list

### ISSUE THREAD

**Issue by Krutfjell** [kelaberetiv/TagUI#1208]
First of all, thanks for TagUI, it looks very promising!

At the moment I am mostly looking at downloading new info/files from sites. I've looked around github, youtube, the forums etc, but I'm kinda stuck. I was looking into downloading the latest security resolution from the UN Security Council, and this is as far as I got:

```
// Site to download from
https://www.un.org/securitycouncil/content/resolutions-0
wait 5

// Click latest year
click //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/div/ul[1]/li[1]/h4/a
wait 5

// Set column headers
dump srelid,date,title to srel.csv

// Count number of rows in srel-table
rows = count('//*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/table/tbody/tr')

// Scrape content from table to CSV-file
for row from 1 to rows
    read //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/table/tbody/tr[`row`]/td[1] to srelid
    read //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/table/tbody/tr[`row`]/td[2] to date
    read //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/table/tbody/tr[`row`]/td[3] to title
    titlet = remove_chars(title,'\t')
    titlen = remove_chars(titlet,'\n')
    srelinfo = [srelid,date,titlen]
    write `csv_row(srelinfo)` to srel.csv
```
First I just used `Click` on the latest one, but I had already downloaded it before, and alas it just overwrites it. So I thought maybe I would write a list of all the latest resolutions to srel.csv and check if it was in the csv then do not download, but not sure how to proceed.

Any tips how to solve this?

**Comment by kensoh** [comment]
Thanks for raising this interesting issue, and your kind words!

Something like below can be used (first create an empty list.txt) -

```
// at start of .tag file
load list.txt to list

// after reading to srelid
if list.indexOf(srelid) == -1
    write `srelid` to list.txt
    // do the step to download report
```

It uses list.txt to tracks if an item has already been processed, before adding the item to list.txt and downloading it.

**Comment by kensoh** [comment]
PS - I've left AI Singapore, but happen to see your interesting question.

@ruthtxh would be able to assist further and could share other ways to achieving the same outcome.

**Comment by ruthtxh** [comment]
Hi @Krutfjell

Instead of dump step to set the column headers, I suggest you can manually create the empty csv file with just the column headers. This is because dump step overwrites the file on each run, so your previous run data in srel.csv will be wiped out each time you run the flow. Write step appends to the last row of the file.

In this case perhaps your srel.csv file can be your single source of truth and you can do a search in that file to see if your variable srelid is in the file. So adding on to @kensoh's suggestion, you can load do `load srel.csv to list` instead of list.txt to list.

**Comment by Krutfjell** [comment]
Thanks @kensoh and @ruthtxh! What you suggested worked perfectly. This is the final script, perhaps someone finds it useful:

```
// Downloads latest resolution(s) from the UN Security Council
// Note: You need to create a blank file named 'downloadedfiles.txt' in the folder where the .tag file is located

// Site to download from
https://www.un.org/securitycouncil/content/resolutions-0
wait 5

// Click latest year
click //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/div/ul[1]/li[1]/h4/a
wait 5

// Create download list
load downloadedfiles.txt to downloadedfiles

// Count number of rows in sres-table
rows = count('//*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/table/tbody/tr')

// Open each sres in the table that is not listed downloadedfiles.txt and download it
for row from 1 to rows
    read //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/table/tbody/tr[`row`]/td[1] to sresid
    if downloadedfiles.indexOf(sresid) == -1
        write `sresid` to downloadedfiles.txt
        Click //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/table/tbody/tr[`row`]/td[1]/a
        wait 10
        keyboard [ctrl]s
        wait 5
        https://www.un.org/securitycouncil/content/resolutions-0
        wait 5
        click //*[@id="page-page"]/div/div[2]/div[1]/div/div/div/div/div/div/div/ul[1]/li[1]/h4/a
        wait 5
```
