### ISSUE TITLE
Not able to run the script using VS code debugger - run from VS Code terminal (cmd)

### ISSUE THREAD

**Issue by Anujpalu24** [kelaberetiv/TagUI#1209]
Not able to run the script using VS code. Tried setting up the run configuration but still not able to run the tagui script. Using cmd able to run the same under VS code but not by run option of the same.

Please let me know the steps or any  video for the same.
Also let me know if any alternate tool we can use to create a end to end framework.

**Comment by ruthtxh** [comment]
Hi @Anujpalu24 just to confirm, it works when you run it separately on command prompt but not when you run from VS Code?

What is the error message you are getting from VS Code? You are running cmd from the VS Code terminal and not other terminal sessions like powershell etc?

You can use any editor to edit your flow such as notepad or notepad++ and run the script directly from your windows command prompt.

**Comment by Anujpalu24** [comment]
@ruthtxh  :  Yes things are working from windows command prompt and same is working from VS code cmd terminal.

But same is not working when tried to run from "Run" option of VS code below : 
![image](https://user-images.githubusercontent.com/89205899/164226443-14e53978-ddfa-4a4a-a330-dd4638eeda9d.png)

Setup the configuration to open chrome with a webpage link but not getting how to call the .tag script to run after chrome get opened. We are trying to create a proper framework for end to end execution of script using VS code

![image](https://user-images.githubusercontent.com/89205899/164226338-8af7e9da-d66e-4369-93b5-96f896027a19.png)

**Comment by ruthtxh** [comment]
Hi @Anujpalu24 

The VS Code built-in debugger (when you press Run button) supports Node.js and javascript related runtime debugging. TagUI script is not exactly a programming language as bulk of it contains pure human language, although you can write javascript code directly to it.

To run the tag file, you need to run from the VS Code terminal, which you confirmed is running fine.
