### ISSUE TITLE
When is js begin and js finish required for code or steps - some examples here

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1211]
**user query**

在 TagUI steps 说明里并找不到  split 语法，
但TagUi 里，可以直接用split ： lasttime=lasttime.split(' ')[1]
而不需要放在   js  begin   ...  js finish  里面。

请问，这是为什么？哪些 Steps 之外的命令，可以不用放在   js  begin   ...  js finish  里直接使用？

>I can't find the split syntax in the TagUI steps description,
But in TagUi, you can use split directly: lasttime=lasttime.split(' ')[1]
Instead of putting it in js begin ... js finish.
>
>excuse me, can you tell me the reason? Which commands other than Steps can be used directly without putting them in js begin ... js finish?

**Comment by kensoh** [comment]
`js`, `js begin` and `js finish` are used in the following ways -

```
js 1-line JavaScript code
```

```
js begin
JavaScript code line 1
JavaScript code line 2
JavaScript code line 3
js finish
```

Whenever there is some JavaScript code (anything other than the TagUI steps or helper functions), above will be required. However, TagUI can "smartly" detect the following 3 situations where JavaScript is used but `js` is not required.

**1. Variable assignment**

When a variable is being assigned, TagUI can detect the `=` symbol and automatically treat that line as JavaScript code, without the user needing to explicitly use `js` or `js begin`/`js finish`.
```
name = "Johnny"
```

**2. Line ending with ;**

If a line ends with `;` character, and that line cannot match any TagUI steps, then it is treated as JavaScript code.

```
// quits TagUI using JavaScript exit() function
this.exit();
```

**Comment by kensoh** [comment]
Copying @ruthtxh on this user question as I've left AI Singapore

**Comment by kangyiwen** [comment]
谢谢，原来是这样的，我会记录下来，并更新到中文文档内。
