### ISSUE TITLE
click 文字时，有些地方无效 - usage issue, need to use popup step for new tab

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1214]
@ruthtxh  你好，有个问题一直困扰着我，就是使用  click 文字  时，有时有效有时无效。例如：

```
http://baidu.com
wait 3
click 百度热搜    <-----------------  这个运行成功
wait 3
click 电影榜     <-----------------  这个不成功，也没有报错
wait 3
```
在页面上搜索 “电影榜” 只有一个；
看了网页源代码，源代码里出现有3个“电影榜”，
是不是因为这个原因？有什么办法避免吗 (不使用XPATH等方法)？

![image](https://user-images.githubusercontent.com/76672577/165195017-9bc81127-c1bc-4e4c-b82d-0e27410311b5.png)

学习初期，我因为这个原因，第一反应是 TagUI 不稳定，相信很多初学者都会有这个误解。
希望可以改进，或者增加一些提示，
谢谢。

**Comment by ruthtxh** [comment]
Hi @kangyiwen 

When you do `click xxx`, xxx will be interpreted as a web identifier in TagUI. For your information, the identifiers will be selected in this order:
> XPath > CSS > id > name > class > title > aria-label > text() > href

So if there is more than one xxx in the source code, the first one matching the above order list will be selected.

For web automation to directly access a particular element it is best to use XPath.

If you really want to use OCR, you can do `click xxx using ocr`, but if there are more than one instance of the same text on the screen, it may not select the correct one.
https://tagui.readthedocs.io/en/latest/advanced.html?#visual-automation-tricks

You can also try to use visual automation by taking a screenshot of the button if it is unique, and doing `click button.png`

**Comment by kangyiwen** [comment]
@ruthtxh ，谢谢这么详细的说明，我理解了。

在我的问题里，我发现需要点击的 “电影榜”，其中2个在  里面，在注释内，TagUI应该是去点击注释内的目标了。

是否可以迭代一下，在识别时，放弃点击在注释内的？或者先把注释代码去掉，再进行寻找点击？

**Comment by kensoh** [comment]
Hi @kangyiwen can you tell us more what 注释 means?

Broadly I think there are text strings that are not visible strings on the webpage but can still result in a match.

However, making a change around how the automatic selection works will be compatibility-breaking. Because many existing user scripts are designed base on the current priority and logic. If TagUI iterate to ignore text matches that are not visible on the screen or less important, it is likely to cause many users existing scripts to fail, when they update to new TagUI version. I'm not saying it is not a good idea and more discussion will be needed, but if that is something to be done, it would have to be in a major new release eg v7, that list out the compatibility-breaking scenarios.

**Comment by kangyiwen** [comment]
Hi @kensoh ，查看 https://top.baidu.com/board 的Html源代码，会发现有大段的注释被包含在  `<!--    ---> `之间。  这之间的代码，应该都不会在前台显示，click 等命令，先过滤掉   `<!--    ---> `之间代码再匹配，应该不会影响老用户的流程。
![111](https://user-images.githubusercontent.com/76672577/165417833-02ff8daa-e754-4cc9-83d2-80f79a844dbb.png)

**Comment by kensoh** [comment]
Oh solution found. It is usage issue. To tell TagUI that you are automating on the popup tab, you need to use popup step https://tagui.readthedocs.io/en/latest/reference.html#popup

Below works correctly for me, it should work for you too, fyi @ruthtxh -

```
https://baidu.com
click 百度热搜
popup board
	click 电影榜
	// some other steps
wait
```

Also, there is no need to use wait 3 to explicitly wait. TagUI will auto-wait for 10 seconds for element to appear and interact with it as soon as it appear. You can change the default timeout of 10 seconds with timeout step - https://tagui.readthedocs.io/en/latest/reference.html#timeout

**Comment by kangyiwen** [comment]
谢谢，我这里测试了，成功运行。
wait 3 是我希望慢一点，让我可以看清楚   ：）

我曾经给多个商业RPA软件提过建议，让他们在点击时，在连续点击命令时，自动判断下一次点击目标是否出现再执行下一步，但是没有一家去这么做了，当然这里有很多技术细节问题。

在写RPA流程时，其实频繁用到 “判断元素是否存在”   “等待元素是否出现”  这2个命令，我认为RPA软件本身可以对此进行优化，提升稳定性，降低学习门槛。

降低学习门槛，我认为这是核心竞争力，比功能强大更有吸引力。所以我特别喜欢：“用人类语言进行RPA开发”

**Comment by kangyiwen** [comment]
是吧是用了 `popup ` 命令，TagUI 就默认寻找带链接的目标了，是这样吗？

**Comment by ruthtxh** [comment]
Hi @kangyiwen the popup step will look for keyword in the new tab's URL. Please note that the keyword has to be unique to identify the right tab.

The steps with the indentation under the popup step will be used for that particular tab only.

**Comment by kangyiwen** [comment]
谢谢 @ruthtxh   `popup board`  这里的  board  是个新 tab 名称吗？  我不太理解这个要写什么

**Comment by ruthtxh** [comment]
If https://www.baidu.com/ opens a new tab https://top.baidu.com/board, now you have 2 tabs.

Comparing the 2 URLs, the unique part of the 2nd URL is either the keyword "top" or "board" so you can either do

```
popup top
  //some step
```
or
```
popup board
  //some step
```

**Comment by kensoh** [comment]
Yes @kangyiwen, TagUI will auto-wait for elements to appear before interacting with them automatically. No need to write your own `wait` steps. Unless you want to explicitly slow down. If webpage is very slow, you can use `timeout 30 seconds` / `timeout 30` for example, to let TagUI auto-wait up to 30 seconds before throwing error.

**Comment by kangyiwen** [comment]
这是非常好的功能，谢谢。
