### ISSUE TITLE
Live mode 下如何调试多行语句

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1217]
@ruthtxh  你好，请问 Live mode 下如何调试多行语句，例如想调试：

```
popup top
  click 汽车榜
```

我自己尝试用 &  来做链接 ，但好像不行，我感觉应该有类似的语法可以使用在 LIVE 下，请问具体应该是什么？谢谢

**Comment by ruthtxh** [comment]
Hi @kangyiwen 

Live mode does not have popup step. Live mode is usually for debugging your individual single line step. You can take the new tab URL and access it in live mode to debug the individual single steps just as if it is your main URL.

**Comment by kangyiwen** [comment]
好的，谢谢。

**Comment by kangyiwen** [comment]
我现在是在 .tag 里，需要的位置用  live 命令，切换到 Live mode。
