### ISSUE TITLE
建议增加“不报错运行”和浏览器窗口控制

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1221]
@ruthtxh @kensoh   HI  经常会发生的一种情况是软件状态不一样，例如浏览器的大小的变化，当我 `click a.png`  时，因为浏览器大小不一样（有时全屏，有时没全屏）造成 a.png  大小不同，click 就无法正常运行。希望增加 不报错运行功能，这样可以设置多个 click 点击不同图片来适应这个情况。

我有2个建议：
1. 增加浏览器窗口控制，例如：最大化、设置浏览器在屏幕位置、设置浏览器窗口大小。
2. 增加不报错执行，在该命令下的步骤，出错了也可以继续执行后续的步骤。
例如：
```
no error  <------------------------在这个范围内的步骤，如果执行遇到问题，也会继续后续的步骤。
    click a.png
    click b.png
//后续步骤
```
或者这样：

```
click a.png -noerroe
click b.png -noerroe
//后续步骤
```
当然，窗口最大化，可以通过 click 完成，但是否可以设置chrome位置、甚至设置chrome窗口大小呢？

**Comment by ruthtxh** [comment]
Hi @kangyiwen you can do the following to handle the error, use the present() or exist() helper functions. If the image is not found it will just not click. The difference between present() and exist() is that exist will wait for the time out while present will not.
https://tagui.readthedocs.io/en/latest/reference.html?#present
https://tagui.readthedocs.io/en/latest/reference.html#exist

```


if present('a.png')
  click a.png
```

**Comment by kensoh** [comment]
Adding on, for web browser size, you can edit the file tagui\src\tagui_config.txt I think there is width and height settings. But for position of browser on the screen I don't think it can be controlled. Maybe browser will save the position.

**Comment by kangyiwen** [comment]
谢谢两位。
