### ISSUE TITLE
要如何判断  Chrome下载成功？

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1222]
请问，当网页下载文件大小不同，并且不确定下载需要多久的时候，如果用 wait 会遇到大文件没下载完，小文件下载完成后浪费时间的情况。要如何判断  Chrome下载成功？

```
https://www.videvo.net/video/7/
click download-button
wait 10  <----------------------------- 这里希望可以被优化，自动判断chrome下载状态
```

谢谢。

**Comment by ruthtxh** [comment]
Hi @kangyiwen 

You can try and use visual automation to check for something generic in the chrome download bar at the bottom. Here is an example, whereby I check if "secs left" is present and wait.
```
https://github.com/kelaberetiv/TagUI/releases/download/v6.46.0/TagUI_Windows.zip
if present('secsleft.png')
	wait 1
```
secsleft.png
![image](https://user-images.githubusercontent.com/40910744/166614397-95d0a953-3561-4c6b-9ccb-2270f30de1fc.png)

**Comment by kangyiwen** [comment]
@ruthtxh  谢谢，我用的方法是： 判断下载文件目录，是否有目标文件。

我试试你这个方法。

**Comment by ruthtxh** [comment]
Hi @kangyiwen to clarify, the secsleft.png is the highlighted portion, so it is like this:
![secsleft](https://user-images.githubusercontent.com/40910744/166616729-9f999f12-1373-4451-81b1-4da5eb9e777e.PNG)

**Comment by kensoh** [comment]
Adding on, following structure will keep checking every second to see if the download is completed

```
for n from 1 to infinity
    if present('secsleft.png')
        wait 1
```

**Comment by kensoh** [comment]
Or the following, if you wish to cap the time to wait to 5 minutes (300 seconds)
```
for n from 1 to 300
    if present('secsleft.png')
        wait 1
```

**Comment by kangyiwen** [comment]
也许我的屏幕太大了，这个方法不太好用。  方法我理解了，谢谢。

**Comment by kangyiwen** [comment]
改进了下

```
https://www.videvo.net/video/8/
wait 3
click download-button
wait 3
for n from 1 to 100
	echo `present('mb.png')`
	if present('mb.png')
		wait 3
	else
		echo 下载完成
		break
```
