### ISSUE TITLE
如何指定下载文件名？chrome设置询问下载位置，但无效

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1223]
download to 可以指定下载目录，有什么命令可以指定下载文件名吗？

想让 chrome 每次下载前询问，这样就自己填写路径和文件名，但已经把chrome设置改后，下载时依然没有询问填写路径和文件名，请问是什么原因？
![image](https://user-images.githubusercontent.com/76672577/166131627-e3c4162b-82cb-434a-9003-2613182732d7.png)

**Comment by kangyiwen** [comment]
希望把代码中的下载文件名，改为 ：`filetitle`.mov
```
https://www.videvo.net/video/7/
//-- 取文件名
read /html/body/main/article/div/div[2]/div/div/div[1]/div[1]/h1/span to filetitle
echo `filetitle`

//-- 点击下载
click download-button
wait 10
```

**Comment by ruthtxh** [comment]
Hi @kangyiwen, there are 2 things you need to check:

1. Your chrome settings as per above image is set in the TagUI Chrome use profile session. You can open live mode to trigger that session and toggle the download setting.
```
tagui live
```
2. In the TagUI source code, the settings for download is set to allow all download requests, so this overwrites the chrome settings you selected in (1). So to set the settings to what you have selected you would have to change the source code.
Do a search of the following devtools protocol function in your tagui_header.js and tagui_parse.php file and change the behavior from allow to default. 

Search for the words "Page.setDownloadBehavior", there should be 3 results that you need to replace.
![image](https://user-images.githubusercontent.com/40910744/166616325-06994f0b-03b4-4382-af97-2920ca38dca7.png)
and replace the function to
```
chrome_step('Page.setDownloadBehavior',{behavior: 'default', downloadPath: location});
```

**Comment by kangyiwen** [comment]
谢谢。 TagUI 的知识好多啊

**Comment by kensoh** [comment]
Adding on, running the following line in .tag file will have the same effect as modifying the source code 
```
www.google.com
js chrome_step('Page.setDownloadBehavior',{behavior: 'default', downloadPath: location})
```

Yes a lot of knowledge. TagUI team essentially is 1 headcount, so we can only build for the most general usage case that most people are using, and no easy customisation for different usage. With a larger team, these options should be made into an IDE for easy configuration.

**Comment by kensoh** [comment]
Ruth is looking at making a desktop IDE this year, maybe options like this could be considered to add into the IDE.

**Comment by kangyiwen** [comment]
做 IDE 是个大工程，到时候如果需要，我可以帮忙。
