### ISSUE TITLE
每次新电脑  第一次运行 TagUI，会有这个报错提示

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1225]
HI  每次在一台新电脑安装TagUI后，第一次运行 TagUI Live ，会有这个报错提示，请问是什么？

![1](https://user-images.githubusercontent.com/76672577/166197325-f7e4e1b9-84e8-43c5-96be-579ab4dbfbdc.png)

**Comment by ruthtxh** [comment]
Hi @kangyiwen 

Yes this is the correct behaviour. This message occurs only on the first run, and after which the SikuliX engine will automatically setup Jython which will self solve the error and hence won't appear in subsequent runs.

**Comment by kangyiwen** [comment]
明白了，谢谢
