### ISSUE TITLE
Do you have any example of web scrapping by using xpath with pure python? - see this

### ISSUE THREAD

**Issue by whitelighter23** [kelaberetiv/TagUI#1230]

**Comment by marcelocecin** [comment]
https://github.com/tebelorg/RPA-Python

**Comment by whitelighter23** [comment]
@marcelocecin can you please let me know which function can be used to scrap a xpath and turn into a text ?

**Comment by marcelocecin** [comment]
https://github.com/tebelorg/RPA-Python/issues/24

**Comment by kensoh** [comment]
Thanks @marcelocecin. Yes @whitelighter23, what Marcelo said is correct, for Python you can use the rpa package and raise issues at that GitHub repo, or the Telegram group shared with TagUI users.

The specific functions would be read(), or table() if you are reading data from a table. You can see more at the API section at that repo.

**Comment by kensoh** [comment]
Copying @ruthtxh and closing issue because this is a rpa package query.
