### ISSUE TITLE
请问要哪些IT技能，才可以对 TagUI 进行深入一些迭代？- some initial thoughts

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1233]
@kensoh @ruthtxh  我公司的程序员开始空下来了，我准备让他学习一下 TagUI 的底层代码，尝试完成一些迭代，例如把报错信息改成中文，让报错信息更具指导性。

请问要哪些IT技能，才可以对 TagUI 进行深入一些迭代？

**Comment by kensoh** [comment]
I would think PHP and JavaScript would be needed. PHP is used for converting .tag files to JavaScript files to run. JavaScript is needed for the actual execution and also the conversion of human language to JS code during live mode operation. But most importantly, is ability to look for answers online and remember to test carefully the changes made. After making some change, you can run tagui command on the tagui/src/positive_test.tag to see if the generated JS code is correct.

The videos here would be useful, https://www.youtube.com/c/kensoh/videos, but probably not needed if you are only changing error messages. Which you can search and replace the text lol. Notepad++ can search for text in all files.

Above are some thoughts that come to my mind, @ruthtxh will know more from her other exposure to TagUI.

**Comment by kensoh** [comment]
Above are for functional changes. If you are thinking of enabling AI / ML, then Python would be needed to do more there

**Comment by kangyiwen** [comment]
哈，谢谢  @kensoh ，看看我的第一个成果
![image](https://user-images.githubusercontent.com/76672577/169631248-c6d51eee-fe10-4bc8-821e-992ffed8174a.png)

**Comment by twinyk** [comment]
我也准备 投入2个程序员，哈哈哈

从 Windows 版邮件发送

发件人: kangyiwen
发送时间: 2022年5月21日 10:43
收件人: kelaberetiv/TagUI
抄送: Subscribed
主题: Re: [kelaberetiv/TagUI] 请问要哪些IT技能，才可以对 TagUI 进行深入一些迭代？- some initial thoughts (Issue #1233)

哈，谢谢 @kensoh ，看看我的第一个成果

**Comment by kangyiwen** [comment]
@twinyk   你也准备投入人员迭代TagUI 吗？  如果是，我们聊聊？

**Comment by kensoh** [comment]
@kangyiwen, 妙！

**Comment by twinyk** [comment]
python 和 js 就够了， 低端货
















在 2022-07-09 18:01:37，"Ken Soh" ***@***.***> 写道：

Closed #1233 as completed.
