### ISSUE TITLE
TagUI中文网流量分析记录

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1234]
看了下 Tagui.com.cn 的流量来源，百度已经收录首页，目前访客还比较少，但平均访问时长有5分钟，还是很不错的。来源关键词也都是tagui相关，跳出率也不错。

![image](https://user-images.githubusercontent.com/76672577/169676310-256d9486-476e-4e3b-b038-37f2b23bf98f.png)

**Comment by twinyk** [comment]
很明显，你的关键词范围太窄了。。。你要做通用行业词。流量就会暴增
















在 2022-05-22 11:08:44，"kangyiwen" ***@***.***> 写道：

看了下 Tagui.com.cn 的流量来源，百度已经收录首页，目前访客还比较少，但平均访问时长有5分钟，还是很不错的。来源关键词也都是tagui相关，跳出率也不错。

**Comment by kangyiwen** [comment]
才上线几天，百度只收录了首页。 我在想，怎么增加点内容，抢一下“开源RPA" 这个词。

**Comment by twinyk** [comment]
数字化，数字化转型，程序自动化，开源数字化应用，开源RPA...，同为研究的开发人员或市场人员，你再借鉴那些 胡乱编学术文章的人，大学教授啊，各个研究机构的称谓和咨询公司的叫法。他们创了很多不靠谱的词。
















在 2022-05-22 13:22:44，"kangyiwen" ***@***.***> 写道：

才上线几天，百度只收录了首页。 我在想，怎么增加点内容，抢一下“开源RPA" 这个词。

**Comment by kangyiwen** [comment]
哈，看来懂行的。

**Comment by kangyiwen** [comment]
这些天，平均每天30个左右访问，情况见图：

![image](https://user-images.githubusercontent.com/76672577/172041447-01f7417c-aefb-47c9-a3b4-c25d0989342e.png)

**Comment by kensoh** [comment]
That is very good @kangyiwen, means reaching ~1k a month.

For TagUI GitHub page, it is ~2k unique visitors a months and ~4k page views a month.

@ruthtxh also has access to these stats if you need updated ones for comparison.

**Comment by kangyiwen** [comment]
目前中国用户还刚刚接触TagUI，遇到的问题和我当时基本一样，主要是安装和一些命令使用问题，我还能应付。
希望下次打包EXE时，可以叫 V7.0  ，这样版本更清晰一些。 我等新打包后，再开始做点入门视频教程。
