### ISSUE TITLE
Can I automate a process on backend sever using TagUI? - check user permissions

### ISSUE THREAD

**Issue by RajanChopra09** [kelaberetiv/TagUI#1236]
Hi, I am new to TagUI and I want to open an application using Visual automation and perform some steps. This need to be done on a backend server, when an action trigger from a website using nodejs. I am able to trigger cmd file and .tag file also executed, but not able to execute keyboard and visual click commands. I am getting report something like this:
_

> keyboard [win]d 
>  ERROR - Unable to open file 'tagui.sikuli/tagui_sikuli.out' 
>  dclick c:/tagui/flows/SL_Flow/SL.png 
>  ERROR - automation aborted due to above 
>  ERROR - automation aborted due to above 
>  ERROR - Unable to open file 'tagui.sikuli/tagui_sikuli.out' 
>  ERROR - automation aborted due to above

_ 
Can someone please help and provide any inputs. Thanks!

**Comment by ruthtxh** [comment]
Hi @RajanChopra09 

The error message unable to open file.. sounds like there are some permission issues accessing the following file? Can you check that the user has the proper access rights to all the files in the tagui/src folder?

You may want to try some things like reinstalling TagUI [see docs ](https://tagui.readthedocs.io/en/latest/setup.html). Also, for visual automation to work you have to install OpenJDK as per the documentation.

**Comment by RajanChopra09** [comment]
Hi @ruthtxh 

Thanks for the quick reply. I have installed OpenJDK as per instruction in documentation and also given full rights to tagui/src folder to all users on the server.

If I run the automation by connecting to Remote Desktop, it works fine. But if I trigger it from website action, getting this error.

Can you please confirm, that visual automation will work on backend server in background, if we trigger that from website?

**Comment by marcelocecin** [comment]
hi Rajan
could you detail how it is running via trigger?

**Comment by RajanChopra09** [comment]
Hi @marcelocecin 

I have hosted a website from a server, on the same server I have installed TagUI. I have created a flow and created CMD file for the same. I have given full access to tagui/src folder to all users on server.

Then any user access the website from there system and click a button on a webpage, that trigger will call CMD file on server(I am using nodejs for calling cmd file) and CMD file will execute TagUI flow in the background.

All this is working fine. Flow file is getting executed, but when it reaches the "Keyboard command" or "dclick" (Visual automation) then it is not working and report showing the following errors:

> keyboard [win]d
> ERROR - Unable to open file 'tagui.sikuli/tagui_sikuli.out'
> dclick c:/tagui/flows/SL_Flow/SL.png
> ERROR - automation aborted due to above
> ERROR - automation aborted due to above
> ERROR - Unable to open file 'tagui.sikuli/tagui_sikuli.out'
> ERROR - automation aborted due to above

If I am connecting to server using remote desktop and run the flow with same CMD file it works perfectly as required.

Can someone please confirm, that visual and keyboard automation will work on backend server in background, where we are not connected with server through any Virtual Machine or Remote Desktop.
