### ISSUE TITLE
如何运行结束，不关闭 chrome - use live step

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1239]
.tag运行结束，希望不关闭 chrome，请问要怎么做？

**Comment by ruthtxh** [comment]
Hi @kangyiwen 

You can use live step:
```
echo abc
live
```

once you are done using that chrome user profile browser, you can type "done" to quit in the command prompt.

**Comment by kangyiwen** [comment]
好的 谢谢
