### ISSUE TITLE
tagui stops when connecting the power cable in windows or when disconnecting the second screen

### ISSUE THREAD

**Issue by Darkness99q** [kelaberetiv/TagUI#1241]
Hi everyone, I'm here to ask for your help. I have been trying to solve this problem for weeks and nothing has worked.(WINDOWS system) I am running tagui in the word extension with an excel database. The problem is that tagui stops at the second item in the database when connected to power. (Laptop) When I unplug my laptop, it works fine until I plug it back in. Previously the same thing happened to me when I disconnected a second screen from my pc. I have cleaned the whole computer, the word cache, chrome and the screen cache. I've changed all the power plans. I have reinstalled tagui countless times. i have reinstalled coretto. nothing has worked. I appreciate if you know how to correct it because I already gave up. I don't know what else to do at this point. my pc is an asus with ryzen 5 3500u of 20 gb of ram and m.2 of 254gb in case you require any features. Thank you very much, I hope you have a solution as they are my last hope.

**Comment by ruthtxh** [comment]
Hi @Darkness99q these changes like unplugging power/ connecting to second screen are done mid way during the automation run?

Are there any errors when the run stops?

**Comment by Darkness99q** [comment]
> Hi @Darkness99q these changes like unplugging power/ connecting to second screen are done mid way during the automation run?
> 
> Are there any errors when the run stops?

Hello, I have tried before running it and it stops by itself. Plugging it in and then starting it doesn't stop. In the middle of the journey I have tried and the same thing continues to happen. It does not show me any error in the execution. the code is executed to fill a form and it only completes 1 or 2 forms for me and then it stops as if the form had finished successfully. but does not continue to 3 or 4 form.

**Comment by ruthtxh** [comment]
Are you using any visual automation in the flow? If yes perhaps when you change unplug power/ connect second screen the elements on the screen changes and does not match your snapshot provided as it was taken in a particular configuration.

**Comment by Darkness99q** [comment]
https://www.funcionpublica.gov.co/
wait 1
if present('//*[@id="frmLogin"]')
	select //*[@id="frmLogin:tipoDocumento"] as 38
	type //*[@id="frmLogin:userName"] as 00000000
click /html/body/div[2]/div[2]/div/form/div[5]/div/div/div[2]/span/input
type /html/body/div[2]/div[2]/div/form/div[5]/div/div/div[2]/span/input as 00000000
	click //*[@id="frmLogin:entrar"]
wait 1
select //*[@id="frmPrincipal:tipoDocumento"]  as 38
click //*[@id="frmPrincipal:cedula"]
type //*[@id="frmPrincipal:cedula"] as `CEDULA`
click //*[@id="frmPrincipal:btnBuscarUsuarioAsociar"]
wait 3
snap page to `CEDULA`.png
if present('//*[@id="swal2-content"]')
click /html/body/div[10]/div/div[10]/button[1] 


I do not use it in this code in specific in another if and it does not work either. I use the latest version of tagui. I've tried before and during and the same thing happens. you could tell me how I reset values. Is there a different way to end_process or closing Word?

**Comment by ruthtxh** [comment]
Hi @Darkness99q to end process on Word you can click the stop button (same as the run button in the ribbon).

Is this the exact flow you have that you are running datatbles on? Perhaps there is some misunderstanding in the concept of datatable. If you are running datatables, your repeated variables perhaps 38, CEDULA etc has to be the column header of the datatable file. How datatable runs is it will run the whole flow on every row of the data. In the case of if you need to login only once on the first data, then you can use the iteration keyword:

```
if iteration equals to 1
  //do something
```

**Comment by Darkness99q** [comment]
> 

hello, sorry for the delay in answering. it's almost accurate. the variables are in CEDULA and are in the header identified as indicated. where 38 is mentioned is not a variable. The process itself is simple I must enter a number and take a screenshot of the result. The code works normally when I disconnect it. it has worked in 20 rows of excel until I stop it with the button you indicate. I have experimented with different settings but they have not worked. I suspect it closes the process because it runs in the background or something similar. but I don't know how to fix it or if that's the problem. when reviewing in the task manager. I notice that the threads suddenly stop.

**Comment by ruthtxh** [comment]
Hi @Darkness99q 

I tried to replicate your scenario but plugging/unplugging the power but my flow continues to run.
Can you try your scenario and run the following simple flow using datatables on Word as well as  from the command prompt:
```
echo `number`
```
[datatable_test.csv](https://github.com/kelaberetiv/TagUI/files/8866369/datatable_test.csv)

To run from command prompt you can save the flow as flow.tag and run `tagui flow.tag datatable_test.csv`

Does the same issue occur when you run from the command prompt?
