### ISSUE TITLE
Error handling - reading messages

### ISSUE THREAD

**Issue by siwieck** [kelaberetiv/TagUI#1244]
Hi, I am trying to automate SAP web transactions with TagUI. It is possible, but error handling is limited in TagUI. The Try/Catch functionality (when catching and error, one could try to read error messages written by SAP system on the page) would help much. Often the error (not being able to read/click a certain page element) is caused by wrong data, entered in previous steps. In such cases SAP system writes messages on the page. I could add trying to read messages between each actual step,  but this would slow the execution (as messages are quite complex - reading from popup, after click on a certain page element). Thus reading messages only when error appeared would be the best solution. This is one of Try/Catch use cases, but I am sure there are plenty of them.

Such error handling is well incorporated in Microsoft Power Automate Desktop (PAD) and works perfectly. Please consider adding it to TagUI as well.

**Comment by ruthtxh** [comment]
Hi @siwieck, seems like this has been explored before and is not technically feasible as documented in this issue/comment [here](https://github.com/kelaberetiv/TagUI/issues/1062#issuecomment-871937623).

Here are some error handling suggestions you can look into:
https://tagui.readthedocs.io/en/latest/advanced.html?#handling-exceptions-and-errors

**Comment by siwieck** [comment]
I admit it was already thought about. But there is no solution. Catching a result of a Taguig flow as i understand allow running a conditional second flow but that second flow cannot attach to the same web browser window as the first (to read messages)? Or am I wrong? And I do believe in programming there is no impossible solutions, but sometimes too complex, too costly.

**Comment by ruthtxh** [comment]
Hi @siwieck 

As per the issue/comment I referenced above, TagUI parses out code for CasperJS, one of the dependency engines to run, so it is pretty much dependent on the dependency architecture as well.
Yes, if you are chaining the flows together, they will run on separate chrome user sessions. 
We will review this issue and see how we can handle such scenarios better. Thanks for bringing this up!
