### ISSUE TITLE
type 支持输入中文吗？- try using clipboard and keyboard step to copy/paste

### ISSUE THREAD

**Issue by kangyiwen** [kelaberetiv/TagUI#1247]
Hi，遇到个问题，type 输入英文没问题
`type (868,556) as test`

输入中文就会卡主不动，请问是什么原因？
`type (868,556) as 测试`

**Comment by ruthtxh** [comment]
Hi @kangyiwen you can use clipboard step and keyboard step to simulate a copy/paste into the field, for example:
```
a = "测试"
clipboard(a)
click (868,556)
keyboard [ctrl]v
```

**Comment by kangyiwen** [comment]
我以为是编码问题，看来是不支持中文。  剪贴板这方法可以，谢谢
