### ISSUE TITLE
Tagui not executing if conditions - pending details

### ISSUE THREAD

**Issue by TejasShete1196** [kelaberetiv/TagUI#1248]
Hello Ken,

I am facing this weird issue the code was running for more than three months now .. and suddenly it is was throwing syntactical error msg ') ' .  But when I checked the code as it was not executing if conditions and not even throwing error for them , what would be the reason behind  error?

**Comment by ruthtxh** [comment]
Hi @TejasShete1196 can you share your script and the exact error message so we can take a look? Thanks!
