### ISSUE TITLE
Unable to launch TagUI Live from C:\Windows\System32 - permission issue, try running from another folder

### ISSUE THREAD

**Issue by fredchan23** [kelaberetiv/TagUI#1249]
Installed Version: You are already using the latest version of TagUI (v6.110)

![image](https://user-images.githubusercontent.com/53962304/175931690-50792776-cf77-470e-b2d4-589b5f77cbd6.png)

**Comment by ruthtxh** [comment]
Hi @fredchan23, as TagUI live creates temporary files (such as live.tag and live.tag.js) in whichever folder you run from i.e. (C:\Windows\System32), it needs to have the appropriate access permissions to read and write to these temp files.

Can you try running live mode from another folder?
