### ISSUE TITLE
Updated statistics script to collate downloads from GitHub stats - fyi

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#1251]
Hi @ruthtxh I saw that you published a new release using GitHub actions. For such publishing it means there will be a new release with each commit I believe. In that case it doesn't make sense to track downloads by "releases" anymore or you will deal with 50-100 releases number which is hardly actionable. I've updated the script (attached below as .txt due to limitation on GitHub issues). You can use that as a reference for updating yours for TagUI website, that you mentioned previously.

[downloads.txt](https://github.com/kelaberetiv/TagUI/files/9034452/downloads.txt)

The script assumes only 3 files (Windows, Mac, Linux) in the release, as I saw in v6.110.0. In future you just need to change the line `if r[n]['tag_name'] in ['v6.110.0']:` to `if r[n]['tag_name'] in ['v6.110.0', 'v6.111.0']:` accordingly to include newer versions. It's probably doable to write some logic to map to number and include all from 110, but will need to rewrite stg new after v7. Lastly, I saw that there is no Windows exe from the release and the TagUI readthedocs page. I assume that is deprecated?

**Comment by kensoh** [comment]
Linking to the statistics file - https://tebel.org/stats/tagui_downloads.csv

**Comment by kensoh** [comment]
Updated script, there was a harmless but duplicated line in above download.txt

https://github.com/kensoh/tagui_distribution/blob/master/downloads.py

**Comment by ruthtxh** [comment]
Hi @kensoh 

For GitHub Actions we will only trigger the release workflow when we tag the version that is ready for a release, hence not every commit will result in a new release. So the usual way of tracking numbers is still maintainable as long as we add the new version number to track.

For the packaged windows exe, unfortunately compiling it on each new release still very manual and based on feedback the usual method of installing does not cause too much of a hassle so we have removed it for now.

Ok noted on the stats file, thanks for updating!

**Comment by kensoh** [comment]
I see, got it. I'll retain this script logic for now, and if there are newer releases it is easier to update by adding that one-line change.

**Comment by ruthtxh** [comment]
@kensoh Ok noted! The Code Check GitHub Action is the one that will be triggered on each push to master branch, and what it does is it will run the test by running positive_test.tag file and reconcile the signature file with the generated js file.

**Comment by kensoh** [comment]
Oh that is a nice automation to have. Can you share how does it run? I think by default running the positive_test.tag will trigger visual automation, but on the cloud how would the launching of SikuliX process work properly without a display?

**Comment by kensoh** [comment]
I see, got it. Thanks Ruth, for sharing this solution! :)
