### ISSUE TITLE
'RunTime:loadLib: libopencv_java430.so (failed) probably dependent libs missing' error while running sikuli test script in Red hat 7.6

### ISSUE THREAD

**Issue by rajateshr** [kelaberetiv/TagUI#1253]
Used maven project: My Automation sikuli script: package Sikuli1.DesktopProject; Error logs: OpenJDK 64-Bit Server VM warning: You have loaded library /home/rajatesh/.Sikulix/SikulixLibs/libopencv_java430.so which might have disabled stack guard. The VM will try to fix the stack guard now. It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'. [error] RunTime:loadLib: libopencv_java430.so (failed) probably dependent libs missing: /home/rajatesh/.Sikulix/SikulixLibs/libopencv_java430.so: /home/rajatesh/.Sikulix/SikulixLibs/libopencv_java430.so: file too short [error] Save your work, correct the problem and restart the IDE! [error] see: https://github.com/RaiMan/SikuliX1/wiki/macOS-Linux:-Support-Libraries-for-OpenCV-4 TERMINATING: problem with native library: libopencv_java430.so Exception in thread "main" java.lang.ExceptionInInitializerError at org.sikuli.script.Pattern.(Pattern.java:128) at Sikuli1.DesktopProject.SikuliProject.main(SikuliProject.java:11) Caused by: org.sikuli.script.SikuliXception: fatal: problem with native library: libopencv_java430.so at org.sikuli.script.support.RunTime.terminate(RunTime.java:1140) at org.sikuli.script.support.RunTime.libsLoad(RunTime.java:1285) at org.sikuli.script.support.RunTime.loadLibrary(RunTime.java:1434) at org.sikuli.script.Finder$Finder2.(Finder.java:538) ... 2 more

OS Used: Red Hat (RHEL Version 7.6)...
I am getting error only in this OS version..For the rest of the OSs it is working..Please help me out in resolve this issue ASAP.
 Code:
package Sikuli1.DesktopProject;

import org.sikuli.script.FindFailed;
import org.sikuli.script.Pattern;
import org.sikuli.script.Screen;

public class SikuliProject {

	public static void main(String[] args) throws FindFailed {
		Screen s= new Screen();
		Pattern QGIS = new Pattern("/home/mglocadmin/Documents/Screenshots/QGIS.png");
		Pattern Layer = new Pattern("/home/mglocadmin/Documents/Screenshots/Layer.png");
		Pattern CreateLayer = new Pattern("/home/mglocadmin/Documents/Screenshots/Createlayer.png");
		Pattern ShapeLayer = new Pattern("/home/mglocadmin/Documents/Screenshots/ShapeLayer.png");
		Pattern Name = new Pattern("/home/mglocadmin/Documents/Screenshots/Name.png");
		Pattern Close1 = new Pattern("/home/mglocadmin/Documents/Screenshots/Close1.png");
		Pattern Close = new Pattern("/home/mglocadmin/Documents/Screenshots/Close.png");
		Pattern SelectPoly = new Pattern("/home/mglocadmin/Documents/Screenshots/SelectPoly.png");
		Pattern Polygon = new Pattern("/home/mglocadmin/Documents/Screenshots/Polygon.png");
		Pattern OKButton = new Pattern("/home/mglocadmin/Documents/Screenshots/OKButton.png");
		Pattern Shapepoly = new Pattern("/home/mglocadmin/Documents/Screenshots/ShapePolygon.png");
		Pattern Message = new Pattern("/home/mglocadmin/Documents/Screenshots/message.png");
		Pattern Yes = new Pattern("/home/mglocadmin/Documents/Screenshots/Yes.png");
		Pattern Shape = new Pattern("/home/mglocadmin/Documents/Screenshots/Shape12.png");
		s.find(QGIS);
		s.click(QGIS);
		s.wait(4.0);
		s.find(Layer);
		s.click(Layer);
		s.find(CreateLayer);
		s.click(CreateLayer);
		s.find(ShapeLayer);
		s.click(ShapeLayer);
		s.wait(4.0);
		s.find(Name);
		s.click(Name);
		s.type(Name,"ShapePolygon1");
		/*s.find(Close1);
		s.click(Close1);*/
		s.find(SelectPoly);
		s.click(SelectPoly);
		s.find(Polygon);
		s.click(Polygon);
		s.find(OKButton);
		s.click(OKButton);
		s.wait(4.0);
		if(s.exists(Message) != null)
		{
			System.out.println("PASS");
		}
		else
		{
			System.out.println("FAIL");
		}
		s.find(Yes);
		s.click(Yes);
		s.wait(4.0);
		if(s.exists(Shape) != null)
		{
			System.out.println("PASS");
		}
		else
		{
			System.out.println("FAIL");
		}
		//System.out.println(s.find(Shapepoly).getText());	
		s.find(Close);
		s.click(Close);
	}

}

**Comment by ruthtxh** [comment]
Hi @rajateshr for java can you try using the Amazon Coretto OpenJDK as per the installation instruction here?
https://tagui.readthedocs.io/en/latest/setup.html#windows

**Comment by kensoh** [comment]
Adding on @ruthtxh, @rajateshr, this issue you are asking is about using SikuliX API in Java programming language. This has nothing to do with TagUI and @rajateshr should raise an issue at SikuliX GitHub repo instead to find a solution.
