### ISSUE TITLE
read in for loop, not correct - try this

### ISSUE THREAD

**Issue by cenwenchu** [kelaberetiv/TagUI#1257]
code:

for (n=1; n<=2; n++)
	if exist('(//div[@class="daren-card"])["n"]')
	{
		
		read (//div[@class="daren-card"])['n'] to total
		
		echo `total`
		
		read (//div[@class="daren-card"])[1] to total1
		echo `total1`
		read (//div[@class="daren-card"])[2] to total1
		echo `total1`

		echo `n`
	}
	else
	{
		break
	}

----- run result : 
read (//div[@class="daren-card"])['n'] to total
原来是七七🎈服饰内衣带过小店相似商品31万粉丝量24带货直播数7万看播人数
read (//div[@class="daren-card"])[1] to total1
原来是七七🎈服饰内衣带过小店相似商品31万粉丝量24带货直播数7万看播人数
read (//div[@class="daren-card"])[2] to total1
miki麦琪琪服饰内衣带过小店相似商品27万粉丝量25带货直播数1万看播人数
1
read (//div[@class="daren-card"])['n'] to total
原来是七七🎈服饰内衣带过小店相似商品31万粉丝量24带货直播数7万看播人数
read (//div[@class="daren-card"])[1] to total1
原来是七七🎈服饰内衣带过小店相似商品31万粉丝量24带货直播数7万看播人数
read (//div[@class="daren-card"])[2] to total1
miki麦琪琪服饰内衣带过小店相似商品27万粉丝量25带货直播数1万看播人数
2

--- 
"read (//div[@class="daren-card"])['n'] to total " not as except run~

**Comment by ruthtxh** [comment]
Hi @cenwenchu you can try the following syntax, do take note of the difference in quotation marks and backticks.
```
for n from 1 to 2
	if exist('(//div[@class="daren-card"])[' + n + ']')
		read (//div[@class="daren-card"])[`n`] to total
		echo `total`
```

**Comment by cenwenchu** [comment]
thanks @ruthtxh , i made a low level mistake :( ,  [`n`] replace  ['n']，it‘s ok.
