### ISSUE TITLE
Problem in accessing iframe - try this

### ISSUE THREAD

**Issue by cenwenchu** [kelaberetiv/TagUI#1258]
<img width="1163" alt="截屏2022-07-19 下午2 22 57" src="https://user-images.githubusercontent.com/80797/179680271-bbdf0517-bb07-4f81-a329-feb7058c75d9.png">

i can access "  click //*[@id="frame_list"]/iframe[2] "

<img width="1184" alt="截屏2022-07-19 下午2 23 43" src="https://user-images.githubusercontent.com/80797/179680566-7033184b-c526-4022-8da2-567fb3d08f33.png">

but can't access iframe any elements, like this:

click //*[@id="_jt_body_list"]/div[1]/div[2]/div[2]/div[1]

("//*[@id="_jt_body_list"]/div[1]/div[2]/div[2]/div[1]")  is in "//*[@id="frame_list"]/iframe[2] "

**Comment by marcelocecin** [comment]
https://tagui.readthedocs.io/en/latest/reference.html?highlight=frame#frame

**Comment by ruthtxh** [comment]
Hi @cenwenchu yes you can use the frame step like this, with the following steps that occur within the frame indented:

```
frame home
  click //*[@id="_jt_body_list"]/div[1]/div[2]/div[2]/div[1]
```

**Comment by cenwenchu** [comment]
@ruthtxh homeframe has no name, id = home; second frame has no name and no id. use frame block need iframe name. how can i do ?

**Comment by ruthtxh** [comment]
Hi @cenwenchu
If you want to access the frame without id/name you can use javascript to inject the id/name attribute and use frame step. For example:
```
dom document.querySelector("iframe[src*='app/order/order/list.aspx']").setAttribute("id", "sampleFrame");
frame sampleFrame
	// do your steps here
```
