### ISSUE TITLE
double for loop , can't run - try this

### ISSUE THREAD

**Issue by cenwenchu** [kelaberetiv/TagUI#1259]
for (n=1; n<=20; n++)
	if exist('//*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[' + n + ']')
	{
		
		read (//*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr)[`n`] to total
		echo `total`
		
		rows = count('//*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[`n`]/td')
		
		
                 **// ---- if  i delete this block, it can run;**
		for (m=1; m<=rows; m++)
		 	echo `m` 
		
		
		if n equals to 1
		{
			mouse down
			click //*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[`n`]
			mouse up
		}
		else
		{
			click //*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[`n`]
		}
		

	}
	else
	{
		break
	}

**Comment by ruthtxh** [comment]
Hi @cenwenchu 
Can you try the following? I have changed the code blocks to the TagUI indentation for consistency.
```
for n from 1 to 20
	if exist('//*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[' + n + ']')
		read (//*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr)[`n`] to total
		echo `total`
		rows = count('//*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[`n`]/td')
		for m from 1 to rows
		 	echo `m` 
		if n equals to 1
			mouse down
			click //*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[`n`]
			mouse up
		else
			click //*[@id="guide-querySupplierShelvesItem"]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[`n`]
	else
		break
```
