### ISSUE TITLE
Problems with configuration python - try creating symlink for python/python3

### ISSUE THREAD

**Issue by pp082** [kelaberetiv/TagUI#1267]
hi!!!

I read the issue [765](https://github.com/kelaberetiv/TagUI/issues/765) and there is a comment asociate sis https://github.com/kelaberetiv/TagUI/issues/765#issuecomment-603685328.

I think I have the same problems with the configuration, but I don't know how I can solve this.

I create a tag file test02.tag 

```
echo Hello World
py begin
a=1
b=5
c=a+b
print(c)
py finish
echo `py_result`
```

```
user1@M1 ~ %  tagui /Users/tagui/flows-M1Pro/RPA-Tagui/test02.tag -n

START - automation started - Sun Jul 31 2022 22:32:57 GMT-0400 (-04)
Hello World
py a=1
b=5
c=a+b
print(c)
```
but the execution was stuck  :(

When I install python with brew command I used (was not previously installed)

```
user1@M1 ~ %  brew install python
```
Then to check 

```
user1@M1 ~ % brew list
...other programs .. and... python@3.9

user1@M1 ~ % pip3 -V
pip 22.1.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)

user1@M1 ~ %  python3 -V
Python 3.9.13
```
```
user1@M1 ~ % python -V
zsh: command not found: python
```

tagui_py.log

`/usr/local/bin/tagui: line 340: python: command not found`

**Comment by ruthtxh** [comment]
Hi @pp082 you probably need to create a symbolic link to point the python command to python3. There are some suggestions in this [external thread](https://stackoverflow.com/questions/18419500/how-to-make-mac-os-use-the-python-installed-by-homebrew) you can try.

**Comment by pp082** [comment]
@ruthtxh 

in the terminal I used

```
$ echo 'export PATH=/opt/homebrew/opt/python@3.9/libexec/bin:$PATH' >> ~/.zprofile
$ source ~/.zprofile
$ python -V
Python 3.9.13
```
Then

user1@M1 ~ %  tagui /Users/tagui/flows-M1Pro/RPA-Tagui/test02.tag -n

START - automation started - Mon Aug 01 2022 00:43:30 GMT-0400 (-04)
Hello World
py a=1
b=5
c=a+b
print(c)
6

FINISH - automation finished - 0.5s

Excelent !!! 👍 

Thanks a lot !!
