### ISSUE TITLE
How can we send emails from TagUI as part of an automation flow?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#134]
Raising this from an user email for sharing, as other users might benefit from this question.

---

**Comment by shahidshaikhleaque** [comment]
Hi @kensoh 
The steps in second way above are performed once we already enter into outlook?
what steps we need to write to open outlook?

**Comment by kensoh** [comment]
Hi @shahidshaikhleaque the step `click outlook-icon.png` opens outlook. It can be outlook icon on the taskbar, or desktop etc. If desktop you need to use dclick to double click to open.

**Comment by shahidshaikhleaque** [comment]
Hi @kensoh 
I tried with dclick but I am getting error as "cannot find image file C:/tagui/src/samples/outlook-icon.png".
I am using windows OS.
How do I find the image name of the desktop icon or taskbar icon.
Also if I don't have shortcuts on desktop/taskbar then is it possible to open via application path as below :
C:\Program Files\Microsoft Office\root\Office16\OUTLOOK application

**Comment by kensoh** [comment]
You have to take your own screenshots of the UI elements. Above is an example only for macOS. Even if you use you have to download the zip file with the images to use.

To run command directly you can try below to see if it works -
`run C:\Progra~1\Microsoft Office\root\Office16\OUTLOOK`

**Comment by shahidshaikhleaque** [comment]
hi @kensoh I took the screenshot of outlook icon from desktop and given the same name as outlook-icon.png still got the above error. I am not able to understand how this image will be related to outlook icon on desktop.
And also if this automation needs to be done by another developer then he/she needs to take the screenshots as well?

Thanks,
Shahid

**Comment by kensoh** [comment]
The error is the image file cannot be found. Double check to make sure the file name and file extension is correct. This visual automation method is you capture screenshot of icon, and ask TagUI to click on the image. You can find out more about its usage here -

https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by shahidshaikhleaque** [comment]
Hello @kensoh I installed Sikuli and successfully opened outlook with function "doubleClick("1571835268634.png")". 
I saved the file in C:\tagui\src\samples.sikuli.
There is one .py file inside.
Could you please help me how to call this using tagui ?

**Comment by kensoh** [comment]
Sorry I can't help, you are asking questions which are already covered in TagUI readme.

Refer here for usage - https://github.com/kelaberetiv/TagUI#visual-automation
Refer here for example - https://github.com/kelaberetiv/TagUI/issues/113#issuecomment-378194245
