### ISSUE TITLE
Calling TagUI as a webservice for integration with end consumer apps

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#138]
Raising this from an user email for sharing, as other users might benefit from this question.

---

First of all – congratulations on great utility tool you have created.
 
I had a question while going through packs and videos (and just about to start installation/hands on) – Is there ability in toolkit, that a particular automated flow (simulation of data entry, click events and response from web server) can be encapsulated as web service? This web service then can be used by diff integration buses or end consumer apps.

**Comment by kensoh** [comment]
Thanks for your encouragement and the interesting question. TagUI comes with a webservice that can be deployed directly on your web server. The way to call the webservice is using the following syntax -

```
http://your_website_url/tagui_service.php?SETTINGS="flow_filename option(s)"
```
More details on this feature here - https://github.com/kelaberetiv/TagUI#api

For security reasons, the webservice is enabled through crontab and not designed to give response immediately, as that would require program execution setting to be enabled in your PHP configuration. Look forward to hearing from you your experience and comments.

**Comment by ramu-yarru** [comment]
Hi, 
Thank you for the wonderful tool. 
I have one question in continuation to the above. I have deployed the webservice on my webserver(XAMPP->Apache) and hitting the URL you mentioned above from my browser after including my flow file name in SETTINGS. I am getting the below message in my browser.
**[6] ./tagui techforce added into queue** 
But my flow is not getting triggered. Note that I have set frequency of tagui chrontab to 5 minutes. 
Where should I keep my flow file (path on file system) in order for the cron to trigger my flow?
Is there any way to get response from my flow file as a response to the API invocation? If so, could you please throw some light on how can we achieve this.

Thanks,
Ram

**Comment by kensoh** [comment]
Hi Ram, thanks for raising this question, looking at it from the new issue you raised (https://github.com/kelaberetiv/TagUI/issues/169)
