### ISSUE TITLE
TagUI support for IE (internet explorer)

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#154]
Raising this on behalf on a user's query through email, so that other users can benefit.

---

Can I check with you if there will be any future support for IE?

**Comment by kensoh** [comment]
Can you tell me more about your use scenario?

If go by the underlying framework, CasperJS does not have integrations with IE (internet explorer) or Edge. If go directly by TagUI Chrome DevTools Protocol integration, there is an [IE adapter but looks unmaintained](https://github.com/Microsoft/IEDiagnosticsAdapter). There is an [Edge adapter](https://github.com/Microsoft/edge-diagnostics-adapter) that looks maintained.

My guess is these 2 would likely to be the entry points to explore integrating with IE or Edge. Though at the moment, integrating with IE or Edge is not in the [development pipeline](https://github.com/kelaberetiv/TagUI/issues/83) as other items have bigger and more urgent impact.

At the moment, you can consider using the [visual automation](https://github.com/tebelorg/TagUI#visual-automation) functionality of TagUI to talk to IE. But that will be based on visual recognition to click and enter text and OCR using the read step. Should work for simple use cases but not for advance cases where data needs to be extracted with fine-tune control.

**Comment by kensoh** [comment]
**response from potential user**

Thanks for your prompt reply.  Reason why I'm asking for IE is because in the organisation, IE is the only official supported browser and we are not allowed to install Chrome.

Currently, I'm using PowerShell to do some simple IE web automation to go in and extract some values for checking purposes.  Comparing it with yours, your coding is so much simpler!  Hence, if TagUI supports IE, I would gladly change it.

Thank you again for sharing this useful info.  Some day I do hope it supports IE. :)

---

**my response**


I see.. Oh we are connected on LinkedIn too. Got it, I'll keep note of demand for IE while I clear the pressing stuffs in pipeline. Thanks for sharing your potential use scenario.

Want to check if you go straight to the packaged installation below and download the package zip for your OS, will it work for you? The default execution mode the engine is actually PhantomJS.

https://github.com/kelaberetiv/TagUI#packaged-installation

The packaged installation comes with all dependencies packaged in, so at some institutions, we are surprised that folks can just download, unzip, and run, without special admin access to that computers or need to install / setup anything.

**Comment by kensoh** [comment]
**user response**

Yes, it works perfectly just by downloading the Windows package.  It only took me less than 5 mins to get it up and running one of your examples. Truly amazing I must say.  Coz, I've tried other RPA like Leo, UiPath, etc.. the learning curve is simply too high.

I actually got to know your product after attending a talk by Laurence Liew.

**Comment by lim-enhui** [comment]
in similar scenario HP Quality web enterprise application uses action script or something that I do not know of for its component and apparent there is no web components for me to use.. and also it only do support with internet explorer...
