### ISSUE TITLE
How to pass a parameter of input in command line (or another script)?

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#159]
I need to re-use multi-time a scritp so I think to launch a tagui script inside an another.
But I need to change a parameter as input as specifies in cheatsheet:

> "input(s) | add your own parameter(s) to be used in your automation flow as variables p1 to p9"

How can I do that?
I tried :
`tagui filename.tagui p1='test'`

but it return ERROR file not fount.

And next: How to use this parameter in the script? like another variable?
Thanks!

**Comment by kensoh** [comment]
Hi @adegard that's a good question. TagUI will automatically take the command line parameters and map them to p1, p2, p3 etc. The [command line options](https://github.com/kelaberetiv/TagUI#to-use) (click the point there to expand and show) will automatically be ignored and not be taken as parameters.

For example this script demo -

```
echo "parameter 1 is - " p1
echo "parameter 2 is - " p2
echo "parameter 3 is - " p3
```

Gives the following output and chrome option automatically ignored not to be used as parameter -

```
TA:Desktop kensoh$ tagui demo chrome apple orange banana

START - automation started - Fri May 11 2018 01:22:25 GMT+0800 (+08)

parameter 1 is - apple
parameter 2 is - orange
parameter 3 is - banana

FINISH - automation finished - 1.9s
```

the order of the chrome option is not important, it will be taken out and not used as parameter - 
```
TA:Desktop kensoh$ tagui demo apple orange banana chrome

START - automation started - Fri May 11 2018 01:25:43 GMT+0800 (+08)

parameter 1 is - apple
parameter 2 is - orange
parameter 3 is - banana

FINISH - automation finished - 2.0s

TA:Desktop kensoh$ tagui demo apple orange chrome banana       

START - automation started - Fri May 11 2018 01:25:59 GMT+0800 (+08)

parameter 1 is - apple
parameter 2 is - orange
parameter 3 is - banana

FINISH - automation finished - 1.9s
```

I'll close the issue, but lemme know if you have any questions or comments!

**Comment by saratSubramaniam** [comment]
Hello, quick question. How do I pass a text variable with spaces ?
Say, I want p1 to be 'hello world'.

**Comment by kensoh** [comment]
Interesting question, posted a new issue - https://github.com/kelaberetiv/TagUI/issues/358

---

Hey Sarat, not designed to pass in variables with space, but you can use the following method by passing filename of complex inputs parameters. for eg, assuming data.json contains the data -

`tagui demo_script data.json`

**demo_script**
```
load `p1` to data
echo data
```
