### ISSUE TITLE
Error - cannot find element during automation

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#161]
--------------------------------
This is the content I wrote for opening fb.com and type some text
https://www.google.co.in/
click lst-ib
enter lst-ib as fb.com
click rhscol
click //a[text()="Facebook - Log In or Sign Up" or contains("https://fb.com/",@href)]
enter pass as manoj[enter]
click u_0_2
------------------------------------------
while running this file as tagui filename
---------------
START - automation started - Mon May 14 2018 14:12:29 GMT+0530 (IST)
https://www.google.co.in/ - Google

click lst-ib
ERROR - cannot find lst-ib
-----------------------------
I am getting error as above.

When I run the above file with some browser as

tagui filename chrome

a blank page is opening and stopping there without any functionality.

when I run with 
---------------
tagui filename firefox
------------

I am getting error as 

START - automation started - Mon May 14 2018 14:10:18 GMT+0530 (IST) 
c is undefined                                                                   
  /home/admin1/Downloads/tagui/src/resource:/slimerjs/slQTKeyCodeToDOMCode.jsm:36 
  /home/admin1/Downloads/tagui/src/resource:/slimerjs/slQTKeyCodeToDOMCode.jsm:36 
  /home/admin1/Downloads/tagui/src/resource:/slimerjs/slimer-sdk/webpage.js:15

I am using Ubuntu 16.04 and npm version as 5.3.0

**Comment by kensoh** [comment]
@nsahithi it is probably because the rendering in default mode (PhantomJS) is different from Chrome mode. For example, running below script using `tagui google chrome` - 

**google**
```
https://www.google.co.in/
click lst-ib
enter lst-ib as fb.com[enter]
click Facebook - Log In or Sign Up
```

**returns following**
```
START - automation started - Mon May 14 2018 19:12:11 GMT+0800 (+08)
https://www.google.co.in/ - Google

click lst-ib
enter lst-ib as fb.com[enter]
click Facebook - Log In or Sign Up

https://www.facebook.com/ - Facebook
FINISH - automation finished - 8.6s
```

**Comment by nsahithi** [comment]
Yes, I did the same, I just executed this script 

--------------
https://www.google.co.in/
click lst-ib
enter lst-ib as fb.com[enter]
click Facebook - Log In or Sign Up
----------------------------------------
as ./tagui filename chrome
the same blank page is opening and no functionality is happening.


do we need to change any visible mode in phantomjs(which is not human readable).

I am using UBUNTU 16.04 version, npm 5.3.0 and 
"casperjs": "^1.1.4",
    "phantomjs-prebuilt": "^2.1.16",
    "slimerjs": "^1.0.0"

**Comment by kensoh** [comment]
Hi @nsahithi can you try the following?

1. check if php is installed on your Ubuntu with `php --version`

2. try typing `google-chrome` from your prompt to see if Chrome launches

3. try unzip from the [Linux packaged installation](https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Linux.zip) of TagUI and try again

check the contents of tagui/src/tagui_chrome.log and paste what is inside here

**Comment by kensoh** [comment]
Pasting email reply here for reference -

Hi Sahithi,

Thanks for sharing your logs and details. After you run is it TagUI hangs at the command prompt? It seems that TagUI has issue connecting to your Chrome websocket connection.

After you run tagui filename chrome and the empty chrome window opens up, can you type the following command in another shell window and send raw_chrome_connections.txt file to me?

`curl -s localhost:9222/json > raw_chrome_connections.txt`

Please also send me the output on screen of following command from another shell prompt after the Chrome window appears and hangs there -

```
curl -s localhost:9222/json | grep -A 1 '"url": "about:blank"' | grep webSocketDebuggerUrl | cut -d'"' -f 4
```

**Comment by kensoh** [comment]
(closing for now - following up through email)

**Comment by fez226** [comment]
@kensoh sorry for the question, maybe its not the place but i need help with something, its possible to innactive the warning dialog message box of chrome?  or the Tagui click the Ok buttom... see the example on the image. thanks

![image](https://user-images.githubusercontent.com/47187733/54242195-5b385d00-44e9-11e9-9561-893b649881ed.png)

**Comment by kensoh** [comment]
I don't think this popup window can be accessed by locater in DOM. You can try using computer vision to click on the OK button. More details on setup and usage below -

https://github.com/kelaberetiv/TagUI/blob/master/README.md#visual-automation

**Comment by fez226** [comment]
yeah i think the same with sikuli, i tried and works. but you need to do a

IF VISIBLE('ok_buttom.PNG')
{
click ok_buttom.PNG
}
....
and works on chrome headless mode! 

thanks
