### ISSUE TITLE
looking for frame name

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#165]
Hi, 

I don't know how to access to this iframe:

```
<div id="BSFRAMECONTENT" style="padding:0!important;"><div class='embed-responsive' style="padding-bottom:150%;" >

<iframe  class="embed-responsive-item"  frameborder = "0" src="https://serviziweb2.inps.it/PagamentiBollettiniLD/accessoUtente.do"  width="100%" height = "100%"  >
</iframe>
</div>
```

It doesn't have any "name"

If it is not possible : can I open it in another tab and "switch " from one tab to another?
Thanks a lot
Arnaud

**Comment by kensoh** [comment]
Hi @adegard , interesting.. This frame has no name and no id.

1 way to consider is creating name attribute for it and setting it to some value. It should be able to be done using dom step to call the [JavaScript code like these](https://www.w3schools.com/jsref/met_document_createattribute.asp).

A 2nd way is if clicking on a link opens up a new page, the popup step can be used. A 3rd way is if you know the URL, you can directly write that URL in your automation flow to go to that page and do what you need over there.

Lemme know how it goes!
