### ISSUE TITLE
snap not working on some pages

### ISSUE THREAD

**Issue by shoeper** [kelaberetiv/TagUI#174]
Hi,

I currently try to automate downloading a newspaper to my archive because it is only available online for limited time (7 days per issue).  I decided to take some screenshots to see whether things are working like I expect them to work. Unfortunately in headless mode snap hangs and both, phantomjs and chrome have 100%cpu. I also tried to enable the debugging mode which didn't gave me very much information. I try to use headless mode because it looks like the normal mode cannot render the next pages (snap is just empty - I'd say those pages are relatively complex).

```
tagui@51e7de6e5311:/s$ /tagui/src/tagui sz headless debug

START - automation started - Tue May 22 2018 15:24:56 GMT+0000 (UTC)
[info] [phantom] Starting...
[info] [phantom] Running suite: 18 steps
[debug] [phantom] opening url: about:blank, HTTP GET
[debug] [phantom] url changed to ""
[debug] [phantom] Successfully injected Casper client-side utilities
https://epaper.sueddeutsche.de/login - SZID - Login

[info] [phantom] Step anonymous 2/18: done in 1953ms.
wait 10 seconds
[info] [phantom] Step anonymous 3/18: done in 1958ms.
[info] [phantom] Step _step 4/18: done in 1977ms.
[info] [phantom] wait() finished waiting for 10000ms.
type id_login as username
[info] [phantom] Step _step 5/19: done in 11994ms.
[info] [phantom] waitFor() finished in 229ms.
[info] [phantom] Step then 6/20: done in 13154ms.
type id_password as password
[info] [phantom] Step anonymous 7/20: done in 13156ms.
[info] [phantom] Step _step 8/21: done in 13176ms.
[info] [phantom] waitFor() finished in 224ms.
[info] [phantom] Step then 9/22: done in 14330ms.
click authentication-button
[info] [phantom] Step anonymous 10/22: done in 14331ms.
[info] [phantom] Step _step 11/23: done in 14351ms.
[info] [phantom] waitFor() finished in 224ms.
[info] [phantom] Step then 12/24: done in 16600ms.
wait 10 seconds
[info] [phantom] Step anonymous 13/24: done in 16605ms.
[info] [phantom] Step _step 14/24: done in 16625ms.
[info] [phantom] wait() finished waiting for 10000ms.
snap page to page1.pdf
here it hangs with both processes using 100% cpu
```

The flow looks like this. I've added the high wait times to see if it improves anything.
```
https://epaper.sueddeutsche.de/login
wait 10 seconds
type id_login as username
type id_password as password
click authentication-button
wait 10 seconds
snap page to page1.pdf
https://epaper.sueddeutsche.de/Stadtausgabe/2018-05-22
wait 10 seconds
snap page to page4.pdf
click issue__cover
wait 10 seconds
snap page to page2.pdf
click sz-daily-download-thumb-tray-control
click //a[text()="Ganze Ausgabe speichern"]
wait 10 seconds
snap page to page3.pdf
```

I'm using https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Linux.zip from yesterday.

I run TagUI using docker, which allows me to just upload it to my gitlab and schedule a regular task where I don't have to care about the system environment and it can just be run on any runner available. The Dockerfile looks like this:
```
FROM debian:latest

RUN apt-get update \
  && apt-get -y install \
       php-cli \
       python \
       unzip \
       wget \
       curl \
       procps \
  && wget https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Linux.zip \
  && unzip TagUI_Linux.zip \
  && rm TagUI_Linux.zip \
  && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i google-chrome-stable_current_amd64.deb || true \
  && apt-get install -f -y \
  && dpkg -i google-chrome-stable_current_amd64.deb \
  && rm google-chrome-stable_current_amd64.deb \
  && apt-get -y remove unzip \
  && rm -rf /var/lib/apt/lists

RUN adduser tagui && chmod +r -R /tagui && chown tagui -R /tagui
USER tagui
WORKDIR /s

#ENTRYPOINT ["/tagui/src/tagui"]
```

And I run it with this `docker run -it --rm --privileged --shm-size 256m -v "$PWD/s":/s tagui bash` and invoke TagUI with `/tagui/src/tagui sz headless debug`

Edit: I've tried a minimal flow to take a snap of google and that works fine.
```
tagui@f2de344576a0:/s$ cat google
https://www.google.com
snap page to google.pdf
```
```
~/D/d/d/tagui docker run -it --rm --privileged --shm-size 256m -v "$PWD/s":/s tagui bash
tagui@f2de344576a0:/s$ /tagui/src/tagui google headless debug

START - automation started - Tue May 22 2018 15:56:50 GMT+0000 (UTC)
[info] [phantom] Starting...
[info] [phantom] Running suite: 4 steps
[debug] [phantom] opening url: about:blank, HTTP GET
[debug] [phantom] url changed to ""
[debug] [phantom] Successfully injected Casper client-side utilities
https://www.google.com - Google

[info] [phantom] Step anonymous 2/4: done in 1653ms.
snap page to google.pdf
[info] [phantom] Step anonymous 3/4: done in 1763ms.

https://www.google.com/ - Google
FINISH - automation finished - 2.0s

[info] [phantom] Step anonymous 4/4: done in 1967ms.
[info] [phantom] Done 4 steps in 1967ms
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
```

**Comment by kensoh** [comment]
Hi @shoeper , the debug messages are for PhantomJS, which will be not useful if headless mode is used (as browser is headless Chrome). It will be hard to troubleshoot this issue as the simple Google page works for you while the member-only portal page which I can't test on does not work.

2 things I can think of to try, see if running on your normal laptop or computer instead of Docker image will it work, and see if tagui_chrome.log has some information what has went wrong when viewing that member page?

Perhaps tail -f tagui_chrome.log to see it or to kill the process after hanging and see the end of the file. For usual webpages it would be Base64 data being transferred from headless Chrome to TagUI to be converted into a snapshot image / pdf.

**Comment by kensoh** [comment]
That's right @shoeper the integrations logs are in the tagui/src folder (Python, SIkuli, R, Chrome, etc). For changing resolution you can edit the width: 1366 and height: 768 settings in tagui/src/tagui_config.txt and see if that helps!

I'll close the issue for now but lemme know if run into any new findings or questions!

**Comment by shoeper** [comment]
Thanks.

Now headless doesn't do anything anymore. I'm not sure where it comes from, but I also had the issue within docker that I sometimes had to restart the container to be able to run the next flow. I'll log off and on later and try again.

**Comment by kensoh** [comment]
Ok Sven, I'll watch out for any new info from you which we can work together on.

**Comment by shoeper** [comment]
I head time to further try it out.

The issue why it doesn't work running multiple times seems to be that chrome is not closed. Searching with `ps aux | grep chrome | grep headless` and killing the chrome process `/opt/google/chrome/chrome --remote-debugging-port=9222 --window-size=1920,905 --headless --disable-gpu about:blank` lets me run another headless flow.

Still have issues downloading the newspaper, though. I also tried to record it using the Chrome plugin, but the generated flow does not work. What about the browser state? Is it being reset after running a flow or are cookies and so on being kept?

**Comment by kensoh** [comment]
Adding on, there is issue with file downloads for headless Chrome, due to security reasons - https://bugs.chromium.org/p/chromium/issues/detail?id=696481

TagUI already has configuration to enable file download in headless mode, you can try running https://github.com/kelaberetiv/TagUI/blob/master/src/samples/3_github in headless option to see the zip file being clicked on, downloaded and saved after execution.

**Comment by shoeper** [comment]
> I've just made a new commit which kills Chrome process by using the process ID versus process name, can you try the cutting edge release to see if it helps for invoking your chrome instance?

I continued using my docker image anyway and didn't run into other issues so far. To do it without running the container privileged it would require a custom seccomp profile (mentioning this just in case someone tries it and wonders why it doesn't work).

> The snap to pdf uses Chrome's printToPDF method. 

That explains it. So as PDF is like print to pdf, while to png is a "real" snapshot of the page as the one would see it in the browser.

> Yes the userAgent only applies to PhantomJS

I worked around this by patching tagui adding `--user-agent='my user agent'`, but found out that the useragent doesn't matter in my case.

> downloaded and saved after execution.

it looks like the file is not being downloaded (assuming it would be stored next to the flow). I try to use the master version and see if that works.

**Comment by kensoh** [comment]
Appreciate your responses Sven :)

> it looks like the file is not being downloaded (assuming it would be stored next to the flow). I try to use the master version and see if that works.
>
> With debug mode it says the download failed (with master unpacked on the latest release & chrome 66 and also with latest release & chrome 66).

Oh for this I mean running TagUI with headless option. Using headless option will run Chrome in headless mode. For TagUI default mode (PhantomJS), need to use the download or receive step in order to download files from website. For TagUI in headless chrome or visible chrome mode, just replicate the user action (clicking download link etc), to trigger the download.

**Comment by shoeper** [comment]
Ah, sure. Yes, with headless it works. So it should work in general. Have to see why it doesn't work with my flow.

Thank you very much :)

**Comment by shoeper** [comment]
So I've run my flow in visual chrome and there is a popup being blocked. Do you know how it can be allowed?

**Comment by kensoh** [comment]
Alternatively for visible Chrome, during running, users can manually select allow popup for the website in top right hand corner of Chrome browser.

Not sure why it is not working for that particular website. By default, TagUI will set a download path to the flow directory, for a webpage that is opened via https or http step.
