### ISSUE TITLE
How to specify specific data table or object repository to be used?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#175]
At the moment, TagUI uses the naming convention to determine which datatable file to be opened. Details here - https://github.com/kelaberetiv/TagUI#datatables

It would be good to have the ability to specify a .csv to be use for a particular automation, autodetecting whether to transpose it, whether to change layout to mainstream datatable representation, whether to auto-pad .csv files without headers defined.

**Comment by lohvht** [comment]
The least breaking change for now would be to add a dummy header row manually to the generated CSV file when transposing the `flow_filename_transposed.csv` in `src/transpose.php` such that users do not need to manually tailor their scripts or worst their own data to how we accept CSVs for the moment.

This would also ensure that our current users who do use the current way that we accept CSVs do not receive a breaking change as well.

**Comment by kensoh** [comment]
@lohvht above commit enables custom csv file to be used. can be filename or relative filename or absolute filename. works for linux / macos / windows. You can validate and doing some bug-catching before closing issue.

**Comment by lohvht** [comment]
Requires a new way to indicate if transposing of the CSV is needed. My suggestion would be to enforce the normal standard data row format that is commonly used and apply transposition by default, all while keeping the specific implementation details (such as having them follow a strict filename standard) hidden from the users.

If they do not want to transpose, we could easily add another flag to not transpose as an advanced user function, such as `--no-transpose`, while the `[iteration]` count can be still appended easily (see point 3 later)

# Example and Potential Proposed Changes
Say we have a csv file `user_data.csv` that we would like to use that has the following structure:
```
Username, Email
user1, email1@example.com
user2, email2@example.com
``` 
Then the file passed in by the in the following command `tagui flow_example.tagui user_data.csv` will then transpose `user_data.csv` and generate a new csv file (say `user_data_tflow.csv` for example), which will finally be used in the `flow_example.tagui` flow that the user has determined

If  `user_data.csv` has the following form instead:
```
Username, user1, user2
Email, email1@example.com, email2@example.com
```
And the user chooses the `--no-transpose` option (`tagui flow_example.tagui user_data.csv --no-transpose`), the output file generated will have a similar filename `user_data_tflow.csv`, but with the appended `[iteration]` row:
```
[iteration],1,2
Username, user1, user2
Email, email1@example.com, email2@example.com
```

This proposed change will indeed break backward compatibility to all previous versions but here are some of the things that I think that users will ultimately benefit from the tool:
1. Explicit declaration of which csv file to use (From your commit in the custom csv datatable option)
2. Users will no longer need to worry about which file format their CSV is in, whether `_transposed.csv` or not, with the default falling on the standard use case for CSVs. However this also giving users the option not to transpose
3. All data tables benefit from having access to the iteration count, which count give users a good mechanism to check the progress of their automation run.

**Comment by kensoh** [comment]
Nice thoughts! Something definitely needs to be done to fix the awkward datatable structure which is data-focus versus the standard row per iteration.

I'll think over to see if there is a way to auto-decide whether to transpose or not. If possible, I do not want users to have to decide whether to transpose or not.

**Comment by kensoh** [comment]
Above commit auto-transpose from assumed standard .csv format to tagui internal format, this will handle custom datatables that users choose to run tagui with. for object repository, i'll chew on it separately to find a way to harmonize or separate from 'datatable'.

Nice work @lohvht on these series of csv changes! and also #184 (copying @Aussiroth) I'll assign myself out of the issue now but lemme know if anything after your sanity checks.

**Comment by kensoh** [comment]
Thank @lohvht! making the change above doesn't break backward compatibility and lets users specify a .csv file to be used, in the standard .csv datatable format. closing issue for now
