### ISSUE TITLE
Use of arrays instead of variables

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#177]
HI Ken,

I would like to use arrays to simplify my code, 
How can I use it with "enter" or "click" commands?

I tried this, but it didn't work properly:

```
https://www.google.com/

cars = ["Saab", "Volvo", "BMW"];

echo cars[1]

enter .gsfi as cars[1]
enter .gsfi as [enter]

wait 3
snap page
```
=> it googles "car[1]" term and not "Volvo"

Thanks

**Comment by adegard** [comment]
Got it I use, like this it work!

enter .gsfi as '+cars[1]+'

**Comment by kensoh** [comment]
Hi Arnaud, yep that's it! Normal programming languages default context is variables and strings are escaped with "" or ''. For TagUI steps interacting with the UI, the default context is string, so '+variable_name+' or '+array_name[]+' is used to escape string mode to denote variables.
