### ISSUE TITLE
Set up: installation step on ubuntu

### ISSUE THREAD

**Issue by jeffreynghm** [kelaberetiv/TagUI#182]
Question on how to install tagui on ubuntu(linux).
I have the following issue when following the instructions on installation: 1. download and unzip; 2. record the script on chrome; 3. run the script on tagui command line following "Set up" guide....
`
tagui [path of the script] chrome`

```
No command 'tagui' found, did you mean:
 Command 'tagua' from package 'tagua' (universe)
tagui: command not found
```
btw, once unzip - the file tagui is located at ./src/

**Comment by kensoh** [comment]
Hi @jeffreynghm where is the installation instructions link that you are using?

From the [tutorial link](https://github.com/kelaberetiv/TagUI/blob/master/src/media/RPA%20Workshop.md) need to change folder to the src folder before running tagui command.

```
cd /home/your_id/tagui/src
./tagui samples/1_yahoo
```

From the [readme link](https://github.com/kelaberetiv/TagUI#command-line), there is a section on running tagui command from anywhere by setting up symlink.

```
Tip - to run tagui from anywhere in macOS/Linux, use ln -sf /full_path/tagui/src/tagui /usr/local/bin/tagui to create symbolic link.
```

Lastly, I think Ubuntu doesn't come with PHP, you may have to `apt-get install php` to install PHP. PHP is needed to translate the human language syntax into executable JavaScript code to run the automation.

I'll close the issue for now, but do advise where is the link you are referring for installation so I can improve the docu, or if you run into any further issues installing!
