### ISSUE TITLE
CSV formatting enhancements

### ISSUE THREAD

**Issue by lohvht** [kelaberetiv/TagUI#184]
Make more improvements to saving to CSV files via helper functions to make formatting strings into CSV data easier

# Proposal
create functions similar to `present(element)` and `url()`:
1. `csv_row(array)` : Takes in an array of strings to convert into a CSV-formatted row
2. `sanitise_csv_cell(string)` : Coverts the string provided into a CSV-formatted cell data

# Example Usage
Example usage within TagUI scripts
## csv_row
```
read //XPATH_SELECTOR_1 to title
read //XPATH_SELECTOR_2 to language
read //XPATH_SELECTOR_3 to format

row_data = [title, language, format]
write csv_row(row_data) to example_file.csv
```

## sanitise_csv_cell
```
read //XPATH_SELECTOR_1 to title
formatted_title = sanitise_csv_cell(title)
echo formatted_title
```

**Comment by kensoh** [comment]
Thanks @lohvht ! used in the lunch time sharing on compiling website data, much easier and readable to save csv files, closing for now
