### ISSUE TITLE
Sikuli visual automation not working on Windows

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#187]
raising on a user's email query

**Comment by kensoh** [comment]
Had a user which Sikuli visual automation is not working, elements can't be found on screen even though you can see the image matching.

Turns out it is because the Windows display resolution setting is set to 150% magnification. By setting back to 100% magnification the visual automation works.

The significant magnification makes the image on the screen differs too much from the image captured through snipping tool, thus the error.

**Comment by naufil09** [comment]
I am facing the same problem. How to resolve this type of issue  ?

**Comment by kensoh** [comment]
Hi @naufil09 for visual automation on Windows, try setting your display resolution to 100% or the recommend zoom %.
