### ISSUE TITLE
How do we use variables in TagUI steps

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#190]
Raising from user's email query for benefit of other users

---

I have one question about the tagui "type" command as it's seems that it's only enter the hard coded text instead of reading from the variable as I am having trouble in inputting variable into the website as it's input "contain" instead of cat - 

```
https://www.google.com/
contain = "cat"
type lst-ib as contain[enter]
wait 5 seconds
```

---

**updated email from user**

it's seems that I should use '+contain+'😅

```
https://www.google.com/
contain = "cat"
type lst-ib as '+contain+'[enter]
wait 5 seconds
```

**Comment by kensoh** [comment]
**my response**

---

That's correct! Where did you find out how to use this syntax?

Thinking where I can improve the readme or samples so that this is easier to see.

PS: variables can also be use as identifiers to specify which elements to interact with

**Comment by tuxalket** [comment]
Hi,
can you please show where to find the correct syntax about the usage of variables?
Regards

**Comment by tuxalket** [comment]
I found it, 
username = "DEVELOPER"
vision type '+username+'[TAB]

**Comment by tuxalket** [comment]
username = "DEVELOPER"
type user.png as '+username+'[TAB]

I guess this should be correct?

**Comment by kensoh** [comment]
Yes that's correct, now there's an improved way to use variables with backticks `, you can do -

```
username = "DEVELOPER"
type user.png as `username`[TAB]
```

There are more examples in flow samples and this is also mentioned in readme document.

**Comment by Steve2955** [comment]
@kensoh Could you please edit your [first anwer](https://github.com/kelaberetiv/TagUI/issues/190#issue-327961022) of this issue to directly include or reference the updated backtick-syntax? Also I didn't found any mention of this in the [docs](https://tagui.readthedocs.io/en/latest/index.html). Is this intended? Using variables is quite an important basic concept in my oppinion🤔

**Comment by Steve2955** [comment]
Hi @ruthtxh, 
thank you very much for the quick reply. I already got variables working for me, but was quiet confused that a basic concept like variable usage is not mentioned in the docs (or at least I didn't find it). On my search for an answer I stumbled upon this issue which finally resolved my confusion. 

However, what I tried to express is that **this is a point where the docs need to be improved** as well as Ken's first reply to this issue as it refers to a deprecated syntax.

**Comment by ruthtxh** [comment]
Hi @Steve2955, as for when to use the backticks/how to use it for accessing variables or concatenating variables, it is quite dependent on the usage and steps involved. Most of the steps already have examples on how to access variables for that particular step.

I've put together some examples to show this, let me know if it helps and I will add it to the docs:
```
text = "hello world"
echo `text`
// output: hello world

a = "hello"
b = "world"
c = a + " " + b
echo `c`
// output: hello world

echo hello world
// output: hello world

echo `a` `b`
// output: hello world

if a equals to b
  echo same
  // output:
```

P.S. this list is not exhaustive, just some examples to show how it might differ with different usage.

**Comment by kensoh** [comment]
Thanks @Steve2955 for suggesting an update. Indeed it is confusing, I have updated the post above. Thanks too @ruthtxh!

**Comment by ruthtxh** [comment]
Hi @Steve2955 @kensoh 
I have updated the docs [here](https://tagui.readthedocs.io/en/latest/reference.html?#using-variables), hope its clearer. Cheers.

**Comment by kensoh** [comment]
Hi @ruthtxh your new guide looks great! There is some formatting issue, the backtick needs to be somehow escaped otherwise render as italic instead of backticks. And there is extra indentation in the output block -

![Screenshot 2022-06-03 at 2 54 48 AM](https://user-images.githubusercontent.com/10379601/171771756-38f962a3-af14-4d11-8355-20904195e971.png)

**Comment by ruthtxh** [comment]
@kensoh edited, thanks!

**Comment by kensoh** [comment]
Maybe still need to iterate but i'm not sure what's the right syntax (now it is a different format but no backticks too) -

![Screenshot 2022-06-03 at 3 19 08 AM](https://user-images.githubusercontent.com/10379601/171774035-a97340de-767a-4ddf-9fff-4554a77acb55.png)

**Comment by kensoh** [comment]
Oh the other docs are just referring to variables and use above formatting syntax.

But in this case, it is to demostrate that backticks are required, thus to show this way will be confusing for users when they are asked to surround the variable name with backticks but it is shown as just the variable name without the ``

**Comment by kensoh** [comment]
Still need iteration (see below), though I'm not sure the syntax. I did a quick google search but didn't find the solution.

![Screenshot 2022-06-03 at 5 46 46 PM](https://user-images.githubusercontent.com/10379601/171909496-b931e670-557a-4cc7-b5aa-e8a7f98204ed.png)
