### ISSUE TITLE
snap step returning black or blank images on Windows

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#191]

**Comment by shoeper** [comment]
I also head a white image for one page. The snap was done on linux.

**Comment by kensoh** [comment]
Fix usable on cutting edge release - https://github.com/kelaberetiv/TagUI/archive/master.zip

**Comment by kensoh** [comment]
@shoeper I see.. Oh this issue is a new bug that appeared for Windows.

Linux and macOS should not be impacted by the code update.

**Comment by kensoh** [comment]
I think there is some alignment issue on Windows depending on the screen resolution. Closing the issue for now until further clues of replication. Potentially related to Windows resolution auto-scaling and perhaps the width of the web-browser scroll bar.

**Comment by kensoh** [comment]
Issue for Windows snap image misalignment found. Solution, change Windows display setting to 100% scaling instead of 125%, 200%, 225% etc. Because of downsampling, the clipping of images will be a little off. Running at 100% will capture images of elements correctly.
