### ISSUE TITLE
How to workaround applications or websites that required 2FA (2-factor-authentication)?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#197]
raising on user's email

---

Tag UI is a wonderful tool. Really like the presentation today. I have question, how to login to website, that requires 2FA. Is there solution or work around for this. The 2FA code will be received in outlook mail

**Comment by kensoh** [comment]
Thanks for your kind words :)

If the 2FA is mobile sms, you can use some mobile apps such as mysms to create a text file of the message received. be sure to place that file on a google drive sync folder on the phone, so that the file can be synced to your computer running the automation. From there you can keep scanning the file on the computer during login to check for the 2FA pin.

If the 2FA is a hardware token, it can be solved by building a robotic actuator and camera sensor. It is technically doable, but it will be expensive in terms of time to get it working for that particular hardware token.

**Comment by raymondlooyc** [comment]
Hi @kensoh 

Thank you for your help. We have done 2FA in tagui with Auto Forward SMS mobile app to auto send SMS to Gmail and tagui will capture OTP from the email content. However, the auto forward SMS seem to stop working now. Do you have suggestions on other mobile app which can auto forward SMS to email so 2FA can be process in tagui?

**Comment by kensoh** [comment]
I see, I'm not sure what other apps can do that. There should be something on appstore you can find to do that, if you do, please share here!

**Comment by raymondlooyc** [comment]
Thank you for reply. we will share here once found the app which do the SMS forward to email for 2FA with tagui

**Comment by kensoh** [comment]
Thanks Raymond, i will also post here if i hear from any other users if they have found a solution.

**Comment by raymondlooyc** [comment]
Hi @kensoh 

we have found the android app to "SMS to mail/phone - auto redirect" to perform SMS forward to email for tagui to perform 2FA verification. And, it working good so far.

**Comment by kensoh** [comment]
hi Raymond, thanks for sharing this gem you found! - https://play.google.com/store/apps/details?id=com.gawk.smsforwarder
