### ISSUE TITLE
How to Representation of Tagui scripts Results finally

### ISSUE THREAD

**Issue by venkatesh17** [kelaberetiv/TagUI#207]
Hi Ken, How to Representation of Tagui scripts Results finally, suppose i execute 4 scripts  in those two are successfully executing and reaming two give error means functionality not working correctly. finally how to display the two scripts pass , two scripts fail  in graphically representation

**Comment by venkatesh17** [comment]
![result](https://user-images.githubusercontent.com/26598091/41098697-e7d10c94-6a79-11e8-9978-37a264bd2214.PNG)

**Comment by kensoh** [comment]
Hi @venkatesh17 at the moment there is no graphical representation of results. If you mean for testing, you can use the check step, and run tagui with test option. There will be an XML file generated which you can integrate with CI / CD tools for test automation and reporting.

Having a dashboard and reporting features is part of TagUI development pipeline, details here - https://github.com/kelaberetiv/TagUI/issues/83

I'm closing the issue for now but please feel free to comment and give your recommendations or thoughts on this, thanks!
