### ISSUE TITLE
Overwriting packaged installation with cutting edge file breaks TagUI (casperjs not found)

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#214]
On some computers, the default behavior when overwriting an existing folder is actually deleting folders which are not present in the source but present in the target folder. Thus, overwriting a local packaged installation that works, with the cutting edge version, may break the program.

**Comment by kensoh** [comment]
above commit changes wording to below so that folders in existing src folder won't get deleted.

---

Tip - to try cutting edge version with the latest features, download master.zip to overwrite an existing packaged installation (be sure to manually select and move the folders & files inside master.zip's tagui/src folder to replace your existing tagui/src folder, otherwise some OSes will delete existing target folders that are missing from source folder)

**Comment by shoeper** [comment]
Sorry for asking, but which OS / Software does delete folders when unpacking an archive into an existing folder?

**Comment by kensoh** [comment]
I can't really replicate, but I've encountered this before on Windows 10. Just today, my colleagues encountered this on their macOS, which is kinda strange.....

**Comment by kensoh** [comment]
Oh.. I don't want to automatically create packaged installation that have cutting edge code.

Will prefer a gap of a couple of months so that pro users can test out the new features first by choosing to manually overwrite their local installation. Then i publish that into a new packaged release.
