### ISSUE TITLE
For loop bugfix - explore enabling break and continue within for loops

### ISSUE THREAD

**Issue by lohvht** [kelaberetiv/TagUI#216]
Attempt to fix the loss of `continue` and `break` for `for`-loops in TagUI scripts due to the IIFE pattern.

# Proposed fix
upon translating from TagUI script to javascript, replace `continue`s and `break`s into returning corresponding flags.

then check the flag and carry out `break`/`continue` accordingly

**Comment by kensoh** [comment]
Made a commit in for_loop_break_continue branch - https://github.com/kelaberetiv/TagUI/commit/8700c0c0f41517357e2a6fa004a63b761cbf3041

samples/loop_demo can't work. in generated loop_demo.js, when for_loop_signal is set, the moment after // end of JS code line if put `casper.echo(for_loop_signal);` it shows blank.

```js
casper.then(function() { // start of JS code
for_loop_signal = '[BREAK_SIGNAL]'; return;
}); // end of JS code
```

problem is variables set with casper.then() blocks remains in casper context. ie the moment exit IIFE pattern, for_loop_signal variable remains blanks and the code to break or continue does not trigger.

```js
})(n); // end of IIFE pattern
if (for_loop_signal == '[BREAK_SIGNAL]') {for_loop_signal = ''; break;}
else if (for_loop_signal == '[CONTINUE_SIGNAL]') {for_loop_signal = ''; continue;}}
});
```

We can look into this together next week...

**Comment by kensoh** [comment]
Experimental implementation using file IO doesn't work as well - https://github.com/kelaberetiv/TagUI/commit/6cbf1f5481f9740026c61aa10636d9e085a20c34

**Comment by Aussiroth** [comment]
http://docs.casperjs.org/en/latest/modules/casper.html#thenbypassif

**Comment by kensoh** [comment]
above commit adds stricter conditions to give correct output. turns out the stack also contains the terminating marker, thus the outer loop for the n for loop will have the market for k for loop and results in false-positive match. below stricter condition to check for real match -

```js
if (casper.steps[s].toString() == ("function () {for_loop_signal = '[BREAK_SIGNAL]["+teleport_marker+"]';}"))
```

```
1
2
3
4
5
6
80
81
82
83
7
8
9
10
cde 1
cde 2
cde 3
cde 4
cde 5
abc 1
abc 2
abc 3
abc 4
abc 5
```

**Comment by kensoh** [comment]
looks ok for repeated use of for loop variables. would have thought will have issues as the markers are similar, but below works, haven't figure out why.

```
for n from 1 to 10
{       
        echo n
        if n equals to 6
        {       
                for k from 80 to 85
                {       
                        echo k
                        if k equals to 83
                        {       
                                break;
                        }
                }
        }
}

for cde from 1 to 5
{
        echo "cde " + cde
}

for abc from 1 to 5
{
        echo "abc " + abc
}

for n from 30 to 35
{
        echo n
}

for k from 20 to 25
{
        echo k
}
```

```
1
2
3
4
5
6
80
81
82
83
7
8
9
10
cde 1
cde 2
cde 3
cde 4
cde 5
abc 1
abc 2
abc 3
abc 4
abc 5
30
31
32
33
34
35
20
21
22
23
24
25
```

**Comment by kensoh** [comment]
Adding on, it works because the later steps in stack are not created yet, so later blocks of for loops with similar variable names wont trigger false-positive if a search is done from the back.

**Comment by kensoh** [comment]
I'll brush up the code and add continue so that you guys can stress test... continue's implementation is probably adding a marker near the start of the loop and searching from forward direction instead of from the back.

**Comment by kensoh** [comment]
merged to cutting edge release, now prepping to release v4.0
