### ISSUE TITLE
Tag UI - calling script using .bat file and integration with knime

### ISSUE THREAD

**Issue by SofyanShaikh** [kelaberetiv/TagUI#219]
Hi , 
Loved your work. Very much a beginner and trying to learn from all sources possible.(if there is any document that could help please provide)
I had a question can tagui script be called using bat file? I guess it should be easy since we already use command prompt.
Also as knime is open source harmonisation tool i have worked on can tagui and knime be integrated?

**Comment by kensoh** [comment]
Hi @SofyanShaikh thanks for your questions -

1. from main readme page there is a tutorial link which is a good guide - https://github.com/kelaberetiv/TagUI/blob/master/src/media/RPA%20Workshop.md

2. From [command line section](https://github.com/kelaberetiv/TagUI#command-line) there is an example of calling tagui from .bat file

```
@echo off
c:
cd c:\folder
tagui filename quiet speed chrome
```

3. TagUI can call APIs and has run step to execute command line tools. If knime works with Python, then there is py step to run python commands as well.

I'm closing the issue for now but feel free to comment or ask any questions!
