### ISSUE TITLE
Getting live visual automation to work

### ISSUE THREAD

**Issue by roverkim** [kelaberetiv/TagUI#225]
Hi there, I am unable to get live visual automation (e.g. viewing the movements of the mouse interacting with chrome) to work on windows when I run 'tagui 1_yahoo chrome' although the process runs successfully on the terminal. I have installed Sikuli but I still can't seem to get visual automation to work. Thank you very much for your contribution and help.

**Comment by Aussiroth** [comment]
Hi,
The 1_yahoo sample does not use steps that make use of the Sikuli visual automation, so the automation runs by scripting in the browser without performing a live visual automation.
This comment gives some good examples for using the visual automation step - https://github.com/kelaberetiv/TagUI/issues/113#issuecomment-378194245

Please let us know if you have any further issues or queries!

**Comment by roverkim** [comment]
Hi Alvin, 

Thank you for responding. I managed to get the example to work. One more question, is there anyway I can run the tagui command in bash instead of using the command prompt on windows? Thank you.

**Comment by lohvht** [comment]
Hi Rover,

Bash running support for TagUI right now is not supported unfortunately. You however run TagUI on Powershell as well and it should work fine.

**Comment by roverkim** [comment]
Hi Victor, 

Thank you for your response. Powershell sounds good. Thank you.
