### ISSUE TITLE
Problem when passing in large string as input

### ISSUE THREAD

**Issue by HenriPro** [kelaberetiv/TagUI#231]
I am trying to automate a task where I have many options. I am passing these options in as a string:
```
./tagui flow.tagui  '{"topSelector":["Burrito"],"fillings":["Chicken","Barbacoa"],"rices":["White Rice","Brown Rice"]}'
 ```

however when I do 
```
echo p1
order = JSON.parse(p1)
```

I get
```
{"topSelector":["Burrito"],"fillings":["Chicken","Barbacoa"],"rices":["White
SyntaxError: JSON Parse error: Unterminated string    
```
shorter strings  appear to work fine with JSON.parse()

**Comment by HenriPro** [comment]
Closing, as I realized that this is cutting off at the space, I will just escape the spaces or replace them'

**Comment by kensoh** [comment]
Hi @HenriPro cool use scenario :) Adding on, another way that can be used to do this is save the large string or block of text into a file, then use the load step to read from the file into a variable.

**Comment by HenriPro** [comment]
Thanks awesome work!
