### ISSUE TITLE
May I know if it is possible to use TagUI to automate sending email reminders? 

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#232]
user query

**Comment by kensoh** [comment]
Normally we use RPA is there is no other way to automate something. Because RPA takes efforts to write the automation and to keep the scripts updated, and slower than other ways of automation that is already there by design. For example, if CA Trust is using MailChimp to manage their clients' contacts, it will be easier to use the functions already in MailChimp to automate sending the email reminders.

Otherwise, if no mail / marketing app is used and only Outlook desktop app is used, then consider using RPA. TagUI can use visual automation to interact with the UI (user-interface) elements on the screen. You can use the Windows snipping tool to capture small image snapshots of those elements and save them. And you can use steps such as click or type to interact with those elements.

An example code that automates Outlook - 
https://github.com/kelaberetiv/TagUI/issues/113#issuecomment-378194245

More details of the visual automation here -
https://github.com/kelaberetiv/TagUI#visual-automation

More details of all the TagUI steps here -
https://github.com/kelaberetiv/TagUI#steps-description

If you are dealing with a lot of clients list in a .csv file, consider using datatables to do at scale -
https://github.com/kelaberetiv/TagUI#datatables

An important point to note is consider saving as draft instead of actually sending out the email. After saving 500 drafts for 500 clients, then someone can manually scan through before sending, just in case there is some error with the automation and typo.

**Comment by kensoh** [comment]
It is also possible to send emails via API. If you have a mail server, you can consider using something like Tmail to accept email messages through API and then use api step to send the email - https://github.com/kelaberetiv/TagUI#api

**Comment by adegard** [comment]
Hi @Ken, I share also a SMS Rest API on the same model but with SMS Gateway. Here you will find program for Skebby Gateway (Italian): https://github.com/adegard/SMS-Marketing 
I use it to send SMS answer to jobs ads on Subito.it or other website using Tagui crawler

**Comment by kensoh** [comment]
Thanks @adegard !  I added a note on this to the API section of readme together with example on email-sending - https://github.com/kelaberetiv/TagUI#api

PS - my GitHub id is @kensoh , if use `@ken` will alert another user. that user is a famous person but he does not seem to use github.

**Comment by sangasangasanga** [comment]
Hi ken. I am using tagUI to retrieve info from datatable and enter it as the input in the website e.g. login id. I did look at this website https://github.com/kelaberetiv/TagUI#datatables. However, it is still not clear exactly how i can do about. My code write now is this:
enter '5b5690e6cd4499000f0b879c' as +name+[enter]

**Comment by kensoh** [comment]
Hi @sangasangasanga I'll reply in a new thread here - #247
