### ISSUE TITLE
How to invoke TagUI automation scripts from Windows task scheduler

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#234]
user query

---

For the scheduling of an automation flow, you mentioned to use task scheduler. However, I am having troubles creating the task as I can’t save the codes used to run in the command prompt. Hence, is there any way to run the command prompt at a certain time using task scheduler so that it can send emails out at a certain timing automatically?

**Comment by kensoh** [comment]
Check this - https://github.com/kelaberetiv/TagUI#command-line

Click on the line 'Click to show how to run TagUI scripts by double-clicking as desktop icons'

It shows an example of a .bat file which you can design the commands to be used in the command prompt. After creating the file to run the scripts you want with the automation filename and options, you can use the task scheduler to run the .bat file.

**Comment by adegard** [comment]
Hi Ken, 
I'd like to share my experience on this topic! Personaly I found Z-cron (https://z-cron.com/) which is more easy to use and powerful than windows scheduler.
For each tagui file I create .bat file like this:
`@echo off

tagui filename

pause
`

**Comment by kensoh** [comment]
Thanks @adegard ! 👍 @Aussiroth pls help to try out z-cron to compare with windows task scheduler, then recommend if we should put it as part of official documentation in scheduling section. I'll reopen the issue for now.

**Comment by kensoh** [comment]
Thanks @adegard ! Added to readme and tutorial 😄 -

https://github.com/kelaberetiv/TagUI#by-scheduling

**Comment by Shivang310** [comment]
hi @kensoh,
I have just start using tagui for a project for automation I just what to ask is it possible to do cron job for desktop automation script, and if it is can you please tell me were to find resources  to learn it please.

**Comment by ruthtxh** [comment]
Hi @Shivang310 you can find out more about scheduling over here https://tagui.readthedocs.io/en/latest/faq.html?#running-flows-on-a-fixed-schedule

**Comment by Shivang310** [comment]
@ruthtxh  thank you, can you please also tell me if there is any problem using task scheduler for visual Automation actually I have used  VA for desktop Application like Mongodb and filezilla and in that i have used VA mostly and I have deployed it as well but I have some doubts if it will work perfectly if I use scheduler to automate it 100%.

**Comment by ruthtxh** [comment]
Hi @Shivang310 since visual automation requires the image to be displayed on the screen to be matched, you will have to ensure that with scheduler the screen display remains turned on at all times for it to work.
