### ISSUE TITLE
Why does text in echo / dump / write / check steps require quotes?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#242]
This issue adds on to #241 where \`variable\` can be used instead of '+variable+' to denote variables where text is expected.

**Comment by kensoh** [comment]
The various TagUI steps by default expect context to be text instead of variables, to let scripts be more human-language-like. However, for some steps (echo, dump, write, check), the context by default is variable. This is because these steps are normally used for dealing with variables.

To make the default context text would mean additional effort when writing scripts using these steps. But to make default context variable, would mean these steps behave differently from most other TagUI steps. To review whether it makes sense to adjust the default context of these steps to be like the other TagUI steps, and whether it can be done with backward compatibility.

**current way**
```
echo 'Name of user: ' name
dump results to result.txt
write output to out.txt
```

**for evaluation**
```
echo Name of user: `name`
dump `results` to result.txt
write `output` to out.txt
```

**Comment by kensoh** [comment]
**thoughts after reviewing**

For dump and write steps, it is easier to simply provide variable name instead of having to put ``.

For echo step, there isn't a way to implement this without breaking backward compatibility. Because something simple like echo name cannot be automatically parsed to determine if it is referring to a variable or a text and then handle it accordingly.

In theory can try and catch for error, but complication comes in when trying to echo text and repository / datatable. The new complexity will affect reliability in exchange for a more streamline syntax when scripting. Decision made for now is to drop this move that will break backward compatibility.

**Comment by Hassan-Ali123** [comment]
Hey @kensoh! Nice to see you! I downloaded the latest version of TagUI (6.0.0). But when I print a text using a variable using the latest syntax it's giving me error. 
<img width="172" alt="EchoError" src="https://user-images.githubusercontent.com/38554003/80957221-30f7dc00-8e1c-11ea-90a0-077ccbe4d888.PNG">. Please guide where am I doing mistake!

**Comment by Hassan-Ali123** [comment]
The latest syntax I am using is: echo message-to-print `variable-name`. This is the generic syntax I am using

**Comment by Hassan-Ali123** [comment]
On variable-name I am using backtick opertors to enclose it like `variable-name`

**Comment by kensoh** [comment]
Hi @Hassan-Ali123 yes what you write is correct. Can you share what is the minimum simple script you have that can replicate the problem? Make sure that you are running TagUI v6. If you type `tagui` without any parameters it should show version as v6. In case somehow the old version is running.

For example, below sample script 

```
a = '2'
echo 1 `a` 3
```

Will give the following run output on my v6
```
1 2 3
```

**Comment by Hassan-Ali123** [comment]
So you mean the message to print should be written in double quotes or backtick characters??

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kensoh** [comment]
For echo step, message no need quotes in v6 and variables need backticks in v6 -

See more info - https://github.com/kelaberetiv/TagUI#echo-dump-write-steps

**Comment by Hassan-Ali123** [comment]
Thanks so much

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
