### ISSUE TITLE
Uninstalling tagUI-writer / TagUI Writer

### ISSUE THREAD

**Issue by RohitY** [kelaberetiv/TagUI#243]
I have used TAGUI WRITER & SCREENSHOTER  created by @adegard . 
Now I want to uninstall this App. There is no option to uninstall tagui writer. 
And every time i do ctrl+left click (on desktop,browser or editor) menu for tagui pops up.

Please let me know how can I uninstall tagui writer.

Thanks

**Comment by adegard** [comment]
Hi @RohitY 
Good question, thanks:
no need of uninstaller, just delete the file (close it before in windows tray : right click on icon /"Exit" )
I had this comment in Github Repo.

**Comment by kensoh** [comment]
Thanks @adegard ! Closing the issue :smile:

**Comment by kensoh** [comment]
Section in TagUI readme describing TagUI Writer from @adegard -
https://github.com/kelaberetiv/TagUI#tagui-writer--screenshoter

Direct URL to TagUI Writer's GitHub repository from @adegard -
https://github.com/adegard/tagui_scripts
