### ISSUE TITLE
Paste function as substitue for type

### ISSUE THREAD

**Issue by RohitY** [kelaberetiv/TagUI#245]
Hi,
Is there a possibility of putting entire text in one go instead of using "type" as inputing it character by character. Let me explain:
type element as <really_long_query>
if <really_long_query> is long enough and doing multiple iteration of it on a web page consumes considerable time. 4-5 mins in my case. 
So is there a way in which i can put a big text in one go inside element instead of using type command and it gets typed 1 character at a time.

Thanks
Rohit

**Comment by kensoh** [comment]
TagUI aims to replicate user actions when typing the text character by character. To set the value directly, you can use dom step and changing the .value property of a web element directly in the HTML dom. See below example.

```
https://ca.yahoo.com
dom_json = 'long string of text'
dom document.getElementById('uh-search-box').value = dom_json
wait
snap page
```

There are more notes on using dom step in the pro steps section here - 
https://github.com/kelaberetiv/TagUI#steps-description

and the sample 9_misc -
https://github.com/kelaberetiv/TagUI/blob/master/src/samples/9_misc
