### ISSUE TITLE
How do I use datatables with TagUI to automate using various data sets?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#247]
from @sangasangasanga at #232 

---

Hi @kensoh. I am using tagUI to retrieve info from datatable and enter it as the input in the website e.g. login id. I did look at this website https://github.com/kelaberetiv/TagUI#datatables. However, it is still not clear exactly how i can do about. My code write now is this:
enter '5b5690e6cd4499000f0b879c' as +name+[enter]

**Comment by sangasangasanga** [comment]
@kensoh Yup i tried the 6C_datatable example

**Comment by sangasangasanga** [comment]
Below is my code and I am just using your user_data.csv 
https://form.sg/forms/mnd/5b568f8acd4499000f0b8794
click .start-page-btn.ng-scope .brown-font
enter '5b5690e6cd4499000f0b879c' as `GITHUB_ID`[enter]
enter '5b569134cd4499000f0b87a2' as `USER_EMAIL`[enter]
click btn-custom btn-large form-submit-btn brown-bg-dark brown-border-dark
wait 2.5
click end-page-btn-link

This is the error I get:
phantomjs://code/form.js:1333 in injectJs
  phantomjs://code/bootstrap.js:456
SyntaxError: At least one digit must occur after a decimal point

**Comment by kensoh** [comment]
Hi @sangasangasanga try this -

`tagui demo.txt chrome user_data.csv`

if you don't want chrome to restarted for each new record use

`tagui demo.txt chrome speed user_data.csv`

**demo.txt**
```
https://form.sg/forms/mnd/5b568f8acd4499000f0b8794
click .start-page-btn.ng-scope .brown-font
enter 5b5690e6cd4499000f0b879c as `GITHUB_ID`[enter]
enter 5b569134cd4499000f0b87a2 as `USER_EMAIL`[enter]
click btn-custom btn-large form-submit-btn brown-bg-dark brown-border-dark
wait 2.5
click end-page-btn-link
```

**output**
```
START - automation started - Tue Jul 24 2018 16:48:00 GMT+0800 (+08)
https://form.sg/forms/mnd/5b568f8acd4499000f0b8794 - FormSG

click .start-page-btn.ng-scope .brown-font
enter 5b5690e6cd4499000f0b879c as ironman[enter]
enter 5b569134cd4499000f0b87a2 as tony@stark.org[enter]
click btn-custom btn-large form-submit-btn brown-bg-dark brown-border-dark
wait 2.5
click end-page-btn-link

https://form.sg/#!/forms/mnd/5b568f8acd4499000f0b8794 - FormSG
FINISH - automation finished - 16.4s
```

**Comment by sangasangasanga** [comment]
@kensoh Thank you it works now. But may I know what did u edit on my codes? because it looks similar but it wasn't working before

**Comment by Hassan-Ali123** [comment]
Hi @kensoh! plz guide how can I scrape an html table spanning multiple pages using tagui?

**Comment by kensoh** [comment]
Replied here - https://github.com/kelaberetiv/TagUI/issues/415#issuecomment-632190344
