### ISSUE TITLE
Is there a way to check if a file exist before to load content?

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#248]
Hi @kensoh 
I wrote a little snippets to check if a entry exist in a file before to append new entries, but I also need before to check if the file exit. 
How can I do that to complete the following code?

```
//email to check/append
email="pinco@gmail.com";

//path of file to create/use
path="/tmp/emails.csv";


//*******CHECK HERE IF FILE EXIST*********//
load '+path+' to database_emails
echo 'database_emails: '+database_emails


if (database_emails.indexOf(email)>-1)
{
echo 'email already exist in database'
}
else
{
echo 'email added in database'
write email to '+path+'
}
```
I didn't found it in tuto or closed issues...
Thanks

**Comment by kensoh** [comment]
Hi @adegard following block of code can be used. As TagUI underlying JS engine is PhantomJS, the [file system module](http://phantomjs.org/api/fs/method/exists.html) that comes with PhantomJS can be used.

```js
fs = require('fs');
target_file = '/tmp/emails.csv';

if (!fs.exists(target_file))
fs.touch(target_file);
```

Alternatively, you can make use of TagUI user-defined functions. By creating a file tagui_local.js and put in same folder as the script, or creating a file tagui_global.js and putting in tagui\src folder, users can define their own functions to be used. [More on this here under helper functions](https://github.com/kelaberetiv/TagUI#helper-functions).

**contents of tagui_local.js or tagui_global.js**
```js
function touch(full_path) {
        fs = require('fs');
        if (!fs.exists(full_path))
        fs.touch(full_path);
}
```

**to use touch() function in your tagui script**
```js
touch('/tmp/emails.csv');
```

**Comment by adegard** [comment]
Great @kensoh 
It works perfectly! I use it as local database (to avoid repeat the same action to the same item)

Good also your user-defined functions creation system!

**Comment by kensoh** [comment]
Also adding on, below egs evaluate to a boolean true or false that can be used in conditions directly -

```js
file_exists = require('fs').exists('/tmp/test.txt')
...
echo require('fs').exists('/tmp/test.txt')
```
