### ISSUE TITLE
How to compare each rows of 2 datatables in TagUI

### ISSUE THREAD

**Issue by sangasangasanga** [kelaberetiv/TagUI#249]
hey @kensoh 

Currently, I am trying to do a task that will compare each rows of 2 datatables e.g. phone directory (original version) and a small chunk of phone directory (the record version). 

But Im not sure how to call 2 datatables at the same time. 

I would like compare each row of the 2 datatables and if it is true then enter it as a variable. If the 2 rows data doesn't match. then enter it to another csv.file.

I did tried looking for solutions in your closed queries  but i couldn't find any.

**Comment by kensoh** [comment]
Hi @sangasangasanga I'll recommend trying to do this in Excel first (using functions such as vlookup), and generate the datatable containing only the data which you want TagUI to process.

It is possible to do something like what you described inside TagUI, but will need programming knowledge. For example loading a datatable into variable using load step, then use the JavaScript split function to convert the datatable into an array in memory, and finally using nested for loops to scan through and compare the databases in memory. This way is possible but someone must be willing to learn JavaScript from websites such as https://www.w3schools.com/jS/default.asp in order to go by this approach. Otherwise, using Excel functions to do the data preparation may be the easier way.

**below is the programming way, for the file tagui\src\samples\6_datatables\user_data.csv**
```
load user_data.csv to datatable
table1 = datatable.split('\n')

// processing table on a row level
for n from 0 to table1.length-1
{
        echo table1[n]
}

// processing table on a cell level
for n from 0 to table1.length-1
{
        row = table1[n].split(',')
        for column from 0 to row.length-1
        {
                echo row[column]
        }
}
```

**below is the output from above script**
```
START - automation started - Wed Jul 25 2018 10:01:53 GMT+0800 (+08)

load user_data.csv to datatable
#,GITHUB_ID,USER_EMAIL
1,ironman,tony@stark.org
2,batman,bruce@wayne.org
3,superman,clarke@kent.org
#
GITHUB_ID
USER_EMAIL
1
ironman
tony@stark.org
2
batman
bruce@wayne.org
3
superman
clarke@kent.org

FINISH - automation finished - 1.6s
```

**Comment by sangasangasanga** [comment]
@kensoh thank you for the above and i do know javascript. 

However (referred to this https://www.w3schools.com/js/js_if_else.asp), How can i compare the output of each row from the two datatables. My if-else statement is completely ignored.

`//first csv file
load user_data.csv to datatable
table1 = datatable.split('\n')

// processing table on a row level
for n from 0 to table1.length-1
{
       // echo table1[n]
}

// processing table on a cell level
for n from 0 to table1.length-1
{
        row = table1[n].split(',')
        for column from 0 to row.length-1
        {
             //  echo row[column]
        }
}
//second csv file
load user_data1.csv to datatable1
table2 = datatable1.split('\n')

// processing table on a row level
for n from 0 to table2.length-1
{
      //  echo table2[n]
}

// processing table on a cell level
for n from 0 to table2.length-1
{
        row1 = table2[n].split(',')
        for column from 0 to row.length-1
        {
                echo row1[column]
        }
}

//comparison
if (row[column] = row1[column])
{
  echo 'ok'
}
else
{
  echo 'not ok'
}`

**Comment by kensoh** [comment]
Hi @sangasangasanga I think it is likely because the condition you should use double equal sign == to do comparison and conditions. Single = sign is to do variable assignment and will not work correctly for checking conditions in if statement. Try below -

```js
if (row[column] == row1[column])
```

**Comment by sangasangasanga** [comment]
@kensoh oops i oversaw that. Even though when i tried this code as below. Firstly, it only echoes once for one row but there are 3 rows. I try to echo row[column] but the output says 'undefined'. Secondly, there is a little difference between one of the rows but it is not showing.
//comparison
if (row[column] == row1[column])
{
 echo row[column]
 echo row1[column]
  echo 'ok'
}
else
echo 'not ok'

**Comment by kensoh** [comment]
Hi @sangasangasanga oh.. Your code is wrong. Your if condition is outside of the for loop, so it will only run once. If the number of rows is the same for both files, you can do a for loop and put your if condition within the for loop.

Something like below compares the whole rows. You can read through the W3 School JavaScript tutorials to understand more on programming, because it is going to be very hard to do advance business logic without learning and be familiar with programming language concepts such as loops and conditions.

https://www.w3schools.com/js/default.asp

```
for n from 0 to table1.length-1
{
        if (table1[n] == table2[n])
        {
                echo 'ok'
        }
        else
        {
                echo 'not ok'
        }

}
```

**Comment by sangasangasanga** [comment]
@kensoh Thank you so much for your help and suggestion. 

Aside from that, how to specify which datatable to get the variable from? Since I am comparing two datatables, after the if condition, it uses the variables in both datatables one by one.

`for n from 1 to table1.length-1
{  
        if (table1[n] == table2[n])
        {
                echo 'ok'
                https://form.sg/forms/mnd/5b568f8acd4499000f0b8794
                click .start-page-btn.ng-scope .brown-font
                enter 5b5690e6cd4499000f0b879c as `GITHUB_ID`[enter]
                enter 5b569134cd4499000f0b87a2 as `USER_EMAIL`[enter]
                click btn-custom btn-large form-submit-btn brown-bg-dark brown-border-dark
                wait 2.5
                click end-page-btn-link
                wait 3.0
        }
        else
        {
                echo 'not ok'
                dump table2[n] to error.csv
        }

}`

**Comment by sangasangasanga** [comment]
@kensoh Thank you so much for your help and suggestion.

Aside from that,  I am comparing 2 datatables, if  both entries are the same at both, I want to enter the entry from table2 as the variable. However, variables from both datatables are taken, making the if loop to repeat twice.  And when the dump the column when if condition is wrong, it keeps overwriting the data.

//first csv file
load user_data.csv to datatable
table1 = datatable.split('\n')


// processing table on a row level
for n from 0 to table1.length-1

{

  // echo table1[n]

}


// processing table on a cell level

for n from 0 to table1.length-1
{
row = table1[n].split(',')

for column from 0 to row.length-1

{

  // echo row[column]

}

}

//second csv file

load user_data1.csv to datatable1
table2 = datatable1.split('\n')


// processing table on a row level

for n from 0 to table2.length-1

{

  // echo table2[n]

}


// processing table on a cell level

for n from 0 to table2.length-1

{

  row1 = table2[n].split(',')

  for column from 0 to row.length-1

{

  echo row1[column]

}

}

break


//comparison

for n from 1 to table1.length-1

{
              
  if (table1[n] == table2[n])
       
 {
               
  echo 'ok'
       
  https://form.sg/forms/mnd/5b568f8acd4499000f0b8794
            
  click .start-page-btn.ng-scope .brown-font
             
  enter 5b5690e6cd4499000f0b879c as `GITHUB_ID`[enter]
     
  enter 5b569134cd4499000f0b87a2 as `USER_EMAIL`[enter]
    
  click btn-custom btn-large form-submit-btn brown-bg-dark brown-border-dark
      
  wait 2.5
        
  click end-page-btn-link
              
  wait 3.0
       
 }
      
  else
       
 {
        
    echo 'not ok'
            
    dump table2[n] to error.csv
       
 }


}

**Comment by kensoh** [comment]
You miss out the documentation, use write step to append text -

https://github.com/kelaberetiv/TagUI#steps-description

**Comment by kensoh** [comment]
You can use write step to append text - https://github.com/kelaberetiv/TagUI#steps-description
