### ISSUE TITLE
Calling TagUI from a NodeJS child process

### ISSUE THREAD

**Issue by lyzs90** [kelaberetiv/TagUI#252]
I'm trying to call TagUI from within a subprocess using the 1_yahoo example script:

Eg:
```javascript
  const { spawn } = require('child_process');
  const process = spawn('node_modules/tagui/src/tagui', [
    '1_yahoo'
  ]);

  process.stdout.on('data', data => {
    console.log(`data: ${data}`);
  });

  process.stderr.on('data', data => {
    console.log(`error: ${data}`);
  });

  process.on('close', code => {
    console.log(`child process exited with code ${code}`);
  });
```

I can see the js, log and raw files getting created. However, the script terminates shortly after without launching casper/phantom.

Anyone know a workaround for this? Cheers!

**Comment by kensoh** [comment]
Hey Shem, cool to see you integrating with NodeJS :)

I haven't tried something like that but a TagUI user @ramanathanMuthuraman does that to automate monthly timesheet filling. He uses `node-cmd`, perhaps you can try if that works for you.

Here's the repo / script he created - https://github.com/ramanathanMuthuraman/web-automation/blob/master/index.js

**Comment by lyzs90** [comment]
sure ill give it a shot and let u know how it goes

**Comment by lyzs90** [comment]
i tried using `node-cmd`, no luck 

```javascript
await cmd.run(`node_modules/tagui/src/tagui 1_yahoo chrome`);
```

**Comment by kensoh** [comment]
You can try his implementation -

https://github.com/ramanathanMuthuraman/web-automation/blob/36c8db3cebab8d3776b2fc629981d6199278879f/index.js#L56

He probably also installed directly using TagUI packaged installation - https://github.com/kelaberetiv/TagUI#packaged-installation

And then adding the tagui command to path by doing a symbolic link (section 'Click to show info on automation log files, and how to run tagui from any directory') - https://github.com/kelaberetiv/TagUI#to-use

**Comment by kensoh** [comment]
You can try his implementation or perhaps share your error message or logs and check with @ramanathanMuthuraman if he encounters that for his implementation -

https://github.com/ramanathanMuthuraman/web-automation/blob/36c8db3cebab8d3776b2fc629981d6199278879f/index.js#L56

**Comment by lyzs90** [comment]
yep im doing that.. the problem is there are no error messages 😅

**Comment by kensoh** [comment]
See if Rama or other Node.js experts can advise further on running from Node command line, running from command line after doing `npm install tagui` works. You can also clone and run his repo to see if it works on your env, if it works then compare why your implementation not working.

```
[~/api/archive/tmp]# node_modules/tagui/src/tagui node_modules/tagui/src/samples/1_yahoo
START - automation started - Fri Jul 27 2018 05:30:57 GMT+0000 (UTC)
https://ca.yahoo.com - Yahoo

NOTE - this sample may not work for EU users due to website changes for GDPR
EU users may have to modify script to first click on announcement OK button

type search-box as github
show search-box
...
```

**Comment by kensoh** [comment]
When I try running below Node,js on my CentOS it works and output files from Twitter data are created.

Try doing symbolic links to the phantomjs and casperjs commands so that they are accessible from your shell. Probably calling from Node there is no reference to get the locations of those commands.

```js
const cmd = require('node-cmd');
cmd.run('/full_path/node_modules/tagui/src/tagui /full_path/node_modules/tagui/src/samples/2_twitter');
```

**Comment by kensoh** [comment]
**additional notes for future reference**

For macOS / Linux, the block of code which likely where this happens is in tagui/src/tagui file. Following implementation works for running from shell or scripts, but may not work when invoking from Node.js script. If you don't do a symbolic link, you can consider hard-coding the env variables in the file or from your Node.js scripts to see if that works - CASPERJS_EXECUTABLE / PHANTOMJS_EXECUTABLE / SLIMERJS_EXECUTABLE. Or recommending some modifications below to enable invocation from Node.js. Otherwise at present, that isn't supported wo further config like symbolic linking.

```bash
# change current directory to TAGUI directory
SOURCE="${BASH_SOURCE[0]}" # slimerjs's implementation instead of cd "`dirname "$0"`"
while [ -h "$SOURCE" ]; do TAGUI_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
SOURCE="$(readlink "$SOURCE")"; [[ $SOURCE != /* ]] && SOURCE="$TAGUI_DIR/$SOURCE"; done
TAGUI_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"; cd "$TAGUI_DIR"

# below 3 blocks dynamically set up dependencies paths for different setups
# first set dependencies to local symbolic links (for manual installation)
CASPERJS_EXECUTABLE="/usr/local/bin/casperjs"
export PHANTOMJS_EXECUTABLE="/usr/local/bin/phantomjs"
export SLIMERJS_EXECUTABLE="/usr/local/bin/slimerjs"

# then set to node.js dependencies if they exist (for npm install tagui)
if [ -f "$(pwd)/../../casperjs/bin/casperjs" ]; then CASPERJS_EXECUTABLE="$(pwd)/../../casperjs/bin/casperjs"; fi
if [ -f "$(pwd)/../../phantomjs-prebuilt/bin/phantomjs" ]; then export PHANTOMJS_EXECUTABLE="$(pwd)/../../phantomjs-prebuilt/bin/phantomjs"; fi
if [ -f "$(pwd)/../../slimerjs/src/slimerjs" ]; then export SLIMERJS_EXECUTABLE="$(pwd)/../../slimerjs/src/slimerjs"; fi

# finally set to packaged dependencies if they exist (for packaged installation)
if [ -f "$(pwd)/casperjs/bin/casperjs" ]; then CASPERJS_EXECUTABLE="$(pwd)/casperjs/bin/casperjs"; fi
if [ -f "$(pwd)/phantomjs/bin/phantomjs" ]; then export PHANTOMJS_EXECUTABLE="$(pwd)/phantomjs/bin/phantomjs"; fi
if [ -f "$(pwd)/slimerjs/slimerjs" ]; then export SLIMERJS_EXECUTABLE="$(pwd)/slimerjs/slimerjs"; fi
```

**Comment by lyzs90** [comment]
just to shed some light on what i was doing. I was trying to get tagui to run from a subprocess in an express server.

symlinking didnt do the trick for me. but the moment i switched to python and used their subprocess module... it just worked. so case closed i guess 😓

**Comment by kensoh** [comment]
Oh shucks.. Hope more Node.js users will run into a similar use case so that we all can figure out how to call TagUI from node script. Cool idea to do that from Python.

By default TagUI is designed to run per instance per installation directory. I think if multiple runs are made it may not work as expected. I have tried running multiple instances (up to 4) on my 2014 macbook air and it becomes very slow. I was using default PhantomJS mode.

**Comment by lyzs90** [comment]
it works now! 🎉 the issue turned out to be nodemon..

**Comment by kensoh** [comment]
Oh cool! Nice catch!

**Comment by ramanathanMuthuraman** [comment]
Hi Shem,

When I was using tagUI via node, I didn't face any issues with mac, but it
didn't work in windows.
When I checked the error, I came to know that tagUI requires PHP and some
other dependencies which were installed in my mac but not on windows. So
went ahead with dockerization.

To execute the app in docker mode (please check out my repo for more info)

*npm run start:docker*

Not sure whether it helped you but this is how I solved it.


Thanks and Regards,
Ramanathan M

**Comment by kensoh** [comment]
Hi Ramanathan @ramanathanMuthuraman thanks for sharing your experience! and creative use of automation for filling timesheets 😄
