### ISSUE TITLE
Tag UI

### ISSUE THREAD

**Issue by SofyanShaikh** [kelaberetiv/TagUI#254]
Hi ,

Recently i was trying to automate data pull through a website.
The step is simple , i need to click few buttons on website make few selection on dropdown box and push the download option.

I tried chrome recorder but it is not working as required. I also tried modifying but the issue seems to be present in case of ticking box in dropdown.

Can you please help me

**Comment by kensoh** [comment]
Hi @SofyanShaikh you can try inspecting the xpath of the tick box using below example to see what is the correct xpath to click on the tickbox - https://github.com/kelaberetiv/TagUI#find-xpath-of-web-element

You can also try using computer vision to click on the tick box. For setting up and using computer vision, you can below link - https://github.com/kelaberetiv/TagUI#visual-automation

Lastly, some websites maybe deter automated robots from interacting with them, so it may be near impossible to automate those websites.
