### ISSUE TITLE
Unable to Enter data to a  popup window

### ISSUE THREAD

**Issue by YPvenkat** [kelaberetiv/TagUI#255]
Hi kensoh,

I'm using tagui to automate a website, when I open that website it  will ask us to enter Username and password in a popup window I tried using the below code but that doesn't helped me.

popup Sign in {
click Username
enter Username as xyz
click Password 
enter Password as xyz
click Sign in
}
Is there anything else to do so that we can enter the username and password to a popup window

Regards,
Rahul.

**Comment by kensoh** [comment]
Hi Rahul for normal popup boxes you can try something like below, where Username, Password are the website identifiers. See here on how to find XPath of identifier - https://github.com/kelaberetiv/TagUI#find-xpath-of-web-element

```
click Username
enter Username as xyz
click Password
enter Password as xyz
click Sign in
```

If you see the pros step in below link, popup step is meant for use with webpages that open up in a new tab from an existing webpage. It might be that popup window you are looking at is not a new tab but a popup modal box on the same tab.

https://github.com/kelaberetiv/TagUI#steps-description

**Comment by kensoh** [comment]
Referring to your screenshot below, there is no way to natively control this type of dialog popup box.

The only way TagUI can interact with this is using the computer vision method, you can see this section of documentation to setup and use the visual automation -

https://github.com/kelaberetiv/TagUI#visual-automation

![untitled](https://user-images.githubusercontent.com/10379601/43844782-1397cbb0-9b5d-11e8-8451-459702948bad.png)
