### ISSUE TITLE
How can we save raw HTML of webpage?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#256]
from email query

**Comment by kensoh** [comment]
Can do something like below, when read step takes in page as the target it automatically extract the raw html and put it to the variable. dump step writes the variable contents to a file. Below works with both chrome option and the default PhantomJS browser.

```
https://google.com
read page to html
dump html to result.html
```

**Comment by CJohnDesign** [comment]
I was hoping to get the HTML of specific elements

**Comment by kensoh** [comment]
Hi @CJohnDesign there isn't a step to do that as TagUI is primarily designed to replicate user's actions on the UI and retrieving the HTML code is not a usual use case. The `read` or `save` step can be used to retrieve the text value but not the raw HTML.

You can consider using the `read page to tmp_var` or `save page to tmp.txt` then do additional processing with JavaScript. You just can write JS code directly in TagUI. Or prefix with `js` or use `js begin` / `js finish`. Details under pro steps - https://github.com/kelaberetiv/TagUI#steps-description
