### ISSUE TITLE
Does Tagui supports remote desktop automation??

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#258]
Hi,
 
 I'm interested in automating tasks in remote desktops. So, I'd like to know is this feature available in Tagui. Is there such possibility?

Thanks in advance,
Sahithi N.

**Comment by kensoh** [comment]
Hi Sahithi, there are perhaps 3 ways to look at this -

1. will be setting up the automation scripts and TagUI on the remote computer run the tasks there directly.

2. will be using [computer vision method](https://github.com/kelaberetiv/TagUI#visual-automation) to control the remote desktop session with TeamViewer or other client.

3. will be having scripts and TagUI at the remote computer, but let the host connect to the remote computer with TeamViewer etc and initiate the automations (again using computer vision).

Copying @Aussiroth as he will be taking over supporting questions and advice on TagUI usage.

**Comment by kensoh** [comment]
Some more notes and examples here - https://github.com/kelaberetiv/TagUI/issues/272
