### ISSUE TITLE
Can TagUI run on smartphones like Android and iPhones?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#260]
from user query, on running on smartphones to bypass company internet restrictions -

---

So all their laptops cannot access internet. 

When I told them that TagUI can also run on linux, one of them asked: if his smartphone has linux, can TagUI run on his smartphone?

They are keen about this because their laptop has no internet, and it's too troublesome for them to bring their laptop from home. So if their smartphone can run TagUI on linux, it would be really cool! 

Theoretically, I don't see any reason why TagUI cannot run on linux on smartphone or tablet. I heard Surface Pro can run linux too.

Have you tried this before?

If it can run, I think TagUI should also run on an jailbreak iPad/iPhone.

**Comment by kensoh** [comment]
**short answer - no**

**long answer**

Their laptops can't access internet, but they can use on their intranet webpages. Android is a variant of Linux but a normal phone doesn't have provision for user to use the terminal or have root access to install software via terminal to run, so it should unlikely be possible. Also the Chrome on the Android would probably behave differently from the Chrome desktop browser.

I have heard that people run PhantomJS successfully on Raspberry Pi, so for those mini-computers TagUI should be able to work, as the Linux OS on the device allows normal installation of software and root access.

Surface Pro can run Linux has no use for this use case, because if the Linux on it works, then might as well run TagUI directly on the Surface Pro Windows OS. The reason for the network and firewall block is from the network hardware / software layer. And unlikely can be hacked by using a Linux shell on the Windows.

iOS is a variant of the macOS which is a cousin of Linux. Perhaps.. But I would think an easy and readily available solution now is simply use remote desktop software, eg TeamViewer. Using this software on Android or iPhone works. And can connect to the user's laptop or desktop at home to run and config the automation as required.

**Comment by adegard** [comment]
Hi @kensoh 
Recently I installed "Debian noroot" app on android wich is a linux emulator.
it runs well on tablet Galaxy (with external mouse a BT keyboard).
(https://play.google.com/store/apps/details?id=com.cuntubuntu)
I didn't try to launch TagUi for now, because my linux Knowledges are limited.

**Comment by kensoh** [comment]
Thanks @adegard for sharing the good info! It might only work in PhantomJS mode, because current versions of Firefox are not compatible with SlimerJS (https://github.com/laurentj/slimerjs/issues/694). Also copying @Aussiroth.
