### ISSUE TITLE
TagUI searches for php

### ISSUE THREAD

**Issue by geff10** [kelaberetiv/TagUI#262]
When trying to run TagUI scripts (like the example script or a hello world) from command line on Windows 10 it says "'php' is not recognized as an internal or external command,operable program or batch file."
![taguierror](https://user-images.githubusercontent.com/3542764/44618409-6b525d00-a875-11e8-9bca-685037d6d408.PNG)

**Comment by shoeper** [comment]
Troubleshooting potential exceptions

For Windows computers, if you see 'MSVCR110.dll is missing' error, install this from Microsoft website (choose vcredist_x86.exe) - this file is required to run the Windows PHP engine packaged with TagUI.
For some newer macOS versions, if you get a 'dyld: Library not loaded' error, install OpenSSL in this way.
For some flavours of Linux (Ubuntu for example), which do not have PHP pre-installed, google how to install PHP accordingly (eg Ubuntu, apt-get install php). Most Linux distributions would already come with PHP.

**Comment by kensoh** [comment]
Thanks @shoeper ! Hi @geff10 the missing PHP error looks like you have downloaded master branch directly and may not have installed from the packaged installation. Try downloading the packaged zip according to the instructions below and see if the error happens again.

https://github.com/kelaberetiv/TagUI#packaged-installation

Also copying @Aussiroth as he will be taking over supporting questions and advice on TagUI usage.
