### ISSUE TITLE
 Error when path directory has space(s)

### ISSUE THREAD

**Issue by shaunlgs** [kelaberetiv/TagUI#264]
Running the program: `C:\Users\Ling Gen Sheng Shaun\tagui\src>tagui project1\project1`

If you have space(s) in your path it gives errors like this:

```
Unable to open file: C:\Users\Ling
  phantomjs://code/bootstrap.js:113 in __die
Unable to load script C:\Users\Ling; check file syntax
  phantomjs://code/bootstrap.js:113 in __die
0 was unexpected at this time.
```

**Comment by kensoh** [comment]
Some components of TagUI don't work well with spaces, for Windows try installing in some folder like c:\tagui from the setup documentation. Copying @Aussiroth as he will be taking over supporting questions and advice on TagUI usage.
