### ISSUE TITLE
Unable to run the flow using Firefox in Linux

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#266]
I have problems using tagui with firefox on ubuntu 16.04.2 LTS

**_._/tagui filename firefox
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS.
See Gecko version compatibility. If version is correct, launch slimerjs
with --debug=true to see Firefox error message_**

I am using Firefox version: 61.0.1 (64-bit)
Later I modified slimerjs/src/application.ini  file into

**MinVersion=53.0.0
MaxVersion=61.***

But, it didn't work for me and when I tried to run the file after this setting, I am getting the below error..

**_c is undefined                                                                   
-> resource://slimerjs/slQTKeyCodeToDOMCode.jsm: 36
-> resource://slimerjs/slQTKeyCodeToDOMCode.jsm: 36
-> resource://slimerjs/slimer-sdk/webpage.js: 15_**

How do I  able to run the flow? Please post the steps to reproduce...

Thanks in advance,
sahithi N.

**Comment by kensoh** [comment]
Hi Sahithi, TagUI uses SlimerJS to handle Firefox browser. SlimerJS is not working with the new versions of Firefox which has compatibility-breaking changes, see the open issue here - https://github.com/laurentj/slimerjs/issues/694

Copying @Aussiroth as he will be taking over supporting questions and advice on TagUI usage.
