### ISSUE TITLE
CORS: XMLHttpRequest Exception 101 error: calling rest api 

### ISSUE THREAD

**Issue by ffoliveira** [kelaberetiv/TagUI#267]
I'm trying to use the api script command to get external values, but i'm receiving the Cross origin are not supported error;

api http://server.domain.com/ws/getText

```
XMLHttpRequest cannot locad http://server.domain.com/ws/getText. Cross origin requests are not supported.
NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.

```

tagui running in debian 9 at command line. i configured the tagui_config.txt with webSecurityEnabled: false and localToRemoteUrlAccessEnabled: true

webservice is made in C# and headers are configured with headers "Access-Control-Allow-Origin" = "*"

**Comment by kensoh** [comment]
Visiting the URL http://server.domain.com/ws/getText results in a blank page with browser console error - Failed to load resource: A server with the specified hostname could not be found.

**sample script**
```
api http://server.domain.com/ws/getText
echo api_result
```

**sample results**
```
START - automation started - Thu Aug 30 2018 13:12:04 GMT+0800 (+08)

api http://server.domain.com/ws/getText
<!DOCTYPE HTML>
<html>

    <head>
        <title>404 Error - Page Not Found</title>
        <style>
            #ad_frame{ height:800px; width:100%; }
            body{ margin:0; border: 0; padding: 0; }
        </style>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script type="text/javascript" language="JavaScript">
            var url = 'http://www.iyfipgun.com/?dn='
                + document.domain + '&pid=9POL6F2H4';

            $(document).ready(function() {
                $('#ad_frame').attr('src', url);
            });
        </script>
    </head>
    <body>
        <iframe id="ad_frame" src="http://www.iyfipgun.com/"
            frameborder="0" scrolling="no">

            <!-- browser does not support iframe's -->

        </iframe>
    </body>

</html>


FINISH - automation finished - 0.9s
```

The execution results matches the behavior when viewing from browser, that the URL / page is not found. The sample flow 3 shows a simple example of running api step - https://github.com/kelaberetiv/TagUI/blob/master/src/samples/3_github

The API section in doc shows more details on making advance API calls with headers and other stuffs -
https://github.com/kelaberetiv/TagUI/#api

Copying @Aussiroth as he will be taking over supporting questions and advice on TagUI usage.

**Comment by kensoh** [comment]
The same code works on Linux CentOS for me. Might be.. The underlying http request is sent through PhantomJS. There may perhaps be something underlying that doesn't work for Debian. But PhantomJS is no longer actively maintained, so you might not get any solution for this. Copying @Aussiroth 

Don't see any related issue for what you are experiencing on Debian -
https://github.com/ariya/phantomjs/issues?utf8=✓&q=XMLHttpRequest+Exception+101+

**Comment by ffoliveira** [comment]
Hi.
I updated the local node_modules repository using the 

npm update

and updated the tagui script to point to the local phantomjs version, and it is working now.

thank you for your great support.

**Comment by kensoh** [comment]
Oh wow, that is cool information, thanks for sharing that Fernando :smile: (copying @Aussiroth)

The npm Phantom package is maintained by the Medium folks, didn't know that their variant would work for this scenario, glad to learn this from you - https://www.npmjs.com/package/phantomjs-prebuilt
