### ISSUE TITLE
Remote Desktop or Citrix based automation support in TagUI

### ISSUE THREAD

**Issue by ramu-yarru** [kelaberetiv/TagUI#272]
Hi Ken,

Is there any Remote Desktop or Citrix based automation support in TagUI. If so, could you please share some samples or documentation where I can get more information.

Thanks,
Ramu

**Comment by kensoh** [comment]
Hi Ramu, I assume you mean running a remote desktop session on your computer and then automating the UI interactions on it. For this, TagUI relies on the visual automation and OCR capabilities of Sikuli (based on OpenCV and Tesseract).

1. To setup visual automation, refer to - https://github.com/kelaberetiv/TagUI#visual-automation

2. For a sample automation flow refer to this example for microsoft outlook - https://github.com/kelaberetiv/TagUI/issues/113#issuecomment-378194245

3. If you are referring to setting TagUI to run on the remote computer, refer to this - https://github.com/kelaberetiv/TagUI/issues/258

Copying @Aussiroth as he is taking over supporting questions and advice on TagUI usage. I think the commercial RPA software is better for such use cases, but you can give a try how TagUI works for you.

Following is comparison of TagUI's strengths and weaknesses, compared to commercial RPA software - https://github.com/kelaberetiv/TagUI#why-this (click to expand `Click to show differences between TagUI open-source RPA and commercial RPA software`)

**Comment by luisbomfim** [comment]
Hi Ken.

I also have some automation that needs to interact with the UI. To run them in a minimized remote desktop session  just make the following change on the local machine (not on the remote server)

1 - Close any Remote Desktop sessions that you currently have open on your computer.
2 - Still on the local computer, open the Registry Editor and navigate to the key: HKEY_CURRENT_USER \ Software \ Microsoft \ Terminal Server Client
3 - Create a DWORD value called RemoteDesktop_SuppressWhenMinimized and set its value to 2

With that, I can open a remote desktop session, start automation and minimize the session without problems. Automation will be able to interact with the UI as the remote desktop client will keep the session active even with the client minimized.

It is not the most elegant solution, but it was the way I found to perform various automation during the night on a server.

**Comment by kensoh** [comment]
Hi Luis, thanks for sharing your solution and tip! Appreciate that you took the time to share =)
