### ISSUE TITLE
Excel support in TagUI

### ISSUE THREAD

**Issue by ramu-yarru** [kelaberetiv/TagUI#277]
Hi Ken,

Do we have excel support in TagUI? My requirement is, i have to open an excel file and read or write data to  particular cell, for example A31 or B2 etc. Is this possible? Note that I don't have any Headers (Heading) for the columns. Kindly let me know is there any possibility.

Thanks,
Ramu

**Comment by kensoh** [comment]
Hi Ramu, there is no excel support in TagUI. The workaround is using the computer vision capability to interact with the excel application, or save the excel as .csv and then use JavaScript code to process the csv file. More on computer vision - https://github.com/kelaberetiv/TagUI#visual-automation

Copying @Aussiroth as he is taking over supporting questions and advice on TagUI usage.

**Comment by ramu-yarru** [comment]
Hi Ken,

        Thanks for the reply. By using the visual automation, I am able to automate the first column of the excel sheet, where it has numbering for the reference. But, I want to select and input data for other columns like B5 or D7 etc, where it has no reference. what you suggest to work on these type of scenarios ??

Thanks,
Ramu

**Comment by SnehaGhatkar** [comment]
Hello @ ramu will you please share the code which you have used to deal with excel sheet?
