### ISSUE TITLE
How to select the web element when the page source is not available?

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#279]
Hi,
    I am trying to automate a web application where the page source is not visible. The application has elements with the same text and class. How can I select the web element in that case? And also how to select web element with respect to class name, if the class name and text of that element is same as that of the another element of the same page?

Thanks in advance,
Sahithi N.

**Comment by Aussiroth** [comment]
Hi,

For a case where elements may share attribute values like for the @class and @name, you will probably need to manually try out xpath selector combinations or use a [1], [2] at the end to specify the 1st or 2nd element matching this. E.g. (//id[@class="sample"])[2] selects the 2nd id element with class equal to the text "sample".  You can use the inspector in whichever web browser you use to enter the xpath and see if it correctly selects only the element you want.

From what I know, a web application without any html document, I think it may not be able to automate it using the usual web automation, such as Progressive Web Apps that are becoming more prevalent now. However I may be mistaken in what you mean by the page source is not available.
