### ISSUE TITLE
How to fetch value of selected dropdown option?

### ISSUE THREAD

**Issue by yangliu8912** [kelaberetiv/TagUI#280]
I have a select element where user would have chosen a particular option. When I do

read //select[@name="applnMemberView[0].position"] to x
echo x

Every option is printed out. Is it possible to fetch only the selected option?

**Comment by Aussiroth** [comment]
Hi,
Usually for a select HTML element you will see something like
<select ...>
   <option value=...>
   <option value=...>
When you do a read step on the select, it will also read the text content for the child options. If you want to read only a specific one, then you would want to also make use of the option element in the xpath.
E.g. read //select[@name="..."]/option[...] to x

**Comment by Aussiroth** [comment]
Hi,
Unfortunately its usually not possible to tell the current option being selected from the HTML document. Instead, you probably will need to use javascript in the webpage DOM. 
This may provide a reference on how to do it - https://stackoverflow.com/questions/1085801/get-selected-value-in-dropdown-list-using-javascript , I am not so well versed in manipulating webpage DOM myself.
