### ISSUE TITLE
Mail read support in Tagui

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#281]
Hi @kensoh ,
   I am working on a case, where I need to download and read an excel sheet got to a particular email with a particular subject every time. How can I trigger my tagui flow when I get the email?  Please suggest.

Thanks in advance,
Sahithi N.

**Comment by kensoh** [comment]
Hi @nsahithi I have left AI Singapore, copying @Aussiroth as he has taken over supporting questions and advice on TagUI usage.

This is not supported. At best you can try using the visual automation method to keep trying to read an email and acting on it. Or if your email is self-hosted on a cPanel server you can consider using Tmail or some other open-source email libraries to try to hack and hijack the incoming email through code. I think it will be very hard to implement, so you can take that it is not possible and not supported.

Related links on visual automation using TagUI and Tmail mailbot configuration -
- https://github.com/kelaberetiv/TagUI/issues/113#issuecomment-378194245
- https://github.com/kelaberetiv/TagUI/issues/134
- https://github.com/kelaberetiv/TagUI/issues/126
