### ISSUE TITLE
How to select multiple options (in multi-select field)?

### ISSUE THREAD

**Issue by yangliu8912** [kelaberetiv/TagUI#283]
@Aussiroth 

Hi Alvin,
What is the syntax for selecting multiple options?

Referring to this example:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple
How do I write TagUI command to select both volvo and audi?

Thanks and regards,
Yang Liu

**Comment by Aussiroth** [comment]
Hi,
TagUI isn't natively capable of supporting a simple command to perform multiple selects. This is actually the first time I've come across an issue of trying to select multiple options with TagUI. I've tried updating the selection code to select multiple options but it only successfully selects the last one. I'll try to see if there's a way to support this automatically, but it will probably need quite some changes to the code.

Hopefully Ken might have experience with such selections.

**Comment by kensoh** [comment]
That's right, a typical selection dropdown TagUI uses JavaScript code to set the matched option and then trigger an UIEvent. When you do this for the 2nd time, the behaviour happens as you expect when you manually click on the 2nd option - the 1st selected option becomes unselected.

I can imagine 2 ways to address this. First may be you can try writing JavaScript code to do the selection that you want. And use the js step (js begin and js finish) to run your custom JavaScript code.

The second way is use the [computer vision method](https://github.com/kelaberetiv/TagUI#visual-automation) of TagUI to visually click on what you want. With the Sikuli's visual automation and TagUI vision step, you can send custom commands such as Control function key. You can give a try with more details here - https://github.com/kelaberetiv/TagUI/issues/155#issuecomment-397403024

**Comment by bcpeinhardt** [comment]
I was able to solve this by putting similar code to what's described here https://stackoverflow.com/questions/1295950/javascript-to-select-multiple-options inside a dom step (dom begin and dom finish).

**Comment by kensoh** [comment]
Thanks @bcpeinhardt for sharing back your solution here! :)

Also copying @ruthtxh
