### ISSUE TITLE
onchange event not activated in select step

### ISSUE THREAD

**Issue by yangliu8912** [kelaberetiv/TagUI#286]
Hi,

I have a select dropdown with an onchange event:

onchange="javascript:hideAndShowHistory();"

When I use the select step in TagUI, the select dropdown box will be selected but the onchange event will not be triggered.

Currently I have to use "live" step to pause the TagUI flow, and manually type hideAndShowHistory() in the chrome inspector console for the onchange event to take effect. Any workarounds to prevent having this extra pause?

Thanks and regards,
Yang Liu

**Comment by yangliu8912** [comment]
Hi Ken,

I just anyhow tried adding the below step after the usual select step:
dom hideAndShowHistory()
and it worked!

I am closing this issue. Thanks!

Best regards,
Yang Liu

**Comment by kensoh** [comment]
Hi Yang Liu, that's a nice question and solution - thanks for sharing! :smile:

Yeah, it looks like there is some special event handling for the dropdown box, and when you use js step to trigger the function handling that event it works the way you expect. Copying @Aussiroth too.

**Comment by Tejaswini-Appollo** [comment]
dom document.querySelector("#bankNiftySelect > optgroup:nth-child(1) > option:nth-child(2)").setAttribute('selected', true)
dom hideAndShowHistory()

Is this way ?

**Comment by ruthtxh** [comment]
Hi @Tejaswini-Appollo are you able to share the website that you are automating on? The suggested solution above is used with select step for dropdown.
https://tagui.readthedocs.io/en/latest/reference.html?#select

You may want to try using click step for automating dropdown too.
