### ISSUE TITLE
Can TagUi detect a button being enabled?

### ISSUE THREAD

**Issue by sangasangasanga** [kelaberetiv/TagUI#287]
For instance, 

TagUi clicks on the run button.
![image](https://user-images.githubusercontent.com/34553270/46645193-55df8b00-cbb6-11e8-9d60-548e3722a178.png)
Then, the run button will be disabled.
![image](https://user-images.githubusercontent.com/34553270/46645265-b373d780-cbb6-11e8-974f-17a01a099bbe.png)
The run button will be enabled again after the process is done

Can TagUi detect when the the run button is enabled again, so that it can continue doing other things?
Or can tagui wait till the enabled run pic is shown?

**Comment by sangasangasanga** [comment]
Hi, I tried your second code as it is not a webpage. However, I am getting an error.
This is my code
`click 1538989320206.png
click Project2.png
dClick 2808v4xamI.png
wait 50sec
click Run.png
wait 10sec
click 1539057219886.png
click 1539056665534.png
break
for i from 1 to 30
if present(1539056665534.png)
{
wait 3
echo no
//this makes tagui wait 3 seconds between each check
}
else
echo yes
`
This is the error
![image](https://user-images.githubusercontent.com/34553270/46650931-e1feac00-cbd0-11e8-95de-b16f8ba728af.png)

**Comment by sangasangasanga** [comment]
Hi, like above, it works in one process. But in another process, tagui is reading this 
![image](https://user-images.githubusercontent.com/34553270/46712907-0072af00-cc86-11e8-930b-e9b39f6f797e.png)
as
![image](https://user-images.githubusercontent.com/34553270/46712914-08caea00-cc86-11e8-8259-f2a1fba3ff66.png)
Thus, it is continuing the process. But it shouldn't till the enabled run button is shown. But tagui is reading it wrongly. Pls advise thank you

**Comment by kensoh** [comment]
for i from 1 to 30
{
  if present('button_disabled.png')
  {
    wait 3
    //this makes tagui wait 3 seconds between each check
  }
  else
    break
}

**Comment by kensoh** [comment]
There isn't enough details above on how the difference in behavior can be replicated.

Perhaps you can try something like below. 1. The wait is positioned to happen first in case the UI takes some time for the button to become disabled. 2. the for loop repeats for infinity (defaults to 1024), in case the UI takes more than 90 seconds for above eg (3 seconds x 30 iterations).

```
for i from 1 to infinity
{
  wait 3
  if present('button_enabled.png')
  {
    break
  }
}
```

**Comment by Anujpalu24** [comment]
@Aussiroth @kensoh  :  I have tried below code snippet shared by you but it not verifying that button is enabled, like button is enabled still it is going into else. 

for i from 1 to 30
  read //id="button"/@name to button_name
  if button_name equals to "disabled"
    {
    wait 3
    //this makes tagui wait 3 seconds between each check
    }
  else
    echo button is disabled

**Comment by kensoh** [comment]
Hi @Anujpalu24 for your above code, it only works if the button has the word "disabled" on it. If you are looking at using computer vision to compare with an image snapshot, then the code to reference will be something like this - https://github.com/kelaberetiv/TagUI/issues/287#issuecomment-428440558

present checks and replies instantly
```
if  present('button_enabled.png')
        do something
```

exist checks up to 10 seconds before giving up
```
if  exist('button_enabled.png')
        do something
```
