### ISSUE TITLE
escape

### ISSUE THREAD

**Issue by yangliu8912** [kelaberetiv/TagUI#290]
"type" step won't type left bracket "("

example:
type //input[@name="combobox"] as "abc(edf)"
will be typed as abcedf)

**Comment by Aussiroth** [comment]
Hi, I tested out the steps for typing that example in google's search bar,
type //*[@name="q"] as "abc(def)", which correctly typed "abc(def)"
type //*[@name="q"] as abc(def), which correctly typed abc(def)
both for chrome and phantomjs browser context. The generated javascript code looks OK as well. Perhaps it may have something to do with the specific text box you are entering into?

**Comment by yangliu8912** [comment]
> Hi, I tested out the steps for typing that example in google's search bar,
> type //*[@name="q"] as "abc(def)", which correctly typed "abc(def)"
> type //*[@name="q"] as abc(def), which correctly typed abc(def)
> both for chrome and phantomjs browser context. The generated javascript code looks OK as well. Perhaps it may have something to do with the specific text box you are entering into?

Thank you Alvin for testing on Google search, I've also verified using other input box. You are right, it seems to be particular to the specific text I am dealing with.

 Closing this issue.
