### ISSUE TITLE
Can Chrome be open when the step reaches the web automation??

### ISSUE THREAD

**Issue by nsahithi** [kelaberetiv/TagUI#293]
Hi,
   I am working on a flow which includes both visual and web automation. In web automation part I am using the _ask_ step. When I started the execution, chrome is opening in the first step itself and I kept it in the minimized mode to continue visual automation part. I want the chrome window to be visual as soon as the web automation starts. Is it possible?

Thanks in advance,
Sahithi N.

**Comment by Aussiroth** [comment]
Hi, it is currently not possible to have chrome window open only when doing the web automation parts. TagUI will check if you are using chrome and perform all the necessary backend tasks needed to launch chrome with the correct settings and attach to it to allow it to communicate and control the chrome session. Starting the chrome session in the middle of the automation would require quite a lot of changes and might not work correctly, so for now you will need to perform the minimisation of the chrome window.

**Comment by harikgdona** [comment]
As you mentioned the issue raise is not possible around October 2018. Now can it be fixed/is it fixed?
If not can we have some guidance to make it done.

**Comment by umakattula** [comment]
Hi,
As you mentioned the issue raised is not possible around October 2018. Now can it be fixed/is fixed?
If not can we have some guidance to make it done.
Thanks in advance,
Umasrinivas

**Comment by kensoh** [comment]
Replied via #401
