### ISSUE TITLE
unable to import npm package in tagui_global.js

### ISSUE THREAD

**Issue by tejaswiniarrob** [kelaberetiv/TagUI#298]
i tried to require exceljs package in tagui_global.js 

it says,
START - automation started - Tue Oct 30 2018 17:38:25 GMT+0530 (IST)
SyntaxError: Use of reserved word 'class'                                       
 /home/wini/Rpa/Botforce-linux/src/phantomjs:/platform/promish-class.js:15 in loadModule

ReferenceError: Can't find variable: Promise                                    
  /home/wini/Rpa/Botforce-linux/src/phantomjs:/platform/promish.js:5
Error: Cannot find module 'events'                                              
  /home/wini/Rpa/Botforce-linux/src/phantomjs:/platform/bootstrap.js:299 in require
  /home/wini/Rpa/Botforce-linux/src/phantomjs:/platform/bootstrap.js:263 in require
  /home/wini/Rpa/Botforce-linux/src/phantomjs:/platform/zip-stream.js:14
Error: Cannot find module 'stream'                                              
  /home/wini/Rpa/Botforce-linux/src/phantomjs:/platform/bootstrap.js:299 in require

Can you please help me with this?

**Comment by kensoh** [comment]
duplicated to - https://github.com/kelaberetiv/TagUI/issues/299
