### ISSUE TITLE
Click on image hangs

### ISSUE THREAD

**Issue by SUPRIYO05p** [kelaberetiv/TagUI#300]
click  C:/tagui/src/samples/win.PNG

hangs at this step. all log files are 0 KB

**Comment by balwant-sd** [comment]
Same With me. Same happens with dclick.

**Comment by Aussiroth** [comment]
Hi, have you installed Sikuli correctly in the tagui.sikuli folder? The /src/tagui.sikuli folder should have contents that look like this if installed correctly.
![image](https://user-images.githubusercontent.com/3212014/47781985-11b95380-dd3a-11e8-8d13-2042762a412f.png)

**Comment by balwant-sd** [comment]
Hey, I using Ubuntu OS. I used packaged installation which required only unzip of package.
My Directory Structure look like this :-
![1](https://user-images.githubusercontent.com/44574296/47782739-fabd3600-dd26-11e8-8391-d847a99ec036.png)

**Comment by Aussiroth** [comment]
Hi, you need to install Sikuli for TagUI to use visual automation. The instructions for it are here in the documentation. https://github.com/kelaberetiv/TagUI#visual-automation)
