### ISSUE TITLE
Help for reading Xls, xlsx files

### ISSUE THREAD

**Issue by SUPRIYO05p** [kelaberetiv/TagUI#301]
Hello, I am looking for automating by reading data from an excel file.

I see a note for CSV files in link 
https://rpa-sg.org/TagUI-Tips-Techniques/how-to-read-a-csv-file-part-2-multiple-columns.php

Will this approach work for excel?

**Comment by Aussiroth** [comment]
Hi, this will not work for excel spreadsheets. CSV files are saved in plaintext format so we can read the data directly as is. However, excel files are saved with lots of other details (e.g. formatting) and are not readable as raw text. 
You can still make use of excel data by saving a specific sheet as a .csv file and automating on that sheet though.
