### ISSUE TITLE
How to wait for an image to appear using Sikuli visual automation?

### ISSUE THREAD

**Issue by SUPRIYO05p** [kelaberetiv/TagUI#302]
For a number of automations, we cannot give an exclusive wait, however we wait for a specific image to come. link in Sikuli we give exclusive pattern matching time. How do we use same in TAGUI?

**Comment by Aussiroth** [comment]
Hi, if you have a specific command used in sikuli to perform a task, you can make use of the exact same command in TagUI, by making use of the vision step. TagUI will pass the command directly as-is to sikuli to execute. So in this case you can use the vision step to send the command for sikuli to wait until it sees the image.

**Comment by kensoh** [comment]
Adding on, for mac/Linux it will be something like below. Full path is required and max timeout in seconds. For more usage of Sikuli will need to google online for other info and resources.

`vision wait('/Users/kensoh/Desktop/yara.png', 3600)`
