### ISSUE TITLE
Select dropdown (drop-down) options - use the option value to denote what to select

### ISSUE THREAD

**Issue by stevzie** [kelaberetiv/TagUI#305]
Placing this here so it does not confuse other users ...

When using the "select" instruction -- select _dropdown_name_ as _option_
you must use the value attribute (not the user visible text).

For example (from Wordpress):

```<select name="role" id="role">
	<option value="wpseo_editor">SEO Editor</option>
	<option value="wpseo_manager">SEO Manager</option>
	<option value="bbp_participant">Participant</option>
	<option value="bbp_moderator">Moderator</option>
	<option value="administrator">Administrator</option>
        <option value="">— No role for this site —</option>
</select>`
```
the correct statement to select the "SEO Manager" option is:

    select role as wpseo_editor

**Comment by kensoh** [comment]
Nice, thanks @stevzie ! It's mentioned in the cheat sheet but this is going to be helpful to other users.

Copying @Aussiroth who is now maintaining TagUI for AI Singapore -

**Comment by shahidshaikhleaque** [comment]
@stevzie I am trying to select value from drop down  which is having 
 name="MC19x279_select_attribute" and drop down value is "creationtime". 
I am doing like this **click //select[@name="MC19x279_select_attribute"] as option creationtime** .
But getting error. Could you please help me to get the correct way.

**Comment by kensoh** [comment]
Oh @shahidshaikhleaque the syntax is

```
click //*[@name="MC19x279_select_attribute"] as creationtime
```

PS - 1. using * instead of select will work, 2. no need for option keyword
