### ISSUE TITLE
hover with XPath (can single quotes be used in XPath?)

### ISSUE THREAD

**Issue by stevzie** [kelaberetiv/TagUI#306]
Can anyone explain why the following does not work:

    hover //tr[contains(@id, 'user')]/td[1]/strong/a

I receive:
    SyntaxError: Expected token ')'

The XPath statement works correctly in the Chrome console.

**Comment by kensoh** [comment]
Hey @stevzie try using double quotes -

```
hover //tr[contains(@id, "user")]/td[1]/strong/a
```

The flow samples and the tip under here - https://github.com/kelaberetiv/TagUI#steps-description mentions this but may be easy to miss.

The convention is chosen so that users can use single quotes to form dynamic XPaths with their variables, eg by user '+variable_name+' or \`variable_name\` in their element identifiers.

**Comment by kensoh** [comment]
Forgot to copy @Aussiroth who is now maintaining TagUI for AI Singapore -

**Comment by fez226** [comment]
hello @kensoh i had a problem with single quote but i finally have a solution... if anybody want to put a single quote on a string you need to put a back slash behind it. example:

var1 = '\'DRAFT\''

type [element] as '+var1+'

so this write 'DRAFT' on the element input text

**Comment by kensoh** [comment]
cool stuff thanks @fez226 fo sharing! yes I normally recommend using double quotes to keep it syntactically correct but yes you can use \ to escape the single quote character in XPath string.

also, now TagUI supports backticks to denote variable, so your example step can be written as

```
type element_identifier as `var1`
```

**Comment by maheswarGR** [comment]
hover xpath not working :

hover //*[@id="gatewayHistoryDetailsTab"]/div[1]/i[3]

**Comment by kensoh** [comment]
I saw the duplicated question here - https://github.com/kelaberetiv/TagUI/issues/1171#issuecomment-1026523066 and will reply there
