### ISSUE TITLE
Unable to Open A Locally Store Image Using dclick 

### ISSUE THREAD

**Issue by balwant-sd** [kelaberetiv/TagUI#314]
This is my script written in tagui
```
echo 'now_sikuli'
dclick /home/pericent/Pictures/sss.png
echo 'now_web'
```

It will show 

```
[starting sikuli process]

START - automation started - Thu Nov 15 2018 11:55:47 GMT+0530 (IST)

now_sikuli
dclick /home/pericent/Pictures/sss.pn
```
and sits idle. What Should i do to open locally store image ?? @Aussiroth

**Comment by kensoh** [comment]
Issue due to https://github.com/kelaberetiv/TagUI/issues/316 - closing this duplicated issue
