### ISSUE TITLE
[enter] does not work inside gmail search bar

### ISSUE THREAD

**Issue by phitienamaris** [kelaberetiv/TagUI#317]
Hi there,

I tried to press enter key, but somehow it doesn't work, I am using [enter]. 
p/s: [clear] works fine.
Below is my script:
Thanks.

https://gmail.com
wait 3
type //*[@id="aso_search_form_anchor"]/div/input as RPA
enter //*[@id="aso_search_form_anchor"]/div/input as [clear]Google[enter]
wait 5

**Comment by Aussiroth** [comment]
Hi, can you try having the [clear] and [enter] in 2 separate steps instead? So 
```
type ... as [clear]
type ... as Google[enter]
```

**Comment by phitienamaris** [comment]
Thanks Aussiroth,

I have tried it as well, but it still does not work

https://gmail.com
wait 3
enter //*[@id="aso_search_form_anchor"]/div/input as Google[enter]
wait 15

**Comment by kensoh** [comment]
Why not try `click Search Mail` to start the search?

TagUI sends \\r to Chrome as the indication to enter, as Chrome browser reacts to \\r as enter key. This is also the same implementation used by Google Puppeteer. It could be the gmail website does not respond to \\r character as the enter keystroke.

'Search Mail' is the aria-label property of the search icon and TagUI element identification will also search for this property to match.

I just tried to see if [enter] works on Google search page, following works -

```
https://google.com
enter q as 123[enter]
wait
```

**Comment by phitienamaris** [comment]
Yes it works for other accept Gmail search box. I will try to use click on the search icon.

Thanks for your suggestion and I will close this issue.
