### ISSUE TITLE
If statement not working

### ISSUE THREAD

**Issue by SnehaGhatkar** [kelaberetiv/TagUI#319]
I am trying to compare the numbers in column1 of file2 with column1 of file1. If number in file2 does not match with number in file1 then it should be written in file3. After running below code all the data from file2 is written in file3. Please help me to solve this problem.

   array_file1num = []

   csv_file1 = 'file1data.csv'
   csv_file2 = 'file2data.csv'
   csv_file3 = 'file3data.csv'
  

   load '+csv_file1+' to lines1
   load '+csv_file2+' to lines2

   array_file1Lines = lines1.split('\n')
   array_file2Lines = lines2.split('\n')

   

   for j from 0 to array_file1Lines.length-1
  {
    items = array_file1Lines[j].split(',')
    array_file1num[j] = items[0].trim()
   }
 

  for k from 1 to array_file2Lines.length-1
  {
    items = array_file2Lines[k].split(',')
    flag  = 0
	
          for m from 1 to  array_file1num.length-1
            
            {
               echo "hii I came inside the loop to compare"
          
	       if array_file1num[k] equals to items[0].trim()
               {
               echo "I compare"
	       flag = 1
               break
               }
             
            }
	
         if flag equals to 0
         {

	  write items[0].trim() + ',' to '+csv_file3+'
          echo "I wrote"

         }
         
   }

**Comment by SnehaGhatkar** [comment]
Did you try with .CSV files? I run my code again it is writing all data from file2 to file3.

**Comment by Aussiroth** [comment]
Hi, apologies, yes I meant with that content in 2 .csv files.
Is it possible for you to share the first few rows or so of your files if they are not confidential? It will help me check why there seems to be an issue for your files but OK for my test sample.
