### ISSUE TITLE
TagUI Editor

### ISSUE THREAD

**Issue by adegard** [kelaberetiv/TagUI#321]
It's not an Issue:
I create a little TagUI editor (for Windows) in autohotkey : [https://github.com/adegard/tagui_scripts](https://github.com/adegard/tagui_scripts)

![tagui_editor](https://user-images.githubusercontent.com/23522577/50013843-95659180-ffc2-11e8-91dc-603a6abe9101.gif)

I hope it could be usefull!

**Comment by Aussiroth** [comment]
Hi Adegard, thanks a lot again for working on tools to help improve the user experience! I will see if I can update the documentation to include this alongside your other tools.

**Comment by adegard** [comment]
Hi @Aussiroth Alvin,
Your welcome! All pleasure is for me... I like so much TagUI, then I try to render it more "user-friendly" for my "non -developper" friends.
I just upload a new release with a "Schedule" Button, which creates directly routine in task scheduler of Windows....(for now:daily tasks, with batch files) If you try it, let me know I there is some issues...
![immagine](https://user-images.githubusercontent.com/23522577/50043813-0799ad00-007b-11e9-84fc-82c687e6a3cf.png)

**Comment by adegard** [comment]
I have an issue if file path contains spaces creating batch files

ie for

filetagui=C:\Users\degar_000\Google Drive\meteo.tagui
```
    @echo off
    
    tagui "%filetagui%" chrome

    pause
```

it return error because doesn't find file in "C:\Users\degar_000\Google "
Do you know how can I pass file path with spaces in batch comands?

**Comment by adegard** [comment]
I think it passing correctly the path, but tagui doesn't send it correctly to phantomjs...
![immagine](https://user-images.githubusercontent.com/23522577/50111301-ccdf7280-023c-11e9-93ee-64bd29769341.png)
Could you control?

**Comment by Aussiroth** [comment]
Hi, phantomjs does not work correctly with file paths that have spaces in them, so this is not something we have control over. Only workaround is to make sure all the file paths used with tagui do not have spaces in them.

**Comment by adegard** [comment]
OK thanks you @Aussiroth Alvin I put a warning message for path file with spaces.

**Comment by kensoh** [comment]
Going to send a PR that updates readme to point to the gif video for @adegard 's TagUI Editor. The gif is hosted at Arnaud's repo and is < 2MB so it's ok to put that instead of a TagUI Writer screenshot.
