### ISSUE TITLE
Portable Chrome

### ISSUE THREAD

**Issue by v-akos** [kelaberetiv/TagUI#329]
Due to the issue that a Chrome update has made file downloading function unpossible in headless mode I'm wondering if using a portable Chrome could be a solution.

My aim is to run TagUI in headless mode, and change the Chrome default download folder during the automation. Before the Chrome update it worked perfectly.

Thanks for any suggestion in advance!

**Comment by Aussiroth** [comment]
Hi, I have not personally tried portable chrome, but you can try it out by changing 
`set chrome_command=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` for windows to point to the portable chrome's execution file to try it out with portable chrome.

**Comment by v-akos** [comment]
Thanks for your help, Alvin!
I've tried with both Chrome v71 and v72beta, downloaded from poartableapps.com.
TagUI can use them as you wrote. But unfortunatelly it looks like it doesn't work in headless mode. No failure message, just nothing happens. And I have to use headless mode for changing the default folder...
Is it possible to run the portable versions in headless mode?

**Comment by Aussiroth** [comment]
As far as I know, it should be possible to run headless in the portable chrome? Just to check, does running normal chrome in headless work successfully for you?

**Comment by v-akos** [comment]
Just checked, and yes, normal Chrome runs in headless mode for me.

**Comment by Aussiroth** [comment]
In this case I think you might need to do some debugging in the tagui.cmd (I believe you are using windows?) to check where TagUI gets stuck. In particular, this code block around lines 600,
```
if not "!chrome_process_id!"=="" taskkill /PID !chrome_process_id! /T /F > nul 2>&1
start "" "%chrome_command%" !chrome_switches! !window_size! !headless_switch!

:scan_ws_again
rem wait until chrome is ready with websocket url for php thread
for /f "tokens=* usebackq" %%u in (`curl -s localhost:9222/json ^| grep -A 1 "\"url\": \"about:blank\"" ^| grep webSocketDebuggerUrl ^| cut -d" " -f 5`) do set ws_url=%%u
if "!ws_url!"=="" goto scan_ws_again
```
Perhaps try replacing it with the following
```
if not "!chrome_process_id!"=="" taskkill /PID !chrome_process_id! /T /F > nul 2>&1
echo Before chrome command start
start "" "%chrome_command%" !chrome_switches! !window_size! !headless_switch!
echo Chrome successfully started

:scan_ws_again
rem wait until chrome is ready with websocket url for php thread
for /f "tokens=* usebackq" %%u in (`curl -s localhost:9222/json ^| grep -A 1 "\"url\": \"about:blank\"" ^| grep webSocketDebuggerUrl ^| cut -d" " -f 5`) do set ws_url=%%u
if "!ws_url!"=="" goto scan_ws_again
echo Chrome websocket successfully attached
```
And see which echos succeed. Also if you aren't already try leaving the headless execution for a few minutes, I noticed that sometimes headless chrome can take surprisingly long to start up and run.

**Comment by v-akos** [comment]
According to your suggestion I've done these steps for debugging:

1) Tried with the original version of tagui.cmd for 15 minutes, but unfortunatelly didn't help.

2) Changed tagui.cmd as you wrote, and leave it for 25 minutes. Echoed lines:
Before chrome command start
Chrome successfully started
But nothing else echoed or happened at all.

**Comment by Aussiroth** [comment]
Ok, just one more check, can you run in portable chrome without headless mode?

Seems like in this case there is an issue with attaching to the remote debugging port for the chrome session, which may be that its not supported by portable chrome. @kensoh Not sure if you know anything about running this with portable chrome, thought if you might have some input.

**Comment by v-akos** [comment]
Yes, portable versions in headless mode work fine.
Thanks, Alvin!

**Comment by v-akos** [comment]
Thanks for the help, Ken!
You are rigth, it hangs without coming back to command line.
Running the curl command in tagui/src/unx folder gave no response, however come back to command line.
If any changes effects the normal the main case of normal Chrome visible and headless means no problem, since if it works with portable Chrome, I won't want to use it with normal Chrome.

**Comment by kensoh** [comment]
I see.. Looks like it could be that portable Chrome in headless mode does not return the websocket connectivity as curl returns no response.. In that case, Alvin, unless there are new findings, this issue will probably be filed under not supported, since headless portable Chrome doesn't provide the same interface for TagUI to latch onto to control it.

**Comment by v-akos** [comment]
Thanks for the support, Ken!
The are not so good news for my case. Do you plan any future improvement in this issue? I believe that having a relieable, not changing Chrome version can be a valid need for your users.

**Comment by Aussiroth** [comment]
Hey Ken, thanks for the input!
Hmm while it would be good to have a stable chrome environment for users to ensure chrome updates don't cause unwanted changes, it might be difficult to have it properly set up and make sure it doesn't get updated for users, especially considering for other OS configs.

**Comment by kensoh** [comment]
Adding on, from the above findings, it looks like the bottleneck and limitation is from the portable headless Chrome, so there is probably nothing that can be done from TagUI (can't find websocket connection info to connect to if it doesn't broadcast it).

One way would downloading older versions of Chrome and turning off the auto-updates (more info can be found online), but this has to be done by users as TagUI don't have control over their Chrome settings. Implementing a packaged version of Chrome doesn't sound like moving in the right spirit of RPA, which is replicating user actions on the software running on their computers (which includes Chrome and it's usual auto-updates).

**Comment by kensoh** [comment]
Oh what I mean is a normal user will not be using Chrome in headless mode. But when there is a chance, I hope that some workaround can be found to make this work for portable Chrome headless mode!

**Comment by v-akos** [comment]
Allright, let's see! :)

**Comment by kensoh** [comment]
Closing this for now as it seems to be resolved in Chrome v72 official build. Running below on the sample flow 3_github in headless mode results in `Tmail-master.zip` file downloaded as expected.

```
tagui 3_github headless
```

**Comment by v-akos** [comment]
Awesome news, thanks, Ken!
I've just tried it out with v72 and it has worked for me also. So I could change the default download folder in the automation flow.

**Comment by kensoh** [comment]
Cool Akos, welcome!

I'm glad Chrome team fixes this in the v72 official release when it was buggy at beta.
