### ISSUE TITLE
Passing Dynamic URL from XML to Tagui File

### ISSUE THREAD

**Issue by kiru00** [kelaberetiv/TagUI#332]
Why Tagui is not working by dynamic url address...
Thanks...

**Comment by Aussiroth** [comment]
Hi, if you want to visit a website via passing a dynamic url via a variable, or something similar, you will need to do a bit of workaround. To identify a step to go to a url, TagUI looks out for the http:// or https:// located at the start of the step. So having a step be like `` `my_url` `` will cause TagUI to fail understanding it.

To get around this, you can manually trim your URL to remove the http:// or https:// in front of it, then manually add in the https:// in front. For example, `` https://`my_url` ``

Another way is to add this function into a tagui_local.js file in the same folder as your automation.
`function gotourl(link) { // this custom function goes to the url provided
        casper.evaluate(function(link) {window.location.href = link;}, link);
}`  
Then, you can use `gotourl(my_url)` to go to that url address.

**Comment by kiru00** [comment]
Thank you Sir, 
I tried this way.. I used this function in same file..Its working...
**function gotourl(link) { casper.evaluate(function(link) {window.location.href = link;}, link); }**

Thank you so much...
