### ISSUE TITLE
Using hosted images and python files. 

### ISSUE THREAD

**Issue by pvankralingen** [kelaberetiv/TagUI#333]
I'd like to run a python file using TagUI, but the python file needs to be hosted. 

Using `run py url_that_ends_with_.py` TagUI simply crashes without any output. 

I'm using Windows. 

How can i fix this?

Thanks!

**Comment by Aussiroth** [comment]
Hi, can you check if the src/tagui_py/tagui_py.log file has anything written to it? This can help to determine if there's an error on the python side when trying to run the .py file.

**Comment by Aussiroth** [comment]
Hi, can you check if the src/tagui_py/tagui_py.log file has anything written to it? This can help to determine if there's an error on the python side when trying to run the .py file.

**Comment by Aussiroth** [comment]
Hi, this is a bit unusual since generally TagUI will just wait until timeout occurs even if the run step fails. Can you try doing a TagUI script just with that run step and paste the TagUI log file so I have a better look at the issue? Thanks!

**Comment by pvankralingen** [comment]
Ofcourse :), 

Script: 
`run py https://url.com/subfolder/__main__.py`

The python script: 
` from tkinter import *
window = Tk()
window.title("This window only appears when .py is local")
window.mainloop()
`

This is what i get in my log ( `script.tagui.log`) : 
`START - automation started - Mon Jan 14 2019 11:19:01 GMT+0100 (W. Europe Standard Time)
run py https://url.com/subfolder/script.tagui/__main__.py
FINISH - automation finished - 0.3s`

When placing the python script locally, i can can call the python script from tagui without a problem. 
Log: 
`START - automation started - Mon Jan 14 2019 11:39:02 GMT+0100 (W. Europe Standard Time)
run py C:\Users\user\Documents\bots\python_test\__main__.py
FINISH - automation finished - 9.2s`

Thank you for your time!

**Comment by Aussiroth** [comment]
Hi, seems like the run step with the python execution returns an error quickly, which leads to TagUI quitting shortly in 0.3s. Since the output of the command line from the last run step is stored in the variable `run_result`, you can try adding a `echo run_result` to see the message. I believe in this case python execution from the command line looks to take in a local file, instead of one hosted on the internet.

**Comment by pvankralingen** [comment]
Thank you! 

TagUI actually procudes an error this time, which is the following: 
` [Errno 22] Invalid argument`

I understand that `.py` files can only be called within the local machine. However, for my particular use case this will not be possible (I have a similar problem with visual automation, where the images need to be local).  Can you suggest a workaround for this issue? 

I can imagine a possible workaround would be to download `.py`- and other necessary files first using the download function within tagUI ( similar to the 3_github example) and execute/use them afterwards? 

It would be an extra step, but well worth it.

**Comment by Aussiroth** [comment]
Yup, in this case it sounds like downloading the files first would be the best way to go about this. Usually it wouldn't be too difficult to have TagUI run to download some files. However, if using Chrome, download step is not supported and file downloads need to be done by directly specifying the URL of the file to download as a navigation step. Though with a recent Chrome update preventing headless Chrome from being able to download files and visible Chrome generally rendering plaintext files like a .py file directly in the browser, it may be a bit of a work to get the files to download successfully.

**Comment by kensoh** [comment]
Adding on, another option to experiment using the curl command to download the file. Curl usually comes with Linux / macOS. For Windows, there is a curl command in tagui\src\unx folder.

```
run curl -k -o filename url_to_file
```

**Comment by gjhagens** [comment]
cURL does work fine, but when used within TagUI the known issue of whitespaces within a local path string comes up agin. Escaping the local url using double quotes works for CLI-commands, however not for execution within TagUI.

**Comment by kensoh** [comment]
I see.. I guess that you mean for some reason, the path and filename has to have a space in between. In that case, a workaround of workaround is to write Windows batch file or Linux script to do all that. and then use TagUI run command to execute the script

Yeah the whitespaces things can be a headache but it is part of CasperJS which TagUI is built on. In future perhaps, that  can be changed when the underlying dependencies are re-written.

**Comment by pvankralingen** [comment]
@kensoh A workaround has been found. The `p1 ` variable can be used to give it an hosted folder. Python can take this variable to download all dependencies as a zip file, and unpack it. 

After this the "main" tagui can kick in and do its job and use all the pre-defined source files. Once complete, Python can be used once more to delete all source files, thus completing the circle of automation :).  The only drawback is not being able to use chrome or any other configuration variable.

It turns out TagUI is much more powerful when used with a bit of creativity. 

With thanks to @gjhagens

**Comment by kensoh** [comment]
Cool stuffs @pvankralingen and @@gjhagens ! Config variables like chrome, headless, and other options can still be used. TagUI will treat these known options as options, and the other parameters as parameter variables p1 .. p9.

**Comment by pvankralingen** [comment]
That is excellent news! I must have misunderstood [this](https://github.com/kelaberetiv/TagUI/issues/159#issuecomment-388124272). I assumed the options were ignored as soon as p1 was found. 

I will test this out later, this issue can be closed :)! Thank you for your help @kensoh @Aussiroth .

**Comment by Aussiroth** [comment]
Sounds good! Hope things work out well :)
