### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by SreenijaK** [kelaberetiv/TagUI#334]
what is the syntax for scrolling down/up and scrolling to the top of the page

**Comment by Aussiroth** [comment]
Hi, to scroll to a specific coordinates in the page you can use js in the dom as mentioned by Ken here https://github.com/kelaberetiv/TagUI/issues/198.

Also if you perform a step such as hover (or click) on an element out of view, TagUI should automatically scroll to fit the element into view on the browser.
