### ISSUE TITLE
Cannot find image file when using vision step - vision wait(image.png,30)

### ISSUE THREAD

**Issue by Rampalitham** [kelaberetiv/TagUI#338]
Hi kensoh,

I'm writing a tagui script where I'm integrating Sikuli with tagui, when doing this I'm facing an issue related to wait statement in Sikuli as "vision wait(img.PNG,30) .
My scenario is:
I'm automating a desktop application where I have to wait for the process to complete,after that, I have to check for an img existence & then click Export button which will export the output to a .csv, but the problem here is, sikuli is unable to execute this Vision wait in my code."vision wait(img.PNG ,30)" automation process is not continuing after this step "vision wait(img.PNG ,300)". please let me know is there any other way to do. I have to do it, help me,,,

Thanks in advance.

**Comment by kensoh** [comment]
Hi @Rampalitham you can check the logs in src/tagui.sikuli to see what is the error message. I think the most likely cause may be the filename of the image given. I think default directory is src/tagui.sikuli so if the img.PNG is not there, Sikuli will not be able to find it.

Try typing the full path to the image (examples below for Mac and Windows) and let me know if it helps. If not, check the logs and let me know what error messages are inside.

```
vision wait('/home/automation/img.png',300)
```

```
vision wait('c:\automation\img.png',300)
```

**Comment by kensoh** [comment]
Closing this issue for now as I'm able to use above vision step to wait for an image to appear on the screen. I can do that both by putting full path to the image or by putting image in src/tagui.sikuli folder and specifying just the image filename. I'm using macOS.
