### ISSUE TITLE
User feedback and experience - stop execution halfway, click by x,y coordinates, UTF-8

### ISSUE THREAD

**Issue by workah0lic** [kelaberetiv/TagUI#340]
Dear kenso, 
I stumbled across TagUI and really like working with it! However, I wasn't able to answer couple of questions regarding its functionality:

1) is there a way to stop execution of a workflow (a hotkey or similar)?
2) finding an image with sikuli takes some time - for my use case (clicking a user input field in a browser which can't be selected by xpath [because it's inside a shadow dom element]), I want to find the location of a search-box. Though I can click it with sikuli:
`click search-box.png
`
... unfortunately, I didn't manage to simply receive the X/Y value of it:
`vision getMouseLocation()
`
How can I get the location-values of the found picture? I think finding it once and saving/reusing the exact coordinates would speed up the whole process (instead of searching for the search-box every single time the page refreshs).

3) Is there support for utf8 characters - when I load text from a txt-file, characters like 'é' are not respresented correctly?

Thank you very much!
Best regards, david

**Comment by kensoh** [comment]
Hi @workah0lic glad you enjoy using the tool!

1. you can use Ctrl+C to terminate execution while it is running. for sophisticated repeated automation flows with a specific exit condition, you can implement other ways within the script to decide when terminate to the execution - check existence of web element, image on screen, check a file, API call etc

2. Sikuli execution speed is already pretty fast. You can try changing the scan_period from the default 0.5 seconds in src/tagui.sikuli/tagui.py to be shorter to make the communication frequency between TagUI and Sikuli faster. Specifying X,Y coordinates is not likely to speed things up substantially but you can try. For the coordinates, you can look at the logs in src/tagui.sikuli and you should be able to see the coordinates where the matched image is found. On Linux and macOS you can tail -f tagui.log while on Windows there should be a minimized windows showing contents of tagui_windows.log which you can click to see directly.

3. I am guessing you may be running on Windows? Linux typically handles UTF-8 automatically. For Windows, you can refer to the following example on setting up foreign languages to show up correctly. The link is in the main readme under native languages. http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/
