### ISSUE TITLE
Datatable iterations issue when triggering TagUI with a batch file on a VM

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#342]
raising on behalf of user email

---

I am having a bit of an issue with TagUI and was wondering whether you had faced this issue before – we recently applied a scheduler to run a new script (bat file) on a VM at certain specified timings. The scheduler will reboot the VM and upon start-up triggers the VM to run the TagUI script. However, after one iteration, the TagUI will shut down itself (i.e. it won’t move to 2nd iteration). This strangely does not occur if we trigger the bat file manually.
 
I have looked at the script log file but found no error message. Would appreciate it if you could let me know if there is any other location I can look for troubleshooting purposes.

**Comment by kensoh** [comment]
I looked through the execution sequence inside tagui.cmd (assuming you are running Windows VM). I can only think of 2 possible ways where this can happen.

1. it could be something to do with the datatable csv file location. For some reason, invoking from your batch file to automate running TagUI versus running manually, the current working directory may be different. That could cause TagUI from not being able to find the datatable and not iterate through the datatable. You can try putting full path to the datatable csv file or dig more in this direction if for some reason the working directory to TagUI is different when invoked in the 2 different ways.

2. it could be something to do with setting environmental variables. TagUI has to set environmental variables in order to track the iteration number and loop through the whole set of iterations. If for some reason, invoking automatically though the batch file does not provide a similar DOS command prompt environment like when you trigger the TagUI automation manually. Both both possible causes, it would be hard to tell what is the root cause without actually seeing your setup and debugging there, since TagUI wasn't developed and tested in the setup you mention.

I also want to update that Alvin has ended his contract with AI Singapore in January.. He won't be supporting TagUI issues on GitHub or emails anymore. I'm working with Yara now on automation work in digital farming, but can advise on GitHub issues whenever time permits!

**Comment by kensoh** [comment]
user's reply

---

The TagUI’s own datatable was created with the full iteration list so probably not this issue. My best guess now is probably due to certain Windows permissions or policies (which we have in the hundreds apparently) so it may or may not have been consistently implemented by our Infra guys across VMs. We have two other VMs running TagUI and they have no trouble with the iterations. For now, we have temporarily resolved the issue by adding extra TagUI script run in the bat file but we probably need our Infra guys to look into the permissions to ensure that they are consistently applied.

**Comment by tierzhang** [comment]
Same issue in VMs. Resolved by Windows permission and running the BAT command by admin. If the iteration is dead, reboot the VM and try it again.
