### ISSUE TITLE
TagUI stuck when i use some Sikuli commands (what's the correct Sikuli syntax)

### ISSUE THREAD

**Issue by LZF07** [kelaberetiv/TagUI#345]
Hello, it´s me again :smile: 

I used a sikuli input command and the tag ui freezes
vision ask_result = input("What´s your phone number?")

vision type(paste(ask_result)) 

it does not continue thereafter until the timeout.
Paste correctly and freezes after that, tag ui continues but sikuli seems to close

Thanks :+1:

**Comment by ryzalk** [comment]
Hi @LZF07. Have you checked the logs in src/tagui.sikuli to see what is the error message? I tried the above iteration myself and it seems like the `vision type(paste(ask_result))` is the step that causes Sikuli to freeze.

**Comment by LZF07** [comment]
Hello, @ryzalk . I checked the logs but was empty.
I dont know why my sikuli logs are always empty...
Here´s the message of error, i dont kno how to fi it. This command would be perfect on my code.
:worried: 

![screen shot 02-21-19 at 05 13 pm](https://user-images.githubusercontent.com/11363500/53239914-fb822b00-367b-11e9-80a0-88b1fce965d1.PNG)

**Comment by kensoh** [comment]
Hi @LZF07, adding on, this looks like using Sikuli incorrectly. It looks like you are running custom Sikuli commands using `vision` step, however the commands seem to be in the wrong Sikuli syntax, below links to the type() and paste() methods -

https://sikulix-2014.readthedocs.io/en/latest/region.html#Region.type
https://sikulix-2014.readthedocs.io/en/latest/region.html#Region.paste

I tried below replication script and it works. The wait is for me to click on a target window or somewhere for the type() command to enter the text. You can also use other Sikuli commands like click() or use TagUI `click` step to click on the target textbox.

```
vision ask_result = input("What is your phone number?")
wait
vision type(ask_result)
```

**Comment by LZF07** [comment]
This way solved my problem.
Thank you again!
