### ISSUE TITLE
Interacting with web elements using variables in live mode

### ISSUE THREAD

**Issue by CJohnDesign** [kelaberetiv/TagUI#347]
When I live mode, the following works and checks the box: `click //*[@id="tm_pb_category"]/label[4]/input`

entering `click //*[@id="tm_pb_category"]/label['+group_num+']/input` gives me this error: `ERROR - cannot find //*[@id="tm_pb_category"]/label[4]/input`

I can `echo group_num` and it gives me `4`. 

`click //*[@id="tm_pb_category"]/label[`group_num`]/input` gives me `ERROR - cannot find //*[@id="tm_pb_category"]/label[`group_num`]/input`

Both work when it's ran in the code.

**Comment by kensoh** [comment]
The live mode wasn't designed to support interaction with web elements using variables.

A workaround is to use `dom` step to pass the variable into DOM before using it with the appropriate escape quote, another workaround would be calling the underlying method directly eg `this.click(locator)`

Besides workarounds, it looks like a technically possible feature, can you replace below tagui_header.js in your src folder to see if that works for your various live mode use cases? I'll have to find more time in my personal time to look deeper on potential compatibility issues.

[tagui_header.js.zip](https://github.com/kelaberetiv/TagUI/files/2904482/tagui_header.js.zip)

**Comment by CJohnDesign** [comment]
Excellent, I will test. 

I just wanted to make the note so no one else tries to too long, like I did.

**Comment by kensoh** [comment]
Cool, I don't see why a technically feasible solution shouldn't be implemented. Only catch is need to make sure that it doesn't break backward compatibility for existing use cases. Above patch only handles dealing with normal with locators in live mode with dynamic variables. Later on, if doing that for Sikuli visual automation is also a common use case, then more code changes are needed.

**Comment by kensoh** [comment]
Did some testing and made a PR - https://github.com/kelaberetiv/TagUI/pull/350

- support use of dynamic variables in live mode
- show error message for JS errors instead of exit

Prior to merging, users can download from below, unzip, and replace contents under src folder. The files changed are tagui_parse.php and tagui_header.js, and test/positive_test.signature. Do a backup if you have made your local modifications to code.

https://github.com/tebelorg/TagUI/archive/live_dynamic_variables.zip

**Comment by kensoh** [comment]
Committed to master and closing the issue. Users can download the cutting edge version to overwrite their package installation to use this feature - https://github.com/kelaberetiv/TagUI#set-up

**Comment by kensoh** [comment]
Committed to master and closing the issue. Users can download the cutting edge version to overwrite their package installation to use this feature - https://github.com/kelaberetiv/TagUI#set-up
