### ISSUE TITLE
How to tell TagUI to use xpath from an extension that is desktop based?

### ISSUE THREAD

**Issue by anubhav13103738** [kelaberetiv/TagUI#349]
I have an desktop application and I wrote an extension for it in html css and js. I have its xpath and I want to use TagUI to automate it. When I open the extension it and try to run it through xpath via TagUI it throws an error 

ERROR - cannot find //*[@id="mirror"]

my script is 1 line simple script:
click //*[@id="mirror"]

I don't have any url can I automate such cases?

**Comment by kensoh** [comment]
I assume you mean that you have developed a Chrome extension for your desktop application. I don't think Chrome allows TagUI to control and have access to Chrome extensions' HTML DOM layer.

So your use case won't be possible using TagUI. You can try using the visual automation method to control your Chrome extension visually but you won't have native access to its DOM.

https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by kensoh** [comment]
Closing for now as there are no further inputs for exploration at the moment
