### ISSUE TITLE
Using clipboard to copy and paste data with TagUI

### ISSUE THREAD

**Issue by indruin** [kelaberetiv/TagUI#353]
Hi!

It is possible to use clipboard for paste something saved on it?

If i copy an image and after i want to paste it on a web page, how can do this?

Thanks on advance!

**Comment by kensoh** [comment]
Hi @indruin ! If what you want to do can be done by a normal user copying and pasting with keyboard shortcuts, then it should be possible using TagUI by using `vision` step. See below on how to install Sikuli to enable computer vision automation, and the second link on using complex keyboard shortcuts, for eg to copy and paste data from clipboard.

https://github.com/kelaberetiv/TagUI#visual-automation

https://github.com/kelaberetiv/TagUI/issues/155#issuecomment-397403024

**Comment by indruin** [comment]
OK, thanks by the response.

It can be used on my next scripts.

Please close this thread.
