### ISSUE TITLE
TagUI check radio buttons, elements with changing ID, modifying DOM directly etc..

### ISSUE THREAD

**Issue by fez226** [kelaberetiv/TagUI#355]
Hello @kensoh i need some help. I have a radiogroup on some web page, i need to click a radio button option, but i cant do it with "click" or "select".. or maybe im doing it wrong.
theres the html code:

![image](https://user-images.githubusercontent.com/47187733/54486561-84415080-484f-11e9-9adf-229e8e2cf061.png)

and a example of the radio button

![image](https://user-images.githubusercontent.com/47187733/54486568-9cb16b00-484f-11e9-8e8c-2fdd0ceb3e23.png)

![image](https://user-images.githubusercontent.com/47187733/54486586-bfdc1a80-484f-11e9-817c-fcf55b7592f8.png)

**Comment by fez226** [comment]
i try with the document.getElementById("iCheck-do2pjq").checked = true

but doesnt work

![image](https://user-images.githubusercontent.com/47187733/54486604-f023b900-484f-11e9-8032-0b315f57d952.png)

**Comment by kensoh** [comment]
@fez226 try dom step to run code on the webpage DOM, hope that helps!

dom document.getElementById("iCheck-do2pjq").checked = true

**Comment by fez226** [comment]
Hello @kensoh thanks for you quickly reply, but not lucky.

![image](https://user-images.githubusercontent.com/47187733/54494081-40c10380-489c-11e9-8c42-60bd37db3d37.png)

i try with the XPath but the same result, im doing something wrong?

dom document.getElementByXPath('//*[@id="iCheck-do2pjq"]').checked = true

**Comment by fez226** [comment]
i think i find a reason of the error, every time i run the tagui and open one chrome windows, the label of the radio button change

![image](https://user-images.githubusercontent.com/47187733/54498203-89db7c80-48c9-11e9-8b4f-0f8e4369ab1b.png)



![image](https://user-images.githubusercontent.com/47187733/54498200-7fb97e00-48c9-11e9-8633-fa0e6f1c3eb7.png)

**Comment by fez226** [comment]
i finally have it, if anyone have a similar problem, you need to copy the xpath of the radiogroup:
in this case:
//*[@id="infoFormStep1"]/div[5]/div[1]/p/span
and add the /label[1]/input for the first option /label[2]/input for the second one...

so the next line will click the Yes Radio Button:
click //*[@id="infoFormStep1"]/div[5]/div[1]/p/span/label[1]/input

**Comment by kensoh** [comment]
Cool detective work! Yes some webpages will have new IDs each time you visit, that makes it impossible to locate by ID. Your above method is an elegant solution to the problem.

Another way I saw your screenshot above there is a name attribute. In XPath you can try out using //*[@name = "useOpportunity"] followed by something to locate that radio group.

**Comment by fez226** [comment]
@kensoh i dont know that, we can change the @ID to @NAME or another attribute. But i have a question, both of the radio buttons option name "useOpportunity" (yes and the no option) so how i can selected?
select //*[@name="useOpportunity"] as Y ?? (doesnt work)

i copy both elements to more examples

<input type="radio" aria-required="true" value="Y" name="useOpportunity" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;">

<input type="radio" aria-required="true" value="N" name="useOpportunity" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"> 

![image](https://user-images.githubusercontent.com/47187733/54502144-be156400-48ee-11e9-827b-b175bbe77b3d.png)

**Comment by kensoh** [comment]
You can many things with XPath, any attribute can be used with @attribute_name.

You can do something similar to what you did earlier by layering -
//*[@id="infoFormStep1"]/div[5]/div[1]/p/span/label[1]/input

Something like below, you have to experiment on the webpage -
click //*[@name="useOpportunity"]//label[1]/input

**Comment by fez226** [comment]
im trying, but doesn't work. Actually my first solution at the end doesn't work, because the html code change when finished loading. the Final html code is on my last screenshot. 
I will continue investigating, but any recommendation is grateful

**Comment by kensoh** [comment]
Some other ideas -

- You can also consider adding a `wait` step to ensure webpage completes loading.

- Your previous attempt at the web page using relative paths like below should be a good approach for websites with changing IDs.

//*[@id="infoFormStep1"]/div[5]/div[1]/p/span/label[1]/input

- Lastly, you can consider using the [computer vision automation](https://github.com/kelaberetiv/TagUI#visual-automation) method to interact with the web page radio button.

**Comment by kensoh** [comment]
PS - I forgot to add that if the webpage is a public webpage, you can share with me your replication workflow script so that I can take a look.

**Comment by fez226** [comment]
i see your point, i think sikuli may dont work, because its a lot of radio buttons with Yes or No answers.
Regrettably the webpage is not public.

the next line doesnt work, because when the page is finally load, the html code change and there is no Label but ichecked
//*[@id="infoFormStep1"]/div[5]/div[1]/p/span/label[1]/input

**Comment by fez226** [comment]
![image](https://user-images.githubusercontent.com/47187733/54556642-e9479400-497e-11e9-8f01-673d0326c98a.png)

**Comment by kensoh** [comment]
Anyone of the following works for me for this website. Good luck!

```
http://icheck.fronteed.com/#skins
click //*[@class="iradio_minimal"]
wait
click (//*[@class="skin skin-minimal"]//*[@class="skin-section"]/ul[2]//div)[2]
wait
click (//*[contains(@class,"iradio_minimal")])[1]
wait
```

Below is a useful guide on using XPath from W3School -

https://www.w3schools.com/xml/xpath_intro.asp

**Comment by fez226** [comment]
Hello @kensoh i learned a lot with the w3schools and your example, finally i can click on the "yes" radio buttons with this line
click (//*[@class="iradio_square-blue"]//*[@name="useOpportunity"])

i try for the "no" answer but doesnt work with this:
click (//*[@class="iradio_square-blue"]//*[@name="useOpportunity"])[2]

i try with this one, but there i way to put 2 attributes for one click, something like
click (//*[@class="iradio_square-blue"]//*[@name="useOpportunity"] | [@value="N"])

see the image below to know more about the last line of code

![image](https://user-images.githubusercontent.com/47187733/54633494-e8c60080-4a45-11e9-877a-3edd74591d7b.png)

**Comment by fez226** [comment]
update: for some reason this line of code click the "no" answer

`click //*[@id="infoFormStep1"]/div[5]/div[1]/p/span`

**Comment by fez226** [comment]
i finally have it, i test it with other radio button i check

`//no
click (//*[@id="infoFormStep1"]/div[5]/div[1]/p/span/label[2])
//si
click (//*[@id="infoFormStep1"]/div[5]/div[1]/p/span/label[1])`

its like my first soution but without the /input

anyway, i thank u kensoh for all the help you can give me.. and also the question its on table:

can i click one element with two attributes: 
`click (//*[@class="iradio_square-blue"]//*[@name="useOpportunity"] | [@value="N"])`

**Comment by kensoh** [comment]
yes xpath is very powerful - https://www.w3schools.com/xml/xpath_operators.asp

for example `//*[@class='abc' and @name='xyz']` - see above link for more useful operators 👍

**Comment by fez226** [comment]
oooh excelent i get it now its inside the [] thanks a lot, i try it and works great... so in this issue we see: tagui automation with another xpath that ID, elements that changes, DOM, and operators like /, //, *, and, or... great thanks!

**Comment by kensoh** [comment]
welcome @fez226 and have fun with xpath!

it is the most expressive and powerful way to locate web elements, more powerful than usual css selectors, your time invested to understand it will give great rewards in your automation work.
