### ISSUE TITLE
How to pass complex data input to be used in TagUI?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#358]
Good user question from https://github.com/kelaberetiv/TagUI/issues/159#issuecomment-475204867

---

Hello, quick question. How do I pass a text variable with spaces ?
Say, I want p1 to be 'hello world'.
**demo chrome hello world** - This would take hello as p1 and world as p2 I believe.

Also, is there a way I can pass complex data ? Say arrays, objects etc.

**Comment by kensoh** [comment]
Hey Sarat, not designed to pass in variables with space, but you can use the following method by passing filename of complex input parameters. for eg, assuming data.json contains the data -

`tagui demo_script data.json`

**demo_script**
```
load `p1` to data
echo data
```

**Comment by saratSubramaniam** [comment]
Great, will try this out ! Thanks @kensoh

**Comment by kensoh** [comment]
TagUI context is JavaScript environment under PhantomJS, so you can use normal JS code such as JSON.parse() and JSON.stringify(), or in above case simply save the string as a text file to load and use directly.

**Comment by saratSubramaniam** [comment]
Great, that works 👍
