### ISSUE TITLE
how to pass the variable in exec(open(filename ).read() in tagui

### ISSUE THREAD

**Issue by Shivam095A** [kelaberetiv/TagUI#363]
Hello @kensoh
I am trying to pass variable into exec(open(write_csv.py).read() function to write the value into csv.
i have tried multiple solution but did not work. [e.g. exec() with globals()]

Below is my code in **TagUi** please suggest if there is any way to pass variable.

=============================================================
read /html/body/section[2]/div/div/div[2]/div[2]/div/div[2]/div[2]/div[1]/div[1]/ul/li[1]/h4 to Instrument
read /html/body/section[2]/div/div/div[2]/div[2]/div/div[2]/div[2]/div[1]/div[1]/ul/li[2]/h4 to ratings
read /html/body/section[2]/div/div/div[2]/div[2]/div/div[2]/div[1]/h3 to Company

echo "This is new var = " + Instrument
echo "This is rating = " +ratings
echo "This is Cname" +Company

py_step('Company = "' + Company + '"')
py print(Company)
echo py_result
py_step('Inst = "' + Instrument + '"')
py print(Inst)
echo py_result
py_step('ratings = "' + ratings + '"')
py print(ratings)
echo py_result

py begin
#exec(open(r'C:\TAGUIAPP\write_csv.py' Company Instrument ratings lst ).read())
py finish
==============================================================

**Comment by kensoh** [comment]
Your code above looks correct to pass the variables to Python. But your Python code when using exec and open is wrong. exec() function takes in Python code and run, open() function is to load script.

If you want to run Python script from within Python and pass parameters, you can look at Python os.system function.

If your goal is to save as csv, you can directly in TagUI without going through Python, see here the example using csv_row helper function -

https://github.com/kelaberetiv/TagUI#helper-functions

**Comment by Shivam095A** [comment]
Thanks for your response Kensoh. code is working fine after replacing exec() with below line.

**py subprocess.getoutput(["filename", arg1,arg2,.....])**

**Comment by kensoh** [comment]
Cool stuffs Shivam, thanks for sharing back here!
