### ISSUE TITLE
Click OK on alert/confirm message

### ISSUE THREAD

**Issue by JTravis76** [kelaberetiv/TagUI#364]
Hello, cannot find any example on how to automate the clicking of the OK button of a alert or confirm message. Have a few web pages where it ask a question before submitting to server. This is possible within tagui?

![image](https://user-images.githubusercontent.com/9905282/55019789-e9bddb80-4fcb-11e9-8125-16f0647e717b.png)

**Comment by kensoh** [comment]
Hi Travis, if you know the JavaScript code that can do this ([for example this](https://www.w3schools.com/jsref/met_dialog_close.asp)), you can try doing it using `dom` step. The `dom` step lets you send JavaScript code to be executed on the browser.

If not, you can use the visual automation method to visually click on the OK or Cancel button -
https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by JTravis76** [comment]
Thanks Kensoh. Visual automation seem to be a start, but running into a side effect. In my script, a button is clicked that fires the confirmation popup box. At that point, all code execution is paused (like hitting a breakpoint in debug mode) and will not continue to the next step that would start the visual automation to click either ok or cancel. 

There is probably not a way to execute another script outside the primary thread that would run the visual portion?

If not, may just redesign the web page with a custom confirmation dialog so tagui could answer.

Thanks again for your help.
BTW, this is one of the coolest projects on github.

**Comment by kensoh** [comment]
Thanks Travis for sharing your appreciation! The visual automation, when installed correctly, should work seamlessly within the same script. So all the steps that you need to run can be put in the same script in the order you want to run them. For example - 

```
click web_locator1
click ok_button.png
click web_locator2
...
```

When installed using the setup instructions in the previous link above, TagUI will detect that you are using visual automation and starts the Sikuli process automatically when your automation is started, and will show the following message - `[starting sikuli process]`

PS - for users of visual automation, last night i've added new commits to master that can interact with UI elements by specifying the (x,y) coordinates. for details, see https://github.com/kelaberetiv/TagUI/issues/361 and https://github.com/kelaberetiv/TagUI/issues/365

**Comment by JTravis76** [comment]
Really like the (x,y) feature, saves from having to create bunch a images.

When you get a chance, could you look at this simple example project? To tell when the script pauses is by design or something else going on. The button images is from Chrome.
[visual.zip](https://github.com/kelaberetiv/TagUI/files/3017837/visual.zip)

It seem to work great, when sikuli clicks the Save button, but fails when the DOM executes the Save button.

**Comment by kensoh** [comment]
This is another question where you are trying to click on a web element using its identifier. I can't replicate the issue on my laptop (Chrome v73 / macOS 10.14.4).

When I tried running TagUI with chrome option, both syntax below works and the button gets clicked.

```
click //*[@id="button1"]
click button1
```

![Screenshot 2019-03-29 at 11 31 29 PM](https://user-images.githubusercontent.com/10379601/55243812-e7cd7400-527a-11e9-8e55-a47649fd5868.png)

**Comment by JTravis76** [comment]
I was able to click button1 (Save button) usi g the identifier. Just not able to click the Ok button on popup.

I'm guessing you are not seeing the executed code pauses until I manually click the Ok button. Wonder if my version of chrome has a security flag set. (Chrome 73/ Windows 10). Will do some research. Thanks for looking sample.

**Comment by kensoh** [comment]
No probs Travis, I get what you mean now. I tried running the full sample script and looked at the logs. It looks like when the popup window appears, Chrome immediately halts responding back to TagUI. That becomes blocking to TagUI. Thus TagUI is still looping to get the response of the click to confirm whether it has been successfully received and processed by Chrome, before continuing execution.

I don't have any straightforward solution on this. One way I can think off is setup another instance of TagUI in another directory, and concurrently run both scripts using something like `start /min cmd /c` in a batch file. That way, both processes exist independently and the visual automation process won't be blocked by the process waiting for response from Chrome. But this may not be robust to pull off, due to potential timing issues and added complexity not designed and tested for.

**Comment by fez226** [comment]
Hello @JTravis76 try with Tampermonkey extension for Chrome, and create the next script, so when the tagui arrive to the section of the "ok buttom" the script will automatically press the ok button, 

just put a wait on tagui....

`// ==UserScript==
// @name        Example of Ok buttom alert
// @match       https://yourwebpage.com/*
// @run-at      document-start
// ==/UserScript==

addJS_Node (null, null, overrideSelectNativeJS_Functions);

function overrideSelectNativeJS_Functions () {
    window.confirm = function alert (message) { return true; }
}

function addJS_Node (text, s_URL, funcToRun) {
    var D = document;
    var scriptNode = D.createElement ('script');
    scriptNode.type = "text/javascript";
    if (text) scriptNode.textContent = text;
    if (s_URL) scriptNode.src = s_URL;
    if (funcToRun) scriptNode.textContent = '(' + funcToRun.toString() + ')()';

    var targ = D.getElementsByTagName ('head')[0] || D.body || D.documentElement;
    targ.appendChild (scriptNode);
}
//var oldConfirm = window.confirm;
 //   window.confirm = function (e) { return true };`

**Comment by JTravis76** [comment]
Hi @fez226 , thanks for sharing Tampermonkey. Never heard until today. Definitely keep in my toolbox.

Using the visual automation seem to work the best in my situation. Anytime a button triggers a pop-up box, I just use the sikuli process to jump that hurdle. Lucky, there is not too many :)

Thanks again @kensoh for all your help.

**Comment by kensoh** [comment]
Cool hack @fez226! That's a good idea. Building on the idea, another elegant alternative is using the `dom` step to override the window.confirm function on the browser's DOM context. For example, below will cause the pop-up to be closed automatically after the click is executed - 

```
dom window.confirm = function alert(message) {return true;}
click //*[@id="button1"]
```

**Comment by fez226** [comment]
Hello @JTravis76 i use TamperMonkey for one reason: is faster than sikuli (visual automation). I will try the 
`dom window.confirm = function alert(message) {return true;}
click //*[@id="button1"]`

**Comment by shahidshaikhleaque** [comment]
Hi @kensoh I tried visual automation by using sikuli and captured images of both dialog box and ok button.
First I hovered on the dialog box to gain the focus then click on ok
vision hover("dialog_box.png")
vision click("Ok_btn.png")

However I saw one more console window is waiting for user input so could not able to move furthur to gain focus. Could you please help how could I focus on dialog box to hit ok button

**Comment by kensoh** [comment]
Hi @shahidshaikhleaque when the browser has a popup, the control will not be returned back to TagUI until user clicks OK. The only workaround I'm afraid is to use visual automation. Use that to click on the browser button that triggers the popup dialog box, after that use that to click OK. After that you can do the normal web identifier stuffs. See below issue for example -

https://github.com/kelaberetiv/TagUI/issues/491

**Comment by mapall** [comment]
Maybe it is written somewhere but I had a similar issue and the problem was that I had two displays and it "looks" only at the main display.

**Comment by kensoh** [comment]
Hi @mapall, by design, TagUI automates the primary monitor. A quick workaround is dragging your taskbar to the monitor that you want to automate visually on. I believe on Windows system, that will assign that as the default monitor. Using `vision` step is another way but need to write custom instruction, the example is in issue #285 below.

Some related issues - https://github.com/kelaberetiv/TagUI/issues/405 and https://github.com/kelaberetiv/TagUI/issues/285

**Comment by sairamphp** [comment]
Hi I'm unable to click the ok button using TagUI
![image](https://user-images.githubusercontent.com/31532092/125049783-f4c6a800-e0be-11eb-849e-7428db07723a.png)

**Comment by kensoh** [comment]
Hi @sairamphp oh this type of popup is a blocking process, only after user clicks then browser will return control to TagUI.

A workaround is using computer vision to trigger this popup (eg click image.png on something that will open this), then use computer vision again to click on this button (eg click ok.png). You can capture the snapshot using snipping tool or use the Microsoft Word plug-in at https://github.com/kelaberetiv/TagUI/blob/master/src/office/README.md
