### ISSUE TITLE
New keyboard step for advance keyboard entries and modifiers

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#370]
Building on the series of enhancements around Sikuli integration #368, #361 and #365 for greater control of mouse, creating and sending a PR that adds a new `keyboard` step. This step lets user send low-level keyboard keystrokes to the operating system user interface, including the special keys and modifier keys. Normal letter characters and numbers can also be entered.

Prior to this, users can only use 1. `type page.png as text` and limited to [enter] and [clear], or 2. use `vision` step to send custom commands to perform complex keyboard actions. Below are some examples.

**macOS**
```
keyboard [cmd][space]
keyboard safari[enter]
keyboard [cmd]c
keyboard [cmd]v
keyboard testing 123
```

**Windows**
```
keyboard [ctrl][home]
keyboard [printscreen]
keyboard [ctrl]c
keyboard v[ctrl]
keyboard testing 456
```

List of modifier keys - [shift] [ctrl] [alt] [cmd] [win] [meta]
List of special keys - [clear] [space] [enter] [backspace] [tab] [esc] [up] [down] [left] [right] [pageup] [pagedown] [delete] [home] [end] [insert] [f1] .. [f15] [printscreen] [scrolllock] [pause] [capslock] [numlock]

**Comment by kensoh** [comment]
Committed to master. Prior to packaged release, feature available from cutting edge version here -

https://github.com/kelaberetiv/TagUI#set-up

**Comment by maheswarGR** [comment]
keyboard [enter] is not working in tagui script

**Comment by kensoh** [comment]
Thanks @maheswarGR for raising this, I've replied to #1171
