### ISSUE TITLE
Close / Exit a browser after running

### ISSUE THREAD

**Issue by Hassan-Ali123** [kelaberetiv/TagUI#391]
I want to close/exit the browser after all processing. Can someone help me how to do this in tagui??

**Comment by Hassan-Ali123** [comment]
Please reply fast....

**Comment by kensoh** [comment]
Hi Hassan, by default, TagUI closes the browser session after running. For example when you do `tagui samples\1_yahoo chrome` it will launch Chrome to run and closes it after running.

If you are using [visual automation](https://github.com/kelaberetiv/TagUI#visual-automation) to visually control an existing browser session, then you can add a step to click on the close button of the browser.

**Comment by Hassan-Ali123** [comment]
Ok. Thanks for the help. I have one more issue: I want to login to a specific site with  my credentials. If I have the credentials stored in a specific file & I want to extract those & type in username & password fields, how can I do this with tagui?? Please all suggestions are appreciated.

**Comment by Hassan-Ali123** [comment]
Credentials are stored in a text file. Although there's a  'load' command that can store filename in a variable, but I want to extract the credentials & type in the respective fields.

**Comment by kensoh** [comment]
Create a new issue next time since different question, so other users can find answer easily.

Created #393
