### ISSUE TITLE
Multiple bots handling in tagui / running multiple flows in parallel

### ISSUE THREAD

**Issue by Hassan-Ali123** [kelaberetiv/TagUI#402]
Hi! I want to know that is there any functionality in TagUI so we can handle multiple bots concurrently, like in UiPath?? Looking for +ve comments

**Comment by kensoh** [comment]
TagUI isn't tested and designed to run multiple scripts in parallel. Though I have tried running on my MacBook Air 2014 model without problem for 4 scripts concurrently in default mode (PhantomJS).

If you use Chrome mode, you can try installing TagUI into different directories and try if that works. Using the same TagUI installation in the same directory probably won't work as the Chrome connections from different scripts will interfere with one another.
