### ISSUE TITLE
Concept of methods, modules and functions in TagUI

### ISSUE THREAD

**Issue by pallavkrishna** [kelaberetiv/TagUI#407]
Hi 
it is possible to segregate my total code to methods and execute them so that i can achieve code re usability

**Comment by bewilderedness** [comment]
Hello @pallavkrishna , this may help with your question:

It looks like there is a way to call other tagui files using the `tagui` keyword and a file path. 

https://github.com/kelaberetiv/TagUI/issues/80

**Comment by kensoh** [comment]
Yes what @bewilderedness shared is the best way to do modular scripting in TagUI. More details in modules section of documentation - https://github.com/kelaberetiv/TagUI#modules

Also, if the methods you are talking about is a collection of custom JavaScript functions, you can create local and global JS functions using tagui_local.js and tagui_global.js. More details here - https://github.com/kelaberetiv/TagUI#helper-functions

Lastly, for reusability of object locators, be sure to check out object repository feature of TagUI where you can define reusable local and global object definitions for use in your scripts - https://github.com/kelaberetiv/TagUI#repositories
