### ISSUE TITLE
How to launch a URL from variable 

### ISSUE THREAD

**Issue by pallavkrishna** [kelaberetiv/TagUI#408]
https://www.google.com
//some actions
newUrl="www.gmail.com"
https://'+url+' - is what I am currently using

i need know , how to launch the content present in the variable(newUrl) can you help

**Comment by bewilderedness** [comment]
https://github.com/kelaberetiv/TagUI/issues/236#issuecomment-403188526

Shows a solution. You will need to add a custom function, but it is fairly straightforward.
