### ISSUE TITLE
How to use variable in "popup" command, if not any workaround?

### ISSUE THREAD

**Issue by wilderchen** [kelaberetiv/TagUI#409]
It's ok when I use the following command:

popup 5178589
{
   echo url()
}

However when I try to use variable in popup command it failed:

x = 5178589
popup \`x\`
{
    echo url()
}

**Comment by wilderchen** [comment]
What's more, are there any commands for us to close the new tab?  

Thanks
@kensoh

**Comment by bewilderedness** [comment]
Did you try to run it with the quotes around the x like 'x'? 

I think that would turn it into a string as opposed to a variable.

**Comment by bewilderedness** [comment]
Re: tab closure-- 

I believe per [391](https://github.com/kelaberetiv/TagUI/issues/391), the browser should auto-close after a successful run.

**Comment by wilderchen** [comment]
> Re: tab closure--
> 
> I believe per [391](https://github.com/kelaberetiv/TagUI/issues/391), the browser should auto-close after a successful run.

Hmmm, I mean I want to close the new tab only. It's not the whole browser.

**Comment by bewilderedness** [comment]
https://github.com/kelaberetiv/TagUI/issues/164#issuecomment-392333545

The above addresses directly tab closure. Unless something has recently changed, it doesn't seem feasible given security restrictions on Chrome. Apologies my first response was not specific enough.

**Comment by wilderchen** [comment]
> [#164 (comment)](https://github.com/kelaberetiv/TagUI/issues/164#issuecomment-392333545)
> 
> The above addresses directly tab closure. Unless something has recently changed, it doesn't seem feasible given security restrictions on Chrome. Apologies my first response was not specific enough.

Thanks, I see. It seem it need to use the OS command to kill the new tab process.
What's more, do you have any idea to use variable in popup command? After debugging into the source code, I found the variable is parsed as:

/'+x+'/

it's a wrong regex expression in javascript. Even though I can change the parse script from  "/'+x+'/" to "Regex(x)", it will raise the exception that it couldn't find out the variable "x".

**Comment by bewilderedness** [comment]
Interesting... The following worked for me in the popup command:

In your test code, you're using backticks instead of single quotes? 

x = 5178589
popup `x`
{
echo url()
}

[Imgur Example](https://imgur.com/7lIDMvh)

**Comment by wilderchen** [comment]
> Interesting... The following worked for me in the popup command:
> 
> In your test code, you're using backticks instead of single quotes?
> 
> x = 5178589
> popup `x`
> {
> echo url()
> }
> 
> [Imgur Example](https://imgur.com/7lIDMvh)

![image](https://user-images.githubusercontent.com/28138033/56631088-5b9a4b00-6686-11e9-9b22-01a3ffe8ec0a.png)


Actually the log on the terminal doesn't mean the real thing happens on the real world. It's just a log to show what the variable value is.

If you want, you can take a deep look into the "1_test.js" file. It will tell how it works actually.

**Comment by bewilderedness** [comment]
Yeah--- you're right.

It looks like there needs to be a change in the tagui_parse.php file

```
"casper.waitForPopup(/".preg_quote($params)."/, function then() {},\n".
```

should become

```
"casper.waitForPopup(RegExp(".preg_quote($params)."), function then() {},\n".
```

**Comment by wilderchen** [comment]
> ```
> "casper.waitForPopup(RegExp(".preg_quote($params)."), function then() {},\n".
> ```

Actually this one won't work as what we expect, since it will raise an exception that it can't find the $params what we have defined.

**Comment by kensoh** [comment]
Thanks @wilderchen for raising this and @bewilderedness for digging into it and sharing your findings!

For compatibility with CasperJS (which TagUI is built on), regex syntax is chosen in TagUI's implementation and it does not take in variables. CasperJS reference - http://docs.casperjs.org/en/latest/modules/casper.html#waitforpopup

Technically it should be possible to implement variables for popup step, as JavaScript supports that, but for above reason that is not supported - https://stackoverflow.com/questions/494035/how-do-you-use-a-variable-in-a-regular-expression

A possible solution is finding other strings that are static in the popup URLs and use that instead. I think you are trying to do that when you asked about closing new tabs. Eg open 1 new tab, interact with new tab, close new tab, repeat.

To close a new tab, you can use popup step with dom window.close() to close it. For eg - https://github.com/kelaberetiv/TagUI/issues/411
