### ISSUE TITLE
Accessing a dynamic link or web element with changing IDs

### ISSUE THREAD

**Issue by fez226** [kelaberetiv/TagUI#410]
Hello @kensoh, i hope you'r fine

i need to download a pdf file from a web page, but its not a button, its a link.

![image](https://user-images.githubusercontent.com/47187733/56770289-ccb62d00-6770-11e9-892a-6a57fa09c8d7.png)

but the link depends of the SAP QUOTE NUM that i put it before it, so the link change every time

this is the element of two examples

>  style="text-decoration: underline;" href="quotePartner.wss?jadeAction=DOWNLOAD_ATTACHMENT&amp;downloadType=quoteOutput&amp;sapDocId=C553F4F4E1171EE996F328ABAEB50C96&amp;outputName=Channel Bid Notification PDF&amp;sapQuoteNum=0018332117">
																		Download now
																	</a><a

> style="text-decoration: underline;" href="quotePartner.wss?jadeAction=DOWNLOAD_ATTACHMENT&amp;downloadType=quoteOutput&amp;sapDocId=C554242436EB1EE996CB52EC523A87F9&amp;outputName=Channel Bid Notification PDF&amp;sapQuoteNum=0018330961">
																		Download now
																	</a><a

as your can look the are the same link but change the sapDocId=xxxxxxx

how can i download the pdf file dinamically?

i can't do: `read element to mypdf` because the result is "Download Now"

if i copy the xpath : `//*[@id="ibm-content-main"]/div[3]/div/div/table/tbody/tr[2]/td[3]/a`

![image](https://user-images.githubusercontent.com/47187733/56771805-f5d8bc80-6774-11e9-84a3-89c4af449934.png)

if I could save `@href` in a  .txt file   it would be perfect

**Comment by fez226** [comment]
doesn't work Sikuli for me because i use Headless Mode

**Comment by kensoh** [comment]
Hi @fez226 thanks for raising this and sharing your findings! Adding on 2 comments -

1. you can use something like below to get href attribute of web element, where //*[text() = "ABOUT"] is the element you are interested in and about_href is the variable to store the value -
`read //*[text() = "ABOUT"]//@href to about_href`

2. to access a URL by specifying a variable, you can try using https://\`variable_name\`

**Comment by fez226** [comment]
that what i need it @kensoh 

`read //*[@id="ibm-content-main"]/div[3]/div/div/table/tbody/tr[2]/td[3]/a//@href to about_href`

**Comment by kensoh** [comment]
opening issue for time being for users visibility
