### ISSUE TITLE
Not selecting the right element (use XPath or give a more specific element identifier)

### ISSUE THREAD

**Issue by kemelzaidan** [kelaberetiv/TagUI#415]
I've been doing some tests with TagUI but the first one I did simply didn't work. The tests consist only on opening packet pub web page and logging in but TagUI simply doesn't type the password on the right element. Here is the script:

```
https://www.packtpub.com/packt/offers/free-learning/
click .login-popup .float-left
type email as kemelzaidan@gmail.com
type password as passwordhere
click edit-submit-1
```
The password is always typed on the email input element, right after the email. Using the XPath as the selector results on the same behavior. Am I doing something wrong or is it a bug?

**Comment by kensoh** [comment]
Probably password as the selector is not specific enough. Below shows the order of selectors TagUI uses - https://github.com/kelaberetiv/TagUI#steps-description In general use something as specific as possible while balancing with natural language readability.

It depends on the user's comfort level to give something very specific that breaks easily if something changes, or something more generic which may still work with minor website changes.

You can try running in live mode to test and debug which selector works, right-click element in Chrome DevTools to copy XPath (https://github.com/kelaberetiv/TagUI#find-xpath-of-web-element), or search in Chrome DevTools interface to make sure it's not a duplicate.

When I copy the XPath returned is //*[@id="password"] and it works.

**Comment by kensoh** [comment]
Adding on, the live mode can be started with the `live` step.

**Comment by Hassan-Ali123** [comment]
Hi @kensoh, I am scraping an html table that is spanning multiple pages. I want to extract the table into a datatable and then load this datatable in a csv file. Please guide how can I do this in tagui??

Thanks again and please reply as soon as possible

**Comment by Hassan-Ali123** [comment]
Please reply to my post as soon as possible! I need help in it

**Comment by kensoh** [comment]
You can try the table step and provide the XPath of the table. This only works for simple HTML tables, some tables have merged cells which will not work with this step. If multiple pages, you have to google and write your own JavaScript code to append the different CSV files.

**Comment by Hassan-Ali123** [comment]
Thank you so much. I shall try this. Please try to reply the query as soon as possible. Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kensoh** [comment]
I'm away from work and no estimate of when I will be back - https://github.com/kelaberetiv/TagUI/issues/804

You can try raise a new issue with your sample script and website so other users can advise -

**Comment by Hassan-Ali123** [comment]
Ok no issue. Actually I asked this because I was in an issue last month so needed your help. But next time I shall create new issue

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
