### ISSUE TITLE
Using visible() function with computer vision, loop and python block usage

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#416]
I'm having problems when I try to use visible and python blocks in a loop

//this code block does not work

```
for (i=0;i<1024;i++)
{
  if visible('system/images/trending.png')
  {
	break;
  }
  
  py a = "Hello"
  py  print (a)
  echo py_result
  
}
```

//this code block is working properly
```
for (i=0;i<1024;i++)
{
 
  py a = "Hello"
  py  print (a)
  echo py_result
  
}
```

Thank you in advance for your support

**Comment by kensoh** [comment]
Hi Murat,

I think the issue happens for an uncommon use case where visible() is used for computer vision automation but there are no other visual automation steps in the script.

TagUI checks for visual automation requirements in the steps to decide whether to launch SikuliX for computer vision. Something like the following may work for you. The click step lets TagUI invoke SikuliX engine to handle the computer vision capability in visible() function -

```
click system/images/trending.png

for (i=0;i<1024;i++)
{
  if visible('system/images/trending.png')
  {
	break;
  }
  
  py a = "Hello"
  py  print (a)
  echo py_result
  
}
```

**Comment by muratcim** [comment]
thanks for your support kensoh

the method you're saying works
