### ISSUE TITLE
Scroll Element into View

### ISSUE THREAD

**Issue by ShwetaChahan** [kelaberetiv/TagUI#419]
Hello

I have a upload element in the page. I want to upload a file, but the functionality does not happen as the element is not in view. 

Is there any way i can scrollElementInto  View.

I do see there is a method in TagUI_header file. Is there a way to call it in the TagUI script

Thanks,
Neha

**Comment by kensoh** [comment]
TagUI automatically scroll the element into view before clicking or hovering on it. You can try using `hover selector` to scroll the element into view and see if that works for this website.

Calling `chrome.scrollIntoViewIfNeeded(selector);` works but it is easier to use `hover` step.

**Comment by ShwetaChahan** [comment]
Does not work for me. The problem i have to keep scrolling multiple times to the bottom of the page and then the element loads.

Any suggestions

**Comment by kensoh** [comment]
Chrome cannot scroll to an element that is not yet loaded. Try this and maybe combine with wait step to scroll a few times to bottom of the webpage. https://github.com/kelaberetiv/TagUI/issues/198#issuecomment-394164409

More details on this JavaScript code here - https://www.w3schools.com/jsref/met_win_scrollto.asp

**Comment by ba700113** [comment]
am using the code below to scroll down a windows service page on my desktop and its not working.
how can i scroll down a page on a desktop. not a webpage.

vision type(Key.PAGE_DOWN)

**Comment by kensoh** [comment]
Replying at the new issue you've raised - https://github.com/kelaberetiv/TagUI/issues/588

**Comment by Hassan-Ali123** [comment]
Hi! I am also facing the same issue. TagUI is not scrolling down the chrome window on my system. I have installed TagUI and SikuliX. Then why this is happening?

Thanks for the suggestions

**Comment by kensoh** [comment]
First try using the hover step on the element, TagUI should try to scroll it into view. You can try testing in Chrome Inspector the XPath to check if the identifier you provide is correct, or in TagUI live mode to try to click it.

For SikuliX automation, check that you have set up the steps here -
https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by soorejmg** [comment]
Hi Kensoh,
I have one page where the element only loads when we scroll down. What needs to be done in that case? I am initialising tagui in Python code and then calling t.fucntions()

**Comment by kensoh** [comment]
Hi @soorejmg for RPA for Python, raise issues over there as it is a separate personal project - https://github.com/tebelorg/RPA-Python/issues

If the element does not show up, you can't use any of the step to automatically scroll to it and interact with it. There are 2 solutions.

First solution is use the dom() function to tell browser to scroll down, for eg below will scroll down by 1000 pixels. So you just scroll accordingly for the element you need.

```
r.dom('window.scrollBy(0, 1000);')
```

Second solution is use the visual automation method to use keyboard keys to scroll down on the browser. [See examples](https://github.com/tebelorg/RPA-Python#use-cases) on how to use visual automation method. To use this method, make sure to click somewhere on the browser first using visual automation to ensure that browser is the active window.

```
r.keyboard('[down][down][down][down][down]')
r.keyboard('[pagedown]')
```
