### ISSUE TITLE
How to reference url() and elements on a new tab

### ISSUE THREAD

**Issue by ShwetaChahan** [kelaberetiv/TagUI#421]
Unable to switch to popup window

Code used : Wherein CustomerService is the text present in the URL 
popup CustomerService
{
	wait 5	
	echo url()
}
url shown is the parent window url and the new tab opened. Please let me know, if the syntax does not look okay

**Comment by kensoh** [comment]
`popup` step and syntax is correct, but I am unable to replicate your error. Below example works for me. You can try using something that is unique to the URL in popup tab and not in parent tab.

```
http://tebel.org
click ABOUT
popup about_tebel
{
wait 5
echo url()
}
```

```
START - automation started - Thu May 09 2019 02:09:14 GMT+0800 (+08)
http://tebel.org - Tebel.Automation

click ABOUT
popup about_tebel
wait 5
http://tebel.org/gist/about_tebel

http://tebel.org/ - Tebel.Automation
FINISH - automation finished - 10.5s
```
