### ISSUE TITLE
Read Email using Gmail API

### ISSUE THREAD

**Issue by ShwetaChahan** [kelaberetiv/TagUI#422]
I am trying to read mail using Gmail API with python. I try to place the entire code in 
py begin 

py finish , but i am unable to execute it. The python file, i am able to execute separately and it works perfectly fine
Please advise

**Comment by kensoh** [comment]
It's hard to advise when there is no replication steps or sample script to look at.

If your Python script works fine, then just use run step to let TagUI run your Python script. You can save email contents in a text file using TagUI write or dump step, then from your Python script load from the text file to process and send the email.
