### ISSUE TITLE
Audit and Reporting - updating check() status in tagui_report.csv

### ISSUE THREAD

**Issue by ShwetaChahan** [kelaberetiv/TagUI#426]
tagui_report.csv  does not check for validations. Ex : if there is a check condition which is failed, then the "Error Status" is still Success in the csv file.

Is there any way to update the check condition result in tagui_report.csv file.

**Comment by kensoh** [comment]
For the audit and reporting feature below saving to tagui_report.csv, it only tracks errors of failure when automation execution encounters missing web elements.

https://github.com/kelaberetiv/TagUI#audit--reporting

check step does not fail and stop automation halfway thus it is not designed to be shown in tagui_report.csv. a workaround is you can intentionally break an automation by making it fail base on some condition.

```
check some_condition | 'yes message' | 'no message'

if some_condition
click some_condition
// eg click number_of_icons_more_than_20
```

**Comment by ShwetaChahan** [comment]
Okay, Thanks
