### ISSUE TITLE
read attribute value

### ISSUE THREAD

**Issue by ShwetaChahan** [kelaberetiv/TagUI#427]
How do i read the attribute value?

Ex :
<th title="abc"></th>

I wanted to find out the position at which the colName exists in the table.

**Comment by kensoh** [comment]
This is an XPath question, to access attributes use `XPath/@attribute_name`. Eg -

```
http://tebel.org/index_mobile.php
show //*[text()="ABOUT"]/@href
```

**Comment by kensoh** [comment]
Output for above script will be below, the @href attribute value -

```
gist/about_tebel
```

Also, `present('//*[text()="ABOUT"]/@href')` will be true or false depending if attribute exists.

**Comment by kensoh** [comment]
Adding on an example from https://github.com/kelaberetiv/TagUI/pull/520 -

First, by using XPath and ending the XPath with `/@attribute`. Second, this can be retrieved using the dom step by querying that web element's attribute directly. Below shows both ways trying to retrieve the class attribute of the search bar in Google webpage.

The type step is to confirm that the identifier used for the search bar is correct. Both will show the class attribute correctly. For my browser and region, it shows `gLFyf gsfi`.

```
https://google.com
type //*[@name="q"] as 123
read //*[@name="q"]/@class to element_class
echo element_class
```

```
https://google.com
type [name='q'] as 123
dom return document.querySelector('[name="q"]').getAttribute("class")
echo dom_result
```
