### ISSUE TITLE
How to use variables in place of text in TagUI steps?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#428]
user query from #190

---

username = "DEVELOPER"
type user.png as '+username+'[TAB]

I guess this should be correct?

**Comment by kensoh** [comment]
Yes that's correct, now there's an improved way to use variables with backticks `, you can do -

```
username = "DEVELOPER"
type user.png as `username`[TAB]
```

There are more examples in flow samples and this is also mentioned in readme document.

**Comment by juan-sanclemente** [comment]
Hi Kensoh 
I have a similar problem: I am trying to fill data in a website with data extracted from Excel file;  I defined as variable the name of the  column  (header), but when I execute the flow, it uses always the name of the variable like argument
I attach the flow for your help

[https://pospopuli.minsalud.gov.co/PospopuliWeb/paginas/home.aspx]()
click .second #login
click EspacioContenido_txtBusqueda
type EspacioContenido_txtBusqueda as ‘medicamentos’[enter]
click EspacioContenido_btnBuscar
click //a[@id="EspacioContenido_lstDatosGenerales_HyperLink1_0"]
click .secondModule > div:nth-child(2)

Thanks for your colaborration 
Regards
Juan Carlos

**Comment by juan-sanclemente** [comment]
[https://pospopuli.minsalud.gov.co/PospopuliWeb/paginas/home.aspx]()
click .second #login
click EspacioContenido_txtBusqueda
type EspacioContenido_txtBusqueda as ‘medicamentos’[enter]
click EspacioContenido_btnBuscar
click //a[@id="EspacioContenido_lstDatosGenerales_HyperLink1_0"]
click .secondModule > div:nth-child(2)
