### ISSUE TITLE
How to control and select calendar dates in a desktop application

### ISSUE THREAD

**Issue by LakshmyNair** [kelaberetiv/TagUI#429]

**Comment by LakshmyNair** [comment]
Dear Ken Soh,
I am trying to access the calendar from a desktop application and select particular dates for my automation project. Is there any solution for that using TagUI? The date's position will keep changing according to the month and how to tell TagUI to go to current date and then select the date, two days ago? Please suggest an alternative otherwise.
Thanks,
Lakshmy.

**Comment by kensoh** [comment]
Hi Lakshmy, your best bet would be using visual automation method. By specifying images of desktop applications UI elements, you can instruct TagUI to click and interact with them. Some ideas would be using mouse_x() and mouse_y() functions and increment to interact with some other buttons, or sending custom keyboard entries directly to the screen to type the date.

More details here - https://github.com/kelaberetiv/TagUI#visual-automation

If all else fails, then some other tools like AutoHotKey, other desktop test automation frameworks, or perhaps some commercial RPA software would be a better solution for this use case.

**Comment by nupurmodi** [comment]
How to select date from datepicker in a website?

**Comment by kensoh** [comment]
For web apps, using XPath is the best option.

**Comment by SnehaGhatkar** [comment]
For selecting date from DatePicker in website there is no Xpath and the textbox for date is readonly

**Comment by kensoh** [comment]
Without XPath (I think all web elements have their XPath, unless the calendar control is some special unique control) you can try using visual automation method, but I don't think that will work well. You can explore other automation solutions and please share your findings here if you found a solution for your use case.
