### ISSUE TITLE
How to change web browser resolution or make it full screen?

### ISSUE THREAD

**Issue by kishorer1290** [kelaberetiv/TagUI#432]
Hi Ken,

One more issue, I have come across. Sometimes, when my application open, it is not open in full size, it is open in minimized: a smaller screen. Is there any way to open the browser in maximized position.

Thank so much in Advance 
Kishore

**Comment by kensoh** [comment]
Hi Kishore, if your application is a web app, you can change the default browser resolution in tagui/src/tagui_config.txt. More details here - https://github.com/kelaberetiv/TagUI#set-up

If your application is a desktop application, you can consider using visual automation to click on the maximise button after launching desktop app to always make window maximise.

**Comment by ShwetaChahan** [comment]
Thanks

**Comment by kishorer1290** [comment]
Thank you Ken. The solution works
