### ISSUE TITLE
Check text inside js alert/confirm/prompt box

### ISSUE THREAD

**Issue by nupurmodi** [kelaberetiv/TagUI#433]
How to check message in javascript alert box/confirm box and click ok/cancel according to that?

**Comment by muratcim** [comment]
Hi nupurmodi 

I don't know how to do this in javascript, but you can do it with sikulix commands

sample code

```
vision begin
ask_res = popAsk("Are You Sure ?","Ask Message")
tagui_text = open('tagui.sikuli/tagui_sikuli.txt','w')
tagui_text.write(str(ask_res)); tagui_text.close()
vision finish
result = fetch_sikuli_text() == "True" ? true:false
echo result
```

For more detailed information about sikulix PopUps and input dialogs, visit [](https://sikulix-2014.readthedocs.io/en/latest/interaction.html)

**Comment by nupurmodi** [comment]
Thanks  @muratcim 
It works but my problem is that i want to interpret message from a website which shows alert / confirm while form validation and sure to submit form or not. I wantedto make testcases for a website that's why.

**Comment by muratcim** [comment]
Hi @nupurmodi 

Okay, I got the problem.I think this can be done with vision steps
I created a sample code below.I hope this helps you

```
https://www.jquery-az.com/javascript/demo.php?ex=151.0_1

click button.png

if present('message.png')
{
    keyboard [enter]
    echo "This is a simple JavaScript alert!"
}
else
{
  echo "Aletr box not found"
}
```

![button](https://user-images.githubusercontent.com/28947111/58161989-f9833480-7c89-11e9-8b20-cfe290c81df6.png)
![message](https://user-images.githubusercontent.com/28947111/58161990-f9833480-7c89-11e9-9420-9c0b10dc62ef.png)

**Comment by kensoh** [comment]
Interesting sharing @muratcim! Adding on that I don't think there is a way to access the popup message by webpage DOM using dom step or other TagUI steps.

Using visual automation is a great idea. It can also be combined with clicking onto the popup box, sending key strokes to select all text and copy and access from Env.getClipboard() within the vision block in @muratcim's example.

**Comment by nupurmodi** [comment]
Thank You @muratcim and @kensoh
