### ISSUE TITLE
Running TagUI-generated CasperJS script with casperjs fails

### ISSUE THREAD

**Issue by sachin1004** [kelaberetiv/TagUI#435]
Run tagui scriptName chrome test. New js file is generated, running casperjs test "scriptName" does not run script.

**Comment by kensoh** [comment]
This is expected, TagUI is built on CasperJS and PhantomJS and generates a CasperJS-like script to run automation. However TagUI does other work in the background such as communicating and integrating with Chrome, Python, SikuliX etc, and other stuffs such as data tables and auditing / reporting.

These capabilities are not in CasperJS. Thus a .js script generated by TagUI thus can't be run and not designed to be run by `casperjs`.
