### ISSUE TITLE
How to pass variables using dom step to browser DOM?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#436]
user query from https://github.com/kelaberetiv/TagUI/issues/414#issuecomment-494248402

**Comment by kensoh** [comment]
TagUI JavaScript environment is separate from the web browser JavaScript environment (also known as DOM, Document Object Model environment). This is by design and for security, otherwise variables and data access across the 2 environments will be breached and also results in conflicts.

To pass variable(s) using dom step, use `dom_json`. More details in [documentation under pro steps](https://github.com/kelaberetiv/TagUI#steps-description) -

>As TagUI default execution context is local, to run javascript on webpage dom (eg document.querySelector) use dom step. Set dom_json variable to pass a variable for use in dom step. Or dom_json = {tmp_number: phone, tmp_text: name} to pass multiple variables for use in dom step (dom_json.tmp_number and dom_json.tmp_text).

**Comment by saketlopes** [comment]
Hello 

I used DOM step for user name / password so it will not display in log files like html.
user name / password stored in tagui_local.csv

_dom document.querySelector("#UserName").value = "`arba_uid`";
dom document.querySelector("#Password").value = "`arba_pwd`";_

Regards
Saket Lopes

**Comment by kensoh** [comment]
This is good info-sharing, thanks Saket! Fyi @siowyisheng 

PS - I escaped your backticks above so that it shows up
