### ISSUE TITLE
Target Offset Feature (capability already implemented in TagUI v5)

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#437]
Hi @kensoh 

I had to add the target offset feature to the images in the tagui commands.

I've added this feature to make some changes to the 3 source files (tagui_header.js, tagui_parse.php, tagui.sikuli \ tagui.py).

With this feature, I can now add target offset to tag ui commands with the following usage

```
type system/images/chrome.png.targetOffset(-193, -1) as murat
click system/images/chrome.png.targetOffset(-193, -1)
```

I share my changes below for your review

**1.tagui_header.js**

Add New Function
```
function is_targetoffset(input_params){ // helper function to check if string is .targetOffset(x,y) 
  if(input_params.match(new RegExp(/.targetOffset\(-?\d+\,-?\d+\)/g))) return true; else return false;
}
```
Change is_sikuli function

```
function is_sikuli(input_params) { // helper function to check if input is meant for sikuli visual automation
if (input_params.length > 4 && input_params.substr(-4).toLowerCase() == '.png') return true; // support png and bmp
else if (input_params.length > 4 && input_params.substr(-4).toLowerCase() == '.bmp') return true;
else if (is_coordinates(input_params)) return true;
else if(is_targetoffset(input_params)) return true; else return false;}
```
**2.tagui_parse.php**

Add new function
```
function is_targetoffset($input_params){
  if(preg_match('/.targetOffset\(-?\d+\,-?\d+\)/',$input_params)) return true;else return false;
}
```

change is_sikuli function

```
function is_sikuli($input_params) { // helper function to check if input is meant for sikuli visual automation
if (strlen($input_params)>4 and strtolower(substr($input_params,-4))=='.png') return true; // support png and bmp
else if (strlen($input_params)>4 and strtolower(substr($input_params,-4))=='.bmp') return true;
else if (is_coordinates($input_params)) return true;
else if(is_targetoffset($input_params)) return true; else return false;}
```
**3. tagui.sikuli\tagui.py**

Add two new function

```
def is_targetoffset( input_locator ):
	if input_locator.split('.')[-1].find('targetOffset') == 0:
		return True
	else:
		return False
def get_image_path( input_locator ):
	return input_locator[:input_locator.find('.targetOffset(')]
```

change x_coordinate function

```
def x_coordinate ( input_locator ):
	return int(input_locator[input_locator.find('(')+1:input_locator.find(',')])
```

and change all sikuli command
for example:

```
def tap_intent ( raw_intent ):
	params = (raw_intent + ' ')[1+(raw_intent + ' ').find(' '):].strip()
	print '[tagui] ACTION - click ' + params
	if is_coordinates(params):
		return click(Location(x_coordinate(params),y_coordinate(params)))
	elif is_targetoffset(params):
		 return click(Pattern(get_image_path(params)).targetOffset(x_coordinate(params),y_coordinate(params)))
	elif exists(params):
		return click(params)
	else:
		return 0
```

I've added all the changes I've made under this issue

[TargetOffset.zip](https://github.com/kelaberetiv/TagUI/files/3212627/TargetOffset.zip)

**Comment by kensoh** [comment]
Cool work @muratcim thanks for sharing! Will not be merging this PR, because TagUI v5 already has provision for handling offsets for visual automation. It is done using the helper functions (more details below), and not inline as your implementation. This retains the text-like format of TagUI scripts for easy maintenance and readability by non-developer users.

https://github.com/kelaberetiv/TagUI#helper-functions

>mouse_xy(), mouse_x(), mouse_y() require visual automation and can be used to interact with UI (user-interface) elements on the screen by specifying their (x,y) coordinates, eg clicking to the right of an UI element by 200 pixels -

```
// example of using mouse_xy(), mouse_x(), mouse_y() functions
hover element.png
echo mouse_xy()
x = mouse_x() + 200
y = mouse_y()
click (`x`,`y`)
```

**Comment by muratcim** [comment]
Hi @kensoh 
Thank you for your feedback.You did a great job with the Tagui project

I hope I will contribute more to this project in the future

**Comment by kensoh** [comment]
Thanks @muratcim for your support and actively creatively using the tool!
