### ISSUE TITLE
Difference between functions in tagui_parse.php and tagui_header.js

### ISSUE THREAD

**Issue by kishorer1290** [kelaberetiv/TagUI#441]
Difference between tagui_parse and tagui_header.js file
I see that there is intent function defined in tagui_parse file for selectbyvalue and the same is there in tagui_header

**Comment by kensoh** [comment]
I can't find 'selectbyvalue' string in both files, not sure what you meant. In general, `tagui_parse.php` interprets the TagUI automation script to become JavaScript code to be executed.

`tagui_header.js` has many helper functions and supporting code such as integration with Chrome and SikuliX, as well as many intent declarations for live mode functionality.

The select intent in `tagui_parse.php` needs the selectOptionByValue functions in `tagui_header.js` to function - they work in pairs by first converting TagUI script to JavaScript, then executing JS code.

```
$ grep -i selectbyvalue tagui_parse.php 
$ grep -i selectbyvalue tagui_header.js
$ 
```
