### ISSUE TITLE
API call with https request - NETWORK_ERR: XMLHttpRequest Exception 101

### ISSUE THREAD

**Issue by kurawadiprasanna** [kelaberetiv/TagUI#448]

**Comment by kurawadiprasanna** [comment]
example:
 api https://domain.com/api/rest/tokens

**Comment by kensoh** [comment]
You can use api step to make API calls. Methods such as GET/PUT can be chosen, and headers / body can be supplied. More details here under API section - https://github.com/kelaberetiv/TagUI#api

**Comment by kurawadiprasanna** [comment]
I did the same. but it is throwing me the error as "FAIL Error: NETWORK_ERR: XMLHttpRequest Exception 101".

**Comment by kurawadiprasanna** [comment]
there is a need of disabling "ssl certification verification". Please suggest

**Comment by kensoh** [comment]
It could be because TagUI's api step web engine is based on PhantomJS and not accepted by the web service. As TagUI supports integration with Python, you can consider using Python requests package and py step to make and save the request response. After that use TagUI load step to retrieve and processing accordingly using JavaScript, eg JSON.

**Comment by kurawadiprasanna** [comment]
@kensoh, we are trying as below.
Script:-
py begin
import requests
respose = requests.post('https://ipaddress:port/v3/auth/tokens',api_config.body)
py finish 

Still, it is not working. Please suggest

**Comment by kensoh** [comment]
api_config is a variable object in TagUI which is not accessible in Python.

For simple data, you can use py_step() to do that (eg in readme under cheat sheet pro steps).

For complex data, you can try saving the object JSON.stringify() using dump step. Then from Python parse that file using json library, before giving to requests.

**Comment by kensoh** [comment]
Let me know again, if you run into any issue!

**Comment by 15634130221** [comment]
请问， 这种情况是怎么造成的？应该如何修改？
![1735808702661](https://github.com/user-attachments/assets/7345cb74-fcf1-4f89-a373-a2eba4c3c0b9)

**Comment by 15634130221** [comment]
请问，这种情况是怎么造成的？应该如何修改？
```
api_config = {method:'post',header:['Authorization :Bearer  fEuyOPSCOngM:WPCvWcASGWtP','Content-Type:application/json'],body:{'model': '4.0Ultra','user': '张三','messages': [{'role': 'user','content': '你好，讯飞星火'}]}};
api https://spark-api-open.xf-yun.com/v1/chat/completions
echo `api_result`

```
![1735808702661](https://github.com/user-attachments/assets/9ca67247-b11d-47c8-a1ba-9f240c8e63d1)

**Comment by 15634130221** [comment]
> @15634130221 hello, I believe this error has to do with the API authentication token

这个API我在测试工具中我得到的反馈是正常的，进行集成时出现这个问题。我将测试工具中的参数直接移植了过来， 所以参数是没问题的。所以目前我依然很疑惑问题的点在哪里

**Comment by marcelocecin** [comment]
Could you do the test via `curl` or https://hoppscotch.io and attach the result here?

**Comment by 15634130221** [comment]
> Could you do the test via `curl` or https://hoppscotch.io and attach the result here?

我通过编写一个python工具，然后使用tagui调用它的方式已经解决了， 感谢您。
