### ISSUE TITLE
How do I use the popup step to open URL?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#456]
from user query in https://github.com/kelaberetiv/TagUI/issues/454#issuecomment-503588904

---

One more thing I wanted to know was how can I use popup step to actually open a new webpage in . a new tab with a totally new URL. I even read the sample 9_misc but was stuck for opening a new url in a new tab.

I tried popup new_url { http://www.google.com }.
This didn't work either popup http://www.google.com.

**Comment by kensoh** [comment]
@abhishek-27 for popup step, it is used after a new tab is opened.

For example, you go to some webpage, click on some button and then a new tab opens up. popup step lets you interact with that new webpage, all you need is specify some string in the URL of the new webpage, so that TagUI knows which tab you want to control.

popup step does not let you open a new tab by itself. You can tell me more about your use case so that I can see if there is some way TagUI can work for that use case or not.

**Comment by kensoh** [comment]
The usage after a new tab is opened,

**this way for many actions**
```
popup url_string
{
action1
action2
action3
}
```
**if only 1 action on new tab**
```
popup url_string
action1
```

**Comment by abhishek-27** [comment]
So my use case is that I need to open multiple URLs and use data from one website and set it on another website and continue the automation in that website. So i was thinking if we can open new URL in new tab. Because if I do just 

```
http://google.com
wait 2
http://youtube.com
```

This results in opening URLs in same tab.

**Comment by kensoh** [comment]
I see.. TagUI doesn't support this case case of opening multiple tabs this way. You can try batching by gathering the data from website 1 and store it in csv or some file, to do this in 1 automation flow. Then in automation flow 2, load the file and use JavaScript to parse the contents and act on website 2.

Alternatively, you can try using visual automation to use keystroke to launch a new tab and type a new webpage before using popup step. But that way is tricky and may not work correctly.

**Comment by Robertsson** [comment]
_If someone happen to land on this issue from google as i did._

Found this flag for chrome: --disable-popup-blocking. 
If that would work it would be easy to do _dom window.open();_ for a new tab.
But couldn't get it to work.

So i made a ugly solution but it solves the problem:
```
dom document.body.insertAdjacentHTML("afterbegin","<a href='https://www.youtube.com' target='_blank' id='youtube'>youtube</a>");
click youtube

dom document.body.insertAdjacentHTML("afterbegin","<a href='https://www.google.com' target='_blank' id='google'>google</a>");
click google

popup youtube
{
    type search as TagUI
}

popup google
{
    type search as TagUI
}
```

**Comment by kensoh** [comment]
Great sharing! I confirm that there isn't a way to open a specific URL not in the original webpage in a new tab and access that tab using its web elements. Above is a cool solution! 👍

**Comment by jamesmnixon** [comment]
Hello again Ken! Regarding this above issue. my use case is a little different. 

- From a certain starting webpage, there are a number of clickable elements that each navigates away to another webpage.
- My current process is as follows:

1. Start with `rpa.url('webpage')`
2. Iterate through clickable element table with rpa.click('target')
3. do work on the resulting page
4. return to base URL with `rpa.url('webpage')`
5. click the next item in the list

I do this for ~350 entries in the clickable element table each day

The problem is that the overhead of having to navigate back to the starting URL takes ~8 seconds for each `rpa.url('webpage')` request. This adds significant overhead to the time the automation takes to run (About 45 extra min).

My question to you is this:
Is it possible to open a new tab/window for each click, (Keeping the base URL window in existence) to do work in that tab/window, close the tab/window, and click the next item on the original tab/window?

I'm not looking to split the automation and have it do work in multiple tabs at the same time, although that would be useful and speed things up greatly, at minimum just do it sequentially without having to reload the base URL?

Any help or further guidance would be appreciated! 

Thanks Ken

**Comment by kensoh** [comment]
Hi James, as there is no @href to read, you can't use r.dom('window.open(url)') and r.popup(unique_string_in_url) to do it.

Otherwise, that method can let your programmatically open new tabs and automate there without leaving the old tab.

To do this is possible but also takes time, you'll need to write custom SikuliX code to use low level keyboard and computer vision. Ie 1. use computer vision to move mouse cursor to the link, 2. use r.vision() to send custom SikuliX code to key press down [ctrl], 3. r.mouse('down'); r.mouse('up'), 4. release the [ctrl] key. This way would force the browser to open a new tab I think. Then you can use popup() to handle.

However, if making automation run faster is your consideration, maybe you can try out the new turbo mode. It runs 10X faster than the normal human speed, so your whole automation should finish much quicker. See more here -

https://github.com/tebelorg/RPA-Python/issues/297

**Comment by chooimail** [comment]
Request:

With reference to the solution provided here https://issueexplorer.com/issue/kelaberetiv/TagUI/1056

I notice that the 'popup' step must use a string typed in the step.
**Is it possible to use a variable instead?**
So far I tested, a variable cannot be used.

For example: (using the same link in this)
```
..
 after opening a new tab and entering a new webpage
..
y = "yahoo"
popup `y`
    type //*[@name="p"] as testing 2
```

When using a variable, the ERROR message will return
```
ERROR cannot find yahoo
```

**Comment by kensoh** [comment]
Hi @chooimail I'm afraid popup step does not support variables. This is due to legacy reasons where it actually takes in a regex string. The internal conversion of the variable to regex string would be invalid regex. Some ideas -

1. if the automation can be broken into 2 parts, you can generate a .tag file with the correct popup step to process
2. if the URL can be retrieved, you can try directly going to the URL of the new tab and automate there directly

**Comment by kensoh** [comment]
CC @ruthtxh

**Comment by chooimail** [comment]
> Hi @chooimail I'm afraid popup step does not support variables. This is due to legacy reasons where it actually takes in a regex string. The internal conversion of the variable to regex string would be invalid regex. Some ideas -
> 
> 1. if the automation can be broken into 2 parts, you can generate a .tag file with the correct popup step to process
> 2. if the URL can be retrieved, you can try directly going to the URL of the new tab and automate there directly

Hi Ken,

OK, noted. And many thanks for the explanation.
Yeah, there are definitely work arounds as you suggested.

I was mainly trying learn and make use of the ```popup``` step, as far as it can go.
(^_^)
