### ISSUE TITLE
Where is my downloaded file?

### ISSUE THREAD

**Issue by adamkendall1** [kelaberetiv/TagUI#469]
Hello,

I just got TagUI up and running on my Mac today, and I'm trying to set up a test script to log in to a website (toggl.com in this case) and download the most recent invoice.

It seems to be working when I run it with the following command:

`tagui ~/Desktop/taguiTest chrome`

I'm using the "chrome" option so I can see what it's trying to do. It clicks on the download link, and I see the file appear in the bottom left of Chrome and it looks like the progress wheel completes pretty much instantaneously. 

But I can't click on the file to open it, and it does not appear in my normal downloads location.

Am I missing something? Is it not possible to download and save files automatically with TagUI?

Below is my script for reference:

-----------------------------------------------
https://toggl.com/app/timer

echo 'navigating to toggl website'

//click Log in
//type email-address as [REDACTED]
//type password as [REDACTED]

//click login-button

wait 5
click /html/body/div[1]/div/div[1]/div/div/div/div[2]/div[1]/div[20]/button/div/span
//click .css-uzk3k9.e69zk535 .css-1y4lfgz.e69zk531 span
wait
click .css-tvipz0.e171c6ue0
wait 5
click .css-18uivy4.e1lwzskz3:nth-child(3) span
wait 5
click .e22ygp07.css-1gwcs5t.e19wvnsp11:nth-child(3) .css-8a0s72.e22ygp01

wait 30

-----------------------------------------------

**Comment by adamkendall1** [comment]
I figured it out.

The file was being saved to my desktop (same directory as the script file itself).
I just didn't see it because my desktop is so messy.

**Comment by kensoh** [comment]
Thanks Adam for your detailed replication steps! Yes it is to the same location as the script.

In addition, below can be used to change the default download path to some other location -

```
chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'flow_path'});
```
