### ISSUE TITLE
Moxie RPA Studio - IDE and advance features by @muratcim

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#470]
First of all, thank you very much for bringing this beautiful application to the open source community.I've been trying to write a studio for a few months.Below is a demo video for the first version.

I wonder your comments

https://www.youtube.com/watch?v=uYw0CIFV_V4&list=PL4E9gtEWdhVVo5UcS3350HnnwF97f2G7H

The application has many features developed in accordance with the nature of tagui cross platform.
Stable version will share with you in the coming days

**Comment by kensoh** [comment]
**Hi @muratcim you have created fantastic work TagUI Studio! It is an amazing IDE studio!**

I watch your video recording a few times and enjoy it. I saw that you implemented below -
- syntax and keyword highlighting
- auto-fill parameters for actions
- actions list for base controls
- modules for advance actions
- visible and headless Chrome
- snap image to capture locators
- console, SikuliX, Python, R logs
- meta data for modules / python 

Very nice implementation! The part on meta data by using // to escape is very creative, it lets the studio adds special action information + code to the script while retaining execution compatibility by TagUI.

---

Your TagUI Studio app is production quality! Without knowing more details of your implementation, application design, and roadmap, these are some thoughts I have as I view your video demo -
- project directory and file structure - system folder may be considered for removal, so the folder structure is flatter, for eg images directly in base folder of project
- auditing and reporting feature - TagUI has a report option which tracks execution result and time taken, that may be useful feature to add without too much rework
- modules, repository, datatable support - other bells and whistles features of TagUI which can maximise the benefit of the studio as it lets users oversee everything
- orchestration functionality - if it is in your roadmap, some form of scheduler or interface to set up and configure jobs may extend functionality of studio beyond IDE

---

Without knowing your roadmap and architecture, below are some thoughts of potential issues -
- cross-platform compatibility might be an issue or potential implementation depending on the application framework that you are building the project on (not sure how you are building it)
- leveraging Python integration and packages is a smart idea to augment areas which TagUI implementation is weak in. For eg in your use of Excel functionality. This brings powerful new capabilities to TagUI Studio users, in return it requires users to first setup Python and packages (or may be automated by shell scripting, Python code, or using pip for dependencies management.

**Comment by kensoh** [comment]
If it's easier for you, I can meet you on Skype or video to learn more about TagUI Studio, your plans and roadmap for this amazing application, and see what can be done to support that vision. Communicating through GitHub issue or email is great too, whichever is easier for you.

Thanks for sharing this fantastic news Murat!

**Comment by muratcim** [comment]
Hi @kensoh 

I would love to discuss this with you. I'm sending my contact information via linkedin

**Comment by kensoh** [comment]
Thanks @muratcim sure, I'll follow-up with you there!

**Comment by muratcim** [comment]
I created a sample project using ocr to demonstrate the capabilities of tagui.
In this project, he reads the values in the order form and saves it to a form prepared on google.

You can watch the video from the link below

https://youtu.be/f7qjZudWlBM

**Comment by kensoh** [comment]
Hi Murat, your video demo looks great!

The only comment I have is on syntax, for your consideration to see if the collapsed metadata name can be the same as the toolbox description. For eg `Open Application` description on the toolbox control and `[Open Application]` in the markup, instead of `[ApplicationOpen]`. This reduces user friction when learning to use the tool as there is consistent same description both in the toolbox and script.

I saw that `"name;variable"` syntax is used to denote a variable with the name "name". It may not be intuitive to a beginner user. But I don't know what syntax could be more natural and deterministic than this. Because if you use "name variable", user might really want to type that string.

Cool stuffs combining visual automation, OCR and web automation, all within your TagUI Studio app!

**Comment by muratcim** [comment]
Hi, Ken

You're right, I need more work on component naming.

In fact, the use of "name; variable" is only required for edit mode.When the edit button above the component keywords is pressed I use to populate values in controls in the window that will open.I will try to find a better method in the future

**Comment by kensoh** [comment]
Hi Murat, closing the issue for now, but do continue to post here if anything!

**Comment by SJACOMDOC** [comment]
Iam trying to download tagui RPA studio 1.3 from google,not found. Is it not yet released or if it is released so it will be available to all as open source or have to be paid. If free where to downlod it. Need to explore a lot in this could you help??? @kensoh

**Comment by kensoh** [comment]
Oh hi, the RPA Studio software is a private commercial project that Murat developed.

It may not be open-sourced and available for download right now. I heard that he is doing the finishing touches now. Am looking forward to hear future updates from Murat!

**Comment by SJACOMDOC** [comment]
Thanks Kensoh for the information!!!!Have some doubts in TAGUI can you give me your mail id any social media to have a chat!!! Thanks!!!

**Comment by kensoh** [comment]
Welcome @SJACOMDOC! For any questions or issues on TagUI, free feel to raise any issue here on GitHub so other users can benefit from the question 😄

**Comment by Hassan-Ali123** [comment]
Can somebody tell how to run a program written in TagUI Studio? I mean where should our files be placed to make run easily as in simple TagUI (without IDE).

**Comment by kensoh** [comment]
@muratcim would be the right person to answer your question. From what I understand, Moxie RPA (the new name for this project that Murat is developing), has its own project file and data structure. It stores a collection of TagUI scripts and images and its own data, to be run from within the IDE. There will probably be provisions to run via scheduler, and perhaps from command line.

**Comment by muratcim** [comment]
Hello to everyone

I want to make an information about the application.
2.0 version of Moxie RPA Studio released at moxierpa.com. Studio is now completely free
Mac and linux versions will be released in the coming days.
I would appreciate it if you use Studio to turn back

**Comment by kensoh** [comment]
Hi Murat, thanks for your update! Reopening issue.

Can you tell us more about the business model if Moxie RPA Studio is completely free? Is there a paid enterprise version or other future plans? Can you tell me what you mean by use Studio to turn back?

Am thinking to add a paragraph in the To Use section on this, maybe before TAGUI WRITER, SCREENSHOTER & EDITOR paragraph. Copying my colleague @siowyisheng

**Comment by muratcim** [comment]
Hi Ken,

Studio app will always be free.  Can be used in all commercial or individual projects.
hopefully helps tagui project reach larger audiences.

**Comment by kensoh** [comment]
Thanks Murat, I'll follow-up with my friend @siowyisheng -

Hi Yi Sheng, give Moxie RPA Studio a try at http://moxierpa.com, I'll be drafting a paragraph to add to readme, probably before the TAGUI WRITER section. After you have tried we can fine-tune the description together with Murat.

**Comment by kensoh** [comment]
For your review Yi Sheng and Murat, on my draft, unassigning myself -

[Moxie RPA Studio](http://moxierpa.com) from Murat Cim / [@muratcim](https://github.com/muratcim) is an IDE app for creating automation workflows, built on top of TagUI. It runs on Windows, macOS, Linux and has more than 70 controls available with drag and drop. The IDE has syntax highlighting, Intellisense and auto-fill support. It also has a recorder for mouse and keyboard movements. Moxie RPA Studio is a free and full-featured app but it is not open-source, thus we can't directly endorse it as its source code is not viewable.

**Comment by kensoh** [comment]
Copying @siowyisheng and @muratcim on above update -

**Comment by Hassan-Ali123** [comment]
So @kensoh what you think should we use Moxie RPA Studio as TagUI Studio or are you developing another Studio for TagUI?

Waiting for cordial reply,

**Comment by siowyisheng** [comment]
In order for it to be Tagui studio it would need to be open source. Is that possible?

**Comment by Hassan-Ali123** [comment]
Hi team! Please tell me if we save or open a project in tagui, where are the changes updated or saved in its setting file? 

Thanks!

**Comment by Hassan-Ali123** [comment]
I mean in its project.json file, in gitignore file, etc. or in some other files that come with the TagUI setup zipped?

**Comment by Hassan-Ali123** [comment]
Please reply as soon as possible! Thanks!

**Comment by kensoh** [comment]
Hi Murat! You have not replied to Yi Sheng's message above, pointing out in case you missed it.

I don't understand what you mean by changes updated. If open and edit and run TagUI script, it does not update any config. For TagUI project, I don't use any IDE to manage it, I just use vi editor to edit and create the files.

**Comment by Hassan-Ali123** [comment]
I mean like in Visual Studio, if we open or create a project, for every project it creates a json file, which saves basic config settings for that opened or newly created project. In TagUI, is this the case?

**Comment by kensoh** [comment]
TagUI is not a Visual Studio project, so it does not have files related to development settings and config.

**Comment by kensoh** [comment]
The .gitignore file is standard file created manually to exclude local files from syncing to GitHub.

The package.json is a file created manually for publishing to NPM.

**Comment by Hassan-Ali123** [comment]
Ok ok I got it. Thanks for it!

**Comment by kensoh** [comment]
Sorry Murat, just realised it is Hassan that is asking question and Yi Sheng was asking him back. Hassan I don't think is involved with Moxie, only Murat is working on it. Moxie is unlikely to be open-source, but AI Singapore is planning to develop an IDE for TagUI this year.

**Comment by Hassan-Ali123** [comment]
True, I am not involved with Moxie.

**Comment by Hassan-Ali123** [comment]
Hi team!
I want to know that can we integrate TagUI functionalities with a custom built studio? If yes please guide me. Thanks for the suggestions!

**Comment by kensoh** [comment]
For simple integration, you can invoke TagUI using the command line with options from your custom studio. Just like how you do it when using the tool manually.

For advance integration, such as step by step execution and feedback of results, you can use live mode to do that. But it is not easy and not possible for us to guide how to do that.

You can see how I implement integration in my Python project -
https://github.com/tebelorg/RPA-Python/blob/master/tagui.py

**Comment by Hassan-Ali123** [comment]
Hi @muratcim!  nice to see you again. Please guide me how you integrated TagUI functionalities as drag and drop activities in Moxie RPA Studio? Actually I am developing a custom studio and I need help from you. Thanks!

**Comment by Hassan-Ali123** [comment]
Hi Kensoh! Please will you elaborate how to invoke TagUI using the command line with options from the custom studio? Please reply as soon as you will be available.

Thanks!

**Comment by kensoh** [comment]
Hi Hassan, this is a software engineering question. I can't teach you software engineering. You will have to check the software framework that you are using how it calls OS-level commands and parameters. Closing this thread as it has derailed from the original post.

**Comment by kensoh** [comment]
Hi Hassan, this is a software engineering question. I can't teach you software engineering as this project is not a software development school that do training for people.

You will have to check the software framework that you are using how it calls OS-level commands and parameters. Closing this thread as it has derailed from the original post.

CC @siowyisheng

**Comment by naufil09** [comment]
Any update about Moxie RPA Studio! How can i download it ? Website is not opening. Can you please help @kensoh @muratcim ?

**Comment by kensoh** [comment]
Oh Moxie RPA Studio is created by Murat Cim from Turkey, https://www.linkedin.com/mwlite/in/muratcim

I believe the project has now been suspended. Murat has now moved on to be CTO of QBitra - https://www.qbitra.com

Hi @muratcim ! 👋🏻
