### ISSUE TITLE
Using python or sikulix command in a while loop - use for 1 to infinity

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#476]
Hi @kensoh 

when using python or sikulix  in the while loop I get the following error

**SyntaxError: Expected token ')'**

sample code..

```
dclick system/images/invoice.png
dclick system/images/invoice1.png

while (visible('system/images/balance_image.png') == false)
{
  echo 'Not Found'
  keyboard [PAGEDOWN]
}
echo 'Found'

```
When I examined the cause of the error, I saw that the casper file was caused by missing brackets.

```
casper.then(function() {while (((visible('system/images/balance_image.png') == false)))
{ // start of code block

this.echo('Not Found');

casper.then(function() {{techo('keyboard [PAGEDOWN]'); var fs = require('fs');
if (!sikuli_step('keyboard [PAGEDOWN]')) if (!fs.exists('[PAGEDOWN]'))
this.echo('ERROR - cannot find image file [PAGEDOWN]').exit(); else
this.echo('ERROR - cannot find [PAGEDOWN] on screen').exit(); this.wait(0);} // end_fi while loop marker});

} // end of code block
});
```

The return " // end_fi while loop marker";  code inside the end_fi function in tagui_parse.php makes a brackets comment line

**Comment by kensoh** [comment]
Hi @muratcim this is by design, with a note under readme conditions section. The technical reason is there is auto-wait + timeout CasperJS code blocks for each TagUI step. Because of this, a while loop in JS will hang CasperJS. Thus as a tradeoff the while loop is deprecated.

https://github.com/kelaberetiv/TagUI#conditions-examples
>{ and } block is required after for loop (while is deprecated - no auto-wait, hangs CasperJS)

As a workaround, you can use a for loop as follows to simulate effect of a while loop
(infinity is a pre-set number of 1024) -

```
for n from 1 to infinity
{
do a
do b
do c
}
```

**Comment by kensoh** [comment]
Adding on, within the for loop, you can use continue / break to control looping. Eg break if the element is present. Also, appreciate your troubleshooting and debugging details above!

**Comment by muratcim** [comment]
Hi @kensoh 

I am sory. I missed the expression in the document

I'm sharing a sample of for example code to help others.

```
 for (counter = 0; counter <= 1024; counter = counter + 1)
 {
   if (!visible('system/images/balanceimage.png'))
   {
     keyboard [PAGEDOWN]
   }
   else
   {
     break;
   }
   
  }
```

**Comment by kensoh** [comment]
Hi @muratcim not at all! The documentation is too long and I had to condense the points.

Adding on, below is a variant if using the natural language condition syntax. Also, break and continue are recognised keywords so with or without ; works. For other JavaScript commands (besides assignment commands), ; behind or js in front is needed for TagUI to detect JS code.

```
 for counter from 1 to infinity
 {
   if (!visible('system/images/balanceimage.png'))
   {
     keyboard [PAGEDOWN]
   }
   else
   {
     break
   }
   
  }
```

**Comment by muratcim** [comment]
This is a much better solution.Thanks Ken
