### ISSUE TITLE
TagUI crashes when download link is clicked - pending replication

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#477]
Hi Ken,

I'm currently writing a TagUI script on one of our corporate websites.

There's a series of reports that the users need to download, and I encounter one very strange situation which I've never seen before.

For each report, the robot will enter the report ID, then click the "Generate Report" button. Then it will click a pulldown menu and then choose "PDF".

If I do it manually, the moment I click "PDF" from the pulldown menu, the report will be generated and straightaway downloaded to the default Downloads folder (in Windows 10).

For your TagUI, you actually created a separate profile for TagUI, right?  When I do this manually in my own Chrome, everything works fine. I see the file downloaded in the Downloads folder. 

However, when I run it using TagUI script, the moment it clicks the PDF from the pulldown menu, TagUI crashes.  The file is actually downloaded, and I can see the file in the Downloads menu.  However, because TagUI crashes, it cannot continue to run the rest of the reports.

To make sure that it's not error in my TagUI script, I put a LIVE early in the script.  Then I manually download the PDF using the Chrome initiated by TagUI.  True enough, the Chrome by TagUI crashes the moment I select PDF from the pulldown menu.

There's no error message at all in the command prompt.  The Chrome/TagUI just crashes.

1) Has any of your users encountered such thing before - in which downloading a file in the user Chrome works fine, but the same link using TagUI Chrome crashes the browser?

2) Is there any other log files somewhere that I can show you so that you have more clues as to where might be the problem?

p.s. the link is not the standard 
~~~ HTML
<a href="url"> 
~~~
type, so I cannot grab the url and go to the download link direct. It's one of those server generated one.

**Comment by kensoh** [comment]
Thanks for the detailed background of the issue. As it is not a public website to share replication steps, my best guess is it is some non-standard link or button. So different that can crash the underlying framework when Chrome sends message back to TagUI.

My first thought will be to use dom step to send JS code directly to the webpage to click the link. that way, no matter what happens, TagUI will still be safe from getting crash. Then if there is a way to tackle this properly, then a longterm solution should be explored.

Will have a look more when you drop by my place this afternoon 👍

**Comment by kensoh** [comment]
Solution found - 
```js
chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'c:\\Users\\userid\\Downloads'});
```

**Comment by kensoh** [comment]
**Summary** - for some reason, the website does not like having the file download location set to the location of the automation flow. Solution done in person just now is modifying tagui_parse.php to comment out the line in url_intent() to not change default download location. However, above statement can also be run to change default file download location to a folder user desires and it should work too.
