### ISSUE TITLE
"ERROR - cannot find Sign in" on github.com website - pending replication

### ISSUE THREAD

**Issue by hemanthsavasere** [kelaberetiv/TagUI#481]
Hi @kensoh,

I tried running tagui on github.com  and click on Sign in button, But getting an error as "Sign in" is not found.

**Comment by kensoh** [comment]
Hi @hemanthsavasere do you have the replication script to trigger this error? To make sure the locator is correct, you can try using Chrome inspector to search XPath locator to see if there is a match.

**Comment by kensoh** [comment]
Also, your background looks like is in Python / data science. You may want to take a look at the TagUI for Python project instead - https://github.com/tebelorg/TagUI-Python

It's a wrapper Python package I made base on TagUI that can be used with `pip install tagui`

**Comment by hemanthsavasere** [comment]
Hi @kensoh 
Thanks. Sure, I'll gladly try that.
