### ISSUE TITLE
How to use frame step - for chrome mode, use name or id attribute

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#493]
Hi Ken,

If there's a webpage with an iframe, and the url pointing to the iframe is:
> https://website.com/info/index.php

What should I put in the frame to access the elements inside?
~~~javascript
frame what-to-put-here?
{
    ...
}
~~~

Tried
~~~
frame website.com/info/index.php
{
    ...
}
~~~

~~~
frame info
{
    ...
}
~~~

~~~
frame index.php
{
    ...
}
~~~

All didn't work

**Comment by Donko123** [comment]
I have the same question.

**Comment by kensoh** [comment]
The parameter is the frame name, when inspecting the frame, you can find the name attribute that identifies the frame.

This is in the readme under pro steps - https://github.com/kelaberetiv/TagUI/blob/master/README.md#cheat-sheet

Default PhantomJS mode using CasperJS only can identify using frame name. For chrome option, I added ability to identify using either frame name or id attribute, that can be found by inspecting the webpage.

**Comment by kensoh** [comment]
It can take some time to inspect and go up the hierarchy of DOM objects to spot the frame object. Lemme know if that works!

**Comment by ck81** [comment]
Hi Ken,

> The parameter is the frame name, when inspecting the frame, you can find the name attribute that identifies the frame.

> For chrome option, I added ability to identify using either frame name or id attribute

What if there's no name or id attribute?

e.g. the examples in https://www.w3schools.com/tags/tag_iframe.asp

~~~HTML
<iframe src="https://www.w3schools.com"></iframe>
~~~~

There's no name or id attribute.

**Comment by kensoh** [comment]
This is tricky, not supported natively from CasperJS withFrame or TagUI's customised withFrame for Chrome browser. There is a workaround you can try. First find out the XPath of that frame, otherwise there is no way for DOM to identify which object you are referring to. Second, use dom step to add a name or id attribute to that frame. Third, use the frame step normally by the name or id as parameter.

Following is an example of adding a name attribute of an object to be "demo".

```js
https://www.w3schools.com/jsref/met_element_setattribute.asp
dom document.evaluate('//*[@class = "w3-btn w3-margin-bottom"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).setAttribute("name","demo")
```

**Comment by kensoh** [comment]
Lastly, if URL of the frame is known, in some cases, can visit that URL directly to do the automation.

**Comment by ck81** [comment]
> There is a workaround you can try. First find out the XPath of that frame, otherwise there is no way for DOM to identify which object you are referring to. Second, use dom step to add a name or id attribute to that frame. Third, use the frame step normally by the name or id as parameter.

This is interesting.  Will give this a try.  Thanks!

**Comment by ck81** [comment]
Hi Ken,

After much testing and digging around, I found your post #312 that highlighted:
>  due to security restrictions this property can't be accessed if the domain of the frame is different from the parent webpage. For reference of this security limitation see here, I think it is the same across browsers -
https://www.w3schools.com/jsref/prop_frame_contentdocument.asp
There's no way to override this default Chrome web-browser behaviour.

For this particular website, I think the website tries to stop RPA from accessing their website.  So they intentionally used a different domain for the main frame and the iframe.  What's even more interesting is that when you try to go to the URL of the iframe directly (as suggested by your method 1), the website will auto-detect that it's not running within an iframe, and it will do an auto-reload back to it's main webpage that has the main page + iframe.

Looks like for this webiste, the only way is to go by visual automation.

**Comment by kensoh** [comment]
Hi CK, I see.. Thanks for looking into it and sharing your findings!

Got it, sounds like that is the only option. Lemme know if you run into problems doing it visually. May need to combine with keyboard step to use key combinations for some advance actions.
