### ISSUE TITLE
Python equivalent of sys.exit() in TagUI for early termination - this.exit();

### ISSUE THREAD

**Issue by ck81** [kelaberetiv/TagUI#494]
Hi Ken,

In one of the use cases, we do not want the script to continue if the login is not successful.

In TagUI-Python, we can use `sys.exit()` to stop the entire robot.

What's your recommended way to achieve the same thing in TagUI?

**Comment by kensoh** [comment]
There are a few ways to do this, depending which way is the best for your scenario.

1. Do a hover step right after the login steps, to check for a web element that will only be there if login is successful. When that element is not found after timeout, TagUI will exit with error. Use timeout step to change the timeout setting to be longer if required. Default is 10 seconds.

2. Use `this.exit();` or `js this.exit()` to terminate TagUI automation script execution. There won't be the usual exit information such as total time taken for automation. But browser and integrations should close as usual.

3. Depending on the length of script, an if block could be used to check if login is successful (by checking presence of web element using present() function for eg), then do the remaining steps.

**Comment by ck81** [comment]
> 2. Use `this.exit();` or `js this.exit()` to terminate TagUI automation script execution. There won't be the usual exit information such as total time taken for automation. But browser and integrations should close as usual.

This works for this use case.  A lot less coding.  Thanks!
