### ISSUE TITLE
How to wait until an UI elements appears before continuing automation?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#499]

**Comment by kensoh** [comment]
TagUI already has auto-wait for UI elements to appear. The default timeout of 10 seconds can be changed with timeout step. Thus usually it is not required to have special flow control, since automation will keep waiting until timeout for the next UI element to act on to appear.

If user explicitly wants to wait, a quick solution is use the hover step. First, use timeout step to change to a timeout value in seconds that you want to wait before program results in error element not found. Second use hover step to hover at the UI element. Doing this will wait for the desired timeout for the element to appear. Also works with visual automation if an image is provided.

```
timeout 300
hover identifier

... do other stuffs ...
```

Another way will be keep looping until the element appears and break the loop, by using present() function to check if the element identifier has appeared. Also works if an image is provided. `infinity` is set to 1024 by default. This is more complicated and if `wait` is used, it will show up in output.

```
for n from 1 to infinity
{ 
    if present('abcededede')
        break

    // a wait should be added to have some time between loops
    wait 1
}

... do other stuffs ...
```

**Comment by Anujpalu24** [comment]
@kensoh  : can you please help me with how to verify a string contain a particular words or not

**Comment by kensoh** [comment]
Hi @Anujpalu24 check out this example flow - https://github.com/kelaberetiv/TagUI/blob/master/flows/samples/3_conditions.tag#L13

You can write the conditions in both human language or JavaScript if you are familiar or ok to google it.
