### ISSUE TITLE
Refresh webpage - use chrome.reload(); or keyboard step

### ISSUE THREAD

**Issue by ShwetaChahan** [kelaberetiv/TagUI#508]
I need to refresh the page 
Tried 
> chrome.reload
> vision type(Key.F5)
but nothing works 
Please advise

**Comment by kensoh** [comment]
- If TagUI is run with chrome option, `chrome.reload();` will trigger `document.location.reload()` on the browser. Can you paste here what is the error message from tagui_chrome.log when you do this?

- If visual automation is set up correctly (click image.png works for you), then `keyboard [f5]` would simulate the keypress. Check if browser is in focus. If not use `click chrome_icon.png` or something to bring it to focus, before using the f5 key or whatever key you normally use to refresh. eg `keyboard [cmd]r` on macOS Safari.

**Comment by ShwetaChahan** [comment]
Thank you Ken 
It works
