### ISSUE TITLE
How to get the directory of current tagui flow file - use flow_path

### ISSUE THREAD

**Issue by dog-2** [kelaberetiv/TagUI#509]
I followed the "To run tagui from anywhere" in README.

> For MacOS/Linux, use ln -sf /full_path/tagui/src/tagui /usr/local/bin/tagui to create symbolic link

I put my flow file in a folder on my desktop(TagUI is not). In command line I went into that folder and run the flow.  It ran well until I tried to use **run** step to load a .py file which is in the same folder as the flow file. (Not using **py begin**  in flow because when I tried to define a function in it, it ran into wrong. Put functions in child flow also got wrong. But I need to run long py code with functions, so I used the **run step** instead.) The py file could not be found.

Then I tried run **pwd** in the flow, the run_result is **...tagui/src**.

So is there any way to get the directory of current flow so that I can find files in the same folder with it, without using absolute path as I may move the folder one day.

**Comment by kensoh** [comment]
Hi @dog-2 this looks like a cool automation workflow that you are building! You can use the flow_path variable which is a global variable used by TagUI to track the flow file directory. For example -

**the flow_path global variable**
```
echo flow_path
```


**using the variable in run step**
```
run ls `flow_path`
echo run_result
```

**Comment by kensoh** [comment]
Forgot to add that I recently created a Python package for TagUI. It is a wrapper around TagUI that lets you access the various UI interactions capabilities directly in the Python environment (Jupyter notebook, Python scripts etc).

It may be more useful to your scenario where code base is already predominantly in Python.

https://github.com/tebelorg/TagUI-Python

**Comment by dog-2** [comment]
@kensoh 
Thanks for your answer. It helps a lot.

TagUI-Python is great. I will try it.

**Comment by vrudhay** [comment]
How do we know which are the global variables in tagui like flow_path? any doc?

**Comment by kensoh** [comment]
This is not documented because normal use cases should not be using global variables that TagUI uses internally for execution. You can see in src\tagui_header.js file if you need to. CC @siowyisheng
