### ISSUE TITLE
File downloads in Chrome incognito mode - accessing environment variables

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#512]
user query

---

I have a query on TagUI on the default download behavior. Previously, I developed a script using TagUI to download some files into "Downloads" folder via Chrome (incognito) by using the following :

- tagui.cmd - > set chrome_switches=--user-data-dir=chrome\tagui_user_profile --remote-debugging-port=9222 -incognito about:blank
- script file -> placed this code on the top of the script "chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'flow_path'});"

Recently when i re-run the file, i realised that the downloaded contents went into the script folder instead, also noted that if I try to use the "show in folder" option in the chrome window (opened using TagUI), nothing seems to happen. However, going through the manual way of open a incognito window, the "show in folder" option opens up the Download folder normally, leading me to think there might be an update to chrome that may have affected the code behavior. I have also tried renaming the 'flow_path' to a directory (using \\ for directory as well) but still get the same results. 

Would like to seek your help on this. Thank you!

**Comment by LIONEL743** [comment]
Hi Ken, I have did afew tests using the updated version of TagUI as well but seems like I still get the same issue. Tested the following cases:
1 ) without incognito - without chrome step ->  Downloaded files are stored in the script folder, pausing the script run in the terminal and using the same browser window to click on the download button causes the file to download into "downloads" folder.

2 ) without incognito - chrome_step code placed in first line of code -> Same results as above.

Tested this on two separate PCs with the same result. Could you help to verify if the chrome_step method of changing the download behavior is still ok?

**Comment by kensoh** [comment]
Hi @LIONEL743 does the problem happen if you place the chrome_step after the line in the script where you specify the URL? The issue may be due to the order. In each URL step, I enforce the changing of download location to the script folder in order to ensure consistency whenever a user specifies an URL. This was done because specifying an alternative download folder was not the design, thus chrome_step becomes like a hack to achieve choosing other folders.

**Comment by LIONEL743** [comment]
@kensoh your advice works. It seems to work fine after switching the chrome_step to after the URL is specified. Really appreciate it. Thanks! 

On a side note, is it possible to specify the download location to point using "%USERPROFILE%\Downloads" instead of a fixed location?

**Comment by kensoh** [comment]
Welcome @LIONEL743 ! I'm still trying to refine this aspect to make it more user friendly. Will keep a lookout on use cases around changing the default download path, to see if I can improve it next time.

For accessing environment variables, you can use something like below -

**TagUI code**
```js
system = require('system');
env = system.env;
echo env['TMPDIR']
```

**Code output**
```
/var/folders/4c/21d_62nx5tnf_t9l0fl9jych0000gn/T/
```

**Reference for this, system module of PhantomJS**
https://phantomjs.org/api/system/property/env.html

So what you want is probably something like below -

```js
chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: env['USERPROFILE'] + '\\Downloads'});
```
