### ISSUE TITLE
Desktop automation UI - see TagUI visual automation & OCR feature

### ISSUE THREAD

**Issue by layanto** [kelaberetiv/TagUI#514]
Any plan for desktop automation UI like Kantu's? See https://youtu.be/wH0MLIUdD-Q

**Comment by kensoh** [comment]
There is already desktop automation through computer vision and OCR. It's done using integration with SikuliX to access the OpenCV and Tesseract layer. Recognising images of UI elements, interacting with them, using (x,y) coordinates and offsets from images, sending keyboard combinations are possible.

More details and usage below. For more advance desktop automation, recommend commercial RPA software or perhaps AutoHotkey, which is able to talk to Windows apps natively through their backend.

https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by layanto** [comment]
I know TagUI can do desktop automation. But will it have user interface to ease creation of automation steps like Kantu's? In the youtube video above, you can see how easy it is to add automation steps, especially the ones with computer vision as the UI includes screen capture and cropping tool.
I am also interested how TagUI handle the OCR in the case like the temperature example shown in kantu's video where the thermometer symbol is used as the anchor for computer vision and the text next to it for OCR.

**Comment by kensoh** [comment]
There is no user interface to ease creation of automation steps.

There are 2 ways to anchor, you can use hover step, followed by mouse_x() / mouse_y() to retrieve the coordinates. After that add offsets accordingly and read step on the rectangle boundary (`read (x1,y1)-(x2,y2)`. This only in the cutting edge version - https://github.com/kelaberetiv/TagUI/issues/461

The second way to anchor is provide an .png image with the centre portion containing the temperature transparent. That way image match can happen even with changing values on the screen. And OCR can be captured using read step using that image.

**Comment by kensoh** [comment]
Can you share more why you are evaluating TagUI and not use Kantu directly for its features?

**Comment by layanto** [comment]
Mainly to do with Kantu's OCR requiring internet connectivity. Looking to use software like Kantu or TagUI to do automated desktop software testing but the network is isolated from internet.

**Comment by kensoh** [comment]
Gotcha, from above link Kantu enterprise edition at 499 USD supports offline OCR. But it did not list the pricing to install their local OCR engine - https://ui.vision/x/pricing#ocrlocal

Oh... For automated desktop testing definitely TagUI and Kantu shouldn't be the option. TagUI was not designed for test automation in mind, and I don't think Kantu is, probably. There should be better built for purpose open-source test automation frameworks to do what you need.

**Comment by layanto** [comment]
Most (all?) test automation framework for Windows desktop application relies on using Microsoft UI Automation framework and requires interacting with unique id of each UI elements. Some of the application we are looking to test will not be able to be accessed that way. Hence I was looking for something like TagUI or Kantu which can interact with UI using visual recognition.
Why don't you think TagUI is suitable for automatically execute a series of actions and monitor the outcome for test's pass/fail?

**Comment by kensoh** [comment]
Oh that is surprising.. I would think automation frameworks would be mature enough by now to make visually identifying and validating UI elements as part of their core capabilities.

The main reason is it is not built-for-purpose for test automation. While there is simple integration with Jenkins through .xml file if test option is used, there isn't advance reporting capabilities or dashboard in TagUI. There is a report option for saving summary of executions, data tables, object repositories etc, but beyond that, users won't be able to design their own implementation of data tables.

Another example would be test automation frameworks have the setup, execute, tear down sequences as part of their core. This would need additional development if done within TagUI, using tagui step to call other TagUI scripts. Thus, only if the reporting, management of test suites using TagUI's current implementation is acceptable, along with other weaknesses above, then users should consider TagUI.

**Comment by kensoh** [comment]
Other than above weaknesses for test automation, TagUI is very reliable during execution. I have users running bulk volume workflows lasting more than 12 hours without crashing. Also, it is easy to create, deploy and maintain due to its readable syntax.

Another weakness is TagUI is not a NodeJS module, thus users can't leverage on the Node ecosystem of packages for their test automation use cases. This weakness may somewhat be mitigated if users choose to develop in Python instead. Because I recently created a Python package for TagUI. Python ecosystem of packages would be available - https://github.com/tebelorg/TagUI-Python

**Comment by layanto** [comment]
Thanks for your detailed response.
