### ISSUE TITLE
How to install TagUI in Ubuntu - probably need to install PHP

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#516]
user query

---

Can you tell me how to install tagui in ubuntu... i checked out that in github bt it's not working😓😓

Plzz help me sir

**Comment by kensoh** [comment]
Try follow the steps below and choose the Linux packaged installation - 
https://github.com/kelaberetiv/TagUI#set-up

After that, you probably need to install PHP to use TagUI as Ubuntu doesn't come with PHP pre-installed, as mentioned in potential exceptions here - 
https://github.com/kelaberetiv/TagUI#command-line

**Comment by kensoh** [comment]
Closing for now until further inputs

**Comment by tanaysengar** [comment]
> Try follow the steps below and choose the Linux packaged installation -
> https://github.com/kelaberetiv/TagUI#set-up
> 
> After that, you probably need to install PHP to use TagUI as Ubuntu doesn't come with PHP pre-installed, as mentioned in potential exceptions here -
> https://github.com/kelaberetiv/TagUI#command-line

I have the same issues...I have installed PHP and followed the instructions but I continue to get the command not found error on command line. Please help

**Comment by manuelgodoy** [comment]
I am having these issues with php command. I believe this link: https://github.com/kelaberetiv/TagUI#command-line does not point anywhere useful anymore

**Comment by kensoh** [comment]
Thanks @manuelgodoy! I've updated the links above. I'm assuming that you are a flavour of Linux that does not come with PHP installed, because MacOS and Windows would already be taken care of.

On Ubuntu, to install php, can use `apt-get update; apt install php;`

See this Google Colab notebook to run TagUI on Ubuntu -
https://colab.research.google.com/drive/1RimeT6-u6_nCyLAFJ0Aq9OvRaEg2UPrg?usp=sharing

See this Google Colab notebook to run RPA for Python on Ubuntu -
https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

Lastly, feel free to join the TagUI group chat to ask any questions, there are other expert users there who will often share their experiences if a question asked is something they have come across - https://t.me/rpa_chat
