### ISSUE TITLE
How to select a data from a Grid - try using XPath

### ISSUE THREAD

**Issue by uzzalkoiri** [kelaberetiv/TagUI#517]
Hi,
I've a grid contains 100 rows. i want to click the option button only for some rows from the grid.
how can i do it? plz advise

**Comment by kensoh** [comment]
Your best bet is using XPath. It is a way of identifying web elements. The typical structure for such a repeated structure is (XPath)[n] where n is the from 1 to the number of elements matching the given XPath. You can look at below on finding XPath, or look up XPath on google for tutorials.

https://github.com/kelaberetiv/TagUI#find-xpath-of-web-element

**Comment by kensoh** [comment]
Closing issue for now until further inputs!
