### ISSUE TITLE
How to install sikulix on ubuntu 16.04 to work with TagUI

### ISSUE THREAD

**Issue by rubber12** [kelaberetiv/TagUI#518]

**Comment by kensoh** [comment]
Issue duplicated here at - https://github.com/kelaberetiv/TagUI/issues/516

**Comment by kensoh** [comment]
For Linux there are more setup steps because need to build the dependencies depending on which Linux flavour. Details - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html#newslinux

**Comment by kensoh** [comment]
Closing issue for now until further inputs!
