### ISSUE TITLE
How to use a conditional click, eg clicking for rows in UI with certain value

### ISSUE THREAD

**Issue by uzzalkoiri** [kelaberetiv/TagUI#522]
Dear Sir,
Please find the attached file. I want to select only the rows whose Netw. status = 'Network Ack'.

![tagui_problem](https://user-images.githubusercontent.com/408189/62002692-6bb14300-b12b-11e9-9bbd-7babf6b341ad.png)

**Comment by cevangelio** [comment]
I can think of 2 ways to accomplish that. You can use the built in conditionals (check Condition Examples in the Cheat Sheet) or if you are familiar with Python, either the python integration or TagUI-python would do.

**Comment by kensoh** [comment]
Closing issue for now until further inputs. Thanks @cevangelio for your solution!
