### ISSUE TITLE
How to get time taken by each step? - use timer() helper function

### ISSUE THREAD

**Issue by rahulmr** [kelaberetiv/TagUI#529]
How to log the time taken by each step in the test?
In below code, I want to determine time taken by each step and log it in csv or xml.
```
https://github.com
vision click('someimage.png')
vision wait('someimage')
```

**Comment by kensoh** [comment]
Hi Rahul,

There is a timer() helper function which returns the time taken in between calling it. More details here - https://github.com/kelaberetiv/TagUI#helper-functions

```
start = timer()

https://github.com
write timer() to result.csv

vision click('someimage.png')
write timer() to result.csv

vision wait('someimage')
write timer() to result.csv
```

To format CSV result easily, use the csv_row() helper function to directly write a row (array of columns) to the csv file. Also see above helper functions link for example of using it.

**Comment by rahulmr** [comment]
@kensoh Thanks for your reply. Really appreciate your work on building this software. I am really surprised how come I never came across TagUI when I really needed something like from a long time.
Thanks again!. I will try the helper functions.

**Comment by kensoh** [comment]
Hi @rahulmr no problem at all, thanks for your kind words.

Hope the tool is fun to use for you and your friends!

I've recently created a Python package base on this project, which brings the digital automation capabilities of TagUI to Python users directly - https://github.com/tebelorg/TagUI-Python
