### ISSUE TITLE
Popup help needed, not working - use string to look for in popup

### ISSUE THREAD

**Issue by hemanthsavasere** [kelaberetiv/TagUI#532]
pop "url_specified"{

}

My URL is
https://www.flipkart.com/realme-c2-diamond-black-16-gb/p/itmfgwbaahz6ph9j?pid=MOBFFMG3FGAFZYVE&lid=LSTMOBFFMG3FGAFZYVEPQOEDM&marketplace=FLIPKART&srno=s_1_1&otracker=search&otracker1=search&fm=SEARCH&iid=de316bad-455c-44c2-b87b-097fe298c1bc.MOBFFMG3FGAFZYVE.SEARCH&ppt=sp&ppn=sp&ssid=eoqgs8xguo0000001564751630833&qH=f229e7835511cc0b

How should I specify the pop function parameter for the URL above?

Thanks

**Comment by kensoh** [comment]
The syntax for popup step is below. It is meant for handling new browser tabs that popup during UI interactions. The parameter is the unique string to look for in the URL of new tab that is different from all other open tabs.

```
popup unique_string_to_look_for_in_url
{
steps..
steps..
}
```

For above example, if you are using Chrome browser and there is only 1 tab with 'c2-diamond-black' string in the URL then it will be below -

```
popup c2-diamond-black 
{
...
...
}
```

**Comment by hemanthsavasere** [comment]
Thank you very much.
