### ISSUE TITLE
Continue previous session, without restarting Chrome - use tagui step

### ISSUE THREAD

**Issue by hemanthsavasere** [kelaberetiv/TagUI#533]
Hi @kensoh,

I am trying to write a TAGUI script that adds items from the cart and checks out the purchases. I am writing separate TAGUI script for different changes, such as login, searching for items, checking out, etc.  

I wanted to know **if there's a way to continue and carry-over my login session while executing "checking out " script and "adding it to cart" script.**

**Comment by kensoh** [comment]
Hi @hemanthsavasere by default, TagUI will keep the same user profile for Chrome. When different sessions are launched, it will retain the cookies and session details. Unless for this website, each time you login and restart browser, its normal behaviour is to restart the previous session.

If that is the case, you can try using the tagui step, see more in modules section. So each series of steps is a workflow which you can call using tagui step. In this way, Chrome browser does not restart and it runs sequentially all the workflows you call.

https://github.com/kelaberetiv/TagUI#modules

**Comment by kensoh** [comment]
Closing the issue for now until further inputs!
