### ISSUE TITLE
Detect loading of page and take screenshot 

### ISSUE THREAD

**Issue by hemanthsavasere** [kelaberetiv/TagUI#534]
Hi @kensoh,

I wanted to know if there is any way to detect using TAGUI when the screen has changed and then based upon that, take a screenshot of the web page. I want to use this utility and integrate this as a module into the TAGUI.

How should as proceed?

Thanks & Regards,
Hemanth Savasere

**Comment by hemanthsavasere** [comment]
Hi @kensoh,

Also, the tutorial to the module function is not properly available.

Thanks & Regards,
Hemanth Savasere

**Comment by kensoh** [comment]
Hi @hemanthsavasere to use modules, refer to here - https://github.com/kelaberetiv/TagUI#modules

1. create a TagUI script, for example `sub_script`, of the steps you want to do
2. from main script you can use `tagui sub_script` to call the `sub_script` module

**Comment by kensoh** [comment]
For the other question on waiting until the screen change, it is answered in the following issues. The normal web element identifiers and image snapshots of UI elements can be used. You can try -

https://github.com/kelaberetiv/TagUI/issues/499#issuecomment-510927437
https://github.com/kelaberetiv/TagUI/issues/287#issuecomment-428440558

**Comment by kensoh** [comment]
After detecting the change you want, then use `snap page` (for website) or `snap page.png` (for whole screen) to take screenshot. More details on the snap step optional parameter in https://github.com/kelaberetiv/TagUI#steps-description

**Comment by hemanthsavasere** [comment]
Thanks for the help.
