### ISSUE TITLE
vision how to click 2nd occurrence image - try anchor image + offset

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#535]
vision click 2nd occurrence image how to write that statement
If same image appears multiple times - how do I click the nth occurrence of that image?  Overall, this vision related commands are quite less.

**Comment by kensoh** [comment]
There isn't an easy way to do this correctly. For example, how do user define which is the 2nd occurrence and which is the first occurrence? It will be relative to different interpretation, depending on the situation.

One way will be to use offset in x, y coordinates. For example, you can use hover step to hover the mouse at the first occurrence of the image, or another image that serves as the anchor image.

After that, you can use the helper functions mouse_x() and mouse_y() to get the current coordinates. Finally you can click on the x,y coordinates by doing an offset, eg -

```
hover anchor.png
x = mouse_x()
y = mouse_y()
x = x + 100
click (`x`,`y`)
```

Above example moves the mouse to the anchor image, adds the offset, and click on the target.

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/63328638-1c3aed00-c34e-11e9-95a1-73ead14a7d0a.png)
I get this error - any idea sir.
Thanks for the reply though

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/63329401-81431280-c34f-11e9-9493-eb959a05f0e7.png)
I got the mistake.  Anyways, I am having issue around how to get the variable outside into the vision command

**Comment by vrudhay** [comment]
Worked
