### ISSUE TITLE
DragDrop to absolute coordinates

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#537]
vision dragDrop(find('Corner.png'), find('GDBox.png'))
How can one put the destination as absolute coordinates?  These coordinates will be generally manipulated.

and:

vision dragDrop(find('GD.png').offset(500, 0)) - this is again relative - how to make this to move to lets say 350,400 absolute position.

**Comment by vrudhay** [comment]
I got the answer:
vision dragDrop(find('GD.png'), Location(700,350))

PS: lack of documentation is making a bit tough.

**Comment by kensoh** [comment]
Hi @vrudhay the method you used is custom SikuliX code, which i think you found via google.

To do this directly using TagUI, you can do below sequence -

```
hover GD.png
mouse down
hover (700,350)
mouse up
```

Visual automation details here - https://github.com/kelaberetiv/TagUI#visual-automation

If relative coordinates needed, example here - https://github.com/kelaberetiv/TagUI/issues/535#issuecomment-522890904

**Comment by vrudhay** [comment]
Worked!
