### ISSUE TITLE
[ctrl]c is working to copy text from app but [ctrl]v can't work

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#543]
![image](https://user-images.githubusercontent.com/6286626/63586812-ec931b80-c5bf-11e9-97fa-a10ddac84d29.png)

Why would Ctrl v not work?  Ctrl c is working to capture the result but not for Ctrl-v
keyboard [win]r
keyboard calc
keyboard [enter]
keyboard 17+34=
wait 1
keyboard [ctrl]c

keyboard [win]r
keyboard notepad
keyboard [enter]
wait 3
keyboard v[ctrl]

**Comment by vrudhay** [comment]
Tried [ctrl]v also!

**Comment by kensoh** [comment]
I haven't come across an issue with [ctrl]v to paste text from the clipboard. I don't have a Windows laptop now to replicate. Can you try the following and let me know what is the result?

1. try to do a sample script to open notepad, type some text, `[ctrl]a` and `[ctrl]c` to copy the test, then maybe do a `[enter]` and then `[ctrl]v`. If this works, this may isolate some problem with copying and pasting from calculator into notepad.

2. check the log file src\tagui.sikuli\tagui_windows.log to see what is the error message from SikuliX or if SikuliX process the ctrl + v command from TagUI successfully. This can help to isolate whether the problem happens somewhere in TagUI or SikuliX's engine.

**Comment by kensoh** [comment]
Closing issue until further inputs
