### ISSUE TITLE
OCR get text value for a field - use image anchor offset or keyboard

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#544]
![image](https://user-images.githubusercontent.com/6286626/63591425-66310680-c5cc-11e9-84f3-33e909932f71.png)

From the image above how do I exactly retrieve the Visit Time/Date:.
Should we cut that piece of screen?

**Comment by kensoh** [comment]
I assume this is not a website application but some desktop application.

You can do this by using anchor image (something like https://github.com/kelaberetiv/TagUI/issues/535). By providing image snapshots of `Gender / Age:`, you can hover the move there to detect the reference point. From there, you can add offset to provide the rectangle boundary to do the OCR. I show you an example below -

```
hover gender_anchor.png
x = mouse_x()
y = mouse_y()
top_left_x = x + 60
top_left_y = y - 20
bottom_right_x = x + 160
bottom_right_y = y + 20

// backticks pair `` is used to denote variables instead of text
read (`top_left_x`,`top_left_y`)-(`bottom_right_x`,`bottom_right_y`) to gender_age
```

For development and finding x,y coordinates offset, you can use the mouse_xy() function in TagUI live mode to return the current x,y coordinates. The above method is still in cutting edge release, so it is not yet in the TagUI documentation.

The second method, is if it is possible to use mouse or keyboard combinations to select the text to copy out, then you may want to consider doing that to copy to clipboard for pasting somewhere else.

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/64003428-db9b5a80-cb29-11e9-8d00-cc679d5ae61a.png)
![image](https://user-images.githubusercontent.com/6286626/64003441-e0600e80-cb29-11e9-8cb0-6083c466d230.png)

It tells cannot find so and so.  What could be the error.  Should I use Location function?

Pls. advise.

**Comment by kensoh** [comment]
Are you using the cutting edge version of TagUI? See below on installing this version -
https://github.com/kelaberetiv/TagUI#set-up

The feature is not in current packaged installation and requires users to overwrites with latest source files as per above steps in set up. This is to add delay from implementing new features to packaged installations, so that bugs can be found and fixed before release to production.

**Comment by vrudhay** [comment]
I saw that the version is same as before. Is there a way to know which tagUI version we are using?
Also, in the previous question, read doesnt substitute the top_left_x and other variables also.  
And if hard coded also it does not work.

yes, it is not in web rather on a pdf opened.

**Comment by kensoh** [comment]
Most likely you are using the packaged release and not the cutting edge version.

You can follow the setup steps below to download from GitHub and overwrite your current version, because the feature you are using is not yet in the packaged version - https://github.com/kelaberetiv/TagUI#set-up

**Comment by kensoh** [comment]
Thanks for your suggestion, I've added updated version number for cutting edge version.

If users type tagui and they have the cutting edge version installed, TagUI will show v5.5.

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/64227312-9a77c180-cf00-11e9-98f7-335261bd8ecc.png)
For some reason even after unzipping the tagui_master.zip, it is showing 5.0
Am I doing something wrong?

**Comment by kensoh** [comment]
As mentioned above, to get the cutting edge version, you have to follow the steps in below link on how to download the cutting edge version to overwrite your TagUI installation -

https://github.com/kelaberetiv/TagUI#set-up

**Comment by kensoh** [comment]
From above link, there is below steps. After overwriting, the tagui command will show v5.5.

>Tip - to try cutting edge version with the latest features, download master.zip to overwrite your existing packaged installation (be sure to manually select and move the folders & files inside master.zip's TagUI-master/src folder to replace your existing tagui/src folder, some OSes will delete existing target folders that are missing from source folder)

If it still shows v5.0, maybe there is another TagUI installation on your computer that is in the environment path variable. And that installation gets executed when you run tagui command. Let me know if you still run into issues!

**Comment by kensoh** [comment]
Closing for now, try above should work. If not let me know again!
