### ISSUE TITLE
Location function is not substituting variable

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#546]
![image](https://user-images.githubusercontent.com/6286626/64002036-c3760c00-cb26-11e9-9c95-ef8a49e31581.png)
Variables like x and y is not getting substituted within the Location function.  any idea?
rel_movex = mouse_x() + 600
rel_movey = mouse_y() + 100
tagui a_dragdrop.tagui
gd1_x = mouse_x() + 5
gd1_y = mouse_y() + 5

echo sd1_x
echo sd1_x+5
vision dragDrop(Location(`sd1_x`, `sd1_y`), Location(`gd1_x`, `gd1_y`))

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/64009844-43f03900-cb36-11e9-965a-574990091cc6.png)

even hardcoded xy coordinates is not fetching.  Any sikuli issues you foreesee?

**Comment by kensoh** [comment]
This is the not syntax to send variables to SikuliX. Using `sikuli_step()` is the way but this hacking should not be needed, I replied on the other issue using read step on a region - https://github.com/kelaberetiv/TagUI/issues/544#issuecomment-526672293
