### ISSUE TITLE
Getting the value from clipboard

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#547]
![image](https://user-images.githubusercontent.com/6286626/64010709-f248ae00-cb37-11e9-8587-3b6d43f869e5.png)

I have copied in a pdf into Ctrl + c using the mouse
mouse down
hover (1202,400)
mouse up

keyboard [ctrl]c

How do I now get into a variable?

**Comment by kensoh** [comment]
There isn't a step to save clipboard value to variable, but you can use the following -

```
vision output_sikuli_text(App.getClipboard())
clipboard = fetch_sikuli_text()
echo clipboard
```

In future, there may be a need to create a new clipboard step to copy / cut and paste clipboard.

```
clipboard copy
clipboard cut
```

```
clipboard paste
echo clipboard_result
```
