### ISSUE TITLE
Capturing open directory action while capturing web broswer actions

### ISSUE THREAD

**Issue by onenessboy** [kelaberetiv/TagUI#548]
I am try exploring TagUI browser action capture via chrome addon given in this repository.. in between web action, i would like to capture local action like, open a directory and open a ppt in powerpoint application and go back to web browser and continue actions... Is that possible with TagUI ?

**Comment by kensoh** [comment]
Hi @onenessboy oh that is not possible from the extension as Chrome extension only has the access to actions performed on the browser. For interaction with desktop applications, TagUI relies on the in-built SikuliX engine to do that visually. So users will have to capture snapshots of their desktop UI elements using tools such as snipping tool for Windows.

https://github.com/kelaberetiv/TagUI#visual-automation

Also, for the Chrome extension, I usually recommend selecting the element identifiers manually or copy XPath using Chrome. This gives users more control and choice to develop scripts that can be more readable and robust.

**Comment by kensoh** [comment]
Adding on, if your use case is selecting a file for upload, then maybe the `upload` step under pro steps can do it easily without having to rely on visual automation.

https://github.com/kelaberetiv/TagUI#steps-description

If you meant actually opening Powerpoint and load a slide deck, then this action will require using TagUI visual automation feature.

**Comment by onenessboy** [comment]
> Adding on, if your use case is selecting a file for upload, then maybe the `upload` step under pro steps can do it easily without having to rely on visual automation.
> 
> https://github.com/kelaberetiv/TagUI#steps-description
> 
> If you meant actually opening Powerpoint and load a slide deck, then this action will require using TagUI visual automation feature.

First of all thank you for developing this wonderful repository.  and coming to my question, Yes I already started using sikuli methos to capture and able to open the ppt.  Actually there are couple of question to me
1 . What I meant to clubbed action of browser + local desktop action.....for example...open abcd.com...--> click on dashboard --> there is image --> copy it and now start sikuli action..open start menu --> cmd type powerpnt --> open parituclar file -> now go to slide 3 for example --> copy and replace image capture from broswer in this file...
In above scenario, chrome extension able to export broweraction, but not able to add sikuli funcation which i did into flow... so requirment is to capture entire flow ( browser action + visual automation step into flow ? is that possble ?

**Comment by kensoh** [comment]
I see.. 

1. You can try to do it in the same way as you do manually visually, or you can see if using keystrokes combinations will be able to select the slide you want and do what is needed. Beside visual automation, there is automation of keyboard and mouse. So you can perform advance control of the computer to do things - https://github.com/kelaberetiv/TagUI#visual-automation

2. Oh TagUI script is a text file. You can edit with a text editor to include the steps that you want to do. For example `click start_menu.png` or `type search_box.png as powerpoint_filename` and so on. More on TagUI syntax here (https://github.com/kelaberetiv/TagUI#steps-description). SikuliX can also do OCR with the read step, but from the use case of powerpoint, maybe using keyboard combinations would be easier to type in text compared to visually looking for text.

Below is a sample automation that open MS Word and make modifications to it, maybe useful as example to you - https://github.com/aimakerspace/TagUI-Bricks/tree/development/MS-Word-Letter

**Comment by onenessboy** [comment]
> I see..
> 
> 1. You can try to do it in the same way as you do manually visually, or you can see if using keystrokes combinations will be able to select the slide you want and do what is needed. Beside visual automation, there is automation of keyboard and mouse. So you can perform advance control of the computer to do things - https://github.com/kelaberetiv/TagUI#visual-automation
> 2. Oh TagUI script is a text file. You can edit with a text editor to include the steps that you want to do. For example `click start_menu.png` or `type search_box.png as powerpoint_filename` and so on. More on TagUI syntax here (https://github.com/kelaberetiv/TagUI#steps-description). SikuliX can also do OCR with the read step, but from the use case of powerpoint, maybe using keyboard combinations would be easier to type in text compared to visually looking for text.
> 
> Below is a sample automation that open MS Word and make modifications to it, maybe useful as example to you - https://github.com/aimakerspace/TagUI-Bricks/tree/development/MS-Word-Letter

Thank you for detailed explanation i will explore those topics.,
Till now what I achieved:
 I am able to create manually all these steps manually (at least 90% of steps ) now... 

The below is tricky thing I would like to experiment

As that chrome extension is capable of exporting steps of web broswer, when I start desktop action, its not export those action into tagui script ..

to put in better way, a layman 
Step1--> i open a chrome broweser --> 
Step2 --click on tagui extension --> 
step 3: click start recording action --> 
step 4:open gmail.com --> 
step 5:enter my user name and password --> 
step 6:now click on windows start button  --> 
step 7: open powerpnt --> browe directory -->
step 8: click on file.ppt and close it

Now when i see that export content I see it writes tagui code till step 5 only...no desktop action being recorded into script . what I require is if we can make extension to record desktop actions too into tagui script which that extension generates ?

The idea behind is instead of manual coding if it could record all browser and desktop actions and makes it to tagui script be really good. In this case, user really does not need to bother any changes overall way he/she interacts with browser and UI actions... any idea ?

**Comment by kensoh** [comment]
I see, that is technically not possible now. There are some Python libraries for recording desktop actions but Chrome cannot do this recording of desktop actions.

Also, many commercial RPA tools would be able to record both desktop actions and web browser actions, for example UiPath. But I think the web and desktop recording is done separately. I don't think any open-source free tool does both recording of desktop and browser actions now.

**Comment by kensoh** [comment]
Closing the issue for now, as technically the current architecture can't do something like this without imposing new dependencies such as Python. Then it would lose the unzip-and-run easy distribution feature.
