### ISSUE TITLE
TagUI RPA software (commercial use and license conditions) - Apache 2.0

### ISSUE THREAD

**Issue by saketlopes** [kelaberetiv/TagUI#554]
Dear Sir,

I am looking for RPA tool for my organization need, I found TAGUI open source RPA tool.

I did few feasibility checks of requirement with TAGUI RPA tool.

If I want to use TAGUI in my organization, can you please let us know which license I need to check avoid any legal impact?

Thank you.

Best Regards

**Comment by kensoh** [comment]
Hi @saketlopes TagUI is licensed under Apache 2.0. It can be used freely for commercial purposes, including charging money for RPA services to implement TagUI, or building on TagUI to offer another paid RPA product or service.

You can find details of the license, its permissions, limitations, and conditions here -
https://github.com/kelaberetiv/TagUI/blob/master/LICENSE.md

Mainly, besides crediting the source of the software to AI Singapore and / or this GitHub page, the license and copyright notice above should be included in deployments, and if changes are made to the code they should be documented as part of the deployment or distribution. There is no liability or warranty for use of TagUI, and the TagUI trademark belongs to AI Singapore, so users can't develop a new software and call it TagUI to sell.

Let me know if you have more questions, of have further roadblocks in using TagUI in your organisation. You can post to this issue or create a new issue for specific usage / feature / bug questions.

**Comment by saketlopes** [comment]
Thanks , kensoh.

You have created a wonderful tool. 
I have created various automation cases with TAGUI.  
With this information I can deploy automation to other users in my organization.
