### ISSUE TITLE
Every time chrome comes up saying 'Restore pages' - may be it is aborting

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#557]
![image](https://user-images.githubusercontent.com/6286626/64403137-1d318580-d095-11e9-9e7c-f128904b2d9a.png)

Every time chrome comes up saying 'Restore pages' - may be it is aborting in the previous run / session execution.

**Comment by kensoh** [comment]
Hi @vrudhay this is expected behaviour. I have not found any way for TagUI to close Chrome browser other than searching for its process and killing it. If you or your network have other suggestions how to close it gracefully, I'll appreciate you to share!

**Comment by kensoh** [comment]
Closing issue for now until further inputs

**Comment by vrudhay** [comment]
Ok Kensoh - I got it.  Thanks.
