### ISSUE TITLE
If 2nd window is opened, keystrokes not working - replicate normal actions

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#558]
![image](https://user-images.githubusercontent.com/6286626/64419310-40226080-d0ba-11e9-8af1-7cd537c0ecc8.png)

In the above sample - first section is open the calculator, do some work and copy result. 
second section - open excel and paste the result (this fails)
Probably this is because, the control is still on the first window opened.
How do we probably bring the control to the new window which is on foreground?

**Comment by kensoh** [comment]
To do so, replicate the normal user actions. If normally after opening Excel it is not in the foreground and in focus, user will need to click on the Excel tab  in taskbar to bring to focus before entering text, or click on somewhere in the Excel window.

You can try to do a click step on the taskbar for Excel or somewhere unique on the Excel window, before using keyboard step to type into the Excel application. Also, I think accessing clipboard seems to be a useful feature, let me create an issue to track this for development!

**Comment by kensoh** [comment]
Issue created at https://github.com/kelaberetiv/TagUI/issues/559 (you can subscribe to that issue so that you will receive notification once it is implemented in the cutting edge version)

**Comment by kensoh** [comment]
Closing issue for now, but let me know if trying above suggestion do not work!
