### ISSUE TITLE
Helper Script not working - use end_processes.cmd directly

### ISSUE THREAD

**Issue by sandeep14897** [kelaberetiv/TagUI#560]
Hello @kensoh 

Below is the error i am facing while executing tagui.

I guess the process are runiing in the back ground;

![Tagui Error_msg](https://user-images.githubusercontent.com/37222769/64520569-6e738c00-d2c4-11e9-9906-f9a84d85a4a7.PNG)

This is the error i am facing while executing my batch file.

Below is the batch file:

![Tagui_BatchFile](https://user-images.githubusercontent.com/37222769/64520689-aa0e5600-d2c4-11e9-8ddb-79319dce18d3.PNG)

**Comment by kensoh** [comment]
For Windows, the helper script is `src\end_processes.cmd` -https://github.com/kelaberetiv/TagUI/blob/master/src/end_processes.cmd

From above error message it looks like your Chrome process (based on PHP) is still running, so TagUI cannot open that out file with write access. Try calling end_processes.cmd directly in your batch file to see if that work, for eg -

```
@echo off
end_processes
cd ...
tagui ..
```

**Comment by kensoh** [comment]
There are advanced methods used in the helper script above that will search for the TagUI processes in memory to kill them and let user use TagUI on a fresh state.

The use case when I developed them is a user sometimes use Ctrl + C to forcefully kill TagUI, so there are remaining processes in memory. But the scripts can be used for other use cases.

**Comment by kensoh** [comment]
Closing the issue for now, but please let me know if above suggestion does not solve the problem!
