### ISSUE TITLE
Login element without ID - considering using XPath to identify web elements

### ISSUE THREAD

**Issue by Fry115** [kelaberetiv/TagUI#561]
Hi Ken Soh,

I am trying to enter a login from a page that does not handle "ID":

![image](https://user-images.githubusercontent.com/54330118/64565649-9dbce400-d32a-11e9-8c37-045b648515ac.png)

At the time of entering the username and password, it indicates that it cannot find the entry:

![image](https://user-images.githubusercontent.com/54330118/64565861-0d32d380-d32b-11e9-89ab-f99c229babf6.png)

![image](https://user-images.githubusercontent.com/54330118/64565708-bfb66680-d32a-11e9-8512-bbc7947eea14.png)

Grettings.

**Comment by kensoh** [comment]
This is a question how to use XPath, not how to use TagUI.

Check this - https://github.com/kelaberetiv/TagUI#find-xpath-of-web-element
And this intro to XPath - https://builtvisible.com/seo-guide-to-xpath

**Comment by kensoh** [comment]
Let me know if above suggestions on XPath works, or if the webpage can be made accessible to public, you can let me know which URL I can use so that I can take a look to check.

**Comment by Fry115** [comment]
Hi Ken Soh,

For some reason I need to position in the box with “click” step, then with type step write the user, the first time this happens to me, anyway thanks for your response.

![image](https://user-images.githubusercontent.com/54330118/64622245-63505700-d3bd-11e9-8481-2bf7d58084d1.png)


Greetings.

**Comment by kensoh** [comment]
I see.. That's unusual, maybe the website need some time to react. Because the type step will already include a click event to Chrome to click on the text box. But maybe the events of click and type happens too fast and not working for this site, so you separate them.
