### ISSUE TITLE
XY Coordinates to be casted to integer by default!

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#562]
![image](https://user-images.githubusercontent.com/6286626/64592262-3efa7780-d3c9-11e9-8cbb-09d9b4f0fd33.png)

![image](https://user-images.githubusercontent.com/6286626/64592286-46218580-d3c9-11e9-88e7-6611c29a3d79.png)

If you see the code - the X and Y coordinates are going properly - but click is failing with cannot find error.  That means, somewhere it is assuming it is a string.  Should you probably cast it within the code itself?

**Comment by vrudhay** [comment]
//-- This is working
casper.then(function() {{techo('click '+abs_file('('+x+', '+y+')')+''); var fs = require('fs');
if (!sikuli_step('click '+abs_file('('+x+', '+y+')')+'')) if (!fs.exists(''+abs_file('('+x+', '+y+')')+''))
this.echo('ERROR - cannot find image file '+abs_file('('+x+', '+y+')')+'').exit(); else
this.echo('ERROR - cannot find '+abs_file('('+x+', '+y+')')+' on screen').exit(); this.wait(0);}});


//-- This is not working
casper.then(function() {{techo('click ('+abc+')');
casper.waitFor(function check() {return check_tx('('+abc+')');},
function then() {this.click(tx('('+abc+')'));},
function timeout() {this.echo('ERROR - cannot find ('+abc+')').exit();});}});

Should we use abs_file to convert it to proper integer?
Or, should we avoid using tx( - so that it is not text?

**Comment by kensoh** [comment]
Oh you have not seen the example here under helper functions - 
https://github.com/kelaberetiv/TagUI#helper-functions

The problem is with your syntax. Below works. If you lump the x and y and comma together, TagUI will not be able to recognize that this is an (x,y) coordinates identifier. Because there can be XPath identifiers that also start and end with round brackets ().

```
x = 100
y = 200
click (`x`,`y`)
```

**Comment by kensoh** [comment]
Closing the issue but let me know if that cannot work! Documentation is not as complete as I hope due to prioritising resource to fast user support, and also working on bug fixes and new features.

**Comment by vrudhay** [comment]
Since the number of lines were more - 1 for x and 1 for y and then to add the offset - thought of putting one liner called 'posFrom' and 'posTo' and call separate module which does the rest.
Anyways, prioritization is yours!

**Comment by kensoh** [comment]
(the adding can be done in-line but you will have to do casting)

Thanks for the suggestion! Not planning for a drag and drop step for now. For clicking at 2 different locations on the screen, you can use select step.
