### ISSUE TITLE
Upload file using upload step with CSS selectors - examples, reference here

### ISSUE THREAD

**Issue by Aut-ui** [kelaberetiv/TagUI#564]
Hello @kensoh i hope you are fine.

I have a doubt with the:
upload element (CSS selector only) as filename to upload.
I have a web page and I need to upload some files, I have tried the following steps but I cannot load:

upload #uploadFile > input[type="file"] as VCTO.TXT

upload #textoDatos as VCTO.TXT

The code to upload in the page is this:

![image](https://user-images.githubusercontent.com/55210156/64729255-2f575d80-d4b3-11e9-98dd-1f5299dd1e69.png)

Thanks.

**Comment by kensoh** [comment]
For CSS selectors, class is `.` and `#` is ID. For name can use `[attribute=value]` format -
https://www.w3schools.com/cssref/css_selectors.asp

Try if the following works for you!

```
upload .textoDatos as VCTO.TXT
```
```
upload [name="uploadFile"] as VCTO.TXT
```

**Comment by kensoh** [comment]
PS - hi @Aut-ui welcome to joining GitHub and raising your first issue!

**Comment by kensoh** [comment]
Closing issue for now until further input
