### ISSUE TITLE
Unexpected result from loop in tagui - refer to example / doc for syntax

### ISSUE THREAD

**Issue by Lion666** [kelaberetiv/TagUI#565]
I use a simple code describing basic usage of a loop in tagui but the result is unexpected. Could you help me understand what went wrong and how to fix this?
I tried to replicate basic example from that website: [https://www.rpa-sg.org/TagUI-Commands/for.php](url) 

`for (n=0; n<10; n+=2)
{
    echo "n = " + n
}`

Expected result: 
`n = 0
n = 2
n = 4
n = 6
n = 8`

Actual result captured from the log: 
`START - automation started - Thu Sep 12 2019 14:06:53 GMT+0200 (Romance Daylight Time)
n = 10
FINISH - automation finished - 0.3s`

My Java version is 1.8.0_152. Java Hotspot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode).

**Comment by kensoh** [comment]
Oh my friend just went for TomorrowLand in Antwerp recently. I am now too old and with baby, otherwise I would love to join one of the EDM festivals in Europe. Miss the partying times!
