### ISSUE TITLE
I cannot click anything inside an iframe - pending replication code / logs

### ISSUE THREAD

**Issue by lchojnowski** [kelaberetiv/TagUI#572]
I have a struggle with a one of our bank websites because it's impossible to actually "click" text inside an this structure:

![image](https://user-images.githubusercontent.com/170290/65203893-cc565f80-da8c-11e9-9fc8-ed1c773a8230.png)

Main content which I need to click lays in #main frame:

![image](https://user-images.githubusercontent.com/170290/65203910-e2642000-da8c-11e9-8e54-2e36859e9797.png)

And it has to be clicked here:

![image](https://user-images.githubusercontent.com/170290/65204000-eee87880-da8c-11e9-855e-c4386317882e.png)

Unfortunate, it's not possible to click it in any way. I'm guessing that it's somehow related to selecting frames. Can you help me somehow with that, or it's just a bug?

**Comment by kensoh** [comment]
It'll be hard to help or access whether it's a bug because I assume this is a private website which I can't access. Can you share the code that you used to try to click on the web element? The minimal replication steps that you do to experience the issue, and any error messages?

**Comment by kensoh** [comment]
As with another open issue, make sure that you are using the cutting edge version. Below are the steps to set it up. There may be a recent change in Chrome behaviour, so there is a patch to make frames work correctly with current version of Chrome (specifically, by adding x, y offsets to the UI elements when interacting with those elements in a frame).

https://github.com/kelaberetiv/TagUI#set-up

**Comment by kensoh** [comment]
Base on above limited info from the screenshots, it looks like a frame within a frame. The syntax would be something like below. But needs some experimenting, because the webpage main frame does not seem to be a frame (it's shown as a frameset but not a frame node).

```
frame mainFrame | main
{
// do the steps needed
}
```

If it is not a frame and the first level frame is the one with id / name 'main', then syntax is
```
frame main
{
// do the steps needed
}
```

**Comment by lchojnowski** [comment]
Works! Thank you. I think will be great to update documentation here :-).

**Comment by kensoh** [comment]
Adding on, an example of how to use frame syntax in the samples script -
https://github.com/kelaberetiv/TagUI/blob/master/src/samples/9_misc

And the frame syntax in the main documentation pro steps -
https://github.com/kelaberetiv/TagUI#steps-description
