### ISSUE TITLE
Cannot run tagui on Chrome - pending user checks and replication

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#578]
raising from user query

---

I’m writing to ask for your assistance. I have started using TagUI and start some recording using TagUI chrome extension tool. When I am running the TagUI file on command prompt, Automation started successfully but when I run the same with Google chrome, a blank page is opening and stopping there without any functionality. I am using windows 10 operating system with 64 bit.
 
Kindly find the below screen shot of a sample 1_yahoo file run and attached tagui_chrome.log  file. I will very obliged if you provide me help and suggestion.

[tagui_chrome.log](https://github.com/kelaberetiv/TagUI/files/3650507/tagui_chrome.log)

**Command Prompt without chrome command and with chrome command**

![unnamed](https://user-images.githubusercontent.com/10379601/65568853-cb8e6380-df8d-11e9-8488-5d319b1ac3dc.jpg)

**Another command prompt opens when I am running the same for chrome**

![unnamed-2](https://user-images.githubusercontent.com/10379601/65568871-d812bc00-df8d-11e9-932c-a83493c47696.jpg)

**Google chrome page is open when I run the chrome command.**

![unnamed-3](https://user-images.githubusercontent.com/10379601/65568896-e660d800-df8d-11e9-9b61-f27bd0fb7341.jpg)

**Comment by kensoh** [comment]
Hi Brahma, I haven't come across this issue before and other users have not reported something like this before. It seems like for some reason, TagUI hangs and unable to send further commands to Chrome. What is normally expected would be sending the URL to Chrome, for this Yahoo example.

```
[tagui] INPUT  -
[2] {"id":2,"method":"Page.navigate","params":{"url":"https://ca.yahoo.com"}}
[tagui] OUTPUT -
[2] {"id":2,"result":{"frameId":"71728F87A821162B2C926AE5ACA48291","loaderId":"1FAA8C3A94D875A0DE3BAB7519F598FE"}}
```

Can you test with another laptop from your friend or colleague, to see if the same issue happens? If your work laptop has problem, try using your personal laptop to see if it happens. Not sure if it is because of network or firewall issue that is blocking access in some way.

**Comment by brahmanath** [comment]
Thanks for posting, I have uninstalled some antivirus(avast,adware) from my system. Now it’s working fine. Thanks for your help.

**Comment by kensoh** [comment]
That's great! Thanks for the update Brahma, and have fun using TagUI :)
