### ISSUE TITLE
Fetching data from database (Sql, Oracle etc) using TagUI - use run step

### ISSUE THREAD

**Issue by brahmanath** [kelaberetiv/TagUI#579]
Hi 

I need to fetch some user data from my SQL database for sending mail/message to particular user. Could you please guide me how I can interact to database and get/update/delete the record using TagUI?
Is there any tool that support the same and I need to download the same? or something else. I want the whole process automate. Please help.

**Comment by kensoh** [comment]
This is a duplicate issue, see https://github.com/kelaberetiv/TagUI/issues/112 on how to run SQL statements to read and write to your database. The idea is to generate a SQL script to be executed by your database command line tool.

It will be different tool depending on your database. After printing the output, will have to parse to extract the data. Above issue has example.

**Comment by kensoh** [comment]
Closing issue for now until further inputs, but let me know if any question!
