### ISSUE TITLE
Chrome recorder ERROR - steps did not start with opening an url

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#581]
user query

---

Hi. I received this when I started the recording. Any suggestions on correcting this error?

**Comment by kensoh** [comment]
The recorder sometimes has problem receiving the current URL from Chrome, you can replace it with the URL after copying out the recorded script.

Alternatively, consider writing your script manually and using XPath identifiers. It can be copied directly from Chrome or manually written in an expressive powerful way -

https://github.com/kelaberetiv/TagUI#find-xpath-of-web-element

For questions and issues, raise to GitHub issues page, so other users can benefit from your question - https://github.com/kelaberetiv/TagUI/issues

**Comment by jagrati639** [comment]
"The recorder sometimes has problem receiving the current URL from Chrome, you can replace it with the URL after copying out the recorded script."  => There is no script generated at all. Just the error.

**Comment by kensoh** [comment]
Sorry @jagrati639, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Can you see if the solution by @kelvinl22 here works for you? - https://github.com/kelaberetiv/TagUI/issues/852#issuecomment-703994021
