### ISSUE TITLE
Need help on parsing PDF table data - use keyboard step and clipboard()

### ISSUE THREAD

**Issue by mandar-bhambure** [kelaberetiv/TagUI#584]
Hi Ken,
I am using TagUI to read contents from a pdf file which has data in tabular format, and facing issues in reading the contents in correct format.

Following is my script,

dclick testPdf.png
wait 30
read page.png to text_on_screen
wait 30
echo text_on_screen

On CLI I don't see the output in correct text format. Please check attached image.

![image](https://user-images.githubusercontent.com/14823299/66265643-94df0580-e837-11e9-9dae-bc8ed9a7888a.png)

I need a help on following,
1. How can I retrieve the text (from PDF table) in correct format ?
2 Or, how can I execute command from other OCR library such as tesseract?

Please advice.

Thanks!
Regards,
Mandar.

**Comment by kensoh** [comment]
Hi Mandar, I have not come across this issue or other users mention this issue before with OCR.

To use other OCR library such as Tesseract, you can use the `run` step to run the tesseract command in your screenshot above. That should give you the best result, as you can do different settings with the tesseract command line tool.

Alternatively, in the cutting edge version, there is now a clipboard() helper function. You can tell TagUI to open the PDF file, then use `keyboard` step to send [ctrl]a and then [ctrl]c to copy all the PDF text. After that you can do `result = clipboard();` to retrieve the text directly from clipboard. Finally you can using JavaScript string manipulation functions to extract the info you want.

Details on installing the cutting edge version here -
https://github.com/kelaberetiv/TagUI#set-up

**Comment by mandar-bhambure** [comment]
Hi Ken,
keyboard [ctrl]a + keyboard [ctrl]c worked for me.
I need have a further query. Is it possible to store tables rows into an array and use it further ?
currently, when I echo clipboard, I see every cell is printed on new row in CLI.

Thanks!
Regards,
Mandar.

**Comment by kensoh** [comment]
I see.. I'm afraid what you copy to clipboard will be what is available to TagUI. Depending on the text information, you may be able to use JavaScript string manipulation to split and parse it into an array for usage or storage later. But this method will be tricky and not easy to do.

You can explore if there are other solutions out there which can process OCR rows, from what I heard, native OCR and Tesseract is still not good at recognising and retrieve text in table form. Providers such as Microsoft would be able to provide computer vision and OCR services for that.

**Comment by kensoh** [comment]
Closing the issue for now, but let me know if you have other inputs!
