### ISSUE TITLE
Scroll through a Windows services page on desktop - try some workarounds

### ISSUE THREAD

**Issue by ba700113** [kelaberetiv/TagUI#588]
Am trying to scroll through a windows services page to enable click an element that is not in view.
Can you guy help me a syntax that will help me do that. i tried the code below but didnt work.
I was able to use the code below to scroll on a web page. but its not working for me windows services page

vision type(Key.PAGE_DOWN)

**Comment by ba700113** [comment]
so on the windows services page, when i execute my script it tell me it clicked the item i wanted to click but i dont see the click. i see the cursor move to the item but does not click it. the script will complete and tell me it clicked it.

**what am trying to do it to click anywhere on the windows services page and type in the word radiant**
here is my code: 
click page.png
type page.png as radiant

what code will you use to do the scenario i described above in bold. any idea is much appreciated

**Comment by kensoh** [comment]
Your code looks correct, but try using a different name for the image. page.png is a reserved keyword to mean the whole screen. Maybe that is what causing the error behaviour.

**Comment by ba700113** [comment]
i renamed the image but still does not click the image. it only hovers on it.
one thing that i would mention is that the cursor moves to the picture but the cursor turns to a double end arrow and does not click. the picture below is the screen i like to click an item on

![windows_services](https://user-images.githubusercontent.com/56697456/67207696-127f4580-f3e2-11e9-8f6b-d0af9fcaf057.PNG)

**Comment by kensoh** [comment]
I see, this problem is very strange, no other user has encountered this before..

1. Does a normal click on an image of the Windows start button work?

2. Does a manual clicking on this application work correctly?

3. Try using `click (x,y)` to see if it clicks on the application

**Comment by kensoh** [comment]
Adding on, 4 - after hovering to the picture, try using `mouse down` and then `mouse up` to simulate a mouse click, to see if that somehow works for this strange situation.

**Comment by kensoh** [comment]
Lastly, check in tagui\src\tagui.sikuli folder. There is a log file of what happens when the click image action is done. Check to see if the log contains some clues on what's wrong with clicking on the app.

**Comment by kensoh** [comment]
Closing issue for now until further inputs!
