### ISSUE TITLE
Tagui visual automation issue on Remote Desktop server - duplicated issue

### ISSUE THREAD

**Issue by onenessboy** [kelaberetiv/TagUI#590]
Hi,

Here what I observed:

Locally using windows 10 -->using 100 % magnification -- my script working fine as intended
RDP to Remote server via RDP --> to a machine with Windows Server 2019 (I have 100 % magnification at local machine , so that when RDP it the target VM also use same magnification)
setup all python tagui there, ran same program with visual automation, its not moving cursor to inteded places..clicking at wrong places...
Locally same program works fine.

so is there any limitation of tagui python with version of windows  ? or on RDP it wont work properly

please suggest..

**Comment by kensoh** [comment]
Closing this issue as this sounds like is for TagUI for Python and not this TagUI project, and I saw your duplicated issue over there - https://github.com/tebelorg/TagUI-Python/issues/70
