### ISSUE TITLE
PhantomJS error after upgrading to macOS Catalina - see solution here

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#601]
After upgrading to macOS Catalina release, users may encounter a popup window saying that phantomjs is an unrecognised application downloaded from the internet. This is because Catalina release implements stricter security and access controls for applications running on macOS.

PS - PhantomJS is the execution engine for TagUI and is a critical component for TagUI to work.

---

I don't have a screenshot of the popup window anymore because I have fixed this on my laptop, it looks something similar to below image (for Terraform, another popular app that's also affected)
<img width="532" alt="terraform" src="https://user-images.githubusercontent.com/10379601/67822977-3e927900-fafc-11e9-96d4-11f170bd068d.png">

**Comment by kensoh** [comment]
1. From macOS Finder, go to the folder where you unzipped and installed TagUI.

2. Go to src --> phantomjs --> bin folder. Right-click phantomjs icon and click Open.

2. If a macOS prompt appears to ask whether to open the application because it is untrusted and downloaded from the internet, click Open to add the app to list of trusted apps.

3. If you enter a PhantomJS terminal prompt, press Ctrl+C to exit.

4. Try running TagUI again and the popup warning message should disappear.

**Comment by kensoh** [comment]
Updated to readme with a link to this solution, keeping issue open for time being before closing.

**Comment by lajennylove** [comment]
What should I do if I installed phantomjs with homebrew?
`$ brew install phantomjs`

**Comment by kensoh** [comment]
Hi @lajennylove that should be ok. If you follow the setup steps here, the packaged zip will come with PhantomJS and TagUI will use the one that comes with it. https://tagui.readthedocs.io/en/latest/setup.html

**Comment by komirand** [comment]
i was able to resolve above issue by following these steps from another thread, i can now run the sample flows from the initial installation. But i have to make sure that run this <export HOMEBREW_NO_INSTALL_CLEANUP=1> on the machine macos recently updated to monterey using m1 chip.
https://github.com/kelaberetiv/TagUI/issues/1136#issuecomment-977160519
