### ISSUE TITLE
Using variable for element id - use backticks `` when text is expected

### ISSUE THREAD

**Issue by LEES0159** [kelaberetiv/TagUI#612]
Dear Mr Soh, 

Not familiar with html and unable to find a suitable used case online. <not to mention first time asking a qn on this platform  #too>
Task is "webscraping" and created a script that runs until the step:

click//a[@id="addToProject_0"]
click//a[@id="addToProject_1"]
...
click//a[@id="addToProject_4"]

Did not work when i assigned a tmp string for the "addToProject_*" but if i use the above as is, the id is detectable.

Logfile and script of the rather futile/ messy attempt as attached for reference.

Many apologies and thanks in advance! :) Hoping to get my first successful attempt of rpa!

[ura_transac_v2.log](https://github.com/kelaberetiv/TagUI/files/3801743/ura_transac_v2.log)
[ura_transac_v2.zip](https://github.com/kelaberetiv/TagUI/files/3801744/ura_transac_v2.zip)

**Comment by kensoh** [comment]
Hi @LEES0159 using variables is covered in various parts of the read and samples. Because TagUI default context is text, to denote that something is variable when text is expected, use backticks `` in the following manner -

```
element_x = "addToProject_0"
click //a[@id="`element_x`"]
```

**Comment by kensoh** [comment]
Above should work, and have fun!

**Comment by kensoh** [comment]
Closing issue for now until further inputs!

**Comment by LEES0159** [comment]
Thanks so much! it worked perfectly as intended! Will read the examples more closely for guidance in future! :)

**Comment by kensoh** [comment]
Welcome! Though I try to be concise, there's a lot to cover in the readme due to the scope of RPA, so there may sometimes be too much information to be able to digest. Have fun using the tool!
