### ISSUE TITLE
How to use apostrophe in vision type() - use keyboard step and \'

### ISSUE THREAD

**Issue by shahidshaikhleaque** [kelaberetiv/TagUI#616]
Hi @kensoh ,

I am successfully copied one value into variable and I am trying to send email through outlook with subject including that variable value.
However I have to used that in subject email but it is printing name of variable instead of value.
I have echoed the value and it is printing correctly as 'en' on console.

Ex :- vision type("The locale value is" + Locale).
Could you please suggest correct way of implementing the same.

**Comment by kensoh** [comment]
Hi @shahidshaikhleaque for the current [cutting edge release](https://github.com/kelaberetiv/TagUI#set-up), there is no need to do this.

You can achieve the same with `keyboard` step -

```
keyboard The locale value is `Locale`
```

To type ` you can use
```
keyboard white isn\'t black
```

sample script

```
Locale = 'en'
keyboard The locale value is `Locale`[enter]
keyboard white isn\'t black[enter]
```

**Comment by shahidshaikhleaque** [comment]
Thanks @kensoh it's working as expected now.
Thanks again for your time & help
