### ISSUE TITLE
Error while selecting a dropdown value - pending replication details

### ISSUE THREAD

**Issue by nithish407** [kelaberetiv/TagUI#617]
I am having dropdown values as 
-Propuesta
-Evaluation
by using xpath i have written as 
select /html/body/div[19]/div[1]/select as Evaluación
but i am not able to select the option.And also i tried another command as 
click /html/body/div[19]/div[1]/select
select //*/html/body/div[19]/div[1]/select as Evaluación
getting error cannot find the element.
can you please give me the solution

**Comment by kensoh** [comment]
Hi @nithish407 the parameter is the option value, not the option text. Try inspecting the dropdown options to see the values. Also, can you paste your sample script here to replicate the issue?

**Comment by kensoh** [comment]
(closing issue for the time being until further inputs!)
