### ISSUE TITLE
How to simulate mouse scroll on a webpage or desktop app?

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#618]
user query

**Comment by kensoh** [comment]
There is no scroll step as it is not commonly used for navigating and interacting with UI elements. Also, it is likely to be inconsistent when an automation is deployed to another computer. Using `keyboard [pagedown]`/ `keyboard [down]` or `keyboard [pageup]` / `keyboard [up]` is better.

However, if there is a use scenario where above is not possible or impractical, users can use the vision step to send custom SikuliX commands there to simulate a mouse scroll, the 2nd parameter is the number of scroll steps to make.

For eg, below simulates scrolling up 20 steps and then down 10 steps.

```
vision wheel(WHEEL_UP, 20)
vision wheel(WHEEL_DOWN, 10)
```

**Comment by supercena** [comment]
真牛逼
