### ISSUE TITLE
Output csv with semicolon instead of comma in table step - local mod

### ISSUE THREAD

**Issue by idiogolima** [kelaberetiv/TagUI#620]
The table function for csv is very useful!

table //*[@id="tabela-exemplo"]/table to arquivo.csv

Is it possible to change the comma separator to semicolon?

Here in Brazil we use semicolons, it makes things easier.

**Comment by kensoh** [comment]
I see, it only saves with `,` for separator.  If you want to change it, you have to modify this file src\tagui_header.js and search for `function save_table` for the part to change.

Change the `,` in the following parts of the code to `;` and try again!
```
row_data = row_data + '","'
```
```
(row_data.substr(0,2) == '",')
```

**Comment by idiogolima** [comment]
Thank you very much!
