### ISSUE TITLE
How to solve captcha - use api step and captcha solving services

### ISSUE THREAD

**Issue by Fry115** [kelaberetiv/TagUI#622]
Hi Ken, how are you? I have a query ... tagui is able to solve captcha, for example I have the following page (www.acepta.com), when I try to enter tagui, it throws me the following image:

![snap1](https://user-images.githubusercontent.com/54330118/68619277-eb300b80-04a9-11ea-8ff5-0bb38a9db582.png)

Any idea how to solve that?

Regards.

**Comment by kensoh** [comment]
Hi @Fry115 I'm tired busy taking care of baby haha. In theory you can use api step to call paid captcha solving services to do this, but I have not tried it before.

You can google captcha solving service for the different service providers and see if they meet your requirements.

**Comment by Fry115** [comment]
Hi ken,

First of all ... congratulations on your baby and thanks once again for guiding me.
