### ISSUE TITLE
Question on using report option and output to csv file - pending details

### ISSUE THREAD

**Issue by Don-Are** [kelaberetiv/TagUI#626]
Hi Ken Soh,

I am ashamed to ask this but I am new to this spectacular tool, my question is: how do I activate the option of report.csv?
He tried like this:
Click on `date ()` .TXT to report.csv

But it gives me an error.

**Comment by kensoh** [comment]
Hi @Don-Are can you tell me what you mean by option report.csv?

There is a reporting option by running `tagui script_name chrome report` for example.
More details on this here - https://github.com/kelaberetiv/TagUI#audit--reporting

For writing results to csv file, you can look at csv_row() example in helper functions section -
https://github.com/kelaberetiv/TagUI#helper-functions

**Comment by Don-Are** [comment]
Hi,

This are:

There is a reporting option by running tagui script_name chrome report for example.
More details on this here - https://github.com/kelaberetiv/TagUI#audit--reporting

I have one question more,
