### ISSUE TITLE
Visual Automation using Screenshot not working

### ISSUE THREAD

**Issue by xiaoyinglim** [kelaberetiv/TagUI#627]
I used the click "image name".png command to click on items on the website for visual automation. The click command worked a few days also but now it is not working. My friend, Fionne is also having the same problem. We already tried to redo the ss and made sure that the resolution was 100% or the recommended one. May I know how to solve this issue? Attached are my file codes.
[Uploading SGX.zip…]()

**Comment by kensoh** [comment]
(user closed as there is a duplicated issue created here https://github.com/kelaberetiv/TagUI/issues/628)
