### ISSUE TITLE
 If condition inside a while loop - no while loop, use for loop and break

### ISSUE THREAD

**Issue by jcarriv** [kelaberetiv/TagUI#630]
I could not find the problem in these conditions if inside an elementary while loop ... 
I would appreciate your help
:(

https://www.google.com
cols = 3
n = 1
max = 10
while  (n < max)
{
    validate = 'Row: [' + n + ']:' + cols + ' column. Not Equal'
    if (n == cols) 
    {
        validate = 'Row: [' + n + ']:' + cols + ' column. OK'
    }
	echo validate
 
    if ( n == 5 )
    {
      n = n + 3
    } 
    else
    {
      n = n + 1
    } 
}

_D:\tagui\src>tagui samples\easy chrome

START - automation started - Sun Nov 17 2019 17:30:44 GMT-0300 (Hora verano Suda
m├®rica Pac├¡fico)
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
Row: [1]:3 column. Not Equal
....
....

**Comment by kensoh** [comment]
There is no while loop in TagUI - https://github.com/kelaberetiv/TagUI#conditions-examples

It is not possible to implement due to technical limitation in CasperJS component when I designed an auto-wait feature as part of all automation steps. Use a for loop with break instead.

for n from 1 to 9
{
    if n equals to 4
        continue

    echo n

    if n equals to 7
        break
}
