### ISSUE TITLE
Extracting more data from a scroll table with fixed number of rows

### ISSUE THREAD

**Issue by xiaoyinglim** [kelaberetiv/TagUI#632]
Hi Mr Ken, for the extraction of data from the webpage, I was only able to extract 40 sets of data per run unless I use multiple for loops. The command prompt will show an error after it tries to extract the 41th of data. Is there any solution to extract more data without using multiple for loops? Because it will increase the chance of the company detecting the automation and blocking me from the website. My files are as attached.
https://send.firefox.com/download/5eeb3883770efb4e/#5xc07Ie3qMQb9OsbaC-f4Q

**Comment by kensoh** [comment]
This looks like the website is intentionally designed that way. If you inspect using Chrome browser, and scroll through the list, you will see that there are always 40 rows no matter where you scroll. This means that the design is such that the website will only render and keep 40 rows on the webpage at any one time.

![Screenshot 2019-11-20 at 1 46 26 PM](https://user-images.githubusercontent.com/10379601/69212418-362ddb00-0b9c-11ea-913b-ca9f41c11605.png)

Thus, you can never access the 41th row using `click (//*[@class="website-link"])[`row`]`

**Comment by kensoh** [comment]
Not sure if there is a solution, because if you are doing it manually, it is not easy to know which row is the next row after scrolling. The data in the columns are quite similar. Also, be sure to follow the T&C on website, to make sure you are not violating their terms of use.

**Comment by kensoh** [comment]
There is a `data-row-id` attribute for each row which seems unique. But I think you'll need a web developer who is an expert with developing websites to be able to find a way to use some creative JavaScript code to access all these rows without missing any or having duplicates.

**Comment by kensoh** [comment]
I don't think using multiple for loops will let you extract without duplicating data or missing data. Also, whether you use for loop or not, each interaction with the website will be tracked by the website. If your rate of access if much faster than what a normal user would, website can detect that you are browsing automatically and block. Be sure to follow the T&C on website, to make sure you are not violating their terms of use.

**Comment by xiaoyinglim** [comment]
> I don't think using multiple for loops will let you extract without duplicating data or missing data. Also, whether you use for loop or not, each interaction with the website will be tracked by the website. If your rate of access if much faster than what a normal user would, website can detect that you are browsing automatically and block. Be sure to follow the T&C on website, to make sure you are not violating their terms of use.

Yes, while extracting I do have some duplicate data haha. I will try and make sure my rate of access is not faster than a normal user. I guess I will just have to run multiple times because this website is tricky and risky to automate. Thanks for your opinion and warning ! :)

**Comment by kensoh** [comment]
You can make use of the `data-row-id` attribute to track if it is already a row that is accessed before. But it will be tricky to make sure there is no row missed. Not saying impossible, but need someone who is good with website development and JavaScript to find the solution. No probs!
