### ISSUE TITLE
Can't run chrome parameter with sudo (root) on Linux - see solution

### ISSUE THREAD

**Issue by muratcim** [kelaberetiv/TagUI#634]
Hi Ken,

When I want to run tagui chrome with sudo,the system was freezing.
As a result of my review of google-chrome command to run sudo "--no-sandox" parameter should be added.

Otherwise I get the following error.
[27984:27984:0826/093850.424373:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180

it worked when I changed the tagui code as follows.Can help for those who have the same problem
```
chrome_sandbox=""; 
if [ "$EUID" == 0 ];then chrome_sandbox="--no-sandbox"; fi
$chrome_command $chrome_sandbox $chrome_switches $window_size $headless_switch > /dev/null 2>&1 &
fi
```

**Comment by kensoh** [comment]
Hi Murat thanks for raising, and sharing your solution!

Yes this was not raised before, probably because most users would not be running as the root user. For the $EUID environment variable, is it something you define or how did that variable come about?

**Comment by muratcim** [comment]
Hi Ken,

The $EUID environment variable holds the current user's UID. Root's UID is 0.

**Comment by kensoh** [comment]
Thanks Murat, this is very useful and I learnt something new today!
