### ISSUE TITLE
Unable to click website link element - complicated web structure

### ISSUE THREAD

**Issue by xiaoyinglim** [kelaberetiv/TagUI#637]
Hi, I was able to extract the PDF Link of the first 40 company annual report. After using codes to navigate to other sets of data for extraction, the click (//*[@class="website-link"])[`n`] command did not click the PDF links hence I was not able to extract the links anymore. I tried to find ways to solve this problem but to no avail :( My files are as attached. Password is the same as last time.
https://send.firefox.com/download/8bc90d22c927d784/#Yz_OeOJap4g0bEXfjsMbFQ
https://send.firefox.com/download/6c0a1eb05fd9a86b/#mytARNl-Nbwwhk4KojS-JQ

**Comment by kensoh** [comment]
Hi @xiaoyinglim the website structure is complicated. It only renders 40 rows at one time and refreshes when user scroll down. It will be hard to write JS code that accurately processes each row. Most likely you will not be able to find out a working solution.....

I'm looping my friend @siowyisheng who has web development experience. He may be able to find an angle for a robust solution. But you have to prepare that this is not doable. Neither do expensive commercial RPA software be able to do something like this.

**Comment by siowyisheng** [comment]
For complicated usage, you may want to try a more low-level approach with selenium/scrapy (python) to interact with the javascript. In my opinion, TagUI is not so suitable to complicated usage like this but I'll give it a try.

**Comment by xiaoyinglim** [comment]
Alright thank you :) SGX is so funny though, the first time I tried extracting more pdf links it worked. I just have to use the command click //*[@class="sgx-scroll-shield-button--down sgx-icon--before"] to toggle down the table and it will help me click the hyperlink for the PDF Annual Report. But now it's not doable.

**Comment by siowyisheng** [comment]
No solution was found was this case.
