### ISSUE TITLE
[TAGUI][ERROR] - text missing for type()

### ISSUE THREAD

**Issue by VincentChong123** [kelaberetiv/TagUI#640]
Hi Ken,

Would you please kindly advise on error below? Thanks!
t.type('.gLFyf.gsfi as test google[enter]')
[TAGUI][ERROR] - text missing for type()

`
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import tagui as t
t.init()
True

t.url('https://www.google.com')
True
t.click('.gLFyf.gsfi')
True
t.type()
[TAGUI][ERROR] - target missing for type()
False

 t.type('testing')
[TAGUI][ERROR] - text missing for type()
False

 t.type('.gLFyf.gsfi as test google[enter]')
[TAGUI][ERROR] - text missing for type()
`

tagui chrome automation export result
click .gLFyf.gsfi
type .gLFyf.gsfi as test google[enter]

**Comment by kensoh** [comment]
Hi Vincent, above code looks like you are trying to run TagUI for Python tool.

For that project, raise issues at the repo here - https://github.com/tebelorg/TagUI-Python

I've raised an issue there for your question and answered there - https://github.com/tebelorg/TagUI-Python/issues/92
