### ISSUE TITLE
Audit and Reporting - tagui_report.csv column LOG FILE location

### ISSUE THREAD

**Issue by saketlopes** [kelaberetiv/TagUI#643]
Hello 

In Audit and reporting option create Log html file for respective automation script in same location.
Do we have any config setting to change location of log file ?

Regards
Saket Lopes

**Comment by kensoh** [comment]
Hi Saket, I'm afraid there isn't such an option now to configure this. However you can add a line in src\tagui (macOS / Linux) or src\tagui.cmd (Windows), to always move report files to a certain location. To do that, search for the line in above files with `tagui_report.php` and add a command  after that to move all the .html files to another folder. Copying @siowyisheng for info.

**Comment by saketlopes** [comment]
Thanks Kensoh

**Comment by Anujpalu24** [comment]
@siowyisheng @saketlopes  : Hello, if possible please share the code to move the file to desired location which we need to add under src\tagui.cmd

**Comment by ruthtxh** [comment]
Hi @Anujpalu24 

If you are on windows and you want to move the main report (without the running number) you can go to src\tagui.cmd and add the following line of code behind this line move /Y "%flow_file%.html.tmp" "%flow_file%.html" > nul
```
move /Y "%flow_file%.html" "your_folder_location" > nul
```
If you want to move the persistent running number reports you can replace your tagui_report.php file with the one in this attached zip file. Then specify your folder in the tagui_report.php file at the top.
![image](https://user-images.githubusercontent.com/40910744/164365595-d81f70cc-4570-422d-bd74-bc937ff9113c.png)

This will both shift the file to the specified folder, as well as update the csv file with the new file path 

![image](https://user-images.githubusercontent.com/40910744/164365400-ee7b6f54-173f-44ae-a5fe-5453933f24c6.png)
![image](https://user-images.githubusercontent.com/40910744/164365362-d5fb739b-171c-41fd-8fed-480ab7ae85f5.png)
[tagui_report.zip](https://github.com/kelaberetiv/TagUI/files/8526951/tagui_report.zip)
