### ISSUE TITLE
How to transform the following script to flowchart?

### ISSUE THREAD

**Issue by githubcyc** [kelaberetiv/TagUI#644]
```
a = 1
if a equals to 1
{
	// do some step(s)
	snap page
}
else if a equals to 2
{
	// do some other step(s)
	snap page
}
else
{
	// do some other steps(s)
	snap page
}

// natural language version of a for loop
for n from 1 to 3
{
snap page
}
```

![condition](https://user-images.githubusercontent.com/19488835/70860231-341c2980-1f5a-11ea-9abb-a05a6dff1fcf.jpg)

**Comment by kensoh** [comment]
Hi @githubcyc TagUI doesn't have this feature now, but a flowchart view is something that is being considered on its roadmap. Are you aware of any NodeJS or Python based solution that can convert a script with conditions and loops into a flowchart? Thanks in advance for sharing your thoughts!

Copying @siowyisheng who will be taking over this project and implementing future releases.

**Comment by kensoh** [comment]
I know that Node-RED seems like an often-used open-source solution for creating apps that requires flowchart editing - https://nodered.org / https://github.com/node-red but not sure how an automated conversion can be done. I think it probably involve identifying a flowchart viewer and protocol, learning how the data is represented and perform a conversion.

**Comment by siowyisheng** [comment]
This will be a possible feature in the IDE.
