### ISSUE TITLE
Error executing ./tagui samples/1_yahoo chrome - fixed in cutting edge version

### ISSUE THREAD

**Issue by andrewwoo0902** [kelaberetiv/TagUI#647]
Warning: count(): Parameter must be an array or an object that implements Countable in /Users/awsw/Desktop/tagui/src/tagui_parse.php on line 31

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/awsw/Desktop/tagui/src/tagui_parse.php on line 32

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/awsw/Desktop/tagui/src/tagui_parse.php on line 34
ERROR - automation aborted due to above

**Comment by siowyisheng** [comment]
https://github.com/kelaberetiv/TagUI/issues/597#issuecomment-546177231

This is due to the OS using php>=7.2. One solution is to use php<=7.1.

**Comment by kensoh** [comment]
Adding on, alternatively, there is a fix implemented in TagUI cutting edge release. To use it, follow the steps in setup section for overwriting existing packaged installation with the cutting edge release codebase - https://github.com/kelaberetiv/TagUI#set-up

The packaged release for this fix is planned for release later this month.

**Comment by siowyisheng** [comment]
Closing now but do feel free to reply if there is any problem with the fix.

**Comment by andrewwoo0902** [comment]
Hi,

My next issue : 
awsw@Andrews-MacBook-Pro src % pwd
/Users/awsw/desktop/Tagui-master/src

awsw@Andrews-MacBook-Pro src % ./tagui samples/1_yahoo chrome
**./tagui: line 327: /usr/local/bin/casperjs: No such file or directory**

awsw@Andrews-MacBook-Pro src % php -v
PHP 7.3.9 (cli) (built: Nov  9 2019 08:08:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
awsw@Andrews-MacBook-Pro src % 


<img width="1007" alt="Screenshot 2019-12-19 at 4 10 45 PM" src="https://user-images.githubusercontent.com/44613326/71156132-4e1b7c00-227a-11ea-88ba-8ee635650768.png">

Google Chrome is up to date
Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by kensoh** [comment]
Hi @andrewwoo0902 can you raise a new issue with this info so that it's easy to add on troubleshooting info and also for other users to benefit from your issue? Thanks!

It could be because you are downloading master.zip directly. Check the Set Up section to make sure that you are downloading the packaged release for your OS.
