### ISSUE TITLE
Run step question - run step is blocking and wait for command to complete

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#649]
I hope this is the correct place to ask about TagUI matters... If not, let me know.

When the "run" step is used to start an external application, does it interrupt or affect the original flow? Does it wait for some result from the application invoked?

I'm finding that the "run" step appears to result in my flow exiting after the external application is started.

**Comment by kensoh** [comment]
Hi @mbsryu yes this is the place to ask about TagUI stuffs, we don't have a Slack group or mailing list. I see, the behaviour for run step is to pause TagUI execution, let the external app complete running, and control gets returned back to TagUI to continue running the next steps.

Can you paste a minimal script that you are running which can replicate this issue? Also, which OS are you having this problem. So that I can give an working example of the run step for the OS.

**Comment by mbsryu** [comment]
I'm trying to use the "run" step to invoke a mail application, **_Swith_**. When invoked using a specific config, it's supposed to send out an email via SMTP. There's no result being output by the mail app. I just wanted the flow to invoke the mail app and continue without pausing...

//Count how many jobs
echo "Countng new jobs"
count_number = count('jobPart active')
echo count_number " new jobs"

if count_number more than 0
{
echo "Accepting " count_number  " jobs."
click jobSelectionToggle
wait .2
click changeJobStatus
wait .2
click submit
wait .2
run SwithMail.exe /s /x "C:\tagui\Tmail-master\SwithMailSettings.xml"
}
wait .2

**Comment by mbsryu** [comment]
Apologies, i\ forgot to mention I'm using Windows 7 and Linux (Ubuntu 18.04).

**Comment by kensoh** [comment]
Ic.. If you are using Windows, make sure you are running TagUI from your command prompt and have installed the TagUI packaged release for Windows. Following eg should print before, the php version into, then after.

```
echo 'before'
run php -v
echo run_result
echo 'after'

The default behaviour is blocking to wait for command to complete before control returns back. To debug, you can try replacing the run step in your code with php -v to see whether execution runs normally. If it does, try run that `SwithMail.exe /s /x "C:\tagui\Tmail-master\SwithMailSettings.xml"` from command line. And maybe also try 'run SwithMail.exe /s /x "C:/tagui/Tmail-master/SwithMailSettings.xml"'

**Comment by kensoh** [comment]
Ic.. If you are using Windows, make sure you are running TagUI from your command prompt and have installed the TagUI packaged release for Windows. Following eg should print before, the php version into, then after.

```
echo 'before'
run php -v
echo run_result
echo 'after'
```

The default behaviour is blocking to wait for command to complete before control returns back. To debug, you can try replacing the run step in your code with php -v to see whether execution runs normally. If it does, try run that `SwithMail.exe /s /x "C:\tagui\Tmail-master\SwithMailSettings.xml"` from command line.

And maybe also try `run SwithMail.exe /s /x "C:/tagui/Tmail-master/SwithMailSettings.xml"`. TagUI architecture is JavaScript, I think backslash is an escape character, try using double backslash `\\` or forward slash `/` to see if that works. Copying @siowyisheng fyi.

**Comment by mbsryu** [comment]
Thank you for your assistance in this. Your example helped me debug the issue.
It should be noted that the forward slashes for the directory paths in Windows actually did work. I will probably need to edit them when deploying on Linux.

**Comment by kensoh** [comment]
I see.. That's great, thanks for your feedback! Closing issue for now pending further inputs.
