### ISSUE TITLE
Change infinity variable - Replace with number or hack `tagui_header.php`

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#650]
It's mentioned in the documentation that infinity loops are limited to 1024 repetitions. Can this parameter be changed somewhere? If so where?

**Comment by siowyisheng** [comment]
Hi @mbsryu, without changing the source code, the way here is just to replace infinity with an actual 
number like
```
for row from 1 to 2048
{
  // some code
}
```
.

**Comment by mbsryu** [comment]
O, I see. That's simple! Thanks!

**Comment by kensoh** [comment]
Welcome! Try not to set to too large number. It actually tries to build a stack data structure in CasperJS (the underlying engine) before the automation starts. So it can have overheads.
