### ISSUE TITLE
Reading from a list on a webpage - use count(), for loop and XPath

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#659]
I want to use the "read" step to get the text from an element on a web page but...

The element is on multiple rows. The number of rows can vary. I would like the flow to go down the list picking up the texts for the element as it appears on the rows until there are no more rows with the element.

The collected text will be written to a file and then picked up by a mailer.

I know I can probably use the"write" step to add new lines of text to file after each iteration but how would one get the "read" step to iterate down the list/

**Comment by mbsryu** [comment]
I suppose counting the number of times the element occurs and using "for" would be the standard method if the number of items in the list wasn't so ephemeral.

**Comment by kensoh** [comment]
That's correct, you can use something like the following -

```
number_of_rows = count('identifer')
for row from 1 to number_of_rows
{
...
...
...
}
```

Normally there is an identifier in XPath which can match the first element. Then you use this syntax to mean for the subsequent elements - ('x_path_identifier')[n]

See example here - https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail

Copying @siowyisheng fyi.

**Comment by mbsryu** [comment]
As always, thank you for your prompt and apt response. There is indeed an x-path to the element... I will try this out this weekend!

**Comment by kensoh** [comment]
Closing for now but feel free to open to add on!

**Comment by pankajbnsl** [comment]
Hi i am trying to get the text of every li tag one by one

Here are the codes :
rows = count('//*[@id="simple-menu"]/div[3]/ul/li')

for (n=1; n<rows; n+=1)
{
read (/html/body/div[7]/div[3]/ul/li)[n] to value
if value equals to "Civics"
// Perform actions if the condition is true
click /html/body/div[7]/div[3]/ul/li[9]
break;
}

but I get and error and error is "ERROR- cannot find (/html/body/div[7]/div[3]/ul/li)[n]

**Comment by kensoh** [comment]
The code looks wrong, need backticks to refer to variables. Maybe something like this. Tagging @pankajbnsl, and @ruthtoh from AI Singapore who is maintaining TagUI project.

```
read (/html/body/div[7]/div[3]/ul/li)[`n`] to value
```
