### ISSUE TITLE
How to upload files on a share point - try CSS selectors from this guide

### ISSUE THREAD

**Issue by saketlopes** [kelaberetiv/TagUI#676]
Hello 

I want to automate files upload in share point. 
from previous issues I found same kind of topic on file upload.

https://github.com/kelaberetiv/TagUI/issues/376

I tried example given in that issue , which is working. 

**http://demo.imacros.net/Automate/FileUploadDemo
upload #uploaded_file as abc.txt
type S1 as filename has been set above
wait**

But in my current case I do not have element with fix name it's has Xpath name.
shows error as below
**upload //*[@name="Files"] as abc.txt
ERROR - upload step is only implemented for CSS selector and not XPath selector
ERROR - for consistency with PhantomJS as it only supports upload with CSS selector**

Can i use phantam JS or Java script when upload dialog appear?

Regards 
Saket Lopes

**Comment by kensoh** [comment]
For element with name attribute 'Files', in CSS you can try -
```
upload [name="Files"] as abc.txt
```

CSS reference - https://www.w3schools.com/cssref/css_selectors.asp

Alternatively, only by using visual automation to click and upload using dialog box, can you have control over the dialog box. If the click is done using web element identifier, it will block TagUI from running until user select the file.

**Comment by kensoh** [comment]
Closing for now until further inputs
