### ISSUE TITLE
What is TagUI - general intro for non-technical audience from @mbsryu

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#681]
I've been attempting to write an intro to a doc on TagUI for our internal documentation. I don't want to sound too critical but the description available didn't do it justice... (apologies) I was wondering whether you could correct/comment... I freely plagiarised your bullet points and would welcome likewise in kind.

It is intended as a general intro for technical as well as non-technical audience. As TagUI is intended for all. as opposed to the _technorati_, I felt this type of intro (with little/no jargon) may be useful.

**What is TagUI?**

**_TagUI is a tool to automate repetitive tasks on the computer. It is a tool commonly classified under the category of **Robotic Process Automation (RPA)**. It is especially suited to business process tasks that are difficult or costly to automate using built-in tools or through traditional back-end integration methods._**

Although **TagUI** is a command-line tool, it is primarily intended to automate web and desktop applications with graphical user interface (GUI). It is particularly suited to tasks requiring interaction with websites and web applications.

TagUI is equally suited to tasks on desktop applications. When used with desktop applications it is capable of using GUI elements on the screen to control the actions. Both operating system and application features may be controlled in this manner.

TagUI can be used on **Windows, Apple Macintosh** and **Linux** platforms. The same TagUI scripts (called flows) can be used on all three platforms with little or no modification.

TagUI flows are comprised of simple concise steps that are **easy to write and maintain**. The Flows may be written in 20+ human languages. Looped steps, conditional statements, use of external data sources (CSV) and data export functions (CSV/PDF) are natively supported.

When the Flows are run, they’re automatically converted into JavaScript in the background. For more complex actions, JavaScript, Python and R elements, as well as external applications may be invoked from the Flows.

- automate web and desktop applications
- automate Chrome in visible / invisible mode
- runs on Windows, Macintosh and Linux
- write in 20+ human languages & JavaScript
- Chrome extension for recording web actions
- Python & R integrations for machine learning

**Comment by siowyisheng** [comment]
Wow! Thanks for the nice effort! We're in the process of overhauling the docs in v6 and this will come in handy 😄

**Comment by kensoh** [comment]
Great stuffs thanks for sharing @mbsryu!

What you wrote is correct, I don't see any part to change.

For the part on running scripts on different OS, your understanding is correct too. If it is purely web-based automation using web identifiers, scripts should work as is. But if scripts uses visual automation or OS-specific code (running OS-level commands with run step), those would be the parts to modify to work on another OS.

**Comment by kensoh** [comment]
Closing issue for now, Yi Sheng is almost done with the v1 of the new documentation.

CC @siowyisheng
