### ISSUE TITLE
Start up times for infinite loops - limitation due to CasperJS steps queue

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#684]
I've noticed that the start up times for a flow appears to be influenced by the number of loop/repetitions. Is my observation correct?

If I need a flow that runs on an "infinite" loop would the start up times increase ad infinitum? Is there a way to address this?

**Comment by kensoh** [comment]
Yes that's right. TagUI is built on CasperJS, so each step gets converted to a CasperJS step which will be added to the execution queue. When you do for loop with 1024 iterations, it takes some time to generate that 1024 queue before execution starts. You can reduce the number to something smaller if that works for you.

CC @siowyisheng for his thoughts. In a potential Node.js version such problem will be gone.

**Comment by kensoh** [comment]
Closing issue for now but will look out for new inputs, and thoughts from Yi Sheng
