### ISSUE TITLE
Towards Intelligent Robotic Process Automation for BPMers

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#685]
A mention in this paper. 
An interesting comparison table that shows some unique strengths for **TagUI**. 

[**Towards Intelligent Robotic Process Automation for BPMers**](https://arxiv.org/pdf/2001.00804.pdf)
Simone Agostinelli, Andrea Marrella, Massimo Mecella, Sapienza Universita di Roma

**Comment by kensoh** [comment]
Thanks for sharing @mbsryu !

Fyi @siowyisheng , interesting this project is included as part of research paper on RPA.

**Comment by kensoh** [comment]
Yi Sheng, this is an interesting paper which you can get some new RPA domain knowledge quickly.

**Comment by kensoh** [comment]
Also shared with team at AI Singapore, closing issue for now.
