### ISSUE TITLE
Space in Username - consider storing files in C:\TagUI instead

### ISSUE THREAD

**Issue by francis-han** [kelaberetiv/TagUI#686]
Hi, I'm attending CK's class. I have a space in my username and running into problems with TagUI.
May i know how I can resolve this?

**Comment by kensoh** [comment]
Hi Francis, try to install TagUI and write your scripts at some other folder locations. For eg, C:\TagUI for the program and maybe C:\TagUI\Flows for your scripts. After that you can create a shortcut to the C:\TagUI\Flows folders for easy access.

There is a limitation in the CasperJS / PhantomJS components of TagUI and thus folders with spaces is not able to work correctly on Windows. In future TagUI release, @siowyisheng is exploring the feasibility of migrating the execution engine to Node.js and this issue can be resolved.

**Comment by francis-han** [comment]
Thanks Ken. I have done the re-installation on a brand new account to get TagUI to work meantime. All the best with the migration!

**Comment by kensoh** [comment]
Thank you Francis :smile: hope you enjoy using the tool as part of your course project!
