### ISSUE TITLE
read file has a Chinese field reporting an error - pending replication steps

### ISSUE THREAD

**Issue by XLL1141348** [kelaberetiv/TagUI#687]
Reading a field in csv file is Chinese and the output is garbled. How can I solve this problem

**Comment by kensoh** [comment]
Can you provide the minimum script and csv file to reproduce this problem?

As Windows Unicode support isn't as straightforward as macOS/Linux, showing output in command prompt in other languages in Windows may require changing system locale, using chcp command, and selecting a font to display native language correctly. [More info here](http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/). So it could be text is read correctly, but shown as garbage in command prompt. Copying @siowyisheng as he has a Windows laptop to try reproducing your issue from your provided script and csv file.

**Comment by XLL1141348** [comment]
After I open a web page, I want to input the parameters read from CSV in the image position of the web page, but if the parameters read are Chinese characters, it will fail. If the parameter is not a Chinese character, it is entered successfully.
[example.zip](https://github.com/kelaberetiv/TagUI/files/4084083/example.zip)

**Comment by siowyisheng** [comment]
I have tested and checked this.

The issue should be with the way the CSV file was saved. Excel messes up text encoding if you save chinese characters as CSV. You can use Notepad or Visual Studio Code to edit the csv and it works fine.

I've attached my csv file here.
[1.zip](https://github.com/kelaberetiv/TagUI/files/4084403/1.zip)
