### ISSUE TITLE
Upcoming TagUI v6 - breaking changes for improved user experience

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#688]
**First of all, [TagUI v5.11 (Pre-v6 Release)](https://github.com/kelaberetiv/TagUI/tree/pre_v6) will be a release that continues to be maintained.**

Upcoming is v6 which introduces breaking changes to improve user experience, which had been kept from implementation for backward compatibility since beta release in Feb 2017.

The feature suggestions for v6 will come from @siowyisheng who has a business background, thus able to spot gaps which make it hard for a business or general user to use TagUI.

Listing below the changes that will impact the way users setup and run TagUI workflows.

**Items implemented in develop branch -**
- [x] set default usage Chrome visible mode instead of invisible PhantomJS mode
- [x] standardise .tag as file extension for TagUI scripts for future IDE association
- [x] do not dump .js, .log, .raw by default, as logs are not required by most users
- [x] dump step include carriage return + line feed for consistency with write step
- [x] change variable and string syntax in echo, dump, write, check steps to be consistent with rest of TagUI steps, where string is the default context while variables are denoted by backticks ``
- [x] deprecate [CLI assistant feature](https://github.com/kelaberetiv/TagUI#cli-assistant) as it is unlikely to be commonly used (excluded from v6 docs)
- [x] consider deprecating [R integration](https://github.com/kelaberetiv/TagUI#r-integration) as ML type of integration is most likely done in Python
- [x] support Python style indentation code blocks besides {} as it is more readable, but this may impact user existing scripts which uses indentation purely for formatting purpose.

**Items to not go ahead after consideration -**
> consider deprecating [native human languages](https://github.com/kelaberetiv/TagUI#native-languages) as most users write scripts in English

> consider changing smart locator priority, now it is running through following hierarchy to search for exact match and contains, instead of exact match in hierarchy then contains in hierarchy (`xpath, css, id, name, class, title, aria-label, text(), href`)

**Items being worked on or still in consideration -**

**Comment by vrudhay** [comment]
When is this coming?

**Comment by kensoh** [comment]
ETA for TagUI v6 is end of Feb or latest end Mar -

Many of the features and changes above are in already in develop branch here -
https://github.com/kelaberetiv/TagUI/tree/develop

**Comment by githubcyc** [comment]
Does TagUI script support multi-line comment ? just like:
```
/*
comment line 1
comment line 2
*/
```
It seems that does not work.

**Comment by kensoh** [comment]
Haha nope. But if you really need that and don't want to have // on every line, try this if you are ok with the additional js begin and js finish keywords.

```
js begin
/*
comment line 1
comment line 2
*/
js finish
```

The main limitation is TagUI tries to convert 21 human languages to JavaScript. While it recognises most JavaScript statements, above due to the multi-line nature, is tricky to implement correctly without hurting other primary use cases, so I didn't implement that.

**Comment by kensoh** [comment]
Hi @siowyisheng for CLI assistant can considered deprecation done since it is already excluded from v6 docs. For R integration, I'm thinking the cost of having that feature is not 2X the effort of having just Python integration. Because the code and docs is similar.

Would you be comfortable to include in v6 to retain this unique integration? I don't think any other RPA tools integrate with R because Python has become the defacto popular ML language. Retaining R will help serve that underserved R users demographics.

**Comment by kensoh** [comment]
Closing issue as v6 is released
