### ISSUE TITLE
phantomjs://code/bootstrap.js:113 in __die - check write permission

### ISSUE THREAD

**Issue by saketlopes** [kelaberetiv/TagUI#694]
Hello 

I have set automation in background mode using windows task manager.
Some time below error which stop automation.

Unable to open file: E:\Automation\invoice_prod\main_flow.txt.js

phantomjs://code/bootstrap.js:113 in __die
Unable to load script E:\Automation\invoice_prod\main_flow.txt.js; check file syntax

phantomjs://code/bootstrap.js:113 in __die

Regards
Saket Lopes

**Comment by siowyisheng** [comment]
It seems like when you run the flow in background mode, you do not have permissions to run the file. You can try to run the flow as administrator in background mode.

**Comment by kensoh** [comment]
Yes, the error message usually happens when you don't have write access to that folder to create the .js file. It could be your user for doing this background job do not have write permissions to E:\Automation\invoice_prod folder.

**Comment by kensoh** [comment]
Closing issue until further inputs, as this seems to be related to user write permissions.

**Comment by saketlopes** [comment]
Hello 

Thanks for response.

I am running automation with user has administration access.This error do not occurs regularly.
Currently I am monitoring it.. 
I will update you.

Regards
Saket Lopes

**Comment by kensoh** [comment]
Oh sure, let me know if you have more inputs!

Also, make sure there is only 1 process running at 1 time and it exits cleanly before new process starts. Just in case 1 process already lock the file for write access and another tries to write to it.

**Comment by saketlopes** [comment]
Hello Ken

Main reason for this issue is , I have several automation in parallel.

This error occurs , if previous instance of automation was terminated and child process of terminated automation were remain active in memory.

Now I have implemented a python script which will close active process belong to my automation, before running  automation. With this check , last few days I have not found this error.

Let me know if I have to take any other validation check before starting automation.

Regards
Saket Lopes

**Comment by kensoh** [comment]
I don't use any special validation check, but using the tagui\src\end_processes.cmd can check through various running processes related to TagUI and kill them. You can check the source code there to see if there is something useful to copy.

**Comment by raghuk9** [comment]
Hi Kensoh,
Huge fan of Tagui here.
I have a script which I am able to execute through the terminal on a mac, but when I try to trigger it via Automator in Mac, I get the following exception 
phantomjs://code/bootstrap.js:113 in __die
Unable to load script

**Comment by kensoh** [comment]
This error normally happens if PHP is missing or not working properly. See if you can create script to run TagUI (text file with just `tagui some_flow.tag` and chmod to 755 to be able to run. Then use Automater to run that script. CC @ruthtoh
