### ISSUE TITLE
Revert to Chrome after Visual Automation - replicate manual steps

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#695]
I have a flow that opens a XML file using the instance of visible Chrome that's invoked when starting the flow.

After some steps, the flow opens another application to continue with visual automation.

Is there a way to change the focus back to the original Chrome window?

**Comment by kensoh** [comment]
Yes of course, just do it like how you will do it manually. For example clicking on the taskbar tab (using image) for Chrome or some Chrome icon for that session. Or use keyboard step to [alt][tab] until the browser appears on the screen again.

**Comment by mbsryu** [comment]
As always, thanks for your response and suggestions.

In this particular case, I decided to to simply minimise the foreground application and used a default icon on the Chrome tab to refocus on the window, and a keyboard shortcut [ctrl]l to select the URL bar.

**Comment by kensoh** [comment]
That's a good method
