### ISSUE TITLE
Nested JS FOR loop result to Syntax Error - try human language syntax

### ISSUE THREAD

**Issue by ace-rivera** [kelaberetiv/TagUI#696]
Hello, I've been working with TagUI and I was trying to parse a paginated table in a web page. I receive error as below:

    Syntax Error: Unexpected token ‘}’
    phantomjs://code/ace_test.js:1482 in injectJs
    phantomjs://code/bootstrap.js:456

Below is the code snippet i'm using:

    for (n=1; n<=45; n++)
    {

      for(i=1; i<=50; i++) 
      {
          click //*[@id="AppFrameMain"]/div/div/div[2]/div/div[1]/div/div/div[2]/ul/li[i]
          wait 2.0
          click //*[@id="order-title-bar"]/div[1]/div[1]/a/span
      }

      wait 3.0
      click //*[@id="AppFrameMain"]/div/div/div[2]/div/div[1]/div/div/div[3]/nav/span/button
    }

**Comment by kensoh** [comment]
Hi @ace-rivera can you the following instead? It works when I try the structure doing some dummy statement.

```
    for n from 1 to 45
    {

      for i from 1 to 50
      {
          click //*[@id="AppFrameMain"]/div/div/div[2]/div/div[1]/div/div/div[2]/ul/li[i]
          wait 2.0
          click //*[@id="order-title-bar"]/div[1]/div[1]/a/span
      }

      wait 3.0
      click //*[@id="AppFrameMain"]/div/div/div[2]/div/div[1]/div/div/div[3]/nav/span/button
    }
```

**Comment by kensoh** [comment]
TagUI tries to convert the human language syntax for loop into JS style for loops, and ideally support JS style for loop directly. But I think you spotted on a case (nested JS for loops) where using JS for loop directly wasn't a use case tested to work with the parser.

This should be costly to fix without causing other use cases to fail. So I'll recommend using above human language syntax instead. In a future TagUI release, we are looking to move to Node.js engine instead of the current CasperJS / PhantomJS engine. This problem will be permanently solved then.

CC @siowyisheng fyi -

**Comment by kensoh** [comment]
@siowyisheng, adding technical reference info.

Human language syntax gets parsed correctly -
```
for n from 1 to 45
{ 
  for i from 1 to 50
  {
    echo `i`
  }
    echo `n`
}
```
```js
casper.then(function() {for (n=1; n<=45; n++)
{casper.then(function() {for_loop_signal = '[CONTINUE_SIGNAL][n]';});
(function (n) { // start of IIFE pattern
{ // start of code block

casper.then(function() {for (i=1; i<=50; i++)
{casper.then(function() {for_loop_signal = '[CONTINUE_SIGNAL][i]';});
(function (i) { // start of IIFE pattern
{ // start of code block

casper.then(function() {this.echo(''+i+'');});

} // end of code block
})(i); // end of IIFE pattern, with dummy marker for break step
casper.then(function() {for_loop_signal = '[BREAK_SIGNAL][i]';});}});

casper.then(function() {this.echo(''+n+'');});

} // end of code block
})(n); // end of IIFE pattern, with dummy marker for break step
casper.then(function() {for_loop_signal = '[BREAK_SIGNAL][n]';});}});
```

The JS nested for loops get parsed incorrectly
```
for (n=1; n<=45; n++)
{ 
  for(i=1; i<=50; i++)
  {
    echo `i`
  }
    echo `n`
}
```
```js
casper.then(function() {for (n=1; n<=45; n++)
{casper.then(function() {for_loop_signal = '[CONTINUE_SIGNAL][n]';});
(function (n) { // start of IIFE pattern
{ // start of code block

casper.then(function() { // start of JS code
for(i=1; i<=50; i++)
}); // end of JS code

{

casper.then(function() {this.echo(''+i+'');});

}

casper.then(function() {this.echo(''+n+'');});

} // end of code block
})(n); // end of IIFE pattern, with dummy marker for break step
casper.then(function() {for_loop_signal = '[BREAK_SIGNAL][n]';});}});
```

It looks like the nested JS for loop did not get interpreted correctly as a for loop but a normal JS step.

**Comment by ace-rivera** [comment]
Hello!

Thank you for the quick response. I tried human language as advised and it works correctly now.
Thank you!

**Comment by kensoh** [comment]
Closing issue for now, but @siowyisheng take note of this, you might run into stg like this when do the parser for Node.js
