### ISSUE TITLE
`click` step for web automation using XPath clicks a different element

### ISSUE THREAD

**Issue by ace-rivera** [kelaberetiv/TagUI#697]
Hello!

I've been trying to automate some clicks on my Shopify website.
I used the XPath of the li.div element as below:

This is the list item XPath:

    click //*[@id="AppFrameMain"]/div/div/div[2]/div/div[1]/div/div/div[2]/ul/li['+i+']/div/a

But there are times that the element click is different, specifically this (the arrow beside the customer name):

This is the arrow XPath being clicked sometimes

     //*[@id="gid://shopify/Order/2049817542765"]/div[2]/div/div[3]/div/div[2]/div/span/a

Below is an image of the list item

![Screen Shot 2020-01-21 at 1 45 36 PM](https://user-images.githubusercontent.com/20509365/72778765-cfd53f80-3c54-11ea-8ad9-6120d689967b.png)

**Comment by kensoh** [comment]
The XPath looks bad.

**Comment by kensoh** [comment]
The XPath looks bad and brittle. See if you can find a better XPath. Below could be a useful resource to learn on XPath - https://www.w3schools.com/xml/xpath_intro.asp

When XPath is not robust enough, automation might end up clicking on the wrong item. An example of good XPath is below, where a suitable anchor element is used, followed by the minimal relative element selectors to reach the target.

https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail

Another thing is make sure Chrome is at 100% zoom. Because TagUI simulates a click on the (x,y) coordinates found on the element. And will click wrongly if zoom is at other %.

**Comment by ace-rivera** [comment]
> Another thing is make sure Chrome is at 100% zoom. Because TagUI simulates a click on the (x,y) coordinates found on the element. And will click wrongly if zoom is at other %.

Chrome is at 100% zoom. I was also thinking about the "click" simulation you mentioned, and based on what I observed, TagUI is actually performing a mouse click on the center of the element. Is it possible that if there is an element on top of the element being clicked, it would perform click on that element instead?

**Comment by kensoh** [comment]
Yes that is possible, if a website is not designed properly and have more than 1 element overlaying in the same location, the one on top may be clicked even if you try to click the bottom one.

My recommendation for such use cases is you try the visual automation method. It can be combined with your main script that works with web element identifiers. But in this visual automation method, you can provide image snapshots of what you want to click and the engine will simulate the same action like a normal user, so it should have the same outcome as your normal browsing.

https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by ace-rivera** [comment]
> Yes that is possible, if a website is not designed properly and have more than 1 element overlaying in the same location, the one on top may be clicked even if you try to click the bottom one.
> 
> My recommendation for such use cases is you try the visual automation method. It can be combined with your main script that works with web element identifiers. But in this visual automation method, you can provide image snapshots of what you want to click and the engine will simulate the same action like a normal user, so it should have the same outcome as your normal browsing.
> 
> https://github.com/kelaberetiv/TagUI#visual-automation

I see, Thank you for the reply! I tried it in a simple script first and simulated using visual automation. Works now and I'll go find a way to make sure elements in the webpage I'm automating are clicked correctly as intended.
