### ISSUE TITLE
[TagUI] OCR for Mac - here are a few samples using visual automation

### ISSUE THREAD

**Issue by ace-rivera** [kelaberetiv/TagUI#698]
Hello Sir,

I'm exploring visual automation in my Mac and was hoping if there are any sample script you can give me? As I was looking most of the samples are intended for Windows. Thank you!

**Comment by kensoh** [comment]
Hi @ace-rivera this sample is is in this repo -
https://github.com/kelaberetiv/TagUI/issues/113#issuecomment-378194245

Here are another 3 samples using visual automation -
https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail
https://github.com/aimakerspace/TagUI-Bricks/tree/master/MS-Word-Letter
https://github.com/aimakerspace/TagUI-Bricks/tree/master/Xero-Accounting

Also CC @siowyisheng

**Comment by kensoh** [comment]
For OCR, use the read step, you can define the boundary with -
```
read (x1,y1)-(x2,y2) to variable
```

You can also provide a .png file with transparent centre to read info within a frame or textbox -
https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by kensoh** [comment]
Closing issue for now but do message here if anything!
