### ISSUE TITLE
Clipboard() step in Visual Automation - download latest version of TagUI

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#701]
This seems like rather simple thing but... I'm having a difficulty with the following steps to copy/paste a variable tin to into a field found using visual automation:

```
//Copying an element to variable tin
read TIN01 to tin
clipboard(tin);
//an application is started here
click C:\tagui\TAX_RPA_Demo\rpademoimg\fm.png
keyboard [ctrl]v
```
The error I get is: 
`ERROR - can't find variable: clipboard`

I would be grateful for any assistance.

**Comment by kensoh** [comment]
Hi @mbsryu can you type `tagui` without parameters from command prompt and see if your TagUI version is v5.11? clipboard() is a new function added in the last few months, if the installation you used was from many months back then it will not be there.

To download latest version, get it from - https://github.com/kelaberetiv/TagUI#set-up

**Comment by mbsryu** [comment]
Oops! Indeed, that was it. Am all up-to-date and good now. (bit embarrassed)
