### ISSUE TITLE
Reducing delay between SikuliX steps - yes can hack these 2 files

### ISSUE THREAD

**Issue by mbsryu** [kelaberetiv/TagUI#703]
I have a series of keyboard steps that copy paste a large number of text from variables into fields in an application (not browser) using tabs to skip to the next field. I'm finding that there appears to be a built-in delay between the execution of each step. Is there a way to reduce this delay?

[clipboard(S01C02L03);
keyboard [ctrl]v
keyboard [tab]
clipboard(S01C02L04);
keyboard [ctrl]v
keyboard [tab]
clipboard(S01C02L05);
keyboard [ctrl]v
keyboard [tab]
clipboard(S01C02L06);
keyboard [ctrl]v
keyboard [tab]](url)
...
Based on your previous response (#682), I have already reduced the scan_period in tagui\src\tagui.sikuli\tagui.py file. Is there a way to reduce the delay further?

**Comment by kensoh** [comment]
Yes, inside https://github.com/kelaberetiv/TagUI/blob/master/src/tagui_header.js replace the sleep(500) to a smaller value. That controls the delay from TagUI side while the scan period controls delay from SikuliX side.

CC @siowyisheng
