### ISSUE TITLE
Upload with button? - try using visual automation or keyboard step

### ISSUE THREAD

**Issue by Fry115** [kelaberetiv/TagUI#704]
Hi Ken,

I have the following question, I have a site where I have to upload a file, the button code is as follows:

`<button class="dropdown-item subir-doc-telefono" data-tipo-doc="csv" id="telefono-subircsv">
Subir archivo CSV
</button>`

I tried the following steps but I can't load the file:

upload #csv as file.csv
upload # telefono-uploadcsv as file.csv
upload #dropdown-item subir-doc-telefono as file.csv

Please help me.

**Comment by kensoh** [comment]
Hi @Fry115 the upload step only works with those uploading box containing text of the file to upload. Your code that uses #telefono-subircsv looks correct. If it doesn't work it means that step does not work for that upload control. You can consider using visual automation method in the readme to visually or use keyboard keystrokes to perform the upload steps.

**Comment by kensoh** [comment]
Closing for now till further inputs!
