### ISSUE TITLE
Switch between browser and excel? - visual automation & keyboard

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#708]
Can you tell how to keep the Excel / CSV open when tagui is running and switch between browser and excel windows?

Any other help on this will be great... Need to quickly get this through compared to UIPath / Blueprism.

**Comment by kensoh** [comment]
TagUI controls desktop applications like Excel using visual automation. You can write the steps just like how you will do it manually, for example clicking on Excel application on the task bar, clicking on the browser on the task bar. Or using keyboard step to [alt][tab]. More on visual automation -

https://github.com/kelaberetiv/TagUI#visual-automation

**Comment by kensoh** [comment]
Closing for now till further inputs!
