### ISSUE TITLE
Unable to automate with native language "hindi" - might be file issue

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#710]
I am facing an issue with automation in hindi language.  

It gives me an error mentioned in screenshot "flow_file" file saving the file, I tried changing Encoding to Unicode,UFT8 while saving the notepad (flow file). then it gives me the error shown in screenshot "Output" on execution.

Even though i have changed tagui_config file changes for language setting.

Please suggest.

![flow_file](https://user-images.githubusercontent.com/60636357/73711388-b2ac7080-472c-11ea-8d18-2484774de92a.PNG)
![tagui_config](https://user-images.githubusercontent.com/60636357/73711393-b50eca80-472c-11ea-828b-adb61f619106.PNG)
![Output](https://user-images.githubusercontent.com/60636357/73711397-b7712480-472c-11ea-8bdd-c5cab0eb1510.PNG)

**Comment by kensoh** [comment]
From the TagUI execution message it looks like the source text file is messed up. From the notepad message it looks like you are saving in ANSI, try to save in Unicode as the message suggest. Or you can try editing and saving the file in Notepad++ tool, which should handle this correctly.

**Comment by joginderrohilla** [comment]
Thanks Ken, It worked

**Comment by kensoh** [comment]
Have fun @joginderrohilla writing automation scripts in Hindi!

**Comment by kensoh** [comment]
Feel free to raise a PR to improve the current translation which auto-generated from Google Translate - https://github.com/kelaberetiv/TagUI/blob/master/src/languages/hindi.csv
