### ISSUE TITLE
How to get the text from variable into vision type variable.

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#711]
![image](https://user-images.githubusercontent.com/6286626/73723483-28c1cf00-474f-11ea-82f2-8e0e909a81f4.png)

http://10.106.25.147:8082/acm/#/queues-and-cases?queueId=838ecbbf-cf3f-4c17-ad7c-2b5ca87672b5
wait 15 secs
read //*[contains(text(),"Watside")] to newName
echo newName
vision type(newName)

last like vision type(newName) is not working??

**Comment by vrudhay** [comment]
I got it... using vision step rite...
vision type("Needed explanation Alert - [[")
vision_step('casenumber = "' + amlAlertNumber + '"')
vision type(casenumber)

is there any simper way?

**Comment by kensoh** [comment]
Yes above is the solution, but why use vision step when you can use normal type step or keyboard step to do the same thing from TagUI? Check the visual automation section of readme for more info.

**Comment by vrudhay** [comment]
I heard you.  But when you use 'type', you have to use type 'object_id' as 'value' rite.  Does it type wherever the cursor is?  Or, will Keyboard do?

**Comment by kensoh** [comment]
`keyboard` will do, and no need for Object ID. `keyboard` will type onto the screen at whatever application that is in focus at the moment.
