### ISSUE TITLE
Request for Hindi code base update - merged into develop branch for v6

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#712]
While going through automation methods for hindi, observed that below methods have different meaning in hindi , which does not fit for automation perspective.

**Current:**
tap- नल टोटी
type-प्रकार
to-सेवा मेरे
present()-वर्तमान()

Kindly Update these with below list::

**Should be:**
tap- दबाना
type-लिखो
to-तक
present()-मौजूद()

**Comment by kensoh** [comment]
Thanks @joginderrohilla for raising this PR! I've committed and merged in develop branch -
https://github.com/kelaberetiv/TagUI/tree/develop

This is the dev branch which is the cutting edge version now and to be released as v6.

CC @siowyisheng fyi on update of Hindi dictionary merging into develop branch.
