### ISSUE TITLE
Is clipboard working?

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#713]
![image](https://user-images.githubusercontent.com/6286626/73735466-4d28a600-4765-11ea-8577-28dcc1a3f7e5.png)
says can't find variable

**Comment by kensoh** [comment]
Make sure using latest packaged installation here - https://github.com/kelaberetiv/TagUI#set-up

Most likely you are using an old version of TagUI without clipboard() helper function

**Comment by vrudhay** [comment]
Agreed. and working now.
