### ISSUE TITLE
Why does it type one character after one character, can it type instantly

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#716]
![image](https://user-images.githubusercontent.com/6286626/73812741-e908ef00-4803-11ea-955c-433a9bdecea7.png)

can it not type as full bang so that we can save time

**Comment by kensoh** [comment]
Because TagUI is a RPA tool. When a normal user type into a text box it is character by character.

To speed up, you can use the clipboard() function to put long text there and use `keyboard [ctrl]v` to paste quickly. See example here - https://github.com/kelaberetiv/TagUI#helper-functions

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/73839461-12457180-483c-11ea-8fb8-b12001e7b63e.png)
Hi, when I use Clipboard function also, it is typing so slowly...  Should I use Ctrl V

**Comment by vrudhay** [comment]
type customer-filter-input as [ctrl]v

this is not working Sir.

**Comment by kensoh** [comment]
Below code is enough to do what you are trying to do above -
```
clipboard(xlPath);
keyboard [ctrl]v
keyboard [enter]
```

If the textbox is not yet in focus you can do a click text_box.png to highlight it first before doing the keyboard [ctrl]v

**Comment by vrudhay** [comment]
![image](https://user-images.githubusercontent.com/6286626/73906795-2932a500-48ca-11ea-9765-3c36215a54f2.png)
Actually I used click 'element_id' and it clicked also
but while using keyboard [ctrl]v - it pastes in URL.

Are there 2 cursors that it creates?

**Comment by kensoh** [comment]
Make sure you use click element_id.png using an image snapshot of the element in the browser. To be sure do it 2 times. The first click is to make sure Chrome browser is in the foreground. The second click is to make sure the text box is selected. After that do `keyboard [ctrl]v`

```
click element_snapshot.png
click element_snapshot.png
```
