### ISSUE TITLE
How can i fix this Error : use init() before using url()

### ISSUE THREAD

**Issue by juniorkidsu** [kelaberetiv/TagUI#717]
![image](https://user-images.githubusercontent.com/60415345/73816048-34c69300-481a-11ea-9224-4836ed8d8e1f.png)

But first i'm try to test with Tagui via cmd It's very well working!
![image](https://user-images.githubusercontent.com/60415345/73816114-5f185080-481a-11ea-959d-13026f60ecd3.png)

so what a problem with my python or TagUi 
In this case i Declare init() before using url()  but i got this message  **use init() before using url();**
so what a problem with this Error???

**Comment by kensoh** [comment]
For the Python project, please raise issue at the RPA for Python GitHub page. A possible error could be your user name or folder has a space. You can provide more details there, including the Python script you write to have the error - https://github.com/tebelorg/RPA-Python/issues
