### ISSUE TITLE
How to create something like function which takes parameters and does some work inside?

### ISSUE THREAD

**Issue by vrudhay** [kelaberetiv/TagUI#723]
How to create something like function which takes parameters and does some work inside?

**Comment by siowyisheng** [comment]
```
// define the function in javascript
js begin
var myFunction = function(param1, param2) {
  some work in javascript
}
js end

// call the function
js myFunction(param1, param2)
```

**Comment by vrudhay** [comment]
Hi,
Actually, I am not looking for javascript statements rather tagUi statements itself to be bundled in a function / module and reuse it with various arguments?

**Comment by siowyisheng** [comment]
The closest TagUI way is to group statements together in a flow file, and then calling that flow within another flow.

```
tagui another_flow
```
