### ISSUE TITLE
Sourcing R script

### ISSUE THREAD

**Issue by pythiantech** [kelaberetiv/TagUI#725]
Firstly, this is a very cool and helpful project!

I am very new to this and couldn't find a suitable tag on SO hence asking here. I am running an automation task where I am able to log on to a site, navigate to a page and then download some data as a csv file. I see that the data indeed gets downloaded. Thereafter I have a R script as well as a .Rmd file which reads in the data and then renders a markdown document. This works well when I run it in RStudio or from R. However nothing seems to happen when I run it from the automation script. I don't get an error either but the script never terminates. Is there some way of increasing the verbosity of the logs? This is the line I am using in the automation script:

```
r source('E:/windward_rpa/pics.sikuli/Vsl_Locations.R')

```
Have also tried this:

```
r rmarkdown::render('E:/windward_rpa/pics.sikuli/Vsl_Locations.Rmd')

```

**Comment by pythiantech** [comment]
Got it sorted. Turns out Rscript for not set in my path. After doing that, it works like a charm! Thanks.

**Comment by kensoh** [comment]
Thanks for your feedback and update! Yes Rscript command is required to be in your path for TagUI to be able to find it and launch it to run R code.
