### ISSUE TITLE
Broken Visual Automation - pending replication and user checks

### ISSUE THREAD

**Issue by alketshabani** [kelaberetiv/TagUI#733]
Hello,
I am doing a visual automation of 2 software: SAP Gui and Microsoft Outlook. The idea is that after tagui does something with SAP it closes it and then continues to open outlook. The problem is that after it closes SAP, it logs that it found outlook (which it does not) and then the automation fails in the next step. Any comments regarding this?
Thanks

**Comment by alketshabani** [comment]
//### automation done for sap and outlook together
//show desktop
rclick start.PNG
click showDesktop.PNG
//open sap
dclick sap-icon.PNG
wait 5sec
//click on white field to bypass problem in the beginning with the selection
click empty.PNG
//open connection
dclick connection.PNG
wait 5 sec
//login into the system
login_username = "SAP*"
type user.png as '+login_username+'[TAB]
vision type (Key.SHIFT +"A"+"" + Key.ENTER)
wait 3 sec

//enter the transaction
click transaction.PNG
wait 1 sec
vision type ("su01" + Key.ENTER)
wait 2 sec



py begin
filename = 'C:/Users/Diploma/Desktop/Diploma/tagui/testVariables/read.txt'
f = open(filename, "r")
print(f.read())
py finish
echo py_result
variable_username= py_result




// type field for new user
username = "DEVELOPER"
type user-field.PNG as '+variable_username+'

click change-user.PNG
wait 3 sec
//click logon-data tab
click logon-data.PNG

//click new-password box
click new-password.PNG
vision type ('P!')

//Click repeat password
Click repeatPassword.PNG
vision type ('Password001!')

wait 2 sec
click system.PNG
click close.PNG
click yesLOGOFF.PNG
click close2.PNG


///////MAIL PART

//open outlook
dclick outlook.PNG
wait 6 sec
//click outlookTaskbar.PNG
//new mail
click newMail.PNG
wait 2 sec
//maximize the window of new newMail so not to have problem with double icons
//click maximize.PNG

//send mail to
mailto = "automatefordiploma@gmail.com"
type mailTO.PNG as `mailto`[TAB]

//put manager in cc
managermail = "@gmail.com"
type mailCC.PNG  as `managermail`[TAB]
mailsubject = "TestTagui"
type mailSubject.PNG as `mailsubject`[TAB]

vision type ("Hello"+ Key.ENTER +"Your new password is: P@ssword" + Key.ENTER + "Best Regards" + "," + Key.ENTER + "Your Bot")

click sendMail.PNG

//click minimize.PNG
click outlookClose.PNG

**Comment by kensoh** [comment]
Hi @alketshabani do you mean that the automation failed at below step?

```
//open outlook
dclick outlook.PNG
```

If yes, what you can try is put a live step just before this step. In live mode you can try out different TagUI steps to test what works. Double check that outlook.PNG is an accurate image snapshot of how the Outlook app looks like on your Desktop.

```
// for live debugging and development
live

//open outlook
dclick outlook.PNG
```

Other ways can be using another method to launch outlook, for eg using keyboard step to search for outlook from start menu. Something like below, I don't have Windows PC to test.

```
keyboard [start]
keyboard outlook[enter]
```

**Comment by alketshabani** [comment]
Hello,
It was failing after that step:
dclick C:/Users/Diploma/Desktop/Diploma/tagui/finalSAP_Automation/outlook.PNG
wait 6 sec
click C:/Users/Diploma/Desktop/Diploma/tagui/finalSAP_Automation/newMail.PNG
ERROR - cannot find C:/Users/Diploma/Desktop/Diploma/tagui/finalSAP_Automation/newMail.PNG on screen

this was the error that i was seeing. After i did live mode, and retried the automation worked. what is live mode supposed to do? was it a glitch?

**Comment by kensoh** [comment]
Live mode is same as normal mode, but you can test TagUI steps interactively to try and debug.

From above error message, it looks like newMail.PNG cannot be found. Check to make sure that the new mail button is visible during the automation. If the button is not visible on the screen or some other window is blocking, then it cannot be found.

Alternatively, if you cannot take a screenshot of the button that works, you can trying using the (x,y) coordinates to click on it. eg `click (100,200)`. To get the (x,y) coordinates, in live mode type echo mouse_xy() to see the value of current mouse position, after you put mouse cursor at location of the button.

**Comment by alketshabani** [comment]
I want to show that the error is misleading. Actually it is not finding outlook.PNG. In the log it says that it found it but actually it was stuck and doing nothing. If i run the automatons separately they work. together they were stuck. i tried it now and it was working the script above? ANy recommendations?

**Comment by kensoh** [comment]
Can you create a minimum replication script (for below) to run and test it? And attach the file tagui\src\tagui.sikuli\*.logs here.

```
dclick C:/Users/Diploma/Desktop/Diploma/tagui/finalSAP_Automation/outlook.PNG
wait 6 sec
click C:/Users/Diploma/Desktop/Diploma/tagui/finalSAP_Automation/newMail.PNG
```

**Comment by kensoh** [comment]
It could also be because the click only set focus on Outlook but not click on the app. You can try clicking 2X to see if it clicks on Outlook and click the new email button. If you can do a video recording of the error happening and attach here together with the log files it will be great.

```
dclick C:/Users/Diploma/Desktop/Diploma/tagui/finalSAP_Automation/outlook.PNG
wait 6 sec
click C:/Users/Diploma/Desktop/Diploma/tagui/finalSAP_Automation/newMail.PNG
```

**Comment by alketshabani** [comment]
I cannot reproduce the error as it is not happening anymore. Today after i did the `live` magically started working. Probably you can close the issue, maybe it was something temporary.

**Comment by kensoh** [comment]
I see, this is strange, ok Alket ping here if you run into similar issue!
