### ISSUE TITLE
Assigning Empty String to Null - pending replication details and context

### ISSUE THREAD

**Issue by tangjh** [kelaberetiv/TagUI#737]
I'm trying out the multi-column line reading from CSV tutorial.
if the split results only has one item instead of 3, I don't want the program to crash but rather assign empty strings "" to the nulls. 

How can this be done?

**Comment by kensoh** [comment]
Can you paste your code or what you mean by the CSV tutorial?

You mentioned split I assume you mean reading from a CSV file and splitting each row into different columns. Normally for a CSV to be valid, the empty columns will still be separated by comma and split should return blank string for the column with no data.

**Comment by kensoh** [comment]
Closing for now until further inputs!
