### ISSUE TITLE
Is Mesos or Marathon the best/optimal for central command center?

### ISSUE THREAD

**Issue by athbharat** [kelaberetiv/TagUI#738]
Hi,

I want to add a central command center to TagUI. Can the learned folks share opinions on using Mesos or it's high level integration Marathon? Or please suggest any other such tool?
Suggested features of central admin: 
1. Get the stats of robots usage.
2. Manage robots - Deploy, Pause, Stop, Terminate, Add, Edit, Play
3. Manage users and device combinations 

Pros for Mesos - I like Mesos because it can run across all operating systems.
Cons for Mesos - It seems like a heavy tool for a small stuff.

**Comment by kensoh** [comment]
Hi @athbharat, I replied to your question at the other thread -
https://github.com/kelaberetiv/TagUI/issues/116#issuecomment-589972297

If you are referring to TagUI controlling Apache Mesos - http://mesos.apache.org then no there is no plan to add native integration with it. However, as Mesos is used through various ways, you should be able to use existing TagUI features to integrate and automate it -

For Mesos command line - use run step
For Mesos HTTP APIs - use api step
For Mesos web interface - use usual TagUI web automation steps or visual automation

See more under pro steps in - https://github.com/kelaberetiv/TagUI#steps-description
More on api step and examples in - https://github.com/kelaberetiv/TagUI#api

---

If you are referring to using Mesos to control TagUI - 

For simple integration, you can invoke TagUI using the command line with options. So everything goes through the command line. From Mesos, schedule or call TagUI to do some workflows, collect and report results.

For advance integration, such as step by step execution and feedback of results, you can use live mode to do that. But it is not easy as you will have to build integration code to do that. You can see how I implement integration with TagUI live mode in my Python project -
https://github.com/tebelorg/RPA-Python/blob/master/tagui.py

**Comment by athbharat** [comment]
Thanks Ken,

Apologies for less clarity. I am talking about Mesos controlling TagUI. You have done an awesome job! I love TagUI.
I have a 5000 staff organization as client who may benefit from automation. The project can be delivered easily by centralized robotics method. That's why I am looking to build or get a central command.

Best Regards,
AB

**Comment by kensoh** [comment]
Hi AB, you're welcome and thanks for your kind words!

I self-funded TagUI development in 2016-2017 but thanks to AI Singapore, TagUI project is able to continue as AISG continued maintaining it. My colleague at AI Singapore @siowyisheng is taking over the baton after I leave the organisation in a couple of months.

There a plan on an Orchestrator / Central Controller / Reporting Dashboard in mind but it won't be so soon. We are working on TagUI v6 now https://github.com/kelaberetiv/TagUI/tree/develop and after this, a refactoring migration to NodeJS is being considered for v7. To prepare the foundation for these higher level features later on.

Feel free to post any questions on GitHub issues when you run into questions while developing a Command Center for TagUI. As a central controller app won't be developed so soon, you may consider doing it from your side to get the functionality to your client faster.

Also, to ensure users' vested interests are protected, the current version of TagUI v5.11 (Pre-v6) https://github.com/kelaberetiv/TagUI/tree/pre_v6 will continue to be maintained as we move to v7 and v8. This allows existing user TagUI scripts or deployments to continue working as big changes are implemented, which can be backward compatibility-breaking (eg from v5.11 to v6).

Kind Regards,
Ken Soh

**Comment by kensoh** [comment]
Closing this issue for now but ping here if anything @athbharat !
