### ISSUE TITLE
Is there some sample for webscraping and converting into excel data - see eg

### ISSUE THREAD

**Issue by bhuvanesh15** [kelaberetiv/TagUI#747]

**Comment by kensoh** [comment]
Hi @bhuvanesh15 there isn't an example for that, but the closest one is this -
https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail

It goes to a website to scrap forex rates, saves the data into a CSV file, then email it.

TagUI does not have native ability to write to Excel file format. To use Excel, you can try to use the Python integration and some Excel package to do that. Or you can save in CSV file for import later by Excel application.

Also, for simple HTML tables with simple rows and columns (without merged cells), the table step can be used to extract contents of the table in 1 line of code by providing XPath of the table.

**Comment by bhuvanesh15** [comment]
Hi @kensoh , Just found useful resource to write .csv use tagUI Native scripts !
https://www.rpa-sg.org/TagUI-Tutorial-1/tagui-tutorial-1-goodreads-com-part-5.php.

**Comment by kensoh** [comment]
Oh great! He's my friend. Copy @siowyisheng fyi on CK's webpage with TagUI tutorials.
