### ISSUE TITLE
Example required for List box, Radio button, Check box, drop down using Xpath element identifier

### ISSUE THREAD

**Issue by anavaneedhan** [kelaberetiv/TagUI#748]
Hi Kensoh,

RPA in python is really a great development. I have a requirement to automate a portal that has a form. The form has multiple check boxes, radio button, list boxes and drop downs. I can able to achieve the selection using XY coordinates but unable to do the same thing for list boxes or drop downs. So I am trying to use SELECT() function with parameters like X path of list box. however the code is throwing error like "[RPA][ERROR] - cannot find "X PATH". could you please help with any sample code list box, radio button, check box, drop down. Appreciate your help. Thanks

**Comment by kensoh** [comment]
Hi @anavaneedhan thanks for your positive feedback! This is a RPA for Python question, I'm closing the issue here so that you can raise there next time - https://github.com/tebelorg/RPA-Python/issues/112
