### ISSUE TITLE
Can TagUI automate Internet Explorer - not natively but try visual automation

### ISSUE THREAD

**Issue by bhuvanesh15** [kelaberetiv/TagUI#749]

**Comment by kensoh** [comment]
Hi @bhuvanesh15 TagUI cannot automate Internet Explorer natively by specifying XPath, CSS selectors or HTML attributes. However, there is visual automation method which you can try to see if that works for your use case.

This method uses computer vision to find web elements. Use can give image snapshot of web elements or their (x,y) coordinates. Also keyboard shortcut keys can be used together to enter and retrieve information out of the webpage.

https://github.com/kelaberetiv/TagUI#visual-automation

CC @siowyisheng

**Comment by kensoh** [comment]
Closing issue for now but ping here if anything!
