### ISSUE TITLE
Tagui pauses during execution run - pending replication details and logs

### ISSUE THREAD

**Issue by ba700113** [kelaberetiv/TagUI#750]
When running the application, the application pauses and refuses to continue with the run. I have not seen the problem in the past but started coming up in the last couple of weeks. 
For example: 
if i have five scripts in my batch file to run, maybe on the first script will run and then Tagui will pause and not continue to run. I use the 64 bit installation package to install the tagui.
Note: during the run/execution, three different command prompt windows open. usually only two windows open

Can you guys help me find out what is happening?

**Comment by kensoh** [comment]
Hi @ba700113 can you attach your sample scripts that can reproduce the issue and the log files here? The log files are in your scripts folder, and in tagui\src\tagui_chrome.log and if visual automation is used, there are log files in tagui\src\tagui.sikuli folder. CC @siowyisheng

**Comment by ba700113** [comment]
The scripts run and then stops when it doesn't find a png file. It will just pause and not continue to next script in batch. Like i said earlier three separate cmd windows open when the script is running. 
See log file below from tagui/src/tagui.sikuli


[tagui log file.zip](https://github.com/kelaberetiv/TagUI/files/4319284/tagui.log.file.zip)

**Comment by kensoh** [comment]
Base on the log file you attached it is working as designed. You specify app_opened.png as the image snapshot to look for to click. But that is not found on the screen. So TagUI should throw error and exit as designed.

```
[tagui] INPUT  - [1] click C:/POSAutomation/BOH/repos/BOH_search.png
[tagui] ACTION - click C:/POSAutomation/BOH/repos/BOH_search.png
[log] CLICK on L[74,883]@S(0) (1031 msec)
[tagui] OUTPUT - [1] SUCCESS

[tagui] INPUT  - [2] type C:/POSAutomation/BOH/repos/search.png as word[enter]
[tagui] ACTION - type C:/POSAutomation/BOH/repos/search.png as word[enter]
[log] CLICK on L[220,837]@S(0) (546 msec)
[log]  TYPE "word#ENTER."
[tagui] OUTPUT - [2] SUCCESS

[tagui] INPUT  - [3] click C:/POSAutomation/BOH/repos/app_opened.png
[tagui] ACTION - click C:/POSAutomation/BOH/repos/app_opened.png
[tagui] OUTPUT - [3] ERROR
```

TagUI has not been tested to run consecutively a few flows within a batch file. It sounds like you mean when run in a batch file and an image locator not found TagUI will hang. I don't have a Windows laptop to test this. Let me ask my colleague to have a look.

Hi @siowyisheng, can you help validate if running a few TagUI workflows within a batch file, if an image locator is not found, does it hang execution instead of continuing to the next flow?

**Comment by ba700113** [comment]
I created a batch file to run a series of txt file or scripts. In my
situation, it if a step fails tagui doesn't go ahead to through the error,
i cant find image. but rather it stops and will not continue. if you look
at the image below, the programs says :The process cannot be access the the
file because it is being used by another process.



[image: image.png]

**Comment by kensoh** [comment]
It could be the processes on the computer has not ended yet and lock up the files. You can try insert the command tagui\src\end_processes.cmd each time before you run the tagui command. It will kill all processes that are dead or alive.

**Comment by ba700113** [comment]
there is no file called 'end_processes.cmd' in the tagui\src\end_processes.cmd directory you gave me.  
i tried to run it in my batch file and it saids cannot find it.

can you take a look again?

**Comment by kensoh** [comment]
Can you share where you download TagUI? TagUI should come with this file in the zip.

CC @siowyisheng

**Comment by ba700113** [comment]
Have been trying to upload the tagui version folder  that i use but its too big so unable to upload it even after zipping it.

Can you rather attach the correct version of tagui for 64 bit windows machine. 
Or give the link that direct me to the right version for 64 bit windows machine
Would really appreciate that
Thank you sir.

**Comment by kensoh** [comment]
Sure the link to download zip is here - https://tagui.readthedocs.io/en/latest/setup.html

**Comment by ba700113** [comment]
Did the installation but when i run my .txt scripts, i get the error message below:
I dont know why am getting that error message. 

![Tagui ERROR](https://user-images.githubusercontent.com/56697456/77476259-a1a8e300-6df0-11ea-921b-8cc6ce4d2d61.PNG)

**Comment by kensoh** [comment]
For TagUI v6, the file extension has to be .tag and in above image your extension is .txt so it does not work. Try renaming your file to .txt and try again. There is a bug in showing the unnecessary error messages above, I'll ask my colleague to review a bug fix below.

Hi @siowyisheng bug found with .tag on Windows, spotted by user above. The log files are being converted from Linux to Windows format without checking that they exist. This was missed when testing on Windows for only positive test but not negative test. Raised PR https://github.com/kelaberetiv/TagUI/pull/768 for your review and merge.

**Comment by kensoh** [comment]
Hi @ba700113 closing issue for now but do ping here if you have new findings to share!

**Comment by divyashreeg17** [comment]
Hi Kenosh, 
I am facing this pause issue. I tried tagui\src\end_processes.cmd but even after that I am facing this issue. Please help me on this.

**Comment by kensoh** [comment]
Hi @divyashreeg17 where are you based? Will you be able to join our weekly Zoom call to troubleshoot?

It is on Thursday 4-5pm SGT (UTC+8), or 130-230pm IST. Link here - https://github.com/kelaberetiv/TagUI/issues/914
