### ISSUE TITLE
Unusual Error message - install vcredist_x86.exe dependency from link in docs

### ISSUE THREAD

**Issue by ba700113** [kelaberetiv/TagUI#751]
I install tagui on a 64 bit machine and when i try to run the tool, it gives me error message below
Error message: 
**The program cant start because MSVCR110.dll is missing from your computer. Try reinstalling the program to fix the problem**

Can you guys help me finfd out why am having this issue

![Tagui_error](https://user-images.githubusercontent.com/56697456/76247089-551caf80-6215-11ea-9916-32fc3663d8c9.PNG)

**Comment by Ralkage** [comment]
Hi, this error appears when you attempt to run an application (such as this one) which requires the Microsoft Visual C++ Redistributable 2012 package 📦. You’re basically missing a DDL filed that is required for this application to execute correctly. You can grab both the 32bit (x86) and 64 bit versions here:

https://www.microsoft.com/en-us/download/details.aspx?id=30679#

Hope this helps :)

**Comment by kensoh** [comment]
What @Ralkage Christian said is correct. This error message is mentioned in the [old docs](https://github.com/kelaberetiv/TagUI/tree/pre_v6#set-up) and [new docs](https://tagui.readthedocs.io/en/latest/setup_troubleshooting.html#troubleshooting-macos-linux). Which should be removed after installing the file. Choose the vcredist_x86.exe version.

**Comment by kensoh** [comment]
CC @siowyisheng

**Comment by ba700113** [comment]
That fixed the issue. Thank you
