### ISSUE TITLE
Sikuli sometimes not activated, causing some visual automation to fail

### ISSUE THREAD

**Issue by siowyisheng** [kelaberetiv/TagUI#756]
This fails if it is the whole script, although it is basic usage of visual automation.
```
if present('test.png')
    echo 5
```

If I just activate sikuli separately using a click on coordinates, then it works.
```
click (1,1)
if present('test.png')
    echo 5
```

To fix.

**Comment by kensoh** [comment]
Oh.. Yes, there isn't a mechanism to detect this. The assumption is if a user uses exist() and present() for images, there is most likely other steps in the workflow that does visual automation. Thus those steps would already trigger sikuli. Very unlikely that a workflow uses exist and present image without any other sikuli VA steps. Though not impossible.

**Comment by adegard** [comment]
Hi guys, 
Click text using ocr seems very attractive new feature!

Is there still needed Sikuli, for that? 
There ins't instructions on the new V6 webpage
Could you explain Sikuli installation?

thanks

**Comment by siowyisheng** [comment]
Sikuli is packaged together with tagui in the zip file. No need for a
separate installation.

**Comment by adegard** [comment]
OK Yi, thank you, however can you better explain the usage of 'using OCR '
feature. I was trying in live, but it is not responding if I indicate some
text to be clicked in webpage...

Il dom 22 mar 2020, 12:38 Yi Sheng <notifications@github.com> ha scritto:

> Sikuli is packaged together with tagui in the zip file. No need for a
> separate installation.
>

**Comment by siowyisheng** [comment]
Sure. I'll also update the docs. Thanks for pointing out the shortcoming.

```
click some text using ocr
```

This looks for 'some text' on the user's screen using ocr and moves the
mouse to the middle of the found matched text (from top left of the screen
to the bottom right) and clicks it. Sometimes it fails because ocr is not
100% reliable.

It's most useful with click, rclick and dclick steps.

When using it in live mode, make sure your command prompt is below your
target text, or it will likely click the matched text within your command
prompt itself.

**Comment by adegard** [comment]
ok, perfect, I found the way, now. thank.
It tooks some time (around 2 min) and pointed to the words when they were at beginning. So, my understand is that it takes a picture and take time to analyse it. Then I need to don't move meanwhile he is searching.

**Comment by kensoh** [comment]
Hi @siowyisheng, I created https://github.com/kelaberetiv/TagUI/pull/774 which fixes this issue using regex string matches.
