### ISSUE TITLE
Unable to load script  while running tagui - wrong file name, check version

### ISSUE THREAD

**Issue by bhuvanesh15** [kelaberetiv/TagUI#757]
![isuue tag](https://user-images.githubusercontent.com/50789213/76837731-0eeccf00-6859-11ea-9992-e29fe3f419d6.PNG)

Tried intalling Visual C++ Redistributable  , still not working,

**Comment by kensoh** [comment]
The 1_yahoo.tag is the filename extension for TagUI v6. In above screenshot, it shows that the file is not found. I think in v6, the folder is in tagui\flows\samples\1_yahoo.tag. Check here to make sure that you have downloaded is and using v6.

For v5.11, it is accessible here - https://github.com/kelaberetiv/TagUI/tree/pre_v6

**Comment by kensoh** [comment]
Closing issue for time being until further inputs!

**Comment by bhuvanesh15** [comment]
But ken , I tried in V5 only ,it shows MSVCR110.dll is missing  also installed  Visual C++ Redistributable
still facing issue ie unable to load script

**Comment by kensoh** [comment]
Make sure you downloaded and installed the 32-bit MSVCR110.dll file. You can also get it from here - https://tagui.readthedocs.io/en/latest/setup_troubleshooting.html#troubleshooting-macos-linux
