### ISSUE TITLE
Issue with sub flow for multiple inputs from a .csv file - usage issue

### ISSUE THREAD

**Issue by samreen-webonise** [kelaberetiv/TagUI#760]
Hi Kensoh,

Hope you are doing great!!!

I have just started exploring about tagui and was trying to implement one task.
The task is :
There is a .csv file containing few values and we have to convert it into another currency.
Steps : 
1. Open currency converter website

2. For each row in the .csv file, 
            Write the values to the website
            Click on Convert button

3. End

Here, as you can see, 
I want to perform the step 1 only once, i.e. Opening browser and the site. And want the step 2 to be executed for each row in the .csv file.
And end.

To achieve this, I have created two .tag file and calling the second file from the first one.
Files are:
----------------------------------------------------------------------------------------------------
1. MainFlow.tag
----------------------------------------------------------------------------------------------------
https://www.xe.com/currencyconverter/
wait 5

tagui SubFlow.tag Data.csv

----------------------------------------------------------------------------------------------------
2. SubFlow.tag
----------------------------------------------------------------------------------------------------
type Amount as [clear]`USD`

click OldButton-jvvAjr SubmitButton-fCPQGw ilGkLV submitButton
wait 5
---------------------------------------------------------------------------------------------------
Data.csv
---------------------------------------------------------------------------------------------------
USD     <-----Column Name
_______|
1
_______|
10
_______|
20      
_______|

-----------------------------------------------------------------------------------------------------
The issue here is, 
The **tagui SubFlow.tag Data.csv** command in the MainFlow.tag is not working.

It shows the error as : File not found for the step tagui SubFlow.tag Data.csv.

Is it the case that we can call another .tag file from one using **tagui FileName.tag** command but if we want to use it in combination with .csv, it fails ?

--- If I use this command **tagui SubFlow.tag Data.csv** directly on cmd, it runs. Issue is only when it is called from another .tag File, as explained above

Note: All the three Files are in the src folder.

Please help.

Thanks in advance :)

**Comment by kensoh** [comment]
Hi @samreen-webonise the tagui step to call sub flows how it works is to expand the text contents of the sub flow into parent script and run. Thus the step cannot call any parameters. All variables in the main script can be access directly in the sub script.

To do something like what you need, you can try running main script with `tagui MainFlow.tag Data.csv -speed`. This way the parameters should still be accessible from the subflow. Also, running with -speed option will not restart Chrome and make it faster between rows.

However, the webpage will still be loaded each time. If you want to only load one time and loop many times for the csv rows, will have to write your own for loop and code to read in the csv and process the values in it.

**Comment by kensoh** [comment]
PS - can also do something like if to check the current URL, and load the page only if the page is not yet loaded.

**Comment by kensoh** [comment]
Closing the issue for now, do ping here if any questions!

**Comment by samreen-webonise** [comment]
Thanks Ken :)
