### ISSUE TITLE
'tagui' is not recognized as an command - add to path see eg here

### ISSUE THREAD

**Issue by gesnype** [kelaberetiv/TagUI#761]
Hi Sir,

I'm having issue with the installation of tagui. Apparently when i run "tagui c:\tagui\flows\samples\1_google.tag" in cmd, this is the error i get "'tagui' is not recognized as an internal or external command, operable program or batch file." I followed the installation instruction. What mistake did i make? Can you please help?

Regards
Lester Yam

**Comment by kensoh** [comment]
Hi Lester, the `tagui` command by default resides in the tagui\src folder and not accessible from other locations if you just type `tagui`. If you are referring to the instructions here,

https://tagui.readthedocs.io/en/latest/setup.html

There is a step `setx path "%path%;c:\tagui\src"` to first make `tagui` command accessible.

**Comment by gesnype** [comment]
Hi kensoh, I have followed that step and it print this output:

"WARNING: The data being saved is truncated to 1024 characters.
SUCCESS: Specified value was saved."

What is the meaning?

**Comment by kensoh** [comment]
Not sure of this issue, maybe some limitation with the setx command (cc @siowyisheng).

Alternatively, you can try adding manually using the step-by-step guide below -

https://stackoverflow.com/questions/44272416/how-to-add-a-folder-to-path-environment-variable-in-windows-10-with-screensho

**Comment by kensoh** [comment]
Lester, closing issue for now but do post here if anything.

**Comment by gesnype** [comment]
Manage to resolve the issue. I have to run the cmd as administrator instead of user

**Comment by pratiksharma1619** [comment]
Can you shed some light on how to tackle the issue on macOS
I am on Mac 10.12 & extracted the folder on Desktop and followed the installation instruction
1) sudo ln -sf /tagui/src/tagui /usr/local/bin/tagui
    ----- my path after CD desktop
2) sudo tagui /tagui/flows/samples/1_google.tag
 but get **tagui: command not found**

**Comment by gesnype** [comment]
I'm using windows. Sorry can't really help you on that

**Comment by kensoh** [comment]
Hi Pratik, this part looks wrong -

/tagui/src/tagui

Check again to make sure that this folder is correct. Normally on macOS nothing gets installed in the root folder. Usually for installing on desktop it is /Users/username/Desktop/tagui/src/tagui

**Comment by edgarascom** [comment]
I am also having problems running tagui.
`zsh: permission denied: tagui`

and when I run with `sudo`:
`sudo: tagui: command not found`

**Comment by tekforge** [comment]
I had a similar issue on Windows 10. Resolved by adding a trailing backslash to the path: 

`setx path "%path%;c:\tagui\src\"`

**Comment by capdiamant** [comment]
I had the same issue, even when running as admin in Win10. Resolved it by changing the "c" to capital "C":

`setx path "%path%;C:\tagui\src\"`

**Comment by kensoh** [comment]
Changing [setup instructions](https://tagui.readthedocs.io/en/latest/setup.html) to add path manually instead of using setx,
as that can be problematic to do on some systems, eg https://github.com/kelaberetiv/TagUI/issues/761 and https://github.com/kelaberetiv/TagUI/issues/826

**Comment by UralanVDH** [comment]
Should anyone still have problems after trying all the above: I had to move tagui to the System32 folder

**Comment by TetraGenius** [comment]
On Fedora 33: (may work on other Linux)
Add path with:
(base) [theuns@localhost ~]$ export PATH=$PATH:/home/theuns/TagUI_Linux/tagui/src
(base) [theuns@localhost ~]$ echo $PATH
/home/theuns/anaconda3/bin:/home/theuns/anaconda3/condabin:/home/theuns/.local/bin:/home/theuns/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/theuns/anaconda3/pkgs/openssl-1.1.1g-h7b6447c_0/lib/pkgconfig:/home/theuns/TagUI_Linux/tagui/src

**Comment by kriskcandy** [comment]
Please help me. I am trying to do the "tagui update" but I'm still not sure if the first part (no. 6+ is right) and then proceed with next steps to actually use TagUi from Terminal on a Mac.

![Screen Shot 2022-04-18 at 1 06 28 PM](https://user-images.githubusercontent.com/25932206/163853179-65c6b2de-faac-4499-ae9b-04b540309462.png)

This is what I see in my terminal. What is wrong?

Shoptelligences-MacBook-Pro:src shoptelligence$ sudo ln -sf /Users/shoptelligence/tagui /usr/local/bin/tagui
Shoptelligences-MacBook-Pro:src shoptelligence$ tagui /Users/shoptelligence/tagui/flows/samples/1_google.tag
-bash: /usr/local/bin/tagui: is a directory
Shoptelligences-MacBook-Pro:src shoptelligence$ tagui update
-bash: /usr/local/bin/tagui: is a directory
Shoptelligences-MacBook-Pro:src shoptelligence$ pwd
/Users/shoptelligence/tagui/src
Shoptelligences-MacBook-Pro:src shoptelligence$ ls
casperjs		sleep.php		tagui_parse.php
chrome			slimerjs		tagui_py
end_processes		tagui			tagui_r
end_processes.cmd	tagui.cmd		tagui_report.php
erina			tagui.sikuli		tagui_runner.php
erina.cmd		tagui_chrome.php	tagui_service.php
languages		tagui_config.txt	test
media			tagui_crontab		translate.php
office			tagui_footer.js		transpose.php
phantomjs		tagui_header.js		ws
sikulix			tagui_helper.php
Shoptelligences-MacBook-Pro:src shoptelligence$ 

**WHAT should I be putting exactly (according to how you see my path above) to do the equivalent of what this is asking here below: **

sudo ln -sf /your_tagui_path/tagui/src/tagui /usr/local/bin/tagui

tagui /your_tagui_path/tagui/flows/samples/1_google.tag

**then how do I run TagUI in Terminal to do any of the exercised listed in the videos as they do not look or act the same to run etc. 

<img width="1214" alt="path" src="https://user-images.githubusercontent.com/25932206/163852715-806063e4-76f5-4f0f-a9dd-c0609621c35b.png">

**Comment by kensoh** [comment]
The line should be -

```
 sudo ln -sf /Users/shoptelligence/tagui/src/tagui /usr/local/bin/tagui
```

I've left AI Singapore, but copying @ruthtxh she can assist further :)

**Comment by kriskcandy** [comment]
^ Sorry to be a bother but would you please delete the above path as this is sensitive information.
And this message as it does not pertain to anything helpful to the community?
thanks @ruthtxh
