### ISSUE TITLE
Opening a program file on windows - use keyboard and visual automation

### ISSUE THREAD

**Issue by gesnype** [kelaberetiv/TagUI#764]
Dear Kensoh,

I was reading your documentation and most of it deals with web element. How do i write code to automate the execution of files stored on local computer? Thanks

**Comment by kensoh** [comment]
Can you share an example what do you mean?

If you mean running commands from the command line, you can use the run step.

**Comment by gesnype** [comment]
For instance, I want the RPA to follow these steps:

Click on search icon on windows menu
Type "Microsoft Word" in search box
Enter to search
Click on Microsoft Word to open app
etc.

**Comment by kensoh** [comment]
I see.. to interact with desktop apps use the keyboard step, and visual automation. I don't have Windows to test, it should be something like below to do what you want above. msword.png is an image snapshot (you can use the Windows snipping tool to capture it) of the MS Word icon.

```
keyboard [win]
keyboard Microsoft Word
click msword.png
```

For keyboard step and visual automation, Java OpenJDK is needed. See here for the installation link - https://tagui.readthedocs.io/en/latest/setup.html

**Comment by gesnype** [comment]
Thank you. This is what I have been looking for. 

However, I noticed every time i run the TAG file, the first step is always opening a Google Chrome browser even though my first step is not a URL. Why is this so?

**Comment by kensoh** [comment]
Yes this is the default behaviour because most use cases involve the web browser. You can run with -n or -nobrowser option to disable that.

`tagui flow_name.tag -n`
`tagui flow_name.tag -nobrowser`
