### ISSUE TITLE
Facing issue python and tagui configuration.

### ISSUE THREAD

**Issue by 92Ashutosh** [kelaberetiv/TagUI#765]
Hi,

I'm trying to write simple code using python as given on Tagui website but getting output which is not expected. Here I'm adding my source code...
echo "Hello World"
py begin
a=1
b=5
c=a+b
print(c)
py finish
echo py_result
 

Here is my Output : 
![python](https://user-images.githubusercontent.com/35497268/77404376-a44b0e80-6dd7-11ea-93f4-c044cc5db7cf.JPG)

Please Suggest

**Comment by kensoh** [comment]
For TagUI v6 syntax, it should be the following -

```
echo Hello World
py begin
a=1
b=5
c=a+b
print(c)
py finish
echo `py_result`
```

For TagUI before v6, it would be the following -
```
echo 'Hello World'
py begin
a=1
b=5
c=a+b
print(c)
py finish
echo py_result
```

**Comment by kensoh** [comment]
To check your version, type tagui without any parameters.

Also, try typing `python` in your command prompt to ensure that Python is available to TagUI on your computer. If not TagUI will not be able to run Python and send instructions to it.

CC @siowyisheng
