### ISSUE TITLE
init() function not able to complete download TagUI

### ISSUE THREAD

**Issue by soorejmg** [kelaberetiv/TagUI#767]
After importing tagui module, i am trying to run the init function like t.init(). Due to some office restriction to github in firewall we are not able to complete the tagui zip file download (200+ download size file) successfully. So i have download the file separately and unzipped to a folder. Is there someway to point the tagui.init() function to that folder so that redownloading wont happen from script?

**Comment by kensoh** [comment]
Hi @soorejmg for RPA for Python issues, raise issue here as its a separate personal project - https://github.com/tebelorg/RPA-Python/issues

RPA for Python (previously called TagUI for Python) is designed to work in environments without internet or having firewall to block internet. You can use the pack() function to automatically generate the zip to copy to your intranet computer. After that, to get the latest release, you can use update() function to generate a Python script that you can copy to update your installation on the air-gapped computer.

More details - https://github.com/tebelorg/RPA-Python#core-functions
