### ISSUE TITLE
Trouble executing python scripts / PhantomJS - pending user checks

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#773]
from user query posted wrongly at https://github.com/tebelorg/RPA-Python/issues/118

---

Hi, im having trouble executing a python script inside the flow, Have tried inserting the whole chunk of code inside it,,. execution seems fine though, the script itself never launches and the flow just keeps running ahead. Tried launching it with run file.py and run /path/file.py  both execute browser briefly before crashing with this message error:

"Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report".

python enviroment is fine, added phantom as well, also the script works when executed on its own.

```
py begin
import os
import openpyxl
import shutil
import timeit

start = timeit.default_timer()


def copyRange(startCol, startRow, endCol, endRow, sheet):
    rangeSelected = []
    # Loops through selected Rows
    for i in range(startRow, endRow + 1, 1):
        # Appends the row to a RowSelected list
        rowSelected = []
        for j in range(startCol, endCol + 1, 1):
            rowSelected.append(sheet.cell(row=i, column=j).value)
        # Adds the RowSelected List and nests inside the rangeSelected
        rangeSelected.append(rowSelected)

    return rangeSelected

def pasteRange(startCol, startRow, endCol, endRow, sheetReceiving, copiedData):
    countRow = 0
    for i in range(startRow, endRow + 1, 1):
        countCol = 0
        for j in range(startCol, endCol + 1, 1):
            sheetReceiving.cell(row=i, column=j).value = copiedData[countRow][countCol]
            countCol += 1
        countRow += 1


current_path = os.getcwd()
for ROOT, DIR, FILES in os.walk(current_path):
    for file in FILES:
        if file.endswith('xlsx') and file.startswith("Publicar"):
            excels = [file]

            for case in excels:
                base = openpyxl.load_workbook("ebook.xlsx")
                excel = openpyxl.load_workbook(case)

                basesheet = base['OHSHIT']
                excelsheet = excel['Libros']


                def get_counter(filename="scriptcounter.txt"):
                    with open(filename, "a+") as f:
                        f.seek(0)
                        val = int(f.read() or 0) + 1
                        f.seek(0)
                        f.truncate()
                        f.write(str(val))
                        return val


                counter = get_counter()
                fila = counter * 100
                DataCopiada = copyRange(1, fila, 22, (fila + 100), basesheet)
                pasteRange(1, 6, 22, 105, excelsheet, DataCopiada)
                excel.save(case)

                sourcepath = "C:\\tagui\\flows\\python" + "//" + case
                destination = "C:\\Users\\Cubano\\Downloads"
                shutil.move(sourcepath, destination)
                print(counter)

                stop = timeit.default_timer()

                print('Time: ', stop - start)
                break



py finish
echo `py_result`
```

**Comment by kensoh** [comment]
Hi @adoravant, moving issue here as this is a TagUI's Python integration question, and not related to the RPA for Python tool.

**Comment by kensoh** [comment]
Hi @adoravant, running below script works for me and returns 100 in output.

```
py begin
def a(input):
    return input * input
print(a(10))
py finish
echo `py_result`
```

The PhantomJS error is usually shown when a command to run is missing. Can you check 2 things. 1. Check if running above sample script works. 2. Check that typing `python` command from your command line where you run tagui command works in launching Python.

TagUI will run `python` command to invoke a Python process in the background to run Python code. If the command is not available it will not work. The part where it is invoked is in tagui\src\tagui.cmd for Windows and tagui/src/tagui for macOS/Linux.

**Comment by kensoh** [comment]
Also, if the bulk of your automation is in Python already, you can consider using RPA for Python tool to do the RPA automation. It is built on TagUI so the functions are similar to TagUI steps. But you won't have the 21 human languages and can only write in Python code.

https://github.com/tebelorg/RPA-Python

**Comment by adoravant** [comment]
Ohhh I just realised RPA-python is a different tool, hands on then!. your sample code works fine btw., Its my script who totally ignores its ends and wont do nothing whe executed. 
Moving on to RPA to see if that solves it.
I love your work btw!

**Comment by kensoh** [comment]
Thank you! Oh yes haha.. It is meant for Python users to easily use TagUI functionalities.

I see, sure you can try the RPA for Python tool and it should work better for more complex Python code as everything happens in the Python environment, and the RPA functionalities are done in the backend seamlessly.
