### ISSUE TITLE
Can TagUI click item of combobox in WinForms app without using OCR ? 

### ISSUE THREAD

**Issue by githubcyc** [kelaberetiv/TagUI#775]
`combobox` in WinForms Application like this:

![Fig1](https://user-images.githubusercontent.com/19488835/78227853-7f097f00-7500-11ea-88f5-8e52800d71e6.png)

**Comment by kensoh** [comment]
There are a few ways. First way is using OCR as you said. For eg `click Exclamation using ocr` will click on the matching text there on the form by using Tesseract technology.

Another way is that you capture a screenshot of the part that you want to click and then do a `click exclamation.png` to click on it by visually finding a match of the element to click. You can also combine using `select combo_box.png as exclamation.png` to first click on the box.

Another way is if the position to click is always the same, you can click using (x,y) coordinates. For eg, `click (444,555)`. To figure out the coordinates on the screen, you can use TagUI live mode and type echo \`mouse_xy()\` to see the (x,y) value of the current mouse location.

Another way is use keyboard shortcuts to click on it, for eg first click visual on the form and combo box, then you can do `keyboard [down][down][enter]` to go down the number of times to the right option to select it.

There are probably more ways that I do not know of. But they would all need the built-in SikuliX technology to invoke the computer vision using OpenCV and OCR using Tesseract.

**Comment by kensoh** [comment]
Closing issue for now until further inputs!

**Comment by githubcyc** [comment]
@kensoh , thanks for ur quick response.
there may be efficient way to do it with python.
```
from pywinauto.application import Application

app = Application().connect(title_re="Form1", class_name="MainForm")
# ComboBox1 is Classname (like id) for ComboBox conponent
app['Form1'].ComboBox1.select('Exclamation')
```

**Comment by kensoh** [comment]
Very nice, thanks for sharing @githubcyc!

**Comment by kensoh** [comment]
For users with Python and PyWinAuto package installed, yes. They can do something like above in TagUI by wrapping the Python code in the `py begin` and `py finish` block.

```
py begin
...
py finish
```
