### ISSUE TITLE
R Usage Deprecated - to bring back as it is useful to TagUI & R users

### ISSUE THREAD

**Issue by pythiantech** [kelaberetiv/TagUI#776]
I am on a mac Catalina(10.15.4) and trying to use the python RPA package. However, `r.close()` seems to hang the system indefinitely. I thought of using `R` to overcome the issue I am facing but got the error that R usage is now deprecated. I thought you were going to continue with R, weren't you? 

I really hope you do.

**Comment by kensoh** [comment]
Hi @pythiantech can you tell me more about how you are using R with TagUI?

For the TagUI project, from v6 we have decided to deprecate R as Python has become the main language for ML models, and to facilitate transition to v7 later by removing features that are not as often used. However, there is some recent team change, thus that is not a factor anymore. The only factor to consider now is whether having R integration is useful to TagUI users.

For RPA for Python project, I maintain a fork that still has integration with R. But that is something not accessible by default from the API - https://github.com/tebelorg/RPA-Python#api-reference

**Comment by kensoh** [comment]
For the RPA for Python tool, it's a separate personal project, you can raise issues at its GitHub page if you run into any problem. You can try using r.debug(True) to output log message and save a copy of the execution log to share with me if there is any clue why r.close() hangs.

**Comment by pythiantech** [comment]
@kensoh thanks for the clarification.
In my current workflow, I am working with AIS data, which essentially gives positions (lat, lon) of ships in near real-time. I am using some GIS packages in R, in particular, `sf` for spatial computational stuff. There are certain built-in functions there which are not available in Python. Hence would appreciate if you could still support R.

On another note, I don't quite agree that Python is the lingua franca when it comes to machine learning. Data wrangling and visualization, which is a very important part of data science, is definitely much better using the `tidyverse` in R. Having said that, I don't want to start another long debate on which language is better. I personally think that both have their merits. In my workflow, I use RStudio as my IDE and packages like `reticulate` which allow me to include Python code as well. Best of both worlds!

**Comment by kensoh** [comment]
@pythiantech what you said is convincing and valid, we'll add back R integration to TagUI!

**Comment by kensoh** [comment]
In the meantime, if you are using v6 and want to use R integration before we add that back and publish the packaged zip files again, try this -

1. edit the file tagui\src\tagui_parse.php
2. search for `function r_intent(`
3. delete the following line and save

```
echo "ERROR - R integration is deprecated, raise an issue if you need to use it\n"; return "";
```

**Comment by pythiantech** [comment]
Roger that, chief!
Much appreciated :)

**Comment by kensoh** [comment]
You're welcome, truly appreciate your feedback!

Hi @siowyisheng I've create a PR above and merged directly to master. Since it is removing the 1-liner in tagui_parse.php and tagui_header.js and there are valid use cases by R users.

**Comment by kensoh** [comment]
Closing issue and the change above will be in the next packaged release
