### ISSUE TITLE
Indentation not working for tagui step calling subflow file - fixed with PR #779

### ISSUE THREAD

**Issue by Robertsson** [kelaberetiv/TagUI#778]
mainflow.tag
```
popup someurl
   tagui subflow.tag
```

Whatever is in the subflow.tag wont be executed on the popup. 
I'm guessing all the commands in the subflow.tag ignores the new indentation so they get executed on the main tab.

**Comment by kensoh** [comment]
You are right, thanks! I think the current implementation does not automatically indent everything in subflow.tag. Fyi @siowyisheng on a use case which is not working with the v6 indentation implementation. Will have a look to see what code change needed to make this work.

**Comment by kensoh** [comment]
Hi @siowyisheng made a PR https://github.com/kelaberetiv/TagUI/pull/779 that passes following tests. For your review and verification -

a.tag
```
for n from 1 to 3
    tagui b.tag
```
b.tag
```
echo 1
echo 2
echo 3
```
c.tag
```
http://tebel.org
click Automation projects
popup automation_projects
    tagui d.tag
```
d.tag
```
echo line 1
show file-automation_projects-LC2
echo line 2
show file-automation_projects-LC2
```
e.tag
```
echo 1
tagui f.tag
echo 2
```
f.tag
```
echo 1.5
echo 1.7
```

**Comment by kensoh** [comment]
Closing issue, the change above will be available in the next packaged release, or now by directly downloading from https://github.com/kelaberetiv/TagUI/archive/master.zip now to overwrite user current installation.

**Comment by kensoh** [comment]
Reopening this issue as the fix is not yet in the packaged zip. Users can download the latest copy of the code from here and unzip to overwrite their existing installations (please drag the folders under tagui\src to overwrite existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files.

**Comment by kensoh** [comment]
Closing issue since the latest packaged release TagUI v6.14 is out.

**Release notes** - https://github.com/kelaberetiv/TagUI/releases/tag/v6.14.0
**To download v6.14** - https://tagui.readthedocs.io/en/latest/setup.html
**Documentation** - https://tagui.readthedocs.io/en/latest/index.html
