### ISSUE TITLE
How to implement a double click or right click on selector

### ISSUE THREAD

**Issue by terrygoldman** [kelaberetiv/TagUI#78]
I would like to perform a mouse double click on the table row.

If I do a: 
_click some_row_selector
click some_row_selector_

It won't work as the webpage see it as 2 single clicks. 

I can do a _hover some_row_selector_, which works

Any ideas? 

BR,
Terry

**Comment by kensoh** [comment]
Hi Terry, thanks for raising this. This is not added as part of the standard steps as double click is not a usual action for web applications. In the meantime, if you are running it in default mode using PhantomJS browser, you can try the following -

```js
this.mouse.doubleclick(tx(identifier));
```

This uses the [CasperJS doubleclick](http://docs.casperjs.org/en/latest/modules/mouse.html#doubleclick) function to click on the element, while still using TagUI smart identifier by using the tx(). Looks like adding a new `dclick` step will be useful to make double-clicking easier for Chrome browser and visual automation using Sikuli.

**Comment by kensoh** [comment]
Besides `dblick` step, `rclick` step would also be good, to support more expressive UI interactions.

**Comment by kensoh** [comment]
Implemented with thanks to @aussiroth and @lohvht - usable right away from [cutting edge version](https://github.com/kelaberetiv/TagUI/archive/master.zip).

**Comment by lookang** [comment]
> dblick

dclick is the correct command
but i tried
dclick moe99999x@mail.dev.sls.ufinity.com
![snap1](https://user-images.githubusercontent.com/20143558/110579866-86bab480-81a2-11eb-995f-03ffb153748e.png)


not dbclick

**Comment by kensoh** [comment]
Hi Lawrence, inside tagui/src/tagui_header.js, can you search for this function `chrome.mouse.doubleclick` and replace with following block of codes to see if either block works for this scenario?

If both does not work it could be how the web page somehow isn't automatable directly using this best practice approach from Puppeteer. In that case, can use the computer vision method to do the dclick to see if that works (either dclick directly visually or dclick base on an xy offset from an anchor element).


**block 1 - moving mouse cursor to element before double-clicking**
```js
chrome.mouse.doubleclick = function(selector,y) { // double press and release on center of selector or point
if (!y) {chrome.scrollIntoViewIfNeeded(selector); var xy = chrome.mouse.getXY(selector);}
else var xy = {x: selector, y: y}; // get coordinates accordingly
chrome.mouse.action('mouseMoved',xy.x,xy.y,'none',0);
chrome.mouse.action('mousePressed',xy.x,xy.y,'left',2); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',2);};
```

**block 2 - separating the clicks into individual mouse down and up**
```js
chrome.mouse.doubleclick = function(selector,y) { // double press and release on center of selector or point
if (!y) {chrome.scrollIntoViewIfNeeded(selector); var xy = chrome.mouse.getXY(selector);}
else var xy = {x: selector, y: y}; // get coordinates accordingly
chrome.mouse.action('mousePressed',xy.x,xy.y,'left',1); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',1);
chrome.mouse.action('mousePressed',xy.x,xy.y,'left',1); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',1);};
```

**Comment by lookang** [comment]
> ```js
> chrome.mouse.doubleclick = function(selector,y) { // double press and release on center of selector or point
> if (!y) {chrome.scrollIntoViewIfNeeded(selector); var xy = chrome.mouse.getXY(selector);}
> else var xy = {x: selector, y: y}; // get coordinates accordingly
> chrome.mouse.action('mouseMoved',xy.x,xy.y,'none',0);
> chrome.mouse.action('mousePressed',xy.x,xy.y,'left',2); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',2);};
> ```

I tested with after re-opening a new cmd prompt (else it will not reload the TagUI files)
code 2 works! Awesome work @kensoh 
//https://github.com/kelaberetiv/TagUI/issues/78#issuecomment-795056564
// second chunk of code works
chrome.mouse.doubleclick = function(selector,y) { // double press and release on center of selector or point
    if (!y) {chrome.scrollIntoViewIfNeeded(selector); var xy = chrome.mouse.getXY(selector);}
    else var xy = {x: selector, y: y}; // get coordinates accordingly
    chrome.mouse.action('mousePressed',xy.x,xy.y,'left',1); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',1);
    chrome.mouse.action('mousePressed',xy.x,xy.y,'left',1); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',1);};

**Comment by kensoh** [comment]
Thanks Lawrence! I see.. Do you have other websites where you need to use double click?

By right, this change should be made so future releases of TagUI will behave this way. But I'm cautious to change this because, it may mean whatever has worked for other users so far may suddenly break when this change is made. I think this approach is inherited from Puppeteer, I was using that a lot for reference when improving the clicks action for TagUI.

**Comment by kensoh** [comment]
In the meantime, can you create a tagui_global.js and put it in tagui/src folder? Just put below inside. This will override TagUI default behaviour with global custom functions and applies to all workflows on your laptop. If you put a tagui_local.js in your flow folder, it will apply the custom JS functions to only workflows in that folder.

```js
chrome.mouse.doubleclick = function(selector,y) { // double press and release on center of selector or point
if (!y) {chrome.scrollIntoViewIfNeeded(selector); var xy = chrome.mouse.getXY(selector);}
else var xy = {x: selector, y: y}; // get coordinates accordingly
chrome.mouse.action('mousePressed',xy.x,xy.y,'left',1); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',1);
chrome.mouse.action('mousePressed',xy.x,xy.y,'left',1); chrome.mouse.action('mouseReleased',xy.x,xy.y,'left',1);};
```

**Comment by ativis** [comment]
Hi @kensoh, thanks for this wonderful resource! I am facing the similar issues with double clicking using the visual image recognition. I tried to open up the tagui/src/tagui_header.js folder but I face this popup. Any suggestions to implement a successful dclick?

![image](https://user-images.githubusercontent.com/32090754/163080750-be47a095-569c-4578-bc2b-badaddbb3789.png)

**Comment by kensoh** [comment]
I assume that you want to edit tagui_header.js manually. You will need an editor to do that (for eg Notepad++, VS Code, Notepad etc). Double-clicking will let Windows try to run the .js file, which is not what you want. CC @ruthtxh

**Comment by ruthtxh** [comment]
Hey @ativis perhaps you can right click the file then click Edit, to open it in an editor.
