### ISSUE TITLE
Issue with OCR - try on Windows or macOS, and try the Linux setup steps

### ISSUE THREAD

**Issue by jereff** [kelaberetiv/TagUI#783]
Hi,

when I try to use OCR feature in TagUI v6, the workflow will be stuck. so I checked log of tagui sikuli, and found below errors:
[tagui] INPUT  - [1] read /home/administrator/tagui/flows/samples/page.png to var1
[tagui] ACTION - read /home/administrator/tagui/flows/samples/page.png to var1
[error] script [ tagui ] stopped with error in line 582
[error] java.lang.UnsatisfiedLinkError ( java.lang.UnsatisfiedLinkError: Error looking up function 'TessPDFRendererCreateTextonly': /usr/lib/x86_64-linux-gnu/libtesseract.so.4.0.0: undefined symbol: TessPDFRendererCreateTextonly )
[error] --- Traceback --- error source first
line: module ( function ) statement 
359: main (  text_read )     temp_text = fullscreen_layer.text()
323: main (  read_intent )     return text_read(raw_intent)
520: main (  parse_intent )     return read_intent(script_line)
[error] --- Traceback --- end --------------
IDE terminated: returned: 1

any idea about this error?

**Comment by kensoh** [comment]
I haven't come across this error. Can you try 2 things to see if that helps -

1. try running your same automation script on Windows or macOS. To isolate the problem to see if it only happens on Linux or if the same script also fails on Win / Mac
2. try following the [setup steps here](https://sikulix-2014.readthedocs.io/en/latest/newslinux.html#newslinux) to do the setup required for OpenCV and Tesseract to work on Linux. OpenCV is used for computer vision and Tesseract is used for OCR capability of TagUI

**Comment by jereff** [comment]
Thanks Kensoh,

I resolved issue by update sikulix to 2.0.x, and installed tesseract 4.0.1.  I noticed that if some errors(like above error) happened in sikulix, the whole tagui will be keep running, is there any way to catch the error and print it  out in terminal, and then finish the executing? otherwise it will always in running.

**Comment by jereff** [comment]
to be more specific, the code is stuck in:
def text_locator ( locator ):
	   return findText(locator)
findText(locator) will not return, so whole things stuck.

**Comment by kensoh** [comment]
That's correct, TagUI assumes that SikuliX will respond to an instruction and will wait until SikuliX responds.

However, during initial use if it is not working, will need to rely on the logs to figure out the problem. Making a note for future reference. If this is a common issue, then some graceful error handling should be done below to just return 0 if crashes -

**tagui/src/tagui.sikuli/tagui.py**
```
intent_result_value = parse_intent(tagui_intent)
```
