### ISSUE TITLE
chrome-error://chromewebdata/ - Privacy error - Chrome blocks website

### ISSUE THREAD

**Issue by maddymb** [kelaberetiv/TagUI#785]
Hi 

I am getting below error while running tagui on mac :
https://opensource-demo.orangehrmlive.com/ - Privacy error
chrome-error://chromewebdata/ - Privacy error
Could you please help.

Thanks
Madhur

**Comment by kensoh** [comment]
Hi Madhur, I'm able to run the following script on my macOS and login successfully -

```
https://opensource-demo.orangehrmlive.com
type txtUsername as Admin
type txtPassword as admin123
click btnLogin
live
```
![Screenshot 2020-04-19 at 2 11 33 AM](https://user-images.githubusercontent.com/10379601/79648674-2cf47900-81e3-11ea-8d24-a208e5b34852.png)

Can you try running on another mac or try checking if your Chrome version is latest? Mine is Version 81.0.4044.113 (Official Build) (64-bit). If all these are checked already, then can you attach 1. a screenshot of the error shown on the command prompt when you run, and 2. the log file tagui\src\tagui_chrome.log to see if there are more clues?

**Comment by maddymb** [comment]
Hi Kensoh , 

Initially i was getting below error :
 
![Screenshot 2020-04-19 at 11 24 44 AM](https://user-images.githubusercontent.com/20455879/79680782-3a385480-8231-11ea-8e22-bed28e0f3a4e.png)

dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/maddy/Desktop/tagui/src/phantomjs/bin/phantomjs
  Reason: image not found


Then i run the following commands:
brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb

i got these commands from below link:
https://github.com/kelaberetiv/TagUI/issues/86

After running the above commands i am getting below error:
![Screenshot 2020-04-19 at 11 33 06 AM](https://user-images.githubusercontent.com/20455879/79680813-81264a00-8231-11ea-82d8-6c389ccdf208.png)

START - automation started - Sun Apr 19 2020 11:30:05 GMT+0530 (IST)
https://opensource-demo.orangehrmlive.com/ - Privacy error


chrome-error://chromewebdata/ - Privacy error
FINISH - automation finished - 2.8s

Could you please suggest.

Thanks
Madhur

**Comment by maddymb** [comment]
Please find log file below:


[tagui_chrome.log](https://github.com/kelaberetiv/TagUI/files/4498445/tagui_chrome.log)

**Comment by kensoh** [comment]
Hi Madhur, from the log above, it looks like on your computer the Google Chrome shows some invalid certificate error for this website and does not allow access. I'm afraid there isn't any solution that I have come across for this as I don't have visibility why the Chrome browser rejects visiting this website on your computer.

What you can try is 1) doing a simple run on a simple script with 1 line eg `https://google.com` to see if such error happens for all websites or this website only, and 2) try on another laptop or computer to see if this error happens.

```
[tagui] INPUT  -
[2] {"id":2,"method":"Page.navigate","params":{"url":"https://opensource-demo.orangehrmlive.com/"}}
[tagui] OUTPUT -
[2] {"id":2,"result":{"frameId":"EA039C0BABE0361BD367177FD480B63A","loaderId":"E58C4545108DEC2378F00FE8F4047D65","errorText":"net::ERR_CERT_INVALID"}}
```

**Comment by kensoh** [comment]
Closing issue for time being until further inputs
