### ISSUE TITLE
Improvement for documentation Linux installation - already included

### ISSUE THREAD

**Issue by puchalakd** [kelaberetiv/TagUI#788]
Hi,

I had to install php-cli to make it work.
In case of Debian Buster it was enough to:
`apt install php-cli`

**Comment by kensoh** [comment]
Hi @puchalakd thanks for raising this! Yes this is already included in the old doc and the new doc, on having to install PHP separately on Linux, as some distributions of Linux does not come with PHP -

https://github.com/kelaberetiv/TagUI/tree/pre_v6#to-use
https://tagui.readthedocs.io/en/latest/setup_troubleshooting.html#troubleshooting-windows
