### ISSUE TITLE
Understanding required on method text_read() in visual automation

### ISSUE THREAD

**Issue by joginderrohilla** [kelaberetiv/TagUI#789]
Queries:

1. How Tesseract OCR is working here?
2.  Is this Screen() method a turtle library method, since dont see any import, and how is it working? Does it capture screen if so how does fullscreen_layer.text() fecth data?

# function for reading text **using Tesseract OCR**
def text_read ( raw_intent ):
	if using_ocr(raw_intent):
		ocr_locator = True
		raw_intent = raw_intent[:-9].strip()
	else:
		ocr_locator = False
	params = (raw_intent + ' ')[1+(raw_intent + ' ').find(' '):].strip()
	param1 = params.split(' to ')[0].strip()
	print '[tagui] ACTION - ' + raw_intent
	if ocr_locator:
		matched_element = text_locator(param1)
		if matched_element == None:
			return 0
		else:
			temp_text = matched_element.text()
			output_sikuli_text(temp_text)
			return 1
	elif is_coordinates(param1):
		region_layer = define_region(param1)
		temp_text = region_layer.text()
		output_sikuli_text(temp_text)
		return 1
	**elif param1.endswith('page.png') or param1.endswith('page.bmp'):**
		fullscreen_layer = Screen()
		temp_text = fullscreen_layer.text()
		output_sikuli_text(temp_text)
		return 1
	elif file_exists(param1):
		if exists(param1):
			matched_element = find(param1)
			temp_text = matched_element.text()
			output_sikuli_text(temp_text)
			return 1
		else:
			return 0
	else:
		return 0

**Comment by kensoh** [comment]
Hi @joginderrohilla, TagUI relies on [SikuliX](https://github.com/RaiMan/SikuliX1) for its computer vision capability through OpenCV and OCR capability through Tesseract.

In above text_read() function in TagUI integration module for SikuliX, TagUI will map to SikuliX functions such as findText(), find(), text(), Screen().

The actual capturing screen and using Tesseract is handled by SikuliX and how it works in the backend the exact code and logic is not visible to TagUI.

**Comment by kensoh** [comment]
Adding on, these functions are internal functions of SikuliX that is only available to the SikuliX process when it is invoked in the background. These functions are not in the same Python environment as when you use py step. So they are not accessible directly from TagUI. If you need to use those functions, you have to go through SikuliX by using vision step.

**Comment by kensoh** [comment]
I'll close the issue for now, but let me know if you have any questions!
