### ISSUE TITLE
Is there any way to increase speed of TagUI? - hackable to 20-30x faster

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#790]
from user query

---

Hi Ken, Is there any way to increase the execution speed like other RPA paid tools? I have been asked this, so i thought to ask you before i make any statement.

**Comment by kensoh** [comment]
cc @joginderrohilla who raised the question

**Comment by kensoh** [comment]
Yes @joginderrohilla there is. TagUI is designed to mimic human user actions, thus by default it has delay in place and also typing character by character into fields, which is the normal behaviour for human app users.

However, there are ways to hack such that it can be 20-30X faster. By reduce the delay between TagUI to browser from 200ms (100+100) to 0ms, and changing the default typing behaviour from character by character to typing whole string at one go.

See below link for the example on RPA Challenge, and the hacks to speed up TagUI. In that example, instead of taking 2 minutes to run, scenario takes 4+ seconds to complete.

https://github.com/tebelorg/RPA-Python/issues/120

I won't recommend speeding it up as it will no longer behave like a human user, and more likely for automation to fail because the target websites or apps are not designed for superhuman usage. Also, such hacks will be overwritten if user upgrades their modified TagUI to new version.

**Comment by joginderrohilla** [comment]
> cc @joginderrohilla who raised the question

He is a RPA adviser, met on LinkedIn.

**Comment by kensoh** [comment]
There are also further hacks, if the automation involve visual automation. For eg removing the 1s delay added between actions, and let the mouse cursor teleport to target position instead of simulating the movement to target position.

**Comment by joginderrohilla** [comment]
Thanks Ken

**Comment by muratcim** [comment]
In headleas mode, the following code will also help you speed up

```
js begin
casper.options.trackingBuffer = [];
casper.options.pageSettings.loadImages = false
casper.options.pageSettings.loadPlugins = false
casper.options.onResourceRequested = function(casper, requestData, request) {

    // white list of tracking services, add here as many as you need
    var trackingServices = [
          'google',
	      'googleapis',
          'googletagmanager',
           '.css',
           '.js',
           '.svg',
           '.jpg',
           '.png',
      		'dsmcdn',
            '.ttf'
    ];

    trackingServices.forEach(function (needle) {

     // if the request url is in our white list, we push the data to the trackingBuffer array
    if (requestData.url.indexOf(needle) > 0) {
        casper.options.trackingBuffer.push(requestData.url);
			
        // OPTIONAL: prevents the tracking events to be actually sent
        // so we won't pollute GA with testing data
        request.abort();
    }
    });

};
js finish
```

**Comment by kensoh** [comment]
Great stuff, thanks for sharing @muratcim !
