### ISSUE TITLE
TagUI Issues when interacting with Two Factor Authentication (2FA)

### ISSUE THREAD

**Issue by QuiParses** [kelaberetiv/TagUI#794]
I notice that TagUI is unable to process 2FA actions, as frequently the additional level of security is an SMS-based multi-digit PIN. As more HTTPS services offer or move to 2FA for additional security, how will RPA in general deal with this?

It's be a shame to have to disable 2FA just so TagUI could work. Any ideas?

**Comment by kensoh** [comment]
For SMS-based 2FA, there are mobile apps that can receive SMS and forward as an email, or save the SMS as a file which could be synced to Google Drive and synced to PC. See this thread - https://github.com/kelaberetiv/TagUI/issues/197

Once SMS is accessible through email or a local file, you can write JavaScript code to read that or to make an API call to retrieve it programmatically. Although that is very troublesome and non-trivial.

For clicking image type of 2FA, there are paid API services which can solve such 2FA, you can google to find a good one. Then use `api` step to make such calls.

For hardware type of 2FA such as a RSA token, there is no workaround now except to engineer a robotic arm which computer vision camera to do it. That will be costly but not impossible.

However, above all else, if an app intentionally wants to enforce 2FA, it is better to not try to break it. They can always upgrade the 2FA to something unbreakable. Better to request a non-2FA special account for the automation to do it.

**Comment by kensoh** [comment]
Closing for now until further inputs!
