### ISSUE TITLE
TagUI Web Automation Extension - frame not supported, do manual

### ISSUE THREAD

**Issue by Venkylovesgit** [kelaberetiv/TagUI#796]
Hi Team,

I'm new to TagUI, I'm trying to automate below URL but neither Web Automation extension nor manual code(using xpath) failed to run the steps. The browser is opened and followed by webpage  but it stops in the second of the code. Please help me on this issue.

Code:-

https://ecom.mohw.gov.tw/web_app/entry_index.jsp
type //input[@name="UserLoginID"] as ABCD
type //html/body/table/tbody/tr[1]/td[2]/form/table/tbody/tr[6]/td[2]/input as xyz
click //html/body/table/tbody/tr[1]/td[2]/form/table/tbody/tr[9]/td/input[1]

Error Screenshot:

![image](https://user-images.githubusercontent.com/52130376/80732929-965b7c80-8b3f-11ea-896b-317eb30f4986.png)

regards
Venkat

**Comment by kensoh** [comment]
Hi Venkat,

From the documentation - https://tagui.readthedocs.io/en/latest/tools.html#tagui-chrome-extension

>The recording isn’t foolproof (for example, the underlying recording engine cannot capture frames, popup windows or tab key input). It’s meant to simplify flow creation with some edits, instead of typing everything manually.

In this case, the web elements are in a web frame, thus this can't be captured from recorder. It exist under the main frame `mainFrame` and subframe `mainContent`. Thus the following code works. However, it has to be inspected manually from Chrome inspector or use tools like ChroPath to inspect to get the frame name. Not easy, but possible.

```
https://ecom.mohw.gov.tw/web_app/entry_index.jsp
frame mainFrame | mainContent
    type //input[@name="UserLoginID"] as ABCD
    type //html/body/table/tbody/tr[1]/td[2]/form/table/tbody/tr[6]/td[2]/input as xyz
    click //html/body/table/tbody/tr[1]/td[2]/form/table/tbody/tr[9]/td/input[1]

wait
```

**Comment by kensoh** [comment]
Hi Venkat, I'm closing this issue for now till further inputs!
