### ISSUE TITLE
How to run TagUi In headless mode in VM? - try this and check log

### ISSUE THREAD

**Issue by sandeep14897** [kelaberetiv/TagUI#800]
Hello @kensoh

I was facing issue while running in headless mode. Could you help us solve this?

The Command prompt is opening and no further operations are performed.
And I want to add a point like, In the local desktop I was able to run fine. But the issue is while running in the VM.

Below mentioned are my Hardware details:
My local machine: Chrome version-81.0.4044.129, Operating system-windows 10 Home, RAM-4GB
VM: Chrome Version-81.0.4044.138, Operating system-windows server 2016 Datacenter,RAM-2GB

Thanks in Advance,

**Comment by kensoh** [comment]
Hi @sandeep14897, first try running in normal mode to see if it works. Maybe need to run normal mode to accept Google T&C before using headless mode.

You can try comparing the tagui_chrome.log when running chrome mode and headless mode to see what difference is there and if there is any error messages.

tagui_chrome.log is found in tagui\src folder and tracks the messages btw TagUI and Chrome.

**Comment by kensoh** [comment]
Closing for now till further inputs

**Comment by amanwadhwa08** [comment]
@sandeep14897  So were you able to run the script on VM
