### ISSUE TITLE
Call a TagUI Workflow or Script inside another script

### ISSUE THREAD

**Issue by Hassan-Ali123** [kelaberetiv/TagUI#801]
Hi! nice to see you all! I want to know what's the method of calling a TagUI script/workflow inside another script/workflow? Please guide me! Your suggestions are appreciated.

Thank you again!

**Comment by Robertsson** [comment]
Add the **tagui** then the filename :

https://tagui.readthedocs.io/en/latest/reference.html#tagui

```
tagui [flow file]
tagui [folder/flow file]
```

**Comment by Hassan-Ali123** [comment]
Hi Jonas! Thanks for your reply! It’s really helpful

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
