### ISSUE TITLE
-bash: tagui: command not found

### ISSUE THREAD

**Issue by omerbensaadon** [kelaberetiv/TagUI#803]
I have tried everything I have found online to get this to work without much success. 

I am running on macOS Mojave and have gotten `-bash: tagui: command not found` no matter how I try to run the sample flow. 

I have tried: 
- running the commands from the tutorial page
- installing tagui from npm 
- checking to see that tagui was copied over to /usr/local/bin/tagui (it was) 
- running tagui from inside of the src folder on my Desktop but nothing seems to work. 

Please help! This seems like the automation tool I have been waiting for

**Comment by omerbensaadon** [comment]
I resolved this by 

- first `npm install` with the -g (global) flag (which installs v.5.0 
- then I downloaded v6.0 and followed the installation instructions 
- then I resolved the `dyld: Library not loaded` error by following the instructions on the [troubleshooting page](https://tagui.readthedocs.io/en/latest/setup_troubleshooting.html#troubleshooting-macos-linux)

**Comment by kensoh** [comment]
Hi @omerbensaadon yes, the steps here should get TagUI up and running -

https://tagui.readthedocs.io/en/latest/setup.html
