### ISSUE TITLE
Away in personal emergency - mum in ICU on ventilator life support

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#804]

**Comment by RaiMan** [comment]
From the base of my heart I wish all the best.

**Comment by youleaf** [comment]
So sorry to hear that, we wish you the best during this difficult time.

**Comment by muratcim** [comment]
so sory I hope he will recover soon and get health.

**Comment by kensoh** [comment]
Hi @RaiMan @youleaf @muratcim thank you for your wishes. Yes we need all the medical help and prayers to bring her through this ordeal.

She is starting to regain consciousness. Still on ventilator life support. Medical team has started treatment on her microscopic polyangiitis condition and we are praying for improvement in her lungs to be able to breathe on her own soon.

**Comment by kensoh** [comment]
Closing this issue as there is now continuity in support for users who raise issues on GitHub.

My part-time contract with AI Singapore is ending and I'll not be renewing for time being. My colleague @siowyisheng will help support TagUI users with issues they raise on GitHub.

My mum has improved slightly over the past week but is still on ventilator support. We are praying for her lungs to continue to recover and for her kidneys to start recovering.

For my personal project RPA for Python, I'll leave a similar issue there https://github.com/tebelorg/RPA-Python/issues/144 open because there won't be continuity in fast and timely user support from me.
