### ISSUE TITLE
Tagui passing parameters to Python - use py_step() to send variables over

### ISSUE THREAD

**Issue by XLL1141348** [kelaberetiv/TagUI#807]
How to pass the value of tagui to Python as a parameter
![1](https://user-images.githubusercontent.com/49892339/82786154-a9d7da00-9e96-11ea-9ea6-7db32343b0b8.JPG)
![2](https://user-images.githubusercontent.com/49892339/82786158-ab090700-9e96-11ea-9369-bce025a4d637.JPG)

**Comment by kensoh** [comment]
See this example here -
https://github.com/kelaberetiv/TagUI/tree/pre_v6#python-integration

```
phone = 1234567
py_step('phone = ' + phone)
py print(phone)
echo `py_result`
```

The new docs has a typo, I'll tell my colleague - @siowyisheng, see this.
