### ISSUE TITLE
Cant't download in nobrowser mode - use normal browser interaction to download

### ISSUE THREAD

**Issue by gorcer** [kelaberetiv/TagUI#808]
Hi,

I try to download file in nobrowser mode.
1) First try

My script have a one line:

> https://doghouse.ru/pricelist/100sp_full.csv

Result:
There is no file in the directory

2) Second try:

My script:

> download https://doghouse.ru/pricelist/100sp_full.csv to 100sp.csv

wait 5

Result:
File exists, but it size is zero!

To run script i'm use command on my Ubuntu machine:

> tagui test.tag -n

Help please.

**Comment by siowyisheng** [comment]
ERROR - for headless and visible Chrome, download file using normal webpage interaction

You should get the error above. Currently, you will need to download the file through normal webpage interaction (clicking).

**Comment by gorcer** [comment]
I'm use normal browser interaction, see - first try

It's work in normal mode, but in nobrowser mode it's doesnt work.
File doesn't download.

**Comment by siowyisheng** [comment]
For normal browser interaction, you would need a link to click on to download the file. Visiting the URL won't work.

**Comment by gorcer** [comment]
Ok, i create simple page with DOWNLOAD link https://doghouse.ru/test

My script:
```
https://doghouse.ru/test
click DOWNLOAD
wait 10
```

My command:
```
tagui test.tag -n

START - automation started - Wed May 27 2020 14:01:16 GMT+1000 (+10)
https://doghouse.ru/test - 

click DOWNLOAD
wait 10

https://doghouse.ru/test - 
FINISH - automation finished - 10.5s

```

My result - there is now file in the directory,

P.S.: it's work with normal mode ( tagui test.tag -h)

**Comment by gorcer** [comment]
Rocket - it's cool)
What should I do?

**Comment by siowyisheng** [comment]
![2020-05-27-15-16-37](https://user-images.githubusercontent.com/25425028/82989332-197fcd80-a02d-11ea-95b5-73d1a3e79800.gif)

**Comment by gorcer** [comment]
What's about problem? You solve it?

**Comment by siowyisheng** [comment]
Oh I thought it was solved already. 

```chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'c:\\Users\\userid\\Downloads'});```
Try this before clicking download.

**Comment by gorcer** [comment]
It's doesn't work. It's freeze on start:

```
gorcer@www2:~/tagui/doghouse$ tagui test.tag -n

START - automation started - Thu May 28 2020 17:08:49 GMT+1000 (+10)

```

My script:

```
chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: '/home/gorcer/tagui/doghouse/'});

https://doghouse.ru/test
click DOWNLOAD
wait 5

```

NOBROWSER mode

**Comment by siowyisheng** [comment]
tested
```
https://doghouse.ru/test
click DOWNLOAD
```
run with `tagui my_flow.tag -h`

-h headless is to not show a browser.
-n nobrowser cannot download the file.

**Comment by gorcer** [comment]
Okay (((

Headless mode does't work on some my servers and if it's work it take to 3x system resource more.

**Comment by kensoh** [comment]
Hi Egor, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see.. Yes -headless mode runs Chrome using invisible mode, and Chrome takes up a lot of memory. However, it is better for automation because it is more accurate than the -nobrowser mode. That mode uses PhantomJS web browser which is an old browser and more likely to encounter issues during automation with modern websites.
