### ISSUE TITLE
What is mean NOBROWSER mode

### ISSUE THREAD

**Issue by gorcer** [kelaberetiv/TagUI#809]
Can you explain -n nobrowser mode?
I see the browser on a snap, but it's not chrome.

**Comment by siowyisheng** [comment]
It's for flows which don't use the browser. For example, if you're just clicking on the screen and automating other programs (SAP, Word).

**Comment by gorcer** [comment]
Then what browser I have seen in the snap?

**Comment by siowyisheng** [comment]
Just tested that when I run it, I don't see a browser. Can you screenshot what browser you mean?

**Comment by gorcer** [comment]
I'm confused. Who render HTML if no browser?

**Comment by kensoh** [comment]
Hi Egor, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see, TagUI runs on the PhantomJS engine for executing JavaScript. With -nobrowser, there is still a PhantomJS invisible browser, which is based on an older version of WebKit.

However, most modern websites are not tested with PhantomJS, so it is not the recommended way to automate websites headlessly. To automate websites without seeing browser, use -h or -headless to run Chrome using invisible mode. Let me know if you have questions!
