### ISSUE TITLE
How to test if a selector exists?

### ISSUE THREAD

**Issue by terrygoldman** [kelaberetiv/TagUI#81]
Hi,
  I would like to know if there is a way that I can test for the existence of the a selector on a page so that I can catch and gracefully handle

`ERROR - cannot find `

Is this possible in Tagui? 

BR,
Terry

**Comment by kensoh** [comment]
Depending on the use case, you can try something like this -

**checking if element exists**
```
http://tebel.org/index_mobile.php
if present('ABOUT')
snap ABOUT
if present('LINKEDIN')
snap LINKEDIN
```

**checking if element visible**
```
if visible('ABOUT')
snap ABOUT
if visible('LINKEDIN')
snap LINKEDIN
```

**Comment by kensoh** [comment]
Depending on the use case, you can try something like this -

**checking if element exists**
```
http://tebel.org/index_mobile.php
if present('ABOUT')
snap ABOUT
if present('LINKEDIN')
snap LINKEDIN
```

**checking if element visible**
```
http://tebel.org/index_mobile.php
if visible('ABOUT')
snap ABOUT
if visible('LINKEDIN')
snap LINKEDIN
```

**Comment by kensoh** [comment]
Closing this for now, maybe reopen or improve documentation when a similar issue is raised.

**Comment by fez226** [comment]
dont working the "if visible" for one element, but for another one yes (in the same page). thoughts?

**Comment by kensoh** [comment]
Hi @fez226 it could something wrong with the element xpath or locator, can you paste your script here, the part with the error? Copying @Aussiroth as AI Singapore is now maintaining the repo.

**Comment by ace-rivera** [comment]
Hello,

I'm not sure if this is the correct thread to ask this.
But I'm currently checking if a certain element exist using XPath instead of an identifier since there is no identifier for the element i'm checking. Below is a code snippet:

	if present(//*[@id="ui-accordion__toggler--28"]/span[2]/div/span)
	{
		fetch //*[@id="ui-accordion__toggler--38"]/span[2]/div/span/span to element_info
		echo element_info
	}

But this gives the following error:

    SyntaxError: Unexpected token '.'

    phantomjs://code/ace_test.js:1477 in injectJs
    phantomjs://code/bootstrap.js:456

**Comment by kensoh** [comment]
Adding on that in the next v6 release, a new function exist() will be added. It is similar to present() but will wait until the default timeout of 10 seconds before returning not found, instead of immediately.
