### ISSUE TITLE
Logging in multiple times to a site without cached logins - use incognito hack

### ISSUE THREAD

**Issue by saravananselvamohan** [kelaberetiv/TagUI#810]
Hi,
I need to test multiple scenarios of login case. The browser stores the cache of successful login credentials. When I run the flow with different credentials, the flow fails as the browser already stored previous login information.

**Comment by gauravgandhi1315** [comment]
@saravananselvamohan Looking at this issue, will get back to you soon

**Comment by gauravgandhi1315** [comment]
@saravananselvamohan You can use this to clear your browser cache:

`chrome_step('Page.navigate',{url:` 'chrome://settings/clearBrowserData'});`

**Comment by kensoh** [comment]
Hi Saravan, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

There are some ways to achieve what you want. First is to include log out steps as part of your automation script, that would replicate how you will do it as a normal human user.

Second way is hacking TagUI by forcing it to run using Chrome incognito mode. This way, there won't be stored settings for each run. Check below link on how to do the hack. It is a simple 1-line modification -

https://github.com/tebelorg/RPA-Python/issues/123

**Comment by kensoh** [comment]
Closing the issue for now, but lemme know if you have any questions
