### ISSUE TITLE
Combining -headless mode with datatable.csv

### ISSUE THREAD

**Issue by olvd** [kelaberetiv/TagUI#813]
The command:

`tagui myflow.tag -headless mydata.csv`

does not seem to be supported. Can you confirm?
My scenario is automation of a desktop app using OCR.
When not in -headless mode, the browser pops up and gets in the way.

How can I still iterate using a datatable?
Thanks.

**Comment by olvd** [comment]
Not sure what happened initially but it is working now. Please ignore this issue.

**Comment by michaeldcalmeida** [comment]
Hi Friend, I have the same problem, if you can explain to me how you solved it, I appreciate it.

**Comment by olvd** [comment]
@michaeldcalmeida I cannot remember exactly what was the cause, but this is what works for me:
`tagui myflow.tag -nobrowser mydata.csv`

**Comment by kensoh** [comment]
Hi Olivier and Michael, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Let me know more details if you are still running into similar issues!
