### ISSUE TITLE
Extract info from website using Xpath in tagui

### ISSUE THREAD

**Issue by Sora1433** [kelaberetiv/TagUI#822]
Hi I am also trying to use xpath to extract info from a table in this website and is looking to extract the first and third column: https://www.dbs.com.sg/personal/rates-online/foreign-currency-foreign-exchange.page
__________________________________________________________________________________________________________
Here are the codes:
dump Name,Price to number6.csv

rows = count('//*[@id="sgfx"]/div/div[2]/table[31]/tbody')

for row from 1 to rows
    read ((//*[contains(@class,"tbl-primary")]/tbody/tr)[`row`]//td)[1] to name
    read ((//*[@id="sgfx"]/div/div[2]/table[31])[`row`]//td)[3] to price
    forex_rate = [name,price]
    write `csv_row(forex_rate)` to number6.csv
__________________________________________________________________________________________________________

Thank you for reading as any help would be greatly appreciated:)

**Comment by joginderrohilla** [comment]
Hi Sora, Please find below updated code and Video created for the same in my channel-https://youtu.be/e_T8FWlCICk

//Step 1: Create CSV file with Date stamp in filename and headers Name , Price
dump Name,Price to Data`datestamp()`.csv

//Step 2:Launch Web application 
https://www.dbs.com.sg/personal/rates-online/foreign-currency-foreign-exchange.page
wait 3

//Step 3:Count rows under the foreign exchange table 
rows = count('(//table[contains(@Class,"tbl-primary")])[1]//tbody/tr')
echo `rows`
//Step 4:Run loop for all rows to extract currency name and corresponding Price
for row from 1 to rows
{
read (//table[contains(@Class,"tbl-primary")])[1]//tbody/tr[`row`]/td[1] to name
echo `name`
read (//table[contains(@Class,"tbl-primary")])[1]//tbody/tr[`row`]/td[3] to price
echo `price`
forex_rate = [name, price]
//Makes entry of current currency Name and it's Price to the CSV File created at Step 1
write `csv_row(forex_rate)` to Data`datestamp()`.csv
}

**Comment by kensoh** [comment]
Sorry I was away the past few months, now starting to look at issues from oldest to latest - https://github.com/tebelorg/RPA-Python/issues/144

For this webpage, this is a good example to see how to get data from the table -
https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail#tagui-workflow

@joginderrohilla has a complete and useful example!

For TagUI v6, indentation is used to mean a code block under a condition statement - 
https://github.com/kelaberetiv/TagUI#if-and-loop-code-blocks-can-use-indentation-instead-of-curly-braces-

So all the lines in your issue description below the `for row from 1 to rows` should be indented with a tab or some spaces.
```
for row from 1 to rows
    read ((//[contains(@Class,"tbl-primary")]/tbody/tr)[row]//td)[1] to name
    read ((//[@id="sgfx"]/div/div[2]/table[31])[row]//td)[3] to price
    forex_rate = [name,price]
    write csv_row(forex_rate) to number6.csv
```

Closing issue for now but please lemme know if you have any question.

**Comment by pankajbnsl** [comment]
Hi i am trying to get the text of every li tag one by one

Here are the codes : 
rows = count('//*[@id="simple-menu"]/div[3]/ul/li')

for (n=1; n<rows; n+=1)
{ 
read (/html/body/div[7]/div[3]/ul/li)[n] to value
if value equals to "Civics"
    // Perform actions if the condition is true
    click /html/body/div[7]/div[3]/ul/li[9]
break;
}


but I get and error and error is "ERROR- cannot find (/html/body/div[7]/div[3]/ul/li)[n]

**Comment by kensoh** [comment]
The code looks wrong, need backticks to refer to variables. Maybe something like this. Tagging @pankajbnsl, and @ruthtoh from AI Singapore who is maintaining TagUI project.

```
read (/html/body/div[7]/div[3]/ul/li)[`n`] to value
```
