### ISSUE TITLE
Run step fails with any command: Fatal Windows exception, code 0xc0000005.

### ISSUE THREAD

**Issue by olvd** [kelaberetiv/TagUI#824]
When I use even the simplest command like:

```
run dir
echo run_result
```

Using TagUI v6.0.0 fails with:

```
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
```

I am not familiar with PhantomJS and wonder what is going on.
Thanks for you help.

**Comment by kensoh** [comment]
Sorry Olivier I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see, the run step can only run command files and executable files that are available on the operating system.

On Windows, there is no dir.exe or dir.com or dir.bat / dir.cmd file. The dir command actually comes from the command cmd.exe. You can try the following to run the cmd command and call the dir command that's part of the cmd command.

```
run cmd /c dir
echo run_result
```

More details at this issue - https://github.com/kelaberetiv/TagUI/issues/473#issuecomment-506111630

Closing this issue for now but please lemme know if you have any questions.
