### ISSUE TITLE
Error: Invalid syntax. Default option is not allowed more than '2' time(s)

### ISSUE THREAD

**Issue by MinionsAnalyst** [kelaberetiv/TagUI#826]
Hi,

I am trying to install TagUI in Windows. When trying to run the first line of installation code,

setx path "%path%;c:\tagui\src"

I face this error message below.

Error: Invalid syntax. Default option is not allowed more than '2' time(s).
Type "SETX /?" for usage.
'crumb' is not recognized as an internal or external command, 
operable program or batch file.

Anyone faced this similar issue? I am also unsure why 'crumb' is being mentioned in the error message when I did not use this in my installation code.

Thank you.

**Comment by kensoh** [comment]
Sorry @MinionsAnalyst I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

From some solutions online, it looks to be a problem with a variable having an extra backslash -
https://stackoverflow.com/questions/29190444/invalid-syntax-with-setx-for-having-more-than-two-arguments-when-there-are-onl/29194542

Or a variable folder name having space -
https://stackoverflow.com/questions/17215562/invalid-syntax-with-setx

A solution (see below link) is to manually add the tagui\src path into your path environment variable - 
https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

Closing issue for now but please lemme know if you have any input or question.

**Comment by kensoh** [comment]
Changing [setup instructions](https://tagui.readthedocs.io/en/latest/setup.html) to add path manually instead of using setx,
as that can be problematic to do on some systems, eg https://github.com/kelaberetiv/TagUI/issues/761 and https://github.com/kelaberetiv/TagUI/issues/826
