### ISSUE TITLE
[doc issue] enter is not in the doc

### ISSUE THREAD

**Issue by riverbuilding** [kelaberetiv/TagUI#830]
step "enter" is widely used in examples and demos but it is not in the doc.
better add it in.

**Comment by kensoh** [comment]
Sorry @riverbuilding I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Can you tell me more where enter step is still used in examples and demos? TagUI steps originally have 2 names for each step, eg click/tap, type/enter. The focus then was flexibility. But this was later deprecated to only 1 name per step. enter step still can be used in the TagUI script, but shouldn't be used in examples anymore.

Closing issue for now, but please lemme know your inputs and I see if something can be changed to avoid confusion.
