### ISSUE TITLE
SyntaxError when using IF condition

### ISSUE THREAD

**Issue by cyherus** [kelaberetiv/TagUI#833]
Hi Ken,

I'm currently using the cutting-edge version TagUI v6.0.0 (for windows). I was exploring the use of IF and Loop,

```
loc = "Changi"
for c from 0 to 1
{
	for s from 0 to 2
	{
		for d from 1 to 9
		{
			lbl_flight = "lbl_Flight"+c+s+d+"1"
			read `lbl_flight` to slot
			if slot is more than 0
				echo `loc`: Flight `c``s``d`1 has `slot` slots available
		}
	}
}
```
The looping works, but when I add the IF condition, it returns error:
> SyntaxError: Expected token ')'

Any advice?

**Comment by Robertsson** [comment]
If you remove **is** in "if slot is more than 0" it should work.

Parser currently only looks at " more than " and replaces that with >  so the word is stays the same in the .js export.

Unclear if it's the documentation or the parser that should be changed.

**Comment by cyherus** [comment]
@Robertsson ,

Thanks for that! It works now. Yes, the documentation needs to be updated.
https://tagui.readthedocs.io/en/latest/main_concepts.html#if-statements

**Comment by kensoh** [comment]
Hi Guys, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Thanks for raising this, yes the docs need to be changed, sorry for the confusion!

I've just updated to remove the erroneous ` is ` in the numerical comparison conditions.
