### ISSUE TITLE
or & and in if condition, using ocr in exist() - added 'using ocr' to exist() & present()

### ISSUE THREAD

**Issue by vincecao** [kelaberetiv/TagUI#834]
Hi, kelaberetiv, I can not find the way for using OR and AND example in tagui in document. Is any way I can add operator?

Also I can not use exist() to find text by using ocr, `if exist('abc using ocr')` is not work. Could you help me?

Thank you.

**Comment by kensoh** [comment]
Sorry Vince, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Below is an example of using `and` / `or` in conditions -
```
a = 1
b = 2
c = 'carrot'
d = 'durian'

if a equals to 1 and b equals to 2
    echo YES
else
    echo NO

if c equals to 'cat' or d equals to 'durian'
    echo YES
else
    echo NO
```

The exist() and present() functions are not designed to take in text search using ocr. Let me review if that can be added in.

**Comment by kensoh** [comment]
Above commits adds 'using ocr' search to present() and exist(). To use it, you can download the latest copy of the code from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files. Thanks for raising this!

**Comment by kensoh** [comment]
Closing issue since the latest packaged release TagUI v6.14 is out.

**Release notes** - https://github.com/kelaberetiv/TagUI/releases/tag/v6.14.0
**To download v6.14** - https://tagui.readthedocs.io/en/latest/setup.html
**Documentation** - https://tagui.readthedocs.io/en/latest/index.html
