### ISSUE TITLE
TagUI click not working with elements loaded using ajax - pending user replication details

### ISSUE THREAD

**Issue by amitvikram123** [kelaberetiv/TagUI#835]
Hello Kensoh,
I am using tagui and chrome(casperjs) to automate my web app. But it seems the click is not working 
on elements loaded using ajax. I am using full xpath of element which I got from browser for the click action. I also tried using css selector but even that is not working. I cannot use dom as it is asynchronous in nature. Please help.

**Comment by kensoh** [comment]
Sorry Amit, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

TagUI will automatically wait for an element to appear before it acts on the element. The most common cause of not finding an element is it belongs to a webpage embedded as a frame. To automate frames, need to use frame step - https://tagui.readthedocs.io/en/latest/reference.html#frame

Also, you can run `tagui live` from the command line to go into live debugging mode, and test if element is found. If you continue to run into an issue, can you paste your sample script here that can recreate the issue?

**Comment by amitvikram123** [comment]
Hi just increased the wait time to 15 and its working.

**Comment by amitvikram123** [comment]
Closing the issue
