### ISSUE TITLE
TagUI in remote server (Centos 7)

### ISSUE THREAD

**Issue by avantec2020** [kelaberetiv/TagUI#836]
i have TagUI in my localhost (Windows 10) but i want install in a remote server. I have root access by terminal. i download files and install java, but i don't use GNOME only terminal. I can work with this? Very thanks

**Comment by kensoh** [comment]
Sorry @avantec2020, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I have not tried running TagUI with a visible Chrome browser on a Linux without any GUI. I don't think that's possible.

For Chrome headless using -h or -headless switch it might be possible but I'm not sure. For the -n or -nobrowser mode it should be possible, but the headless PhantomJS engine is an old browser and may not work correctly when automating modern websites.

Java or OpenJDK is only needed for visual automation or low level control of keyboard or mouse. But without a GUI these features aren't applicable. Closing issue for now but please lemme know if you have any input or question
