### ISSUE TITLE
Wait for page load

### ISSUE THREAD

**Issue by terrygoldman** [kelaberetiv/TagUI#84]
Is there a way to wait until finishes loading? 

BR,
Terry

**Comment by kensoh** [comment]
TagUI explicitly waits for a web element or image to appear before acting on it. The default time out of 10 seconds before error can be set in tagui_config.txt. If you expect long loading but do not want to change that timeout setting, you can use the `wait` step to wait for a number of seconds before proceeding with the next step.

https://github.com/kelaberetiv/TagUI#steps-description

**Comment by kensoh** [comment]
Closing this issue for now but do let me know if you run into issues!

**Comment by fez226** [comment]
hello @kensoh i have a similary problem, sometimes my page load in 10 seconds, sometimes 1 minute, sometimes more or less... there is a way to wait until the page load? like a loop until a element is visible maybe? can you help me with the code?

**Comment by kensoh** [comment]
Hi @fez226 one way is to make a for loop with delay to check if element has appeared -
https://github.com/kelaberetiv/TagUI#conditions-examples

But easier way is to update src/tagui_config.txt to change timeout settings to a large number -
https://github.com/kelaberetiv/TagUI#packaged-installation

For example, changing below -

`casper.options.waitTimeout = 10000;`

to

**Comment by kensoh** [comment]
Adding on, you can use the timeout step (under pro steps) to dynamically set the number of seconds to wait for an element to appear before timeout - https://github.com/kelaberetiv/TagUI#steps-description

**Comment by fez226** [comment]
thanks @kensoh but i dont want to wait 120000 if the page load on 10 seconds, i see a while https://github.com/kelaberetiv/TagUI#steps-description

but i dont undestand how to do it, can you help with a simple example code? 

while ([element]) == visible
{
// wait
}

**Comment by kensoh** [comment]
while loop is not reliable and deprecated - https://github.com/kelaberetiv/TagUI#conditions-examples

you can use for loop + present() + break but i'll recommend just setting time out using timeout step, so there is no additional code or steps needed to handle waiting until page loads.

read my above examples again. setting timeout in tagui_config.txt to 120000 (in milli seconds) means that it will only error out after 2 minutes if web page has not loaded. if it has loaded, execution auto continues. if use `timeout` step you can key in using seconds. eg timeout 60 if you think web page will load faster than 60 seconds.

**Comment by fez226** [comment]
thank u @kensoh we setting the timeout to 190000 and works, cheers
