### ISSUE TITLE
How to use variables in for loop limits

### ISSUE THREAD

**Issue by amitvikram123** [kelaberetiv/TagUI#840]
I need to do something like this
length = 20
for i from 1 to `length`
{
    echo `i`
}

**Comment by kensoh** [comment]
Hi @amitvikram123 sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

The solution is below, no need for backticks for the variable length in the for loop statement. The design is this way to make it more like natural language. Closing issue for now but lemme know if any input or question.
```
total = 20
for n from 1 to total
    echo `n`
```
