### ISSUE TITLE
Oracle Applet Application Running with JRE 1.6

### ISSUE THREAD

**Issue by BACCMED** [kelaberetiv/TagUI#842]
I have an oracle applet application must running in JRE 1.6 and I want to automate some process with TAGUI who running in JRE 1.8
there is a solution or a workaround for this.
Thanks.

**Comment by kensoh** [comment]
Sorry @BACCMED I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I think multiple versions of Java can co-exist on the same computer. Try installing OpenJDK from below link for your OS, and see if that works for you. Java is required for visual automation, OCR, low level keyboard and mouse capabilities.

https://tagui.readthedocs.io/en/latest/setup.html

Closing issue for now but please lemme know if you run into any issues.
