### ISSUE TITLE
clipboard() not working - previously requires js or ; in syntax, updated to recognise now

### ISSUE THREAD

**Issue by ronisc** [kelaberetiv/TagUI#843]
Hi, 

I am using version 6 but it seems like it still can't recognize the clipboard function.

```
C:\tagui\src>tagui live

START - automation started - Thu Jul 09 2020 14:18:52 GMT+0100 (GMT Daylight Time)

LIVE MODE - type done to quit
clipboard('some text')
ERROR - cannot understand step clipboard('some text')
```

Any idea?

Using version 6 on Windows 10.
(as a side note, it is not working on both live mode and script mode)

**Comment by alexandruioanvoda** [comment]
I'm also having an issue with clipboard.

`really = clipboard()
dump really to clip.txt`

and the clip.txt just says `really` instead of saying what is inside the actual clipboard

**Comment by siowyisheng** [comment]
Hi @alexandruioanvoda.

This changed in v6 for consistency with the other steps. 
Just do 
```
dump `really` to clip.txt
```
https://github.com/kelaberetiv/TagUI#echo-dump-write-steps

**Comment by sheneeb** [comment]
@siowyisheng this thread is closed , though the original issue is the step clipboard is not understood. Even I am facing the same issue

**Comment by pl1094602077a** [comment]
还是无法识别剪切板，有办法解决吗

**Comment by kensoh** [comment]
Hi Guys, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Reopening issue to figure out what's wrong. I think  `clipboard('some text')` should be `clipboard('some text');` or `js clipboard('some text')` to order to be recognised as a function call. Maybe there's typo in docs.

**Comment by kensoh** [comment]
The original syntax to write to clipboard is `clipboard('abc');` or `js clipboard('abc')`. The docs have typo. But it's definitely more intuitive to recognise `clipboard('abc')` as trying to write to the clipboard. Above commits fixes this.

Users can download the latest copy of the code from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files. Thanks for raising this!

**Comment by kensoh** [comment]
Closing issue since the latest packaged release TagUI v6.14 is out.

**Release notes** - https://github.com/kelaberetiv/TagUI/releases/tag/v6.14.0
**To download v6.14** - https://tagui.readthedocs.io/en/latest/setup.html
**Documentation** - https://tagui.readthedocs.io/en/latest/index.html
