### ISSUE TITLE
How to auto translate text with TagUI?

### ISSUE THREAD

**Issue by mapofthe** [kelaberetiv/TagUI#844]
Hello! I need to get text from one field on web page, then translate it from English to Russian and paste it to another field. Can TagUI do it? I need it to repeat many times

**Comment by ronisc** [comment]
Hi, 

I am new to TagUI, but as far as I know TagUI is using a single chrome instance.
So if you want to implement switching between browsers, it will be a combination of the TagUI Chrome instance together with  using computer vision and flip between windows and work with the other window.
In the TagUI Chrome you will be able to use xpaths and web actions, but for the other window you will need to simulate a user.

Should be doable.

Another option,  If you have some development background, you can use API for the translation.
Microsoft Azure is offering a good API REST service with a free tier. 
[https://azure.microsoft.com/en-gb/services/cognitive-services/translator/#overview](url)

Then you can use https://github.com/tebelorg/RPA-Python to implement your logic,

Hope that helpful.

**Comment by kensoh** [comment]
Hi @mapofthe and @ronisc , sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

What @ronisc are good options, in a scenario when translation has to happen live on the same page. There's another way by invoking another webpage and using popup step to use Google Translate to do the translation. But that is very hackish.
