### ISSUE TITLE
Unclear debugging instructions

### ISSUE THREAD

**Issue by stevzie** [kelaberetiv/TagUI#846]
The docs say:
"Create log files for debugging

To do advanced debugging, you can create log files when running flows by creating an empty tagui_logging file in tagui/src/"

Did you mean an empty directory (rather than file)?
Is there a "-" command needed to get the debugging output?

The presence of the directory alone doesn't seem to do anything.

**Comment by siowyisheng** [comment]
You just need to create a file named `tagui_logging` within the `tagui/src/` folder.
