### ISSUE TITLE
How to switch between multiple browser tabs

### ISSUE THREAD

**Issue by prashanthtv** [kelaberetiv/TagUI#847]
Hello, I was trying to learn to automate workflows using tagui. It is as a great platform indeed.
I stumbled across a issue where I need to switch to a different window as part of the workflow. How do I do it.

Eg: I go to this link "https://www.google.com/intl/en-GB/gmail/about/#" and click on the "Sign in" link. 
This is taking me to a new Browser tab where I have enter my user credentials.
How do I switch my control to the parent window to this new tab. Really appreciate your help in this regard.
![Signinpage](https://user-images.githubusercontent.com/4215208/88175848-0e6ba700-cc44-11ea-97ff-5aa813789dd3.png)
![user credentials page](https://user-images.githubusercontent.com/4215208/88175855-10356a80-cc44-11ea-9865-af481f798ddb.png)

Thanks
Prashanth

**Comment by siowyisheng** [comment]
Check out [the popup step](https://tagui.readthedocs.io/en/latest/reference.html#popup).

popup signin
  type xxxx as yyyy
  click zzzz

**Comment by prashanthtv** [comment]
Thanks for the quick reply, It works..Thanks once again.
