### ISSUE TITLE
hi is this tagui solution can be used not on browser , but on application directly .

### ISSUE THREAD

**Issue by fguerouali** [kelaberetiv/TagUI#849]
hi is this tagui solution can be used not on browser , but on application directly ex open calculator ...
I try the :
Click (screen of the application)
or
Click (coordinate of application
or
click nameofapplication using ocr 
But nothing happen.
Im on windows 10 
Thanks for reply

**Comment by kensoh** [comment]
Sorry @fguerouali I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes it can be used on desktop apps by using visual automation method and using keyboard step, for eg -
https://github.com/aimakerspace/TagUI-Bricks/tree/master/MS-Word-Letter

Have you completed the installation instructions here - https://tagui.readthedocs.io/en/latest/setup.html
Including installing OpenJDK, which is required for visual automation.

Is there any error message after each step or the program hangs? Can you check in the folder tagui\src\tagui.sikuli, there is a file tagui_windows.log, can you paste the contents of the file here after doing the `click abc.png` step?

I'm closing the issue for now, you most likely have found the solution after many months. But please lemme know if you have any input or question so we can look more into the issue.
