### ISSUE TITLE
Unable to load script rpa_python.js - phantomjs://code/bootstrap.js:113 in __die

### ISSUE THREAD

**Issue by mbolduc-usesi** [kelaberetiv/TagUI#850]
Brand new windows 2016/2019 server with Python3.8 installed and I can't get RPA to initialize at all.

PS C:\Users\Administrator> pip install rpa
Collecting rpa
  Downloading rpa-1.27.1.tar.gz (5.6 kB)
Collecting tagui>=1.27.1
  Downloading tagui-1.27.1.tar.gz (23 kB)
Using legacy setup.py install for rpa, since package 'wheel' is not installed.
Using legacy setup.py install for tagui, since package 'wheel' is not installed.
Installing collected packages: tagui, rpa
    Running setup.py install for tagui ... done
    Running setup.py install for rpa ... done
Successfully installed rpa-1.27.1 tagui-1.27.1

PS C:\Users\Administrator> python.exe
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpa as r
>>> r.init()
[RPA][ERROR] - following happens when starting TagUI...

Unable to load script C:\Users\Administrator\rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

False

**Comment by rafa761** [comment]
Same here

**Comment by kensoh** [comment]
Sorry Guys I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

RPA for Python is a personal side project, please raise the issue here - https://github.com/tebelorg/RPA-Python/issues

However, I most likely won't have time to work on it for now. Catching up with issues raised here past few months. Closing the issue here. From the error message above, it looks like a user file permissions access issue.

Maybe the package can't write to the c:\users\administrator directory. Try to run from your user desktop folder to see if it helps. Another thing to try is opening command prompt as administrator to see if that helps.

**Comment by ZhaoJiangJie** [comment]
I met same error ,please refer to @kensoh reply https://github.com/tebelorg/RPA-Python/issues/151,and first make sure tagui can work in cmd line:https://tagui.readthedocs.io/en/latest/setup.html.I found my err was that missing windows C++ files，It can work after i installed the  windwows sys file.

**Comment by kar-pat** [comment]
I can't run commands of the type r.click('abc.png') or r.click('path/abc.png'). I am running rpa on an M1 (2020) mac.

Things I have already tried:

- Downsizing the image to 72 ppi
- Test given here https://tagui.readthedocs.io/en/latest/setup.html
- reinstalling Correto
- Enabled accesibility to terminal and AEServer in Security and Privacy(Here Java doesn't show up for me, but AEServer does)
- When I run the google.tag command I get the following response

> ln: /usr/local/bin/tagui: No such file or directory
zsh: command not found: tagui

- Lastly the rpa_python.log file says

> Unable to open file: /Users/username/Documents/SBOM/rpa_python.js
 phantomjs://code/bootstrap.js:113 in __die
  Unable to load script /Users/username/Documents/SBOM/rpa_python.js; check file syntax
  phantomjs://code/bootstrap.js:113 in __die

**Comment by kensoh** [comment]
Install PHP manually this way - https://github.com/tebelorg/RPA-Python/issues/335#issuecomment-989470056

Mac started removing PHP in newer releases of macOS. Inferring from your rpa_python.log error. Copying @ruthtxh

**Comment by kar-pat** [comment]
I have already installed php 8.1.8. using Homebrew. Still doesn't work. Also, java doesn't appear for me in Privacy>Accessibility  as mentioned here https://github.com/tebelorg/RPA-Python/issues/78
but terminal and AEServer does. Could this have something to do with it?

**Comment by kensoh** [comment]
Install Java from https://aws.amazon.com/corretto choose OpenJDK v8 (64-bit).

Try typing `php -v` from your Mac terminal and see what happens. Mine works with v8.1.1.

```
PHP 8.1.1 (cli) (built: Jan  8 2022 08:29:30) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies
```
