### ISSUE TITLE
Minimum PHP version?

### ISSUE THREAD

**Issue by iandoug** [kelaberetiv/TagUI#851]
Hi

Was working in initial testing with Vivaldi, but the browser plugin does not seem to work properly in Vivaldi. (Am installing Chromium to try that instead.)

Then the CLI scripts suddenly started throwing PHP errors, and I could not see why.

What's the minimum PHP version?

Am running on Linux.

Thanks, Ian

**Comment by iandoug** [comment]
Works better after I did the linking step .... but it curiously worked sometimes without that step.

It seems like PHP errors should be interpreted as "there is an error or typo in your script".

**Comment by kensoh** [comment]
Hi Ian, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

TagUI was developed and tested with PHP 5 and then PHP 7. I think a typical PHP version should work. Provided the `php` command is accessible from the command line. It is required to do the parsing of TagUI script into JavaScript code before running the automation sequence. For Windows, the PHP is included as part of the packaged zip. For macOS and most Linux variants, they come with PHP already. For Ubuntu, will require installing PHP.
