### ISSUE TITLE
ERROR - steps did not start with opening an url

### ISSUE THREAD

**Issue by iandoug** [kelaberetiv/TagUI#852]
Hi

Using Chromium browser with TagUI extension.

I click start, paste a URL in the address bar, hit enter, it loads, I do some things, and when I go to export it, it says

ERROR - steps did not start with opening an url

What am I doing wrong?

thanks, Ian

**Comment by kelvinl22** [comment]
Hi,

You should open new tab, paste URL to load page before click START.

**Comment by kensoh** [comment]
Sorry Ian, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes what Kelvin said is correct, start recording after you have gone to the website URL. Closing issue for now but please lemme know if you have any input or question, or if you could replicate the issue again. I sometimes do get this error, some issue inherited from the open-source recorder project I used for this.
