### ISSUE TITLE
Still issues selecting from dropdown

### ISSUE THREAD

**Issue by iandoug** [kelaberetiv/TagUI#853]
Hi

I see this is a persistent problem.

Site in question is http://ieants.cc/code/keyboard/klatest/#/config
I want to select a particular option from dropdown list "Presets".

Have tried various things in live mode, nothing wants to work. Occasionally get a error back from the site backend saying it can't find the requested layout.

The site uses a lot of Angular, don't know if that is affecting things.

Have tried these in live mode, none work.

select kb-config-select-list as acemak1.standard.json
select Preset as Amuseum.standard.json   ( click Preset actually puts focus on the list)

select //body/div[2]/div[1]/div/div[2]/table/tbody/tr/td[2]/div/form/div[2]/div/select/optgroup[2] as acemak1.standard.json

select //body/div[2]/div[1]/div/div[2]/table/tbody/tr/td[2]/div/form/div[2]/div/select as acemak1.standard.json

Don't know what else to try ...

Thanks, Ian

**Comment by kensoh** [comment]
Sorry Ian, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

It looks like the website http://ieants.cc/code/keyboard/klatest/#/config is no longer running.

For using the select step, the option value to put is the 'value' attribute when you inspect the dropdown from Chrome browser. Value is usually an unique identifier and is thus used as the reference for the option to choose.

Alternatively, you can consider using visual automation method to do the selection, something like below, where dropdown.png is an image snapshot of the dropdown element, and option_1.png is an image of the option you want.

```
select dropdown.png as option_1.png
```

You can test out in the live mode before writing the script. Closing issue for now but lemme know if any problem.
