### ISSUE TITLE
I cannot use crontab with Linux and Tagui

### ISSUE THREAD

**Issue by eduardolc21** [kelaberetiv/TagUI#854]
I have tried to schedule an automation flow with crontab (for Linux), in the crontab editor with the format: 

**00 08 * * * /full_path/tagui/src/tagui flow_filename option(s)** . Then I have tried the following:

1) 07 00 * * *  /home/user_name/tagui/src/tagui samples/1_yahoo chrome
2) 40 23 * * * /home/user_name/tagui/src/tagui 1_yahoo.log chrome
3) 26 22 * * *  /home/user_name/tagui/src/tagui 1_yahoo
4) 38 22 * * * /home/user_name/tagui/src/tagui samples/1_yahoo
5) 40 22 * * * /home/user_name/tagui/src/tagui 1_yahoo chrome

It doesn't pop up anything, It is supposed to appear a chrome webpage.

Am I writing the wrong syntax? **Beforehand, thanks for your support/answers**

**Comment by kensoh** [comment]
Sorry Eduardo, I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

First, try running the commands from your Linux command prompt to see if it works. For eg below, for TagUI v6 -

`/home/user_name/tagui/src/tagui /home/user_name/tagui/flows/samples/1_google.tag`

In crontab, the starting directory may not be in the same as tagui, so you can do - 

`07 00 * * * cd /home/user_name/tagui/src; ./tagui ../flows/samples/1_google.tag`

or try using the full path to see if that works -

`07 00 * * * /home/user_name/tagui/src/tagui /home/user_name/tagui/flows/samples/1_google.tag`

The default behaviour is launching Chrome for TagUI v6, so the chrome option is no longer needed. However, I'm not sure how running a visible browser from crontab will behave on Linux. Haven't tried that before. Closing issue for now but please lemme know if you have any input or question.
