### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by oulufeng** [kelaberetiv/TagUI#855]
Tagui： How to  returns to the previous page of the browser dirrectly?

**Comment by kensoh** [comment]
Sorry @oulufeng I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

There are a few ways to do that, first way by using dom step -

**dom window.history.back()**
```
https://google.com
type q as rpa[enter]
wait
dom window.history.back()
type q as tagui[enter]
wait
```

Second way is use the internal function chrome.back() -

**chrome.back()**
```
https://google.com
type q as rpa[enter]
wait
chrome.back()
type q as tagui[enter]
wait
```

Third way is to use visual automation to click on the browser back button to go back.

Functions like back, forward and refresh are not often used during normal processes, thus for simplicity of the API these steps are not part of TagUI steps. Closing issue for now but please lemme know if any question.
