### ISSUE TITLE
can i use the document.ready or window.onload in the dom statement ?

### ISSUE THREAD

**Issue by MD-luffy** [kelaberetiv/TagUI#856]
dom begin
return document.getElementById('xxx').value
dom finish
echo `dom_result`

i found the result always null，so i doublt that maybe the dom isn't loaded, so i add the live command before dom begin, and the the result was right, then i try to add window.onload to listen the loaded event, but i found it seems didn't work, so how can i resolve such issue, thank you very much ^_^

**Comment by kensoh** [comment]
Sorry @MD-luffy I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

One way to wait for an element to appear before continuing automation is use the hover step -

```
hover element_identifier
```

```
wait for element_identifier
```
PS - using `wait for` works as well, it will be converted to `hover` during execution

This way, the element will be confirmed loaded before you work on it. Also, for reading element value, you can use read step - https://tagui.readthedocs.io/en/latest/main_concepts.html#read

Closing issue for now but please lemme know if you have any input or question.

**Comment by kensoh** [comment]
Adding on, TagUI steps like click or read, will auto-wait for the UI element to appear, before interacting with it. The default timeout is 10 seconds, and can be changed with timeout step, for eg `timeout 5 seconds` or `timeout 300`
