### ISSUE TITLE
if statement not working as intented

### ISSUE THREAD

**Issue by sheneeb** [kelaberetiv/TagUI#863]
OpUnit = 'Months'
if `OpUnit` === 'Months'
    echo `OpUnit`

the following does not output any value

START - automation started - Sat Sep 05 2020 18:31:39 GMT+0400 (Arabian Standard Time)

FINISH - automation finished - 0.1s

**Comment by sheneeb** [comment]
Ok I figured this out  by using 'equals to'

**Comment by kensoh** [comment]
Sorry @sheneeb I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

Yes the following works. Can use the natural language method or JavaScript equality comparison -

```
OpUnit = 'Months'
if '`OpUnit`' equals to 'Months'
    echo Yes

if '`OpUnit`' equal to 'Months'
    echo Yes

if '`OpUnit`' == 'Months'
    echo Yes
```
