### ISSUE TITLE
echo showing variable name instead of value

### ISSUE THREAD

**Issue by ericdarwin01** [kelaberetiv/TagUI#864]
Hi All,
I'm a new user in tagui.

I've read the docs and examples, and followed the tutorials.

One thing I cannot do right is the echo part.

For example the tutorial 1 - https://rpa-sg.org/TagUI-Tutorial-1/tagui-tutorial-1-goodreads-com-part-1.php

when doing the tagui live, the echo part does not show the title of the page. The command was executed but no output.
and everytime I do an echo for a variable, it just writes the variable name, not the value.

during live, opening the goodreads page --> ok
read the title using xpath --> ok (output command prompt shows value of the title)

but this code:
echo "title = " + title

on my system, output is:
"title = " + title

instead of the value of title

Is there anything that I am missing here?

excuse the beginner level question here, but I wish to learn more of this.

Thank you.

**Comment by sheneeb** [comment]
Hi @ericdarwin01 
Try using `` around the title 
Like this 
Echo `title`

**Comment by ericdarwin01** [comment]
Hi @sheneeb 

Thanks for your reply.

It works!

Thanks again.

**Comment by kensoh** [comment]
Hi Eric, sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I've updated the docs, there were a couple of locations where ticks are missing for variables in echo step.
