### ISSUE TITLE
How to use visual automation across machines work different screen resolutions?

### ISSUE THREAD

**Issue by agalino91** [kelaberetiv/TagUI#868]
Is it possible to use a screenshot/image specified using visual automation even when the machines have different screen resolution? Thank you

**Comment by kensoh** [comment]
Sorry Anna I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I'm afraid no. Different screen resolutions, the image snapshots captured will be quite different in size. During automation run, when the computer vision engine tries to match the images with UI elements, if the size difference is too much it will not work.

Closing issue for now but please lemme know if any input or question.
