### ISSUE TITLE
Cannot create new element using dom - try build from simple code, live step to verify

### ISSUE THREAD

**Issue by amitvikram123** [kelaberetiv/TagUI#869]
Unable to create new input element using tagui dom
Here is my code
js current_dir = '/home/amit/ocr/ocr5/'
js fs = require('fs');
js content = fs.read(current_dir + 'popup1.html');
field_names = []
js csv_file = current_dir + 'result.csv';
js csv_file2 = current_dir + 'result2.csv';
load '+csv_file+' to lines
array_lines = lines.split("\n")
for (n=0;n<array_lines.length;n++)
{
    items = array_lines[n].split("-")
    field_names[n] = items[0].trim()
}
m = array_lines.length;
load '+csv_file2+' to lines
array_lines1 = lines.split("\n")
for (n=0;n<array_lines1.length;n++)
{
    items = array_lines1[n].split("-")
    field_names[m] = items[0].trim()
    m = m + 1
}
js data = {content:content,fields:field_names};
dom_json = data
wait 10
dom begin 
document.getElementsByTagName("body")[0].innerHTML += dom_json.content;
field_names = dom_json.fields;
const modalId = "tagui_modal_btn";
for (var i = 0; i < field_names.length; i++)
{
    field_name = field_names[i].toLowerCase().replace(" ","_");
    divField = document.createElement("div");
    divField.classList.add("tagui-form");
    labelField = document.createElement("label");
    labelField.for = field_name;
    textNode = document.createTextNode(field_names[i]);
    labelField.appendChild(textNode);
    inputField =  document.createElement("input");
    inputField.type = "text";
    inputField.name = field_name;
    inputField.id = field_name;
    divField.appendChild(labelField);
    divField.appendChild(inputField);
    console.log(divField);
}

The chrome doesnot create element and just freezes. Also cannot view DOM error in browser console.
Please suggest solution

**Comment by amitvikram123** [comment]
Also dom finish is also present

**Comment by kensoh** [comment]
Sorry @amitvikram123 I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

This looks like a complex block of code to run in DOM. I tried doing some simple tests and they work with dom step.

You can try writing simple dom statements to test and build up to something complicated. Put a `live` step at the end of each test run so that you can inspect the web browser DOM to see the status of your DOM code after each iteration.

**Comment by amitvikram123** [comment]
Hello it works when I put "if" and "for" statements inside dom blocks and using dom step for rest

**Comment by amitvikram123** [comment]
Closing the issue
