### ISSUE TITLE
Downloading on Chrome 'Failed - Path too long'

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#87]
The error message 'Failed - Path too long' may appear when downloading files on Chrome. The default download directory is set to the location where the flow file resides. If the location on the computer has exceeded the path limit by Chrome, above error message can appear.

**Comment by kensoh** [comment]
The command below can be used to overwrite default location by changing flow_path to some path name, for eg 'c:\' or '/tmp'. Alternatively, flow file can be stored at a location with shorter path name.

```
chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: flow_path});
```

**Comment by TimMiller005** [comment]
I would like to suggest you, try **LongPathTool** program to resolve this issue.
This tool is very helpful to resolve the issue.
