### ISSUE TITLE
Chrome v85 headless failed on Windows Scheduler - pending user log details

### ISSUE THREAD

**Issue by nurdiyana-ali** [kelaberetiv/TagUI#872]
Hi!

We are running TagUI on headless mode and launched it using PowerShell script. When we run the powershell script on the terminal, it works just fine, and the files were downloaded (as what the tagUI automation were programmed for).

However, scheduling it via Windows Task Scheduler failed. We noticed that there are .log, .js, .raw were in fact generated. We suspected that the headless Chrome is not working when launched via Windows task scheduler.

The powershell script can be seen here:
https://github.com/nurdiyana-ali/AutomationScripts/blob/master/PowerShell/WindowsUpdateScheduler.ps1

Let us know how we can fix this.

**Comment by kensoh** [comment]
Sorry @nurdiyana-ali I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

From your description, it sounds like TagUI could start but somehow Chrome can't work. Here are some ideas -
- try removing the -h headless switch to see if Chrome can work
- put an empty file tagui_logging in c:\tagui\src folder to retain the logs to see any clues from logs
- double-check user permissions to make sure user running the task has access to c:\tagui\src folder
- try running the windows task schedular as admin user or grant all permissions to all users to c:\tagui\src folder

**Comment by kensoh** [comment]
(closing issue for now till further inputs)
