### ISSUE TITLE
How to automate desktop calculator using tagui - use visual automation method

### ISSUE THREAD

**Issue by mouriya99** [kelaberetiv/TagUI#876]
Can somebody help me in automating desktop calculator with proper steps
Thanks in advance

**Comment by kensoh** [comment]
Sorry @mouriya99 I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

You can do this with visual automation method, for examples using click step -
https://tagui.readthedocs.io/en/latest/main_concepts.html#click

With visual automation, you can provide an image file of the button to click on. You can take snapshots of the buttons 1 to 9 and save as 1.png ... 9.png. After that in your flow you do `click 1.png`.

You can also use variables to decide on what image files to click, but must first write JavaScript code to break up the number into the individual digits. Alternatively, you can use `js clipboard(number_variable)` to copy something into clipboard to paste to the calculator, either by visually clicking the paste option or using `keyboard [ctrl]v`.

The main idea is do it visually on the screen like how a human user will normally use the app.

Closing issue for now but please lemme know if you have any input or question.
