### ISSUE TITLE
TagUI JS click not wokring

### ISSUE THREAD

**Issue by egodagesd** [kelaberetiv/TagUI#879]
I'm trying to automate daily in time/ out time process through online HR system since we are working from home.

**Comment by egodagesd** [comment]
I'm trying to automate daily in time/ out time process through online HR system since we are working from home.

![image](https://user-images.githubusercontent.com/61376471/97140065-dfecf300-1781-11eb-84f8-4556c289c62a.png)


These are steps I need to follow.
1) Login to the system
2) click on highlighted finger print button in the image.

![image](https://user-images.githubusercontent.com/61376471/97140121-fbf09480-1781-11eb-9e6b-32f84db340ca.png)

I even tried to put click (87,87) as the x,y coordinates. But that is also not working.

Here is my script with x,y coordinates for the swipe button.

```
https://www.hris.com/security/login?ReturnUrl=%2fhome%2findex
enter #txtusername as username
enter #txtpassword as password
click #btnsubmit
wait 8 seconds
click (87,87)
wait 5 seconds
```

Script with Xpath

```
https://www.hris.com/security/login?ReturnUrl=%2fhome%2findex
enter #txtusername as username
enter #txtpassword as password
click #btnsubmit
wait 8 seconds
click //*[@id="RecordAttendanceWidget"]/div[3]/div[2]/a/i
wait 5 seconds
```


Button xpath: //*[@id="RecordAttendanceWidget"]/div[3]/div[2]/a/i
full xpath: /html/body/div[2]/div/div/div/div[2]/div[2]/div/div/div[3]/div[2]/a/i

I tried to record these all steps using new TagUI chrome extension as well. When I click the swipe button, it won't record any step in the script.

Really appreciate if you can guide on this.

**Comment by kensoh** [comment]
Sorry @egodagesd I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

For swiping action, I think using normal click step will not work. Try visual automation, something like this -

```
// make Chrome browser in focus in foreground to receive visual automation actions
click chrome_icon.png

// use a snapshot of button (eg using snipping tool), to tell TagUI to move mouse to button
hover button.png

// do a low level mouse down action
mouse down

// measure current (x,y) coordinates and add offset
x = mouse_x() + 50
y = mouse_y()

// move mouse to the right by 50 pixels
hover (`x`,`y`)

// do a low level mouse up action
mouse up
```

Closing issue for now but please lemme know if run into any issue or question.
