### ISSUE TITLE
Can't paste from the clipboard to a dump or save a file 

### ISSUE THREAD

**Issue by frankinstyyn** [kelaberetiv/TagUI#882]
I'm currently trying to paste text from the clipboard but unable to. This only results in the text being added to the file and not the clipboard copied information. I've tried the below and still no luck. Any help is appreciated!

dump //*[@id="mat-dialog-4"]/app-create-api-key-dialog/div[2]/div/p to api-key-new.txt

text_contents = clipboard()
dump text_contents to api-key.txt

**Comment by kensoh** [comment]
Hi @frankinstyyn, Sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see, for accessing variables, backticks are required in order for TagUI to know if you are referring to text string or variable. What you are looking for would be following examples. Closing issue for now but please lemme know if you have any input or question, if you saw somewhere a bad example in documentation or sample lemme know too I go fix it.

```
text_contents = clipboard()
dump `text_contents` to api-key.txt
```
```
dump `clipboard()` to api-key.txt
```
