### ISSUE TITLE
Do not close browser on execution done

### ISSUE THREAD

**Issue by macrocks** [kelaberetiv/TagUI#884]
Hello Team,

I have a scenario where user wants to login to a website and perform few  operations and wait on a page to perform manual actions.
currently I am able to perform actions automatically but on last action how to force tagui to hold execution and user can perform manual action

**Comment by kensoh** [comment]
Hi @macrocks sorry I was away the past few months - https://github.com/tebelorg/RPA-Python/issues/144

I see.. there are a few ways to do this -

1. if you know how long to wait beforehand you can use `wait 300 seconds` to tell TagUI to wait for some time before continuing rest of automation
2. if the time to wait is unknown, you can use `live` step to pause execution. after user is done, can type `done` into the command prompt window to continue automation
3. if there are no automation actions required after user manual actions, you can run tagui with the `-s` or `-speed` option, eg `tagui demo.tag -s`. in the speed mode, TagUI does not close or restart the web browser between datatable iterations, but it fits your purpose not to close browser.

Closing issue for now but please lemme know if you have any input or question

**Comment by macrocks** [comment]
thanks a lot @kensoh  .. Option 3 helped us to complete our task.

**Comment by kensoh** [comment]
Oh great @macrocks, thanks for replying back that the solution works!
