### ISSUE TITLE
csv value syntax

### ISSUE THREAD

**Issue by BaliJaniHu** [kelaberetiv/TagUI#886]
Hello,

If I run your sample 6C_datatables I can not see the value of variables at first echo, but later it is appears during mail sending.

C:\tagui\src\samples\6_datatables>tagui 6C_datatables.tag user_data.csv

START - automation started - Sun Nov 29 2020 21:56:10 GMT+0100 (K├Âz├ęp-eur├│pai t├ęli id┼Ĺ )
https://medium.com/tebelorg - Tebel.Automation ÔÇô Medium

**github_id " - " user_email**
api your_website_url/mailer.php?APIKEY=unique_key&SUBJECT=Hi @**ironman**&SENDTO=**tony@stark.org**&SENDFROM=Your Name <your_email@gmail.com>&MESSAGE=Your message line 1.<br><br>Your message line 2.
wait 3 seconds

https://medium.com/tebelorg - Tebel.Automation ÔÇô Medium
FINISH - automation finished - 7.5s

START - automation started - Sun Nov 29 2020 21:56:23 GMT+0100 (K├Âz├ęp-eur├│pai t├ęli id┼Ĺ )
https://medium.com/tebelorg - Tebel.Automation ÔÇô Medium

github_id " - " user_email
api your_website_url/mailer.php?APIKEY=unique_key&SUBJECT=Hi @batman&SENDTO=bruce@wayne.org&SENDFROM=Your Name <your_email@gmail.com>&MESSAGE=Your message line 1.<br><br>Your message line 2.
wait 3 seconds

https://medium.com/tebelorg - Tebel.Automation ÔÇô Medium
FINISH - automation finished - 8.2s

START - automation started - Sun Nov 29 2020 21:56:38 GMT+0100 (K├Âz├ęp-eur├│pai t├ęli id┼Ĺ )
https://medium.com/tebelorg - Tebel.Automation ÔÇô Medium

github_id " - " user_email
api your_website_url/mailer.php?APIKEY=unique_key&SUBJECT=Hi @superman&SENDTO=clarke@kent.org&SENDFROM=Your Name <your_email@gmail.com>&MESSAGE=Your message line 1.<br><br>Your message line 2.
wait 3 seconds

https://medium.com/tebelorg - Tebel.Automation ÔÇô Medium
FINISH - automation finished - 7.8s

Is it caused by computer settings or something changed until sample provided?

I want to make a flow what I run with e.g. tagui test.tag user_data.csv
and later I want to write into a place the variable like in the sample, just with keyboerd or type command

keyboard 'github_id'  ---from variable
or
keyboard "`GITHUB_ID`" --from csv file 

Thanks for your help in advance.

Regards,
Bali

**Comment by kensoh** [comment]
Hi Bali, yes the syntax for using variables for echo step has changed in TagUI v6 -
https://github.com/kelaberetiv/TagUI#change-in-syntax-for-echo-dump-write-steps

The sample above is outdated already, the updated samples are in this folder - 
https://github.com/kelaberetiv/TagUI/tree/master/flows/samples

Yes below is the correct syntax to use, where github_id is a variable defined either in the flow, or the datatable csv, or object repository. You can get TagUI v6 from this link - https://tagui.readthedocs.io/en/latest/setup.html
```
echo `github_id`
keyboard `github_id`
```

Closing this issue for now but please lemme know if you run into any issue or question
