### ISSUE TITLE
How to get a link on an element - use /@href to get href and other attribute values

### ISSUE THREAD

**Issue by Kudzai-dot** [kelaberetiv/TagUI#889]
I have an automation running that downloads a file and l would like to store it in memory. Right now the idea l had was to get the download link from the button or copy the link address from the button and issue a get request. I cant seem to be able to copy the link address or get the href attribute of a button.

Any ideas?

**Comment by kensoh** [comment]
Hi @Kudzai-dot you can use the `/@href` to return the href of a web element -

```
https://github.com/kelaberetiv/TagUI/issues/889
// show step to print directly to screen
show //*[text()="TagUI"]/@href

// read to variable to process further
read //*[text()="TagUI"]/@href to link
echo `link`
```

**Comment by Kudzai-dot** [comment]
Worked perfectly thank you!

**Comment by sgyaswal** [comment]
how to use in RPA python?

**Comment by kensoh** [comment]
Same
```py
print(r.read('//*[text()="TagUI"]/@href'))
link = r.read('//*[text()="TagUI"]/@href')
```
