### ISSUE TITLE
ERROR - No module named openpyxl - package not installed for python command

### ISSUE THREAD

**Issue by PravinAlhat** [kelaberetiv/TagUI#895]
I am getting below errors while executing a flow,
ERROR - No module named openpyxl
ERROR - can't find variable: json

pravin-a:samples pravin.a$ tagui 9_formfill.tag

START - automation started - Mon Dec 21 2020 15:37:55 GMT+0530 (IST)

https://demoqa.com - ToolsQA
click Form
click Practice
py from openpyxl import load_workbook
import json
wb = load_workbook(filename = "/Users/pravin.a/Desktop/tagui/flows/samples/TestData.xlsx")
sheet = wb.active
firstname = sheet.cell(row=2, column=1).value
lastname = sheet.cell(row=2, column=2).value
address = sheet.cell(row=2, column=3).value
subject = sheet.cell(row=2, column=4).value
data = {'1':firstname,'2':lastname,'3':address,'4':subject}
print(json.dumps(data))
ERROR - No module named openpyxl
ERROR - can't find variable: json

**Here is my 9_formfill.tag file**
// launch application
https://demoqa.com

// click forms menu
click Form

// click Pratice form menu
click Practice

// check for element presence
//check present('//input[@id="firstName"]') | FirstName exists | FirstName does not exists

// Get Data From excel sheet
py begin
from openpyxl import load_workbook
import json
wb = load_workbook(filename = "/Users/pravin.a/Desktop/tagui/flows/samples/TestData.xlsx")
sheet = wb.active
firstname = sheet.cell(row=2, column=1).value
lastname = sheet.cell(row=2, column=2).value
address = sheet.cell(row=2, column=3).value
subject = sheet.cell(row=2, column=4).value
data = {'1':firstname,'2':lastname,'3':address,'4':subject}
print(json.dumps(data))
py finish
echo `py_result`
DataValues = json.parse(py_result)

// input data in Form
type FirstName as DataValues[1]
type LastName as DataValues[2]
type Address as DataValues[3]
type Subject as DataValues[4]
click Submit

**Object Repository tagui_local.csv.**

OBJECT,DEFINITION
email,quick_email
password,quick_pass
user_email,mickey_mouse@disney.com
user_password,iloveminnie4eva
show info,Show full information
click link,click `facebook_link`
facebook_link,//*[@id="profile_full"]//a
Form,(//div[@class="category-cards"]//div[@class="card mt-4 top-card"])[2]//*[name()="svg"]
Practice,(//div[@class="element-list collapse show"]//span[text()="Practice Form"])
FirstName,//input[@id="firstName"]
LastName,//input[@id="lastName"]
Subject,//div[contains(@class,"subjects-auto-complete__value-container")]
Address,//textarea[@class="form-control"]
Submit,//button[@id="submit"]

I already have openpyxl module installed on my Mac system as shown below.

pravin-a:samples pravin.a$ pip3 show openpyxl
Name: openpyxl
Version: 3.0.4
Summary: A Python library to read/write Excel 2010 xlsx/xlsm files
Home-page: https://openpyxl.readthedocs.io
Author: See AUTHORS
Author-email: charlie.clark@clark-consulting.eu
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
Requires: et-xmlfile, jdcal
Required-by: rpaframework, robotframework-excellib

Location of tagui
pravin-a:samples pravin.a$ which tagui
/usr/local/bin/tagui

Python version - 3.8.1
pravin-a:samples pravin.a$ which python3
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3

pravin-a:samples pravin.a$ echo $PATH
/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages

**Comment by kensoh** [comment]
Hi Pravin, thanks for raising this! Can you try the following and let me know if it helps?

1. TagUI runs the `python` command to start a background Python session to run Python code. From above, it looks like you have installed the packages on your Python 3 installation. Try installing it on your Python 2 installation with `pip2 install openpyxl`. Alternatively, try changing the file src\tagui this line `python -u ...` to `python3 -u ...`

2. For accessing variables you defined in the object repository, use backticks ``. This will let TagUI know whether you are referring to a variable or a text string to search for in the identifier.
```
type `FirstName` as DataValues[1]
type `LastName` as DataValues[2]
type `Address` as DataValues[3]
type `Subject` as DataValues[4]
click `Submit`
```

**Comment by kensoh** [comment]
Adding on, it looks like you are very familiar with Selenium. Be sure to try out the visual automation methods of TagUI, for eg `type firstname.png` / `click submit.png` where submit.png is an image snapshot of the button to click, and firstname.png is the image snapshot of the firstname textbox. Also, if you are already very familiar with Python, you can also directly use TagUI in Python language, by using the wrapper RPA for Python - https://github.com/tebelorg/RPA-Python

**Comment by PravinAlhat** [comment]
Thank you for the quick reply ken. As you suggested, I changed the file src\tagui this line python -u ... to python3 -u and it worked. Now, I am not getting an error ERROR - No module named openpyxl. 
But unfortunately, I am still getting an error ERROR - can't find variable: json. 

pravin-a:samples pravin.a$ tagui 9_formfill.tag

START - automation started - Tue Dec 22 2020 11:51:31 GMT+0530 (IST)

https://demoqa.com - ToolsQA
click (//div[@class="category-cards"]//div[@class="card mt-4 top-card"])[2]//*[name()="svg"]
click (//div[@class="element-list collapse show"]//span[text()="Practice Form"])
py from openpyxl import load_workbook
import json
wb = load_workbook(filename = "/Users/pravin.a/Desktop/tagui/flows/samples/TestData.xlsx")
sheet = wb.active
firstname = sheet.cell(row=2, column=1).value
lastname = sheet.cell(row=2, column=2).value
address = sheet.cell(row=2, column=3).value
subject = sheet.cell(row=2, column=4).value
data = {'1':firstname,'2':lastname,'3':address,'4':subject}
print(json.dumps(data))
{"1": "abc", "2": "xyz", "3": "USA", "4": "new subject"}
**ERROR - can't find variable: json**

Also, as you recommended I will definitely use TagUI in Python language, by using the wrapper RPA for Python and also the visual automation methods of TagUI. RPA for Python is more of my interest.

**Comment by PravinAlhat** [comment]
In addition to this, I have installed rpa using pip and able to use it with python. Initially, I encountered an error for openssl but could resolve it by following the below steps,

wget https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
brew install openssl.rb

Now, I have openssl 1.0.2t installed in below directory.
/usr/local/Cellar/openssl/1.0.2t

Additionally, I performed the below steps.
echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> /Users/pravin.a/.bash_profile

For compilers to find openssl you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl/include"

I am all set now. Ken, could you please help me with the video tutorials for RPA using python, Or maybe any sample flows also would work. Thanks.

**Comment by kensoh** [comment]
For your question on TagUI, after changing python to python3 as above (because my openpyxl is also installed for Python 3), I can run the following -

```
py begin
from openpyxl import load_workbook
import json
py finish
```

And the log file tagui/src/tagui_py/tagui_py.log looks to be working.
```
[tagui] START  - listening for inputs
  
[tagui] INPUT  - [1] py from openpyxl import load_workbook
import json
[tagui] ACTION - from openpyxl import load_workbook
import json
[tagui] OUTPUT - [1] SUCCESS

[tagui] FINISH - stopped listening
```

**Comment by kensoh** [comment]
Thanks for sharing your findings for RPA for Python! I could use this info for future troubleshooting if users run into problems.

For samples, there are a few links to examples here -
https://github.com/tebelorg/RPA-Python#api-reference

For video, you can check this one, but recording team has a technical glitch, there is a segment screen is frozen - 
https://www.youtube.com/watch?v=F2aQKWx_EAE

I'll close this issue for now, but do let me know if you run into anything!

For issues on RPA for Python, you can post there. But it's a personal side project, I can only look into it when I get a moment. Now still struggling with some family challenges - https://github.com/tebelorg/RPA-Python/issues/144
