### ISSUE TITLE
Something wrong with clipboard() function - use backticks `` to refer to variables

### ISSUE THREAD

**Issue by ryanpoh** [kelaberetiv/TagUI#897]
Just made a simple .tag file:

```
keyboard [ctrl]a
keyboard [ctrl]c
text_contents = clipboard()
read text_contents to cell_1
```

It produces this output error:

```
keyboard [enter]
keyboard [ctrl]a
keyboard [ctrl]c
read text_contents to cell_1
ERROR - cannot find text_contents
```

Did I make a mistake?

**Comment by kensoh** [comment]
Hi Ryan, is it you want to copy some text value into clipboard and then access it via a variable?

Below steps will read into the variable already -

```
keyboard [ctrl]a
keyboard [ctrl]c
text_contents = clipboard()
```

To use the variable, use backticks `` to let TagUI know that you are referring to a variable and not the text text_contents
```
echo `text_contents`
```

**Comment by kensoh** [comment]
For read step, it is to read the value of a UI element and save the value to the variable provided.

If you want to type some copied text from clipboard into a UI element with identifier cell_1, you can do -
```
type cell_1 as `text_contents`
```

Also, you can insert the live step anything in your flow to pause execution and run everything interactively to test -
```
live
```

The live mode can also be invoked from the command prompt with `tagui live`

**Comment by ryanpoh** [comment]
Oh I see, it solved my issue. Noted with thanks Ken, much appreciated.
