### ISSUE TITLE
Run python file from .tag file

### ISSUE THREAD

**Issue by georgescaria** [kelaberetiv/TagUI#902]
Hi, is there an option to run python file from .tag file? Instead of writing the entire python code inside py begin and py finish tag.

**Comment by georgescaria** [comment]
Got the solution from issue #898.

**Comment by kensoh** [comment]
Hi George, yes from below there are a few ways to run Python code from TagUI -
https://github.com/kelaberetiv/TagUI/issues/898#issuecomment-752827600

If most of the work to be done is already in Python, you can also use the RPA for Python package (wrapper for TagUI) -
https://github.com/tebelorg/RPA-Python
