### ISSUE TITLE
Some option or step to not close web browser after running? - use -speed option

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#911]
During recent training with an accounting SI, a question asked is can they leave the browser open after running?

And the current way is using -speed option (which supposedly is being deprecated).

What people want is not making it run faster, but having the option to leave browser open after automation.

This can be implemented on the option level (eg `-keep_browser_open`, or as a step within the flow eg `keep browser open`)

To chew whether this calls for adding something new to the tool. Am always careful to add stuffs. In theory there is no impact. But as time passes, more options and features and steps means users have to choose from a bigger list of stuffs to get to where they are going. This paradox of choice can often slow down progress. Especially when unnecessary.

**Comment by macrocks** [comment]
@kensoh  Not sure -s option is being deprecated but this option works perfectly and has helped me a lot in my automation as wel a few manual steps which are dynamic in nature.
I guess instead of adding more options for the same step doesn't make any sense until n unless it will not add any value.

**Comment by kensoh** [comment]
Hi Amit, thanks for your feedback! If I ask you, we made TagUI default behaviour is always with speed option on, ie no restarting of browser for each row in datatable, and no added 3 seconds delay between each iteration. Is that good for you?

I'm considering for some users, they are running long processes taking 10 hours or more. If Chrome doesn't restart at all for so long, performance and automation problems might appear. So maybe add a new option to restart if this use scenario is common.

**Comment by kensoh** [comment]
Closing issue, since not closing browser is not a primary use case, users who want to keep browser open can use the -speed option. In future, if this becomes a major use scenario then we think of improving with another option with meaningful name.

**Comment by kensoh** [comment]
Hi @macrocks adding a new update at https://github.com/kelaberetiv/TagUI/issues/1045#issuecomment-854947259

Speed mode will be enabled by default for datatable batch automation, and browser will not restart after each run.
