### ISSUE TITLE
Video of RPA for Everyone webinar - Free RPA by AI Singapore 

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#912]
**Webinar Video**
https://www.youtube.com/watch?v=VOYg9dfZn-w

**Webinar Title**
RPA for Everyone using AISG TagUI

**Date / Time**
Thursday Jan 28, 7pm-8pm SGT (UTC+8)

RPA (robotic process automation) is now gaining traction in helping organisations increase productivity and reduce costs. RPA helps to automate repetitive digital processes by instructing the computer to do what is done manually by a human worker. Examples include claims processing, HR onboarding, sales lead generation, collecting and moving data across different applications.

In this webinar, we will introduce an open-source and free RPA software by AI Singapore called TagUI. You can use 21 different human languages to instruct the computer how to perform your digital processes. Our guiding vision is 'RPA for Everyone' and in the webinar you'll see how easy it is to do RPA, why there are over 30k downloads since v5, and why it is used in over 80 countries - https://share.streamlit.io/kensoh/tagui_distribution

The webinar is also a great opportunity to know about various AI Singapore's offerings and how they might be useful for you and your organisation. AI Singapore is our national AI programme funded by the National Research Foundation, and our mission is to accelerate AI in Singapore - https://www.aisingapore.org

**Outline**
- What is AISG TagUI
- Where and how is it used
- Roadmap for the RPA Brick
- DataCamp Lucky Draw
- Q&A and next steps

**Presenter**
Ken Soh - Product Engineer at AI Singapore, focusing on RPA and TagUI

**Comment by lookang** [comment]
Dear ken,
How to sign up?
Thanks

**Comment by kensoh** [comment]
Hi Loo Kang, thanks for messaging me your interest! After my team-mate creates the event page, I'll post again on the webinar details. I think she'll probably have a sign-up page. But nowadays with online mode of delivery, there is no space limit like a physical event, so maybe sign-up is not required. Will check more with her :)

**Comment by kensoh** [comment]
Hi Loo Kang, the registration page is up - https://bit.ly/rpaforeveryone

I also would like to include the intro that I shared on my [LinkedIn post](https://www.linkedin.com/posts/kensoh_rpa-tagui-activity-6755787724000632832-_mAy) on this webinar.

---

With TagUI, you can create your automation robot in 21 human languages.

Automating websites, desktop apps, computer vision and OCR come out-of-the-box. Works on Windows, macOS, Linux. Use any popular Python package in your robot by writing Python code directly in your automation flow.

When you use TagUI RPA, it comes with 24h soft SLA where we aim to reply user issues within 24 hours, including weekends. There will also be weekly live Q&As on YouTube / Google Meet starting next month to answer any usage questions.

Over the next few months, we'll be adding integrations to Excel, Emails and Telegram, so that you can do more with less. Imagine sending a Telegram notification on your RPA with just the line 'telegram id message'.

Later this year, we'll be introducing an AI Recorder, to automatically generate your robot script in MS Word, for you to fine-tune before deploying. Define data tables and object repositories in Excel. And automatically get your robot statistics as a Powerpoint slide deck.

We call this Office RPA - we are bringing our vision of RPA for Everyone to reality. By making RPA super accessible, yet super powerful. Free of charge, of course.

![RPA for Everyone Webinar](https://user-images.githubusercontent.com/10379601/104834087-3462c300-58d8-11eb-851a-daae9b32f072.png)

**Comment by gpdeepblue** [comment]
Look who is back! Hurray~

**Comment by kordop** [comment]
Hello. Is it still possible to get access? 
Whether the limit has been reached?

**Comment by kensoh** [comment]
Yes, the limit has been hit (Zoom meeting 300 PAX), we are setting up run #2 directly after run #1.

I'll post the registration page for session #2 here when it's up. Thanks @kordop for your interest!

**Comment by kensoh** [comment]
Update - my team-mate says she'll send an invitation for people on waitlist to register for the 2nd run at 9pm SGT 😄

**Comment by MrDaggubati** [comment]
Considering popularity, may be a great idea to have a Youtube channel.

**Comment by kensoh** [comment]
Thanks @MrDaggubati for suggesting!

I've started uploading some videos - https://www.youtube.com/c/kensoh

**Comment by kensoh** [comment]
Video for the first run for folks who missed attending the webinar - https://www.youtube.com/watch?v=57rmXyNreYY

**Comment by kensoh** [comment]
Video for the second run for folks who missed attending the webinar - https://www.youtube.com/watch?v=VOYg9dfZn-w

**Comment by kensoh** [comment]
The 2 runs have completed, closing issue

**Comment by kensoh** [comment]
Adding on, the winners for the DataCamp Premium annual passes (worth $400 USD each) are -

- Webinar Run 1 - Terry C. from Singapore
- Webinar Run 2 - Radoslaw K. from Poland
- TagUI Poll - Joginder R. from India
