### ISSUE TITLE
Weekly Zoom Q&A - free 1-to-1 call for any questions or blockers

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#914]
Please note that we will no longer be providing weekly 1-to-1 Q&A calls, for any questions or blockers feel free to reach out to our communities on [Telegram](https://t.me/rpa_chat) and [AISG](https://community.aisingapore.org/groups/tagui-rpa/).

**Comment by kensoh** [comment]
**Live Q&A #0 - 20 Jan 2021 - https://youtu.be/dlzm403c1co**

A spontaneous run of the weekly live Q&A for TagUI open-source RPA users, originally scheduled to start in late Feb. 361 Degree Consultancy is a Singapore-based firm providing software solutions to the accounting sector. Their TagUI users have some questions on a client's automation scenario, so we decided to hop onto a call and get this live Q&A thing started -

[ Updating accounting system with POS transactions ]
- modularising the automation into 2-3 workflows
- exporting spreadsheet from POS vendor website
- getting today's date base on vendor file naming
- different ways to open the spreadsheet to read
- possible pitfalls to avoid with robust RPA design
- why do it via Excel instead of API in their setup

[ Other questions on best RPA / TagUI practices ]
- scheduling and when's the best time to run RPA
- dynamically choosing which image files to use
- using RPA with WhatsApp to send messages
- RPA data privacy and security considerations

[ Sharing Roadmap 2021 - RPA for Everyone ]
- TagUI integrations to MS Excel, Emails, Telegram
- Office RPA, doing RPA in MS Word, Excel, PowerPoint
- 24h soft SLA (including weekends) gone live Jan 15
- weekly live Q&A on Zoom + YouTube for TagUI users
- demo of TagUI on cloud (or phone) with Google Colab
- RPA in MS Office, Google Workspace apps, or both?

**Comment by kensoh** [comment]
**Live Q&A # 1 - 29 Jan 2021, 4pm SGT (UTC+8)**

Zoom Meeting URL - https://nus-sg.zoom.us/j/82049782250?pwd=WTRZcmRIWXU2OWJEYmt1UWR1MUVYUT09
YouTube Livestream - URL will be auto-generated by Zoom when the live session starts, then I will update here

**Comment by kensoh** [comment]
**Live Q&A # 2, Thursday 4 Feb 2021, 4pm SGT (UTC+8)**

Zoom Meeting URL - https://nus-sg.zoom.us/j/85847222905?pwd=bm9yb3R2NEZEVnRPZ0ZKdjJ0d1VhZz09
YouTube Livestream - URL will be auto-generated by Zoom when the live session starts, then I will update here

**Comment by kensoh** [comment]
**Live Q&A # 3, Thursday 11 Feb 2021, 5pm SGT (UTC+8)**

Zoom Meeting URL - https://nus-sg.zoom.us/j/85847222905?pwd=bm9yb3R2NEZEVnRPZ0ZKdjJ0d1VhZz09
YouTube Livestream - URL will be auto-generated by Zoom when live session starts, then I will update here

***PS - coming week meeting will be at 5pm to avoid an internal meeting conflict***

**Comment by kensoh** [comment]
**Live Q&A # 4 - Thursday 18 Feb 2021, 430pm SGT (UTC+8)**

Zoom Meeting URL - https://nus-sg.zoom.us/j/85847222905?pwd=bm9yb3R2NEZEVnRPZ0ZKdjJ0d1VhZz09
YouTube Livestream - URL will be auto-generated by Zoom when live session starts, then I will update here

**Comment by kensoh** [comment]
A bit late, sorry, meeting overrun

**Comment by kensoh** [comment]
Give us 5 min

**Comment by kensoh** [comment]
Here we go:

Zoom Meeting URL - https://nus-sg.zoom.us/j/85847222905?pwd=bm9yb3R2NEZEVnRPZ0ZKdjJ0d1VhZz09
YouTube Livestream - https://www.youtube.com/watch?v=WsohX6aElPc

**Comment by kensoh** [comment]
**Thursday 25 Feb 2021, 400pm SGT (UTC+8)**
**Live Q&A # 5 - [Zoom One-to-One Meeting URL](https://nus-sg.zoom.us/j/85847222905?pwd=bm9yb3R2NEZEVnRPZ0ZKdjJ0d1VhZz09)**

The weekly live Q&A will no longer stream to YouTube. Also, during the session, if there are more than 1 participant, we will go to the breakout room to go through questions from the participant 1 at a time. First come first serve.

These changes are to optimise the privacy of participants who join the Q&A, over the 'learning' aspect of the general public on YouTube or other participants on the call. There will be free Udemy-style course soon which serves the learning aspect.

**Comment by kensoh** [comment]
**Thursday 4 Mar 2021, 4pm SGT (UTC+8)**
**Live Q&A # 6 - [Zoom One-to-One Meeting URL](https://nus-sg.zoom.us/j/85847222905?pwd=bm9yb3R2NEZEVnRPZ0ZKdjJ0d1VhZz09)**

**Comment by kensoh** [comment]
**Thursday 11 Mar 2021, 4pm SGT (UTC+8)**
**Live Q&A # 7 - Zoom One-to-One Meeting URL**

**Comment by kensoh** [comment]
From now, updated directly to issue description.

Since no longer have YouTube streaming and posting of Q&A topics for privacy reasons.

**Comment by ruthtxh** [comment]
Closing this issue as per latest update [here](https://github.com/kelaberetiv/TagUI/issues/914#issue-793034811)
