### ISSUE TITLE
How do I print screen a web browser tab to a file? - here are a few ways to do it

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#916]
Hi there !
I have the following scenario
there is a login form and after the credentials are validated a new tab is opened with a web RDP system
how can I get a screen snap of this new tab?
thanks !

**Comment by kensoh** [comment]
Hi Marcelo,

Base on your scenario, I assume that you are doing this from a web browser. Normally for webpages, there is a popup step which can set the context for which tab you are trying to automate on. More details here - https://tagui.readthedocs.io/en/latest/reference.html#popup

But in this case, doing a simple `snap page to screenshot.png` within the popup step might not work because the remote desktop object may not be something that is renderable directly. But you can test it out.

If that doesn't work, you can use the computer vision engine to do it with the following. That will do a full screen shot of your computer. Be sure to first using a `click tab_identifier.png` to activate the new tab if it is not already on the screen.

```
snap page.png to screenshot.png
```

You could also do the screenshot by specifying the boundaries of what to capture, for example below.
```
snap (x1,y1)-(x2,y2) to screenshot.png
```

To get the (x,y) coordinates of your mouse cursor position, move your mouse to the upper left boundary and do the following. Then repeat for the bottom left boundary. You could also use some 3rd-party apps that show your mouse (x,y) coordinates on the screen.

```
echo `mouse_xy()`
```

Note that you can run TagUI in live mode with `tagui live` from the command prompt for easy testing of such commands. Alternatively, you could insert `live` step in your workflow to tell TagUI to pause and enter live mode for all these experimentation.

Lastly, if you don't mind capturing the whole desktop, you could also try the keyboard step to printscreen -
```
keyboard [printscreen]
```

**Comment by kensoh** [comment]
Adding on, for macOS, I can do the print screen with `keyboard [cmd][shift]3`. I'm assuming for Windows the `[win][printscreen]` key combination will automatically save the screen to a file.

**Comment by kensoh** [comment]
Adding on, more on how this solution is found on this YouTube video - https://youtu.be/M4JbL-Mr93Y

**Comment by marcelocecin** [comment]
thanks @kensoh ! the `snap page.png to screenshot.png` works perfectly !

**Comment by marcelocecin** [comment]
hi @kensoh how are you doing ?
I'm trying to get OCR using this command: `save (456,287)-(592,304) to text.txt` but nothing happens
where can I check the log for this ?
thanks !

**Comment by kensoh** [comment]
Hi @marcelocecin, the file should be save to the same folder as your automation flow file.

Hmmm, can you see what is inside the log file tagui\src\tagui.sikuli\tagui.log ?

(copying @ruthtxh for info)

**Comment by marcelocecin** [comment]
[error] script [ tagui ] stopped with error in line 584
[error] java.lang.UnsatisfiedLinkError ( java.lang.UnsatisfiedLinkError: Error looking up function 'TessPDFRendererCreateTextonly': /lib/x86_64-linux-gnu/libtesseract.so.4: undefined symbol: TessPDFRendererCreateTextonly )
[error] --- Traceback --- error source first
line: module ( function ) statement 
354: main (  text_read )     temp_text = region_layer.text()
331: main (  save_intent )     return text_read(raw_intent)
526: main (  parse_intent )     return save_intent(script_line)
[error] --- Traceback --- end --------------
IDE terminated: returned: 1

**Comment by kensoh** [comment]
Hi Marcelo, it looks like you are running on Linux. Because the OpenCV and Tesseract libraries can't be packaged directly, can you look through below guide to install them manually? https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

Let us know how it goes!

**Comment by marcelocecin** [comment]
hello Ken, do you know in which Linux folder do I need to put the `tess4j-4.5.4.jar` file?
https://sikulix-2014.readthedocs.io/en/latest/textandocr.html?highlight=tess4j
thank you

**Comment by kensoh** [comment]
Hi @marcelocecin I don't have the answer to this question specific to the setup on Linux. I've raised an issue on the SikuliX project so that its maintainer can advise - https://github.com/RaiMan/SikuliX1/issues/417 (copying @ruthtxh)

**Comment by marcelocecin** [comment]
I downgraded tesseract to version 3.05.02
the error has now changed:
Failed loading language 'eng'
Tesseract couldn't load any languages!

**Comment by kensoh** [comment]
Hi Marcelo,

From the SikuliX guide above - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

It looks like recommended to have v4 (`It must be a version 4.x`). That might be the likely reason why this error message appears when you are trying to use the OCR capabilities of the packaged SikuliX engine in TagUI.

**Comment by kensoh** [comment]
Adding on, Raimund on his SikuliX issue for this asked me for the architecture of how TagUI uses SikuliX.

I'll send that over and see if he could make recommendations on how TagUI should incorporate newer SikuliX engines.

**Comment by marcelocecin** [comment]
hi Ken
because of [this comment](https://github.com/nguyenq/tess4j/issues/209#issuecomment-771694111), I downgraded
<img width="863" alt="" src="https://user-images.githubusercontent.com/2955762/106632104-25c50e80-655c-11eb-9055-4a7721851f65.png">
I already tried to define in the TAG code in Python the TESSDATA_PREFIX environment variable but even so the error persisted
<img width="580" alt="" src="https://user-images.githubusercontent.com/2955762/106632347-691f7d00-655c-11eb-84c5-f24d8742fce3.png">
<img width="738" alt="" src="https://user-images.githubusercontent.com/2955762/106632356-6b81d700-655c-11eb-8624-54b312b78606.png">

I also tried to edit the tagui.py file, including that same definition, however the error persists
<img width="569" alt="" src="https://user-images.githubusercontent.com/2955762/106632068-1f369700-655c-11eb-9a50-481c461decaa.png">

<img width="1286" alt="" src="https://user-images.githubusercontent.com/2955762/106632591-b1d73600-655c-11eb-9a24-9a3e879efa97.png">

**Comment by marcelocecin** [comment]
hey Ken
now is partially working!
I need help in just one detail!
after placing the traineddata files in the / home / user / folder. Sikulix / SikulixTesseract / tessdata / the above error has stopped occurring
now what is happening is something related to special characters
I am OCR the phrase Versão 4.82.01.4:
<img width="117" alt="" src="https://user-images.githubusercontent.com/2955762/106637255-362bb800-6561-11eb-84bf-d32520a8c87b.png">
however the generated file is bringing `ã` as `Ã£` - `VersÃ£o: 4.82.01.4`
<img width="672" alt="" src="https://user-images.githubusercontent.com/2955762/106637756-dc77bd80-6561-11eb-9ee3-b2c7560c7967.png">
<img width="300" alt="" src="https://user-images.githubusercontent.com/2955762/106637590-a89c9800-6561-11eb-8da2-4dd8313e71f3.png">

**Comment by kensoh** [comment]
Hi Marcelo, I've seen something like that before, it seems something to do with the OCR engine. See this issue - https://github.com/kelaberetiv/TagUI/issues/905

We might have to raise this to Raimund at his SikuliX's page to see if he has similar feedback from other users.

**Comment by kensoh** [comment]
I don't have a solution yet for this OCR issue, but would also like to figure out a solution tgt with Raimund.

**Comment by marcelocecin** [comment]
hello Ken
just some instructions to install tesseract-3.05.02 on Ubuntu 18.04.5
```
wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/3.05.02.tar.gz
tar xzf tesseract-ocr-3.02.02.tar.gz
cd tesseract-3.01
./autogen.sh
./configure
make
sudo make install
sudo ldconfig
```
