### ISSUE TITLE
echo mouse co-ordinates hangs - works after installing OpenJDK in setup steps

### ISSUE THREAD

**Issue by AntoryuLimyh** [kelaberetiv/TagUI#920]
Hi I am new here and totally impress by the wonderful presentation yesterday. Thanks

I have successfully  launch the Tagui Live on chrome browser over command prompt. 

However when I key in the command - echo `mouse_xy()` with the intent to get the co-ordinates. It seems to hang over there.

Appreciate any advice on it. ( I am a Window User)

Thanks

**Comment by ruthtxh** [comment]
Hello @AntoryuLimyh 

Good to see you at yesterday's webinar!

You may try the following:
- Check that backticks are wrapped around the syntax `mouse_xy()`
- Ensure live mode is successfully started up before using, by typing only after the "LIVE MODE - type done to quit" line appears

Please see attached snapshot for a sample in Windows cmd. If error persists can you also attach a snapshot so we can investigate further? :)

![image](https://user-images.githubusercontent.com/40910744/106219961-71eb1880-6215-11eb-81be-f3a1d980bb60.png)

**Comment by AntoryuLimyh** [comment]
Hi Ruth,

Thanks for the prompt response.

I have tried that but no luck in getting it to work.

Thanks
Andrew Lim

**Comment by ruthtxh** [comment]
Hello @AntoryuLimyh

I see. Perhaps you can try the following:

Please check that you have installed OpenJDK for Windows - see step 3 in installation steps [here](https://tagui.readthedocs.io/en/latest/setup.html). FYI, the `mouse_xy()` function relies on TagUI's built-in integration with SikuliX (base on OpenCV) which is dependent on OpenJDK.

You may also attach a copy of the log file right after you exit the run, for us to investigate further. The log file can be found here: C:\tagui\src\tagui.sikuli\tagui.log , which keeps track of the latest run.

Hope this helps!

**Comment by AntoryuLimyh** [comment]
Hi Ruth,

Thanks. It works right after I installed the OpenJDK.

Appreciate your help.

Thanks

Regards,
Andrew Lim

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kensoh** [comment]
Nice work Ruth!

Hi Andrew, adding on, this is a video of how we arrived at the solution - https://youtu.be/rgDUu0D3Ws4?t=3392

**Comment by AntoryuLimyh** [comment]
Hi Ruth and Ken,

Thanks for the wonderful product and support.

Really appreciate it,

Have a great week ahead.

Regards,
Andrew Lim

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
