### ISSUE TITLE
Playwright browser - for now, re-engineering has negative user benefits vs risks

### ISSUE THREAD

**Issue by mark05e** [kelaberetiv/TagUI#923]
Microsoft's [Playwright](https://github.com/microsoft/playwright) (fork of Google's [Puppeteer](https://github.com/puppeteer/puppeteer)) seems to support 3 different browsers and have larger team behind them.

I was wondering if you could consider this in a future roadmap.

**Comment by kensoh** [comment]
Hi Mark, thanks for raising this suggestion!

When TagUI was created in 2016, PhantomJS offers a reliable and easy-to-use platform for TagUI users to unzip and run directly. It also is a stable release which works so far all these year, without performance or feature limiting issues, by providing a stable JavaScript engine to run all of TagUI's backend. In fact, we have users running TagUI for automation lasting more than 10 hours without any hiccups.

If there is a switch to PlayWright, and by requirement NodeJS, that means the whole architecture would have to be redesigned, as a major overhaul. I've checked and found that it's possible to run NodeJS without installation, so the major downside is the opportunity cost of investing to an overhaul when it is not yet needed.

For example, being a lean team, the time could be used to implement new features like running RPA directly with Microsoft Word and Google Docs. Also, an overhaul like that, in the best case scenario, does nothing to improve features or usability for existing users who are primarily automating Chrome, but it adds a lot of risks of something failing when it is able to work now using the current architecture.

But we do understand that it allows native automation of other browsers other than Chrome (TagUI now can only automate Firefox and Safari using visual automation method and keyboard shortcuts and OCR). Also, when the time comes that PhantomJS engine is not able to work for primary TagUI user needs (assuming primarily to automate Chrome and desktop apps), then we'll revisit an alternative engine, which could also be Python and the Python version of Playwright.

**Comment by kensoh** [comment]
More context of our thoughts at this video - https://youtu.be/fLwOqK1y0uA?t=155

**Comment by mark05e** [comment]
Thank you for your explanation. Will close this issue.

**Comment by kensoh** [comment]
Adding on, TagUI has an in-built integration with Python. That means you can run Playwright code directly within TagUI, by using the Playwright Python package. Though I think you are looking more for `click abc` directly running using Playwright.

https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

**Comment by mark05e** [comment]
Yep. I was looking for that abstraction layer! 😁
