### ISSUE TITLE
[RPA][ERROR] - use init() before using url()

### ISSUE THREAD

**Issue by elizaMathaai** [kelaberetiv/TagUI#927]
Hi Team,

I have installed rpa for python. However, the script is unable to even start with this error. I have tried uninstalling Visual C++ 2010 manually and installing it again. Still, it gives this error.

[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - now installing missing Visual C++ Redistributable dependency
[RPA][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
[RPA][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
[RPA][INFO] - after that, TagUI ready for use in your Python environment
[RPA][ERROR] - following happens when starting TagUI...

Unable to load script C:\TagAutomation\rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using close()

As advised in other issues, I have made sure that the path to the script doesn't contain any spaces. Kindly help.

**Comment by ruthtxh** [comment]
Good day @elizaMathaai!

RPA for Python is @kensoh's personal side project, please raise a separate issue over at https://github.com/tebelorg/RPA-Python/issues and he will look into it as soon as he has some spare time!

Meanwhile you may want to try out this project, TagUI (RPA without the Python wrapper). If you bump into any issues while using TagUI, our team at AI Singapore will be here to assist you on this page.

**Comment by kensoh** [comment]
Adding on, you can try installing TagUI using these steps here - https://tagui.readthedocs.io/en/latest/setup.html

From the error message, it suggests that for some reason TagUI could not generate an intermediate .js file for automation.

That could be due to PHP issue, file permissions, anti-virus issue. Running TagUI directly could give you more clues.

Here's a video for more context and details - https://www.youtube.com/watch?v=YoP9B13OkHg

We'll close the issue for now over here. Thanks!

**Comment by elizaMathaai** [comment]
> Good day @elizaMathaai!
> 
> RPA for Python is @kensoh's personal side project, please raise a separate issue over at https://github.com/tebelorg/RPA-Python/issues and he will look into it as soon as he has some spare time!
> 
> Meanwhile you may want to try out this project, TagUI (RPA without the Python wrapper). If you bump into any issues while using TagUI, our team at AI Singapore will be here to assist you on this page.

Hi Tea, Does the TAGUI have internal integration with Sikuli for webautomation using images. Or should that be installed separately ?

**Comment by elizaMathaai** [comment]
> > Good day @elizaMathaai!
> > RPA for Python is @kensoh's personal side project, please raise a separate issue over at https://github.com/tebelorg/RPA-Python/issues and he will look into it as soon as he has some spare time!
> > Meanwhile you may want to try out this project, TagUI (RPA without the Python wrapper). If you bump into any issues while using TagUI, our team at AI Singapore will be here to assist you on this page.
> 
> Hi Tea, Does the TAGUI have internal integration with Sikuli for webautomation using images. Or should that be installed separately ?

I am facing this issue when I tried to run TAGUI alone.
<img width="603" alt="error1" src="https://user-images.githubusercontent.com/51569138/106832114-0b11a780-66cc-11eb-99db-3334e8853c4b.PNG">
<img width="308" alt="error" src="https://user-images.githubusercontent.com/51569138/106832117-0cdb6b00-66cc-11eb-848d-fa953ba2c5a4.PNG">

<img width="308" alt="error" src="https://user-images.githubusercontent.com/51569138/106832121-0fd65b80-66cc-11eb-9196-3ed8a5635942.PNG">

Kindly help

**Comment by kensoh** [comment]
Hi Eliza, TagUI comes packaged with SikuliX engine already so there is no need to install it separately. Oh for this issue, from the installation page there is a link on 'having problems?' - clicking that link will let you download the MSVCR110.dll file.

This is a file needed for the packaged PHP engine to work and do all the translation from TagUI language to JavaScript code to run RPA workflows.

![Screenshot 2021-02-04 at 9 38 39 AM](https://user-images.githubusercontent.com/10379601/106832595-ebc74a00-66cc-11eb-8120-65be9e88f105.png)

**Comment by elizaMathaai** [comment]
> Hi Eliza, TagUI comes packaged with SikuliX engine already so there is no need to install it separately. Oh for this issue, from the installation page there is a link on 'having problems?' - clicking that link will let you download the MSVCR110.dll file.
> 
> This is a file needed for the packaged PHP engine to work and do all the translation from TagUI language to JavaScript code to run RPA workflows.
> 
> ![Screenshot 2021-02-04 at 9 38 39 AM](https://user-images.githubusercontent.com/10379601/106832595-ebc74a00-66cc-11eb-8120-65be9e88f105.png)

Thank you Kensoh!. I was able to resolve the issue when I installed the C++ redistributable separately like you advised when running with tagui alone. 

And the old error with RPA (python) is also no more. Now, there is problem with it finding chrome.exe path. Which I updated in the tagui (chrome_command) file. However, everytime the script runs, it goes to download the TAGUI (~200mb) and then overwrites the tagui.cmd file. Is there a way to prevent this ?

**Comment by elizaMathaai** [comment]
Hi Kensoh, 
I was able to resolve the issue with both TAGUI and RPA when I installed the  C++ redistributable separately as advised. Can I know where is it written to check if this is installed ? 

P.S (I am writing a python script which is meant to run in client machines as part of an automation project which may not have admin access. So, I would like to know if Microsoft C++ installation is a pre-requisite?. If yes, what version is required?. It would be of great help if you could share this info.

**Comment by kensoh** [comment]
Hi Eliza, oh from above link of installation page --> click Having problems

>Hi Eliza, TagUI comes packaged with SikuliX engine already so there is no need to install it separately. Oh for this issue, from the installation page there is a link on 'having problems?' - clicking that link will let you download the MSVCR110.dll file.

**Comment by kensoh** [comment]
Yes the Microsoft MSVCR110.dll library is a pre-requisite. It is required for the packaged PHP that comes with TagUI for Windows. TagUI uses PHP to do the translation from TagUI language into the JavaScript code that runs the RPA, using PhantomJS JavaScript engine, also comes packaged with the TagUI zip file.

**Comment by elizaMathaai** [comment]
Hi Kensoh, Can I pre-install it in the client machines ?. If it is already installed, does the first run of RPA download it again and install (which requires admin privileges) ?

**Comment by kensoh** [comment]
Yes, you can pre-install.

If you have pre-install by running setup() or init() and get all dependencies installed, then no need to download again.

**Comment by elizaMathaai** [comment]
Hi Kensoh,

Can the rpa (for python) run without JDK installation ? Or is that also a pre-requisite ?
I understand that for the installation of TAGUI alone, it is required as per installation. Does the same apply for RPA wrapper for python ?

**Comment by kensoh** [comment]
Oh, OpenJDK is required for visual automation, whether it is for TagUI or RPA for Python.

This because the computer vision and OCR engine runs on Java (OpenJDK).
