### ISSUE TITLE
Possible to click on some text on the screen using OCR? - yes, see examples here

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#933]
hello
is it possible to execute the click command with ocr?
an example is from the [ui.vision](https://ui.vision/rpa/docs/xclick#vision) tool
<img width="945" alt="" src="https://user-images.githubusercontent.com/2955762/107241516-cfe3e100-6a09-11eb-8983-1b782f573a56.png">
thanks

**Comment by kensoh** [comment]
Hi @marcelocecin, yes this can be done in TagUI, without the file or OCR or actions limit in UI.Vision free version.

Here's the example on the TagUI GitHub page - https://github.com/kelaberetiv/TagUI#click-text-using-ocr

And here's a video with a couple of demos of using this feature - https://www.youtube.com/watch?v=hQ1TZv7BjAk

**Comment by marcelocecin** [comment]
perfect
thanks !
