### ISSUE TITLE
cannot find png on screen cronjob crontab

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#934]
Hello
The script works normally when executed manually
however when configured to open automatically through crontab the error occurs
`30 5 * * 2-6 /usr/local/bin/tagui /home/rpa/tagui/flows/script.tag -q >> /home/rpa/tagui/cron.log 2>&1`
<img width="804" alt="" src="https://user-images.githubusercontent.com/2955762/107353536-ea6e9680-6aab-11eb-91ce-340bc11cb4ed.png">

**Comment by marcelocecin** [comment]
I managed to solve by inserting in front of the command `env DISPLAY=:0`
`30 5 * * 2-6 env DISPLAY=:0 /usr/local/bin/tagui /home/rpa/tagui/flows/script.tag -q >> /home/rpa/tagui/cron.log 2>&1`

**Comment by kensoh** [comment]
Thanks Marcelo for raising this and sharing your solution!

Here's a video with more context for other users with this issue - https://www.youtube.com/watch?v=4zdpTtsloTI
