### ISSUE TITLE
Some ideas for better Chinese support - some suggestions on Chinese support

### ISSUE THREAD

**Issue by chenshuichao** [kelaberetiv/TagUI#935]
As we know, there are 13 billons people saying chinese,there are so many web sites and desktop apps in chinese.
So if we can support chinese better ,we can make the tagui more popular .
1)make the chinese support out of box (just the download zip, and unzip, no more config)
2)make ocr support  chinese better
3)add more chinese website and desktop app sample by tagui rpa

**Comment by kensoh** [comment]
Hi Shui Chao, thanks for raising this issue!

I've recorded a video with more context and examples of what you raised above -
https://www.youtube.com/watch?v=fHNAu9vd0Is

1. The config setting is only change 1 line in tagui_config.txt. If that is too much trouble, the user won't be using this tool anyway. Even though this tool can do RPA in the fastest shortest way, you will still need to map out your processes mentally into instructions to do. If there are 20 steps in a process, will need 20 lines of instructions. So if changing 1 line is too difficult for a user, then that user is not the target user for this app, for now... In future when we have more resources, we can look into this again. Until recently, the project is a 1-man show, so making multiple packaged zip per release for all 3 OSes just with 1 line of config difference, is too much work compared to using the time to create new features.

2. I have not use the Chinese OCR before, can you tell me how you are using it and share some examples of the accuracy? I think there is a way to upgrade the Tesseract trained models to use newer language files. But I have not tried that myself.

3. Can you do some sample automation workflows and share here? My laptop is not in Chinese, so all apps are in English. And I'm not familiar with Chinese websites to create examples. Also, in the video, I shared more on how you can translate existing examples in English, into Chinese with just 1 line.

**Inside tagui/src folder you can use the translate.php to do this**
```
php translate.php filename.tag to chinese
```

**You can also translate something written in Chinese to English**
```
php translate.php filename.tag from chinese
```

Above also works for other languages.

A translated workflow will be created when you run above in command prompt/terminal.

For GitHub homepage and documentation, I think can use Google Chrome browser to translate and view in Chinese.

CC @ruthtxh for info

**Comment by chenshuichao** [comment]
Thank you!
I am in china.I like tagui very much, perfect for design idea.
When I run tagui in my windows desktop in chinese ,I can not ocr the chinese word in screen well.
Click as ocr,when the screen or application is chinese,for example ,these app:
http://guangxi.chinatax.gov.cn/nsfw/xzzx/201808/P020201231310677674028.zip

**Comment by chenshuichao** [comment]
tagui_language = 'chinese',is well

**Comment by kensoh** [comment]
Thanks Shui Chao, can you tell me what is the zip file? When I download I see below .exe file on my Mac computer.

![file_download](https://user-images.githubusercontent.com/10379601/107619283-e4d0a680-6c8d-11eb-9c40-e04b08f84fd8.png)

**Comment by chenshuichao** [comment]
@kensoh ,so this is my question when I run tagui on my chinese desktop.the zip from this website .
http://guangxi.chinatax.gov.cn/nsfw/xzzx/201808/t20180802_273222.html
we can make this sample:
1)visit this website (http://guangxi.chinatax.gov.cn/nsfw/xzzx/201808/t20180802_273222.html)
2)download zip
3)install application
4)start application click some button and input something

**Comment by chenshuichao** [comment]
write the flow Script for above 4 steps with tagui.

**Comment by kensoh** [comment]
I see.. The easiest way to do your above steps is to automate visually --> do screenshot of the UI element to click. Then tell TagUI to click on them. For example below. See below for a few examples how to automate visually. For Windows, you can use Microsoft snipping tool to capture screenshot. For Mac you can do [cmd][shift]4 to capture a snapshot.

```
http://guangxi.chinatax.gov.cn/nsfw/xzzx/201808/t20180802_273222.html
click download_button.png
click ...
click ...
type some_text_box.png as some value
```

https://youtu.be/49zGvO1aNGM?t=2948
Example automating Microsoft Excel - https://github.com/kelaberetiv/TagUI/issues/904
https://github.com/aimakerspace/TagUI-Bricks/tree/master/MS-Word-Letter
https://github.com/aimakerspace/TagUI-Bricks/tree/master/Xero-Accounting

**Comment by chenshuichao** [comment]
👌，yeah，this is ok！
thank you！
