### ISSUE TITLE
Is it possible to visit the URL provided from a variable? - yes here's a few examples

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#936]
hi there !
is it possible to visit the URL provided from a variable? 
example:
```python
read //a[contains(text(),'Some text')]/@href to url
visit `url`
```

**Comment by ruthtxh** [comment]
Hello @marcelocecin 

Currently, visit is not part of the TagUI syntax so you cannot use it directly.

Here's a quick workaround you can look into, which is to pass the href link_text variable to a DOM step through a dom_json variable, and use window.location to go to the URL.

Here's an example of how it works:
```
https://github.com/kelaberetiv/TagUI/issues/936
read //a[text()="Security"]/@href to link_text
dom_json = {url: link_text}

dom begin
window.location= dom_json.url;
dom finish
```

**Comment by marcelocecin** [comment]
perfect !
thanks @ruthtxh !

**Comment by kensoh** [comment]
Adding on, below are 2 more examples how you can do it in 1 line.

TagUI detects whether a step is going to a webpage by checking if the step starts with `https://` or `http://`

Below works by using the `https://` keyword and then truncating away the `https://` prefix in url variable.

```
url = 'https://google.com'
https://`url.split('//')[1]`

url = 'https://yahoo.com'
https://`url.replace('https://','').replace('http://','')
```

**Comment by kensoh** [comment]
Adding on a video link with below demo - https://www.youtube.com/watch?v=qbXFouBC3Cg
```
url = 'https://google.com'
https://`url.split('//')[1]`
snap page
```

**Comment by marcelocecin** [comment]
perfect !
thanks @kensoh !

**Comment by marcelocecin** [comment]
hello @kensoh 
is it possible to use this solution using a variable declared within a csv database?
thanks

**Comment by kensoh** [comment]
Hi Marcelo! Possible, you can specify the datatable using `tagui flow.tag datatable.csv`.

Above error and file naming is probably you are referring to the old documentation.

For current doc - https://tagui.readthedocs.io/en/latest/advanced.html#datatables

**Comment by marcelocecin** [comment]
hello Ken, I opened issue #953
