### ISSUE TITLE
Use keyboard function keys F1 to F2 with keyboard step - some examples

### ISSUE THREAD

**Issue by 1RedTea** [kelaberetiv/TagUI#940]
Hello Ken/Ruth,

Is there a way to replicate function keyboard commands in TagUI?

Context: I would like to use function key to do a process in SAP instead of mouse coordinates.

Keyboard Commands example:
[F1, F2, F3, F4].

Tried the following command line but does not work to expectation:
1. keyboard F1
2. keyboard Key.F1
3. keyboard [F1]
4. keyboard [Key.F1]

Thanks in advance.

Regards
Hidayat

**Comment by kensoh** [comment]
Hi Hidayat, try below, I'll fill in with details later - 

keyboard [f1]

**Comment by 1RedTea** [comment]
Thanks Ken, it works!

**Comment by kensoh** [comment]
Welcome Hidayat!

`keyboard [F1]` uppercase F1 should also work - a common cause could be the focus is still on the command prompt or terminal window in live mode, and the keystroke press gets actioned onto the prompt instead of the desktop app.

Adding on a video with some demos of using F1 in live mode - https://www.youtube.com/watch?v=9YUF9gpKvQ0

**Comment by 1RedTea** [comment]
Thanks for the video Ken, relating to keyboard commands in TagUi, how to write the syntax to activate, Windows logo key + D?

Tried a few variations and error message is "ERROR - cannot understand step  "

**Comment by kensoh** [comment]
Hi Hidayat, (at my phone, from memory) I think it's

keyboard [win]d

**Comment by 1RedTea** [comment]
thank you Ken! 
keyboard [win]d works as expected!  👍 💯 

my failed attempt was with command words,  [window]d / [windowslogo]d / [windows]d

**Comment by kensoh** [comment]
Welcome Hidayat! My earlier reply for this issue I miss out including the reference link of the list of 'keywords' for keyboard step 😅 - 

https://tagui.readthedocs.io/en/latest/reference.html#keyboard
