### ISSUE TITLE
Saving images from Google search - see this example and simple identifier to use

### ISSUE THREAD

**Issue by TetraGenius** [kelaberetiv/TagUI#945]
In 2020 there was an example to save images that I cannot find? So...

I've tried this to scrape images from google search: (also tried using "src" in place of "imgurl" in the following code)
Any advice?

CODE:
// This flow makes a search on Google, clicks tries to SAVE images and screenshots the page
// First, visit google.com
https://www.google.co.za/search?q=svg%20images%20innovation&tbm=isch&hl=en&tbs=il:cl&sa=X&ved=0CAAQ1vwEahcKEwjwpKGk24TvAhUAAAAAHQAAAAAQAg&biw=1905&bih=913

// Wait 3 seconds so the page can load
wait 1
snap (//*[contains(@imgurl=".svg") or contains(@imgurl=".png") or contains(@imgurl=".jpg")])[1] to image1.png

snap (//*[contains(@imgurl=".svg") or contains(@imgurl=".png") or contains(@imgurl=".jpg")])[2] to image2.png

snap (//*[contains(@imgurl=".svg") or contains(@imgurl=".png") or contains(@imgurl=".jpg")])[3] to image3.png

// Save a screenshot of the web page to top_result.png
snap page to top_result.png

THE OUTPUT IS:

tagui TagUI_Linux/tagui/flows/samples/3_google.tag

START - automation started - Thu Feb 25 2021 12:59:57 GMT+0200 (SAST)

https://www.google.co.za/search?q=svg%20images%20innovation&tbm=isch&hl=en&tbs=il:cl&sa=X&ved=0CAAQ1vwEahcKEwjwpKGk24TvAhUAAAAAHQAAAAAQAg&biw=1905&bih=913 - svg images innovation - Google Search
wait 1
snap (//*[contains(@imgurl=".svg") or contains(@imgurl=".png") or contains(@imgurl=".jpg")])[1] to image1.png
ERROR - cannot find (//*[contains(@imgurl=".svg") or contains(@imgurl=".png") or contains(@imgurl=".jpg")])[1]

**Comment by TetraGenius** [comment]
Also tried:
snap (//*[@class="g"])[1]//a to image1.png
with same ERROR

**Comment by kensoh** [comment]
Hi @TetraGenius, when I try below link and check using web browser inspector, there isn't a match for the identifier that you are looking for `(//*[contains(@imgurl=".svg") or contains(@imgurl=".png") or contains(@imgurl=".jpg")])[1]`

https://www.google.co.za/search?q=svg%20images%20innovation&tbm=isch&hl=en&tbs=il:cl&sa=X&ved=0CAAQ1vwEahcKEwjwpKGk24TvAhUAAAAAHQAAAAAQAg&biw=1905&bih=913

**Comment by kensoh** [comment]
Using //img directly seem to be a match and works. Below example uses count() function to check total and auto-loop.

```
https://www.google.co.za/search?q=svg%20images%20innovation&tbm=isch&hl=en&tbs=il:cl&sa=X&ved=0CAAQ1vwEahcKEwjwpKGk24TvAhUAAAAAHQAAAAAQAg&biw=1905&bih=913
total_images = count('//img')
for n from 1 to total_images
    snap (//img)[`n`] to image`n`.png
```

You may want to also add a wait after each snap to make sure data is fully downloaded.

**Comment by kensoh** [comment]
Closing issue for now, but do ping here if any issue!
