### ISSUE TITLE
Run TagUI on Microsoft Edge web browser (beta), added new run option - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#946]
Boss's friend wants to use MS Edge.

**Comment by kensoh** [comment]
If anyone really wants to use TagUI on the new MS Edge (Chromium-based), you can try downloading below file, rename to tagui.cmd, and replace your tagui\src\tagui.cmd file. Note that it is a 5-min hack from me without exhaustive testing. So results may not be exactly the same as running the automation on Chrome browser which is tested to work OK.

[tagui.txt](https://github.com/kelaberetiv/TagUI/files/6046536/tagui.txt) - 5-min hack to work on Microsoft Edge instead of Chrome

**Comment by kensoh** [comment]
Closing issue for now, but if users have any issues on the Microsoft Edge ping here!

**Comment by kensoh** [comment]
Review if need to make it as an option

**Comment by TheBoojah** [comment]
Got it working with the "hack"! Thanks!

At my company only edge (chromium) is allowed, so regular chrome is no go.
If it is this easy, adding it as an option or fallback if chrome.exe does not exist would be great.

**Comment by kensoh** [comment]
Thanks for your feedback @TheBoojah! I'll explore making Edge as an option, since now IE is being phased out and apps and organisations that are using IE will be moving to Microsoft Edge browser.

**Comment by kensoh** [comment]
Added for macOS. Linux and Windows next.

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. You can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html), or manually unzip [this zip file](https://github.com/kelaberetiv/TagUI/archive/refs/heads/master.zip) to overwrite your existing installation (drag all the folders and files under TagUI-master\src to your existing tagui\src folder).

**Comment by kensoh** [comment]
Added for macOS and Linux. Usable with `-edge` or `-e` option. Windows next.

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. You can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html), or manually unzip [this zip file](https://github.com/kelaberetiv/TagUI/archive/refs/heads/master.zip) to overwrite your existing installation (drag all the folders and files under TagUI-master\src to your existing tagui\src folder).

**Comment by kensoh** [comment]
Added for Windows, macOS and Linux. Usable with `-edge` or `-e` option.

If you are using TagUI v6.46 and above, you can get this update with `tagui update` command or MS Word plug-in `Update TagUI` button. You can get TagUI v6.46 from this [installation page](https://tagui.readthedocs.io/en/latest/setup.html), or manually unzip [this zip file](https://github.com/kelaberetiv/TagUI/archive/refs/heads/master.zip) to overwrite your existing installation (drag all the folders and files under TagUI-master\src to your existing tagui\src folder).

**Comment by kensoh** [comment]
**PS 1 -** to use MS Edge in Word plug-in, enter -edge in the parameter option. in the next Word plug-in release, this would be a selectable option on the task pane

**PS 2 -** TagUI is meant for automating processes, not test automation. This feature isn't designed for users to alternate between Edge and Chrome to automate the same websites but more for users with specific restrictions (company don't allow use of Chrome) to have an option to use Edge (exclusively)

**Comment by kensoh** [comment]
**PS 1 -** to use MS Edge in Word plug-in, enter -edge in the parameter option. in the next Word plug-in release, this would be a selectable option on the task pane. CC @ruthtxh 

**PS 2 -** TagUI is meant for automating processes, not test automation. This feature isn't designed for users to alternate between Edge and Chrome to automate the same websites but more for users with specific restrictions (company don't allow use of Chrome) to have an option to use Edge (exclusively)

**Comment by Mavericks334** [comment]
@kensoh  where does the src file reflect when i do it offline. I could not find tagui\src\tagui.cmd it any where

**Comment by kensoh** [comment]
Do you mean for TagUI or for RPA for Python tool?

**Comment by kensoh** [comment]
If you mean for RPA for Python, you can do r.tagui_location() to know where the tagui folder is stored.

**Comment by harishweeroda** [comment]
hi @kensoh i have one doubt is there an active window browser on tagui

**Comment by kensoh** [comment]
Hi @harishweeroda can you share more what you mean?

Usually to activate a Window into foreground need user to replicate what he does manually - for eg clicking using visual automation on the taskbar or some other ways.

**Comment by blueberry-byte** [comment]
Hi! I managed to get TagUI to work on Edge using pure TagUI. May I know how to configure init() in python to run using Edge?

**Comment by kensoh** [comment]
Closing since this change has made its way into the latest packaged release.

**Comment by kensoh** [comment]
Hi @blueberry-byte I just saw your message above. Do you still need the solution? Will require modifying some files of the TagUI engine that came with the Python rpa package. You can raise an issue here if you are still looking for the answer - https://github.com/tebelorg/RPA-Python/issues
