### ISSUE TITLE
Issue while using py_step() - use py_step() outside of your Python code block

### ISSUE THREAD

**Issue by reddy2000** [kelaberetiv/TagUI#947]
When I am executing the following flow am getting an error saying **ERROR - name 'py_step' is not defined**

s1 = "#1 -#2 -#12 -#14 -#15 -#13 -#3"

py begin

py_step('s = ' + s1)

lis = s.split('#')

#print(lis)

list1 = []
list2 = []
list3 = []

for n in lis:
    list1.append(n.split(" ")[0])
#print(list1)

for n in list1:
    try:
        list2.append((int)(n.split(' ')[0]))
    except:
        list3.append(n)
print(list2)
#print(list3)

py finish

echo `py_result`

**Comment by kensoh** [comment]
Hi @reddy2000, the py_step() function should be done outside of the py begin and py finish.

Because it is a function in TagUI. If put inside it means you are trying to run it in Python, which there is no such function.

 Also I assume above your Python code there is no indentation is because of copy and pasting here got formatting issue. Otherwise I think the code will break, after for loop statement need indentation for next line.

**Comment by reddy2000** [comment]
Hi @kensoh I tried using the py_step() outside the python block even then it is showing error **ERROR - name 's' is not defined** at line 4.

s1 = "#1 -#2 -#12 -#14 -#15 -#13 -#3"

py_step('s = ' + s1)

py begin

lis = s.split('#')

#print(lis)

list1 = []
list2 = []
list3 = []

for n in lis:
    list1.append(n.split(" ")[0])
#print(list1)

for n in list1:
    try:
        list2.append((int)(n.split(' ')[0]))
    except:
        list3.append(n)
print(list2)
#print(list3)

py finish

echo `py_result` #

**Comment by kensoh** [comment]
Hi @reddy2000 I think it's because you are trying to define a Python string here. So there needs to be quotation marks to denote a string by doing below -

```
py_step('s =" ' + s1 + '"')
```

When I run below sample -
```
s1 = "#1 -#2 -#12 -#14 -#15 -#13 -#3"
py_step('s = "' + s1 + '"')
py begin
list = s.split('#')
print(list[1])
py finish
echo `py_result`
```

I get this expected result -
```
1 -
```

**Comment by kensoh** [comment]
(I know the syntax for `py_step()` is not straightforward, but it is hard to correctly pass variables from 1 programming language to another programming language consistently, that's why it is this way for now to make ensure exactly what user wants)

**Comment by reddy2000** [comment]
Thank You @kensoh now my flow is working fine.

I am facing issue with the following flow I have divided it into two parts one as **Login** and the other as **Searching in Mail** when I am running these two parts as two separate flows they are working fine.But when I try to run one flow in the other flow its showing error like mentioned below

**ERROR - number of step { does not tally with with }
ERROR - automation aborted due to above**

//Login
```
https://google.com
click Gmail
if url() contains 'accounts.google.com'
	if exist("Vishnu Reddy") and url() contains 'signinchooser'
		click Vishnu Reddy
		if exist("password")
			type password as xyz
		click Next

	else
		if exist ("Email") and url() contains 'accounts.google.com'
			type Email as `user_email`
			click Next
		if exist("password")
			type password as xyz
			click Next

	if url() contains "rm=false" && exist("password") && !exist("Compose")
		type password as `xyz`
```

//Searching in Mail

```
https://mail.google.com/mail/u/0/?tab=rm&ogbl#advanced-search/subject=MoM&subset=all&within=1d&sizeoperator=s_sl&sizeunit=s_smb
click //div[@class="T-I J-J5-Ji Zx aQe T-I-atl L3"]
wait 5

for n from 1 to 3
    click //div[@jsaction="oehdpb:.CLIENT;UXdbee:.CLIENT"]/div[2]/div/table/tbody/tr[`n`]
    read //div[@class="a3s aiL "] to fall
    dump `fall` to fall`n`.txt
    wait 5
    keyboard [alt][left]
    wait 2
```

**Comment by kensoh** [comment]
Hi @reddy2000 the 2 files actually the indentation is different. Can you check?

1 file is tab indentation, 1 file is a few spaces. TagUI automatically detects the indentation to decide code blocks formatting. But if the indentation format is different it will be confused which is the real indentation character to use as reference.

**Comment by kensoh** [comment]
Closing issue for now till further inputs!
