### ISSUE TITLE
Which row of data table is being run - use `[iteration]` to retrieve current row

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#948]
Hello
in the demo `6_datatables.tag` is it possible to find out which step is being run the script?
example:
```echo This is the `current` line of the CSV```
or
```
py begin
import glob
print(glob.glob("/home/rpa/tagui/flows/samples/*.PDF")[`current`])
py finish
echo `py_result`
```
thanks

**Comment by kensoh** [comment]
Hi Marcelo, you can use the following. This was in the old v5.11 docs but not included because maybe too programmatic. We'll watch out if more users ask similar questions we'll add it back to the docs so that users can see that right away.

```
echo This is the `[iteration]` line of the CSV
```

**Comment by marcelocecin** [comment]
thanks @kensoh !

**Comment by kensoh** [comment]
Have fun automating!
