### ISSUE TITLE
Object repository datatable as variables, and datatable count with iteration - done

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#953]
Hello
attachment error is occurring
<img width="508" alt="" src="https://user-images.githubusercontent.com/2955762/109717489-d8e94d80-7b84-11eb-8ac0-299b2ef3a1ec.png">
<img width="450" alt="" src="https://user-images.githubusercontent.com/2955762/109717500-dbe43e00-7b84-11eb-9cfb-58de9c697873.png">
<img width="344" alt="" src="https://user-images.githubusercontent.com/2955762/109717501-dbe43e00-7b84-11eb-8e8c-f9d7c6167fbb.png">

**Comment by kensoh** [comment]
Hi Marcelo! You can specify the datatable using `tagui flow.tag datatable.csv`.

Above error and file naming is probably you are referring to the old documentation.

For current doc - https://tagui.readthedocs.io/en/latest/advanced.html#datatables

Also, to use commas `,` in your CSV, you can enclose the whole thing in double quotes. eg `"11.021,00"`

**Comment by marcelocecin** [comment]
Hi Ken!
thanks for the tip for using the comma inside the CSV
I'm using the command: `tagui 11_ifDB.tag 11_ifDB.csv`

<img width="584" alt="" src="https://user-images.githubusercontent.com/2955762/109815555-89e7fa80-7c0e-11eb-98f2-d8a971f01036.png">
<img width="329" alt="" src="https://user-images.githubusercontent.com/2955762/109815560-8bb1be00-7c0e-11eb-881f-f0003777c529.png">
<img width="598" alt="" src="https://user-images.githubusercontent.com/2955762/109815568-8d7b8180-7c0e-11eb-95ca-d2df4e88443f.png">

**Comment by kensoh** [comment]
Oh I get the problem now, the \`varstring\` works because it will retrieve data from your csv file. But using varstring directly in the condition, TagUI assumes that it is a variable and doesn't read from the csv file the value. Let me chew on this what is the best solution, and if we can make a patch to solve this. CC @ruthtxh (think the issue you ran into previously with csv_row())

**Comment by marcelocecin** [comment]
<img width="592" alt="" src="https://user-images.githubusercontent.com/2955762/109969550-cda43800-7cd2-11eb-9848-2f0b4c2b0e60.png">
<img width="595" alt="" src="https://user-images.githubusercontent.com/2955762/109969560-ced56500-7cd2-11eb-9107-6c7339da8709.png">

**Comment by kensoh** [comment]
Yes, I don't think there's a direct solution now, the parsing for the backticks happens before script runs and only for normal steps, it does not parse for lines that are in JS code, because variables would not have `` in that context. Will think over.

**Comment by kensoh** [comment]
A workaround in the meantime is below, after the 2 steps below, varstring can be used in the if condition -

```
dump `varstring` to variable.txt
load variable.txt to varstring
```

**Comment by kensoh** [comment]
If this works, you can use this workaround for the time being. In the next release, I'll see if there's a good permanent fix.

**Comment by marcelocecin** [comment]
it works !
thanks Ken !

**Comment by kensoh** [comment]
Welcome Marcelo, thanks for raising this to us! Your feedback helps us to improve TagUI.

Reopening issue to investigate on a permanent solution for next release.

Cc @ruthtxh

**Comment by kensoh** [comment]
Above commit works with below examples. If a field has spaces, the spaces will be replaced with underscore for valid variable names. If there is single quote in the field data, it will be escaped automatically to not break JavaScript compilation.

You can download the latest copy of TagUI with this and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files. 

**repository.tag**
```
echo `name`
echo `date of birth`
echo `home_town`

if name equals to 'Andy Garcia'
    echo YES
if date_of_birth equals to '01/01/1991'
    echo YES
if home_town contains 'It'
    echo YES
```
**tagui_local.csv**
```
object, value
name,Andy Garcia
date of birth,01/01/1991
home_town,South\nItaly
```
**datatable.tag**
```
echo `name`
echo `date of birth`
echo `home_town`

if name equals to 'Andy'
    echo YES
if date_of_birth equals to '01/01/1991'
    echo YES
if home_town contains 'It'
    echo YES
```
**data.csv**
```
#,name,date of birth,home_town
1,Andy,01/01/1991,Italy
2,Ryo,02/02/1991,Japan
```

Fyi @ruthtxh

**Comment by kensoh** [comment]
To review if defining all datatable and object repository values is better, instead of defining what is being used in TagUI steps.

**Comment by kensoh** [comment]
Above commit is v2 of this enhancement, it will process all fields regardless of whether a field is used in TagUI steps.

**repository.tag**
```
echo `name`
echo `date of birth`
echo `home_town`

if name equals to 'Andy Garcia'
    echo YES
if date_of_birth equals to '01/01/1991'
    echo YES
if home_town contains 'It'
    echo YES
if favourite_color equals to 'blue'
    echo YES
```

**tagui_local.csv**
```
object,value
initials,AG
name,Andy Garcia
date of birth,01/01/1991
favourite color,blue
home_town,South\nItaly
occupation,wine maker
```

**datatable.tag**
```
echo `name`
echo `date of birth`
echo `home_town`

if name equals to 'Andy Garcia'
    echo YES
if date_of_birth equals to '01/01/1991'
    echo YES
if home_town contains 'It'
    echo YES
if favourite_color equals to 'blue'
    echo YES
```

**data.csv**
```
#,name,date of birth,home_town,favourite color
1,Andy,01/01/1991,Italy,blue
2,Ryo,02/02/1991,Japan,orange
```

**Comment by kensoh** [comment]
Users can download the latest copy of TagUI with this and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files.

**Comment by kensoh** [comment]
Also, as part of the change, following will be the new way to access iteration -

**new way**
```
if iteration equals to 1
    // do login steps
```

**old way**
```
if `[iteration]` equals to 1
    // do login steps
```

**Comment by kensoh** [comment]
Above commit adds v3 of this feature, to make it robust for edges. Otherwise it is possible for some header names to break the execution due to invalid JavaScript variable naming convention.

Users can download the latest copy of TagUI with this and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this will become part of the packaged zip files.

**Comment by kensoh** [comment]
tested ok for -

**datatable.csv**
```
#,a1,1a,_,_1,!@#$^&^*%%^?><{}|\][';,test
1,2,3,4,5,6,7
```

**tagui_local.csv**
```
object,value
a,1
a a,2
a1,3\n4
1a,3\r\n4
,123
_1,1
_,2
a~!@#$%^&*()_+{}|":?></.';\][=-z,3
~!@#$%^&*()_+{}|":?></.';\][=-,4
```

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0
