### ISSUE TITLE
Cannot use Chinese flows - update the correct tagui_config.txt, use chcp 65001

### ISSUE THREAD

**Issue by Peter-YAN** [kelaberetiv/TagUI#957]
Hi all,

I use it TagUI in China, but cannot understand chinese cmd.
The language setting is changed in C:\tagui\src\tagui_config.txt

_var tagui_language = 'chinese';_

but after TagUI started, there is error as the following.
![image](https://user-images.githubusercontent.com/11254009/109906499-94bc9100-7cdb-11eb-8d73-f49e4c350536.png)

I have installed MS plugin, I run the cmd in MS word, get the cmd cannot understand yet.
![image](https://user-images.githubusercontent.com/11254009/109907082-920e6b80-7cdc-11eb-9761-ff4c37be3389.png)

**Comment by kensoh** [comment]
Hi Peter, thanks for raising this! My colleague and I have started looking into this and will work with you to solve the problem.

There are 2 issues reported above. 1 is live mode entering Chinese characters the error. 1 is running Chinese document flow.

@ruthtxh tried running Chinese document flow but works for her. I'll check on issue 1 and we will check with you for more details on logs or some steps so that we can understand why the error happens on your computer.

**Comment by Peter-YAN** [comment]
Hi kensoh, 
Thanks for your response.
I cannot find any log files.
My TagUI version is 6.14, and I unzip it to C:\. and "**_C:\tagui\src_**" is add into system environment **_PATH_**

I also installed the latest **_[Python for RPA](https://github.com/tebelorg/RPA-Python)_**, and tagui is download to **_C:\Users\Administrator\AppData\Roaming\tagui_**,
so there are multi TagUI in my computer. is there confilct?

**Comment by Peter-YAN** [comment]
Where can i get the logs?

**Comment by Peter-YAN** [comment]
> Hi kensoh,
> Thanks for your response.
> I cannot find any log files.
> My TagUI version is 6.14, and I unzip it to C:. and "**_C:\tagui\src_**" is add into system environment **_PATH_**
> 
> I also installed the latest **_[Python for RPA](https://github.com/tebelorg/RPA-Python)_**, and tagui is download to **_C:\Users\Administrator\AppData\Roaming\tagui_**,
> so there are multi TagUI in my computer. is there confilct?

**Comment by kensoh** [comment]
Hi Peter, for RPA for Python, it auto-installs a forked version of TagUI to a separate folder, so no conflicts.

Can you try the following - 

1. create an empty file tagui\src\tagui_logging
2. run tagui command on the 8_chineseflow.tag

Does it work?
If does not work, can you attach the .log file from the flows\samples folder here? (drag and drop into reply text box)

If it works, can you try running `tagui live` again, then copy paste every line in 8_chineseflow.tag to run?

If it does not work, can you attach .log file here too?

**Comment by Peter-YAN** [comment]
Hi Kensoh,

1. I got nothing after add C:\tagui\src\tagui_logging and run tagui.

![image](https://user-images.githubusercontent.com/11254009/110052231-343c5b00-7d92-11eb-9139-cbaf4006e79c.png)
![image](https://user-images.githubusercontent.com/11254009/110052267-43bba400-7d92-11eb-8645-ccfaf2ba8903.png)

2. **There is no log file in the tagui directory.**

![image](https://user-images.githubusercontent.com/11254009/110052683-f5f36b80-7d92-11eb-925b-f430379aa503.png)

**Comment by Peter-YAN** [comment]
The last picture, tagui_windows.log, tagui_py_windows.log, tagui_r_windows, tagui_chrome.log and tagui are 0 bytes.

**Comment by kensoh** [comment]
Hi Peter, the log files will be in same folder as the flow file (tagui/flows/samples) or the folder when u run tagui live

**Comment by kensoh** [comment]
From above screenshot, it looks like for some reason, the Chinese text on your computer can't be read as Chinese text to be parsed by TagUI. Is there another laptop (own personal or company laptop or friend laptop) you can try to see if there is also the same problem?

**Comment by kensoh** [comment]
If can't try on another laptop, can you see if you can join our weekly 1-to-1 Q&A on Thursday 4pm to look at the issue together?

https://github.com/kelaberetiv/TagUI/issues/914

**Comment by Peter-YAN** [comment]
I got C:\tagui\flows\samples\8_chineseflow.tag.html, the file content as the following:

```
<!DOCTYPE html>
<html><head><link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:600' rel='stylesheet'>
<style>body {font-family: 'Source Sans Pro', sans-serif; width: 90%; margin: auto;}</style></head><body><h3>
<span style="color: rgb(30,130,201);">ERROR - [LINE 10] cannot understand step 输入 search-input 为 github
</span><br>
ERROR - [LINE 11] cannot understand step 显示 search-input
<br>
ERROR - [LINE 12] cannot understand step 点击 search-button
<br>
ERROR - [LINE 13] cannot understand step 等待 2.5秒
<br>
ERROR - [LINE 14] cannot understand step 回声 完毕
<br>
ERROR - automation aborted due to above 
<br>
</h3></body></html>
```

**Comment by Peter-YAN** [comment]
I got C:\tagui\flows\samples\8_chineseflow.tag.html, the file content as the following:

```
<!DOCTYPE html>
<html><head><link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:600' rel='stylesheet'>
<style>body {font-family: 'Source Sans Pro', sans-serif; width: 90%; margin: auto;}</style></head><body><h3>
<span style="color: rgb(30,130,201);">ERROR - [LINE 10] cannot understand step 输入 search-input 为 github
</span><br>
ERROR - [LINE 11] cannot understand step 显示 search-input
<br>
ERROR - [LINE 12] cannot understand step 点击 search-button
<br>
ERROR - [LINE 13] cannot understand step 等待 2.5秒
<br>
ERROR - [LINE 14] cannot understand step 回声 完毕
<br>
ERROR - automation aborted due to above 
<br>
</h3></body></html>
```
![image](https://user-images.githubusercontent.com/11254009/110062022-8043cb80-7da3-11eb-9eb9-5d11b35e9587.png)

**Comment by Peter-YAN** [comment]
Hi Kensoh,
the chinese flow is done, but the chinese character cannot be shown in correct.
I just run it under c:\tagui\src.
![image](https://user-images.githubusercontent.com/11254009/110073328-2bf81600-7dba-11eb-95d5-1b315fa13c9a.png)

**Comment by Peter-YAN** [comment]
[tagui_chrome.log](https://github.com/kelaberetiv/TagUI/files/6088379/tagui_chrome.log)

**Comment by Peter-YAN** [comment]
[translate.log](https://github.com/kelaberetiv/TagUI/files/6088386/translate.log)

**Comment by Peter-YAN** [comment]
Is there any special font need to install for chinese?

**Comment by kensoh** [comment]
Hi Peter, from above, I can guess what is the problem already for the unable to recognise step.

I think there could be another installation of TagUI on your computer which is in your PATH environment variable. So that when you type tagui from another directory, it is running that copy instead of the one in C:\tagui. The one in C:\tagui is the one which you change tagui_config.txt to Chinese.

Now when you run from c:\tagui\src it works because it is running the correct copy. You can double check your environment variables PATH to see which is the other copy. The Python package one does not automatically add to PATH.

For the display of Chinese characters correctly, can you see the link here and let me know if it works? If works, let me know what you do so next time I can tell other users with Chinese Windows computer.

http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/

---
Below is old v5.11 documentation for this info. We will add this back into the new documentation for next release.

>Tip - as Windows Unicode support isn't as straightforward as macOS/Linux, doing this in Windows may require changing system locale, using chcp command, and selecting a font to display native language correctly (more info)

https://github.com/kelaberetiv/TagUI/tree/pre_v6#native-languages

CC @ruthtxh fyi -

**Comment by Peter-YAN** [comment]
Yes, there is another tagui in my path. :-)
But the Chinese cannot display correctly.
![image](https://user-images.githubusercontent.com/11254009/110094055-58219000-7dd6-11eb-8065-be50473ab29a.png)

**Comment by Peter-YAN** [comment]
haha, Sloved it.
![image](https://user-images.githubusercontent.com/11254009/110095459-e9ddcd00-7dd7-11eb-834c-2f87ffc62b08.png)

**Comment by kensoh** [comment]
Oh great!! Thanks Peter for sharing the solution! Next time we know, can advise Chinese users to try `chcp 65001`

Fyi @ruthtxh both the display problem (use chcp 65001) and don't understand step problem (tagui_config.txt changed but the tagui in PATH is some other installation) solved.
