### ISSUE TITLE
MS Excel Add-in v3 Release - RPA data and parameters with Microsoft Excel - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#958]
My team-mate @ruthtxh has created an add-in to set RPA data and parameters with Excel.

Try it out and let us know! - https://github.com/kelaberetiv/TagUI/tree/master/src/office

![excel_addin](https://user-images.githubusercontent.com/10379601/110236941-0adb2500-7f74-11eb-827c-77b3f69cb1fa.png)

---

**v3 ideas to review for implementation**
- [x] text area in task pane for run output
- [x] rename setup.exe --> Setup.exe
- [x] metadata to store run options
- [x] ribbon to show/hide task pane
- [x] output back to .xlsx as new sheet
- [x] TagUI run report filtering and chart
- [x] Handle subflows and images

**Comment by jroachgit** [comment]
I noticed theres the option to install the add-in for the local user. I note that the installation path should also change to the c:\Users\<user>\AppData

**Comment by jroachgit** [comment]
Also - when running 'Setup.exe', Symantec blocks the file:

Scan type: Auto-Protect Scan
Event: Risk Found!
Security risk detected: WS.Reputation.1

**Comment by kensoh** [comment]
Congrats @ruthtxh! Finally wrap up :D

Closing issue, following is post sharing the highlights of TagUI Excel v3 compared to previous release -
https://www.linkedin.com/posts/kensoh_introducing-tagui-ms-excel-plug-in-v3-activity-6823494939909988352-E9l4
