### ISSUE TITLE
Task scheduler unable to run TagUI when disconnected from VM - pending details

### ISSUE THREAD

**Issue by lol538** [kelaberetiv/TagUI#962]
Hi Ken, really appreciate this TagUI software which help me solve a problem of sending out an email from a word document when i am not in office.

I have scheduled the VM to run the bat file during two instances: 1) When i am connected to VM. 2) When i am disconnected from VM.

1) When i am connected to VM, the task scheduler run the bat file as per expectations
2) However when i am disconnected to VM, i the task scheduler does not run the bat file.
I am not sure what is stopping the task scheduler to run the bat file as my scheduler is able to run other software even when i am disconnected as well.

Will appreciate your help if you know what is happening

**Comment by ruthtxh** [comment]
Hello @lol538 

Can I check if you used visual automation for your workflow? If you did, I suspect this could be the reason why the workflow did not run when you're disconnected from it, as the screen has to be on for TagUI to do the actions.

**Comment by kensoh** [comment]
Closing issue for now until further inputs!
