### ISSUE TITLE
Chrome white screen of death

### ISSUE THREAD

**Issue by eienkisu** [kelaberetiv/TagUI#963]
![Screenshot (4)](https://user-images.githubusercontent.com/26756159/110757389-4af91b00-8286-11eb-8f08-71c60f095cfa.png)

When i start chrome myself it is working fine, I can browse web normally, but when tagui starts chrome it's a white window, sometimes without title bar. It happen suddenly, it was ok yesterday. I run flows daily.

What I tried that didn't work: 
- Uninstall and reinstall chrome.
- delete chrome user data.

Specs:
Google Chrome is up to date Version 89.0.4389.82 (Official Build) (64-bit)
Windows 10 Home
Version	20H2
Installed on	‎28 ‎Jul ‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by ruthtxh** [comment]
Hello @eienkisu 

This is an unusual scenario. Can you paste the logs for us to take a look? The log file can be found here: tagui/src/tagui_chrome.log

Also, is this your company laptop? It could be a change in company network policy that blocks the TagUI access to chrome, which was the case for one of our users - https://github.com/kelaberetiv/TagUI/issues/921.

**Comment by eienkisu** [comment]
> Hello @eienkisu
> 
> This is an unusual scenario. Can you paste the logs for us to take a look? The log file can be found here: tagui/src/tagui_chrome.log
> 
> Also, is this your company laptop? It could be a change in company network policy that blocks the TagUI access to chrome, which was the case for one of our users - #921.


Hi Ruth

log attached. 

strange enough when using work laptop it works fine, using vpn or not. I'm a nus staff.

[tagui_chrome for 1_google.log](https://github.com/kelaberetiv/TagUI/files/6126823/tagui_chrome.for.1_google.log)

**Comment by ruthtxh** [comment]
Hello @eienkisu 

The nus laptop is slightly different from your personal laptop specs, but this shouldn't be an issue. Do you have any anti-virus software installed on the laptop? 

I've taken a quick look at the logs you attached, seems like TagUI does not throw an error upon visiting Google.com although the webpage is not responding and continues with the next step and is able to find an element with id of "q". For this sample, if I've not mistaken, TagUI would have matched the element by it's name and not id...

I also noticed another strange thing from your screenshot, the output "c:\tagui\src\tee.exe: Reading stdin..." appears twice when running the flow, which should not be the case.

My suggestion is, you may reinstall TagUI by deleting the tagui folder from your C drive, and unzipping a fresh copy. Please follow the steps at https://tagui.readthedocs.io/en/latest/setup.html.

Do let us know if the issue persists upon reinstalling. Thank you!

**Comment by eienkisu** [comment]
Hi Ruth

deleting tagui folder and reinstalling tagui works. Thanks!
________________________________

**Comment by ruthtxh** [comment]
Awesome @eienkisu! Closing this issue, have fun automating with TagUI :-)

**Comment by kensoh** [comment]
Thanks @ruthtxh ! - I've updated issue title with the solution (for this case is reinstalling)
