### ISSUE TITLE
How to pause and resume TagUI - figuring out the solution to address root cause

### ISSUE THREAD

**Issue by sheneeb** [kelaberetiv/TagUI#964]
when the cmd command starts to loop through a csv, when i use keyboard shortcut `ctrl c` i can terminate it or when i type `n` it resume, but the problem is it resumes with a new record, it does not continue, how can i pause and continue with the same record.

**Comment by kensoh** [comment]
Hi @sheneeb, from the command prompt, once [ctrl]c is pressed it will kill automation of the current record. Can you tell me more what is your usage scenario and why do you need to pause and continue? So that I can see if there is a suitable workaround to get the result you want for your usage scenario.

**Comment by sheneeb** [comment]
Hi @kensoh, i am using tagui to download files from a website using javascript fetch command on the console in chrome  browser. my input is a csv file that has a list of filenames that i am passing as filenames to the fetch command download.
after the fetch call completes it asks for a save as option and saves the file to a local folder. here since i don't know how long the fetch call takes so i put an infinite loop to check if the file is downloaded else wait 1 second. how i did this is by running cmd command to retrieve all the files in the folder and checking if the input filename matches the list of files in that folder.
Sometimes i often find that the download folder is a different folder mainly because of an earlier download to a different folder and the loop never breaks as the downloaded file is not in the folder that the cmd command is looking in,so here i could pause the tagui and copy the file to that folder and then have it continued.
the reason why i want it this way is because finally i am writing to another csv file the success for download of that file.

i hope i was able to put that across to you, let me know if you need further explanation

**Comment by kensoh** [comment]
Hi @sheneeb, this sounds like an advanced sophisticated automation scenario! The weak link here looks like the downloaded files being in a different folder. If that is indeed the problem, can you try below to override the download location? TagUI by default will download to the same folder as the flow file, by running below and using TagUI to do the download instead of JavaScript fetch() might be able to address this scenario.

```
chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'C:\\Downloads'});
dom_json = 'url_of_the_file_you_want_to_download'
dom window.location.href = dom_json
```

**Comment by sheneeb** [comment]
@kensoh thank you for that, i setup the bot without using the chrome browser that comes when the bot is running, so i am using the `-n` command in cmd and using chrome as a shortcut to load, i don't know why i went with that. 
the fetch api call is basically a cross origin fetch call so first i am login to the website and then making a call and dynamically creating a dom element and downloading it. in this case when i am not using the default browser of tagui, will the `chrome_step` work on the browser that i am opening using chrome.exe shortcut on the desktop ?

**Comment by kensoh** [comment]
Oh I see.. The chrome_step() only affects the TagUI's launched Chrome, not the one you open using shortcut, because there is no websocket connection for that Chrome instance with TagUI. I don't think from console the download location can be set.

I understand your use case now. Actually you can try invoking Chrome using the normal TagUI way, and use the dom step to do what you need to do on the Chrome browser to see if that works. https://tagui.readthedocs.io/en/latest/reference.html#dom

**Comment by kensoh** [comment]
Oh the CSV datatable file, TagUI only opens it for read-only, so you can't directly write on it.

Would it work for you if you track the records executed? For example, you can use write step to track current execution.

Or you can use below to track which run is it -
```
echo `[iteration]`
```

Alternatively, you can consider writing some JavaScript code to do it using fs module -
https://phantomjs.org/api/fs/

Or using some Python package or code to do it with the py begin and py finish -
https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

**Comment by sheneeb** [comment]
hi @kensoh , thank you that suggestion, i was able to use this
`chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: 'C:\\RPA'});`
and this
`dom begin
// do something here
dom finish`
and changed my code to use the default browser which helped me realize that i can call xpath elements directly and so this allowed me to replace all images with dom paths.

**Comment by sheneeb** [comment]
i'll explore the suggestion on csv row deletion using your suggestions.

**Comment by sheneeb** [comment]
HI @kensoh,
i have implemented the suggestion you mentioned using python for csv row deletion, but in both cases i am getting the following errors.
can you review ?

sample.csv

`name,st_dt,en_dt,filename
file1,2021-01-28,2021-01-29,file1_2021-01-28.txt
file2,2021-01-28,2021-01-29,file1_2021-01-28.txt
file3,2021-01-28,2021-01-29,file1_2021-01-28.txt
`
i am calling tagui tag like this:

`
tagui myrpa.tag sample.csv -speed
`
and this is the part of the code where i implemented it:

`
logfile_table = datatable.split('\n')
dom_json = 'url_of_the_file_you_want_to_download'
dom window.location.href = dom_json
for loop from 1 to infinity
if (status === "true")
    break
    **py begin
    filename = "`filename`"
    import pandas as pd
    df = pd.read_csv(r'C:\rpa\sample.csv', sep=',', encoding='UTF-8', engine="python")
    df = df.drop(df[df.filename.str.contains(filename)].index)
    df.to_csv(r'C:\rpa\sample.csv',mode='w+',index=False)
    py finish**
else
    wait 0.5
   run cmd /c dir \rpa\ /b
   file_list = run_result.split('\n')
   for n from 0 to file_list.length
        row = file_list[n]
        for n from 1 to logfile_table.length-1
            csvrow = logfile_table[n]
        if row equals to csvrow
            status = "true"
            break
        else
            wait 0.5
            if present('save.png')
                echo click on save
            else
                echo waiting on save image to appear
`

i am getting the following error , if i remove the lines between `py begin` and `py finish` the tagui file works without any errors.
`ERROR - number of step { does not tally with with }
ERROR - automation aborted due to above`

and the second method i tried is this 
same code but through a .py file in run command but getting this error:
`
logfile_table = datatable.split('\n')
dom_json = 'url_of_the_file_you_want_to_download'
dom window.location.href = dom_json
for loop from 1 to infinity
if (status === "true")
    break
    run python C:\rpa\delete_row.py "`filename`"
else
    wait 0.5
   run cmd /c dir \rpa\ /b
   file_list = run_result.split('\n')
   for n from 0 to file_list.length
        row = file_list[n]
        for n from 1 to logfile_table.length-1
            csvrow = logfile_table[n]
        if row equals to csvrow
            status = "true"
            break
        else
            wait 0.5
            if present('save.png')
                echo click on save
            else
                echo waiting on save image to appear
`

**Comment by sheneeb** [comment]
@kensoh i got the first step working from this issue raised [https://github.com/kelaberetiv/TagUI/issues/966](url)

**Comment by kensoh** [comment]
Hi @sheneeb on an earlier point you made on interacting with XPaths. TagUI steps can directly interact using CSS / XPaths and various HTML attributes, for eg `type //*[@name="q"] as query` or `read some_id to some_variable`. So in most cases, `dom` step is not needed to programmatically do things on the webpage, if it is only for interaction purpose.

**Comment by kensoh** [comment]
Great investigation from you to find the solution for 1, by using the latest patch in #966!

**Comment by kensoh** [comment]
For 2, the error is because run step can't automatically convert the filename variable in TagUI. Because we cannot be sure whether user is actually trying to do a variable mapping or to actually send that entire string to be run in the OS. So it is processed as it is, and will lead to error on Python side trying to open an invalid file.

A solution is to save the filename in a text file from TagUI -
```
dump `filename` to filename.txt
```

Then from Python, you read the text file to get the filename value.

This way, it will be unambiguous in handling what user provides from run step.

**Comment by sheneeb** [comment]
@kensoh thank you for that , great help for providing the solution

**Comment by kensoh** [comment]
Welcome @sheneeb let us know if you run into anything again!
