### ISSUE TITLE
Scraping URL from webpage

### ISSUE THREAD

**Issue by asishRye** [kelaberetiv/TagUI#965]
I have a particular webpage that lists out various products. When I click each product listing it opens up a new tab to show further details. 
To continue with my automation task I have used the popup function. However the links are dynamic for each new tab. I can scrape those from the main product listing page. How can I collect all the href tags and it's values in TagUI. I didn't find any help in the docs. I was hoping to use some web scraping tools in .tag file //as JS code. Is this the right way to go or are there any alternatives?

**Comment by ruthtxh** [comment]
Hello @asishRye 

Here's a quick sample on how to collect the href text for top 5 apple products on Shopee, push the text into an array and subsequently visit the links.

```
https://shopee.sg/search?keyword=apple
list = []
for i from 1 to 5
	read //*[@class="row shopee-search-item-result__items"]/div[`i`]/a/@href to url
	js list.push(url)
for i from 0 to 4
	js url = list[i]
	https://shopee.sg`url`
```

Hope this helps!

**Comment by asishRye** [comment]
yes this is perfect, thanks @ruthtxh for the help.
