### ISSUE TITLE
ERROR - number of step { does not tally with with }, nested code blocks bug - fixed

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#966]
hello the error is occurring: **ERROR - number of step {does not tally with with}**
this is part of my code:
```
total = count('//*[@class="mr9 "]')
dump Data,PDF to file.csv
if total greater than or equals to 1
  for n from 1 to total
    click (//*[@class="mr9 "])[`n`]
    wait 5
    read (//tr[@class="expansive"]//td[4])[`n`] to data
    click (//*[@class="mr9 "]/..//*[@class="noClick"]//input[`n`])[3]
    wait 5
    popup saveAsFile.jsf
      click PDF.png
      wait 5
      keyboard [ctrl]w
    py begin
    import glob
    print(glob.glob("/home/rpa/Downloads/tagui/flows/samples/*.PDF")[0])
    py finish
    wait 1
    line = [data, py_result]
    write `csv_row(line)` to file.csv
wait 5
dom window.history.back()
```

**Comment by kensoh** [comment]
Hi Marcelo! I can replicate. When I remove the block of code `py begin .. py finish` it works. Will check more.

**Comment by kensoh** [comment]
While figuring out more on this, can you try below to see if it works for you?

Below block can be runnable by me, the change I made is use py step directly instead of py begin and finish.

```
total = count('//*[@class="mr9 "]')
dump Data,PDF to file.csv
if total greater than or equals to 1
  for n from 1 to total
    click (//*[@class="mr9 "])[`n`]
    wait 5
    read (//tr[@class="expansive"]//td[4])[`n`] to data
    click (//*[@class="mr9 "]/..//*[@class="noClick"]//input[`n`])[3]
    wait 5
    popup saveAsFile.jsf
      click PDF.png
      wait 5
      keyboard [ctrl]w
    py import glob
    py print(glob.glob("/home/rpa/Downloads/tagui/flows/samples/*.PDF")[0])
    wait 1
    line = [data, py_result]
    write `csv_row(line)` to file.csv
wait 5
dom window.history.back()
```

**Comment by marcelocecin** [comment]
hi @kensoh it worked !
would there be another more practical way to search for the path of the last downloaded file?
thanks !

**Comment by kensoh** [comment]
Hi Marcelo, if you meant just the folder name, it would be in the `flow_path` variable. If you want the full filename you can try something like below using run step to use the OS commands to return what you need.

**for windows**
```
run cmd /c dir parameters *.PDF
echo `run_result`
```

**for macos/linux**
```
run ls parameters *.PDF
echo `run_result`
```

Note that the working folder for run step is in tagui/src folder.

**Comment by marcelocecin** [comment]
Hi Ken
here my code
```
    py import glob, os
    py list_of_files = glob.glob("/home/rpa/Downloads/tagui/flows/samples/*.PDF")
    py latest_file = max(list_of_files, key=os.path.getctime)
    py print(latest_file)
```
thanks

**Comment by kensoh** [comment]
Using Python seems like the most straightforward haha.

TagUI has the `fs` module inherited from PhantomJS, but the list() does not sort by file date -
https://phantomjs.org/api/fs/method/list.html

Following on mac will return the filename of the latest file created. But I'll prefer the Python method than this.
```
run ls -lt
echo `run_result.split('\n')[1].split(' ')[run_result.split('\n')[1].split(' ').length-1]
```

**Comment by kensoh** [comment]
Above commit seems to solve the problem by handling nested code blocks correctly. You can download the latest copy of TagUI with this fix and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this fix will become part of the packaged zip files. Thanks Marcelo for spotting and reporting this bug!!

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0
