### ISSUE TITLE
Google Colab TagUI on the cloud update on Ubuntu package manager - done

### ISSUE THREAD

**Issue by TetraGenius** [kelaberetiv/TagUI#970]
When running the second line:
run sample GitHub workflow showing license for TagUI project and downloading source code
!tagui/src/tagui https://raw.githubusercontent.com/kelaberetiv/TagUI/master/flows/samples/2_github.tag -headless

This error results:
"chrome browser not found" 

To fix, add to the first line the **code: apt-get update**:
setup RPA environment by installing PHP, Chromium web browser and TagUI Linux version
!**apt- get update;** apt install php;  apt install chromium-browser; wget https://github.com/kelaberetiv/TagUI/releases/download/v6.14.0/TagUI_Linux.zip; unzip TagUI_Linux.zip; cd tagui/src; wget -O tagui https://gist.githubusercontent.com/kensoh/b12a350513268df5456165180dbee6a6/raw/0947f8d53d5744eb7c51ba0a06448fc8b33b06ab/tagui

Then re-run the line:
run sample GitHub workflow showing license for TagUI project and downloading source code
!tagui/src/tagui https://raw.githubusercontent.com/kelaberetiv/TagUI/master/flows/samples/2_github.tag -headless

**Comment by TetraGenius** [comment]
Ken, maybe update your colab with: apt-get update ? In your first line of code.

**Comment by kensoh** [comment]
Thanks @TetraGenius for spotting this and sharing your solution!

Yes it looks like somehow the Ubuntu package manager has become outdated and break the notebook. I've added your update to the Colab notebook and it works now. Thank you very much for letting us know and sharing this! 😄🎉

(tagging https://github.com/kelaberetiv/TagUI/issues/913)

**Comment by TetraGenius** [comment]
Pleasure; trying to give back a bit since tagui is giving so much to open source! (you know me on LinkedIn as Theuns Dirkse-van Schalkwyk)

**Comment by kensoh** [comment]
Hi Theuns Dirkse!! I saw your messages but I haven't got to reply my messages yet.

Thanks you so much again for spotting this quickly and suggesting the fix! 😄

I've just set up an optional Telegram for use as TagUI RPA community group chat. Feel free to join if you are using Telegram and would like to take a look. I think that might be the future of TagUI user community - https://t.me/rpa_chat
