### ISSUE TITLE
 Passing variables to R r_step(): 1234567 works but ABCDEFG does not 

### ISSUE THREAD

**Issue by TetraGenius** [kelaberetiv/TagUI#974]
This code:
```
phone = 1234567
r_step('phone = ' + phone)
r print(phone)
echo `r_result`
```
from Release 6.14.0 Doc of Mar 17, 2021: https://tagui.readthedocs.io/_/downloads/en/latest/pdf/ 
works as intended in R as well. But can I pass 'ABCDEFG' strings as well? 
```
phone = 'ABCDEFG'
r_step('phone = ' + phone)
r print(phone)
echo `r_result`
```
When I tried, the browser opens and then hangs with output in the terminal:
START - automation started - Thu Mar 18 2021 10:32:50 GMT+0200 (SAST)

I want to use this to create directories, or can that be done simpler directly in tagui?

**Comment by TetraGenius** [comment]
I've tried the following code from the release document above:
`run cmd /c mkdir 'abcd'`
gives error:
yntaxError: Expected token ')'

  phantomjs://code/6.14R.tag.js:1474 in injectJs
  phantomjs://code/bootstrap.js:456

```
myDir = 'abc'
run cmd mkdir myDir
```
gives:
START - automation started - Thu Mar 18 2021 10:55:14 GMT+0200 (SAST)

run cmd mkdir myDir
and hangs.

**Comment by TetraGenius** [comment]
I'm opening a new issue for the question:
`run cmd /c mkdir abcdefg`
that hangs after displaying:
START - automation started - Thu Mar 18 2021 11:16:36 GMT+0200 (SAST)

run cmd /c mkdir abcdefg

**Comment by TetraGenius** [comment]
This worked from your previous solution I just saw: https://github.com/kelaberetiv/TagUI/issues/947
s1 = "abc"
r_step('s = "' + s1 + '"')
r begin
print(s)
r finish
echo `r_result`

**Comment by kensoh** [comment]
Hi Theuns!

For your question here, https://github.com/kelaberetiv/TagUI/issues/974#issue-834526580

It is because for strings you'll probably need to enclose with double quotes ""

```
letters = 'ABCDEFG'
r_step('letters = "' + letters + '"')
r print(letters)
echo `r_result`
```

I know this is very un-user-friendly, but so far I find using r_step() the best way to send what the user intends to R accurately. If special parsing is done to the input (for eg automatically parsing backticks `), then user can't control 100%.

**Comment by kensoh** [comment]
For https://github.com/kelaberetiv/TagUI/issues/974#issuecomment-801762214,

Is this still an issue? The folder where run step happens in tagui\src folder.

Your syntax looks right. You can try running that same command from command prompt in tagui\src folder and see.

**Comment by kensoh** [comment]
Oh ya, yes that's the solution to pass strings over to R - https://github.com/kelaberetiv/TagUI/issues/974#issuecomment-801801644

There are other ways of passing data, for eg you can write to a file from TagUI and read it from R. Data passed could be something simple like a string or CSV data or JSON string (an array of different data and types).

**Comment by kensoh** [comment]
Oh saw your new open issue https://github.com/kelaberetiv/TagUI/issues/975 will follow-up there!
