### ISSUE TITLE
run cmd /c mkdir not working as expected - can't replicate pending more details

### ISSUE THREAD

**Issue by TetraGenius** [kelaberetiv/TagUI#975]
Fedora 33 with normal tagui examples working:
Running the code from Release 6.14.0 Doc of Mar 17, 2021: https://tagui.readthedocs.io/_/downloads/en/latest/pdf/ :
`run cmd /c mkdir abcdefg`
hangs after displaying:
START - automation started - Thu Mar 18 2021 11:16:36 GMT+0200 (SAST)

run cmd /c mkdir abcdefg

and does not create a directory (have to exit with Ctrl~z)

**Comment by TetraGenius** [comment]
Using:
`run cmd mkdir abcdefg`
hangs after displaying:
START - automation started - Thu Mar 18 2021 11:23:04 GMT+0200 (SAST)

run cmd mkdir abcdefg

and does not create a directory (have to exit with Ctrl~z)

**Comment by TetraGenius** [comment]
I managed to create directories using tagui and R dir.create()
Will post the code later.

**Comment by kensoh** [comment]
Hi Theuns, an idea I thought you can try is this. The `run` step runs commands that are available in the command line.

For many DOS commands there are not actually real .exe files to be run but part of cmd.exe command. Maybe mkdir is not part of cmd.exe but a separate mkdir.exe command. Can you try if the following works?

```
run mkdir abcdefg
```

If it does not work, can you try if from your command prompt, go to tagui\src folder,
and type `mkdir abcdefg` or `cmd /c mkdir abcdefg`

**Comment by kensoh** [comment]
I just managed to get a Windows laptop to test. The following script will run ok and create a `abc` folder in `tagui\src`

```
run cmd /c mkdir abc
```

So maybe something to do with folder permissions. Or you can try run command prompt as Administrator to see if it helps.
