### ISSUE TITLE
snap command not working very well - here's how to snap beyond what's on screen

### ISSUE THREAD

**Issue by marcelocecin** [kelaberetiv/TagUI#976]
hi
snap command not working very well
the image is cropped, not capturing the entire table
```
https://en.wikipedia.org/wiki/COVID-19_pandemic_death_rates_by_country
click //*[@id="mw-content-text"]/div[1]/table[2]/thead/tr/th[4]
snap //*[@id="mw-content-text"]/div[1]/table[2] to covid19.png
```
![covid19](https://user-images.githubusercontent.com/2955762/111614129-01488d00-87be-11eb-80f7-8cdbee4b30ac.png)

**Comment by kensoh** [comment]
Oh Marcelo, this is the expected behaviour. In this case, you are trying to capture an entire snapshot of the whole table. But the whole table actually is not rendered and shown in Chrome browser because it overflows. Let me see what is the best way for this scenario.

**Comment by kensoh** [comment]
I think we have a possible solution here. Are you able to run TagUI in headless mode for your use case?

If yes, change your config in tagui\src\tagui_config.txt and increase the height to a level you want.

Make it so long such that in headless mode the browser is super long. In normal mode it is limited by screen size.

When I run the same workflow with -headless or -h option and height 7680, I get below output file. Now more can be captured, but 7680 is still not enough. You'll probably choose some super large number that is more than enough for your scenario.

![covid19](https://user-images.githubusercontent.com/10379601/111742508-460a1c00-88c3-11eb-8858-fcd0c4ae0a4c.png)

**Comment by kensoh** [comment]
Also, adding on, in headless mode you can do a `snap page to webpage.pdf` to capture page to PDF

(using an inherent Chrome function that works only in headless mode)

**Comment by marcelocecin** [comment]
hi Ken
sorry for the delay in the response
running headless and changing the height to 10622 it worked saving the png
thanks

**Comment by kensoh** [comment]
No probs Marcelo, thanks for replying back!
