### ISSUE TITLE
TagUI stuck on read step using OCR on Linux thru VNC - pending log details

### ISSUE THREAD

**Issue by ftruzzi** [kelaberetiv/TagUI#979]
Hi!

I'm trying to get TagUI up and running but it's getting stuck indefinitely every time I try to run a read command (or anything using OCR?) I don't care about browser automation, but I need visual OCR desktop automation.

I'm running it inside docker with VNC and have followed the SikuliX setup guide (opencv + tesseract).

I see no errors or debug messages -- how do I investigate this further?

```
app@8499c0ce2f2e:~$ tagui live -n -debug

START - automation started - Fri Mar 19 2021 22:53:46 GMT+0000 (UTC)
[info] [phantom] Starting...
[info] [phantom] Running suite: 4 steps
[debug] [phantom] opening url: about:blank, HTTP GET
[debug] [phantom] url changed to ""
[debug] [phantom] Successfully injected Casper client-side utilities

[info] [phantom] Step anonymous 2/4: done in 79ms.
LIVE MODE - type done to quit
read (0,0)-(1024,768) to test_var

```

Thanks :)

**Comment by kensoh** [comment]
Hi Francesco! Can you try the following and paste the contents in tagui/src/tagui.sikuli/tagui.log here?

read page to ocr_text

**Comment by ftruzzi** [comment]
Hi, thanks for your quick reply. Here's the log:

```
app@8499c0ce2f2e:~/tagui/src/tagui.sikuli$ cat tagui.log

(process:641): Gtk-WARNING **: 09:50:19.604: Locale not supported by C library.
        Using the fallback 'C' locale.
[debug] RunTime:temp folder ok: /tmp/Sikulix_628902113
Options: *** options dump
Options: testing =
Options: OptionsFile = /app/.Sikulix/SikulixStore/SikulixOptions.txt
Options: *** options dump end
***** show environment for 2.0.5 API
user.home: /app
work dir: /app/tagui/src
running on Linux 4.19.104-microsoft-standard from a jar
running Java Debian 11.0.9.1+1-post-Debian-1deb10u2
java.io.tmpdir: /tmp
app data folder: /app/.Sikulix
executing jar: /app/tagui/src/sikulix/sikulix.jar
*** classpath dump sikulix
  0: /app/tagui/src/sikulix/sikulix.jar
  1: sikulix/sikulix.jar
*** classpath dump end
***** show environment end
[10218 debug] Runner: added: Jython [py] text/jython
[10222 debug] Runner: added: SikulixJar [jar] text/jar
[10232 debug] Runner: init: class org.sikuli.script.runners.AbstractLocalFileScriptRunner: warning: not possible
[10234 debug] Runner: added: Robot [robot] text/robot
[10235 debug] Runner: added: NetworkRunner [] NET
[10236 debug] Runner: added: Text [txt] text/text
[10236 debug] Runner: added: Sikulix [] directory/sikulix
[10237 debug] Runner: added: PackedSikulix [zip] application/zip
[10238 debug] Runner: added: SikulixExecutableJar [executablejar] text/jar
[10240 debug] Runner: added: PackedSikulix [skl] text/skl
[10257 debug] RunTime:loadlib: trying JXGrabKey
[10284 debug] RunTime:libsExport: folder has wrong content: /app/.Sikulix/SikulixLibs
[11638 debug] RunTime:libsExport: folder created: /app/.Sikulix/SikulixLibs (2.0.5 - 202103030910)
[11690 debug] RunTime:loadLib: libJXGrabKey.so (success)
[11874 debug] HotkeyManager: add Abort Hotkey: ALT+SHIFT C (67, 9)
[11994 debug] Runner: runscript: running script: /app/tagui/src/tagui.sikuli/tagui.py
[11999 debug] JythonRunner: starting initialization
[12144 debug] RunTime:resourceLocation: (class org.sikuli.script.support.RunTime) /Lib
[12148 debug] RunTime:resourceList: having jar: jar:file:/app/tagui/src/sikulix/sikulix.jar!/Lib
[23470 debug] RunTime:files exported: 1190 from: Lib to:
 /app/.Sikulix/Lib
[28726 debug] Jython: added as Jython::sys.path[0]:
/app/.Sikulix/Lib/site-packages
[28743 debug] Jython: ***** sys.path
 0: /app/.Sikulix/Lib/site-packages
 1: /app/.Sikulix/Lib
 2: /app/tagui/src/sikulix/Lib
 3: /app/tagui/src/sikulix/sikulix.jar/Lib
[29404 debug] JythonRunner: ready: version 2.7.2
[debug] ImagePath: new BundlePath: /app/tagui/src/tagui.sikuli
[debug] Jython: SikulixForJython: init: starting
[debug] Jython: added as Jython::sys.path[0]:
/app/.Sikulix/Lib/site-packages
[debug] Jython: SikulixForJython: init: success
[debug] Jython: sikuli: Sikuli: starting init
[debug] Screen: initScreens: starting
[debug] Screen: Accessing: GraphicsEnvironment.getLocalGraphicsEnvironment()
[debug] Screen: Accessing: GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()
[debug] Screen: ScreenDevice 0 has (0,0) --- will be primary Screen(0)
[debug] Screen: Monitor 0: (0, 0) 1024 x 768
[debug] Screen: initScreens: monitor mouse check
[debug] Screen: *** checking: R[0,0 1024x768]@S(0) center: (512, 384) --- OK
[debug] Screen: initScreens: ending
[debug] Jython: use as default region: R[0,0 1024x768]@S(0)
[debug] Image: BufferedImage: (1024, 768)
[debug] Jython: sikuli: Sikuli: ending init
[debug] Jython: use as default region: R[0,0 1024x768]@S(0)
[debug] Image: BufferedImage: (1024, 768)
[tagui] START  - listening for inputs

app@8499c0ce2f2e:~/tagui/src/tagui.sikuli$
```

**Comment by kensoh** [comment]
Hi Francesco, from your logs it seems like a more verbose debug output from SikuliX, but it looks like stuck at the listening for inputs step. Can you try running the following and share with me the same tagui.log output? Sorry I think because I miss out the .png and it didn't route correctly over to SikuliX.

```
read page.png to ocr_text
```

Hopefully we can get more clues from there. Because I don't have a similar Linux environment to replicate the issue, in some cases we can get the best troubleshooting if we meet on a call to figure out. Let's see if there is more clues from running above, if not we have a weekly Zoom 1-to-1 meeting to work through with users on issues. It is every Thursday 9am your time. We'll meet each user privately in the breakout room, before going through issues with another user.

This is the Zoom meeting URL - https://github.com/kelaberetiv/TagUI/issues/914

**Comment by kensoh** [comment]
For my macOS, doing a `read page.png to ocr_text` gives the following tagui/src/tagui.sikuli/tagui.log

```
[tagui] START  - listening for inputs
  
[tagui] INPUT  - [1] read /Users/kensoh/Desktop/page.png to ocr_text
[tagui] ACTION - read /Users/kensoh/Desktop/page.png to ocr_text
[tagui] OUTPUT - [1] SUCCESS

[tagui] FINISH - stopped listening
IDE terminated: returned: 0
```

**Comment by ftruzzi** [comment]
Thank you for your kind and detailed reply!

I had [this error](https://answers.launchpad.net/sikuli/+question/676733) and I was able to make everything work by doing the following:

Download newer SikulixAPI:

```
wget https://launchpad.net/sikuli/sikulix/2.0.4/+download/sikulixapi-2.0.4.jar -O tagui/src/sikulix/sikulix.jar
```

Update tesseract 4.0 (default in debian buster) to 4.1:
```
echo "deb https://notesalexp.org/tesseract-ocr/buster/ buster main" >> /etc/apt/sources.list
wget -O - https://notesalexp.org/debian/alexp_key.asc | sudo apt-key add -
sudo apt-get update && sudo apt install tesseract-ocr
```

Maybe the installation instructions should be updated? I followed https://sikulix-2014.readthedocs.io/en/latest/newslinux.html and it says `It must be a version 4.x` but could it be 4.1?

Thanks!

**Comment by kensoh** [comment]
Oh perfect, thanks for updating back here your solution!

I see, in the next release, we'll be reviewing if the latest SikuliX engine works well with TagUI and then package it together. If I remember correctly, the latest SikuliX has some dependency that needs to be installed separately for even Windows and macOS, that's why it is a hard decision to upgrade since there will be extra work for most users with little gains.

Will check more. Closing this issue for now and keeping the issue on SikuliX upgrade open - https://github.com/kelaberetiv/TagUI/issues/928

I believe v4.1 should be ok but I'm not the best person to advise on SikuliX lol...

**Comment by kensoh** [comment]
Please do continue to ping me here if you run into anything related to this topic :)
