### ISSUE TITLE
Add dictionary for Malayalam language - updated Google Translate build robot - done

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#986]

**Comment by nived00015** [comment]
Hi ken,

i am not bale run the tagui program in malayalam 
see the tag file  in the zip file below

[fp.zip](https://github.com/kelaberetiv/TagUI/files/6206831/fp.zip)

Regards,
Nived N

**Comment by kensoh** [comment]
To use non-English language, set language in tagui/src/tagui_config.txt then it will recognise the steps.

**Comment by kensoh** [comment]
Also, as Windows Unicode support isn't as straightforward as macOS/Linux, showing other language in Windows may require changing system locale, using chcp command, and selecting a font to display native language correctly. I'll paste a link below.

**Comment by kensoh** [comment]
http://www.walkernews.net/2013/05/19/how-to-get-windows-command-prompt-displays-chinese-characters/

**Comment by kensoh** [comment]
Above is an example to show Chinese characters. But first, you change tagui_config.txt to work first.

**Comment by nived00015** [comment]
Hi ken it shows like this 
![image](https://user-images.githubusercontent.com/64367090/112521936-11b2c600-8dc3-11eb-9854-3778d9ac12b6.png)

after adding all langauge details to config

**Comment by kensoh** [comment]
Hi Nived, can you try changing back your changes and see if it works? Your previous screenshot in Telegram already showing that PHP is running ok, that's why it can say step not recognised. I'm guessing that other changes have been made that's why this new error appears.

The change that is needed is only in tagui\src\tagui_config.txt change below line
```
var tagui_language = 'english';
```

to the following
```
var tagui_language = 'malayalam';
```

That change shouldn't create the error on php not recognised

**Comment by kensoh** [comment]
@nived00015 added an `ask` dictionary step. But I'll need to add ask step into the translation engine first to work.

**Comment by kensoh** [comment]
Done!

**Comment by kensoh** [comment]
Closing issue, change included in latest packaged release - https://github.com/kelaberetiv/TagUI/releases/tag/v6.46.0
