### ISSUE TITLE
Autorun end_processes before running automation to kill dead processes? - drop

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#998]
also, explore clean up at the end of each run

**Comment by steewel** [comment]
So will need to make end_processes kill an individual automation, because if you ran simultaneous automations, end_processes will kill them all

**Comment by kensoh** [comment]
After thinking through, should be a better idea to drop. Including this to be run every time will make it no longer a choice for users to kill all existing dead processes. By telling users about this command they can decide whether to run it or not.

Also, for Microsoft Word plug-in this will be automatically run anyway, because the assumption for the user demographic are people who don't use command prompts and not tech-savvy. Doing on their behalf by default saves their trouble.

Copying @ruthtxh

**Comment by kensoh** [comment]
Also, if implemented this will have downstream impacts on other apps and versions of TagUI like C# and Java.

For RPA for Python, it is ok because I maintain a separated fork of TagUI meant to work best for Python package.
